### ISSUE TITLE
Strange scroll behaviour on IOS 8 Chrome 40.0.2214.69

### ISSUE THREAD

**Issue by since1976** [metafizzy/flickity#10]
I am experiencing some strange scrolling behaviour in Chrome 40.0.2214.69 on IOS, specifically on the freescroll examples of the demo. 
When scrolling from either direction the gallery will sometimes disappear altogether and then reappears a second later at a different cell location. Also on occasion it will just jump straight to the last cell. This all seems to happen when scrolling quickly but isn't specifically just a quick scrolling problem.

I have tested same instances—local install and on your demo—in safari and it works smooth and flawlessly in that browser.

**Comment by desandro** [comment]
Thanks for reporting this issue! I've tried flicking around a bit on Chrome 40 for iOS and I haven't been able to reproduce this issue. Every now and then I do catch a weird skipping behavior. But it's hard to pin down. I'll keep this ticket open 

---

Thanks you for this feedback. [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), please email me yo@metafizzy so I can send some your way.

**Comment by desandro** [comment]
Closing as non-reproducible.
