### ISSUE TITLE
Define a speed autoplay with playPlayer

### ISSUE THREAD

**Issue by CM-Webdesign** [metafizzy/flickity#1000]
I would like to set `autoPlay: false` on beginning and use a button to start the carousel.
But how I can define a speed autoplay in this case ?

```
$carousel.flickity({
   autoPlay: false
});
$button.click(function(){
   $carousel.flickity('playPlayer');
});
```

**Comment by XPOL555** [comment]
@CM-Webdesign you can do the reverse and using the [pause](https://flickity.metafizzy.co/api.html#pauseplayer)/[unpause](https://flickity.metafizzy.co/api.html#unpauseplayer) and pausing immediatly after init.

```javascript
$carousel.flickity({
   autoPlay: 1500
});
$carousel.flickity('pausePlayer');
$button.click(function(){
   $carousel.flickity('unpausePlayer');
});
```

**Comment by CM-Webdesign** [comment]
Oh yeah, you right. Thank you !
