### ISSUE TITLE
Suggestion: add option for continousScrolling

### ISSUE THREAD

**Issue by noftaly** [metafizzy/flickity#1006]
Hi!
I was looking for a library to help me making a little image carousel, with autoplaying. I was not satisfied with bootstrap's one, and a friend told me about Flickity. I wanted to have a carousel that autoplays, without arrows, without dots, and most importantly that does not pause on each slide. I managed to get really close to what I wanted with free scroll, autoplay, draggable, etc, but unfortunately, afaik, Flickity does not support "not pausing on each slide".

So this is my suggestion: add an option like `pauseOnSlides: boolean` or `continousScrolling: boolean` or something like that.

What do you think of it ? is it doable and will it be added?
Thanks!
(Sorry for my English ^^)

**Comment by P2284912693** [comment]
> but unfortunately, afaik, Flickity does not support "not pausing on each slide"

{"autoPlay": 3000} will make all the slides pause for 3 seconds. I don't understand what you need exactly, please include a [reduced test case ](https://codepen.io/desandro/pen/azqbop)

[Read Guidelines here](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md)

**Comment by desandro** [comment]
See solutions in #77
