### ISSUE TITLE
CSS / JS blocked

### ISSUE THREAD

**Issue by chanjingxiong** [metafizzy/flickity#1008]
Code was working fine till all of the sudden we have the CSS & JS blocked. Checked console and here's the error: 

The resource from “https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js?ver=dist” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)

Could you advise we should do?

**Comment by desandro** [comment]
Thanks for reporting this issue. I believe this issue has been resolved.
