### ISSUE TITLE
iOS13.3 PrevNext Buttons change z-index when swiping

### ISSUE THREAD

**Issue by charlesr1971** [metafizzy/flickity#1013]
iPhone 8+ iOS13.3 Safari: PrevNext Buttons change z-index when swiping  

When I use wrapAround = true, pageDots = false, the z-index of the previous/next buttons changes whenever I swipe left or right. The result is that the buttons hide behind the slides temporarily. This creates a choppy visual effect as the buttons appear & disappear.

**Comment by fantasticmachine** [comment]
Was this fixed, or ignored?
