### ISSUE TITLE
Use custom handle with PlainDraggable item

### ISSUE THREAD

**Issue by yepecece** [metafizzy/flickity#1014]
Hi, I am trying to use a custom handle that has a drag event drag item created with PlainDraggable (https://anseki.github.io/plain-draggable/). Do you have an idea as how I could bind the drag of the slider with the drag of the item?

Here is a basic slider with a custom handle and the draggable item.
https://jsfiddle.net/1unbwmja/10/

Thanks

**Comment by desandro** [comment]
Sorry, Flickity does not provide a straightforward API to manually set the position.
