### ISSUE TITLE
When in Viewport on Scroll, Add Class to Element

### ISSUE THREAD

**Issue by abaney** [metafizzy/flickity#1017]
I'd like to add a class (ultimately an animation) to an element right when it comes into the viewport within a Flickity carousel. I can make this work outside of a Flickity carousel, however, when applying this within a Flickity carousel, it does nothing.

Below are links to 2 Codepens: 1) with the "when in viewport" jQuery, and 2) with this jQuery applied to an element that lives within a Flickity carousel.

Codepen 1 ("When in Viewport"):
https://codepen.io/adambaney/pen/ZEYdqXR

Codepen 2 ("When in Viewport" with Flickity carousel):
https://codepen.io/adambaney/pen/qBEzJGE

Any idea how to accomplish this? I have a project due within the next 7 days. If this can't be done by then, I'll just have to do without. Would make the experience much more rich and interactive!

Thank you!

**Comment by clarknelson** [comment]
It's a bit past the 7 days, but I really enjoy using this plugin for "Scroll into window" functionality
https://github.com/russellgoldenberg/scrollama

**Comment by abaney** [comment]
@clarknelson - Thank you for your response. The Scrollama looks really cool! Could possibly use it on a future project.

I wound up not using Flickity for this project, and went with a dot navigation instead, like this: https://codepen.io/Rueb/pen/WabbEo
