### ISSUE TITLE
Some progressBar

### ISSUE THREAD

**Issue by Rad1calDreamer** [metafizzy/flickity#102]
HI!
Thanks for pretty good plugin!
Can you add progressBar option looks like this http://codepen.io/anon/pen/bNJBMo.
And i have some comments for this pen https://gist.github.com/Rad1calDreamer/075e6e942817fa520d0d

**Comment by desandro** [comment]
Thank you for this feature request. I'm closing this issue as it did not get much public interest :watermelon:
