### ISSUE TITLE
IOS 13.3.1v : No Smoothness while Dragging the next slide in IOS 13.3.1 version

### ISSUE THREAD

**Issue by syedazampasha** [metafizzy/flickity#1020]
**Test case:** https://codepen.io/syedazam/pen/rNaQWLy

Hi There, 

I have purchased a Flickity Licence recently and i have integrated with my website, which is working fine in all the browsers & devices except **Apple NEWLY RELEASED Version IOS 13.3. 1**. 

Request you help on this ASAP. 

Thanks !!

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry, I am not able to reproduce this issue. Please follow up if I should take another look.
