### ISSUE TITLE
Center slide on select ( active ), exactly that asNavFor does but in a normal slider.

### ISSUE THREAD

**Issue by zzseba78** [metafizzy/flickity#1024]
Is there a way to center selected slide, just like asNavFor does, but in a single slider?
Because the slider act as navigation that loads with ajax some content.
Thanks!

**Comment by clarknelson** [comment]
Have you tried this option: https://flickity.metafizzy.co/options.html#cellalign

**Comment by zzseba78** [comment]
Thanks for your response! yes, but this is for center the slider items, i need to center the item when clicked ( active ), just like asNavFor navigation does.

**Comment by clarknelson** [comment]
It should center as you desire, make sure the slides are not 100% width, but a natural width based on their content

**Comment by zzseba78** [comment]
Center the slider is not what i need, i need to center the active item when is selected.

**Comment by clarknelson** [comment]
Do you have a live example? I believe "cellAlign" will add this functionality. The active slide should be centered in the gallery.

**Comment by zzseba78** [comment]
@clarknelson Hi! No it doesn´t, it just center align items.
https://flickity.metafizzy.co/options.html#cellalign

**Comment by clarknelson** [comment]
Isn't this what you are looking for?

![image](https://user-images.githubusercontent.com/4106671/76106424-6c9d3380-5f9c-11ea-9e71-3466d1920247.png)

**Comment by zzseba78** [comment]
No, i need to center the clicked slider item, just like asnav does.

**Comment by clarknelson** [comment]
Are you using isNavFor? Did you see that it requires an extra package if you are not using the bundled version. Can see more configuration options in this repo:  https://github.com/metafizzy/flickity-as-nav-for

**Comment by zzseba78** [comment]
Hi @clarknelson ! I want the same behavior as isNavFor ( i mean, each time you click the item, item is centered in slider ), but is not a sub nav, is just one slider that loads ajax content.

**Comment by nickersonm** [comment]
@zzseba78 Do you mean centering an item that is to the side when it is clicked?  This should do it:
```
flkty.on( 'staticClick', function( event, pointer, cellElement, cellIndex ) {
    if ( !cellElement ) {
        return;
    }
    flkty.selectCell(cellElement, false, false);
});
```
