### ISSUE TITLE
initialIndex option not working with React Hooks

### ISSUE THREAD

**Issue by codeithuman** [metafizzy/flickity#1025]
**Test case:** https://codesandbox.io/s/brave-sound-xnjm9?fontsize=14&hidenavigation=1&theme=dark

As you'll see in the Code Sandbox, in `FlickityCarousel.js`, we are passing options into a new Flickity instance. Some options work, while the `initialIndex` option does not work. 

Is there something we're doing wrong or is this a bug? We are using Flickity with React and the new React Hooks API. 

I see that this example is working, but is not using Flickity as an NPM package or with React, https://codepen.io/desandro/pen/2d56398416e1fef1b409863e47e79cc3/

Thanks in advance for any and all help!

**Comment by codeithuman** [comment]
It would appear that `initialIndex` is working with the npm package `react-flickity-component`. Looks like they implement Flickity as a Class Component instead of with Hooks, https://github.com/theolampert/react-flickity-component/blob/master/src/index.js.

**Comment by codeithuman** [comment]
Well, `initialIndex` is working here now, https://codesandbox.io/s/react-flickity-5gk0u?fontsize=14&hidenavigation=1&theme=dark. But setting state inside of Hooks does not work now.

**Comment by iou90** [comment]
``` javascript
useEffect(() => {
    flickity.current = new Flickity(flickityNode.current, options || {});
    const { initialIndex } = options;
    flickity.current.selectedIndex = initialIndex || 0;
    setFlickityReady(true);
    return () => flickity.current.destroy();
  }, [options]);
`

Set selectedIndex from options manually may resolve the problem.
