### ISSUE TITLE
Current slide / total number of slides at CSS (no JS)

### ISSUE THREAD

**Issue by grimcap** [metafizzy/flickity#1026]
Hey!
I think that way of slide counter can go to doc section
https://codepen.io/grimcap/pen/XWbdjWa

**Comment by clarknelson** [comment]
This is an elegant solution, thank you for sharing. Where does the `carousel-cell` value come from?

**Comment by grimcap** [comment]
>Where does the carousel-cell value come from?
.carousel-cell {
  **counter-increment**: anyValue;
}

**Comment by clarknelson** [comment]
All I see is this: 

```
.carousel-cell {
  counter-increment: carousel-cell;
}
```

so it's calling itself?

**Comment by grimcap** [comment]
Yep, it's magic

**Comment by desandro** [comment]
Thanks so much for sharing this! I've added this [CodePen to Extra Demos](https://flickity.metafizzy.co/extras.html#extra-demos)

Get in touch yo@metafizzy.co so I can send you some stickers as a thank you 🐻🌈
