### ISSUE TITLE
Fade option with true crossfade

### ISSUE THREAD

**Issue by stubear** [metafizzy/flickity#103]
I'm in the middle of implementing Flickity on my site and I discovered an instance where it would be nice to be able to have a fade transition instead of a scroll. I know the focus is mostly on the touch enabled swipe but fade transitions can still work with a swipe of the finger. If you do implement this feature, please, please, please use a true crossfade where the top image fades away to reveal the image beneath instead of the typical scenario where the images both fade out and at one point are both 50% opaque.

**Comment by desandro** [comment]
Thanks for the feature request! I've considered this feature over in #26 and have decided it is outside Flickity's feature set. Closing this issue as a dupe.
