### ISSUE TITLE
[NOT ISSUE] Skew effect transition style

### ISSUE THREAD

**Issue by coderesolution** [metafizzy/flickity#1035]
Hi all,

I wondered if anybody has been able to create a nice slide effect similar to this skew style I have found here: https://codyhouse.co/ds/components/app/svg-slideshow--skew

Thank you! Also, apologies if this is the wrong place.

Elliott

**Comment by clarknelson** [comment]
You can't just add the transition effect, it took forever for flickity to just get a fade option and its another package.

You could look at that package to get an idea of how to implement this. Or you can just buy the codehouse plugin.

**Comment by coderesolution** [comment]
It's something I will most likely end up doing myself but I'd love to see if it's been done before first (on Flickity) before I delve in.

Thanks

**Comment by clarknelson** [comment]
http://snapsvg.io/ might help you animate svgs, good luck!

**Comment by desandro** [comment]
Thanks for this feature request. Flickity is designed to work with any HTML content in slides, not just images. So custom transition styles like this skew effect are difficult to achieve. That said, it may be possible to do, but I'll leave that up to you. Look over the source code for [flickity-fade](https://github.com/metafizzy/flickity-fade) for how to approach this behavior.
