### ISSUE TITLE
 Show more of the requested slides

### ISSUE THREAD

**Issue by remaxprueba** [metafizzy/flickity#1036]
I try to group the slides in 3 with CellsGroup but it still shows me 4, just as with lazyload I don't respect the amount of slides requested

I would greatly appreciate your help, I'm desperate!

**Comment by clarknelson** [comment]
Please post an example so we can help.

**Comment by remaxprueba** [comment]
<div class="carousel" data-flickity='{"contain":true, "pageDots": false,"lazyLoad": 3, "adaptiveHeight":true, "groupCells": 1, "dragable":true,"wrapAround": false}' style="width:80%;position:relative;margin:0 auto;padding-top: 40px;">
       <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/gastronomia/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/2019/05/Categoria-1.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/2019/05/Categoria-1.png" title="<? esc_html_e( 'Gastrononía', 'theinn' ); ?>" alt="<? esc_html_e( 'Gastrononía', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'Gastrononía', 'theinn' ); ?></h4>
                </a>
            </div>
            <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/que-hacer-en-mazatlan/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/que-hacer-en-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/que-hacer-en-mazatlan-the-inn.png" title="<? esc_html_e( 'QUÉ HACER EN MAZATLÁN', 'theinn' ); ?>" alt="<? esc_html_e( 'QUÉ HACER EN MAZATLÁN', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'QUÉ HACER EN MAZATLÁN', 'theinn' ); ?></h4>
                </a>
            </div>
             <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/atracciones-y-lugares-de-interes/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/carnaval-de-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/carnaval-de-mazatlan-the-inn.png" title="<? esc_html_e( 'ATRACCIONES Y LUGARES DE INTERÉS', 'theinn' ); ?>" alt="<? esc_html_e( 'ATRACCIONES Y LUGARES DE INTERÉS', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'ATRACCIONES Y LUGARES DE INTERÉS', 'theinn' ); ?></h4>
                </a>
            </div>
             <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/cultura/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/centro-historico-de-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/centro-historico-de-mazatlan-the-inn.png" title="<? esc_html_e( 'CULTURA', 'theinn' ); ?>" alt="<? esc_html_e( 'CULTURA', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'CULTURA', 'theinn' ); ?></h4>
                </a>
            </div>
             <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/playas/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/playas-de-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/playas-de-mazatlan-the-inn.png" title="<? esc_html_e( 'PLAYAS', 'theinn' ); ?>" alt="<? esc_html_e( 'PLAYAS', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'PLAYAS', 'theinn' ); ?></h4>
                </a>
            </div>

**Comment by remaxprueba** [comment]
"<div class="carousel" data-flickity='{"contain":true, "pageDots": false,"lazyLoad": 3, "adaptiveHeight":true, "groupCells": 1, "dragable":true,"wrapAround": false}' style="width:80%;position:relative;margin:0 auto;padding-top: 40px;">
       <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/gastronomia/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/2019/05/Categoria-1.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/2019/05/Categoria-1.png" title="<? esc_html_e( 'Gastrononía', 'theinn' ); ?>" alt="<? esc_html_e( 'Gastrononía', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'Gastrononía', 'theinn' ); ?></h4>
                </a>
            </div>
            <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/que-hacer-en-mazatlan/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/que-hacer-en-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/que-hacer-en-mazatlan-the-inn.png" title="<? esc_html_e( 'QUÉ HACER EN MAZATLÁN', 'theinn' ); ?>" alt="<? esc_html_e( 'QUÉ HACER EN MAZATLÁN', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'QUÉ HACER EN MAZATLÁN', 'theinn' ); ?></h4>
                </a>
            </div>
             <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/atracciones-y-lugares-de-interes/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/carnaval-de-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/carnaval-de-mazatlan-the-inn.png" title="<? esc_html_e( 'ATRACCIONES Y LUGARES DE INTERÉS', 'theinn' ); ?>" alt="<? esc_html_e( 'ATRACCIONES Y LUGARES DE INTERÉS', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'ATRACCIONES Y LUGARES DE INTERÉS', 'theinn' ); ?></h4>
                </a>
            </div>
             <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/cultura/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/centro-historico-de-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/centro-historico-de-mazatlan-the-inn.png" title="<? esc_html_e( 'CULTURA', 'theinn' ); ?>" alt="<? esc_html_e( 'CULTURA', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'CULTURA', 'theinn' ); ?></h4>
                </a>
            </div>
             <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/playas/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/playas-de-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/playas-de-mazatlan-the-inn.png" title="<? esc_html_e( 'PLAYAS', 'theinn' ); ?>" alt="<? esc_html_e( 'PLAYAS', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'PLAYAS', 'theinn' ); ?></h4>
                </a>
            </div>"

**Comment by remaxprueba** [comment]
> `<div class="carousel" data-flickity='{"contain":true, "pageDots": false,"lazyLoad": 3, "adaptiveHeight":true, "groupCells": 1, "dragable":true,"wrapAround": false}' style="width:80%;position:relative;margin:0 auto;padding-top: 40px;">
       <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/gastronomia/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/2019/05/Categoria-1.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/2019/05/Categoria-1.png" title="<? esc_html_e( 'Gastrononía', 'theinn' ); ?>" alt="<? esc_html_e( 'Gastrononía', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'Gastrononía', 'theinn' ); ?></h4>
                </a>
            </div>
            <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/que-hacer-en-mazatlan/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/que-hacer-en-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/que-hacer-en-mazatlan-the-inn.png" title="<? esc_html_e( 'QUÉ HACER EN MAZATLÁN', 'theinn' ); ?>" alt="<? esc_html_e( 'QUÉ HACER EN MAZATLÁN', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'QUÉ HACER EN MAZATLÁN', 'theinn' ); ?></h4>
                </a>
            </div>
             <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/atracciones-y-lugares-de-interes/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/carnaval-de-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/carnaval-de-mazatlan-the-inn.png" title="<? esc_html_e( 'ATRACCIONES Y LUGARES DE INTERÉS', 'theinn' ); ?>" alt="<? esc_html_e( 'ATRACCIONES Y LUGARES DE INTERÉS', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'ATRACCIONES Y LUGARES DE INTERÉS', 'theinn' ); ?></h4>
                </a>
            </div>
             <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/cultura/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/centro-historico-de-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/centro-historico-de-mazatlan-the-inn.png" title="<? esc_html_e( 'CULTURA', 'theinn' ); ?>" alt="<? esc_html_e( 'CULTURA', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'CULTURA', 'theinn' ); ?></h4>
                </a>
            </div>
             <div class="carousel-cell">
                <a href="https://blog.theinnmazatlan.com/category/playas/" target="_blank" class="cell-content grow">
                    <img class="carousel-cell-image" data-flickity-lazyload="https://blog.theinnmazatlan.com/wp-content/uploads/playas-de-mazatlan-the-inn.png" src="https://blog.theinnmazatlan.com/wp-content/uploads/playas-de-mazatlan-the-inn.png" title="<? esc_html_e( 'PLAYAS', 'theinn' ); ?>" alt="<? esc_html_e( 'PLAYAS', 'theinn' ); ?>" />
                    <span class="more"><? esc_html_e( 'Visitar', 'theinn' ); ?></span>
                    <h4><? esc_html_e( 'PLAYAS', 'theinn' ); ?></h4>
                </a>
            </div>`

**Comment by remaxprueba** [comment]
![Captura de pantalla 2020-03-05 a la(s) 12 35 43](https://user-images.githubusercontent.com/43283646/76018790-ed492a80-5edd-11ea-8c80-05287b564d32.png)
