### ISSUE TITLE
Disable bounce at first and last slide

### ISSUE THREAD

**Issue by dkoether** [metafizzy/flickity#1038]
I'm trying to disable the bounce at the first and last slide. I want that the slider to end hard without any bouncy animation at both ends. 

See https://codepen.io/desandro/pen/aOyMam
When you drag the first slide to the right you can see the background. I want to avoid this.

In this case of issue I can't provide a reduced test case.

Thanks in advance!

**Comment by desandro** [comment]
Thanks for reporting this issue. You'll have to overwrite [dragMove method,](https://github.com/metafizzy/flickity/blob/v2.2.1/js/drag.js#L230-L236) in particular, modifying the `!this.options.wrapAround && this.slides.length` conditional

**Comment by allan-walker** [comment]
For anyone interested, It seems like the way to do it is to add this code above your call to instantiate Flickity:

`Flickity.prototype.dragMove = function (event, pointer, moveVector) {
    if (!this.isDraggable) {
      return;
    }
    event.preventDefault();

    this.previousDragX = this.dragX;
    // reverse if right-to-left
    var direction = this.options.rightToLeft ? -1 : 1;
    if (this.options.wrapAround) {
      // wrap around move. #589
      moveVector.x = moveVector.x % this.slideableWidth;
    }
    var dragX = this.dragStartPosition + moveVector.x * direction;

    //  *** Basically comment out this section to prevent the bounce:
    //
    // if ( !this.options.wrapAround && this.slides.length ) {
    //   // slow drag
    //   var originBound = Math.max( -this.slides[0].target, this.dragStartPosition );
    //   dragX = dragX > originBound ? ( dragX + originBound ) * 0.5 : dragX;
    //   var endBound = Math.min( -this.getLastSlide().target, this.dragStartPosition );
    //   dragX = dragX < endBound ? ( dragX + endBound ) * 0.5 : dragX;
    // }

    this.dragX = dragX;

    this.dragMoveTime = new Date();
    this.dispatchEvent("dragMove", event, [pointer, moveVector]);
  };`

**Comment by holtkamp** [comment]
@desandro, I also encountered this "wish" to disable the bouncing at the ends. Would it be an idea to make it a configurable option `bounce` which defaults to true to allow easy adoption of it and prevent the need for customization?

**Comment by desandro** [comment]
Hmm, given the low popularity of this request over the course of 7 years, I'd prefer not to add another option it for it and instead address it with the [duck punch](https://metafizzy.co/blog/duck-punching-prototype/) above

**Comment by holtkamp** [comment]
mm, ok, that might be an approach. But to solution suggested by @allan-walker actually "disables" some code, so duck punching won't work here, right?

I can try to come up with a pull request which will be something like:

```javascript
Flickity.prototype.dragMove = function (event, pointer, moveVector) {
    if (!this.isDraggable) {
      return;
    }

    event.preventDefault();

    this.previousDragX = this.dragX;
    // reverse if right-to-left
    var direction = this.options.rightToLeft ? -1 : 1;
    if (this.options.wrapAround) {
      // wrap around move. #589
      moveVector.x = moveVector.x % this.slideableWidth;
    }
    var dragX = this.dragStartPosition + moveVector.x * direction;

    // Should we bounce?
    if( this.options.bounce ) {
      if ( !this.options.wrapAround && this.slides.length ) {
       // slow drag
       var originBound = Math.max( -this.slides[0].target, this.dragStartPosition );
       dragX = dragX > originBound ? ( dragX + originBound ) * 0.5 : dragX;
       var endBound = Math.min( -this.getLastSlide().target, this.dragStartPosition );
       dragX = dragX < endBound ? ( dragX + endBound ) * 0.5 : dragX;
    }

    this.dragX = dragX;

    this.dragMoveTime = new Date();
    this.dispatchEvent("dragMove", event, [pointer, moveVector]);
};
```

But it is up to you to decide whether such approach actually disables the bounce as intended...

**Comment by kylegoines** [comment]
> For anyone interested, It seems like the way to do it is to add this code above your call to instantiate Flickity:
> 
> ```
> Flickity.prototype.dragMove = function (event, pointer, moveVector) {
>     if (!this.isDraggable) {
>       return;
>     }
> 
>     event.preventDefault();
> 
>     this.previousDragX = this.dragX;
>     // reverse if right-to-left
>     var direction = this.options.rightToLeft ? -1 : 1;
>     if (this.options.wrapAround) {
>       // wrap around move. #589
>       moveVector.x = moveVector.x % this.slideableWidth;
>     }
>     var dragX = this.dragStartPosition + moveVector.x * direction;
> 
>     //  *** Basically comment out this section to prevent the bounce:
>     //
>     // if ( !this.options.wrapAround && this.slides.length ) {
>     //   // slow drag
>     //   var originBound = Math.max( -this.slides[0].target, this.dragStartPosition );
>     //   dragX = dragX > originBound ? ( dragX + originBound ) * 0.5 : dragX;
>     //   var endBound = Math.min( -this.getLastSlide().target, this.dragStartPosition );
>     //   dragX = dragX < endBound ? ( dragX + endBound ) * 0.5 : dragX;
>     // }
> 
>     this.dragX = dragX;
> 
>     this.dragMoveTime = new Date();
>     this.dispatchEvent("dragMove", event, [pointer, moveVector]);
>   };
> ```

sorry, this doesn't seem to do anything, this a feature im very much trying to implement, - it seems to trigger whenever i drag on any panel

**Comment by kylegoines** [comment]
i found @allan-walker 's solution not working, but the initial idea was very good,
i updated it for my use-case and hopefully this can help someone else

```
    Flickity.prototype.dragMove = function (event, pointer, moveVector) {
      console.log('jsut drag')
      if (!this.isDraggable) {
        return
      }

      event.preventDefault()

      this.previousDragX = this.dragX
      // reverse if right-to-left
      var direction = this.options.rightToLeft ? -1 : 1
      if (this.options.wrapAround) {
        // wrap around move. #589
        moveVector.x = moveVector.x % this.slideableWidth
      }
      var dragX = this.dragStartPosition + moveVector.x * direction

      var originBound = Math.max(-this.slides[0].target, this.dragStartPosition)

      var endBound = Math.min(
        -this.getLastSlide().target,
        this.dragStartPosition
      )

      if (dragX > originBound) {
        dragX = originBound
      }

      if (dragX < endBound) {
        dragX = endBound
      }

      this.dragX = dragX

      this.dragMoveTime = new Date()
      this.dispatchEvent('dragMove', event, [pointer, moveVector])
    }
```
i have altogether removed the `this.wrapAround` if statement, as this is not valid for my use-case but i could imagine wanting it if you plan on having update-able configs.
The real usefullness of this is to know whatever you pass to `this.dragX` will be represented in the next tick. `originBound` and `endBound` are these two extremes.
