### ISSUE TITLE
When one thumbnail is clicked the list of images must move ONLY ONE slot up

### ISSUE THREAD

**Issue by Yurii-Smortkin1** [metafizzy/flickity#1040]
When one thumbnail is clicked the list of images must move ONLY ONE slot up in order to display a new thumbnail in the bottom and hide one in the top without centering selected thumbnail.

**Additional info about slider:**

- 5 pictures are visible in the slider, the remaining 5+ are hidden

- Now there is the [wrapAround: true] property, which centers the selected image and adds the ability to slide endlessly.

How can i do it with flickity slider?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
