### ISSUE TITLE
Images overlap on load

### ISSUE THREAD

**Issue by elemis** [metafizzy/flickity#1042]
Even on the official demo, images overlap on load: https://codepen.io/desandro/pen/GgQREP 
 **imagesLoaded:true** is set, but it doesn't seem to fix it. Happens both on Chrome and Firefox. Any suggestions?
<img width="955" alt="Screen Shot 2020-03-26 at 15 27 22" src="https://user-images.githubusercontent.com/608547/77647376-5705a300-6f77-11ea-944f-b76c349e543b.png">
Screencast of the issue: https://share.getcloudapp.com/z8uX97jZ

**Comment by desandro** [comment]
Thanks for reporting this issue. I am not able to reproduce.
