### ISSUE TITLE
Lazyload when scrolling down into viewport?

### ISSUE THREAD

**Issue by madjedo** [metafizzy/flickity#1043]
I understand how the lazyloading works with flickity. I can set lazyload: 1 to have adjacent slides load only when active and so on...

However, what if I want to load images only when user scroll down to the slider? Just like lazyloading any other image on the web.

For example, I have a carousel slider with 5 images, but its very low down on the page, at the moment I have set lazyload: 1. This still means however, that 3 images are directly loaded on pageload. I would like there to be some function to have images load only when user scrolls down or when the carousel slider is on viewport only.

**Comment by OneTimeUser** [comment]
I have done this...basically I just lazyload the carousel. Not sure if its the best option but it has worked. Just wrap the flickity initializer in a LazyLoad function.
