### ISSUE TITLE
Cannot focus/click on form elements in iOS devices

### ISSUE THREAD

**Issue by passiomatic** [metafizzy/flickity#105]
I guess this issue is related to #21. Speaking of forms this bit of code from Unidragger module looks problematic on touch devices (tested on iPad2 running iOS 7.0.4 with Safari, iPhone 4 and 5):
```
// triggered after pointer down & up with no/tiny movement
Unidragger.prototype._staticClick = function( event, pointer ) {
  // allow click in text input
  if ( event.target.nodeName == 'INPUT' && event.target.type == 'text' ) {
    event.target.focus();
  }
  this.staticClick( event, pointer );
};
```

I have a cell with few text fields - 'text' and  'email' types - a textarea and a submit button - BUTTON element, not INPUT. It's easy enough to change the code above to pass focus to type=email and textarea elements. In fact I have done just that with some specific code: 

```
Unidragger.prototype._staticClick = function( event, pointer ) {
  // allow click in text input and textarea
  if ( event.target.nodeName == 'TEXTAREA' || ( event.target.nodeName == 'INPUT' && event.target.type == 'text' || event.target.type == 'email' ) ) {
    event.target.focus();
  }
  this.staticClick( event, pointer );
};
```

However, things start to go downhill when you try to submit the form. Unfortunately it does nothing. I've tried to programmatically send clicks to submit button using a similar approach but I experience double submits and other weird behaviors. 

I've read the code again and again but it escapes me how the click() events are routed and interact with staticClick. It looks like staticClick cancel click events, or perhaps the drag events cancel them.

Testcase:
http://codepen.io/anon/pen/QwXjzJ

Thanks for your time.

**Comment by desandro** [comment]
Thanks for reporting this bug. I'll be looking in to it.

**Comment by mgomes** [comment]
+1

**Comment by tsanzol** [comment]
just checked, input type password is also not clickable..

**Comment by desandro** [comment]
Flickity `v1.0.1` has been released with fixes for inputs. [Try it out](http://flickity.metafizzy.co) and holler if this problem persists.

**Comment by passiomatic** [comment]
Works for me. Thank you!
