### ISSUE TITLE
Use scroll (event) to create parallax effects, bug when using wrapAround: true

### ISSUE THREAD

**Issue by romain-granai** [metafizzy/flickity#1050]
Hi,

I'm trying to implement to implement this demo to my website : https://codepen.io/desandro/pen/jAGWRQ

but unfortunately when the carousel is looped using wrapAround: true, there is a bug with the last item.
Is it possible to to make that work on wrapAround or not at all?

Thank you

**Comment by desandro** [comment]
This is indeed a bug. See #468 for tracking
