### ISSUE TITLE
Start autoplay on hover

### ISSUE THREAD

**Issue by DirtyWork** [metafizzy/flickity#1055]
Hey. I would need an exact opposite of the pause on mouse over feature. You know those image/video galleries where the pictures or videos start to play when you mouse over.

**Comment by P2284912693** [comment]
Just use jQuery/JS to control slide change by using ["next()"](https://flickity.metafizzy.co/api.html#next) event of [Flickity API](https://flickity.metafizzy.co/api.html)

### **_Here's my bodged solution:_**
```
$(function () {
  var $carousel = new Flickity(".carousel", {
    "prevNextButtons": false,
    "autoPlay": false,
    "wrapAround": true,
    "pauseAutoPlayOnHover": false
  });

  
  var autoTimer;
  $(".carousel")
    .mouseenter(function() {
      autoTimer = setInterval(function () {
        $carousel.next();
      }, 1000);
    })
    .mouseleave(function() {
      clearInterval(autoTimer);
    });

});
```
[Working Demo (CodePen)](https://codepen.io/yourpalnurav/pen/GRpQoVj)

_Dev's rarely change carousels on hover; carousels containing buttons/links should usually stop autoplaying on hover to let the user view the content of the slide before a decision is made to click on the element._
