### ISSUE TITLE
Please add an option {"dragAmt":100} which represents the amount a slide is to be dragged before changing.

### ISSUE THREAD

**Issue by P2284912693** [metafizzy/flickity#1056]
The current option {"dragThreshold": 3} just gives the safe space for vertical scrolling. It doesn't compensate for accidental flicks on the carousel.

If we want to limit the slide changing drag threshold to compensate for accidental drags by certain pixels say 100px, there is currently no option for that.

If we increase this to say {"dragThreshold": 100} to achieve compensation, the UI feels janky;
At first the slide doesn't move till user drags over 100px and when the user crosses the 100px threshold, the Slide jumps to that dragged position; It basically teleports itself there.

**If dragAmt is implemented, the slide will start dragging no matter what but when 'dragEnd' fires, if 'moveVector' is less than dragAmt, then the slide can bounce back to original place. The slide remains draggable but doesn't change to the next/previous slide until the moveVector is more than dragAmt.**

**Reduced Test Case:**
[https://codepen.io/U2284912693/pen/WNQMQLv](https://codepen.io/yourpalnurav/pen/WNQMQLv)

_DragEnd doesn't provide the moveVector value_ :(

**Comment by desandro** [comment]
Thanks for this feature request. I appreciate your thoughtfulness and consideration with this issue, but I don't think this is the right approach to resolve the issue. Sorry, I will have to pass on this one.
