### ISSUE TITLE
Slider positioning issue 

### ISSUE THREAD

**Issue by rasneu88** [metafizzy/flickity#1057]
Hello! 

First of all, thank you for this slider :) 

I have an issue with the slider, where it seems is doesn't position itself correctly, and there for doesn't align with other content. 
In the example below, i have a slider with cells, that are 25% in width. I have `groupCells` and `contain` set to true. I can see that the slider positions itself with `transform: translateX(-5px)`. I expect the slider to have a start position of 0, so that it will align properly. 

Is there any why around this? 

**Test case:** https://codepen.io/rockerduck/pen/gOavqaw

**Comment by desandro** [comment]
Thanks for reporting this issue. Flickity will position the first cell to the start of the cell, excluding the margin. If you want to add margin to the cell positioning, you would need to add a another wrapping element and add margin to an inner cell element

``` html
<div class="cell-wrapper">
  <div class="cell"> <!-- has margin -->
  </div>
</div>
```

**Comment by rasneu88** [comment]
@desandro  Thank you for responding to my issue! 

What i'm trying to achieve is that the first and last cell in the current slide, should align with the edges of the screen. Also, i find it weird that the slider aligns differently, if there is one slide vs. two.

I have updated my codepen to illustrate my issue: https://codepen.io/rockerduck/pen/gOavqaw

Again, thank you for the support :)

**Comment by rasneu88** [comment]
This is essentially the same issue as this: #1062

In my case, if i set "contain: true", the slider is positioned incorrectly if there's only 1 slide, and if there's more than 1 slide and cellIndex is === last slide. 
I ended up using Flickitys events to offset the slider in the above cases, so that the slider aligns with other content on the site.
