### ISSUE TITLE
New dynamiclly created carousel not initialising

### ISSUE THREAD

**Issue by JordanSayner** [metafizzy/flickity#1061]
Hi, 

I want to insert new carousels onto my page dynamically, i have added a reduced test case of what im trying to do. The only real different is how the new carousel is being added, my test case it just a string which gets appended. but in my project, it will be an ajax request.

Anyway, as you can see, i am destroying all carousels on click, then once I've added the new carousel, i try and initialise the new one as well as the old one. 

The problem is, the new one isn't effect. 

Any ideas?

**Test case:** https://codepen.io/jsayner/pen/ab06bdabd3d74afc5e84cb7730d21b52

**Comment by wpexplorer** [comment]
@JordanSayner - Did you ever figure out a fix for this?

**Comment by desandro** [comment]
Looks like that codepen is no longer valid. If you have another one I can take a look.
