### ISSUE TITLE
Initial setting transform:translateX is wrong

### ISSUE THREAD

**Issue by mrdotb** [metafizzy/flickity#1062]
Hello,

When I was using flickity I found a weird behavior. I read some issues about that already.
#867 #972 maybe.

Basically if there is two blocks in position absolute inside a cell a  ```transform: translateX(some%)``` is added.

The minimal test case.

**Test case:** https://codepen.io/mrdotb-the-lessful/pen/abvMgvO

You have to reload the browser, codepen trigger page reload.

![bug](https://user-images.githubusercontent.com/7212914/82761671-6fceef80-9e26-11ea-9823-8a2dbc54765b.png)

**Comment by mattneal-stafflink** [comment]
I'm having the same issue. Have you figured this out yet?

**Comment by mrdotb** [comment]
For my case I did without using absolute position in my slide.  For curiosity I try to add the `contain: false`  as you suggested to the codepen but the translate is still here.

**Comment by mattneal-stafflink** [comment]
Yeah turns out that didn't fix my problem. My issue seemed to be CSS related. I copied the full width example exactly the way it is in the CodePen and it was still messed up, so that was a dead giveaway.

**Comment by desandro** [comment]
Thanks for the CodePen!

I think this is a browser scrollbar issue. Set `html { overflow-y: scroll; }` fixes the issue. See https://codepen.io/desandro/pen/XWeaPOd
