### ISSUE TITLE
The 'settle.flickity' event only triggers after resize if the slider is used 'asNavFor'

### ISSUE THREAD

**Issue by Hlsgs** [metafizzy/flickity#1064]
`settle.flickity` would be significantly more useful if it could be used consistently for the layout recalculation and subsequent 'settling' that occurs after resize, not just after slide change, and seems to work that way only if the silder is used as navigation for another.
Is this intentional, and, if so, why?

**Comment by desandro** [comment]
sorry, I don't understand this use case. This issue was quiet for a while, so looks like others are not interested in this sort of enhancement.
