### ISSUE TITLE
autoplay Flickity

### ISSUE THREAD

**Issue by leszekbucki** [metafizzy/flickity#1065]
I can't find a solution. Autoplay only works at the beginning. If I use the mouse to rewind the slides, autoplay will turn off. How do you set autoplay to run all the time?

**Comment by MikeyJN** [comment]
This is the intended default behaviour for Flickity, that one the carousel is interacted with the auto-play stops. so the user retains full control.

However, you can get around this by adding a 'mouseleave' event:

```
$(".main-carousel").on("mouseleave", function() {
    $(this).flickity("playPlayer");
});
```

Or alternately use this Instead which IMO is better than the above with regard to touch-screen devices as it doesn't rely on seeing a mouse event which of course they don't have: 

```
Flickity.prototype.stopPlayer = function() {
    this.player.stop();
    this.player.play();
};
```

Hope this helps,

Mike
