### ISSUE TITLE
Target 'flickity-slider' div and add more classes to it

### ISSUE THREAD

**Issue by Auromnia** [metafizzy/flickity#1068]
Hey all, this isn't a bug but I've tried numerous ways on achieving this and as someone who is self-teaching web design, I struggle with JS and JQuery and I can't seem to figure this one out. I'm trying to target the div 'flickity-slider' so I can add custom classes to this specific div to further style the slider. Any help or pointers in the right direction would be really appreciated! 

Original HTML
`<div class="flickity-slider" style="left: 0px; transform: translateX(48.76%);">`

Added Classes
`<div class="flickity-slider white-bg margin-10" style="left: 0px; transform: translateX(48.76%);">`

**Comment by MikeyJN** [comment]
Hi,

Not sure if this is what you mean, but here is the typical Flickity set-up:

```
<div class="main-carousel">
  <div class="carousel-cell">...</div>
  <div class="carousel-cell">...</div>
  <div class="carousel-cell">...</div>
</div>
```

So if you wanted to be able to target a particular slide/slides you could do so by assigning another class to the slide/slides in question like this:

```
<div class="main-carousel">
  <div class="carousel-cell one">...</div>
  <div class="carousel-cell two">...</div>
  <div class="carousel-cell three">...</div>
</div>
```
Then you can target the first one for example via CSS with:

```
.carousel-cell.one {
background-color: red;
}
```

The second with:

.carousel-cell.two {
background-color: blue;
}
```

...and so on.

Hope this is what you was after,

Mike

**Comment by Auromnia** [comment]
Hi Mike, thanks for the input! It’s not exactly what I was looking for, but close. When Flickity is enabled it creates a class below “flickity-viewport” called “flickity-slider” which I’ve been trying to add other classes too. I’ll continue to play around with the cells though and see if that does the trick. 

Thanks again!

**Comment by MikeyJN** [comment]
Hi,

Rather than trying to add in-line styles to the HTML, can you not just target '.flickity-slider' in your CSS style sheet and apply them there?

So going by your first post and example, are you looking to add a margin of 10px and a background colour of white? If so, you could just add the following to your CSS:

```
.flickity-slider {
margin: 10px;
background-color: white;
}
```

Mike

**Comment by victormayala** [comment]
Not sure if this still matters but here is the solution:
Add your own CSS class for "flickity-slider" to your CSS stylesheet like this:

.flickity-slider {
        position: absolute;
        left: -40px !important;
      }

Make sure you add "!important" to the left attribute, this will overwrite the default CSS.
