### ISSUE TITLE
Slide over to left/right/top/bottom

### ISSUE THREAD

**Issue by kabubi** [metafizzy/flickity#1069]
Hi,
Any change or idea to implement this kind of slide transition? Check examples here.
https://www.themepunch.com/revsliderjquery-doc/slide-transitions/
"Slide Over To Left", "Slide Over To Right", "Slide Over To Top", "Slide Over To Bottom"
Thanks

**Comment by desandro** [comment]
Sorry no plans to support this. You'll have to hack Flickity's slide movement behavior. See also [Flickity transformer](https://github.com/elcontraption/flickity-transformer)
