### ISSUE TITLE
Create a branch / package with just the dist files

### ISSUE THREAD

**Issue by pesla** [metafizzy/flickity#107]
It would be nice to have the ability to add this package with Bower (or another package manager) without checking out all dependencies and / or dev files. In my case, for now all I want to do is use the package (like many others) and keep the package up-to-date easily. Without having to download and check for updates manually, that is.

A solution would be to create a dist branch with just the necessary files to use the package (eg. `/dist`, `README` and `LICENSE`). In that case someone could install that package with `bower install flickity#dist`. Another option is to create a separate package.

Lastly: Thanks for your work on flickity!

**Comment by desandro** [comment]
Thanks for adding this request. I find that including packaged source files in `dist`, along with installing dependencies, in the same repo, is the best solution that allows the most use cases. Host-and-link users can use `dist`, or package management users can install dependencies. Adding a second repo could be confusing.

**Comment by pesla** [comment]
Why would package management users ever want to install dependencies if their goal only is to have up-to-date dist files? I see your reasoning, but creating a branch to which you merge dist files after a release is easy work and helps PM users with a clean codebase.

Anyway, thanks for responding, i'll look for a way to manage this in our codebase.
