### ISSUE TITLE
wrapAround images not shown until full loop completes

### ISSUE THREAD

**Issue by johncarter-** [metafizzy/flickity#1072]
When using images inside a wrapper in a `wrapAround` instance, the repeated loop are not shown until the entire loop has been shown.

After reading other issues I thought the issue was with the `imagesLoaded` option but toggling that makes no difference.

If I remove the wrapping `<a href="#"></a>` the images load properly.

**Test case:** https://codepen.io/johncarter-the-decoder/pen/wvMGwYd
I have added a border just to demonstrate the missing images.

Sorry if this is a usage error rather than a bug.

**Comment by desandro** [comment]
Thanks for reporting this image. It looks to be some conflict with Tailwind CSS. Once I remove it, all the images are visible. I thought it could be `img { max-width: 100% }` but that doesn't seem to be it. https://codepen.io/desandro/pen/726e7c75fe37bfc4d7f129b7a714d0cf
