### ISSUE TITLE
Won't initialize properly unless resizing window (Rails 6)

### ISSUE THREAD

**Issue by anon987654321** [metafizzy/flickity#1077]
Hello!

Does anyone know why Flickity won't initialize properly unless one resizes ones window?

![flickietest](https://user-images.githubusercontent.com/62118265/85226839-dcafb800-b3d9-11ea-93a1-f258e2e85535.png)

I've tried with `resize` as well as `imagesLoaded` but to no avail:

https://github.com/anon987654321/rails-flickity (uses [ruby-faker](https://github.com/faker-ruby/faker) and [loremflickr](loremflickr.com) for placeholder images)

Or more specifically:

https://github.com/anon987654321/rails-flickity/blob/master/app/javascript/packs/application.js

Thanks!

**Comment by Riyad95** [comment]
same issue here

**Comment by graygilmore** [comment]
Are you included `imagesLoaded`? https://flickity.metafizzy.co/extras.html#module-loaders

**Comment by anon987654321** [comment]
@graygilmore yep! I've linked to the `application.js` above.

**Comment by anon987654321** [comment]
Oh wait, I need to include `flickity-imagesloaded` separately? Thanks for pointing that out, I'll try it ASAP.

**Comment by anon987654321** [comment]
@graygilmore worked perfectly, thank you!
