### ISSUE TITLE
Specify Aspect Ratio for Images

### ISSUE THREAD

**Issue by maimairel** [metafizzy/flickity#108]
Hello, 

One more feature request here...

I'd love to see a feature where we can specify the aspect ratio of image carousel items. We could take the aspect ratio from the image's width and height attribute, or from a HTML5 data-* property, or just a function supplied with the element to Flickity's constructor.

The specified aspect ratio (which of course must be specified correctly by the dev for the image to show up in the correct aspect ratio) can be used by Flickity to calculate the item width based on the item height directly after initialization.

For example, if an image has 16/9 aspect ratio, and the carousel's height is 400px, then Flickity can immediately determine that the image width is 400 * 16 / 9 = 711.

This would be very useful and will enhance user experience significantly. Visitors will never need to wait for the images to load before Flickity can properly layout the items in the carousel.

Even more useful, devs can just set the image opacity to zero, then put a preloader in place, and animate it to 1 after the image is fully loaded.

In my opinion this is really a feature that must be present in modern plugins :)

Thank you!

**Comment by desandro** [comment]
Thanks for this feature request. I see this as something you can do outside of Flickity, either with native `width` and `height` attributes, or with [`padding-bottom` CSS technique](http://www.fredparke.com/blog/css-padding-trick-responsive-intrinsic-ratios)

**Comment by maimairel** [comment]
Hi, 

I think for #14 to be implemented, you'll first need this. Just for images :)
