### ISSUE TITLE
Swipe direction (swipe angle)

### ISSUE THREAD

**Issue by Razum** [metafizzy/flickity#1081]
Hello

First of all thanks for such a lovely carousel plugin!

Just wondering is it possible somehow to change swiping direction (angle)?
The problem:
We have full width flickity carousel on mobile devices - [Carousel example](https://aavaswim.eu/products/l-retro-one-piece). And it swipes left/right when i need the page to be scrolled vertically.

When swipe angle is 90deg it scrolls the page (as expected)

![90deg scroll](http://i.piccy.info/i9/f1c70530c03bc03037a3294125a0c3f1/1594061794/130947/1386742/1594061238926.jpg)

but if angle ~45deg it swipes carousel
![45 deg swipe](http://i.piccy.info/i9/7b3ced66ad758eac610a63d0b007f56e/1594061899/133538/1386742/1594061352163.jpg)

I need both these cases to trigger vertical scroll instead of horizontal swipe. How can implement this behaviour?

Thanks in advance!

**Comment by Razum** [comment]
any thoughts?

**Comment by desandro** [comment]
Ideally, swiping horizontal within Flickity will only move the Flickity carousel. Swiping vertically will only move the page. But for the past several years, iOS has not made that possible.

In any case, that's the behavior I am aiming for. Sorry I cannot accommodate this request.
