### ISSUE TITLE
Offset cell align?

### ISSUE THREAD

**Issue by LeoSeyers** [metafizzy/flickity#1082]
Hello,

For a client, I need to align the first item of my slider (that takes 100% of the viewport) to the container left margin.
It would be like to use cellAlign option but with a defined offset in pixel for instance. 

We don't have this option right now but I'm wondering if someone has already encounter a situation like this and if a workaround / simple solution already exists.

See schema for clarity : http://demo.studio-scale.com/offset-flickity.jpg
(I'm sorry I have no idea about how to embed an image within a thread)

This is close to #171 but not exactly the same.

Thank you 
Leo

**Comment by clementducerf** [comment]
Check this : https://github.com/metafizzy/flickity/issues/955

**Comment by LeoSeyers** [comment]
> Check this : #955

You're gold! Thanks Clément, David's solution is pretty good to my case
