### ISSUE TITLE
Thumbnails in grid

### ISSUE THREAD

**Issue by kiul** [metafizzy/flickity#1083]
![sample-normal](https://user-images.githubusercontent.com/5055746/87227651-cbd0e180-c39c-11ea-9e45-52cfb70a9fd2.jpg)
![sample-idea](https://user-images.githubusercontent.com/5055746/87227652-cf646880-c39c-11ea-88c0-c4b5fa86bcfd.jpg)

Hello
I have 2 carousels on my page
The first is a classic carousel, the second thanks to the "asNavFor" functionality I use it as navigation
I was wondering if it was possible to have a grid thumbnail rather than a line because I want to be able to see all the thumbnails in grid.
I can't do it at all if someone can help me?
Thank you

**Comment by desandro** [comment]
Sounds like you're looking for [Custom UI](https://flickity.metafizzy.co/extras.html#custom-navigation-ui)
