### ISSUE TITLE
Slider breaks with three cells and wrapAround

### ISSUE THREAD

**Issue by L3vi** [metafizzy/flickity#1086]
Added styling to make non-selected cells smaller, opaque, and spaced out a bit. During this process ran into this bug that only happens when there is only three cells and wrapAround is `true`. You can strip down the CSS down to essentially nothing and you'll still see the issue. 

**Test case:** https://codepen.io/Levistum/pen/OJMaPVw

**Comment by Hlsgs** [comment]
Try this:
https://github.com/metafizzy/flickity-fade/issues/1#issuecomment-486778382

**Comment by L3vi** [comment]
That didn’t work either :/

**Comment by Hlsgs** [comment]
Yeah, sorry about that. Didn't pay proper attention to your question . That's why I deleted it after.

**Comment by L3vi** [comment]
That's okay, I just got the email and responded to it. 

Thanks for the response though

**Comment by desandro** [comment]
Looks like this is an issue with wrapAround and not having enough content to fill the container. In which case, I'm tracking a resolution in #809
