### ISSUE TITLE
Custom Prev/Next with Flickity Page Dots

### ISSUE THREAD

**Issue by Auromnia** [metafizzy/flickity#1090]
Hey all, I've been experimenting with Flickity for the last few months and have found some creative ways to really customize sliders.  

I've been trying to find a way to add previous and next buttons to the Flickity Page Dots using this code pen as a reference, [Flickity Custom Navigation UI](https://codepen.io/desandro/pen/VLPJqO). 

And here is what I've come up with, [Custom Prev/Next with Flickity Page Dots](https://codepen.io/svpasch/pen/xxZoVoV). 

My issues currently are that the previous and next buttons are not working, and the slides skip to the cell after the next when you click on the page dot. 

I was wondering if I'm on the right track with this and if there is a way to make previous and next buttons work with the page dots instead of creating custom buttons. as well as how to prevent the odd skipping when you click on a page dot. I'm new to jQuery, JS and web design in general so I'm not familiar with advanced jQuery/JS.

Thank you in advance for any feedback!

**Comment by Auromnia** [comment]
*SOLVED*
Updated my CodePen with comments.

**Comment by 1o1developmentadmin** [comment]
can we achieve it through HTML data attributes and without js?
