### ISSUE TITLE
Increase sensitivity for drag/swipe trigger to next/prev slide

### ISSUE THREAD

**Issue by ivandurst** [metafizzy/flickity#1092]
Hello, great carousel! I'd like to adjust the sensitivity (or threshold) for swiping to the next/prev slide - for example, I'd like to be able to only swipe--for example--2px left or right to _move to the next/prev slide_. Note that I'm not asking for `dragThreshold`- I want to actually move to the next slide with less effort, such as on https://www.patagonia.com/product/mens-pack-in-pullover-hoody/20895.html (test swipe on mobile). 

I can't find any examples of this, is there any way to do it outside of manually tracking drag direction and distance, and manually triggering an advance to the next or prev index? If that's the only way, can you share a code snippet? Thanks!

**Comment by SpecBoy99** [comment]
I would love this too, the sensitivity on smartphones is not sensitive enough for my use. A short swipe only moves my content one cell at a time even though I group the cells at two at a time. On a much wider swipe it works fine, but most users won't figure that out as a typical swipe on a phone is not terribly wide.
