### ISSUE TITLE
Flickity carousel, adding a button or a link in the last cell 

### ISSUE THREAD

**Issue by Adambyb** [metafizzy/flickity#1094]
**Test case:** https://codepen.io/desandro/pen/azqbop

Hey guys.

I'm trying to add a button or a link in the last carousel cell, but the button is never being clickable.

The Flickity carousel is lazyLoad images.

If i place the button or the link before or after the carousel it's clickable and functional, but if i place it anywhere in the carousel it's not clickable.

Any idea what should i change in HTML code or CSS

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
