### ISSUE TITLE
Adaptive height

### ISSUE THREAD

**Issue by myconcretelab** [metafizzy/flickity#11]
Is it planned to have a adaptive height or we just build it with event?

Thank you for this great slider that is really sweeter than others

**Comment by desandro** [comment]
Thanks for this request! Currently, no it's not in the plans. If others would like to see this feature, please **+1** this ticket.

Adding adaptive height can be done with a bit of code. I'll follow up once I'm able to produce an example. 

---

Thanks you for this feedback. [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), please email me yo@metafizzy so I can send some your way.

**Comment by myconcretelab** [comment]
Thanks, i has searching for event but not directly find it.

**Comment by lunelson** [comment]
+1 either for building-in the feature, or just callback/events API and classes so we react on changes and reference properties of prev/current/next slides

**Comment by lunelson** [comment]
But it's only logical to do this if the slide width is 100%, otherwise you can still see other content on the slides which is either shorter or higher

**Comment by myconcretelab** [comment]
The slider would take the height of the highest item in the viewport as reference.

**Comment by SRTM** [comment]
If by adaptive height, you mean auto-height, +1.
Would like to see this feature similar to slick/flexslider.

**Comment by gergelypap** [comment]
**+1**, would be neat to have.

**Comment by stefancova** [comment]
+1, it would be nice to no specify height for slider items

**Comment by 72quadrat** [comment]
+1 really an extremely useful feature

**Comment by jonathanolsen** [comment]
+1 really need this when creating sliders that have dynamic height, such as sliders where the content doesn't consist of images. Take the height of the highest element of the slides and apply to the container.

Does anyone know how to to this before the feature is release, if it will be released? I'm struggling with this problem atm.

**Comment by desandro** [comment]
@jonathanolsen 

> Take the height of the highest element of the slides and apply to the container.

Flickity already supports this: http://codepen.io/desandro/pen/ZYvemV

**Comment by mrJlz** [comment]
+1 for adaptive height. I am using flickity for a project right now that needs this feature, and not having this option built in is a real bummer.

**Comment by madebydominick** [comment]
**+1** for this.

**Comment by zslabs** [comment]
+1

Sliders are used for more than just image galleries -- I've even used them for a tabbed interface.

**Comment by jacmaes** [comment]
Another +1

**Comment by notflip** [comment]
+1! Would be amazing

**Comment by notflip** [comment]
I'm using the following as a temporary solution ( in case the user isn't allowed to return to the previous slide )

    var data = $gallery.data('flickity');				
    for(var i = 0; i < data.selectedIndex; i++){
	    $('.gallery-cell:eq(' + i + ')').empty();
    }
    $gallery.flickity('reloadCells');

**Comment by richgcook** [comment]
+1 🍕

**Comment by impsart** [comment]
+1 ... in need of this feature.

**Comment by macbruker** [comment]
+1

**Comment by komunyako** [comment]
#93 — That's mine attempt to implement this feature.

**Comment by ksherman** [comment]
+1!

**Comment by appliculture** [comment]
+1

**Comment by estrattonbailey** [comment]
+1

**Comment by languitar** [comment]
+1

**Comment by anthony0579** [comment]
+1

**Comment by ErikFontanel** [comment]
flickity is my slider of choice, so +1 as well!

**Comment by ianxd** [comment]
+1 !!

**Comment by paulmasek** [comment]
+1

**Comment by kimlarocca** [comment]
+1

**Comment by circa1983** [comment]
+1 for me as well

**Comment by CumpsD** [comment]
+1 Would love this

**Comment by imaginamundo** [comment]
+1

**Comment by chriskaisermann** [comment]
+1 pretty please

**Comment by animaux** [comment]
+1

**Comment by chappydboz** [comment]
+1

**Comment by scottcarver** [comment]
+1

**Comment by kyleoliveiro** [comment]
+1, Flickity is my de-facto carousel plugin, except when adaptive height is a requirement. Would be awesome to see this feature added.

**Comment by brandexponents** [comment]
+1  Please desandro, eagerly looking forward to this feature,  I just love flickity and this feature will simply blow away competition. I have a buit a beautiful image carousel using flickity and would like to use it testimonial / content carousels as well in the same site. I have to include owl carousel or other plugins for this sake :(

**Comment by matthiashonert** [comment]
+1

**Comment by christophermiles** [comment]
+1

**Comment by raywongjr** [comment]
+1

**Comment by brandexponents** [comment]
+1

**Comment by maxariss** [comment]
+100

**Comment by andreylysenko** [comment]
+1

**Comment by jpkempf** [comment]
+1!

**Comment by idiazroncero** [comment]
+1 
I was a bxSlider user until iI came across Flickity. The API, touch events, physic animations, the "asNavFor", the overall performance... there is no competition here: flickity is better.
However, I am missing bxSlider's "adaptiveHeight" feature. For a recent projects, I had to use bxSlider instead of flickity because of this.
I would definitively LOVE flickity to add this feature.

**Comment by laurelstreng** [comment]
+1!

**Comment by vision34** [comment]
+1

**Comment by mikebikeboy** [comment]
Super easy:

slider.on( 'cellSelect', function() {
	var selectedHeight = slider.find('.is-selected').height();
	slider.find('.flickity-viewport').height(selectedHeight);
});

**Comment by vision34** [comment]
your code doesnt worked for me, but you gave me an idea, so i changed it to this solution.

slider.on( 'cellSelect', function() {

        slider.find(  '.flickity-viewport'  ).height(  $(this).find( '.is-selected' ).height()  );	
	
});

**Comment by kevinPire** [comment]
+1

**Comment by jasonwbullok** [comment]
+1

**Comment by viktorbijlenga** [comment]
+1

**Comment by JamesHooker94** [comment]
+1

**Comment by appliculture** [comment]
so many comments and requests, @desandro are you planning to add this feature soon ?

**Comment by chappydboz** [comment]
@vision34's suggestion is working for me.  

$slider.on( 'cellSelect', function() {
    $newTab = $(this).find('.is-selected'); 
    $slider.find('.flickity-viewport').height($newTab.height());        
});

**Comment by aaronstezycki** [comment]
Made a few simple changes to get this working.

On line 2242 changed to:
```
this.viewport.style.minHeight = this.maxCellHeight + 'px';
```

Then to give it a nice transition 
```
 .flickity-viewport { transition: min-height 0.5s ease-in-out; } 
```

**Comment by matthewhirsch** [comment]
+1

**Comment by sector5** [comment]
+1

**Comment by sector5** [comment]
Seems to work with something like this:
Line 2239:
```javascript
Flickity.prototype.setGallerySize = function() {
  if ( this.options.setGallerySize ) {
    var height = this.maxCellHeight;
    if ( this.options.adaptiveHeight && this.selectedCell !== undefined ) {
      height = this.selectedCell.size.height;
    }
    this.viewport.style.height = height + 'px';
  }
};
```

Line 2380 (after the code above has been added):
```javascript
Flickity.prototype.setSelectedCell = function() {
  this._removeSelectedCellClass();
  this.selectedCell = this.cells[ this.selectedIndex ];
  this.selectedElement = this.selectedCell.element;
  classie.add( this.selectedElement, 'is-selected' );
  if ( this.options.adaptiveHeight ) {
    this.setGallerySize();
  }
};
```

The use the option "adaptiveHeight". If you want a nice transition use @aaronstezycki suggestion:
```css
 .flickity-viewport { transition: min-height 0.5s ease-in-out; } 
```

**Comment by mavrck** [comment]
+1

**Comment by sambaldwin** [comment]
+1

**Comment by Fequois** [comment]
OK, I don't know if I misunderstood the request, but I came up with a solution to a problem I came here looking for: using Flickity and Packery together, where Packery would fail to properly align other elements due to `.flickity-viewport`'s explicitly set height.

However, it does depend on knowing the initial dimensions of the gallery as I'm effectively just setting an "aspect ratio." I'm pretty sure there's a more elegant solution resting in a more elegant mind somewhere.

What I did is this:

1. Set `setGallerySize` to `false`.
2. Add the following styles (apologies for the Sass and nesting):

`.flickity-viewport {
  &::before,
  &::after {
    content: "";
    display: block;
  }

  &::after {
    // % = height ÷ width
    padding-top: 40%;
  }
}`

Apologies if this is completely irrelevant.

**Comment by erickmonteiro** [comment]
Hello guys,

download and test the test of automatic height.

changed js files flickity.js and sandbox/autoheight.html

https://github.com/erickmonteiro/flickity

**Comment by desandro** [comment]
@erickmonteiro Thanks for taking a shot at this! :tangerine:

**Comment by daviestar** [comment]
@erickmonteiro I've tried out your solution and it works well in my project, which is a simple image gallery, where each image is 100% width of the viewport, and on list pages I use multiple galleries with no issues found.

I did notice the framerate of both the flickity horizontal animation, using `requestAnimationFrame`, and the vertical animation using CSS `transition` are way lower than without the dynamic viewport height.

Here's an attempt to decouple the animations which may improve fps:
```html
<!-- How it currently works -->
<div class="flickity">
    <div class="flickity-viewport" style="transition: height 300ms ease-out; height: 400px;">
        <div class="flickity-slider" style="left: 0px; transform: translateX(0%);">
            <img class="item" />
            <img class="item" />
        </div>
    </div>
</div>

<!-- Variation -->
<div class="flickity">
    <div class="flickity-resizer" style="transition: height 300ms ease-out; height: 400px;"></div>
    <div class="flickity-viewport" style="position: absolute; top: 0; height: 100%;">
        <div class="flickity-slider" style="left: 0px; transform: translateX(0%); height: tallestItem;">
            <img class="item" />
            <img class="item" />
        </div>
    </div>
</div>
```

**Comment by warreb1** [comment]
@erickmonteiro the new approach seems to work perfect. I'll test this extensively on some new projects and will report back.

**Comment by sashabeep** [comment]
Wrong viewport height by default on page load
When i switch to 2nd slide ang back to 1st - recalculated to normal

**Comment by daviestar** [comment]
@sashabeep try `imagesLoaded: true`

http://flickity.metafizzy.co/options.html#imagesloaded

**Comment by sashabeep** [comment]
@daviestar thanks, now correct

**Comment by mnlearth** [comment]
Definitely +1

**Comment by rtklwm** [comment]
+1

**Comment by sdempsey** [comment]
+1

**Comment by desandro** [comment]
**Let's do it.** Flickity v2.0 will have an adaptive height feature. ETA is Spring 2016. Thanks so much for your interest over the past year. Just sit tight a bit longer :clock11:

**Comment by aaronstezycki** [comment]
@desandro :+1: 😁

**Comment by craigmdennis** [comment]
+1

**Comment by desandro** [comment]
Flickity v2 it out now, with new [`adaptiveHeight` option](http://flickity.metafizzy.co/options.html#adaptiveheight).

Set `adaptiveHeight: true` to change the viewport height to the height of the selected slide. [See demo on CodePen](http://codepen.io/desandro/pen/dXVXYj). Use CSS transitions to transition height changes.  [See demo on CodePen](http://codepen.io/desandro/pen/PzJzPv) But heads up: transitioning height triggers reflow and may cause poor performance. 

``` css
.flickity-viewport {
  transition: height 0.2s;
}
```

This issue is now closed 🎉 . Thanks for all your feedback 😊
