### ISSUE TITLE
Slider to only scroll through full (contained) images without overflow

### ISSUE THREAD

**Issue by adrian0007** [metafizzy/flickity#1100]
Hi @desandro and many thanks for your work!

I'm trying to create something very simple, and I'm sure that I'm missing something:

A logo slider that displays full, contained images only (not half of the previous and half of the next)

I wrote a little codepen which reflects what I'm trying to build: https://codepen.io/lsdigital/pen/oNxwgqL

Any thoughts on what I'm doing wrong, please?

**Comment by desandro** [comment]
Looks like you can remove `max-width` on `.section1-inner`.

See demo https://codepen.io/desandro/pen/f176e03151f2c689824a370622ad6a08
