### ISSUE TITLE
Documentation does not contain usage instructions after installing with npm

### ISSUE THREAD

**Issue by kadetXx** [metafizzy/flickity#1101]
I just installed flickity js with npm and after the installation was complete, i had no idea how to link it with my codes. I checked the docs and searched everywhere else but couldn't find anything. It'll be nice if instructions regarding this issue are added to the docs and the readme file as well.

**Comment by jwrunner** [comment]
Here is an implementation example: https://svelte.dev/repl/6d203ee5296c47b094771a0be1ea1572?version=3.29.0
