### ISSUE TITLE
How to select the cell automatically when the anchor point reached?

### ISSUE THREAD

**Issue by nsrplanet** [metafizzy/flickity#1102]
Hello,

I use Flickity as mobile navigation for a page within my website. This page have several anchor points defined by element id. When i scroll within the page it is possible to highlight the correspondig cell (link text). But how can i configure the script in order to select the cell automatically depending to the section where the user is?

![screenshot](https://user-images.githubusercontent.com/70637304/91970815-81267280-ed18-11ea-9738-6dd51c0b6ebd.png)

https://codepen.io/Nsrplanet/pen/KKzXOdN

Thanks,
NsrPlanet

**Comment by desandro** [comment]
You'll need to add an event listener on scroll, calculate the positions of the the anchored elements, calculate which element is closest. It's a non-trivial problem that I leave to you.
