### ISSUE TITLE
Carousel Breaks if using with Angular ngFor update

### ISSUE THREAD

**Issue by Crazyprogrammer1** [metafizzy/flickity#1103]
I am creating the carousel using dynamic data from array using Angular ngFor : 

```
<div class="carousel">
          <div *ngFor="let card of Cards; let index = index" class="slide carousel-cell">
        
         </div>
        </div>
```

Now when there is an update on Cards array, the carousel is breaking. I have to re initialize the carousel to make it work, But if I reinitialize the carousel. there is one blink effect which is obviously due to re initializing the carousel. How do I make it work without re initializing the entire carousel on Array update

**Comment by AlexHodzitsky** [comment]
Yo! Check this out https://flickity.metafizzy.co/api.html#adding-and-removing-cells. Instead of re-initialization, you can use such API methods as append/prepend/insert/remove.
