### ISSUE TITLE
Add random offset when the "selectCell" method stops

### ISSUE THREAD

**Issue by aethletic** [metafizzy/flickity#1104]
Hello!

Can I set an offset to stop when using the `selectCell ` method? 
So that the indicator does not stop exactly in the center, but stop to the left or to the right by a var that I could set, for example from -10px to 10px random choice?

https://codepen.io/blyaa/pen/BaKJJVy

**Comment by aethletic** [comment]
Okay, I found this option: `cellAlign: 0.5, // 0.4 for right | 0.6 for left `
Is it possible to set a new value every time before calling the `selectCell `method?

**Comment by desandro** [comment]
I do not recommend setting a custom `cellAlign` for individual cells.
