### ISSUE TITLE
Hiding the active item of a navigation ('asNavFor') slider

### ISSUE THREAD

**Issue by HarryFrancis** [metafizzy/flickity#1105]
Hello!

I am working on a slider similar to this: https://codepen.io/harryfrancis-the-encoder/pen/mdPjJYo

It's working really nicely, except I'd like to hide the active item in the carousel navigation, so it only shows in the main carousel.

I've tried a few ways:

- Hiding it with display none. This kept it's width but hid the slide content.
- Offsetting the carousel navigation with a left -xx%, this moved the right content over too (also tried using transforms to correct this but couldn't get it working as I wanted)

I was wondering if there might be a nicer way/any way to do this, and if anyone had any ideas?

Thanks, Harry.

**Comment by desandro** [comment]
Thanks for reporting this issue.

If you wish to remove or change the size of a cell, you likely need to trigger [reposition](https://flickity.metafizzy.co/api.html#reposition) after the cell has been changed.

Or you may want to use [remove](https://flickity.metafizzy.co/api.html#remove) and then `insert` to add it back
