### ISSUE TITLE
Issue with infinite not showing slides in order.

### ISSUE THREAD

**Issue by CHEWX** [metafizzy/flickity#1107]
Hi,

I have a slideshow on mobile, where it shows the snippet of the next slide, I do this by simply changing `.flickity-viewport { overflow: visible; }`. This works without hitch. However, on load you cannot see the next slide until you interact.

**Test case:** https://codepen.io/CHEWX/pen/oNxabQN

Be good to see if anyone has a fix for this.

Thanks

**Comment by desandro** [comment]
Looks like `wrapAround` being enabled is what is causing the missing the cells. This is because wrapAround moves cells between the front and back. So I think the only solution is to disable wrapAround if you want this extra preview feature to work
