### ISSUE TITLE
Carousel is working very slowly if I have 300+ Slides

### ISSUE THREAD

**Issue by Crazyprogrammer1** [metafizzy/flickity#1108]

**Comment by wannesdebacker** [comment]
Don't punish your users with 300+ slides loaded into one page, load a couple and add and remove slides asynchronously.

**Comment by Crazyprogrammer1** [comment]
@wannesdebacker I am generating the slides using Angular *ngFor, and If I add and remove the data in the array from which I am generating the slides, Its not refreshing the carousel with new data

**Comment by desandro** [comment]
I feel that 300 slides is well outside the bounds of what any carousel plugin should be expected to handle. Sorry, I leave this one with you.
