### ISSUE TITLE
Adaptive Height Calculation

### ISSUE THREAD

**Issue by rolenzian648** [metafizzy/flickity#1110]
Hi All!

I have a slider here on the testimonial section. However, the slider stills calculate a height that is not accurate most of the time. Having a big blank space between the buttons and the paragraph slider.

Let me know what the issue is.

Also, making adaptive height and auto scroll at the same, can it make the site now wobbly on mobile? the site is moving all the time when those two are enabled

Here's the site 
https://bachperformance.com/

Thanks

**Comment by rolenzian648** [comment]
Hi! still no updates regarding this ?

**Comment by khoipro** [comment]
You should call `slider.resize()` after the slider has been init.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
