### ISSUE TITLE
Wrap only from right side?

### ISSUE THREAD

**Issue by Kcko** [metafizzy/flickity#1111]
Hi,
is possible to create slider with wrapping from right side only?

Demo is from both side, and i need only from right side.

**Comment by CHEWX** [comment]
You can just hide the left hand side with an element? If you supply a re-production link.

**Comment by Kcko** [comment]
Hi,
I need this https://bit.ly/34hvV7C but this slider solve it http://swiperjs.com/

**Comment by CHEWX** [comment]
Yes you can complete this with Flickity.

This is not an issue with Flickity and you have solved the issue, please close.

**Comment by Kcko** [comment]
I couldn't handle it with flickity ... 

No available settings in flickity helped me and I don't see anything in the examples.

**Comment by CHEWX** [comment]
If you re-produce the above in a CODEPEN link I can help you, but it's not an issue with Flickity.

**Comment by desandro** [comment]
Sorry, Flickity does not support `wrapAround` from only the ending side.
