### ISSUE TITLE
Next-Previous arrows are not working properly

### ISSUE THREAD

**Issue by lightmar** [metafizzy/flickity#1113]
Hello,

The Flickity slider came installed with my Shopify theme Prestige.
By default the Next and Previous arrows are not enabled in the product gallery, but my client asked for them so I simply enabled them in the parameters.
The arrows now show up, but after two clicks on the next button, the images are not showing anymore.
Please help me to fix this issue.
The website url is: https://www.leebonk.com/collections/all-jewelry/products/sabrina-round-signet-druzy-gemstone-ring

Thank you!

**Comment by CHEWX** [comment]
This is password protected...

**Comment by chrisvidal** [comment]
similar issue on a custom theme. How did you solve the issue please?

**Comment by tarin-swanky** [comment]
I'm having this issue at the moment, any fix for this?
