### ISSUE TITLE
Request demo for including clickable links

### ISSUE THREAD

**Issue by s-canchi** [metafizzy/flickity#1114]
Hi,

Flickity is awesome!  I am relatively inexperienced in all things websites (html, css, javascript) but thanks to the detailed demos and snippets, I was able to incorporate Flickity into my organization's website which uses [Material Theme for MkDocs ](https://squidfunk.github.io/mkdocs-material/)and hosted on [Read the Docs](https://readthedocs.org). 
However, there is a requirement to make the included images clickable and linked to existing website content. I couldn't find any closed or open issues that addressed this point. I implemented a widely suggested solution of adding anchor tags but that did not resolve it as I get a 404 error.

```
<div class="carousel-cell"
     <a class="carousel-cell" href='./path_to_webiste_link''><img class="carousel-cell-image" data-flickity-lazyload="./images/carousel-images/carousel-images.002.jpeg" alt="grapes" /></a>
 </div>  
```
Any demo code or suggestion for how I would achieve the linkable image slider is greatly appreciated! Please let me know if I should submit any additional context or code.

**Comment by CHEWX** [comment]
This isn't to do with Flickity. 

Change:

`<a class="carousel-cell" href='./path_to_webiste_link''>`

to

`<a class="carousel-cell" href="/path_to_webiste_link">`
