### ISSUE TITLE
Page dot text is not descriptive (arguably not accessible)

### ISSUE THREAD

**Issue by tbredin** [metafizzy/flickity#1116]
Firstly thanks for building a great plugin.

I wanted to raise an issue that — without building an entirely custom navigation — the page dot text doesn't appear to be customisable, and the default text is not particularly accessible.

Proposal:
- Add config options for `pageDotText` and `pageDotTextSelected`
- Default these to something more descriptive, I would like to suggest something like:
  - `pageDotText: "Move carousel to page ${pageIndex}`
  - `pageDotTextSelected: "Carousel page ${pageIndex}: currently active"`

Additionally, [I agree with this issue about the use of li's](https://github.com/metafizzy/flickity/issues/777), and would like to suggest that these would be most appropriately changed to `button` elements since they do not navigate you away from the page or anchor you to a region on the page (so an `a` element is not quite appropriate either).

**Comment by desandro** [comment]
Than you for this suggestion. As this relates to #777, I'm moving your suggestion over there, so we can keep all the page dot accessibility stuff in one place.
