### ISSUE TITLE
How do I enable/disable the carousel with JavaScript?

### ISSUE THREAD

**Issue by produktive** [metafizzy/flickity#1117]
How can you enable/disable the carousel on demand with JavaScript? Such as if you click a button, disable all interaction with the carousel without destroying it.

**Comment by CHEWX** [comment]
Not sure there is a flickity method for this as it's an unusal use-case, you'd normal destroy it.

As such, you could add a class to flickity that sets `.flickity * { pointer-events: none; }`.

**Comment by produktive** [comment]
Interesting, I'll try that.

**Comment by k1ll1n** [comment]
Hello!
For me this question is also interesting

> As such, you could add a class to flickity that sets .flickity * { pointer-events: none; }.
This is an interesting solution, but I need the child elements to remain active, or rather only the element that is currently selected

I would like to pause the slider, it would be a great solution for me.

**Comment by k1ll1n** [comment]
I solved my problem like this:
```js
let flkty = new Flickity()
...
flkty.options.draggable = false | true
flkty.updateDraggable()
```

**Comment by desandro** [comment]
There are two undocumented methods `activate` and `deactivate`. Try those!
