### ISSUE TITLE
Question about OS license

### ISSUE THREAD

**Issue by powerbuoy** [metafizzy/flickity#1118]
Hi,

Thanks for the best slideshow library in 2020!

I have a question regarding the open source license.

I've created my own UI library that consists of common UI elements, written in SASS and JS. It's licensed under GPL-3.0: https://github.com/powerbuoy/sleek-ui

If I understand correctly I'm free to include Flickity in my project (well its package.json at least) - is that correct?

What if I were to use my own open source project in a commercial project - would that still be fine?

Thanks.

**Comment by desandro** [comment]
As you have open sourced this UI library, this usage is compliant with GPL-3.0. You can then use that library in other projects, but those projects may need to be open-sourced as well to be GPL compliant.
