### ISSUE TITLE
LazyLoad next slide (but not previous slide)

### ISSUE THREAD

**Issue by JoshuaHaymann** [metafizzy/flickity#1122]
Hello all,
When you add LazyLoad : 1, my understanding is that it will preload the slides after and before the current slide.
As I'm making a carousel in which you can only go forward and not backwards, is there a way to ask to LazyLoad only the next slide, or the next 2 slides?
Thanks in advance

**Comment by desandro** [comment]
Sorry, technically Flickity does not not support this behavior. But if you are making a carousel that only progresses forward, then you will only be lazy-loading next slides anyway.
