### ISSUE TITLE
item with mx margin sticks to the left side

### ISSUE THREAD

**Issue by mokhosh** [metafizzy/flickity#1123]
Notice here (you might need to refresh or modify some text in the code for the render to be refreshed) the box is stuck to the left side, but as soon as you resize the render section a bit it sticks to the middle which is the expected behaviour in the first place.

https://codepen.io/mokhosh/pen/rNLpgKO

**Comment by desandro** [comment]
Thanks for reporting this isssue. I'm having trouble seeing the issue, This carousel has `"groupCells": true,  "contain": true` and cells are being positioned according to that behavior. What am I missing?

**Comment by mokhosh** [comment]
Thanks for responding, I can't see the issue either, and it's so far in the past that I don't remember the specifics.
