### ISSUE TITLE
How To Change Group Cells Value on Browser Resize

### ISSUE THREAD

**Issue by SpecBoy99** [metafizzy/flickity#1124]
Flickity is great and grouping cells works fine except on browser **resize** where I'm changing the cell widths at four CSS breakpoints. I use matchMedia as shown in the "Extras" documentation to set different groupCells values on site **load** but need to also do so on browser **resize**. The only thing I can think of is to call the API destroy method and re-initialize the carousel, but that seems like a big performance hit and maybe cause page redraw flashing? 

Thanks anyone for any help!

**Comment by desandro** [comment]
>  The only thing I can think of is to call the API destroy method and re-initialize the carousel, but that seems like a big performance hit

Yes, that is one way.

[groupCells](https://flickity.metafizzy.co/options.html#groupcells) can be set to a percentage of the carousel width, however many cells fit within that width will be set as a group. This way you wouldn't have to re-set `groupCells` explicitly.
