### ISSUE TITLE
Flickity weird result if not enough items

### ISSUE THREAD

**Issue by sbalet** [metafizzy/flickity#1128]
Hello,

I love this plugin and use it as soon as I can (I have bought the licence). I have a problem on a sports site. We have a list of sports categories, but there are not many elements, in fact I think not enough for Flickity to loop efficiently on big screens as we can see the items move and reposition to the right in order to loop. Also the groupCells 80% with low opacity on non selected elements gives weird results: on page 1 four elements are selected, page 2 there is only one.

Any solution for this ? Thanks in advance

**Test case:** https://codepen.io/stebal/pen/vYKPoew 
(this text case should be watched on a large screen, 1800px show the problem well)

**Comment by desandro** [comment]
Sorry, there is no good solution, but I do have a proposal that could help in the future. See #809
