### ISSUE TITLE
have error when load cell by js

### ISSUE THREAD

**Issue by wtubby** [metafizzy/flickity#1129]
i have error when  ajax change content
some like this 
https://codepen.io/wtubby/pen/jOrogdq

**Comment by desandro** [comment]
If you're going to add jQuery code, I recommend [initializing Flickity with jQuery](https://flickity.metafizzy.co/#initialize-with-jquery) instead of HTML. 

``` js
let $carousel = $('.carousel').flickity({
  pageDots: false,
  imagesLoaded: true,
  wrapAround: true,
  cellAlign: "left",
});

$('.button').on( 'click', function() {
  var $cellElems = $('<div class="carousel-cell">5</div><div class="carousel-cell">6</div><div class="carousel-cell">7</div><div class="carousel-cell">8</div>');
  $carousel.flickity( 'append', $cellElems );
});
```

Also, be sure to order `jquery.js` before `flickity.js`

See demo https://codepen.io/desandro/pen/692bc166bb0124bb3d6fb87310345162
