### ISSUE TITLE
select closest cell with wrapAround

### ISSUE THREAD

**Issue by outsetrin** [metafizzy/flickity#113]
Hi, so with the wrapAround option turned on,  when the last slide of the gallery is selected, we can see the first slide on its right.

Using the "select" function, we click on the first slide on the right and it is being selected. But when we would expect the slider to go over one slide to the right, the animation happens to the left, going over all the slides up to the first one, as it would have happened without the wrapAround option.

Here is the Pen to illustrate the issue.
http://codepen.io/anon/pen/WveLRJ
With the slide 5 selected, click on the slide 1 on the right.

Same issue when on the first slide and clicking on the last slide to the left.

**Comment by desandro** [comment]
Thanks for the feature request. I'm considering adding in an extra parameter so that selecting a cell with wrapAround will take the shortest route.

**Comment by outsetrin** [comment]
The route could be equally long in both directions (slide 3 in a 4-slide gallery) so the answer might be closer to the navigation arrow behavior...
But the shortest route parameter could be needed I guess, because I have seen that, with freeScroll option enabled, if you spin the slider real hard so that it goes over all the slides one or more times, and then you click one slide with the "select" option, the slider will go back one or more times to find the slide, even if the slide was at the center of the screen to begin with.

**Comment by hirasso** [comment]
Another way could be to send an element to the select method instead of an index id: 
```javascript
$(".gallery-cell").click(function() {
  if( !$(this).hasClass("is-selected") ) {
    flkty.select( $(this) );
  }
});
```
That way flickity would know where to move to

**Comment by desandro** [comment]
Another demo with asNavFor demonstrating the problem: http://codepen.io/desandro/pen/ZYqNrO

**Comment by drastick** [comment]
Just wondering what the status of this is and if any work on it has been started?  This is something we need and I would be willing to help out on it.

**Comment by notflip** [comment]
What is the status on this issue? Thank you

**Comment by netnak** [comment]
I also need a fix for this issue. Any updates?

**Comment by Frobitz** [comment]
Yeah, could do with a solution for this also :+1:

**Comment by maxackerman** [comment]
+1 would be great to have wrapAround take the shortest path

**Comment by dinealbrecht** [comment]
+1 shortest path option please!

**Comment by adrienlamotte** [comment]
+1 :)

**Comment by jasonwbullok** [comment]
+1

**Comment by desandro** [comment]
Flickity v2 is out now, [with new select behavior for `wrapAround`](http://flickity.metafizzy.co/options.html#wraparound) that selects the closest slide. Try selecting the 5th slide while at the 1st to see it in action.

Closing this issue now :tada: Thank you for your feedback!

**Comment by gavin310** [comment]
@desandro This is still an issue when there's only two slides. What if there's an option to always match the synced slider's direction? So if SliderA has `navNavFor: '.slider-b'` and you swipe SliderA from right-to-left, SliderB will always slide right-to-left?
