### ISSUE TITLE
Preventing js actions on dragging

### ISSUE THREAD

**Issue by SpabRice** [metafizzy/flickity#1130]
Hello,

When dragging the carousel it doe not take action of the anchor tags which are inside the cells. 
But if this anchor tag has any javascript connceted, the javasrcript is firing.
Example: http://jsfiddle.net/mqw31zd2/

Is there a possibility to prevend this?
I'm trying to combine the fancybox with flickity and the fancybox is always opening when dragging the carousel.

Thanks

**Comment by desandro** [comment]
Use [staticClick](https://flickity.metafizzy.co/events.html#staticclick) instead of click.

Also, you may want to look at [flickity fullscreen](https://flickity.metafizzy.co/options.html#fullscreen) instead of Fancybox
