### ISSUE TITLE
Image not appearing in mobile

### ISSUE THREAD

**Issue by loafymold** [metafizzy/flickity#1132]
Images is not appearing on in mobile size but only laptop screen size.
 My codepen: (https://codepen.io/jl-joey/pen/ZEpbONK)

Things that I done:

installed https://unpkg.com/flickity@2/dist/flickity.min.css" and https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js

write data-flickity="{ 'imagesLoaded': true }" in carousel div

<script>
var flkty = new Flickity('.carousel',{
	imagesLoaded: true
});
var carouselStatus = document.querySelector('.carousel-status');

function updateStatus() {
  var slideNumber = flkty.selectedIndex + 1;
  carouselStatus.textContent = slideNumber + '/' + flkty.slides.length;
}
updateStatus();

flkty.on( 'select', updateStatus );

</script>`

Am I missing something?

**Comment by desandro** [comment]
I'm able to see the images. Is this issue still a problem?

<img width="499" alt="image" src="https://user-images.githubusercontent.com/85566/103020911-5191b500-4517-11eb-903a-98fc4dbd8eee.png">

**Comment by aariacarterweir** [comment]
Looks like this might be an intermittent issue. We're seeing this happen on and off on `2.2.0 - 2.2.2`.  Havent tested any other versions. Running latest version of flickity-imagesloaded
