### ISSUE TITLE
Question about Dynamic Imports

### ISSUE THREAD

**Issue by strandofgenius** [metafizzy/flickity#1133]
I am using webpack and dynamically importing chunks something like the following. This will output flickity as its own js chunk in my dist folder, but the issue is initiating flickity `new Flickity( elem )` because Flickity is not defined. Any direction to accomplish this?

``` js
const main = async() => {
    await import(/* webpackChunkName: "flickity" */ 'flickity');
};
// Execute async function
main().then(() => {
});

document.addEventListener('DOMContentLoaded', function() {
      new Flickity(elem);
});
```

**Comment by desandro** [comment]
Looking at [Webpack Dynamic Imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports), you'll need to get Flickity from the `default` argument returned from `import`. If you're using async / await, I would rewrite it as such:

``` js
async function importFlickity() {
  const { default: Flickity } = await import('flickity');
  return Flickity;
}

importFlickity.then( ( Flickity ) => {
  document.addEventListener('DOMContentLoaded', function() {
    new Flickity(elem);
  });
});
```

**Comment by strandofgenius** [comment]
@desandro thanks for the direction. I discovered after some trial and error having the event listener wouldn't trigger because it was after the dom was already loaded. This is what my file looked like.

```js
async function importFlickity() {
    const { default: Flickity } = await import(/* webpackChunkName: "flickity" */ 'flickity');
    return Flickity;
}

importFlickity().then((Flickity) => {
    const elem = document.querySelector('.carousel');
    new Flickity(elem);
});
```
