### ISSUE TITLE
Hard to swipe/drag within large groupCells

### ISSUE THREAD

**Issue by bahung1221** [metafizzy/flickity#1135]
Thanks for an amazing library, I'm using Flickity to create a fullscreen width slider, each `groupCells` inside slider are fullscreen width, too. The problem is It slightly hard to drag the slider by `laptop touchpad` because Flickity required the drag ratio must be larger than 50% width of the group to trigger the slider move handler.

On other sliders, it normally has an option to modify the `drag ratio`, e.g. [longSwipesRatio of Swiper](https://swiperjs.com/api/#components)

**Test case:** https://codepen.io/bahung1221/pen/rNMdGbw
**Image**:
![Screen-Recording-2021-01-03-at-1 (1)](https://user-images.githubusercontent.com/27690861/103476507-1df13d80-4de9-11eb-8195-41a141af9b58.gif)

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue and for providing a reduced test case.

Just to be clear about what's happening: When you drag, stop, then release, the slider will re-position to the closest slide.

https://user-images.githubusercontent.com/85566/103487665-0b6d0900-4dd5-11eb-8891-9fe60746e72b.mov

But when you drag & release while dragging, the slider will select the next slide. In fact, you barely have to move the slide at all to get to the next slide as Flickity has extra boost behavior make this motion easier.

https://user-images.githubusercontent.com/85566/103487690-3b1c1100-4dd5-11eb-8170-ede162fb08bd.mov

---

Now then, what is considered a 'flick' is when the mouse/touch pointer moves between the current and previous frame. There may be a case where you did move the pointer, but not on that last frame. If that's the case, it may be worth exploring calculating with more frames to compensate for this issue.

**Comment by bahung1221** [comment]
> But when you drag & release while dragging, the slider will select the next slide. In fact, you barely have to move the slide at all to get to the next slide as Flickity has extra boost behavior make this motion easier.

It seems that the touchpad on my macOS doesn't support this behavior, even when I release the drag immediately while dragging, maybe cause by the drag `inertia/momentum` of macOS?

> Now then, what is considered a 'flick' is when the mouse/touch pointer moves between the current and previous frame. There may be a case where you did move the pointer, but not on that last frame. If that's the case, it may be worth exploring calculating with more frames to compensate for this issue.

Yes, It will be more flexible and also resolve the issue on the macOS touchpad above 😄

**Comment by desandro** [comment]
> It seems that the touchpad on my macOS doesn't support this behavior

Ah, what version of macOS are you running? I'm still on Catalina

**Comment by bahung1221** [comment]
I'm on macOS 11.1 (Big Sur).  I'm trying to change some touchpad settings but no luck (disabled scrolling inertia), not sure what was caused this issue 😢

**Comment by anilyeni** [comment]
it would be great if there was a setting for this one. i don't want it to be repositioned by the distance, it would be better if it goes to next slide depends on the direction of the swipe. may we have something like "dragThreshold" setting, which will decide to reset to previous position or switch to next slide depends on the pixels that it moved ? like: "swipeThreshold: 10px" if it moves 10px or more, don't reset, swipe to next.

**Comment by desandro** [comment]
I think this issue was related to scroll bugs in iOS, not necessarily the dragging the behavior itself. This has been resolved along side #1177
