### ISSUE TITLE
When resizing window, margin between cells/slides not respected during resizing

### ISSUE THREAD

**Issue by ironchef-bklyn** [metafizzy/flickity#1136]
https://codepen.io/ironchef-bklyn/pen/Exgpmgq

I have a set amount of margin defined between cells.

When resizing window to a smaller size, the tiles overlap each other during the transition to a smaller size.  When making the window bigger, there is more space between the tiles during the transition. Once the resizing, stops, they settle back to the defined margin.

Is there a way for flickity to respect the margin during window resizing?

**Comment by desandro** [comment]
Try setting [`"percentPosition": false `](https://flickity.metafizzy.co/options.html#percentposition). See demo https://codepen.io/desandro/pen/qBaJvPN
