### ISSUE TITLE
Parsing data-flickity on flickity-enabled is-draggable is-fade: SyntaxError: Unexpected token ' in JSON at position 1

### ISSUE THREAD

**Issue by cadalzolc** [metafizzy/flickity#1137]
**Test case:** https://codepen.io/desandro/pen/azqbop

**Comment by cadalzolc** [comment]
I have used flickity in asp.net core but this error is showing up. my slider is not working properly.

parsing data-flickity on flickity-enabled is-draggable is-fade: SyntaxError: Unexpected token ' in JSON at position 1

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you copy/paste your [HTML initialization code](https://flickity.metafizzy.co/#initialize-with-html)? Sounds like there is a JSON syntax error in there.

**Comment by cadalzolc** [comment]
I found the issue, the data attribute: 
`data-flickity="{'prevNextButtons': false, 'fade': true, 'bgLazyLoad': 1, 'autoPlay': true }" `
was changed to this format.
`data-flickity='{"prevNextButtons": false, "fade": true, "bgLazyLoad": 1, "autoPlay": true }' `
