### ISSUE TITLE
Multiple cells in groups per button

### ISSUE THREAD

**Issue by mikehermary** [metafizzy/flickity#1139]
Hello,

I am using this example (https://codepen.io/desandro/pen/mEBAXR) to try and setup a history timeline carousel for my client's website. I have forked that example (https://codepen.io/mikehermary/pen/GRjeOrR) to illustrate a basic example with two slides per button. Some buttons will have multiple slides in each group assigned to it. The buttons when clicked/tapped should display the first slide in each group. The class .is-selected should be applied to the buttons.

I have a built out an example here: http://staging.medicineriverwildlifecentre.ca/about-us. The carousel is halfway down the page. The slide groups are labelled with groupone, grouptwo, etc. As you will see, the buttons do connect to the first slide in each group, but the first button does not return the carousel to the first slide. Also, the .is-selected class is not changing when a different button/link is clicked/tapped.

Please note: grouped slides will not be visible together in the viewport.

Screenshot of full design:

![history-timeline-example](https://user-images.githubusercontent.com/879989/105113065-7418de80-5a81-11eb-8441-bc3bb614a50b.png)

Any suggestions are greatly appreciated.

Cheers,

**Comment by desandro** [comment]
as there are more cells than nav items, you'll need a way to match the cells to respective nav item. You already have the data in the cell `class`, but I would move that out into its own custom attribute `data-group`. See demo on CodePen  https://codepen.io/desandro/pen/jOMooLX

``` html
  <div class="carousel-cell" data-group="cell3"></div>
```


``` js
buttonGroup.addEventListener( 'click', function( event ) {
  // filter for button clicks
  if ( !matchesSelector( event.target, '.button' ) ) {
    return;
  }
  let group = event.target.dataset.group;
  flkty.selectCell(`[data-group="${group}"]`);
});

let selectedNavButton = buttonGroup.querySelector('.is-selected');

flkty.on( 'change', function() {
  let group = flkty.selectedElement.dataset.group;
  let navButton = buttonGroup.querySelector(`[data-group="${group}"]`);
  if ( navButton != selectedNavButton ) {
    selectedNavButton.classList.remove('is-selected');
    navButton.classList.add('is-selected');
    selectedNavButton = navButton;
  }
})
```

**Comment by mikehermary** [comment]
@desandro Thank you very much for the code. I really appreciate it. Cheers.
