### ISSUE TITLE
Add is-animated class to flickity container

### ISSUE THREAD

**Issue by danielvonmitschke** [metafizzy/flickity#114]
Could we add an "is-animated" class to the flickity container or flickity-slider div?
This way we could hide some stuff via css while a transition is in progress.

**Comment by desandro** [comment]
Interesting request. You can duck-punch a solution. See http://codepen.io/desandro/pen/vOYxNL. Add this code:

``` js
// duck-punch startAnimation
var startAnimation = Flickity.prototype.startAnimation;
Flickity.prototype.startAnimation = function() {
  if ( this.isAnimating ) {
    return;
  }
  // do regular
  startAnimation.apply( this, arguments );
  classie.add( this.element, 'is-animating' );
  this.once( 'settle', this.removeAnimatingClass );
};

Flickity.prototype.removeAnimatingClass = function() {
  classie.remove( this.element, 'is-animating' );
};
```

---

**+1** this issue if you would like to see this feature added.

**Comment by danielvonmitschke** [comment]
Great this works for me.
Thanks!

**Comment by desandro** [comment]
Closing this issue as it hasn't received much interest :ghost:
