### ISSUE TITLE
[2.2.1] Overlapping layers when text content too long, fixes on resize window

### ISSUE THREAD

**Issue by DrLightman** [metafizzy/flickity#1144]
On the far right:

<img src="https://i.ibb.co/BK6Qz9p/Immagine-2021-02-25-152142.png">

This fixes itself when I resize the browser window in any way.

The object has been created with these option in my purchased theme:

```js
$obj.flickity({
    wrapAround:         true,
    autoPlay:           5000,
    cellAlign:          'left',
    prevNextButtons:    true,
    pageDots:           false
});
```

All I can do in order to fix this thing is execute some code at the document ready event.

Tried to issue a `$(window).trigger('resize');` after the obj.flickity-enabled was found but it didn't sort the desired effect.

Any idea of some method I can call or execute on the flickity element?

**Comment by DrLightman** [comment]
Hallo?

**Comment by tsargent** [comment]
I am getting similar behavior. When I resize the browser, it looks correct. It just does not seem to initialize correctly.

**Comment by Chrys-Nicolaides** [comment]
I am also experiencing this issue - however only when this using Flickity inside a modal that is conditionally rendered using react.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

As a hack, after initializing Flickity, you may need to trigger the [resize method](https://flickity.metafizzy.co/api.html#resize)

``` js
// jQuery
$carousel.flickity('resize')

// vanilla JS
flkty.resize()
```
