### ISSUE TITLE
Flickity default options

### ISSUE THREAD

**Issue by danielvonmitschke** [metafizzy/flickity#115]
Is there a way to set default options for all flickity instances and then just trigger flickity with the js-flickity class.
If so, would it then be also possible to override these default options via the data-flickity-options attribute?

**Comment by desandro** [comment]
> Is there a way to set default options for all flickity instances and then just trigger flickity with the js-flickity class.

Yes, you can overwrite default Flickity options in JavaScript.

``` js
// jQuery
$.extend( Flickity.defaults, {
  cellSelector: '.carousel-cell',
  pageDots: false
});
```

``` js
// vanilla JS
Flickity.defaults.cellSelector = '.carousel-cell';
Flickity.defaults.pageDots = false;
```

> If so, would it then be also possible to override these default options via the data-flickity-options attribute?

Yes, you can overwrite _your_ default options with `data-flickity-options` or options set in instances.

**Comment by danielvonmitschke** [comment]
perfect. thanks a lot!
