### ISSUE TITLE
Left Space in Slider

### ISSUE THREAD

**Issue by losee93** [metafizzy/flickity#1152]
Hello everyone !
I started building a website and decided to use flickity slider, but am facing an issue.
When i add images in slider i have an extra space in the left side of slider, does anyone knows a solution for this ?
Thanks all !!

You can see the issue in this next link:
https://codepen.io/lose99/pen/PobryMY

**Comment by e-p-n** [comment]
Change "initialIndex": 1 to "initialIndex": 2

**Comment by marcomezzavilla** [comment]
@losee93 You can use `cellAlign: 'left'` during initialization.
Flickity's default is `cellAlign: 'center'` ([link](https://flickity.metafizzy.co/options.html#cellalign)), that's why you see the space on the left.

**Comment by IsmaelVaazquez** [comment]
How can I make it so that it is neither left nor in the centre? And that for example it has 400px of alignment from the left?
