### ISSUE TITLE
wrapAround: true with 33% width does not show half items

### ISSUE THREAD

**Issue by gallien** [metafizzy/flickity#1156]
There is a different behaviour for wrapAround: true and a different width. I will expect an half item also for 33% width. Why it is different for both values?

**Test case 1:**

wrapAround: true with 25% width: left and right with an half item

**Test case:** https://codepen.io/gallien/pen/oNBqXBY

![image](https://user-images.githubusercontent.com/812394/114442956-7052af00-9bcd-11eb-9bee-0e279b98bc79.png)

**Test case 1:**  https://codepen.io/gallien/pen/NWdBmYW

wrapAround: true with 33% width: left and right without an half item

![image](https://user-images.githubusercontent.com/812394/114443641-359d4680-9bce-11eb-810c-fecb6664849b.png)

**Comment by marcomezzavilla** [comment]
The default cell alignment is `center` ([link](https://flickity.metafizzy.co/options.html#cellalign)).
If you change the alignment to `cellAlign: 'left'` in the first example, the result will be the same.

**Comment by gallien** [comment]
@marcomezzavilla I'd like to have an half item also in the second example.

**Comment by gallien** [comment]
I have found a solution with an undocumented `cellAlign` parameter with float value. In this example `"cellAlign": 0.25` will center the items with an half item left and right.

![image](https://user-images.githubusercontent.com/812394/123814423-f68db000-d8f5-11eb-8ded-6c4c48bdcbfe.png)
