### ISSUE TITLE
Carrousel vertical 

### ISSUE THREAD

**Issue by GeoffreyOlivier** [metafizzy/flickity#1159]
Hello, I don't know why, my carrousel is displayed verticaly. 3h to looking, but I don't find why !  
```
  <div>
    <div class="carousel" v-for="item in category" :key="item.id">
      <div class="carousel-cell">{{ item.titre }}</div>
    </div>
  </div>
```

**Comment by nguyenvanphi98** [comment]
Same too..

**Comment by desandro** [comment]
Thank you for this feature request, but I have decided not to support vertical sliding. See https://github.com/metafizzy/flickity/issues/36#issuecomment-212905712
