### ISSUE TITLE
Pause on hover doesn't work if the values for `friction` and `selectedAttraction` are configured for smooth scrolling

### ISSUE THREAD

**Issue by arvilmena** [metafizzy/flickity#1162]
Hello!

I have implemented the following values for `friction` and `selectedAttraction` in our flickity settings to enable smooth-scrolling (the slide doesn't snap/bounce at the center and instead it just slides smoothly)

```
friction: 0.4,
selectedAttraction: 0.001
```

but the problem is it removes the default "Auto-playing will pause when the user hovers over the carousel." behaviour.
I can't find a way to enable the pause with this configuration. Any help on how I can achieve this?

Regards,

**Test case:** https://codepen.io/arvil/pen/zYNjvOq

**Comment by desandro** [comment]
I mean - if you hack the `friction` and `selectedAttraction` to make the movement 'smooth', you'll consequently making stopping that movement just as smooth. Sorry, you'll have to pick one behavior or the other here.
