### ISSUE TITLE
different slide momentum

### ISSUE THREAD

**Issue by colouredFunk** [metafizzy/flickity#1163]
I've seen on this site https://www.powerhouse-company.com/pathe-arnhem when moving between different slides in the carousel, the dragged slide moves at a different speed to all the others, creating a really nice effect. How is this achieved, I've played around with dragThreshold, selectedAttraction and friction but can't seem to get the same results

**Comment by desandro** [comment]
Take a look at using the [scroll event for parallax effect](https://flickity.metafizzy.co/events.html#scroll)
