### ISSUE TITLE
[Flickity] How to add/remove options when clicked button?

### ISSUE THREAD

**Issue by keansgor** [metafizzy/flickity#1171]
Hi all,

Is there any way to add/remove option in html file when clicked a button using Javascript?

What I expect is that when I clicked on the button, the carousel will be undraggable, and the flickity-button will disappear (display: none).
Is there any way to do it?

Appreciate if anyone could answer my issue.
Thanks in advance!

**For example:-**

[HTML file]
[button id="submit-btn"] Submit [button]

[div class="carousel" data-flickity='{"wrapAround": true, "autoPlay": true}']
     [div]Slide 1[/div]
     [div]Slide 2[/div]
     [div]Slide 3[/div]
[/div]

**Comment by phucbm** [comment]
I know it's a bit late to answer but maybe someone will need this.

I'm afraid that you cannot change the options once you initialized the carousel as mentioned from this [issue](https://github.com/metafizzy/flickity/issues/233). However, you definitely can destroy and re-init the carousel after clicking the button.
