### ISSUE TITLE
Before change event

### ISSUE THREAD

**Issue by YOBA1112** [metafizzy/flickity#1173]
Is there a way to execute code just before the slide is changed? In my test case you can see, that it returns _location.hash_ of changed slide. For example, I am swiping `#page1` slide to `#page2` slide, and _location.hash_ returns `#page2`, but I want it to return _location.hash_ of slide that being swiped, which in that case is `#page1`. 

**Test case:** https://jsfiddle.net/hw1xqL46/

**Comment by frizzant** [comment]
I would recommend saving the initial state of which slide is active, then always save the last one. Basically you are saving the active element, and using it when the change event happens. After that, you save the current slide into the variable.

1) pageload: save current active item to variable
- Event 'change'
1) get variable value
2) save event target to variable

That should do the trick.
