### ISSUE TITLE
Adding boundary friction to stop the slides from stretching off the carousel edges    

### ISSUE THREAD

**Issue by nafis25** [metafizzy/flickity#1174]
Hey there! First off, thanks so much for this awesome slider, the physics based animations really takes the cake!

I was thinking if it was possible to add some resistance/friction to the first and the last slides of the carousel (slide[0] and slide[-1]) on to prevent the user from over-swiping. Currently, the first and last slides can be dragged for as long as the flickity viewport div can stretch, I tried to illustrate what I mean with the help of the pictures attached.

![normal](https://user-images.githubusercontent.com/45073662/129053760-bf601c75-e8d7-4885-aa82-d6170745ea54.png)
![streched](https://user-images.githubusercontent.com/45073662/129053765-23890a82-939c-4bec-9c31-0861379717cf.png)

To further explain this feature request, the best example I can come up with is the `resistance` and `resistanceRatio` parameter [Swiper](https://swiperjs.com) uses for their slides [here](https://swiperjs.com/swiper-api#parameters). 

I hope I was able to articulate this feature request properly, fingers crossed for this to make it into production. Thanks again!

**Comment by desandro** [comment]
Yup, this is how Flickity was designed. It's boundary physics is fairly simple - move the slider at half-rate compared to dragging. See `dragMove` in `drag.js`

``` js
  if ( !this.options.wrapAround && this.slides.length ) {
    // slow drag
    var originBound = Math.max( -this.slides[0].target, this.dragStartPosition );
    dragX = dragX > originBound ? ( dragX + originBound ) * 0.5 : dragX;
    var endBound = Math.min( -this.getLastSlide().target, this.dragStartPosition );
    dragX = dragX < endBound ? ( dragX + endBound ) * 0.5 : dragX;
  }
```

The `0.5` is the rate.

This feature-enhancement doesn't feel popular enough for master branch. But let me know where you take it.

**Comment by desandro** [comment]
Sorry, this request didn't get much love
