### ISSUE TITLE
No jquery versión

### ISSUE THREAD

**Issue by nam-co** [metafizzy/flickity#1176]
2021, jquery usage has gone way down everywhere, maybe there could be a smaller no-jquery version of the js file? Hope you'll consider

**Comment by desandro** [comment]
flickity.pkgd.js does not require jQuery. It does include [jQuery Bridget](https://github.com/desandro/jquery-bridget), which is ~100 lines of code, fairly small. If you really want to remove that bit, you can build Flickity as you like, see [bundle-js.js](https://github.com/metafizzy/flickity/blob/master/bin/bundle-js.js)
