### ISSUE TITLE
Is this effect compatible with flickity?

### ISSUE THREAD

**Issue by PartisanEntity** [metafizzy/flickity#1179]
Hello,

I cam across this nice slider effect: https://codepen.io/mrspok407/pen/bwLwvL 

I am wondering if in your opinion this can be easily incorporated with flickity or would it clash with the way flickity is built?

**Comment by frizzant** [comment]
Seems like quite some work. In theory your slide can contain whatever you like. So i am pretty sure this is possible.
But you might have to do some JS trickery to get the slide to recognize if it is moving <----> in any horizontal direction.

**Comment by desandro** [comment]
Yes, it's possible. Take a look at the [parallax demo using the scroll event](https://flickity.metafizzy.co/events.html#scroll).
