### ISSUE TITLE
Focus in IE

### ISSUE THREAD

**Issue by outsetrin** [metafizzy/flickity#118]
Hi, I am testing a website that contains a slider that is higher than the viewport.
After scrolling down a little, a mousedown event on the flickity slider immediately brings the page back to the top, only in IE.
The issue can be reproduced on http://flickity.metafizzy.co/, just scroll down so that the top of the slider is out of the viewport, and on mousedown IE will automatically realign the browser with the top of the slider.
Is it a focus issue? Can it be avoided?
Thank you..

**Comment by desandro** [comment]
Yes, this is an issue with `focus`. See my comments in #76
