### ISSUE TITLE
Issue at the first load with my two first images overlap

### ISSUE THREAD

**Issue by mathieuperrot** [metafizzy/flickity#1181]
Hi everyone. 
I have a little issue with at the first loading of my page where my two first images overlap. If anyone knows how to fix it, that would be great ! Thanks !

![Capture](https://user-images.githubusercontent.com/52498929/137673174-205f7359-08bc-4c38-9c7d-86afb7ff9709.PNG)

**Comment by desandro** [comment]
Have you tried using [imagesLoaded or lazyLoad](https://flickity.metafizzy.co/options.html#images) ?
