### ISSUE TITLE
Play/ Pause button

### ISSUE THREAD

**Issue by manerkargaurav** [metafizzy/flickity#1183]
Hello,

How can i add play/pause button before page dots ?
May be an option to create a element using available events and bind play, pause methods on it?

**Comment by desandro** [comment]
You'll have to create your own [custom UI elements](https://flickity.metafizzy.co/extras.html#custom-navigation-ui) that trigger `playPlayer`, `pausePlayer`

**Comment by manerkargaurav** [comment]
Any example of adding element ? Is there any option available in library ?
