### ISSUE TITLE
flickity swipe is not working & page dot also click event in ios 15

### ISSUE THREAD

**Issue by vasanthangel4** [metafizzy/flickity#1184]
Hello All, i have using flickity single vanilla js file, but it is not working the iOS 15 for swipe , but iOS 14, Android devices , Deskop working fine. we need to go live this due to this issue it is postponed. so i am totally stuck on it, i need your help. please help me on this.

**Comment by ermincelikovic** [comment]
Any update here?

**Comment by shahriared** [comment]
Same issue

**Comment by desandro** [comment]
This is indeed an issue and I will have to investigate.

**Comment by desandro** [comment]
Closing as a duplicate of #1177
