### ISSUE TITLE
Custom button jump 2 items at a time

### ISSUE THREAD

**Issue by an0dnh** [metafizzy/flickity#1186]
I'm currently having an array of items. I created a for loop to generate flickity with each item. However, when I created a custom button
```   
 const previousButton = document.querySelector('.js-carousel-block__left')
    previousButton.addEventListener('click', function () {
      flkty.previous()
    })
```
They always skip a slide (for exemple 1 > 3 > 5 )
Tks for reading

**Comment by frizzant** [comment]
More code please. This by itsself seems fine to me.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
