### ISSUE TITLE
Arrows keep clicks in memory

### ISSUE THREAD

**Issue by CHEWX** [metafizzy/flickity#1187]
When using custom arrows for example:

```
$prev.on('click', () => $('.slideshow').flickity('previous') );
$next.on('click', () => $('.slideshow').flickity('next') );
```

If you get to the end of the slideshow and keep clicking next, it'll continue with those clicks and go nowhere, so when you click previous, you would expect to go to the previous slide but you have to click numerous times to get back onto the timeline.

I would expect Flickity to handle this rather than using custom javascript to return false if at of the slideshow.

**Comment by frizzant** [comment]
Simply do something like this if you got custom arrows like me.
If you got buttons "disable" them via HTML, not just via style like me. I however don't have the issue you mentioned.

	```
slider?.on('change', (index) => {
		if (index === 0) {
			// first item reached
			addAndRemoveClass(previousButton, 'is-disabled', false)
			addAndRemoveClass(nextButton, false, 'is-disabled')
			return;
		}

		if (index === main?.cells.length - 1) {
			// last item reached
			addAndRemoveClass(nextButton, 'is-disabled', false)
			addAndRemoveClass(previousButton, false, 'is-disabled')
			return;
		}

		// if nothing else is true do this
		addAndRemoveClass(nextButton, false, 'is-disabled')
		addAndRemoveClass(previousButton, false, 'is-disabled')
	});
```

**Comment by desandro** [comment]
Thanks for reporting this issue. I am not sure I am able to reproduce this. Try forking this CodePen https://codepen.io/desandro/pen/RwLZYLL
