### ISSUE TITLE
Question on max height for each cell

### ISSUE THREAD

**Issue by talmax1124** [metafizzy/flickity#1188]
Hello there! I am wanting to only allow cells to take all the width they want but to not pass a certain height per se 600px and that it does not look Stretched. Has anyone achieved this? Thanks!

The link in the bottom is irrivelant.

**Test case:** https://codepen.io/desandro/pen/azqbop

**Comment by talmax1124** [comment]
@wesbos Does anyone have a way to do this?

**Comment by desandro** [comment]
[See setGallerySize: false demo](https://flickity.metafizzy.co/options.html#setgallerysize)
