### ISSUE TITLE
Bug in reposition demo

### ISSUE THREAD

**Issue by sarantakis** [metafizzy/flickity#119]
The parameters of the event callback are not in the correct order.
It is in the demo and on the website:
$gallery.on( 'staticClick', function( event, pointer, clickedCellIndex, clickedCellElement)
But correct is:
$gallery.on( 'staticClick', function( event, pointer, clickedCellElement, clickedCellIndex )

**Comment by desandro** [comment]
Thank you for reporting this issue. I've fixed the documentation and the CodePen demos.
