### ISSUE TITLE
Issue with other JS on Safari

### ISSUE THREAD

**Issue by stefanomonteiro** [metafizzy/flickity#1191]
I would have created a codepen, but the issue I am having is only happening on Safari mobile size only.

I am using GSAP Flip to crate a tab style, where each button display a certain slider as 'block' and the remainder as 'none' hiding them. As mentioned it works well on chrome, but on Safari mobile size it is like flickity is not working out and applying the container `height` properly and it bugs as the image below shows.

https://snipboard.io/sI0fi7.jpg

Here is [the link to the test page](https://jiujitsux.com/tabs-test/) I am working on. I have tried to add some timeout to delay flickity to run, but it did not help. Furthermore, the bug happens not everytime (though it does 90%). 

So any ideas on what else I could do here would be greatly appreciated. Maybe someone has had a similar issue.

Thanks

**Comment by desandro** [comment]
Thanks for reporting this issue. Flickity v2.3.0 was just released with some fixes for iOS. Can you please update and report back if your issue is persisting?
