### ISSUE TITLE
Any way to disable the sliding animation while clicking next and previous buttons?

### ISSUE THREAD

**Issue by aasutossh** [metafizzy/flickity#1192]
Didn't find it in docs. Tried looking for `animation` and `transition` property in the inspector but couldn't find.

**Comment by desandro** [comment]
You'll have to create custom buttons that trigger [`next`](https://flickity.metafizzy.co/api.html#next) and `previous`, and set `isInstant` to true

``` js
// jQuery
$carousel.flickity( 'next', false, true )

// vanilla JS
flkty.next( false, true )
```
