### ISSUE TITLE
Unexpected transitionX when the slider has more cells and can't fit on a full width

### ISSUE THREAD

**Issue by joffreypersia** [metafizzy/flickity#1198]
Hi, 

I am using a flickity slider on my WordPress Oxygen Builder website. 

I am facing a problem.
I don't understand why, on the row where there is more items than the number that the width can display. It shifts the cell as a translateX and ignore the margin-left of my cell (this is the space I would like to have before the first item display.)

<img width="1440" alt="Screenshot 2022-01-01 at 16 56 37" src="https://user-images.githubusercontent.com/94628273/147861016-6708d250-21c6-4c17-ab7b-42a4314689c4.png">
<img width="1440" alt="Screenshot 2022-01-01 at 16 56 22" src="https://user-images.githubusercontent.com/94628273/147861017-12ff3547-43a2-459f-a797-1d54fe176d28.png">
 
https://www.pulqo.com (live website that have the problem)

Here is the JS code used : 

`    jQuery('.repeater__1').flickity( {
          // options
            cellAlign: 'left',
            contain: true,
            // wrapAround: true,
            pageDots: false,
            groupCells: true
    } );`

Thank you,
Joffrey

**Comment by desandro** [comment]
Thanks for reporting this issue. To be clear - Flickity aligns the cell content, without the margin, with `cellAlign`. If you want extra space within the carousel, you may have to use `padding` instead of margin
