### ISSUE TITLE
Concatenation build error

### ISSUE THREAD

**Issue by nouveller** [metafizzy/flickity#120]
### Issue

When making Flickity part of a build process that incorporates concatenating it together with other files "bad scripts" that don't properly close off causes the first part of Flickity to become a string; thus throwing an error. While this is not Flickity's fault, it should try protect from this.

Further explanation: http://stackoverflow.com/questions/7145514/whats-the-purpose-of-starting-semi-colon-at-beginning-of-javascript

### Build issue problem for the fix

I tried to make a pull request to fix this but I've ran through all the gulp tasks and none of them seem to rebuild the packaged files in `dist`. If you could provide instructions on how to do this (perhaps in `contributing.md`, I'll happily put in a PR.

### Solution

Otherwise, on https://github.com/metafizzy/flickity/blob/master/js/flickity.js#L11 just add `;`.

**Comment by desandro** [comment]
Thanks for reporting this issue.

> I tried to make a pull request to fix this but I've ran through all the gulp tasks and none of them seem to rebuild the packaged files in dist.

JS `dist` files are built with `gulp uglify`.

I don't feel a semi-colon is required at the beginning of the file. I'd rather the problem be fixed with the bad scripts rather than Flickity handling the issue.

**Comment by nouveller** [comment]
Ok, that's fair enough that you don't think Flickity should handle this situation, but personally I think the benefits outweigh the cons which is a shame.

For instance, the library that is causing me the issue that comes above Flickity in the build process is not active and the author is not responsive. That's sort of the point of the point of a defensive semicolon, it's you protecting your library from others that aren't coded as well.

But there are work arounds, so I'll stick with adding a semicolon myself. I hope you'd reconsider if more people run into this type of thing.
