### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by hn1** [metafizzy/flickity#1200]
please STOP sellinng or even promotinng this CRAP. It wastes a lot of developers times while its substance - i.e. undrlyig code is nothing but RUBBISH!.
It may work in simple scenarios, but this is NOT a product that should be charged for in ia production level application.

Leave it for school children to practice with but DO NOT market it as a serious product..

Unfortunately, the Ineternet has given a platform to all sorts of IDIOTS!

If anyone is reading this - USE ANTHER OPTION FOR YOUR OWN SAKE!

**Comment by desandro** [comment]
Thank you for your feedback!
