### ISSUE TITLE
Amending "autoPlay" value via a java script

### ISSUE THREAD

**Issue by cueball22** [metafizzy/flickity#1206]
Hello - I am not a coder but have basic understanding (worst combination!)

I have a directory site. It uses Flickity for a carousel/slider on home page. I can only amend the CSS or the HTML via a crude method of creating Java script code in a custom HTML snippet.

Can you help me understand and create the correct Java script to amend the HTML for the autoPlay attribute to a more preferable value e.g. 6000 (6 seconds). 

Please assume the HTML code is at present the same as on your Codepen page:

div class="carousel" data-flickity='{ "autoPlay": true }'

And just to reassure, I have access to the source code of my site BUT if I make amends to the code directly I invalidate my support licence, however if I make amendments either in the CSS editor (not useful for these purposes) or in custom code snippets in HTML that is fine.

MANY THANKS!!!

**Comment by desandro** [comment]
Set `"autoPlay": 6000`. See demo https://codepen.io/desandro/pen/VwrvVWr

**Comment by cueball22** [comment]
Thank you for this but I need to know what the code inside a <script></script> tag is please to make this change. I.e. I need to know the JavaScript code to amend the autoPlay speed in the HTML code. I hope that makes sense. And thanks!
