### ISSUE TITLE
Parallax images don't fill the container

### ISSUE THREAD

**Issue by dijkermans** [metafizzy/flickity#1207]
Hi,

The images of the official Parallax demos don't fill the container. 

![parallax](https://user-images.githubusercontent.com/33194795/154279175-2fddb127-0891-498f-ba92-574790b976a5.jpg)

https://codepen.io/desandro/pen/jAGWRQ
https://codepen.io/desandro/pen/qNPbgb

It looks better on your site but it has the same problem but just less noticeable:
https://flickity.metafizzy.co/#parallax

I think it should fill up the entire space like background-size cover (or object-fit cover), but then probably zoomed in a bit so it can be panned.

I've seen it the right way with Flickity, but what's the difference? How did they do it?:

https://themenectar.com/salient/architect/project/23-world-plaza/

![parallax2](https://user-images.githubusercontent.com/33194795/154280360-00e89a31-be0c-4858-8970-f5bd5b5595f4.jpg)

flickity 2.3.0 + 2.2.2 / win10 / chrome v98 + edge v98 + firefox v97

Regards! Great slider!

**Comment by dijkermans** [comment]
I noticed the demos look fine on my mobile; android12 / chrome + samsung browser

**Comment by dijkermans** [comment]
This CodePen works!:

https://codepen.io/acolinucci/pen/QWbOWqP

Now I have to analyze the differences. Looks like they scaled the image.

**Comment by desandro** [comment]
As you discovered, you'll need to made some adjustment to cover that other space. One way is to scale up the image.

Another way would be to decrease the size of the containing cell element. You could try something like `.carousel-cell { margin-right: -60px; }`. [See CodePen](https://codepen.io/desandro/pen/YzjrJvp/b6e7b9dbc6e3b3d738b6437a3aa47ef9). There's still a chance of gaps, so you'll have to play around with that number.

Or, you could try dynamically resizing the cell width.
