### ISSUE TITLE
Gap appears using imagesLoaded:true 

### ISSUE THREAD

**Issue by dijkermans** [metafizzy/flickity#1209]
Hi, there's a gap with imagesLoaded: true with 3 cells on first time load. It's fixed after resize.

![flickity](https://user-images.githubusercontent.com/33194795/157028705-729333dd-101e-4a00-8727-d54d703731ef.jpg)

Test: https://codepen.io/dijkermans/pen/YzEgarb

It's fixed with imagesLoaded:false, but then there's unfortunately still the _height problem_ mentioned here: #906

This vanilla resize doesn't work either to fix the height problem:

window.addEventListener('DOMContentLoaded', (event) => {
   flkty.resize();
});  

Also, this adaptiveHeight fix #185 isn't a proper solution to fix the height problem, because it causes content shift. It looks like the wrong height is corrected aftwarwards. The initial calculated height seems to be the width of the image of 1 cell. So it only works fine with square images.

Thanks.

**Comment by desandro** [comment]
Thanks for reporting this issue. Hmm, sounds like a tricky one. I wasn't able to reproduce the issue with the CodePen either. This issue is a bit old so I'm closing for now.
