### ISSUE TITLE
Animation is "janky" on heavier page loads 

### ISSUE THREAD

**Issue by drastick** [metafizzy/flickity#121]
I have put together a test case to show what I mean about it being [janky](http://jankfree.org/).  This is a big issue for us as it negatively impacts above the fold assets.

http://codepen.io/synapen/pen/GJgYdx

**Comment by desandro** [comment]
Thanks for reporting this issue. This test case loads in 5 big websites. Given this situation, I don't feel Flickity is at fault. Any widget's animation would suffer from that kind of page load. See this simplified demo http://codepen.io/desandro/pen/ZGYVEv

If you can produce a realistic scenario where Flickity is underperforming, I'll take another look.
