### ISSUE TITLE
Flickity wont initialize properly in details when open

### ISSUE THREAD

**Issue by malkum** [metafizzy/flickity#1214]
Hi,
When the slider is used in details element as shown in the below case, the vieweport height is not set. I am trying to avoid bootstrap or other js based accordions and want to use details tag for collapsed content.
**Test case:** https://codepen.io/malkum/pen/MWrXKZw

i tried this solution but I think it works for bootstrap accordions and not for details collapsed content.
https://codepen.io/desandro/pen/82f5a8d70e47a1f1fbf9922b11bb2be2

**Comment by malkum** [comment]
UPDATE:
Did a fix not sure if it is the right method. The fix is to by default make the details tag open. And after flickity initialization in js collapse and close the details.
https://codepen.io/malkum/pen/MWrXKZw

**Comment by desandro** [comment]
Thanks for reporting back on your solution!
