### ISSUE TITLE
Request: Pure vanilla version

### ISSUE THREAD

**Issue by buskol** [metafizzy/flickity#1217]
Thanks for all your great extensions :-)

Not many new sites use jQuery, so going forward a version without it (to maybe save a few kb), would be nice...

TIA!

**Comment by sadeghbarati** [comment]
This plugin is `javascript` package, only uses `jquery-bridget` for easy usage with jquery 

vanilla js:

```js
// vanilla or pure js
const vanillaFlickity = new Flickity(target, options)

// jquery
const jqueryFlickity = $(target).flickity(options)
```
