### ISSUE TITLE
Double move on prev/next button tap on iOS & Android

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#122]
From https://github.com/metafizzy/flickity/issues/67#issuecomment-97034012, bug with Flickity v1.0.1

> clicking on the arrows makes the carousel move ahead by two items instead of one. Confirmed on ios8 safari, chrome android.
> 
> Shown here https://jsfiddle.net/rfdeoqea/25/
> 
> And for reference, here is the same on 1.0.0 https://jsfiddle.net/dgbrt/rq5dwjne/2/

**Comment by desandro** [comment]
Flickity `v1.0.2` has been released with a fix for this bug.

**Comment by bramsmulders** [comment]
It seems this bug is still present on stock android browsers with android versions:

* 4
* 4.1
* 4.2
* 4.3

I've reproduced this issue on my own devices and some browserstack devices. And this occurs on my own site aswell as the slider on your homepage.

I've upgraded to version v1.0.2 which should fix the issue, but with no avail.

Can you please look at this?

**Comment by johjacb** [comment]
I'm also seeing this issue

**Comment by desandro** [comment]
Flickity v1.1.1 has been released with some fixes for dragging and tapping on touch devices. I haven't tested this bug, but it may be resolved. [Try it out](http://flickity.metafizzy.co/)

**Comment by jonathanolsen** [comment]
I have the same issue on iphone as seen here.

http://hammr.co/7603307/7/index.html

When pressing the prev/next arrow, it jumps two steps instead of one.

Am I doing something wrong?

**Comment by mrmartineau** [comment]
FYI, I am seeing this on iPad Mobile Safari too..

**Comment by juvenpajares** [comment]
This is caused by a reset flag on tap-listener required plugin, issued a pull-request on this issue.

**Comment by chrisforrette** [comment]
I'm seeing this issue in iOS 6 as well, which you can see here if it might be helpful:

http://remo.com/products/drumheads/drumset/?product_series=ambassador

I stuck some `console.trace()` calls into some `cellSelect` event listeners locally and I can see that on one arrow tap both an `ontouchend` and an `onmouseup` event are being fired:

![screen shot 2016-03-18 at 5 48 49 pm](https://cloud.githubusercontent.com/assets/126919/13895558/bcba0a50-ed31-11e5-9d83-7b654a4eea75.png)

Happy to supply any other info that might be helpful. I'd love to PR too, but this one is quite beyond me :)

**Comment by chrisforrette** [comment]
FYI, upping the timeout of the function that @juvenpajares commented out in metafizzy/tap-listener#2 from 320ms to 400ms seems to resolve the issue for me. Not sure how that fares on Android though.

**Comment by chrisforrette** [comment]
I made a fork of tap listener with a slightly upped timeout time and it works well for me:

https://github.com/chrisforrette/tap-listener

I've only tested on iOS, any Android folks want to install the above and give it a go? If you're running npm 3.x it should be super easy to install my fork, just add `"tap-listener": "chrisforrette/tap-listener",` to your `dependencies`/`devDependencies` list, run `npm install` and rebuild your code. If it works, I can PR into the `tap-listener` repo.

**Comment by desandro** [comment]
@chrisforrette Thanks for looking into this. I'll evaluate adding this in for Flickity v2

**Comment by desandro** [comment]
[Flickity v2 is out now](http://flickity.metafizzy.co), and it's bumped up the click delay to 400 ms. Please chime in if you still experience this issue.

**Comment by AdamWaz** [comment]
@desandro it's still moving two slides.

**Comment by nolaandy** [comment]
I'm unfortunately experiencing this with the latest version. Anyone else?

**Comment by nolaandy** [comment]
I will say , I am using 4 flickity galleries inside individual bootstrap tabs and I had to trigger a resize on bootstrap tab change in order to see the slides in their respective tabs.

**Comment by desandro** [comment]
After Flickity v2 release, this issue has been relatively quiet. I'm closing this issue here. 

@nolaandy Can you please open a new issue with a **reduced test case** demonstrating the issue? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
