### ISSUE TITLE
Unexpected   transform: translateX added to slider children / items

### ISSUE THREAD

**Issue by adewalegeorge** [metafizzy/flickity#1220]
**Test case:** https://codepen.io/desandro/pen/WzGgJY

![image](https://user-images.githubusercontent.com/3802751/167035791-42968d55-e02e-471d-af98-ba5128b902b7.png)

This has been working without version changes but as you can see from the codepen example on this page [https://flickity.metafizzy.co/options.html#adaptiveheight ](https://flickity.metafizzy.co/options.html#adaptiveheight ) it appears broken. How can I go around this? 

it used to return something like `left: 0%;` but now returns `    transform: translateX(0%);`

This issue cancels out all of my `transform` use cases when trying to vertically center the slider items / content.

**Comment by Ryann2002** [comment]
I'm facing the same problem, it set a transformX and misaligns my .flickity-slider element

**Comment by Hud1ai2** [comment]
Don't know what to see, but I have problem with Flickity in repeater. Some sliders work like thi
![Snímek obrazovky 2022-05-05 073948](https://user-images.githubusercontent.com/24320756/167184451-c822ce20-e4ca-4bf7-a919-aa25deb8cfee.png)
s

**Comment by Hud1ai2** [comment]
So you can check the same behaviour here
https://jsmerab.cz/horolezectvi/

And try these steps
1. open that site and try some of the sliders - doesn't work as should be
2. change the size of the browser window and try some slider. It will work. 
3. maximaze the browser window and it will work. But refresh the page and slider doesn't work. Till you repeat the steps above

**Comment by Hud1ai2** [comment]
I've found next thing. If you open the Inspector, you can change the size of the window about 1px only. Even this small change and it starts to work.

**Comment by adewalegeorge** [comment]
> I've found next thing. If you open the Inspector, you can change the size of the window about 1px only. Even this small change and it starts to work.

![image](https://user-images.githubusercontent.com/3802751/168992108-887709b8-20fd-4fa1-8165-196351887808.png)

The issue above is that the vertical alignment of the images/items is broken. There have been no effective changes in the implementation.

It used to be something like 
![image](https://user-images.githubusercontent.com/3802751/168992648-0e6d3d8b-e09f-47ed-8718-41daebf97edb.png)

and now..
![image](https://user-images.githubusercontent.com/3802751/168992725-3e569fd5-ce1f-43cf-a8b5-8b2099ca8498.png)


As you can see the transform: translateX was added inline which overrides the one set in my stylesheet

**Comment by desandro** [comment]
As of Flickity v2.3.0, Flickity no longer sets `left` but uses transforms instead. If you need to use transforms, I recommend setting the transform on an interior element within a cell, not the cell element itself.
