### ISSUE TITLE
Flickity v2.3.0 does not resize properly if browser size is changed during a slide transition

### ISSUE THREAD

**Issue by dylanfisher** [metafizzy/flickity#1223]
Flickity v2.3.0 doesn't resize carousels in the same way as v.2.2.0, and if a user resizes their window while a slide transition is in progress, the correct size is not recalculated after the transition. This is apparent in autoplaying carousels.

Test case showing incorrect behavior in 2.3.0 https://codepen.io/dylanfisher/pen/JjpbEqe

Test case showing correct behavior in 2.2.0 https://codepen.io/dylanfisher/pen/MWQbJMO

Possibly related to [1202](https://github.com/metafizzy/flickity/issues/1202)

BTW, thanks for an amazing plugin. I've used Flickity since at least 2015 on dozens of sites!

**Comment by desandro** [comment]
Thanks for reporting this issue. Yeah this looks like #1202. I'm closing here as a duplicate so we can track there.
