### ISSUE TITLE
Flickity v3 .destroy() is removing cell class names so it cant reinit

### ISSUE THREAD

**Issue by gregg-cbs** [metafizzy/flickity#1234]
When destroying flickity it then removes all the cell class names.
So when trying to reinit it, flickity does not work.

Here is the repoduction:
https://codesandbox.io/s/flickity-destroy-and-init-edkcew?file=/index.html

**Comment by desandro** [comment]
Thanks for this. `flickity-cell` is added and removed by Flickity. You should not `flickity-cell` to your own markup. So, I recommend you use a different selector like `carousel-cell`.
