### ISSUE TITLE
Disable extra scroll at the edges of the carousel

### ISSUE THREAD

**Issue by aurelien-robineau** [metafizzy/flickity#1236]
Hi !

I can't find any option in the docs that allow to disable the extra scroll at the beginning and at the ending of the carousel.

Here is a GIF showing what I would want to disable :
![extra-scroll-exemple](https://user-images.githubusercontent.com/34516875/176163081-1e33e5e6-ce8e-4ea3-bd01-546adb7dd52d.gif)

Is there any way of doing this ? If not, could you implement it ?

**Comment by desandro** [comment]
Sorry, there is no option for this. You would have to [re-write this code](https://github.com/metafizzy/flickity/blob/v2.3.0/js/drag.js#L220-L226)
