### ISSUE TITLE
 Flickity last image is jumping around

### ISSUE THREAD

**Issue by o771e** [metafizzy/flickity#1247]
When using `wrap around` the last image visibly jumps around from the beginning to the and vice versa. Maybe duplication of the last element is sufficient? V 3.0.0

[https://www.youtube.com/watch?v=MbIhAmf7IGk](https://www.youtube.com/watch?v=MbIhAmf7IGk)

````JS
      $carousel.flickity({
        cellAlign: 'center',
        wrapAround: true,
        lazyLoad: 2,
        imagesLoaded: true,
        percentPosition: false,
        pageDots: false,
        initialIndex: 1,
        arrowShape: 'M 25,50 L 70,95 L 70,90 L 30,50  L 70,10 L 70,5 Z'
      });
````

**Comment by desandro** [comment]
If you're using Flickity v3, try setting `wrapAround: 'fill'`. See #809.
