### ISSUE TITLE
How to swipe 2 slider that overlap eachother

### ISSUE THREAD

**Issue by QgAnhDo** [metafizzy/flickity#1248]
I have 2 flickity slider that overlap each other by position absolute. I want to be able to swipe both of them at the same time with mouse, but I can only slide the first one on the top. So how can I also swipe the behind one? 
I also tried the asNavFor function but it didn't allow free scrolling like the upper slider, the behind slider will automatically return to center.

Here my example code: https://codepen.io/SparkDo/pen/oNqKeyR

**Comment by desandro** [comment]
Try [flickity-sync](https://github.com/metafizzy/flickity-sync)
