### ISSUE TITLE
On Wrap Around, Prepend Last Cell

### ISSUE THREAD

**Issue by peterph-am** [metafizzy/flickity#125]
Is there a way to prepend the last cell in a slider, on init, to the slider?

So that when wrapAround is activated you don't get a gap before the first slide?

**Comment by desandro** [comment]
I'm having trouble understanding what you are requesting. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by graygilmore** [comment]
I think this matters when there are only two slides: http://codepen.io/graygilmore/pen/106167336876c05ebf04111a9e417f3f

**Comment by desandro** [comment]
If there's only two slides, then there's not enough to work with. I'll close this issue for now.
