### ISSUE TITLE
Cannot set properties of undefined (setting 'sync')

### ISSUE THREAD

**Issue by Dhanush-gitt** [metafizzy/flickity#1251]
I am trying to use flickity sync but I keep getting this error
![image](https://user-images.githubusercontent.com/114050393/194842850-7d50d65a-ce02-4319-ad9e-34b610c957df.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
