### ISSUE TITLE
"Low battery" iOS slider problem

### ISSUE THREAD

**Issue by tilenp2** [metafizzy/flickity#1254]
First of all, I really like what you're doing here, it is a wonderful carousel. However, there seems to be an issue if you're viewing carousel in "low battery" mode on iOS devices. I haven't tested on Android devices. I've been trying to find a solution but there seems to be only 2 cases on here, where users mentioned this problem with no solution. Is there any solution to it yet? You can view flickity carousel on the official website with "low battery" mode and see what I am talking about if you're interested. It is very "laggy" if you compare to the normal battery sliding.

**Comment by tobystokes** [comment]
iOS low battery mode reduces the refresh rate and GPU usage, so I'd say it's pretty much intentional on Apple's part that resource-intensive animation is limited, in order to save the battery.
