### ISSUE TITLE
Add Class to arrows based on slide selected

### ISSUE THREAD

**Issue by timbrandon** [metafizzy/flickity#1255]
Hi, somewhat new to JS / Jquery. 

I'm trying to change the color of the arrows depending on what slide its on.
That way if you are on a dark slide, the arrows display differently then when on a light slide. 

Any help on achieving this would be greatly appreciated.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues). If you can write up a CodePen with some light and dark slides, I may be able to whip up the JS for you.
