### ISSUE TITLE
carousel-cell not animated properly when using flickity reposition

### ISSUE THREAD

**Issue by khoiruddin-ms** [metafizzy/flickity#1256]
I tried to merging "Static select" and "flickity reposition" to add condition when cell clicked, it marked as cell-active and reposition the cell to adjust is-selected size but it won't animated/transitioned properly (using static animation instead)

i tried to use transition on css (transition : 1s all) on is-selected but instead having weird animation instead.

**Test case:** https://codepen.io/khoiruddin-ms/pen/wvXqKpX

is there any method to animate reposition properly?

**Comment by desandro** [comment]
Thanks for the test case. If you want to go to a slide immediately, use the `isInstant` argument with [selectCell](https://flickity.metafizzy.co/api.html#selectcell)

```js
flkty.selectCell( value, isWrapped, isInstant )
```

[See CodePen](https://codepen.io/desandro/pen/oNMeoOa/34c6515c7e3ef1fda94ed5725f17de21)
