### ISSUE TITLE
<video> + <img> together

### ISSUE THREAD

**Issue by philipfarmer** [metafizzy/flickity#1258]
Hi there,

I was hoping someone could help with an issue i'm encountering when using both html5 video and images together in a slider. It's not something i've come across in any examples online

At first glance it appears to work but with different options added (e.g autoplay) the gaps between the items begins to shrink at times and other times there are larger gaps as if the video is running outside of the slider itself

I've created a pen here:
https://codepen.io/phlp/pen/bGKYajO

Look forward to hearing if anyone has any suggestions, this has been a serious (months long at times headscratcher for me!)

thanks

**Comment by vozaldi** [comment]
I think you need to set width and height attribute for the videos

For example:
```<video .... width="480" height="640">...</video>```
