### ISSUE TITLE
transform: translateX(-150%) causing issue

### ISSUE THREAD

**Issue by Dragolin** [metafizzy/flickity#1259]
When loading the mobile version of my Shopify collection, the Flickity code causes the last item to appear first, messing up the sort.
I've looked at the code and it appears this transform: translateX(-150%) is causing the issue.

Test case:
https://vzwduik.be/pages/zwemlessen-in-aaigem (products at the bottom)

(desktop view has the correct sort and when you switch to / load mobile, then the last item is shown first, as described above)

**Comment by desandro** [comment]
This looks to be a wraparound fill issue. See #809 . This will be fixed in Flickity v3 - releasing in in the next couple months. Closing this ticket here.

**Comment by FluffyDiscord** [comment]
@desandro it has been a year since you said that v3 is in the making and almost half of year since it should be released, any updates? is this project dead?
