### ISSUE TITLE
select cell without animation

### ISSUE THREAD

**Issue by Wolfr** [metafizzy/flickity#128]
Q: Is there a way to prevent the excessive animation at the beginning when scrolling to a slide?

See video: http://cl.ly/0k3T3n2m1x30/kanamaster.mp4

I could hide while animating but that would just make the app feel slower.

Loving Flickity, great work @desandro .

**Comment by desandro** [comment]
Ah! Good feature request. Sounds like you want a `selectInstantly` method. You can add this code:

``` js
Flickity.prototype.selectInstantly = function( index ) {
  if ( !this.cells[ index ] ) {
    return;
  }

  this.selectedIndex = index;
  this.setSelectedCell();
  // instantly go to cell
  this.x = this.selectedCell.target;
  this.positionSlider();
  this.dispatchEvent('cellSelect');
};
```

See http://codepen.io/desandro/pen/aOvoPv

---

**+1** this issue if you would like to see this method added to Flickity.

**Comment by Wolfr** [comment]
Thanks so much. I've been going through the source of Flickity it's a good learning experience :+1: My project is OSS but I'll buy a license tomorrow to support your work.

**Comment by desandro** [comment]
+1 from https://twitter.com/iammattq/status/617000462479396864

**Comment by iammattq** [comment]
Thanks @desandro! this is perfect.

**Comment by jgerigmeyer** [comment]
+1

**Comment by iammattq** [comment]
Hey there @desandro. I ran into a snag with your selectInstantly method. I'm currently creating an overlay and adding elements to Flickity dynamically with flkty.insert. When I close the overlay I do flkty.remove on the items in the slider (clearing them all out). When I open the overlay I re-populate the slider with new tiles via flkty.insert. The problem is is once I re-populate the slider the the selectInstantly method no longer works (reverts to old animated select).

Any ideas on how to get this to work?

**Comment by desandro** [comment]
@iammattq Sorry to hear the trouble. Can you provide a [**reduced test case**](http://flickity.metafizzy.co/extras.html#reduced-test-cases)?

**Comment by mellinger** [comment]
+1

**Comment by IbeVanmeenen** [comment]
+1

**Comment by graygilmore** [comment]
+1

**Comment by sambaldwin** [comment]
+1

**Comment by rzschoch** [comment]
+1

**Comment by desandro** [comment]
In Flickity v1.1.2, [`select()` has an additional argument to select instantly without animation](http://flickity.metafizzy.co/api.html#select).

Thanks so much for all the feedback! :rainbow: :bear:

**Comment by raphaelokon** [comment]
In version > 2.0.0 the Flickity object is missing the `this.setSelectedCell` property throwing an TypeError.

```js
TypeError: this.setSelectedCell is not a function. (In 'this.setSelectedCell()', 'this.setSelectedCell' is undefined)
```

**Comment by desandro** [comment]
@raphaelokon Use the [`isInstant` argument](http://flickity.metafizzy.co/api.html#select) instead of code you mentioned. 

``` js
$carousel.flickity( 'select', 2, false, true )
```

**Comment by raphaelokon** [comment]
Worth noting that the vanilla API looks like:

```js
flkty.select( index, isWrapped, isInstant )
```

**Comment by madebyreformat** [comment]
Is it possible to autoplay instantly so it simulates a GIF effect? I've been trying having ```friction: 1``` with ```fade: true``` but doesn't quite work

**Comment by stevesoldierunltd** [comment]
+1

**Comment by hemant-tivlabs** [comment]
+1
