### ISSUE TITLE
Use native scrolling instead of translate, use CSS scroll snap points

### ISSUE THREAD

**Issue by ivancuric** [metafizzy/flickity#130]
Would it be possible to add two-finger scrolling on OSX devices?
Basically, to enable native scrolling, like on http://store.apple.com/us/buy-watch/apple-watch-sport, using overflow: scroll

**Comment by desandro** [comment]
Could you clarify what you are requesting? How is "native scrolling" different from `freeScroll`?

**Comment by ivancuric** [comment]
"Native scrolling" would use `overflow: scroll` to enable scrolling inputs such as scroll wheels, touchpad swiping and the like to manipulate the slider, instead of using `translate` and the click/touch event. Ideally with some sort of controller to keep the two in sync when switching methods (scroll + button).

Basically, an scrolling overflow container with a hidden scrollbar with a fallback to all the bells and whistles that Flickity supports at the moment.

**Comment by desandro** [comment]
So in that case, Flickity would only be providing extra UI: previous/next buttons, page dots; and its API with events in methods.

It's an interesting request. But I'm afraid its asking for an overhaul of how Flickity works. There would likely be conflicts. I'm speculating that using scroll position over `translate` could be problematic. By not using scroll, Flickity avoids conflicting behavior that come with native scrolling.

---

I'll keep this issue open for a while. I'm curious to hear how other people want to use native scrolling.

**Comment by tomtev** [comment]
You could use watchCSS and disable Flickity on mobile devices and then use white-space:nowrap and -webkit-overflow-scrolling: touch on the Slider.

**Comment by desandro** [comment]
Native scrolling also has the benefit of using [CSS scroll snap points](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap_Points)

**Comment by desandro** [comment]
Looks like this issue didn't get as much interest as other feature requests. I'm closing this issue for now. Feel free to chime in if you'd still like to see this feature.
