### ISSUE TITLE
Add slideStart event

### ISSUE THREAD

**Issue by nokiko** [metafizzy/flickity#131]
Hi

Great plugin but i am running into one issue, i have the content of a div above the slider change onsettle. but I would like to hide it when the movement starts

There is ondrag and onclick but I don't see the option to attach to an event when the slider starts moving ( either by drag, or click , or  when the slider is set to auto scroll.

I would like to can a function the second the slider start moving ( either by click drag or auto scroll, how do I go about this ?

**Comment by desandro** [comment]
Thanks for this feature request. You can hack in a solution with this code:

``` js
var startAnimation = Flickity.prototype.startAnimation;
Flickity.prototype.startAnimation = function() {
  if ( this.isAnimating ) {
    return;
  }
  // do previous logic
  startAnimation.apply( this, arguments );
  // trigger event
  this.dispatchEvent('slideStart');
};
```

This allows you to listen for `slideStart` events. 

``` js
$gallery.on( 'slideStart', function() {...})
```

---

**+1** this issue if you would like to see this event added to Flickity's API.

**Comment by nokiko** [comment]
thanks that will do for now

**Comment by desandro** [comment]
Closing this feature request as it's been quiet :ghost:

**Comment by TheNewGuy16** [comment]
Is this what the scroll.flickity event does now?  Cause i cant get the scroll event to work for some reason.
