### ISSUE TITLE
Change flickity options after initialization

### ISSUE THREAD

**Issue by Odisseas** [metafizzy/flickity#133]
I am looking for a way to change some options (draggable, pageDots, prevNextButtons) after I have initialized flickity, since I have content inside of the cells which is shown after staticClick has fired. I might even add another flickity gallery in each cell, so disabling dragging etc for the outter gallery is really useful while this content is shown. I was then thinking to re-enable these options with a button that hides that content and brings navigation back.

My initial thought was to add this into the staticClick, but it doesn't work obviously:

```javascript
//Initialize flickity with some options
var $gallery = $('.gallery').flickity({
  cellAlign: 'center',
  draggable: true,
  friction: 0.2,
  contain: true,
  pageDots: true,
  imagesLoaded: true
});

//Then alter them when staticClick has fired
$gallery.on( 'staticClick', function( event, pointer, cellElement, cellIndex ) {
  /*Code to show hidden content*/

  //I thought this would work
  $gallery.flickity({
      draggable: false, //not working
      pageDots: false, //not working
      prevNextButtons: false //not working
  });

  /*Code to hide content & bring back navigation*/

});
```
A workaround would be hiding the Dots & Arrows in CSS but I think there is not much I could do about the draggable option.
I took a look at the docs and couldn't find something useful, or it was just there and I didn't even realize it.
This might look like an edge case, but I thought I'd give it a shot and ask anyways!

A basic test case can be found here:
http://codepen.io/djseas/pen/OVywza/

**Comment by juergengenser** [comment]
+1

**Comment by jesperavot** [comment]
I recently needed this as well to temporary disable dragging. If you look closely at the source, you can see that an event dispatched is used. If added 2 extra listeners to the **_createDrag** method of the drag plugin: **this.on("activate.drag",this.bindDrag)** next to the default **this.on("activate",this.bindDrag)**

In my normal code I receive the Flickity instance and emit the new events when needed: **flkty.emit('deactivate.drag');** and **flkty.emit('activate.drag');**

**Comment by Odisseas** [comment]
Long overdue, but thank you @jesperavot !
This worked perfectly!

**Comment by eriklougee** [comment]
I too would like to see this implemented as a basic feature; dependent upon your organization you may or may not be able to edit the source for any libraries / plugins you have access to. Thanks for the workaround @jesperavot!

**Comment by desandro** [comment]
Closing this issue here. Let's keep discussion about changing options like draggable after initialization over at #233
