### ISSUE TITLE
contain: true = too many dots and next btn disabled to late

### ISSUE THREAD

**Issue by hadl** [metafizzy/flickity#135]
I've set contain: true and the dots don't reflect the "slideable slides/pages". 
The next button gets disabled only if selectedIndex == cells.length. Therefore the user can click several times without any animation before the button gets disabled.

Testcase: http://codepen.io/hadl/pen/MwKGdE/

**Comment by desandro** [comment]
Thanks for reporting this issue. Visually, you are correct. When `contain: true`, it appears like there can be an extra page dot and the next button doesn't get disabled when you're at the end. But functionally, both the page dots and the previous/next buttons work with the selected cell, not where the gallery is visually. Highlighting the selected cell helps show how this works: http://codepen.io/desandro/pen/rVxrxX

Flickity is working as intended.

**Comment by hadl** [comment]
Thank you for your fast reply.
I thought so, will forward your answer to my PM :)

Btw, thank you for this incredible slider!
