### ISSUE TITLE
Can't select text inside Flickity cells

### ISSUE THREAD

**Issue by UberGruber** [metafizzy/flickity#137]
Hey there, I don't know if its intended or something but actually for users it's impossible to select text inside a cell to copy it for example.

As far I can tell, javascript tracks for mouse down to enable the nice drag effect and preventing normal cursor behavior.

Is this in total contrast with the drag functionality? can this be somehow implemented? 

Thank you for your time and this great widget btw! ;)

**Comment by desandro** [comment]
Thanks for reporting this issue. As you suspect, this behavior is intended. Either users can drag via pointers, or you can disable dragging `draggable: false`, and enable text selection.

Additional logic could possibly be added to interpret pointer actions to enable text selection or dragging. Perhaps via if the user pointer-downed on text vs. an element. But I fear this would be cumbersome, and lead to a less consistent user experience.

I'm leaving this issue as `wontfix` for now.

**Comment by jgerigmeyer** [comment]
What about a dynamic option where its ``draggable`` on touch devices and not on other devices? It'd be nice to be able to select text with the mouse, but swipe to navigate on a touch device.

**Comment by virgo79** [comment]
Maybe a solution could be adding a new option called `draggable-selector` where a user can define an html element where the drag action could rely on.
Could be this possible?

**Comment by OACDesigns** [comment]
I found I had a similar in my situation where I had a video in a cell and needed to be able to drag the video scrubber and not drag flickity at the same time.
It's a bit hacky, but it is possible to achieve this in 2 steps:

1: add event handlers to the element you wan't to disable drag on, indicating that dragging shouldn't happen:
```js
    var sliderElm = document.querySelector('.jw-slider-time');
    sliderElm.addEventListener('mousemove', function(event) {
        event.noFlickityDrag = true;
    }, false);
    sliderElm.addEventListener('touchmove', function(event) {
        event.noFlickityDrag = true;
    }, false);
    sliderElm.addEventListener('pointermove', function(event) {
        event.noFlickityDrag = true;
    }, false);
    sliderElm.addEventListener('MSPointerMove', function(event) {
        event.noFlickityDrag = true;
    }, false);
```

2: override Flickity's `_dragStart` function to not do dragging is the `noFlickityDrag` attribute is present on our modified element:
```js
Flickity.prototype._dragStart = function( event, pointer ) {
    if (event.noFlickityDrag) {
        // check if the event has been modified to disallow dragging
        return false;
    }

    this.isDragging = true;
    this.dragStartPoint = Unidragger.getPointerPoint( pointer );
    // prevent clicks
    this.isPreventingClicks = true;

    this.dragStart( event, pointer );
};
```

So for your situation you would want to add this event handler to any text components, perhaps all `<p>`s inside a flickity cell.
