### ISSUE TITLE
Adjust touch sensitivity between vertical scrolling and Flickity dragging

### ISSUE THREAD

**Issue by mashaal** [metafizzy/flickity#138]
I'm finding the touch a bit sensitive on my phone and tablet - many times my intention is to scroll past the slider, but I end up triggering it. Is there a way I can set the threshold to be a bit higher?

**Comment by desandro** [comment]
Thanks for this feature request. **+1** this issue if you would like to see this feature implemented.

---

One way to adjust when this happens is with this code:

``` js
Flickity.prototype.hasDragStarted = function( moveVector ) {
  // start dragging after pointer has moved 3 pixels in either direction
  return !this.isTouchScrolling && Math.abs( moveVector.x ) > 3;
};
```

Change `3` to a larger value so dragging occurs after moving a greater distance, allowing more wiggle room.

**Comment by dustinhorton** [comment]
+1. thanks for the snippet.

**Comment by MarioDabrowski** [comment]
+1

**Comment by pleek91** [comment]
+1

**Comment by yougotashovel** [comment]
+1 really would love this

**Comment by eldub2001** [comment]
+1

**Comment by spoeken** [comment]
+1 royalslider handles this very well!

**Comment by mdmoreau** [comment]
+1

**Comment by mellinger** [comment]
+1

**Comment by TylerFisher** [comment]
+1 a configuration parameter to adjust the threshold would be excellent.

**Comment by jonanderdev** [comment]
+1 to the snippet
+1 to the configuration parameter

**Comment by idiazroncero** [comment]
+1

**Comment by SirNovi** [comment]
+1 

and thanks for the snippet, I'll try that. I was even wondering about turning the touch feature off. As soon as the slider takes a rather large portion of your smartphone, this get's really problematic

**Comment by spacecat** [comment]
+1

**Comment by gordonwes** [comment]
+1

**Comment by justnorris** [comment]
+1 
A huge issue when the flickity gallery is almost full iPhone screen size. I have to be extremely careful to scroll down straight. Usually, that just means the user leaving :/

**Comment by Dylan-Chapman** [comment]
+1

**Comment by andrewkellerweb** [comment]
+1

**Comment by desandro** [comment]
This issue is now closed :tada: Open a new issue if you run into trouble with `dragThreshold`. Thank you for all the feedback and your patience. Glad to finally ship this one :blush:
