### ISSUE TITLE
Misalignment with lots of cells

### ISSUE THREAD

**Issue by aunruh** [metafizzy/flickity#139]
Hey, I think flickity is the best slideshow plugin out there right now, great job.

I'm using Chrome Version 42.0.2311.135 (64-bit)

I have a little problem, see here:
http://codepen.io/arminunruh/pen/mJPXgE

There are a lot of images in the slideshow. It has "wrapAround" set to true. When you are on the first image, please go back to the last image. You will notice a "gap" on the left side where you see a bit of the previous image. You will notice the gap is the biggest on the last images and the gap is small or non-existing on the first images. You may also notice the gaps have a different size depending on the width of your browser.

![screen shot 2015-05-14 at 09 58 57](https://cloud.githubusercontent.com/assets/1537389/7628150/ea817b54-fa1f-11e4-995c-4811dd78fc74.png)

Do you know how to solve that?

**Comment by desandro** [comment]
Thanks for reporting this issue.  I believe this can be resolved by forcing a scrollbar `html { overflow-y: scroll; }`. See http://codepen.io/desandro/pen/OVNZeL

**Comment by aunruh** [comment]
Hey, thanks for taking a look at this. With your codepen I see the same issue:

![screen shot 2015-05-14 at 15 07 49](https://cloud.githubusercontent.com/assets/1537389/7632225/2b5066f6-fa4b-11e4-82f8-91b0e8e9472f.png)

If you can't see the gap you can try to resize your browser while on the last slide until you see it. As you may see in my screenshot above my `window.innerWidth` is `1219`.

Here's another codepen: http://codepen.io/arminunruh/pen/doMKzE
You can click both buttons on the top left. The right button applies a `translateX` in % to `".flickity-slider"`, the left button applies the `translateX` in px. If you alternate between clicking both buttons you may see the difference.

So I think it has to do with `translateX` being in % and not px? 
Really not sure about why it seems to work better with px positioning for me. Maybe it has something to do with how the browser is rounding things.

**Comment by desandro** [comment]
After looking it over, yes, the problem looks to be setting the position in percent values. A quick fix is to set `percentPosition: false`, which appears to fix this issue. See demo http://codepen.io/desandro/pen/00ec35554f393578a1ebe546877e3583/

**Comment by aunruh** [comment]
Great! Thank you!

**Comment by omerbonfil** [comment]
Thank you, was going nuts over a gap between the cells, setting the percentPosition to false fixed it.
