### ISSUE TITLE
Preventing animation when clicking on a bookmarked slide

### ISSUE THREAD

**Issue by iconologic** [metafizzy/flickity#140]
Greetings:
I have an issue with a project utilizing flickity where we are required to create bookmarkable slides so that the user may click to navigate to any slide within a deck. The issue is the animation that occurs between slides. For example, if I am currently viewing slide #1 and I click on a link to view slide #10 it will cycle through slides #2-8 before showing 9. Is there a method to display slide #10 instantly rather than scrolling through all previous slides? 

Is there something that I can do to override the physics to instantly show the slide on a static click? I know that it's currently hard coded. Could you point me to where that function exists?

Thanks in advance for your support!

**Comment by desandro** [comment]
See my solution in https://github.com/metafizzy/flickity/issues/128#issuecomment-98707460.

Closing this issue here as a duplicate.
