### ISSUE TITLE
Only first div is shown, the rest are blank.

### ISSUE THREAD

**Issue by edinchez** [metafizzy/flickity#143]
I did a basic initiation through HTML leaving the div classes the same as the demo's, "gallery-cell", but only the image in the first div is shown. When I try to slide across to the second div, it shows a blank image, although the class "is-selected" gets added to it. Sometimes the first div is stuck in half with the second div, and when I try to swipe across to the third and/or fourth divs, nothing happens. Nothing moves. Some help would be very appreciated!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by edinchez** [comment]
I just did, and apparently, setting "max-width: 100%;" to the images in the divs was the problem. Any workaround on this?

**Comment by nanov** [comment]
You have tow options, either setting a "max-width : none;" to the the images, or setting s a "width : 100%" to the cells. Take a look here : #141.
