### ISSUE TITLE
prevNextButtons and pageDots demos are switched in docs

### ISSUE THREAD

**Issue by elainen** [metafizzy/flickity#144]
The demo for [prevNextButtons](http://flickity.metafizzy.co/options.html#prevnextbuttons) is showing the page dots, whereas the [pageDots](http://flickity.metafizzy.co/options.html#pagedots) demo is showing the prev/next buttons.

**Comment by desandro** [comment]
Thanks for reporting this issue. Both `prevNextButtons` and `pageDots` are enabled by default. The demos show how to disable them. I realize this is kind of counter-intuitive, but I like it as is.
