### ISSUE TITLE
Unbinding tap event on certain PrevNextArrow

### ISSUE THREAD

**Issue by ChristophLabacher** [metafizzy/flickity#145]
Hello!

I’d like to unbind the tap/click-event of a certain PrevNextArrow in order to (only) fire my own event when it is clicked. I can’t figure out a way to do this. Can you help me?

Help is much appreciated!
Best greets,
Christoph

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

Could you elaborate on what you're trying to achieve? You do not have to use Flickity's default UI. You can use your own. See [Custom navigation UI](http://flickity.metafizzy.co/extras.html#custom-navigation-ui)

**Comment by ChristophLabacher** [comment]
Oh, I didn't realize it was that easy to create a custom navigation. I guess that will solute my problem, I will try it as soon as possible. Thanks!
