### ISSUE TITLE
Possible to control speed of carousel?

### ISSUE THREAD

**Issue by admanami** [metafizzy/flickity#146]
Is there a way to control how fast the slides move from one to the next. I'd like to pause longer on each slide.

**Comment by desandro** [comment]
[Set `autoPlay` to a number](http://flickity.metafizzy.co/options.html#autoplay). `autoPlay: 3000` will advance cells every 3 seconds.

**Comment by admanami** [comment]
Ah, missed it! (I did search for 'speed', 'delay' etc, but didn't see it under 'autoPlay'. Thanks!
