### ISSUE TITLE
Incorrect size calculations, due to Scrollbars being removed during calculation

### ISSUE THREAD

**Issue by AbeCole** [metafizzy/flickity#147]
Have found an issue with the size calculations affecting cells appearing to overlap. When the size calculations are being done in 'getSize' the container already has '.flickity-slider' class added, giving it absolute position and taking it out of the flow. This causes scrollbars to be removed if the total page length is only just over the viewport height. 

The calculations for innerWidth (and other properties) are then done without scrollbars, before the sizes for the container & cells are applied, including height sizing. Once these sizes are applied the height sizing corrects the document flow and scrollbars are re-added, causing the viewport width to change and the calculated sizes to become incorrect.

There are a couple simple solutions for people having issues with this:

1. [Force scrollbars](https://css-tricks.com/snippets/css/force-vertical-scrollbar/), this is the simplest solution as it's just adding CSS however has the down side of adding scrollbars when they may not be necessary.
2. [Call the resize function](http://flickity.metafizzy.co/api.html#resize) after X seconds. A simple `setTimeout(function() { flkty.resize() }, 300)` call should suffice.
3. Meddle with the Flickity source and either: calculate & set the height of the container prior to calculating the width (thus having the rest of the document flow correctly); or calculate the width prior to adding the '.flickity-slider' and removing the content from the flow.

Found this bug while working to a client deadline otherwise I would look at doing the first part of no.3, if you are in a rush I'd just recommend option 1 as it will work close to 100% of the time (100% if you ignore opera OR you use a different method of forcing scrollbars).

**Comment by desandro** [comment]
Thanks for reporting this issue. To better understand the bug, can you help me put together a reduced test case? Try forking this demo: http://codepen.io/desandro/pen/YXNVYa. It has a flickity in an overflow element. The scrollbar is there, but the width of the cells look fine.

**Comment by AbeCole** [comment]
Hi Desandro, I've done that now http://codepen.io/anon/pen/LVxddM . If you inspect the cells and then press to fire the resize event you will see the sizes are updated, prior to this you can also see the second cell overlaps the first's margin. I've added the margin to the gallery and brought the whole viewport width down, it is more noticeable when the gallery is smaller.

Let me know if you want any more info on it, keep up the good work

**Comment by desandro** [comment]
Thanks for that! I forked that demo to check what would happen if it measured size before adding elements, as you suggested:

http://codepen.io/desandro/pen/BNRrea

Your suggestion fixes it. This change will be in the next release of Flickity. Thanks so much for your work putting this issue together! :whale:

**Comment by mitidiero** [comment]
I'm having same issue on windows.

**Comment by ApofisXII** [comment]
This issue is still present, somehow, on Safari browser 17.6
