### ISSUE TITLE
Select cell via #id, link to via href="#id"

### ISSUE THREAD

**Issue by pixelman** [metafizzy/flickity#148]
would be nice to link form another HTML document to a specific slide via an anchor element.
ex.
a href="gallery.html#slide2"

**Comment by PaoloFalomo** [comment]
i've done a jsfiddle for you :)
is [this](https://jsfiddle.net/3n17opm5/) what you're looking for?

The main js code is this:
```html
<h1>Flickity - autoPlay</h1>

<!-- Flickity HTML init -->
<div class="gallery js-flickity" data-flickity-options='{ "autoPlay": true }'>
  <div class="gallery-cell"></div>
  <div class="gallery-cell"></div>
  <div class="gallery-cell"></div>
  <div class="gallery-cell"></div>
  <div class="gallery-cell"></div>
</div>

<div class="specialAncors">
    <a href="#slide1"> slide 1</a>
    <a href="#slide2"> slide 2</a>
    <a href="#slide3"> slide 3</a>
</div>
```

```javascript
jQuery(document).ready(function($){
    $('.specialAncors a').on('click',function(event){
        event.preventDefault();
        var indexElement = $(this).attr('href');
        indexElement = indexElement.replace('#slide','');
        $('.js-flickity').flickity( 'select', parseInt(indexElement)-1 );
    });
});
```

**Comment by pixelman** [comment]
this is exactly what I mean in terms of functionality, but If I try to link from another html doc it's broken…
Changing the url in your browser doesn't work either.

**Comment by PaoloFalomo** [comment]
I'm not sure that i'm understanding what are u trying to do.
Let me give you an example to be sure:
You have the page pageone.html that inside there's a link (or some) like this:
```html
<a href="http://www.domain.extension/pagetwo.html#slide3">Page 2</a>
```
and you want that **on load of page** *pagetwo.html* **the slider** that there's inside of it point to the slide that's specified on the **ancor link** so *#slide3*. Is it right?

### if YES 

##### you've just to work this code on load and catching the window.location var and *et voilà*

:tada::tada::tada::tada:

**Comment by desandro** [comment]
I need to put together an example on how to do this.

**Comment by bravokiloecho** [comment]
+1 for this feature from me. Or if if just involves some example code, that would be useful too!

**Comment by amdad** [comment]
+1

**Comment by desandro** [comment]
Thanks for submitting this feature request. The feature should support

+ Opening a page with `#slide2` in the URL hash should init the gallery with the matching cell
+ Clicking on a link with `href="#slide2"` should select the matching cell
+ Add a method to the API, something like `.select('#slide2')` and it works.

**+1 this issue** if you'd like to see this feature added.

**Comment by pixelman** [comment]
Thank you! Sorry for my late reply. Looking forward to the new feature.

**Comment by bravokiloecho** [comment]
+1 look good

**Comment by amdad** [comment]
+1 again

**Comment by berma** [comment]
+1

**Comment by bkCDL** [comment]
+1 :+1:

**Comment by aaronstezycki** [comment]
+1

**Comment by sharpe89** [comment]
+1

**Comment by k33** [comment]
+1

**Comment by fietstouring** [comment]
+1

**Comment by amdad** [comment]
Hey @desandro Do you plan to add support for it in v2?

**Comment by desandro** [comment]
@amdad Yes. I'm working on Flickity v2 currently.

**Comment by desandro** [comment]
Flickity v2 is out now, with new [`selectCell` method](http://flickity.metafizzy.co/api.html#selectcell). With it, you can select cells via a selector string.

``` js
// jQuery
$carousel.flickity( 'selectCell', '.cell3' )
// vanilla JS
flkty.selectCell('.cell3')
```

Closing this issue now :tada:. Please open a new issue if you run into trouble with `selectCell`. Thank you for your feedback! and your patience. I'm delighted to finally ship this one :blush:

I've opened a new issue for URL hash feature. See #411
