### ISSUE TITLE
When resizing the browser window, the banner moves out of position

### ISSUE THREAD

**Issue by lexbi** [metafizzy/flickity#15]
Hi guys,

This seems to happen most of the time if you scale the browser width down, the banner goes out of position:
http://cl.ly/303T1o2N1z2g

**Comment by desandro** [comment]
Thank you for reporting this issue. I am having trouble with the video. Can you upload a screenshot?

---

Thanks you for this feedback. [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), please email me yo@metafizzy so I can send some your way.

**Comment by lexbi** [comment]
![screenshot 2015-01-27 17 04 26](https://cloud.githubusercontent.com/assets/2337910/5922829/9dade5d8-a646-11e4-921e-a7e90c957c4c.png)

**Comment by desandro** [comment]
Thanks. From the looks of it, I believe you are reporting how Flickity waits until window resizing is done then resizes the cells. So overlapping can occur while resizing, but things should look fine afterwards. If the cells are not being positioned after being resized, then that is indeed a bug. A live test case would help confirm this.

**Comment by lexbi** [comment]
Currently on my project the resizing of the cells doesn't happen when window resizing is done, it only resizes it when the next slide loads! Either with autoplay true or a manual slide change.

**Comment by desandro** [comment]
Can you provide a live URL for me to take a look at?

**Comment by lexbi** [comment]
Sorry it's a dev site, needs to private until live. I can maybe look at setting up a codepen soon, but, I just had a look at your homepage and isn't happening on there, so it's probably some conflicting CSS which will be my fault. I'll close this and look into it. I'll let you know if it's not my own problem :P

Found another issue, but I'll open a new one and close this.
