### ISSUE TITLE
wrapAround with only 2 images

### ISSUE THREAD

**Issue by flatr0ze** [metafizzy/flickity#151]
In case with only two images, wrapAround does not "clone" the wrapping slides properly :cry:

**Comment by PaoloFalomo** [comment]
I've done this jsFiddle to test your case and nothing went wrong: https://jsfiddle.net/xpol555/76hjomo5/

```html
<div class="gallery js-flickity" data-flickity-options='{ "imagesLoaded": true, "percentPosition": false,"wrapAround": true }'>
    <img src="http://i.imgur.com/bwy74ok.jpg" alt="orange tree" />
    <img src="http://i.imgur.com/bAZWoqx.jpg" alt="submerged" />
</div>

```

### Can you do a jsFiddle of your case?

**Comment by desandro** [comment]
Yes, this is an issue. But there's no good solution to it.

Best fix is to use at least 3 cells when using `wrapAround`.

Closing as `wontfix`.

**Comment by PaoloFalomo** [comment]
![Still looking for the problem...](http://cdn.meme.am/instances/250x250/61333013.jpg)
