### ISSUE TITLE
add disabled Class to custom navigation.

### ISSUE THREAD

**Issue by zenics** [metafizzy/flickity#152]
Any way to add a class when no more slide to go to like native nav arrows (like button--previous disabled)

<code><pre>
// previous
$('.button--previous').on( 'click', function() {
  $Carousel.flickity('previous');
});
// next
$('.button--next').on( 'click', function() {
  $Carousel.flickity('next');
});

</pre><code>

**Comment by desandro** [comment]
Yes, use the API to add the behavoir on `cellSelect`. See demo http://codepen.io/desandro/pen/VLPJqO

``` js
$gallery.on( 'cellSelect', function() {
  // enable/disable previous/next buttons
  if ( !flkty.cells[ flkty.selectedIndex - 1 ] ) {
    // on first cell
    $previousButton.attr( 'disabled', 'disabled' );
  } else if ( !flkty.cells[ flkty.selectedIndex + 1 ] ) {
    // on last cell
    $nextButton.attr( 'disabled', 'disabled' );
  } else {
    $previousButton.removeAttr('disabled');
    $nextButton.removeAttr('disabled');
  }
});
```

**Comment by damienroche** [comment]
@desandro I think it doesn't works if we have only 2 cells.
