### ISSUE TITLE
Images Loading Very Slowly

### ISSUE THREAD

**Issue by isbara** [metafizzy/flickity#153]
Hi, I have a main gallery and on that gallery every images getting another gallery but its take a lot of time. Why is that?
```
$(document).ready(function() {
$(".loader-inner").hide();
});
$(document).ready(function() {
$("#nbg1").on("click", function(){
$("#gnc2").css("display","none");
$(".loader-inner").show();
$('#mmg1').load('galeri.html #tr1 img', function() {
$('.main-gallery').flickity( {
cellAlign: 'left',
contain: true,
prevNextButtons: false,
freeScroll: true,
pageDots: false,
imagesLoaded: true
});
$('#mmg1').waitForImages({
each: function(){
$(".loader-inner").fadeOut("slow")
}
});
});
});
});
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
