### ISSUE TITLE
dynamic variableWidth support?

### ISSUE THREAD

**Issue by peucaio** [metafizzy/flickity#154]
Hi desandro,
I need to ask the experts if there's a way of using a variable width for the cell widths, the same effect found in slick slide. I need a slider that shows dynamic paintings from database, all with height: 320px but different proportional widths (some paintings are square, so 320x320px, some are vertical 240x320px). This width needs to be calculated on the fly based on the image height.

I've tried some workarounds using css, such as
.gallery-cell {
height:320px;
width: auto;
}
and many others, but couldn't make it work. Using different cell sizes controlled by css is also not possible, since there are hundreds of different painting sizes.

Can you imagine any way of doing it via css or is it a feature request?

Thanks.
Pedro

**Comment by desandro** [comment]
The image demo uses images with different widths, all set to the same height. See http://codepen.io/desandro/pen/GgQREP

It sets the height of images

``` css
.gallery-cell img {
  display: block;
  height: 320px;
}
```

Have you tried this?

**Comment by peucaio** [comment]
Thanks desandro, it worked as a charm. I didn't know flickity recognized image without putting inside a div.
