### ISSUE TITLE
Functionality breaks when inserting html via Ajax on first call.

### ISSUE THREAD

**Issue by TyAdams4** [metafizzy/flickity#155]
I'm initializing a flickity gallery after loading html via Ajax, but on the first call the functionality breaks. If I reload the html it works fine. 

The first time, the arrows show up, but have no functionality. If I load it a second time, it works fine. I setup my script to only initialize flickity once the images are loaded, but now the images will show up without the gallery first, then the gallery takes over and formats them causing it to look off for a second while flickity loads.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
