### ISSUE TITLE
Image height missed in initial height sizing

### ISSUE THREAD

**Issue by JasonTheAdams** [metafizzy/flickity#157]
First issue posted, so I have to say: flickity is awesome. Straight up. What a find. Bam. :)

I'm having one issue, however, that is pretty strange. The flickity slides consist of an image and some buttons underneath. When flickity first loads I get this chopped effect, wherein it's clearly only providing enough height for the buttons, but since they're beneath the image it just looks chopped.

If the browser is resized, or I wait a second and call the resize function, then it snaps to the perfect height. I'm also swapping out sets of slides in the same flickity, and when I do this the same issue happens.

It seems as though flickity calculates the height before the image has a chance to load and provide its height.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by JasonTheAdams** [comment]
I believe this has to do with the [imagesLoaded](http://flickity.metafizzy.co/options.html#imagesloaded) option. Since I believe that's the solution I missed and I've moved one, I'll close the issue.
