### ISSUE TITLE
Issue with flicking/cells being skipped on the iPhone

### ISSUE THREAD

**Issue by danielflodin** [metafizzy/flickity#162]
I've had some issues on the iPhone with the carousel going from first to last cell immediately in one flick (similar to [#43](https://github.com/metafizzy/flickity/issues/43)) as well as sometimes skipping through multiple slides.

I've made a video of this which is available [here](http://somevid.com/Ny9akkuL). It is recorded on http://flickity.metafizzy.co/, but is basically appearing in all instances I've come across. In the recording I had to exaggerate my flicks with the mouse in order to similate what I'm experiencing. On the real device though I'd say that I use pretty much just regular swipes.

Is this a threshold issue or something or what could it be? Seeing as Flickity is working beautifully on both my iPad and on desktop I'm also thinking of whether or not it has something to do with the smaller screen size/swipeable area making it more sensitive??

**Comment by desandro** [comment]
Thanks for reporting this. I'll move your comment to #43 so we can track progress on one issue.

The tricky part of this issue is that I haven't been able to reliably reproduce it. I just gave it another test and everything is behaving appropriately on the device.
