### ISSUE TITLE
loadComplete and renderComplete Events?

### ISSUE THREAD

**Issue by RatGit** [metafizzy/flickity#165]
Are there any events I can use to add callback functions when Flickity has loaded itself into the DOM and also when it has completely finished rendering itself?

**Comment by desandro** [comment]
> when Flickity has loaded itself into the DOM

> when it has completely finished rendering itself

After you initialize Flickity, it's ready to go

``` js
var $carousel = $('.carousel').flickity({
  // options
});
// Flickity is ready
```

**Comment by MerlinBB** [comment]
Hey Dave,

I have a related question and was wondering if you can help... I'm trying to find a reliable way to know when Flickity has finished rendering so I can do some other page operations based on the height of the carousel. Take the following code snippet, outerHeight is reported differently on each console log.

```
new Flickity($(el).get(0), {
    // opts
});
console.log(($(el).outerHeight(true));

setTimeout(() => {
    console.log(($(el).outerHeight(true));
}, 1000);
```

Using setTimeout feel pretty brittle, are you aware of a better way I can detect the finish of the initial render?

Thanks!
