### ISSUE TITLE
watchCSS no longer working in Internet Explorer

### ISSUE THREAD

**Issue by mdmoreau** [metafizzy/flickity#166]
Windows 7 IE version 11.0.9600.17843

It seems like a recent update to IE may have broken the watchCSS feature in Flickity.  It was working fine before on multiple project sites and your demos, but now all seem to never pick up the ::after value to enable Flickity.  This is happening in every emulation mode for me as well.

Any ideas what might be causing this issue?

**Comment by desandro** [comment]
Thanks for reporting this bug. I was not able to reproduce it with the [`watchCSS` demo](http://codepen.io/desandro/pen/NPyWbQ). Do you have a **reduced test case** I could look at? Try forking the [watchCSS CodePen](http://codepen.io/desandro/pen/NPyWbQ). [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by mdmoreau** [comment]
Yeah your demo at http://s.codepen.io/desandro/debug/NPyWbQ? is what I tested on after I saw that mine didn't work.  I know my project (and I assume the demo as well) were working fine a week or so ago the last time I checked it in IE, so I'm wondering if a browser update broke something.

There are no errors displayed or anything - the slideshow just never kicks in.  In IE dev tools it even looks like the ::after pseudo element is being picked up correctly from what I can tell, but the slides still stay stacked.

Was able to find an older machine running Win 7 IE 11.0.9600.17633 / 11.0.16 and the demo seems to be working fine for now.  In the process of upgrading that, so I'll let you know if it breaks once the new browser version is installed.

**Comment by mdmoreau** [comment]
Once I upgraded IE (11.0.9600.17843 / 11.0.20) the same issue appeared on the second machine.  Hopefully it's related to some IE bug they caused with the update and can patch, but I figured you'd still want to know in case it ends up being something fixable in Flickity.
