### ISSUE TITLE
Broken with Wiredep

### ISSUE THREAD

**Issue by klase** [metafizzy/flickity#168]
I'm getting "ReferenceError: Flickity is not defined" when using the bower version of Flickity with asset-builder. Seems like index.js doesn't return a global version?

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm not familiar with asset-builder. Can you share your JS for how you're using it with Flickity?

**Comment by klase** [comment]
I'm not sure actually if it's specifically with asset-builder, but I'm using it as part of the build process for Sage (https://roots.io/sage/docs/theme-development/). It reads your project's bower.json and automatically collects the js file defined in Flickity's bower.json main property and bundles it according to the dependency tree. Since Flickity's main property in the Flickity bower package points to "js/index.js" it is what's included in my bundle, but index.js doesn't set the global window.Flickity variable anywhere. It seems that the main js file in other bower packages (including Flickity's dependencies) do.

For example, bower.json in the classie bower package has its main property set to 'classie.js', and in there:

if ( typeof define === 'function' && define.amd ) {
  // AMD
  define( classie );
} else if ( typeof exports === 'object' ) {
  // CommonJS
  module.exports = classie;
} else {
  // browser global
  window.classie = classie;
}

**Comment by klase** [comment]
Actually this is probably a wiredep issue.

**Comment by desandro** [comment]
Try adding Flickity's js file to wiredep's overrides.

``` json
"overrides": {
  "flickity": {
    "main": [
      "js/flickity.js",
      "js/drag.js",
      "js/prev-next-button.js",
      "js/page-dots.js",
      "js/player.js",
      "js/add-remove-cell.js",
      "js/lazyload.js"
    ]
  }
}
```

This is part of a larger issue with Bower we're looking to resolve in bower/bower.json-spec#47.

**Comment by klase** [comment]
Works like a charm. Thanks for helping out, really appreciate it. Especially since it's not really a Flickity issue.

**Comment by desandro** [comment]
Bower + Wiredep usage has decreased in past 1.5 years. I'm closing this one as `wontfix`.
