### ISSUE TITLE
Flickity v2: drop IE8 and 9 support

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#178]
Flickity will be dropping support for IE8 and IE9 in the next major version, v2. Expected release date in early 2016.

The time has come. [Browser usage](http://caniuse.com/usage-table) for IE8 is 2%, IE9 is 1.5%. Android 2 and 3 support will also be dropped. These are the last browsers with large feature gaps. By dropping support for them, we can remove a lot of code including helper libraries: [eventie](https://github.com/desandro/eventie), [classie](https://github.com/desandro/classie) and [doc-ready](https://github.com/desandro/doc-ready).

Flickity v1 will still be made available to download and view documentation.

**Comment by CaptainCodeman** [comment]
Lots of mainstream javascript frameworks (e.g. Angular 2) are dropping support for these older versions of IE so I don't think that's a bad decision - the sooner the better !

**Comment by julienbenisty** [comment]
I second that.
Although developing sites for mainly the Asian market, I see more IE8-9 usage than North America or Europe due to the existing normalization of pirating windows XP; I think it's the only way to go. These 2 version are so old, so making people who are still using ancient browsers see with a warning that it's time to update or they will not enjoy modern is the only way to push them.

**Comment by nicholas-c** [comment]
Don't see why not!

As of 12th Jan 2016 MS Are dropping all support anyway; 

http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx

**Comment by ivancuric** [comment]
Agreed. It's also easy to do a fallback to a simple tab-like slider for ie8.

**Comment by desandro** [comment]
[Flickity v2 is out now](http://flickity.metafizzy.co)! Time to close up this one.

[Flickity v1 will still be available](http://flickity.metafizzy.co/v1/) if you need IE8+ or Android 2.3+ support.

**Comment by Fortyfive** [comment]
Wondered there was a way to add IE9 support into Flickity v2 without having to roll back to Flickity v1 so that I can retain some of the v2 benefits? I have a client who is specifically looking for IE9 support. Thanks

**Comment by desandro** [comment]
@Fortyfive sorry, nope. Flickity v2 and its many dependencies were all refactored to remove IE9 support.

**Comment by Fortyfive** [comment]
No problem, thanks!

**Comment by bentalgad** [comment]
Is there a simple solution to have a nice fallback or even to the v1 fallback for users that use ie 10 and less ?

**Comment by desandro** [comment]
Flickity v1 documentation is available to view & download at https://flickity.metafizzy.co/v1

**Comment by bentalgad** [comment]
Thanks, Yes i know that. my question is if i want to use v2, is there a way to detect that the v2 can't work on the user's browser and then load v1 ?

**Comment by desandro** [comment]
You could do a quick & dirty check for a feature like classList

``` js
if ( 'classList' in document.documentElement ) {
  // Flickity v2 okay
} else {
  // Flickity v1 required
}
```

It's not foolproof, but it could work.
