### ISSUE TITLE
cellSelect fired when image loads

### ISSUE THREAD

**Issue by edull24** [metafizzy/flickity#179]
The cellSelect event is fired when an image loads when using the imagesLoaded and/or lazyLoad options.

imagesLoaded example: http://codepen.io/edull24/pen/aOqqMq

lazyLoad example: http://codepen.io/edull24/pen/XbZEXE

**Comment by desandro** [comment]
Yup. This behavior is intended. When a cell changes size, and [`reposition`](http://flickity.metafizzy.co/api.html#reposition) is called, it calls `select` on the selected cell. This is an easy way to reposition cells.

If you're finding this behavior to be problematic, I recommend adding logic to check if the [`selectedIndex`](http://flickity.metafizzy.co/api.html#selectedindex) has changed on cellSelect

``` js
var previousIndex = flkty.selectedIndex;
$carousel.on( 'cellSelect', function() {
  if ( flkty.selectedIndex == previousIndex ) {
    // same index
     return;
  }
  // different index...
  previousIndex = flkty.selectedIndex;
});
```

**Comment by edull24** [comment]
Ah ok thanks for the explanation!
