### ISSUE TITLE
Custom navigation UI IE8 Error with Lazy Load

### ISSUE THREAD

**Issue by aaronstezycki** [metafizzy/flickity#184]
Unfortunately I have to support IE8, and I'm currently getting an error when using the example code for the custom navigation and Lazy Loading. It works in all other browsers, but when I add lazyLoad: 2 to the initialisation it fails and crashes in IE8. Should I be using the vanilla version of the code for IE8 to work?

http://flickity.metafizzy.co/extras.html#custom-navigation-ui

hashtag I hate IE8. :(

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by aaronstezycki** [comment]
Well, the example above you have given is the test case. Add lazyLoad: 2 to the javascript on the Var $gallery, and then open this in IE8 and you will see that this combination of parameters will crash the browser.
