### ISSUE TITLE
Option to horizontally re-position arrows

### ISSUE THREAD

**Issue by corysimmons** [metafizzy/flickity#186]
Is there such an option? If not, could we add one?

Just something to bump the arrows more or less off the edges.

**Comment by desandro** [comment]
Thanks for reporting this issue. You can re-position arrows with CSS. See http://flickity.metafizzy.co/style.html#previous-next-buttons

**Comment by corysimmons** [comment]
Yeah I know. I was suggesting adding an option in there that just automatically does it for you.
