### ISSUE TITLE
autoPlay animation speed

### ISSUE THREAD

**Issue by animaux** [metafizzy/flickity#188]
It seems there is no way to control the speed of the slide transition itself when using autoplay. Is there?

Thanks for this nice script btw :)

**Comment by desandro** [comment]
Thanks for your input. You can adjust transition speed with [`selectedAttraction` and `friction`](http://flickity.metafizzy.co/options.html#selectedattraction-friction)

**Comment by animaux** [comment]
Brilliant thanks!

**Comment by raphaelokon** [comment]
I would add a note in the docs regarding this or add a `duration` property that shims those behaviors.
