### ISSUE TITLE
100 slide animations seem to activate at once when returning to page after browsing another tab

### ISSUE THREAD

**Issue by lexbi** [metafizzy/flickity#19]
I have noticed that if you load a page with flickity running (with autoplay going), then jump to another tab for a couple of minutes then go back it seems to go through 100 slides at once (this is with wrapAround:true)

**Comment by desandro** [comment]
Right-o! This will be fixed in the next release. Closing as a duplicate of #6

**Comment by lexbi** [comment]
ah sorry i didn't see that.
