### ISSUE TITLE
Document leftArrowText and rightArrowText

### ISSUE THREAD

**Issue by LagunaCompany** [metafizzy/flickity#190]
Is it worth documenting these options somewhere? They're quite handy if you need to set arrow text for browsers that don't support SVG arrows. You get a button tag with the corresponding text within it

`
var flickityOptions = {
    leftArrowText: '<',
    rightArrowText: '>'
};
`

**Comment by desandro** [comment]
Bravo for finding this! Yes, `leftArrowText` and `rightArrowText` are options that allow you to set the text of the button for [browsers that do not support inline SVG](http://caniuse.com/#search=inline%20svg). Only IE8 and Android 2 do not have support, and I'll be dropping support for these browsers in 2016, see #178. So I'm okay with keeping these undocumented.

I'm curious: what browsers did you need these for?

**Comment by LagunaCompany** [comment]
Primarily for good old IE8!

My company is seeing IE8 usage fade away, but looking beyond that, I was toying with the idea of combining these options with icon fonts. That might be quite handy for re-using some of the icons we already use on our websites, or for using new ones from places like [Icomoon](https://icomoon.io/).
