### ISSUE TITLE
IE10 Bug with cell images width set to 100%

### ISSUE THREAD

**Issue by aaronstezycki** [metafizzy/flickity#193]
When setting a 100% width to cell images within the gallery, flickity applies height incorrectly in Internet Explorer. 

If you then go through the entire set of images, and resize the browser, it fixes itself.

Here is a test case. Open this in IE10, or any IE version for that matter.
http://codepen.io/aaron-stez/full/WvgBqJ

![screen-shot](https://cloud.githubusercontent.com/assets/5744600/8850187/c27632e4-313d-11e5-9452-39685f628a54.jpg)

**Comment by aaronstezycki** [comment]
Just to justify why you would want images at 100%, if you have images of different widths or are too small to fill its container, you end up with vertical or horizontal areas of space in the container. Setting a min width (as advised <a href="http://flickity.metafizzy.co/options.html#lazyload">here</a>) is not good responsive practise.

**Comment by desandro** [comment]
Looks like the demo on CodePen is no longer up. Closing this issue. Please re-open if you're able to provide another test case.
