### ISSUE TITLE
Add an option to disable focus on click

### ISSUE THREAD

**Issue by EugeneDae** [metafizzy/flickity#194]
This is a follow-up to #111.

![b297716c-3084-11e5-9f31-ad044ab136d6](https://cloud.githubusercontent.com/assets/980835/8856970/e63acdbe-3176-11e5-8740-743d18b59b4c.gif)

Focusing may be the right thing to do by all standards, but I think most people will agree that the behaviour depicted in the GIF is counterintuitive and confusing.

Please add an option to disable it.

**Comment by nvartolomei** [comment]
@EugeneDae http://flickity.metafizzy.co/options.html#accessibility set this to false.

**Comment by desandro** [comment]
@nvartolomei has it. Set `accessibility: false`. Which is not recommended. Again, from https://github.com/metafizzy/flickity/issues/76#issuecomment-77430660

> This behavior is actually a feature of keyboard accessibility. By clicking/tapping on a gallery, it adds focus to its element. This will jump the scroll so that element is completely in the viewport.
> 
> If this behavior is really bugging you, you can disable it with accessibility: false -- which I don't recommend because accessibility is a wonderful thing.
