### ISSUE TITLE
lazyLoad Event Original Event Target is undefined

### ISSUE THREAD

**Issue by maimairel** [metafizzy/flickity#195]
Hi, 

On the documentation of Flickity, the lazyLoad event callback should receive two arguments, `event` and `cellElement`. The documentation stated that we could access the loaded image through `event.originalEvent.target`, but the originalEvent object's target property is undefined.

Is this a bug or did I miss something?

Thank you!

**Comment by maimairel** [comment]
Event initializing Flickity with vanilla JS produces the same result.

**Comment by desandro** [comment]
I've added demos for [lazyLoad event](http://flickity.metafizzy.co/api.html#lazyload). Try these out

+ jQuery: http://codepen.io/desandro/pen/RPqMra
+ vanilla JS: http://codepen.io/desandro/pen/VLVXjv

If you're using jQuery, with `$gallery.on()` then you need to use `event.originalEvent` to get the image, with `event.originalEvent.target`. If you're using vanilla JS, with `flickity.on()` then you can use `event.target`.

**Comment by maimairel** [comment]
Yes, that is the exact code I have but `event.originalEvent.target` is `undefined`. Inspecting the event object on the eventie code already shows an undefined target property.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
