### ISSUE TITLE
Windows Phone 8.1 & Windows Surface - Unable to scroll past Flickity

### ISSUE THREAD

**Issue by MarioDabrowski** [metafizzy/flickity#196]
When you scroll to a flickity instance, you are unable to scroll up or down from the flickity container. The only way around this is if you can somehow grab an element that is not part of flickity.

I've tried the fix from the following issue #138 but didn't have any luck.

To reproduce you can access any of the flickity instances on http://flickity.metafizzy.co/ Testing on a physical device and on browserstack produce the same result.

Any ideas on how we could prevent this from happening?

**Comment by desandro** [comment]
Thanks for reporting this issue. I'll have to investigate.

**Comment by jamieohanlon** [comment]
I've been having the same issue. Frustrating.

**Comment by filipbocek** [comment]
We have the same problem. And we did not find any workaroud.

**Comment by igorkulman** [comment]
Same problem here.

**Comment by desandro** [comment]
Thank you for chiming in! I'm closing this issue here and grouping it together with #97. Please follow & discuss on that issue.
