### ISSUE TITLE
Event for keyboad control of carousel?

### ISSUE THREAD

**Issue by cmeeren** [metafizzy/flickity#197]
When using arrow keys to control the carousel, the autoplay stops (as it should). I would like to detect when this has happened (specifically, I have a visible timer which I use for indicating the time to next slide, and I need to stop this when flickity has been cycled by keyboard presses). Is this possible?

**Comment by desandro** [comment]
autoPlay stops on two events: `uiChange` and `pointerDown`. [`pointerDown` is a documented event](http://flickity.metafizzy.co/api.html#pointerdown).

`uiChange` is not documented as Flickity uses it internally, but you can still use it.

``` js
// jQuery
// using .flickity() plugin method syntax
$carousel.flickity( 'once', 'uiChange', function() {
  // player stops
});
```

``` js
// vanilla JS
flkty.once( 'uiChange', function() {
  // player stops
});
```
