### ISSUE TITLE
how to build latests changes? and commercial usage

### ISSUE THREAD

**Issue by boynet** [metafizzy/flickity#20]
1. how do I build the latest changes? 
2. its ok to use it in commercial site untill you release it for sell and than buying?

**Comment by desandro** [comment]
Thank you for your interest in Flickity! I appreciate your enthusiasm to start using Flickity today.

> how do I build the latest changes?

``` bash
npm install
bower install
gulp
```

Although, the `pkgd` files might be broken when you try, because I'm doing local development and haven't synced all my changes with Bower dependencies.

> its ok to use it in commercial site untill you release it for sell and than buying?

Yes, you may use Flickity beta on commercial sites.

**Comment by hydrotik** [comment]
Can you explain the implications of using this on a commercial site? Seems a little vague to me and we're weighing the options on this versus Slick.

**Comment by desandro** [comment]
Sure thing. I'm working with my legal on a proper Commercial license for Flickity. Until that is released, you may use Flickity under [GPL v3](http://www.gnu.org/copyleft/gpl.html). You may use Flickity version 0.x in commercial site under the terms of the GPL.

An important term of the GPL is that it is sticky. By using Flickity v0.x, you must license your work as GPL. [Section 5](http://www.gnu.org/copyleft/gpl.html#section5):

> 5c. You must license the entire work, as a whole, under this License [GPL v3] to anyone who comes into possession of a copy.

If you are wary of GPL stickiness, or would prefer a more liberal license, I would advising either using another solution, like [Slick](http://kenwheeler.github.io/slick/), or wait until the Flickity Commercial License is released.

**Comment by desandro** [comment]
Flickity v1 is released, and with it, complete licensing terms including commercial licensing: http://flickity.metafizzy.co/license.html

**Comment by hydrotik** [comment]
Commercial license indicates a single developer, is there a different license for usage at a company with multiple developers?

**Comment by desandro** [comment]
@hydrotik There are three kinds of commercial license: developer, team, and organization http://flickity.metafizzy.co/license.html#purchasing-a-commercial-license

You can click Developer / Team / Organization buttons above the license terms to read each license terms. The changed terms are highlighted in blue. http://flickity.metafizzy.co/license.html#flickity-commercial-license-agreement

**Comment by hydrotik** [comment]
Got it thanks! Cheers!

**Comment by zaphod77** [comment]
So can i try to put a carousel into a website and then pay later once i've worked out the modifications to make it do what i want (use data from a mysql database)?  or must i buy it first? i will have to test on a customers website with the customer's data.  and will i be fine with the developer license?  what if the customer then messes with the webpage?  is it only the css and js code that the other person can't change?

**Comment by desandro** [comment]
@zaphod77 Try it out first, then buy when you're ready. You do not need to purchase an additional license if the end user has to make some revisions.
