### ISSUE TITLE
Any chance of an option 'fade' on the roadmap? For some break-points?

### ISSUE THREAD

**Issue by sheriffderek** [metafizzy/flickity#200]
Any chance of an option 'fade' on the roadmap? For some break-points?

Sometimes, I like to have the great swipey action on small touch devices, but then at a large screen - fading seems more appropriate.

Right now I switch out responsive slider and flickity - but I always love "a better way."

PS, I would have labeled this 'question' and/or 'feature request' - but I don't know how, or if that is even a permission I have.

Thanks.

**Comment by desandro** [comment]
Thanks for your input! We've already got an open issue for this feature request. See #26.
