### ISSUE TITLE
not responsive with image and Bootstrap

### ISSUE THREAD

**Issue by xavierartot** [metafizzy/flickity#202]
Hi,
I use Bootstrap:

    #carousel {
      position: relative;
      .main-gallery {
	padding: 0;
	.flickity-page-dots {
	  bottom: 15px; 
	  left: 0;
	  padding-left: 40px;
	  text-align: left;
	}
	.gallery-cell {
	  height: auto;
	  img{
	    /*@include img-responsive();*/
	    min-width: 150px;
	  }
	}
      }
    }

  ` <div class="main-gallery">
       <div class="gallery-cell"><img src="http://placehold/1200x400/E8E8E8" alt="lack image" /></div>
       <div class="gallery-cell"><img src="http://placeholdt/1200x400/cccccc" alt="lack image" /></div>
       <div class="gallery-cell"><img src="http://placeholt/1200x400/E1E1E1" alt="lack image" /></div>
   </div>`
   
   
             $('.main-gallery').flickity({
            // options
            prevNextButtons: false,
            cellAlign: 'left',
            freeScroll: true,
            imagesLoaded: true,
            lazyLoad: true,
            autoPlay: true,
            wrapAround: true,
            contain: true
          });
 
 
 What's wrong with that?
 
 Thanks

**Comment by waqasss** [comment]
Same issue on bootstrap, The "flickity-viewport" doesn't resize itself on changing screen width.

**Comment by xavierartot** [comment]
I just use another carousel ):

**Comment by infn8** [comment]
Devil's Advocate, @waqasss do you have the screen resize meta tag? 
```
<meta name="viewport" content="width=device-width, initial-scale=1" />
```
I know I use flickity with Bootstrap all the time and it's all good.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by waqasss** [comment]
@infn8 Yes I tried with and without viewport tag.
@desandro Please accept the provided pen as reduced test case. It uses Flickity v1.1.0 unaltered. 

http://codepen.io/waqasss/pen/QbYXRa

**Comment by desandro** [comment]
@waqasss Thanks for the CodePen. Images will not be resized responsively because they are using the intrinsic size of the photo (500px height) for the size  of the slider. If you do want to resize the slider proportional the size of the window, see the [full-bleed demo with  `setGallerySize: false`](http://flickity.metafizzy.co/options.html#setgallerysize)

**Comment by waqasss** [comment]
Thanks you. I added some custom css. Now its working fine.

**Comment by memo510** [comment]
im having the same issue :(

**Comment by marknuyens** [comment]
@waqasy May I ask you how you've resolved the issue using CSS? I am currently facing the same challenge, but can't seem to get it working (properly). -- Thank you.
