### ISSUE TITLE
Graphical Glitch on Flickity Load - Images Overlapping - Webkit Browsers

### ISSUE THREAD

**Issue by AlvSovereign** [metafizzy/flickity#206]
Hi

I am having an issue when my page loads the first time. The images seen to collapse and overlap each other.

The issue also happens only with webkit browsers (Chrome and Opera - cannot test Safari as I do not own a Mac).

The issue is rectified when I resize the viewport.

On mobile, the same issue occurs (Webkit browsers)

Please go here to see : http://coconutkizombaclub.com/gallery.html

Any ideas?

Thanks for your help.

EDIT: I have recreated the issue on Firefox as well.

AlvSovereign

**Comment by AlvSovereign** [comment]
Just to add, I have recreated the issue on Firefox now as well.

**Comment by desandro** [comment]
Try using [the `imagesLoaded` option](http://flickity.metafizzy.co/options.html#imagesloaded)

**Comment by AlvSovereign** [comment]
Hi Desandro

Thanks for your help.

Your solution has seemed to fix the collapsing images.

The second issue is when the browser loads. Images load (as is should) in a top down column fashion, before the javascript code (including Flickity) loads. The first image in the gallery stays as a background of the image gallery when flickity rearranges the images. Thus the image appears in the gaps made between the images (the gaps are the "padding-right : 5vw" that I have added.

I have worked around this to remove the padding.

**Comment by mjcampagna** [comment]
I'm having this same issue, and using imagesLoaded:true doesn't seem to be solving it. This seems only to occur at small display sizes. Any ideas?

**Comment by thomaslove** [comment]
Also getting this issue myself on Chrome 59. Any suggestions?

**Comment by desandro** [comment]
@mjcampagna @thomaslove Sorry to hear you're running into this issue. Could you provide a **reduced test case**? So I can better understand what's going on. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by sirbootoo** [comment]
Please I am having this same issue with my project, The images overlap each other on webkit browsers. How can this be solved ?

**Comment by mjcampagna** [comment]
@sirbootoo Less a solution, more a workaround, the only thing I was able to do to reliably address this was to make the images themselves the slides, i.e.

````html
<div class="wrapper">
<img src="..." />
<img src="..." />
<img src="..." />
</div>
````
This, of course, limits what you can do. When uses DIVs as slides, containing my images (and maybe other things), the script was unable to determine the size of the slides, and so they would just pile up. This might be something you can get around by providing a fixed width for each slide, but then it's difficult to make things responsive, or to allow the images to have their native width and/or scaling with the viewport.

**Comment by atloveday** [comment]
I also had this issue.

My solution:
Add a class to all Flickety images to hide them and then in javascript unhide the images when the DOM has loaded.

Regards

Andrew

**Comment by lucademontis** [comment]
For the second issue, I simply added some CSS where the first child of the carousel is on display: block and the others on display: none. The moment flickity is triggered and the class .flickity-enabled is added, all carousel cells are on display: block.

**Comment by MattrCoUk** [comment]
None of those worked for me...
In my case the `carousel-cell` element's CSS `left` property is incorrectly calculated on document-load. It fixes itself after viewport resize though hence this hacky workaround: force the resize event ;-)

		<script> 
		    document.addEventListener('DOMContentLoaded', function () {
		        setTimeout(function () {  
		            window.dispatchEvent(new Event('resize')); // flickity fix
		        }, 200);
		    });
		</script>

**Comment by gunavara** [comment]
> 

Thank you for this, @MattrCoUk!
