### ISSUE TITLE
Disable autoPlay on 'select' api call

### ISSUE THREAD

**Issue by klase** [metafizzy/flickity#207]
It would be good if changing index via the api would also turn off autoPlay, for example when using a custom nav ui. Or is there an api call to turn off autoPlay manually?

**Comment by desandro** [comment]
Thanks for asking! You can stop the player with the `stopPlayer` method

``` js
// jQuery
$gallery.flickity('stopPlayer');

// vanilla JS
flkty.stopPlayer();
```

This is a currently undocumented method. You're right to ask about it.

`select` does not stop autoPlay because autoPlay uses `select` :grin:

**Comment by klase** [comment]
Sweet just what I needed thanks. I'll go ahead and close this then.

**Comment by desandro** [comment]
[v1.2.0](https://github.com/metafizzy/flickity/releases/tag/v1.2.0) has added [proper auto-play API](http://localhost/flickity-docs/build/api.html#player): `playPlayer`, `stopPlayer`, `pausePlayer`, `unpausePlayer`.
