### ISSUE TITLE
Chrome 44 sliding issue (slide randomly jumping rather than sliding)

### ISSUE THREAD

**Issue by richgcook** [metafizzy/flickity#208]
Hi folks,

I've just started to use this plugin again after a few weeks and noticed that the slides sometimes 'jump' to position rather than 'slide' to position (Chrome only). I then remembered I found the same issue with fullPage.js which uses CSS3 animations. The issue was then raised with the Chrome devs.

The issue seems to have been resolved within the plugin, rather than Chrome fixing the bug, which you can view here: https://github.com/alvarotrigo/fullPage.js/issues/1389

Is anyone else having the same issue? And if so perhaps this is a fix (using the `requestAnimFrame` function).

Thanks.

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you specify when this bug happens? Is this with autoPlay?

This sounds like a browser bug. fullPage.js resolved their bug by wrapping stuff in requestAnimationFrame. Flickity already uses requestAnimationFrame. If this is a browser bug, then I'm likely to let it go in the hopes that it'd be fixed on Chrome's side, rather than developing a custom solution.

**Comment by richgcook** [comment]
Definitely, @desandro – I agree... and wasn't expecting a custom solution at all... we all know how this stuff goes :+1:

I'm not using autoPlay, but below is my setup below. What happens is that for the first few slides it seems to bounce right in, but then once you've got it going to slides in as normal. I have also attached a .mov screengrab to show you. http://d.pr/v/13IFR

```
function projectSlider() {
	$('.project-slider').flickity({
	    lazyLoad: 2,
	    wrapAround: true,
	    prevNextButtons: false,
	    pageDots: false
	});
	$('.project-slider-container').each(function (i, container) {
	    var $container = $(container);
	    var $slider = $container.find('.project-slider');
	    var $counter = $('.project-slider-counter');
	    var flkty = $slider.data('flickity');
	    $container.find('.project-slider-navigation .next').on('click', function(e) {
	        $slider.flickity('next');
	        e.preventDefault();
	    });
	    $container.find('.project-slider-navigation .prev').on('click', function(e) {
	        $slider.flickity('previous');
	        e.preventDefault();
	    });
	    $slider.on('lazyLoad', function() {
	        $slider.flickity('resize');
	    });
	    function updateCounter() {
			var cellNumber = flkty.selectedIndex + 1;
			$counter.text(cellNumber + '/' + flkty.cells.length);
		}
		updateCounter();
		$slider.on('cellSelect', updateCounter);
	});
}
projectSlider();
```

Thanks!

**Comment by desandro** [comment]
Thanks for the code and the movie. I haven't seen this bug occur like it does in the movie, but I'll keep an eye out for it.

Looking at your code, you should be able to remove `$slider.on('lazyLoad' ...` bit. Flickity will resize cells after images have been loaded. This code is not necessary.

**Comment by richgcook** [comment]
Thanks @desandro; I will try to do some more testing and debugging to see if I can work it out.

**Comment by desandro** [comment]
Closing as no one else chimed in.

**Comment by richgcook** [comment]
@desandro I still continually have this issue... on all sorts of setups... definitely not related to fullpage.js as most of the time I just use it as a standard slider.

**Comment by desandro** [comment]
Thanks for following up. fullpage.js's fix was to use requestAnimationFrame, which Flickity already does. As no else has reported this bug, I'm leaving it as a browser edge case. If others start reporting the issue, I'll take another look.

**Comment by richgcook** [comment]
Thanks for replying. Just frustrating as I cannot work out what I am doing wrong... or what would make this happen. Cheers again.

**Comment by richgcook** [comment]
Still a bug. I wonder why it hasn't gone with Chrome's many updates since? Definitely haven't encountered this in Safari.

**Comment by na86** [comment]
Hi David, 
foa thanks for your amazing work, with all your libraries.

i'm reporting the same issue, my flickity carousel skips randomly trough slides and i'm not able to control it. 

that's my configuration. 
here my config: 

`var $carousel = $('.main-carousel');
  	$carousel.flickity({
	  pageDots: false,
	  prevNextButtons: false,
	  wrapAround: true,
	  cellAlign: 'left',
	  contain: true, 
	  selectedAttraction: 1,
	  friction: 1
	});
	$('.button--previous-wrapped').on( 'click', function() {
	  $carousel.flickity( 'previous', true );
	});
	// next wrapped
	$('.button--next-wrapped').on( 'click', function() {
	  $carousel.flickity( 'next', true );
	});`

Any ideas of what's going on? 
anyway thanks a lot for everithing. 

nnd

**Comment by richgcook** [comment]
Still a bug in Chrome. Any thoughts @desandro?

**Comment by desandro** [comment]
Sorry but I will not be debugging this issue.

**Comment by richgcook** [comment]
I will @desandro :) leave it with me.

**Comment by engram-design** [comment]
@richgcook I certainly noticed it too - must have been very recent. Seems that when I flick between the start/end slides, it goes a little crazy. Happy to take an updated video (or live URL) if it helps.

**Comment by engram-design** [comment]
@desandro Not sure if this is the same issue, but using the latest 2.0.2 version jumps between the first/last slide when using wrapAround. You can see a demo on the main hero image here - http://wefindhouses.madebys.com.au/

Just using:
```
$('.home-hero .slider-mask').flickity({
    cellSelector: '.slide',
    wrapAround: true,
    prevNextButtons: true,
    pageDots: true,
    autoPlay: 10000,
    pauseAutoPlayOnHover: true,
});
```

**Comment by richgcook** [comment]
@engram-design That's not a flickity issue... that's your code. You have `transition: all 0.3s ease;` set on your `.slide` which is... wrong 👍

**Comment by engram-design** [comment]
@richgcook You're totally right - just tracked that down to. Sorry to waste your time - carry on! 😃

**Comment by jonschmitz** [comment]
For anyone else having this issue… it is related to having a `transition` on your carousel-cell.

**Comment by skillmatic-co** [comment]
Yep, had this issue in 2024. Was having weird transition issues in Safari only. I had a css transition set on my slideshow parent. Removed this and the issue disappeared.
