### ISSUE TITLE
Very unforgiving on touchscreens when attempting to scroll vertically

### ISSUE THREAD

**Issue by pleek91** [metafizzy/flickity#209]
This is more of a feature request but it could be considered a bug as well. 

On touch screens and particularly mobile devices (tested on iPhone 5s and Droid Ultra), flickity tends to capture touch events when a user attempts to scroll vertically by touching in the flickity viewport and dragging up or down. This results in the flickity slider wiggling back and forth (following the slight side to side movement of the users finger) and the page not scrolling. This is only an issue if draggable is set to true and especially if the slider has not settled before the user attempts to scroll. 

Maybe add a tolerance setting? A lower tolerance would result in a more responsive slider and a higher tolerance would be more forgiving.

**Comment by desandro** [comment]
Thank you for this feedback. Others have requested an option to customize this behavior. See #138. Closing this issue here. Continue conversation there.
