### ISSUE TITLE
Unable to focus or open <select> on click

### ISSUE THREAD

**Issue by gordonwes** [metafizzy/flickity#21]
Hi, there is a issue when you implement a html form inside a slide, the textform and select tags don't apply the :focus state when clicked, and then as a result the list of options won't open and you can't input text.
However i noticed that when you right click on it,  :focus state is applied.
Thanks for this amazing plugin, very fluid!

A. G.

**Comment by desandro** [comment]
Thanks for reporting this issue. I'll have to take a look to see if this can be fixed.

**Comment by desandro** [comment]
Fixed in v0.2.0 :white_check_mark:
