### ISSUE TITLE
Accessing slide's data and binding to specific event

### ISSUE THREAD

**Issue by richgcook** [metafizzy/flickity#210]
Each of my 'slides' have some data attributes that I would like to use when you first load the slider and when you slide to the next.

For example: `<div class="each-slide" data-color="black"></div>` but I am struggling to work out how to access these data attributes.

I thought this would work:

``` js
$slider.on('cellSelect', function() {
    var slideColor = flkty.selectedElement.data('color');
    alert(slideColor);
});
````
So when it loads or slides, it would grab the selectedElement's data (and I set up an alert to test this) but it simple states, as an error in my console: `Uncaught TypeError: o.selectedElement.data is not a function`

Am I missing something? Also, regards the 'when the slider loads or slides', cycle2 has a decent event `cycle-update-view` which fires on load and on a 'cycle'. Does flickity?

Thanks, @desandro.

**Comment by richgcook** [comment]
It's weird that if I just use:
```
$slider.on('cellSelect', function() {
    var slideColor = flkty.selectedElement;
    console.log(slideColor);
});
```
It outputs the right slide and HTML etc, but when I try to get anything (data element, class etc.) it outputs the same error: `Uncaught TypeError: o.selectedElement.data is not a function` or `Uncaught TypeError: o.selectedElement.attr is not a function`

**Comment by richgcook** [comment]
Reduced case: http://codepen.io/anon/pen/JdVLQe

**Comment by desandro** [comment]
Close! Let's clear some things up.

+ `flkty` is a `Flickity` instance
+ `flkty.selectedElement` is a property of `flickity`. It is a HTML Element.
+  `.data()` is a jQuery method

In order to use `.data()` ( or `.attr()`), you need a jQuery object. Wrap `flkty.selectedElement` in `$()` to do so.

``` js
$slider.on('cellSelect', function() {
    var slideColor = $(flkty.selectedElement).data('color');
    console.log(slideColor);
});
```

See example: http://codepen.io/desandro/pen/LVvdvq

---

> regards the 'when the slider loads or slides', cycle2 has a decent event `cycle-update-view` which fires on load and on a 'cycle'. Does flickity?

cycle2's `cycle-update-view` sounds very much like Flickity's `cellSelect`.

**Comment by richgcook** [comment]
@desandro MAN! I was close... not quite sure how I missed that. Thanks for the help and explanation.

Re the `cellSelect` event... this is only triggered on slide though, right? Not when the slider initialises as well?

**Comment by richgcook** [comment]
I guess I could do `$slider.on('load cellSelect', function() {` ?

**Comment by richgcook** [comment]
Just to say that I realised that `settle` would work; but you cannot have two events bound to the same function `$slider.on('settle cellSelect', function() {` like you can have with standard jQuery events... so had to set up two different events.
