### ISSUE TITLE
Strategy foi avoiding FOUC

### ISSUE THREAD

**Issue by lmartins** [metafizzy/flickity#211]
Hi,

Do you recommend any strategy to avoid FOUC on Flickity sliders?

Thanks.

**Comment by christophermiles** [comment]
+1

**Comment by Primaginary** [comment]
I would appreciate any hint on this too! Thanks in advance.

**Comment by albell** [comment]
My approach: First give the html element a `no-js` class.

    <html class="no-js" lang="en">

then use script to immediately replace that class with "js" in the document `<head>`

    (function(doc) { 
	    doc.className = doc.className.replace(/(^|\b)no\-js(\b|$)/, 'js');
    }(document.documentElement));

Then give your slides classes:

    <div class="carousel_slide">Something here</div>

Then write css to make the carousel with js (but flickity not yet initialized) look like the carousel with flickity initialized. For example, hide overflow on the container, etc. This will depend completely on your layout, css, and selected options. 

In my current case I'm only showing one carousel item at a time, so I use:

    // FOUC. When js is active, Initially hide all but first carousel item 
    .js .carousel_slide + .carousel_slide {
	    display: none;
    }
    // Make all visible once flickity is initialized
    .js .flickity-slider .carousel_slide {
	    display: flex;
    }

Then there's the question of what to show in the admittedly rare `.no-js` case. I'm happy to just dump all the carousel items in consecutive order, so the user gets all the content. Hope this helps.

**Comment by ericthayer** [comment]
I found that "fading" in the gallery after JS fires works best. Here is the CSS I used.

```
 // This helps w/ FOUC; 
.gallery,
.gallery-cell {
  opacity: 0;
  transition: opacity 200ms ease;
  &.flickity-enabled {
    opacity: 1;
    .gallery-cell {
      opacity: 1; 
    }
  }
}
```

**Comment by desandro** [comment]
Here is one approach. See demo http://codepen.io/desandro/pen/KVwVqa/

With CSS set the gallery's opacity to 0, enable opacity transition, and add a class to hide the gallery.

``` html
<div class="gallery is-hidden is-faded-out">
```

``` css
.gallery {
  opacity: 0;
  -webkit-transition: opacity 0.4s;
  transition: opacity 0.4s;
}

.gallery.is-hidden {
  display: none;
}
```

In JS, remove the hidden class, trigger the opacity [transition with a redraw](http://blog.alexmaccaw.com/css-transitions), and initialize Flickity.

``` js
// show
var $gallery = $('.gallery').removeClass('is-hidden');
// trigger redraw for transition
$gallery[0].offsetHeight;
// init Flickity
$gallery.flickity();
```

**Comment by desandro** [comment]
This demo is now linked in [Extra demos](http://flickity.metafizzy.co/extras.html#extra-demos)
