### ISSUE TITLE
zoom functionality

### ISSUE THREAD

**Issue by stefangeorge** [metafizzy/flickity#213]
I have flickity working well but would like the flickity container to be fullscreen when tapped. In other words, The flickity carousel should zoom to occupy the whole screen with a little 'x' in the top right to return to the web page. Is this possible?

**Comment by desandro** [comment]
Yes, this is possible. After resizing the Flickity element, trigger [`resize`](http://flickity.metafizzy.co/api.html#resize). As to making a Flickity fullscreen, that's a separate implementation. See duplicate issue #28
