### ISSUE TITLE
Imageloaded with safari and firefox

### ISSUE THREAD

**Issue by paulorzoni** [metafizzy/flickity#214]
Hello,

I first installed flickity without the imageloaded option then I experienced the behavior described in the doc which throw off cell positions. Then I imported the flickity-imagesloaded.js which solved the problem on chrome. 

Unfortunately it seems that we still have this little moment when all the images appear on top of each other on safari and firefox.

Any idea about how to solve this?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
