### ISSUE TITLE
Smoothly animate reposition() and prepend/append/insert/removing gallery elements

### ISSUE THREAD

**Issue by bornytm** [metafizzy/flickity#215]
Flickity is fantastic!

I'm working towards building a dynamic UI that leverages the library (as well as packery). 

Is there currently a way to avoid gallery element overlapping while adding/removing and smoothly animating width changes of gallery elements?

The goal is to add cell allocation that reflects the gallery elements width (even while in transition).

**Comment by desandro** [comment]
Thank you for this feature request. **+1 this issue** if you would like to see this feature added to Flickity.

**Comment by oskarrough** [comment]
+1. One use case would be a gallery where the `.is-selected` cell has twice the size of the other cells. I've attempted a pattern as this:

```css
.gallery-cell {
  width: 33%;
  transition: width 400ms;
}
.gallery-cell.is-selected {
  width: 66%;
}
```

```javascript
let gallery = new Flickity('.gallery');
gallery.on('cellSelect', () => {
  gallery.selectedElement.addEventListener('transitionend', () => {
    gallery.reposition();
  }, false);
});
```

… but it of course doesn't animate smoothly. Any ideas how to approach it?

**Comment by desandro** [comment]
Looks like this did not get much public interest. Closing. Thank you for this feature request! :strawberry:

**Comment by JesseHigson** [comment]
@desandro any chance of this getting this re-reviewed for upcoming versions of Flickity?

**Comment by desandro** [comment]
@JesseHigson Sorry nope.

**Comment by maycontainweasel** [comment]
I would also really appreciate this feature, could you give us an idea of how you would accomplish this is we wanted to animate the repositioning? thanks for the amazing work!

**Comment by desandro** [comment]
Look into [Flickity.prototype._positionCells in flickity.js](https://github.com/metafizzy/flickity/blob/master/js/flickity.js#L260)

**Comment by t-walker-wei** [comment]
+1 I would like to see this feature added to Flickity
