### ISSUE TITLE
input type range is unusable inside the slider cell

### ISSUE THREAD

**Issue by praveenpuglia** [metafizzy/flickity#216]
### What's happening?

The `range` input type is not usable inside slider cell. The swipe on slide always takes the precedence over the actual event on the input. The only way to be able to use it by focusing on it via keyboard or mouse and then use the arrow keys.

### What's expected?

The range input should be usable and while changing it's value, it should not trigger the swipe event.

### Where's the demo?
http://codepen.io/praveenpuglia/pen/doByxg

**Comment by desandro** [comment]
Thanks for reporting this bug. I'll be evaluating a solution.

**Comment by praveenpuglia** [comment]
Cool! :+1:

**Comment by desandro** [comment]
Fixed in Flickity v1.1.1. [Try it out!](http://flickity.metafizzy.co/) :pear:

**Comment by praveenpuglia** [comment]
Thanks for fixing this! tested. works! :+1:
