### ISSUE TITLE
Access flickity gallery from different starting image

### ISSUE THREAD

**Issue by bwanaaa** [metafizzy/flickity#217]
I want have a flickity gallery of 100 images. There are 10 spots in my blog that I want to access the same flickity gallery. However I want the flickity carousel to show a different 'cover' image at each point in the blog. Each point in the blog is a different part of a hiking trail. I want the user to be able to flick through the whole trail at any given 'entry' point. It sounds simple but I don't know how to reuse a flickity gallery and just specify a different 'starting point'. The only way I can construct this is to reproduce the entire flickity gallery with a different image order at each of the 10 points in my blog.

**Comment by bwanaaa** [comment]
I know I can use the 'initial index' variable in the html but is there a way to avoiding re typing the entire list of 100 images?

**Comment by desandro** [comment]
What you're asking for deals more with general JavaScript or HTML templating than it does with Flickity specifically. Sorry, but I won't be able to provide support here.
