### ISSUE TITLE
Responsive full-bleed images

### ISSUE THREAD

**Issue by bwanaaa** [metafizzy/flickity#219]
Here is a website made with flickity:
https://bwanaaa.github.io/pictest/
For some reason, the flickity gallery does not show up until you resize the page. The top image is static and I want a full bleed pic that scales with the page. Here is the css I used:

```
/* external css: flickity.css */
img {
    max-width: 100%;
    width: inherit !important;
    height: inherit !important;
}
* {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}
body { 
     height: auto;
    width: 100%;
    background-color: #000;
    color: #fff;
}
```
The flickity gallery however did not scale proportionately like the static image. Here is a code pen:

http://codepen.io/littleredbowtie/pen/yNdOMQ

The navigation arrows do not stay centered when resizing the page. I tried changing the css from:
```
 max-width: auto;
    width: inherit !important;
    height: inherit !important;
```
to this:
```
.gallery-cell img {
  display: block;
  max-width: 100%;
  max-height: 100%;
```
No improvement. When I add media selectors, it does not seem to help:

http://codepen.io/littleredbowtie/pen/gpNMWB

Can the navigation arrows be centered on each image? or do I have to scale the images so they are all the same height?

**Comment by desandro** [comment]
[See `setGallerySize: false`](http://flickity.metafizzy.co/options.html#setgallerysize). You can set the size of the gallery to 100% width and height, for a "full-bleed" gallery. How you size the images within that gallery is up to you. You may want to try using background images, rather than `<img>` elements.
