### ISSUE TITLE
Slide by group

### ISSUE THREAD

**Issue by myconcretelab** [metafizzy/flickity#22]
Playing with this great slider, i realize that it doesn't scroll with group of slide. Eg : When i see three slide in the viewport i expect, when i click on the next button, to have the next three slide. Or we just have the capabilities to have the next slide, one by one.
Is it in project ?

Thanks !

**Comment by lunelson** [comment]
:+1: 
this would be a relevant option WRT the `cellAlign` and `contain` options—depending on the hard-coded or CSS width

**Comment by desandro** [comment]
If you would like to see this feature, please +1

Ha, I wondered when this request was going to come up. Yes, I think it would be a nice feature. When you see 3 cells, you expect that swiping will show you 3 new ones, not just increment to the next cell.

This feature might be a big undertaking, as it adds an additional concept: the group.

**Comment by lunelson** [comment]
I wonder if a group concept is necessary--it seems to me the question is how many items are visible currently, and maybe also how many would be visible on the next swipe right or left. Note that these could also be different: e.g. one skinny item is shown in the middle of the viewport, two items are visible to the right (one fully, one partially), but only one is visible to the left (partially). So if you swipe right it should advance by 2, but if you swipe left only 1.

**Comment by ryanberg** [comment]
:+1: 
Finally went to give the beta a spin for a project I'm working on, and immediately ran into this current limitation. No question, it's an additional layer or two of complexity to handle. FWIW, it might not require groups in the HTML structure, but perhaps groups within the javascript object.

**Comment by FROLoff** [comment]
+1, but I don't need groups — I need just simple carousel behavior. Like this: http://flexslider.woothemes.com/basic-carousel.html

**Comment by zslabs** [comment]
+1

**Comment by boynet** [comment]
+1

**Comment by chrispif** [comment]
+1

**Comment by kylegach** [comment]
+1

**Comment by jasonwbullok** [comment]
+1

**Comment by fa6ian** [comment]
+1

**Comment by anoosurf** [comment]
+1

**Comment by terkelg** [comment]
+1

**Comment by ThijmenDeValk** [comment]
+1

**Comment by atacrawl** [comment]
+1

**Comment by evoactivity** [comment]
+1

**Comment by mican** [comment]
+1

**Comment by impsart** [comment]
+1

**Comment by jackrugile** [comment]
+1

**Comment by alanbrowndesign** [comment]
+1

**Comment by johndugan** [comment]
+1

**Comment by pseidemann** [comment]
+1

**Comment by BernoH** [comment]
+1

**Comment by BenHaldenby** [comment]
+1

**Comment by jonnyhaynes** [comment]
+1

**Comment by dennisfrank** [comment]
+1

**Comment by joshrounsville** [comment]
+1

**Comment by amywieliczka** [comment]
+1

**Comment by wekii** [comment]
+1

**Comment by Jinksi** [comment]
I was able to produce a similar effect for the prev/next buttons using this:

```javascript
	$('.flickity-prev-next-button.next').click(function(){
		var flkty = $featured_carousel.data('flickity');
		var defaultSelect = flkty.selectedIndex;
		var newSelect = defaultSelect + 2;
		$featured_carousel.flickity( 'select', newSelect );
	});
	$('.flickity-prev-next-button.previous').click(function(){
		var flkty = $featured_carousel.data('flickity');
		var defaultSelect = flkty.selectedIndex;
		var newSelect = defaultSelect - 2;
		$featured_carousel.flickity( 'select', newSelect );
	});
```

**Comment by rctneil** [comment]
+1

**Comment by cmeeren** [comment]
+1

**Comment by jonathanmoore** [comment]
Heck ya! +1 :+1:

**Comment by squiss** [comment]
+1 PLEASE!

**Comment by quebec87** [comment]
+1 Thanks

**Comment by thomas-gordon** [comment]
+1

**Comment by carburant** [comment]
+1

**Comment by guillaumeCarburant** [comment]
+1

**Comment by joriscolours** [comment]
+1

**Comment by kud** [comment]
+1

**Comment by juhalehtonen** [comment]
+1

**Comment by circa1983** [comment]
+1

**Comment by tomtev** [comment]
What about having a 'scrollVisible' option?

That would scroll all visible slides at once and the Next / Prev nav would be disabled if there is no more slide groups to scroll. There should also just be one bullet pr visible slides group.

**Comment by michaelwoodruff** [comment]
+1
It seems http://www.fabletics.com/ has figured out how to do this.

**Comment by jessehart** [comment]
+1
almost pulled the trigger on this until i saw this wasn't an option.
my expectation is that it would scroll the visible count (which could be diff per breakpoint)

**Comment by michaelwoodruff** [comment]
@jessehart had the exact same thought

**Comment by pseidemann** [comment]
this is easy to implement yourself via overwriting the slide methods.
just load this script (coffeescript, jquery needed) after loading flickity, but before the code which initializes your flickity galleries:
```coffeescript
# change flickity slide selection behavior to navigate per page instead of per element

Flickity.prototype.computeActiveCells = ->
  totalWidth = $(@viewport).width()
  cellWidth = $(@slider.children[0]).outerWidth(true)

  return Math.floor(totalWidth / cellWidth)

Flickity.prototype.previous = (isWrap) ->
  if @options.wrapAround
    @select(@selectedIndex - 1, isWrap)
  else
    index = @selectedIndex - @computeActiveCells()
    index = 0 if index < 0
    @select(index, isWrap)

Flickity.prototype.next = (isWrap) ->
  if @options.wrapAround
    @select(@selectedIndex + 1, isWrap)
  else
    index = @selectedIndex + @computeActiveCells()
    lastIndex = @cells.length - 1
    index = lastIndex if index > lastIndex
    @select(index, isWrap)
```

using Flickity PACKAGED v1.0.2

**Comment by desandro** [comment]
@pseidemann Nice work! This solution may work for simple use cases, but is likely break when used with the rest of Flickity's feature set.

**Comment by esbenam** [comment]
I went a bit further with @pseidemann s idea since I need pageDots and prevNextButtons. You can add a slideByGroup property to your options and it will handle the rest.

It is propably in need of a refactor and a general cleanup, but it seems to do the trick right now. (It doesn't support wrapAround)

   

<pre>
/**
 *
 * Flickity overrid to support slide by page
 *
 */

// Addition: we need to be able to tell how many cells are visible
Flickity.prototype.computeActiveCells = function() {
	var totalWidth = this.viewport.offsetWidth,
		cellWidth = this.slider.children[0].offsetWidth,

		// floor the percentageWidth before calculating
		// to minimize unfortunate off-by-one errors
		cellPercentageWidth = Math.floor(((cellWidth / totalWidth) * 100));

	return this.options.slideByGroup ? Math.floor(100 / cellPercentageWidth) : 1;
};

Flickity.prototype.previous = function(isWrap) {
	// Addition: we need to move by active-cells, not just one
	if (this.options.slideByGroup) {
		index = this.selectedIndex - this.computeActiveCells();
		index = index < 0 ? 0 : index;
		this.select(index, isWrap);
	} else {
		this.select(this.selectedIndex - 1, isWrap);
	}
};

Flickity.prototype.next = function(isWrap) {
	// Addition: we need to move by active-cells, not just one
	if (this.options.slideByGroup) {
		// If the last cell is visible don't do anything
		if (this.selectedIndex > this.cells.length - 1 - this.computeActiveCells()) {
			return;
		}

		index = this.selectedIndex + this.computeActiveCells();
		lastIndex = this.cells.length - 1;
		index = index > lastIndex ? lastIndex : index;
		this.select(index, isWrap);
	} else {
		this.select(this.selectedIndex + 1, isWrap);
	}
};

Flickity.prototype.resize = function () {
	if ( !this.isActive ) {
		return;
	}
	this.getSize();
	// wrap values
	if ( this.options.wrapAround ) {
		this.x = (( this.x % this.slideableWidth ) + this.slideableWidth ) % this.slideableWidth;
	}

	this.positionCells();
	this._getWrapShiftCells();
	this.setGallerySize();

	// Addition: on resize we always set the selected cell
	// to the first in the active group
	if (this.options.slideByGroup){
		this.selectedIndex = this.pageDots.computeGroupIndex(this.selectedIndex) * this.computeActiveCells();
	}

	this.positionSliderAtSelected();

	// Addition: we need to update dots on resize
	// since they can change now
	if (this.options.slideByGroup){
		this.pageDots.removeDots(this.cells.length);
		this.pageDots.setDots();
		this.pageDots.updateSelected();
	}
};




/**
 *
 * PrevNextButton override
 *
 */

Flickity.PrevNextButton.prototype.update = function () {
	// index of first or last cell, if previous or next
	var cells = this.parent.cells;
    // enable is wrapAround and at least 2 cells
	if ( this.parent.options.wrapAround && cells.length > 1 ) {
	    this.enable();
		return;
	}

	var lastIndex = cells.length ? cells.length - 1 : 0;
	var boundIndex;
	var method;

	// Addition: we need to disable active-cell-count before first/last index
	if (this.parent.options.slideByGroup) {
		boundIndex = this.isPrevious ? this.parent.computeActiveCells() : lastIndex - this.parent.computeActiveCells();

		if (this.isPrevious) {
			method = this.parent.selectedIndex < boundIndex ? "disable" : "enable";
		} else {
			method = this.parent.selectedIndex > boundIndex ? "disable" : "enable";
		}
	} else {
		boundIndex = this.isPrevious ? 0 : lastIndex;
		method = this.parent.selectedIndex == boundIndex ? 'disable' : 'enable';
	}

	this[ method ]();
};




/**
 *
 * PageDots override
 *
 */

Flickity.PageDots.prototype.setDots = function () {
	// get difference between number of cells and number of dots
	// Addition: take active cells into consideration
	var delta = Math.ceil(this.parent.cells.length / this.parent.computeActiveCells()) - this.dots.length;
    if ( delta > 0 ) {
	    this.addDots( delta );
	} else if ( delta < 0 ) {
		this.removeDots( -delta );
	}
};

Flickity.PageDots.prototype.updateSelected = function () {
	if ( this.selectedDot ) {
		this.selectedDot.className = 'dot';
	}
	// don't proceed if no dots
	if ( !this.dots.length ) {
		return;
	}

	// Addition: take active cells into consideration
	var index = this.parent.options.slideByGroup ? this.computeGroupIndex(this.parent.selectedIndex) : this.parent.selectedIndex;

	this.selectedDot = this.dots[ index ];
	this.selectedDot.className = 'dot is-selected';
};

// Addition: Returns the group the given index belongs to
Flickity.PageDots.prototype.computeGroupIndex = function (index) {
	return Math.floor(index / this.parent.computeActiveCells());
};

Flickity.PageDots.prototype.onTap = function (event) {
	var target = event.target, index, computed, cells;
	// only care about dot clicks
    if ( target.nodeName != 'LI' ) {
	    return;
	}

	this.parent.uiChange();

	// Addition: We need to multiply the index with
	// of the dot with the active cells count
	index = this.dots.indexOf(target);
	computed = this.parent.computeActiveCells();
	cells = this.parent.cells.length;

	index = index * computed > cells ? cells -1 : index * computed;

	this.parent.select( index );
};




/**
 *
 * Drag override
 *
 */

Flickity.prototype.dragEnd = function( event, pointer ) {
	if (this.options.slideByGroup) {
		if (this.dragX < this.previousDragX) {
			this.next();
		} else {
			this.previous();
		}
		delete this.previousDragX;
		return;
	} else {
		if ( this.options.freeScroll ) {
			this.isFreeScrolling = true;
		}
		// set selectedIndex based on where flick will end up
		var index = this.dragEndRestingSelect();

		if ( this.options.freeScroll && !this.options.wrapAround ) {
			// if free-scroll & not wrap around
			// do not free-scroll if going outside of bounding cells
			// so bounding cells can attract slider, and keep it in bounds
			var restingX = this.getRestingPosition();
			this.isFreeScrolling = -restingX > this.cells[0].target &&
				-restingX < this.getLastCell().target;
		} else if ( !this.options.freeScroll && index == this.selectedIndex ) {
			// boost selection if selected index has not changed
			index += this.dragEndBoostSelect();
		}

		delete this.previousDragX;

		// apply selection
		// TODO refactor this, selecting here feels weird
		this.select( index );
		this.dispatchEvent( 'dragEnd', event, [ pointer ] );
	}
};
</pre>

**Comment by nonlinearcom** [comment]
+1

**Comment by benjasHu** [comment]
+1

**Comment by Harrald** [comment]
+1

**Comment by imran-p** [comment]
+1

**Comment by neilhem** [comment]
:+1:

**Comment by raywongjr** [comment]
+1

**Comment by stevemayhew** [comment]
Here's my take on it...  Just add an option to return the step value for prev/next that allows many different options for how far to move.  This combines two branches (cell-visibility-feature, prevNextStepBy-opt-feature) and their pull requests I've submitted into one:
  https://github.com/stevemayhew/flickity/tree/slide-by-group

Here's the CodePen:  http://s.codepen.io/stevemayhew/debug/WrNNEe

And the pull request: 
 https://github.com/metafizzy/flickity/pull/294

**Comment by gyachuk** [comment]
Nice solution, Steve. 

Just looked at your CodePen. Looks like the prevNextStepBy callback function makes it very general purpose.

````javascript
  var $gallery = $('.gallery').flickity({
    cellAlign: 'left',
    pageDots: false,
    percentPosition: false,
    prevNextStepBy: function(direction, isWrap) {
      return this.getVisibleCellElements().length - 1;
    },
    contain: true
  });
````

With a default of "1", we get the standard behavior. Otherwise, we can come up with any dynamic amount of scroll that we want.

Great job.

**Comment by amdad** [comment]
+1

**Comment by OACDesigns** [comment]
@amdad I've just been working on this for my own project. 
I needed to be able to drag and flick the slider and have the cells act as a group.
(I have also worked on tweaking the "flick" behaviour by adding in thresholds for flick distance and velocity, something else that was bugging me).

I'm not sure if it's worth creating a pull request for any of this (would need more integration and deeper testing), but here is a codepen with the overloaded classes for anyone needing the same functionality. I've also overloaded the `next()` and `previous()` functions but not the `select()`.

http://codepen.io/OACDesigns/pen/BjLOKp

**Comment by amdad** [comment]
That's cool. Can this change number of displayed items according to width?

**Comment by OACDesigns** [comment]
no, I've only been interested in flicking 2 cells at a time (i.e. left and right pages of a book).
In fact you've just made me realise that as a result I've actually done more complicated things (like using modulus to ensure the slides are always even)....meaning this codepen wouldn't work with a group of say 3.

I suppose If you could tell how many cells were in view at any time you could dynamically update how many cells to flick by. I'm not sure if there's something in Flickity to tell you this.

in the interest of curiosity i'll see if I can quickly change the codepen to always change by x number of cells rather than using the modulus....

**Comment by OACDesigns** [comment]
I updated the codepen. It now moves by the specified number of cells each time

**Comment by amdad** [comment]
I see, now it's 3 slides. So you can add switch to 2 slides for smaller width? I mean responsiv.

**Comment by OACDesigns** [comment]
I'm specifying the width of the slides in the css and then using a matching group size according to that. So in the example I have the images set to 1/3 of the width of their container and then have the group size set to 3 so it always changes 3 images at a time.
I guess you could have it reduce to 2 slides responsively. You'd need to update the group size, maybe by listening to the window `resize` event and changing it accordingly

**Comment by alsontann** [comment]
+1

**Comment by lunelson** [comment]
Nice work @OACDesigns—that was exactly what I needed :+1:

**Comment by benjasHu** [comment]
If someone is interested, I've made this code to only show grouping page dots. It can be improved using resize events. :)

```javascript
const $dots = $(flkty.pageDots.dots)
			
$dots.hide()
$dots.each((i, el) => {
	if(i%flkty.options.cellGrouping === 0)
		$(el).show()
})
```

**Comment by desandro** [comment]
**It's on.** :sunglasses:  I'll be working on a grouping feature for Flickity v2. ETA: Spring 2016.

+ Cells can be grouped into slides
+ Groups work as a single cell. When dragged, or flicked, they align as groups
+ Default grouping will be visible cells in the viewport
+ Previous/next buttons will select previous/next group
+ Page dots will represent groups, not the cells

Thanks so much for your feedback over the past year. Hold tight a bit longer.

**Comment by amdad** [comment]
That's cool. What about this https://github.com/metafizzy/flickity/issues/239 ? Will be included too?

**Comment by apsolut** [comment]
+1

**Comment by pjmay** [comment]
I know it's a little bit different, but to get a simple slide group behavior you can use a container as your cell-selector, i.e. 

```html
<div class="gallery js-flickity">
  <div class="cell-group">
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
  </div>
  <div class="cell-group">
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
  </div>
  <div class="cell-group">
    <div class="cell"></div>
    <div class="cell"></div>
    <div class="cell"></div>
  </div>
</div
```

**Comment by qbunt** [comment]
@desandro How's the v2 looking? We have an immediate need for grouping and Flickity definitely the best option.

**Comment by sumobi** [comment]
+1

**Comment by funwithtriangles** [comment]
+1

**Comment by martinwolf** [comment]
+1

**Comment by jeroenkampinga** [comment]
+1

**Comment by vanjadevcic** [comment]
+1

**Comment by Laosing** [comment]
+1

**Comment by desandro** [comment]
Flickity v2 is out now, with new [`groupCells` option](http://flickity.metafizzy.co/options.html#groupcells). [See basic groupCells demo on CodePen](http://codepen.io/desandro/pen/XKZXyv).

Flicking, page dots, and previous/next buttons are mapped to group slides, not individual cells.

``` js
groupCells: true
// if set to true,
// group cells that fit in carousel viewport

groupCells: 2
// if set to a number, group cells by that number

groupCells: '80%'
// if set to a percent string,
// group cells that fit in the percent of
// the width of the carousel viewport
```

See complete [groupCells documentation and demos](http://flickity.metafizzy.co/options.html#groupcells). 

This issue is now closed :tada:. Thank you for all the feedback and your patience. I'm delighted to finally ship this one :blush:
