### ISSUE TITLE
End of gallery or last cell event?

### ISSUE THREAD

**Issue by Melbournite** [metafizzy/flickity#220]
Is there currently a way of determining when the end of a gallery is reached?

Intention is to automatically load more content via AJAX when event is triggered, however I can't figure out the best way of determining end of gallery.

If someone has an idea I'd be very appreciative.

For reference, I've currently put this together which appears to work when within the total cells - 3. I guess I could add the ajax call where true to append cells unless there is another way.

``` js
$gallery.on( 'settle', function() {
    var settleCell = flkty.selectedIndex;
    var cellCount = flkty.cells.length;
    var triggerMin = 3;

    var triggerEvent = false;
    if ( settleCell > (cellCount - triggerMin)) {
        triggerEvent = true;
    }

    console.log( 'Flickity settled at ' + settleCell );
    console.log( 'Flickity has ' + cellCount );
    console.log( 'triggerMin is ' + triggerMin );
    console.log( 'triggerEvent is ' + triggerEvent );

});
```

**Comment by Melbournite** [comment]
For reference, I've currently put this together which appears to work when within the total cells - 3. I guess I could add the ajax call where true to append cells unless there is another way.

          $gallery.on( 'settle', function() {
              var settleCell = flkty.selectedIndex;
              var cellCount = flkty.cells.length;
              var triggerMin = 3;

              var triggerEvent = false;
              if ( settleCell > (cellCount - triggerMin)) {
                  triggerEvent = true;
              }

              console.log( 'Flickity settled at ' + settleCell );
              console.log( 'Flickity has ' + cellCount );
              console.log( 'triggerMin is ' + triggerMin );
              console.log( 'triggerEvent is ' + triggerEvent );

          });

**Comment by desandro** [comment]
Your code is a great way to do it. The [`cellSelect`](http://flickity.metafizzy.co/api.html#cellselect) or [`settle` event](http://flickity.metafizzy.co/api.html#settle) would both work. Here's a simplified example:

``` js
// get Flickity instance
var flkty = $gallery.data('flickity');

$gallery.on( 'cellSelect', function() {
  if ( flkty.selectedIndex == flkty.cells.length - 1 ) {
    console.log('last cell selected')
  }
});
```

**Comment by maxfenton** [comment]
:pray:
