### ISSUE TITLE
staticClick fires when dragging on iPhone

### ISSUE THREAD

**Issue by cmeeren** [metafizzy/flickity#221]
I'm using the following code:

````javascript
$carousel = $('.flickity-carousel').flickity({
  ...
});

$carousel.on('staticClick', function() {
  $('#modal-read-buttons').modal('show');
});
````

Works fine on PC and Android, but on iPhone the modal shows even when sliding.

**Comment by desandro** [comment]
I wasn't able to reproduce this issue on my iPhone. See demo http://s.codepen.io/desandro/debug/RNQgxe . Can you provide a reduced test case?

**Comment by cmeeren** [comment]
Unfortunately no. One of my test users reported this (on a rather complex website), I don't have an iPhone myself. I worked around it by placing the desired javascript code in a function called in an ``href`` attribute instead. Unfortunately I don't have the time to hunt this down.

**Comment by desandro** [comment]
Closing as a duplicate of #123
