### ISSUE TITLE
How to get Flickity instance in event with multiple galleries

### ISSUE THREAD

**Issue by buck-danny** [metafizzy/flickity#222]
I have an index page and i load different single pages via ajax into the index page layout. Every single page has a flickity slider, I can control (prev/next) all slider individually but i have a problem with the captions. I only get the caption information from one slider and printed to every slideshow, but how can I get the right caption for each slider?

i have this to get the caption, it works but only for the first active slider, what to do?

``` js
$(document).ready( function() {
   var $gallery = $('.gallery').flickity({
    cellSelector: '.gallery-cell',
    imagesLoaded: true,
    percentPosition: false,
    wrapAround: true,
    pageDots: false,
    lazyLoad: true,
    lazyLoad: 2,
    imagesLoaded: true
  });
  
 
  var flkty = $gallery.data('flickity');
  $gallery.on( 'cellSelect' , function() {
  var element = flkty.selectedElement;
  var cap =  $(element).children().data('name');
  var $caption = $(element).parent().parent().parent().parent().find(".caption");
  $caption.text( cap )
  
  });
});

```

**Comment by desandro** [comment]
`var flkty = $gallery.data('flickity');` will return the Flickity instance of the first slider. Try this code to get the Flickity instance of the slider of the event

``` js
$gallery.on( 'cellSelect' , function() {
  var flkty = $(this).data('flickity');
  var element = flkty.selectedElement;
  // your code...
});
```

**Comment by buck-danny** [comment]
thanks a lot for your help!
outstanding!

**Comment by mikecarlyle** [comment]
Is there anyway to add a link to each caption?

**Comment by buck-danny** [comment]
by the way: this don't work for me for the first image/caption. Only after changing from the first to the second image the caption appears. How can I show the caption for the first image for the initial layout. Thanks alot!

maybe this helps for adding a link to the caption:
http://stackoverflow.com/questions/6216098/how-can-i-use-an-href-link-within-a-data-attribute-or-rewrite-it-with-jquery
