### ISSUE TITLE
UX: PageDots touchstart prevents native scrolling

### ISSUE THREAD

**Issue by jkempff** [metafizzy/flickity#223]
I have multiple Flickity instances with PageDots on a mobile optimized website. I use `Flickity PACKAGED v1.1.0`.

When the user just swipes down the page, he sometimes hits the `<ol>` that holds the pagedots. Since `PageDots` is a `TapListener`, this prevents the default native scrolling.
This looks like an error to the user, because the page won't scroll, if he starts swiping on that `<ol>`.

Bug confirmed on iOS Safari 8 and Chrome DevTools Mobile Emulation.

You can reproduce this, by visiting http://flickity.metafizzy.co/ with a mobile-like browser.

**Comment by desandro** [comment]
Thank you for reporting this bug! Indeed, this was an issue with `TapListener`. A fix has been added in TapListener v1.1.2 and will go out in the next release of Flickity :grin:

**Comment by desandro** [comment]
[Flickity v1.2.0 has been released](https://github.com/metafizzy/flickity/releases/tag/v1.2.0) with the Tap Listener fix. Get the latest at http://flickity.metafizzy.co

Closing as fixed! :whale:
