### ISSUE TITLE
Cycle through images rather than rewinding to the first image.

### ISSUE THREAD

**Issue by sabrina-hop** [metafizzy/flickity#228]
Is it possible to allow a cycle through of the images so that the last image automatically goes next onto the first rather than rewinding to the first. In this way, there would then always be two images on either side?

**Comment by desandro** [comment]
Yes! Set [`wrapAround: true`](http://flickity.metafizzy.co/options.html#wraparound). See demo with wrapAround and autoPlay http://codepen.io/desandro/pen/mebbJd
