### ISSUE TITLE
Overlay cell, small cells, space between cells and same height for each cell problem.

### ISSUE THREAD

**Issue by phongphan117** [metafizzy/flickity#229]
1. I don't know why gallery cells width that outside of screen is smaller than inside of screen after page loading.
![flickity-1](https://cloud.githubusercontent.com/assets/3041677/9538191/8e54bc90-4cf6-11e5-82c2-863a4c3e29c2.png)

2. I use `margin-right: 10px;` at `.gallery-cell` and `margin-right: 0px;` at .`gallery-cell:last-child` to adjust space between each gallery-cell. But when minimize or resize window I don't know why space between some gallery-cell is too wide.
![flickity-2](https://cloud.githubusercontent.com/assets/3041677/9538194/92de37d2-4cf6-11e5-9dd4-671e3a7a5e6a.png)

3. After maximize window, it seem gallery-cell was overlayed.
![flickity-3](https://cloud.githubusercontent.com/assets/3041677/9538201/9944ad36-4cf6-11e5-9b80-b8af0b97e8c8.png)

4. I want to make every gallery-cell same height with the height of the tallest cell.  So I set `setGallerySize: true`  and `height: 100%;` at `.gallery-cell` but it isn't work for me.
![flickity-4](https://cloud.githubusercontent.com/assets/3041677/9538202/9d8d2328-4cf6-11e5-8702-8678f1f609de.png)

jsFiddle: http://jsfiddle.net/phongphan117/sk5q7zLr/
Thank you in advance if someone can solve the problems.

**Comment by desandro** [comment]
Since `.gallery-cell` have no explicit width set, their size is determined by how they can 'fit' into the browser window. Cells that outside the viewport essentially have width of 0.

My recommendation is to set width. See demo http://jsfiddle.net/5uy643x3/

``` css
.gallery-cell { width: 300px; }
```

**Comment by awkale** [comment]
@desandro 
But what if the width of `.gallery-cell` if varied or you will not know the width?

**Comment by tyte** [comment]
I'm having a similar issue as the above. Some new thoughts about this?

**Comment by jimmyadaro** [comment]
Any updates on this issue?
