### ISSUE TITLE
Disable navigation on end of scrolling when multiple slides on screen

### ISSUE THREAD

**Issue by kud** [metafizzy/flickity#230]
I'm using flickity where it displays like 10 elements and there're 50 elements in the slider. The thing is when I arrive at element the 40th, the right arrow is still displayed even if there's nothing to slide anymore.

How could I easily display: none the right arrow? How can I know how many elements are displayed (because this slider is responsive, and the elements displayed could change)?

I need to count how many elements are displayed and where I am in the slider to disable the right arrow.

**Comment by desandro** [comment]
> the right arrow is still displayed even if there's nothing to slide anymore

Yes, but at this point, the cell on the left is selected and the user can still select cells to the right. This is a an accessibility feature — consider keyboard users.

While we could hack a solution, I think a better approach would be to add a slide group feature like #22. Currently it's a feature request, but it's got a lot of attention.

**Comment by kud** [comment]
Yep it's totally logic. But thank you for the #22. Sounds what I need indeed.

**Comment by kud** [comment]
Well in fact, not exactly. There they want to make a group step. In my case, I still want to move 1 by 1 but to disable the right arrow when there's nothing to slide more.

**Comment by zslabs** [comment]
@desandro Is there anyway we can get a simple `flicker-accessibility-arrows` class (or something like that) added to the slider wrapper when they may not be needed based on the number of elements so we can hide with CSS? http://codepen.io/zslabs/pen/BoQyRX That's my long-winded attempt to hide or show the arrows with a wrapper class of my own, but something built-in would be immensely helpful.

**Comment by desandro** [comment]
@zslabs Sorry, no.

I'm going to stick to my guns. Selecting cells is different from changing the cells in the carousel viewport. It's useful for accessibility and for other APIs. I hope to address this issue with #22.
