### ISSUE TITLE
Change settings at breakpoint

### ISSUE THREAD

**Issue by coreyworrell** [metafizzy/flickity#233]
It would be nice to do something similar to [slick](http://kenwheeler.github.io/slick) where you can define settings that only kick in at certain breakpoints.

For example, on a wide screen I would like to show multiple items and allow free scrolling, but on a smaller mobile device I would like to only show one item at a time and snap to each item. I see that the showing one at a time option is doable now by setting the width to 100%, but changing freeScroll is not possible currently (as far as I can tell).

Is there a simple way to handle this?

Thank you.

**Comment by desandro** [comment]
Thanks for this feature request. **+1 this issue** if you'd like to see this feature added.

I've tried to make Flickity as flexible as possible so that layouts are handled entirely with your CSS. There's also the [watchCSS](http://flickity.metafizzy.co/options.html#watchcss) option that allows you to enable or disable Flickity with breakpoints.

I'm not keen on adding this feature as its added complexity with small benefit. It requires mixing CSS logic with JS logic, which can be problematic. Many options, like freeScroll, assume you're only setting them at initialization. Changing options on the fly would require a large overhaul. That said, I'm always interested to see what developers are really wishing for.

**Comment by richgcook** [comment]
http://flickity.metafizzy.co/options.html#watchcss is just what I was after... being able to destroy/init the slider with your CSS/media queries is a game changer. Nice work, @desandro.

**Comment by piotrkulpinski** [comment]
+1

**Comment by amdad** [comment]
+1

**Comment by nonlinearcom** [comment]
+1

**Comment by michaelwoodruff** [comment]
+1 

The Owl Carousel has these options:
http://www.owlcarousel.owlgraphic.com/demos/responsive.html

**Comment by warreb1** [comment]
+1 indeed, I hoped to see the same like what Owl Carousel has. Before I've been using Owl Carousel in pretty much every project. Our team changed to Flickity because it was very promising. This feature however is key.

An alternative solution is to make two options. 1 would be mouseDraggable and the other would be touchDraggable. So we still have the touchdrag on mobile & tablets.

**Comment by addedlovely** [comment]
+1

**Comment by jeffpannone** [comment]
+1

**Comment by linnett** [comment]
+ 1

**Comment by KrielkipNL** [comment]
+1

**Comment by desandro** [comment]
You can set options according to media queries with [matchMedia](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Testing_media_queries). This will set the option on initialization, but not on resize. Some options are hard to re-set after initialization, like freeScroll, draggable, and cellAlign. But I think this solution will suit most of your requests. See demo http://codepen.io/desandro/pen/xVBpqG

``` js
// Flickity options, defaults
var options = {
  prevNextButtons: false
};

// enable prev/next buttons at 768px
if ( matchMedia('screen and (min-width: 768px)').matches ) {
  options.prevNextButtons = true;
}

// disable draggable at 1200px
if ( matchMedia('screen and (min-width: 1200px)').matches ) {
  options.draggable = false;
}

$('.gallery').flickity( options );
```

**Comment by desandro** [comment]
This demo is now linked in [Extra demos](http://flickity.metafizzy.co/extras.html#extra-demos)

**Comment by PortEdison** [comment]
Using vanilla js, I found this worked.
         `// force options to transition instantly
          featureFlkty.options.selectedAttraction = 1;
          featureFlkty.options.friction = 1;
          // select item
          featureFlkty.select(i);
          // reset defaults
          featureFlkty.options.selectedAttraction = 0.025;
          featureFlkty.options.friction = 0.28;`

**Comment by desandro** [comment]
@PortEdison You can select instantly with the [third parameter in select](http://flickity.metafizzy.co/api.html#select)

``` js
flkty.select( index, isWrapped, isInstant )
//
flkty.select( i, true, true )
```

**Comment by nChauhan91** [comment]
Can these options be somehow used on resize, I'm trying to implement few options without re-creating the slider on resize, i'm able to pass correct value to the plugin but it doesn't work while resizing.

Thanks

**Comment by daveybrown** [comment]
Heres a quick snippet of how I change the flickity options on resize. It's commented, and will need adapting, I dont have time at the moment to make a more generic example...

`// Returns a function, that, as long as it continues to be invoked, will not
// be triggered. The function will be called after it stops being called for
// N milliseconds. If `immediate` is passed, trigger the function on the
// leading edge, instead of the trailing.
function debounce(func, wait, immediate) {
    var timeout;
    return function () {
        var context = this, args = arguments;
        var later = function () {
            timeout = null;
            if (!immediate) {
                func.apply(context, args);
            }
        };
        var callNow = immediate && !timeout;
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
        if (callNow) {
            func.apply(context, args);
        }
    };
}

var latestMachines = debounce(function () {

    var $latestMachines = $('.latest-machines .product-cards>.row');

    // set flickity options - small first
    var latestMachinesOptions = {
        // options
        cellAlign: 'left',
        contain: true,
        prevNextButtons: false,
        pageDots: false,
        wrapAround: true,
        groupCells: 1
    };

    // group cells and align center for large
    if (matchMedia('screen and (min-width: 1000px)').matches) {
        latestMachinesOptions.groupCells = 2;
        latestMachinesOptions.cellAlign = 'center';
    }

    if ($latestMachines.hasClass('flickity-enabled')) {

        // get flickity data
        var flkty = $latestMachines.data('flickity');

        if (latestMachinesOptions.groupCells == flkty.options.groupCells || latestMachinesOptions.cellAlign == flkty.options.cellAlign) {
            // do nothing, flickity options are correct
            return false;
        } else {
            // flickity options are incorrect
            // destroy slider
            $latestMachines.flickity('destroy');
        }
    }
    // init (or re-init) flickity
    $latestMachines.flickity(latestMachinesOptions);

}, 250);

if ($('.latest-machines .product-cards>.row').length > 0) {

    latestMachines();
    window.addEventListener('resize', latestMachines);

}`

**Comment by jerome-toole** [comment]
The new `draggable: '>1'` option takes care of this if all you want to do is disable dragging. If you want to disable flickity based on slide count, then I found this solution to work well (using `watchCSS`):

https://github.com/metafizzy/flickity/issues/278#issuecomment-266070668

**Comment by saltcod** [comment]
Hey all. I didn't see this example out there, so I wanted to leave it here.

I want to instantiate flickity for small screens, then destroy it when we get up to large screens. I'm using enquirejs for the media query testing, but matchMedia would work too.  This might not be the right/best way to do this, but I think it does work. 

`import enquire from 'enquire-js';
import Flickity from 'flickity';

/**
 * Initialize flickity slider on mobile, destroy it when we go
 * back to desktop width
 */

const columnSlider = document.querySelector('.columns');

export default enquire.register('screen and ( max-width: 767px )', {
	match: () => {
		const flkty = new Flickity(columnSlider, {
			cellAlign: 'left',
			contain: true,
			pageDots: false
		});
	},
	unmatch: () => {
		const unflkty = new Flickity(columnSlider).destroy();
	}
});
`

**Comment by caseyjhol** [comment]
@desandro Why is this issue closed? As far as I can tell, it's still not possible to change options after initialization.

**Comment by tpinne** [comment]
The linked demo in this [comment](https://github.com/metafizzy/flickity/issues/233#issuecomment-221586880) only shows how to set options based on breakpoint on page load but not on page resize.

**Comment by mikespineu** [comment]
Why this issue is closed? Demos provided by desandro doesn't resolve problems with different settings for breakpoints for example "groupCells".

**Comment by saltcod** [comment]
Not directly solved with the plugin, but my solution works perfectly using enquire or just plain match media:

https://github.com/metafizzy/flickity/issues/233#issuecomment-388374039

**Comment by ali-hellani** [comment]
+1

**Comment by Julix91** [comment]
Another attempt at this:

```JavaScript
function toggleDraggableAtFlickityBreakpoint(mediaQuery, $carousels) {

	if(!mediaQuery || !$carousels) { return; }

	var dragToggles = function (match) {
		$carousels.forEach(function($carousel) {
			var flkty = $carousel.data('flickity');
			if(!flkty) { return; }

			if (match) {
				flkty.options.draggable = true;
			} else {
				flkty.options.draggable = false;
			}
			flkty.updateDraggable();
		});
	};

	var mql = window.matchMedia(mediaQuery);
	dragToggles(mql.matches);

	// listener
	mql.addListener(function(e){
		dragToggles(e.matches);
	});
}
toggleDraggableAtFlickityBreakpoint("(max-width: 768px)", [$carouselMain, $techSlider]);
```

**Comment by codefinite** [comment]
I've recently migrated from Slick and have been sorely missing this feature, I've come up with an idea to leverage the existing watchCSS so it can do more than just enable/disable Flickity, by adding the ability to trigger setting changes.  Here's an example of how it could work:

JS

```javascript
var flkty = new Flickity( elem, {
  watchCSS: true
  groupCells: 2,
  responsive: {
    small: {
      groupCells: 1
    }
  }
});
```

CSS

```css
/* enable Flickity default settings */
.carousel:after {
  content: 'flickity';
  display: none; /* hide :after */
}

@media screen and ( max-width: 480px ) {
  /* enable Flickity small settings */
  .carousel:after {
    content: 'flickity.small';
  }
}
```

You have a new setting, an object for storing your breakpoints, (in the example I've named it "responsive"), the property names become the identifiers for your breakpoint and you trigger them by appending the breakpoint identifier to the `.carousel:after` content. The breakpoints contain an object where you can override any of the existing Flickity settings.

This keeps the settings and styles separate, yet allows for triggering settings changes with any CSS media query.

**Comment by mintymatt** [comment]
Any update on this?

**Comment by bobbaker404** [comment]
For my purposes, I wanted to change the groupCells based on breakpoint. I'm sure this method can be used with changing other Flickity options as well.

My plan was to initi Flickity based on the current breakpoint (xs, sm, md, lg, xl, xxl). 1 groupCells for xs, sm & md; 2 groupCells for anything bigger. On resize, check the breakpoint & reset the number of groupCells. If the number of groupCells changed, destroy Flickity & re-init with the new groupCells count.

I found [this lovely article](https://gomakethings.com/the-easy-way-to-manage-css-breakpoints-in-javascript/) about setting breakpoints in CSS & using them within Javascript, so I gave it a try and I'm quite happy with the results.

Here's my code:
`// Flickity set-up
    var flkty;
    var elem = document.querySelector('.testimonial-carousel');
    var groupCells;

    // Set-up the breakpoint variable
    var breakpoint;

    // Get the current breakpoint
    var getBreakpoint = function () {
      return window.getComputedStyle(document.body, ':before').content.replace(/"/g, '');
    };

    // Set the number of groupCells based on breakpoint
    var setCells = function () {
      if (breakpoint === 'xs' || breakpoint === 'sm' || breakpoint === 'md') {
        return 1;
      } else {
        return 2;
      }
    };

    // Calculate breakpoint on page load
    breakpoint = getBreakpoint();
    groupCells = setCells();
    // console.log(groupCells);
    do_flickity();

    // Setup a timer
    var timeout;

    // Recalculate breakpoint on resize
    window.addEventListener('resize', function () {
      if (timeout) {
        window.cancelAnimationFrame(timeout);
      }
      timeout = window.requestAnimationFrame(function () {

        // Get the groupCells value from before resize
        var prevGroupCells = groupCells;

        // Get the new current breakpoint
        breakpoint = getBreakpoint();

        // Get the new groupCells value
        groupCells = setCells();

        // If new groupCells count is different from previous. DESTROY Flickity & init new Flickity
        // console.log(groupCells + ' | ' + prevGroupCells);
        if( groupCells !== prevGroupCells ){
          flkty.destroy();
          do_flickity();
        }

      });
    }, false);

    // init Flickity
    function do_flickity() {
      flkty = new Flickity( elem, {
        groupCells: groupCells,
        prevNextButtons: false,
      });
    }`

**Comment by Hlsgs** [comment]
@desandro 
This is my and many others' deal braker when it comes to migrating to Flickity.

**Comment by fbnntt** [comment]
Already use Flickity on most of my projects but would be great to have the options working per breakpoint on window resize rather than only intialized — in particular, the `groupCells` option.

**Comment by zzseba78** [comment]
Any news on this?

**Comment by kazunorimiura** [comment]
+1

**Comment by obliviga** [comment]
+1

**Comment by umkasanki** [comment]
+8908765 !!!

**Comment by nikkster311** [comment]
What about this? https://flickity.metafizzy.co/options.html
![image](https://user-images.githubusercontent.com/26155010/108575586-9f385d00-72cf-11eb-93de-eae889176e6b.png)

**Comment by TomSinclair** [comment]
Any update on bringing this functionality to Flickity?

**Comment by phucbm** [comment]
Hi guys,

I've been using Flickity for a while and have had an urge for this responsive option, so I created a jQuery plugin to handle this and am quite happy with the result, here is how I control responsive with the extra plugin

```
// Init Flickity
$carousel.flickityResponsive({
    cellAlign: "left",
    contain: true,
    freeScroll: true,
    responsive: [
        {
            breakpoint: 1024,
            settings: {
                wrapAround: true,
                cellAlign: "center",
                freeScroll: false,
                prevNextButtons: false,
                pageDots: false
            }
        }
    ]
});
```
The plugin will decide when to destroy and re-initialize the carousel to apply new options using `matchMedia()`. You might notice that the usage was inspired by Slick.
I published the code at my repository for maintenance purposes 👉 https://github.com/phucbm/flickity-responsive
There's also a CodePen for it 👉 https://codepen.io/phucbui/pen/ExmJVZa

**Comment by davemac** [comment]
Thankyou @phucbm this is just what I was looking for. It seems to be a very common requirement that  `groupCells` should change on different screen sizes - would be great to see this added to Flickity.

**Comment by obliviga** [comment]
+1

**Comment by kevin-vo** [comment]
+1

**Comment by fozdemir40** [comment]
Works amazing @phucbm thank you!

**Comment by dijkermans** [comment]
+1

**Comment by hiphopappotamus** [comment]
+1

**Comment by joebentaylor1995** [comment]
Such a shocking and disappointing  decision to make this an extra - rather than integrated into the slider... glad i went to SwiperJS

**Comment by scheylon** [comment]
Still no breakpoint feature ?

**Comment by phucbm** [comment]
Looks like @desandro might have missed the memo on this one! 😅 After several years of development, my Flickity wrapper has finally made its mark with 2 million hits per month. If you’re craving responsive settings for your carousel, feel free to give it a whirl here!

https://github.com/phucbm/flickity-responsive

**Comment by magnusdalkvist** [comment]
+1
