### ISSUE TITLE
Problem with 'destroy' and re-initializing and Unidragger error

### ISSUE THREAD

**Issue by chrisforrette** [metafizzy/flickity#235]
I have a case where I'm showing and hiding a sort of paginated menu and using Flickity to make it swipeable from left to right. So when the menu slides in, I initialize with the following:

```js
$('.wrapper').flickity({
      cellSelector: '._pane',
      contain: true,
      draggable: true,
      pageDots: false,
      prevNextButtons: false,
      setGallerySize: false
});
```

...and it works fine, except that when I drag, I get this error in the console: `Unidragger.getScrollPosition is not a function`.

Another issue is that when the menu is hidden, I call:

```js
$('.wrapper').flickity('destroy');
```

...and then when its shown again, I run the initialize call above again and it doesn't work. At this point when I look at the DOM, I see my `._pane` elements with modified `left` properties, but they aren't nested in the `flickity-viewport`/`flickity-slider` elements and the `flickity-enabled` class isn't there. If I follow up my `destroy` call with a `$('.wrapper').removeData('flickity');` call it seems to work OK—is that the intended behavior?

Please let me know if there's a better way I should be doing something like this or if there's any other helpful information I can provide. I'm using the latest version, 1.1.1.

Thanks!

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Flickity. Can you check that you are using Flickity and all of its dependencies? For example, you're jusing flickity.pkgd.js and not just flickity.js, if you're including Flickity as a `<script>`.  Better yet provide a **reduced test case**. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by chrisforrette** [comment]
@desandro Thanks for the response!

I'm using Flickity via Browserify, so just a `import Flickity from 'flickity';`—is there more to it than that?

**Comment by desandro** [comment]
See docs on using [Flickity with Browserify](http://flickity.metafizzy.co/extras.html#browserify). If you can provide a live URL demonstrating the issue, I could possibly debug it.
