### ISSUE TITLE
Disable navigation on end of scrolling when multiple slides on screen.

### ISSUE THREAD

**Issue by tomtev** [metafizzy/flickity#236]
Hi there,

Is it possible to disable the navigation when there is no more slides to scoll?
This works perfect if there is only 1 slide, but it is a bit confusing if you are scrolling multiple slides at once and reach a end point. You can still click, but the scrolling has stopped.

Here is an example: http://recordit.co/AYD5maq5X1

Maybe there should be some options like these: slidesToShow: 4, slidesToScroll: 4

**Comment by desandro** [comment]
Thanks for reporting this issue. We already have an issue open for this. See https://github.com/metafizzy/flickity/issues/230#issuecomment-137125683
