### ISSUE TITLE
Before / After slide callbacks with promises

### ISSUE THREAD

**Issue by Ahrengot** [metafizzy/flickity#237]
Hey Desandro,

I'm trying to figure out a way to have the slider do some kind of animation before it slides to the next image. I imagine having to modify the slider itself to achieve this, and that is completely fine, but if you could point me in the right direction I would really appreciate it.

I imagine setting up beforeSlide/afterSlide callbacks that would look something like this:

```javascript
var flkty = new Flickity('.main-gallery', {
	beforeSlide: function(done) {
		dosomethingAsync.then(done);
	},
	afterSlide: function(done) {
		dosomethingAsync.then(done);
	}
});
```

Is this a pipe dream? if not, which methods in flickity should I be modifying and is there anything I should watch out for as I modify the code?

Really appreciate any help here :)

**Comment by desandro** [comment]
Thanks for this feature request. Have you looked at using [Flickity's events](http://flickity.metafizzy.co/api.html#events)?

> have the slider do some kind of animation before it slides to the next image.

I'd be careful with this approach. One of Flickity's best features is how easy it is to drag and flick it. Users may not be using the previous & next buttons.
