### ISSUE TITLE
Selecting cells based on ID

### ISSUE THREAD

**Issue by mikeebee** [metafizzy/flickity#239]
Hi,

I have a Flickity carousel as the navigation to a SVG map. The idea being that if you click on a carousel item, it focusses on the corresponding map region. Also, if you click on a map region it highlights the corresponding carousel item.

I have this working great, it uses id's of the cells and ID's of the map regions (which are matching and I am outputting as a console log when a map region is clicked).

What I would like is for the **carousel to move and centre on the carousel item that corresponds to the map region that was clicked**.

I see no way of doing this using the [select method](http://flickity.metafizzy.co/api.html#select) as I don't have an index available on the map regions from what I can see.

Here is a pen of what I have so far. http://codepen.io/anon/pen/garPVR

Any ideas?

**Comment by desandro** [comment]
Thank you for this feature request. **+1 this issue** if you would like to see Flickity support selecting cells via `#id`.
