### ISSUE TITLE
allow alternative re-layout method / disable resize listener

### ISSUE THREAD

**Issue by lunelson** [metafizzy/flickity#24]
I guess flickity is tracking a debounced window.resize() event to know when to re-layout itself—probably the ideal for nearly every scenario but it could be useful to disable this and be able to trigger it manually, e.g. if tracking a custom 're-layout' event on media-query changes. What do you think?

**Comment by lunelson** [comment]
I just realized of course I can disable it; so the question is just whether I can trigger it manually

**Comment by desandro** [comment]
You can disable resizing logic by setting `resizeBound: false`.

Yes, you can trigger resize logic manually with the `resize` method.

``` js
// jQuery
$gallery.flickity('resize')
// vanilla JS
flkty.resize()
```

This will be added to the docs.

**Comment by desandro** [comment]
Docs on [`resize` option](http://flickity.metafizzy.co/options.html#resize) and [`resize` method](http://flickity.metafizzy.co/api.html#resize) added. Closing as resolved :white_check_mark:
