### ISSUE TITLE
JS Click events inside slides opens when relasing dragging.

### ISSUE THREAD

**Issue by tomtev** [metafizzy/flickity#240]
Is is possible to disable JS Click events when dragging? I have some images in a slider that opens in a lightbox if they are clicked, but now it opens when dragging is finished.

Example: http://recordit.co/Obs1ns9Aij

**Comment by desandro** [comment]
Yes, it is possible. But a better solution would be to disable the lightbox click behavior, and re-implement it with Flickity's [`staticClick` event](http://flickity.metafizzy.co/api.html#staticclick)

**Comment by tomtev** [comment]
I solved it by adding:

$('.ux-slider').on( 'dragStart', function( ) {
  $(this).addClass('is-dragging');
});

$('.ux-slider').on( 'dragEnd', function(  ) {
  $(this).removeClass('is-dragging');
});

And pointer-events:none to .is-dragging

**Comment by andrewjmead** [comment]
Thanks so much for this @tomtev!

**Comment by TorchSK** [comment]
Any idea how to implement his also on mobile?

**Comment by RadGH** [comment]
I think it is absurd that this is still a problem in Flickity. The staticClick event is great if you are binding the click event yourself, but doesn't work with lightbox libraries etc.

Here is an improvement to Tomtev's answer which uses the proper `dragStart.flickity` and `dragStop.flickity` events. It also has a delay to ignore clicks until the slider "settles down". This uses jQuery.

```var $gallery = jQuery(this);
var opts = {
		wrapAround: true,
		cellAlign: 'center',
		container: true,
		imagesLoaded: true,
		lazyLoad: 5
	};

new Flickity( $gallery[0], opts );

// After dragging, ignore clicks for this many milliseconds.
var dragIgnoreClickDelay = 75;
var dragTimeout = false;
var dragging = false;

$gallery
	.on('dragStart.flickity', function() {
		dragging = true;
		if ( dragTimeout !== false ) clearTimeout(dragTimeout); 
	})
	.on('dragEnd.flickity', function() {
		dragTimeout = setTimeout(
			function() { 					
				dragging = false;
				dragTimeout = false;
			}, 
			dragIgnoreClickDelay
		);
	})
	.on( 'click', 'a', function() {
		if ( dragging ) return false;
	});
```
