### ISSUE TITLE
Cells affected by Chrome bug that incorrectly positions fixed width content on window resize

### ISSUE THREAD

**Issue by timswalling** [metafizzy/flickity#241]
[I have reported a bug in Chrome](https://code.google.com/p/chromium/issues/detail?id=533277) that causes fixed width content to be incorrectly positioned after window resize when it had ancestor elements with transform and left/right properties that counteract each other.

Although this is a problem with Chrome, Flickity is affected because it uses the combination of negative translateX transform (on the .flickity-slider element) and left (on its children) to position the cells. There is an easy fix, which is to add any transform value to the slider's children.

I have created a [reduced test case in CodePen](http://codepen.io/timswalling/pen/VvjmKa). You'll note that when you resize the window, all of the slider cells with the heading "works as expected" work as expected (surprise!), but the fixed width content of the cell with the heading "doesn't work as expected" moves to the right as the window width is decreased, and the to the left and the window width is increased.

**Comment by desandro** [comment]
Thanks for reporting this related browser issue. Looks like this issue was resolved in Chromium on Sep 30, 2015. I'm closing this ticket here :whale:
