### ISSUE TITLE
Support initialization with pre-existing viewport and slider elements

### ISSUE THREAD

**Issue by EntropyAu** [metafizzy/flickity#242]
Hi - awesome library! I'm evaluating it for a project it could be suitable for, and it looks like the only hurdle at the moment is working in combination with knockout.js . The knockout bindings on the individual items are lost when the viewport and slider div elements are created, and each item is moved underneath them. Would it be possible to allow for these container elements to be manually created thus preserving bindings?

**Comment by desandro** [comment]
Thanks for submitting this issue. If DOM is changed with Knockout.js (or other framework), you can use [`reloadCells`](http://flickity.metafizzy.co/api.html#reloadcells) to reload the elements for the Flickity instance. If the entire carousel element is changed, you might as well initialize a new Flickity instance.

**Comment by EntropyAu** [comment]
Thanks @desandro, that's the way I've wired it up, however the issue is that Flickity, when initializing, moves the DOM elements for the items. This breaks the knockout bindings (the item elements are no longer where Knockout is looking for them).

Ideally I'm hoping we can avoid Flickity moving the elements in the DOM by setting up the expected DOM hierarchy (eg. <div class="flickity-viewport"><div class="flickity-slider"><item/><item/>...</div></div>) in advance of initializing Flickity - this would greatly simplify integration with knockout which doesn't play well with nodes being moved in the DOM tree.

**Comment by desandro** [comment]
Ah, thanks for clarifying. Could you initialize Flickity first before Knockout?

**Comment by EntropyAu** [comment]
I think that could work in theory, but it would make it complex to use Flickity as part of Knockout bindings (therefore use in templates, show/hide on demand etc). The idiomatic approach is to bind the entire page, then use knockout custom bindings to instantiate widgets / custom javascript behaviours (such as Flickity).

One approach (without Flickity changes) would be a custom Knockout binding that instantiates Flickity and then creates it's own binding context within the Flickity-created &lt;div class="slider> element - but this could prevent items from accessing the parent binding context (limiting).

Really awesome library btw - it just 'feels' right.

**Comment by desandro** [comment]
After four months, no one has chimed in with Knockout issues. I'm closing this issue to clean up the tracker, but it shall not be forgotten. Thanks again for reporting it!
