### ISSUE TITLE
Sizing issue

### ISSUE THREAD

**Issue by Kaorinite** [metafizzy/flickity#243]
Hello!
I have trouble with sizing a fluid responsive flickity image gallery. I've been trying to make the height of the gallery much smaller than it is now, about half the size. But when I resize the style of the height, the images become distorted as I change the size of the window... 
Could you, please, point out, if there's something wrong with the styles for the gallery?
Here's my example page: http://rusrecipes.ru/test3/index.html
The css file: http://rusrecipes.ru/test3/css/style.css

Best regards,
Kaori

**Comment by desandro** [comment]
See possible solution at https://github.com/metafizzy/flickity/issues/219#issuecomment-133063005

**Comment by Kaorinite** [comment]
Hello!

I've tried it, but for some reson the images disappear... And I don't quite understand how to use several background images. Tried that too...

He's an example: http://rusrecipes.ru/test3/index.html

Css:
.gallery-cell {
  width: 100%;
  height: 100%;
  margin-right: 10px;
  background-image: url (pics/6.jpg);
}

.main-gallery img {
  display: block;
  max-width: 100%;
  height: 100%;
}

Best regards,
Kaori

**Comment by desandro** [comment]
I recommend adding `$(document).ready` to your JS

``` js
$(document).ready( function() {
  $('.main-gallery').flickity({
    // options
    cellAlign: 'left',
    contain: true,
    wrapAround: true,
    imagesLoaded: true,
    autoPlay: true,
    setGallerySize: false,
  });
});
```

**Comment by Kaorinite** [comment]
Thanks! I've added this, but it still doesn't work... :( Hmm...

**Comment by desandro** [comment]
Sorry, but I won't be able to debug this issue.
