### ISSUE TITLE
Count Issue (Previous/Next button)

### ISSUE THREAD

**Issue by zslabs** [metafizzy/flickity#244]
Hi,
I'm noticing a count/overflow issue with Flickity. If you look at http://codepen.io/zslabs/pen/MaeQRM you'll notice that there are 4 items; all of which appear within the scope of current viewport, no overflow needed. The previous button is correctly disabled, but the next button appears as active, even though the slider doesn't move and there is nothing to shift.

I'd also like to see a wrapper class added to Flickity, something like "disabled-navigation" if both elements are disabled from that count.

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue. See discussion at https://github.com/metafizzy/flickity/issues/230#issuecomment-137125683
