### ISSUE TITLE
Two images are scrolled at once under webkit 534.30 

### ISSUE THREAD

**Issue by nonmanifold** [metafizzy/flickity#246]
I fixed it by throttling selection function which gets called when taping on arrows:
```
 Flickity.prototype.select = throttle(Flickity.prototype.select, 450);
```

Touch events handling is probably contains bug somewhere in webkit, or in unidragger/tap-listener

**Comment by desandro** [comment]
Thanks for reporting this issue. This sounds very similar to #123. Can you check that you are using Flickity v1.1.1? Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
