### ISSUE TITLE
Decouple swiping and dragging

### ISSUE THREAD

**Issue by IanLunn** [metafizzy/flickity#247]
Is it possible to separate swiping from dragging? I'd like to disable dragging but still be able to navigate between cells via swiping. Swiping once would trigger the next callback instead of phyics based functionality.

**Comment by desandro** [comment]
Thanks for this feature request. I'm not a fan of using swipe gestures without moving content. Moving content while swiping provides immediate feedback of the users interaction. Otherwise, it's a hidden gesture. Sorry, but I'll have to say no to this one.

**Comment by IanLunn** [comment]
No problem, thought as much. Thanks for quick response.
