### ISSUE TITLE
Flickity Window Size Reload Cell Width Incorrect

### ISSUE THREAD

**Issue by tdorr07** [metafizzy/flickity#248]
I'm using flickity to sort through staff members on a website in combination with a drop down selector to make various flickity galleries viewable.

The filter system works great on a fresh load of the site, without resizing the window. 

If you resize the window and then select a different department, the width of the cells does not respond correctly and overlaps. If you choose a new department, see the overlap, and then slighlty adjust the width of the browser, everything works fine.

Anyone have a solution to this issue? Thanks for the help!

http://wstar.wpengine.com. The flickity slider is found at the bottom of the homepage.

This is the flickity initialize:

```
jQuery(document).ready(function(){

jQuery('.gallery').flickity({
  // options
  cellAlign: 'left',
  freeScroll: true,
  pageDots: false,
  wrapAround: true,
  
});

});
```
On the page I have the following script for hiding and viewing different galleries:

```
jQuery(document).ready(function($){
		
		$('div.projects').hide();
		$('div.projects.all').show();
							
		$('#faculty-filter li').on('click', function(){
		    $('div.projects').hide();
		    
		    if($(this).hasClass('all')) {
		      $('div.projects.all').show();
		      
		      var categoryId = $(this).data('category');
		      var $gallery = $('.gallery').flickity();
		      
		      $('div.projects div.cat-'+ categoryId).hide();
		      $("#faculty-filter").slideToggle();
		      $("#menu-icon").toggleClass('active');
		      
		    } else {
			    
		      var categoryId = $(this).data('category');
		      $('div.cat-'+ categoryId).show();
		      $("#faculty-filter").slideToggle();
		      $("#menu-icon").toggleClass('active');
		      
		    }
		  });
		  
		

			$('#faculty-filter li').click(function(){
			    $("#menu-icon").text($(this).text());
			  });


	  
	  });
```

**Comment by desandro** [comment]
After hiding or showing cells, trigger [`reposition`](http://flickity.metafizzy.co/api.html#reposition) so cells are properly positioned.

``` js
var $gallery = $('.gallery');

$('#faculty-filter li').on('click', function(){
  $('div.projects').hide();

  if($(this).hasClass('all')) {
    $('div.projects.all').show();
    var categoryId = $(this).data('category');
    $('div.projects div.cat-'+ categoryId).hide();
    $("#faculty-filter").slideToggle();
    $("#menu-icon").toggleClass('active');
  } else {
    var categoryId = $(this).data('category');
    $('div.cat-'+ categoryId).show();
    $("#faculty-filter").slideToggle();
    $("#menu-icon").toggleClass('active');
  }

  $gallery.flickity('reposition')
});
```

**Comment by tdorr07** [comment]
Thanks for the response Desandro. I tried inserting the code provided, but it now collapses all items on top of each other when you switch filters after resizing the browser window to any width. Still fixes itself if you slightly adjust the browser width after viewing the broken slider.

**Comment by tdorr07** [comment]
Actually think I got it working now.

Replacing 

    $gallery.flickity('reposition')

with

    $gallery.flickity('resize');

appeared to do the trick.
