### ISSUE TITLE
repsonsive breakpoint example: 3 cards on desktop, 2 for tablet, 1 for mobile

### ISSUE THREAD

**Issue by gebrits** [metafizzy/flickity#249]
Interested in this perhaps commercially but missing example for critical feature: to be able to have flexible widths with breakpoints, e.g.: 

* show 1 card at a time, e.g.: `width: 100%` on mobile
* show 2 cards at a time, e.g.: `width: 50% - 1x gutter` on 600px and above
* show 3 cards at a time, e.g.:  `width: 33% - 2x gutter` on 1000px and above. 

Is this possible? Any examples to see how this works?

**Comment by desandro** [comment]
Thanks for getting in touch. Have you taken a look at the [Flickity Style demos](http://flickity.metafizzy.co/style.html). See also the [Flickity with media queries demo on CodePen](http://codepen.io/desandro/pen/azqbGV)
