### ISSUE TITLE
How are images being height-adjusted and centred?

### ISSUE THREAD

**Issue by lunelson** [metafizzy/flickity#25]
Looking at the project page, there seems to be more going on with the image carousel than what's listed... it's adjusting itself and all the images to specific heights—depending on a media query—seems like either `160px` or `400px` for `height`. How is this being specified?

I was going to request some kind of `max-height` / `max-width` logic for images anyway: allowing absolute or relative units (?), so one could specify for example that the carousel be no more than some number of `rem`s high and each image no wider than `80%` of the width of the carousel, or no wider than `20em`, or conform `height` to the shortest image, etc..

What do you think?

**Comment by desandro** [comment]
I've added CodePens for both image carousels: 

http://codepen.io/desandro/pen/GgQREP
http://codepen.io/desandro/pen/MYQWEe

Additionally, the [Flickity • Style](http://flickity.metafizzy.co/style.html) page has more details what CSS is used.

**Comment by lunelson** [comment]
Thanks for those demos, it seems pretty clear now. I notice that defining image height in something other than pixels gives mixed results: `rem` seems not to work at all, nor `vw`; but `vh` does seem to work

**Comment by desandro** [comment]
I was able to use these units for image height with no problems.

+ Using `rem`: http://codepen.io/desandro/pen/VYBjBm
+ Using `vh`: http://codepen.io/desandro/pen/JoBKaY
+ Using `vw`: http://codepen.io/desandro/pen/MYBezR

**Comment by lunelson** [comment]
Great. Sorry, I must have just been overlooking something else. Thanks for doing those.
