### ISSUE TITLE
Hide next (and/or previous) gallery item "off screen" (don't show)

### ISSUE THREAD

**Issue by mattkaz** [metafizzy/flickity#250]
I'm wondering how I can hide the next gallery item in the carousel, instead of having it bump right up next to the current, active gallery item. I have images that I need to set to a certain height (300px), but they have different widths then when explicitly setting their height like that... and almost never go the full width of the gallery wrapper. So I want to only show the current active item/image, and hide the next (and/or previous) image off the screen, until the next or previous navigational arrows are clicked to make that next or previous item active.

I've tried adjusting width of gallery-item, tried adjusting padding and margin gallery-item and the images itself, and no luck. I've searched and searched your site, message boards, etc... and no luck there either. So any help you could give would be greatly appreciated :)

Thanks much!! Love it otherwise :)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

Have you tried using CSS with `.is-selected` ? See http://flickity.metafizzy.co/style.html#selected-cell and fun demo http://codepen.io/desandro/pen/jEpxqJ/
