### ISSUE TITLE
Touch down scroll problem

### ISSUE THREAD

**Issue by yemrecetin** [metafizzy/flickity#252]
Hi, we use flickity extention for the purpose of "slide touch tab". 
However our problem is;
When we scrool down the page, if our finger cross slightly to the left of the right side of the screen, the existing page slides to another tab.

Would you help us to solve this issue?

http://i.imgur.com/5HJpHeN.png (the red arrow on the image shows how the page slides)

**Comment by desandro** [comment]
See adjusting vertical scroll sensitivity in https://github.com/metafizzy/flickity/issues/138#issuecomment-110059643

**Comment by yemrecetin** [comment]
thank you @desandro :)
