### ISSUE TITLE
Can't touch after touch, scroll on mobile

### ISSUE THREAD

**Issue by mdmoreau** [metafizzy/flickity#257]
http://codepen.io/mdmoreau/pen/GpWGXK

I've noticed an odd issue on all versions of Chrome with touch scrolling (mobile, desktop emulation).  If you start page scrolling vertically by touching the Flickity element and then stop, you won't be able to swipe that element on the next attempt.  It seems like after starting a touch scroll on Flickity you then have to either swipe twice or tap and then swipe for it to work.  Is it intended to work that way?

**Comment by mdmoreau** [comment]
Looks like this might be caused by the `is-pointer-down` class not being removed from the container after the touch page scroll is finished

**Comment by desandro** [comment]
Thanks for reporting this bug. I'll have to take a look.

**Comment by Isodie** [comment]
same problem for me too @mdmoreau

**Comment by aghouseh** [comment]
Yeah, I'm seeing this issue as well as the previous `staticClick` bug still existing on iOS/Chrome. If you view the [Fliciktiy API Events Demo](http://flickity.metafizzy.co/api.html#events-demo), the issue is still visible there as well.

**Comment by tafkanator** [comment]
any update on this issue?
problem exists in crosswalk also. triggering layout seems to help as a workaround

slider.on('dragEnd', () => slider.classList.add('is-moving'));
slider.on('settle', () => slider.classList.remove('is-moving'));

window.setTimeout(() => slider.classList.add('is-moving'), 500);
window.setTimeout(() => slider.classList.remove('is-moving'), 1000);

.is-moving&:before {
	position: absolute;
	content: "";
}

tried this, and it seems to help but not nice solution

**Comment by kallaspriit** [comment]
Experiencing same issue.

**Comment by mikebikeboy** [comment]
Also experiencing here.

**Comment by peduarte** [comment]
I was having the same issue, and adding `will-change: transform` to `.flickity-slider` solved my problem. 
This is basically telling the browsers, expect this element to change, by adding this property the browser will prioritise the rendering of this element and move it onto the GPU

**Comment by mdmoreau** [comment]
Gave `will-change: transform` a shot, but I haven't noticed any difference.

**Comment by peduarte** [comment]
@mdmoreau hmm weird, worked here :/

**Comment by mmacartney10** [comment]
I am getting the same issue, it doesn't seem to be removing the 'is-pointer-down' class like @mdmoreau said. I'm getting this issue on iPhone (iOS 8)

**Comment by mdmoreau** [comment]
It's odd - the bug hasn't ever been something that happens 100% of the time for me.  Sometimes when scrolling vertically I'll notice that the slider does a slight twitch horizontally.  After those instances I'll be able to slide it on the next attempt once scrolling finishes.  I haven't been able to reliably reproduce that touch interaction to sort out what might be the issue though.

**Comment by peduarte** [comment]
I never had the issue where the `is-pointer-down` not being removed. Mine was simply a hardware acceleration issue. 

If that class is not being removed, I'd make sure you are using the latest version of the library.

**Comment by mmacartney10** [comment]
I am using the latest version of the library and it doesn't seem to happen 100% of the time as well.

**Comment by JordanDoczy** [comment]
I may have found a solution, I simply changed the following: 

Flickity.prototype.hasDragStarted = function( moveVector ) {
  return !this.isTouchScrolling && Math.abs( moveVector.x ) > 3;
};

to 

Flickity.prototype.hasDragStarted = function( moveVector ) {
  return Math.abs( moveVector.x ) > 3;
};

**Comment by OACDesigns** [comment]
encountered this issue as well. Debugged it extensively and came up with a quick solution (though the bug lies much deeper).
It appears that after you touch down on the page and then scroll vertically, if the element containing flickity is scrolled (in my case `body`) flickity would no longer fire a `pointerUp` event when you let go. As a result the `isTouchScrolling` attribute is never reset so the next time you touch down flickity thinks you are still scrolling and disables dragging. Only after a successful `touchend` event is fired will scrolling start working again.
It looks like scrolling the parent interrupts the event handlers (maybe they're getting de-registered early or not bound at all?).

My solution was to overload the `ontouchstart()` function and reset the state of `this.isTouchScrolling` and `this.isDragging`.  Below is my code.




    /**
     * overload touchstart handler to add our own state reset function (see below)
     */
    Flickity.prototype.ontouchstart = function( event ) {
        this.resetStates();
        this._pointerDown( event, event.changedTouches[0] );
    };

    /**
     * custom function to manually fix a bug related to page scrolling interrupting flickity's normal event handling
     * and resulting in isDragging and isTouchScrolling states not getting reset (should happen in pointerUp() function)
     */
    Flickity.prototype.resetStates = function() {
        delete this.isTouchScrolling; 
        this.isDragging = false;
    }

**Comment by SinoBoeckmann** [comment]
Any news here?
The issue still exists. Any of the "problem-solving" cases above are not working. :(

**Comment by peduarte** [comment]
Yep, this is the worst part of maintaing a library, but the longer you wait, the worst it gets. :(

**Comment by SinoBoeckmann** [comment]
The problem is, that I'm just investigating it on the simulator/ device not in the browser. Sometimes I can scroll for seconds, sometimes it breaks at the first scroll.
The only thing I can more or less confirm is, that in case you're scrolling and at the same time do a double click/ tap it breaks more often.

Maybe it helps: I'm having the problem with freeScroll true and false. When it is set to false it happens less often and less fast.

I understand the problem on how hard it is to fix the problem. I would help but 6000 Lines are hard to get in quite fast.

**Comment by biesbjerg** [comment]
Same issue here.

JordanDoczy's workaround did it for me though. I just added this after loading the flickity javascript file:

```js
 	// Fix for pointerUp event not being fired when scrolling vertically
 	// See: https://github.com/metafizzy/flickity/issues/257
	Flickity.prototype.hasDragStarted = function( moveVector ) {
		return Math.abs( moveVector.x ) > 3;
	};
```

**Comment by desandro** [comment]
This bug has been fixed in [Flickity v1.2.0](https://github.com/metafizzy/flickity/releases/tag/v1.2.0). Get the latest version at http://flickity.metafizzy.co . Thanks so much for your input here, glad to have this one solved.

**Comment by mdmoreau** [comment]
Looks good from what I just tested - thanks!

**Comment by peduarte** [comment]
@desandro nice one man

**Comment by SinoBoeckmann** [comment]
Looks good so far. Tested it with a bunch of data (200+) on the iPhone Simulator (iPhone 5, iOS 9.2) and works well and the more important thing: as expected! :) Thanks for this mate @desandro
