### ISSUE TITLE
Slide progress

### ISSUE THREAD

**Issue by nicholas-c** [metafizzy/flickity#258]
Hey! So I've got a slider which has controls and a "Progress bar" that outputs the progress of a slider.

This would be possible if there was an event that triggered however there is not, I'm "close with the following...
    $(event.target).find('.is-selected').offset().left

That returns on the dragMove event however that stops reporting on mouseup... 

Ideas?

**Comment by desandro** [comment]
Fun idea! There's no event, but you can do this by duck punching `positionSlider`. See the [Flickity slide progress bar demo on CodePen](http://codepen.io/desandro/pen/obpVGa/)

``` js
// duck punch
var _positionSlider = flkty.positionSlider;
flkty.positionSlider = function() {
  _positionSlider.apply( flkty, arguments );

  var firstCell = flkty.cells[0];
  var cellsWidth = flkty.getLastCell().target - firstCell.target;
  var progress = ( -flkty.x + -firstCell.target ) / cellsWidth;
  progress = Math.max( 0, Math.min( 1, progress ) );
  progressBar.style.width = progress * 100 + '%';
}
```
