### ISSUE TITLE
Unwanted scrollbars

### ISSUE THREAD

**Issue by sjelfull** [metafizzy/flickity#259]
This is probably something I've done wrong, but I can't figure out why i'm getting unwanted scrollbars every time I hover over / try to move the slideshow with my mouse on this page: http://kaos-4.myshopify.com/

Any obvious answers that you can clue me in on?

**Comment by desandro** [comment]
I'm not able to reproduce the scrollbars. Can you try putting together a **reduced test case**. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by sjelfull** [comment]
Aha, had a closer look at it, and it was the Pinterest Chrome plugin and the insertion of a "Pin it" button that caused it.

**Comment by matyushen** [comment]
This is an old issue but still relevant. Did anybody come up with a reliable solution? Chrome extension seems to just add 2 spans to the body without any class names. So I can only suggest this as a quick fix:
```
body > span {
  display: none !important;
}
```
But I wonder if there's a better solution.
