### ISSUE TITLE
Option to disable or modify behavior of scrolling galleries into the viewport

### ISSUE THREAD

**Issue by luksak** [metafizzy/flickity#266]
I have a site where I have a sticky header using [Headroom.js] (http://wicky.nillia.ms/headroom.js/). When changing the slide of a flickity gallery on for the first time and the gallery is not completely in the viewport, flickity scrolls up to have the gallery completely in the viewport. In my case this activates Headroom.js to display the header and covers the gallery again. The same bug also exists if the header was positioned: fixed. This is only the case on non-touch devices.

It would be nice to completely disable this behavior since in my case this feature is quite annoying.

Also nice would be a callback where I could alter the position flickity is going to scroll to and add the height of the header.

I created a reduced test case scroll until the gallery is almost not visible anymore an the click on a dot in the pager: http://codepen.io/luksak/full/bVrrRr

**Comment by desandro** [comment]
Hi there! Thanks for reporting this issue and for providing a :star: reduced test case :star2:. The issue you mention is related to the `accessibility` option. From #76 

> Thanks for reporting this! This behavior is actually a feature of keyboard accessibility. By clicking/tapping on a gallery, it adds focus to its element. This will jump the scroll so that element is completely in the viewport.

If this behavior is really bugging you, you can disable it with `accessibility: false` -- which I don't recommend because accessibility is a wonderful thing.

**Comment by luksak** [comment]
Thanks for the fast reply! Sorry, I couldn't find this issue. I will try this. Is this the only behavior ```accessibility: false``` controls?

**Comment by luksak** [comment]
Oh, I see... This is not so good. Do you still think that modifying the scroll position is a bad idea? Fixed headers kind of break this completely.

**Comment by desandro** [comment]
>  Do you still think that modifying the scroll position is a bad idea?

Yes, this is a bad idea, and complicated to implement. You'll have to decide whether you prefer no scroll-jumping or less accessibility.

**Comment by luksak** [comment]
Ok. Thank you!
