### ISSUE TITLE
Callback when Flickity is initialized?

### ISSUE THREAD

**Issue by mildrenben** [metafizzy/flickity#269]
On load of my flickity gallery, often there is a split second flash of all the gallery elements stacked up vertically before Flickity kicks in. It can be seen here http://codepen.io/tutsplus/pen/mJGZzx

How can I apply opacity 0 to the flickity gallery and then opacity 1 once its fully loaded so the user doesn't see the vertical stack and jarring change?

**Comment by desandro** [comment]
See demo http://codepen.io/desandro/pen/avyQWE

Hide the gallery with CSS by default.

``` css
.gallery {
  opacity: 0;
}
```

Then show the gallery after initializing Flickity

``` js
var $gallery = $gallery.flickity();
$gallery.css({ opacity: 1 });
```

**Comment by mildrenben** [comment]
@desandro Thanks so much for the speedy response. Any chance of a vanilla js version please?

**Comment by desandro** [comment]
Updated comment with vanilla JS code

**Comment by mildrenben** [comment]
@desandro Here's a codepen with the vanilla js, doesn't seem to work... http://codepen.io/mildrenben/pen/gaxQjY

**Comment by mildrenben** [comment]
Scrap that, I was being stupid
