### ISSUE TITLE
imagesLoaded option broken when images are children of cells

### ISSUE THREAD

**Issue by virgo79** [metafizzy/flickity#27]
Hi,

Thanks for this awesome plugin.
I'm trying to use flickity toghether with imagesLoaded for a correct images loading.

I noticed that, if each image is placed into a parent div, imagesLoaded does not load correctly them and layout breaks. To better show the problem I have build the two following links:

1) Correct image loading:
<a href="http://flickity.virgotest.com/imgnodiv.html" target="_blank">flickity.virgotest.com/imgnodiv.html</a>

2) Broken image loading:
<a href="http://flickity.virgotest.com/imgdiv.html" target="_blank">flickity.virgotest.com/imgdiv.html</a>
in this example each img tag is inside a div element.

I attach below a screenshot from the chrome debug console.
I suggest to use chrome to verify the issue. Firefox seems to show the layout without breaking, but report an error too.

![flickity-imagesloaded](https://cloud.githubusercontent.com/assets/6567583/5962896/93ff8d32-a7e7-11e4-9eab-cb8a8d9f67d9.png)

Giving a parent div to each image is necessary, for example, if you wish to show captions for images.

Maybe ticket #10 could be connect to this?

**Comment by virgo79** [comment]
The problem is that getCell (at line 3568) return undefined if img is inside a div parent.
However this will not break the layout. Layout will break (chrome and safari) if img elements has max-width set to 100%.
Setting max-width to none in all img elements everything works fine.

**Comment by desandro** [comment]
Thank you for reporting this issue. This sounds like a legitimate bug. I'll have to look into it.

---

Thanks you for this feedback. [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), email me yo@metafizzy so I can send some your way.

**Comment by desandro** [comment]
Fixed in Flickity v0.2 :white_check_mark:
