### ISSUE TITLE
Flickity + Videojs + next() function not working

### ISSUE THREAD

**Issue by mildrenben** [metafizzy/flickity#270]
This one is only really viewable with an example http://codepen.io/mildrenben/full/rOzQLy/

I have a flickity gallery full of videojs elements. It works fine for the most part, you can play the vids and push the next and prev buttons.

But if I tie vid.on('end') to flkty.next() it all goes awry. Basically, when the video ends I want flickity to move to the next.

**Comment by desandro** [comment]
Remove initializing in HTML and initialize only in JS. Initialize Flickity outside of the videojs stuff. Then it should work. See demo http://codepen.io/desandro/pen/f904e276eed8259b16e32e400a8ad476 I'm having trouble with the demo loading the video, but this should work

``` js
var flkty = new Flickity('.gallery', {
  draggable: false
});

var video = videojs('first-video').ready(function(){
  var player = this;
            
  player.on('ended', function() {

    flkty.next();
  });
});

```

**Comment by mildrenben** [comment]
Works like a charm, thanks so much dude :)
