### ISSUE TITLE
asNavFor not working with requirejs

### ISSUE THREAD

**Issue by hjeong1114** [metafizzy/flickity#271]
Hello,
Initializing flickity in vanilla JS doesn't work with requireJS.
Working asNavFor when flickity is included as an external js: http://codepen.io/hjeong1114/pen/ojeRwZ
Not working using requireJS: http://codepen.io/hjeong1114/pen/Lpjojx.

Additional info: Some debugging revealed that the factory for asNavFor is never executed:
```
  // AMD
    define( 'flickity-as-nav-for/as-nav-for',[
      'classie/classie',
      'flickity/js/index',
      'fizzy-ui-utils/utils'
    ], function( classie, Flickity, utils ) {
      return factory( window, classie, Flickity, utils ); //never executed
    });
```

**Comment by desandro** [comment]
Thanks for reporting this issue. To load the `as-nav-for` package with `flickity.pkgd.js`, you need to do a second `require` call, similar to using [jQuery Bridget](http://flickity.metafizzy.co/extras.html#requirejs). See demo http://codepen.io/desandro/pen/RWLayx/

``` js
require.config({
  paths: {
    'flickity': 'path/to/flickity.pkgd'
  }
});

require(['require', 'flickity'], function(require, _Flickity) {
  // require as-nav-for, it's included in flickity.pkgd.js
  require(['flickity-as-nav-for/as-nav-for'], function(Flickity) {
    var flickity = new Flickity('.gallery-main');
    var nav = new Flickity('.gallery-nav', {
      asNavFor: '.gallery-main'
    });
  });
});
```

**Comment by Und3Rdo9** [comment]
Hi David,

Is there no way to initialise both flickity and flickity-as-nav-for in one require call? We only initialise our sliders through the html data-flickity attribute. That means that our sliders that have asNavFor need to await auto-initialisation before as-nav-for is loaded or otherwise the asNavFor option won't work. Currently we have it solved by doing something like this, but it's not a very nice solution as we load two versions of Flickity now it seems: 

``` javascript
    if(document.querySelectorAll('[data-flickity]').length) {
      require(['require', 'flickity'], function(require, _Flickity) {
        
        // let flickity auto-initialize things through the html data-flickity attribute
        
        var asNavsFor = document.querySelectorAll('[data-flickity-as-nav-for]');
        if(asNavsFor.length) {
          require(['flickity-as-nav-for/as-nav-for'], function(Flickity) {

            var intializedSliders = [];
            for (var i = 0; i < asNavsFor.length; i++) {
              // intialize sliders with the asNavFor option
              intializedSliders[i] = new Flickity(asNavsFor[i], JSON.parse(asNavsFor[i].getAttribute('data-flickity-as-nav-for')));
            }
          });
        }
        
      });
    }

    ```

**Comment by desandro** [comment]
@Und3Rdo9 This is only if you want to use flickity.pkgd. If you just require `flickity-as-nav-for` as an npm package, it should work just fine.
