### ISSUE TITLE
Change cell alignment after Initialization?

### ISSUE THREAD

**Issue by nonlinearcom** [metafizzy/flickity#273]
Hi, is there any way to change the cellAlign option value after initialisation? for example using media queries?

Thanks!

**Comment by desandro** [comment]
Sorry, Flickity does not support changing `cellAlign` after initialization. Looks like this issue didn't get much interest.

**Comment by vschaefer** [comment]
Hi,

I need this feature for a project too. Does Flickity support this in the meantime?
Or is there a workaround?

Thanks and regards
Volker
