### ISSUE TITLE
Flickity returning syntax error from minified js file

### ISSUE THREAD

**Issue by mjrapp** [metafizzy/flickity#274]
Everything seems to load, but the js file is not activating and I'm getting a fatal syntax error from the js file. Thanks!

![screen shot 2015-10-19 at 12 12 28 pm](https://cloud.githubusercontent.com/assets/15200169/10585078/565f59c4-765b-11e5-9604-c717db9f3486.png)

http://buttermilkskypie.generatornetwork.com/test

**Comment by desandro** [comment]
Looks like there is a syntax error in the JSON of your `data-flickity-options='{}'` attribute.

**Comment by mjrapp** [comment]
thanks for responding. I've made the changes you noted, but now am getting the attached errors.
![screen shot 2015-10-20 at 8 39 28 am](https://cloud.githubusercontent.com/assets/15200169/10608785/2b1f838c-7706-11e5-87c6-6258f626ab82.png)

**Comment by desandro** [comment]
Looks like you're using an old version of jQuery. Upgrade to jQuery v1.7+

**Comment by mjrapp** [comment]
I can't. The CMS runs on the older version, and the new version will break
it. Let me try to wrap it in their include and see if it works.

Mike Rapp

615.400.0646

This e-mail including any attachments is confidential and may be legally
privileged. If you have received it in error please advise the sender
immediately by return email and then delete it from your system. The
unauthorized use, distribution, copying or alteration of this email is
strictly forbidden.

**Comment by mjrapp** [comment]
Hello,

Well, it appears as though the "fix" did indeed eliminate all console errors. Unfortunately, it did not make Flickity work. Given that I cannot find any errors, I am reluctantly concluding that Flickity simply won't work with this particular CMS. Bummer, love your work. If you can recommend a third party developer who is familiar with your work (and perhaps that is you) I'd certainly consider paying for dev help.
