### ISSUE TITLE
Flickity doesn't work well with masonry grid

### ISSUE THREAD

**Issue by piotrkulpinski** [metafizzy/flickity#275]
Hi there,
I've noticed that when you try to use flickity when you have a number of slides with masonry grid in each of them the layout of flickity slider is broken.

https://www.dropbox.com/s/jv1p0hmu3b32ql2/Screenshot%202015-10-21%2010.57.48.png?dl=0 - each of the slides is pushed down to another row.

Is there any quick fix for that?
Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by piotrkulpinski** [comment]
Hi @desandro 
Looks like it was caused by something on my site, as I can't reproduce it on one of your pens.

Sorry about the trouble!
