### ISSUE TITLE
First pixel line of next slide visible

### ISSUE THREAD

**Issue by thedgbrt** [metafizzy/flickity#276]
Hey guys,
I reproduced the issue with the current workaround available here http://codepen.io/anon/pen/epKOpB

![capture d ecran 2015-10-29 a 15 36 31](https://cloud.githubusercontent.com/assets/1362558/10821536/2d87d95e-7e53-11e5-8d3d-27ca0aa773ac.png)

I think this should be documented somewhere so that the next people don't spend 2 hours trying to fix it.

**Comment by desandro** [comment]
Thanks for reporting this issue. Yes, this happens sometimes due to pixel rounding errors. It doesn't happen at all screen sizes. I'm not sure if there is a good solution.

**Comment by richgcook** [comment]
I have this issue too. Not sure of solution but just thought I'd report it too.

**Comment by dagobertrenouf** [comment]
@richgcook the way I fixed it was to add a margin on the side of each image (so there's a gap between them). If that's okay with the design your implementing it's an easy fix.

**Comment by aunruh** [comment]
Hey!
Here's another solution that doesn't require margins on the sides of each image:
http://codepen.io/arminunruh/pen/PZdygZ

**Comment by akmur** [comment]
I think I found the best way to fix this.

Use the following CSS

.slide {
  margin: 0 0.005%;
  width: 99.99%;
}

Works for me

**Comment by schiavassa** [comment]
Setting the width of the slides with CSS to something like `100.5%` or `101%` seems to work for me.

**Comment by mitogh** [comment]
Another way I was able to fix this was by wrapping the item around a div and applying a padding. 

Like:


```html
<div class="carousel-cell">
  <div class="slider-item-wrap">
     <img src="http://i.imgur.com/q9zO6tw.jpg" alt="cat nose" />
  </div>
</div>
```

```css
.slider-item-wrap { 
   padding-left: 10px;
   padding-right: 10px;
}
```

**Comment by desandro** [comment]
I'm closing this issue for now. Looks like its been quiet for a while.

**Comment by obliviga** [comment]
> I am also experiencing this bug. Has anyone found a true fix?

Nevermind, looks like adding `percentPosition: false` fixes the issue in my case.
