### ISSUE TITLE
Flickity HTML Initialisation

### ISSUE THREAD

**Issue by aaronstezycki** [metafizzy/flickity#277]
Is there anyway to achieve a callback like this #269, but by initialising with html ?

**Comment by desandro** [comment]
Hmm, interesting request.

If you are using jQuery, you can listen to the initial `cellSelect` event. See demo http://codepen.io/desandro/pen/NGzNgP

``` js
// capture initial cellSelect
$('body').one( 'cellSelect', function( event ) {
  console.log( 'initial cell select on ', event.target )  
});
```

But this code is a race condition, and may happen after the initial event has been triggered.

A better solution is to initialize in HTML with your own code so you don't have to hack it. See demo http://codepen.io/desandro/pen/yYEOza

``` js
// init Flickity on all .js-custom-flickity elements
$('.js-custom-flickity').each( function( i, elem ) {
  var $elem = $(elem);
  var optionsAttr = $elem.attr('data-flickity-options');
  var options = optionsAttr ? JSON.parse( optionsAttr ) : {};
  // init Flickity
  $elem.flickity( options );
});
```

**Comment by aaronstezycki** [comment]
Using a json parse. Brilliant, I had thought of that but wasn't quite sure how to execute it. This worked perfectly! :)

**Comment by Julix91** [comment]
Seems all the older ones point at non https versions of the link - wonder if that's fixable with a redirect or something? 

![Screen Shot 2019-03-29 at 1 58 15 PM](https://user-images.githubusercontent.com/12877287/55262326-baf17080-522a-11e9-802c-b0682a541c52.png)

**Comment by desandro** [comment]
@Julix91 pen files updated.
