### ISSUE TITLE
Full screen support

### ISSUE THREAD

**Issue by asafbrukarz** [metafizzy/flickity#28]
Good job on this library. Very well organised and easy to use. 

Many image galleries will implement a full screen image feature that can toggle an image to full screen.  Is there a plan to implement something similar?

**Comment by desandro** [comment]
Thank you for this feedback! Yes, I imagine some users would like this feature. I don't feel it should be built into Flickity, but I could try putting together an example to show how it could be done.

If you would like full-screen support, please **+1** this issue.

**Comment by nvartolomei** [comment]
:+1:

**Comment by o-l-e** [comment]
+1

**Comment by kamaal-** [comment]
+1

**Comment by AronWatson** [comment]
+1

On Mon, Feb 2, 2015 at 8:59 PM, Kamaal Aboothalib <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metafizzy/flickity/issues/28#issuecomment-72418208>.
>



-- 
Regards
Aron Watson

Phone: (03) 4349242
Address: 39 Upper Ure Street, Oamaru

**Comment by kiul** [comment]
+1

**Comment by markpestickov** [comment]
+1

**Comment by downFast** [comment]
+1

**Comment by viocassel** [comment]
+1

**Comment by yann369** [comment]
+1

**Comment by zslabs** [comment]
+1

**Comment by osricmacon** [comment]
+1

**Comment by pepperstreet** [comment]
+1

**Comment by remisture** [comment]
+1

**Comment by ryanwiemer** [comment]
+1

**Comment by iamalexkempton** [comment]
+1

**Comment by ffub** [comment]
+1

**Comment by dope** [comment]
+1

**Comment by Twanneman** [comment]
+1

**Comment by marianoviola** [comment]
+1

**Comment by rehananwar** [comment]
+1

**Comment by kevohagan** [comment]
+1

**Comment by kevohagan** [comment]
+1

**Comment by mariyanang** [comment]
+1

**Comment by paulmasek** [comment]
+1

**Comment by clausjuhl** [comment]
+1

**Comment by rppld** [comment]
+1

**Comment by chrisbarry** [comment]
+1

**Comment by aaronstezycki** [comment]
+1

**Comment by nelga** [comment]
+1 

Would love to see an example with https://github.com/tholman/intense-images
At the moment there's a few UX conflicts.

**Comment by rctneil** [comment]
+1

**Comment by mmjaeger** [comment]
any news or progress on this one????

**Comment by traviseugeneclark** [comment]
+1, Tried integration with Clearing Lightbox and a few others with limited success. Would be very interested in seeing an example.

**Comment by desandro** [comment]
I've looked at [Intense Images](http://tholman.com/intense-images/) and [zoom.js](http://fat.github.io/zoom.js/) and I'm sorry to say neither solutions will work with Flickity. The main problem is that they rely on `click` and do not provide an API to disable click behavior and use something like Flickity's `staticClick`. I'll likely have to develop a custom solution.

**Comment by nelga** [comment]
I found this resource that shows OwlCarousel and PrettyPhoto working together. Might be helpful in determining a way to make this happen (or how not to make it happen).

Original Question: http://stackoverflow.com/questions/21501157/owl-carousel-and-lightbox-together-or-is-there-another-solution

Example: http://jsfiddle.net/gableroux/gxG87/

**Comment by LucianNovo** [comment]
+1 (?) 
is this going to happen? I'd love to know <3

**Comment by nelga** [comment]
I managed to get Flickity playing nice with FancyBox (which has an API). Should be able to get it working with PrettyPhoto using a similar technique too.

I've popped it in Codepen if it helps anyone. Please feel free to optimise/clean my code: http://codepen.io/creaturelab/pen/qdLdVM/

**Comment by nelga** [comment]
And a version referencing the 2x size using SRCSET: http://codepen.io/creaturelab/details/eNbNar/

**Comment by fmalina** [comment]
+1

**Comment by desandro** [comment]
@nelga This is great! Thank for sharing :heart_eyes:

**Comment by fmalina** [comment]
There are two issues with the example: FancyBox missing arrows and Flickity on Safari 8 Desktop advances each slide only by 5px (missed the width of image?). Not sure what causes the bugs.

**Comment by nelga** [comment]
You're right, I was in a rush. Maybe try this out. Seems to be working in Chrome and Safari for me:

http://codepen.io/creaturelab/pen/qdLdVM

**Comment by promptdev** [comment]
+1

**Comment by JasonTheAdams** [comment]
+1

**Comment by davidklebanoff** [comment]
+1

**Comment by aaronstezycki** [comment]
Ive had a crack at this with a popular plugin call magnific popup. However theres an issue when selecting the correct popup. The lightbox always starts from 1, even if you click the second image. I need to find a way counting the images and selecting the correct one. http://codepen.io/aaron-stez/pen/ZbxooO

**Comment by aaronstezycki** [comment]
Done, with Magnific Popup, and Photo Swipe. http://codepen.io/aaron-stez/pen/ZbxooO, http://codepen.io/aaron-stez/pen/RWMXWj

**Comment by desandro** [comment]
:unamused: Not a fan of using _another_ slider on top of Flickity

**Comment by aaronstezycki** [comment]
No? Just gives the user added functionality when the image is expanded. I don't have to click out/close, then navigate and open the next, which equals less clicks? Your right in terms of code... there's a lot here that could optimised. Ideally, we just want to expand Flickity to a full page with X amount of slides.

**Comment by nonlinearcom** [comment]
+1

**Comment by Npahlfer** [comment]
+1

**Comment by Chriz74** [comment]
+1

**Comment by srimola** [comment]
+1

**Comment by SirNovi** [comment]
+1

**Comment by samuelwill** [comment]
+1

**Comment by Siton-Design** [comment]
+1

**Comment by pinkp** [comment]
+1

**Comment by spacecat** [comment]
+1

**Comment by msd64** [comment]
I got Flickity getting fullsecreen with screenfull.js

**Comment by vlemcoff** [comment]
+1

**Comment by vilav** [comment]
+1

**Comment by fgilio** [comment]
+1

**Comment by benjibee** [comment]
I'm not sure why you'd need a light box *and* Flickity. Just make Flickity fullscreen, use the arrows to navigate, it's pretty simple.

Here's my [basic and still buggy implementation](http://independent-photo.com/photographers/moe-zoyari/), but you get the idea.

**Comment by vlemcoff** [comment]
Hi Benji,


The reason would be to create Product slideshows. The original images would be thumbnails, so that the customer could also view product information on the same screen. Then, upon clicking on a product to make it bigger, that's when I would need the lightbox option.


I found a way using magnific pop up, but thanks anyway!


Thanks,
Veronica


________________________________

**Comment by evangrichards** [comment]
@benjibee Are you able to share with us the code you put together for your solution?

**Comment by davedawkins** [comment]
+1, please

**Comment by davedawkins** [comment]
This may be of interest to some of you (not my work)
http://codepen.io/jimahyland/pen/GZGrEa/

**Comment by TheRealJAG** [comment]
+1, please

**Comment by alexyakir** [comment]
Got flickity playing nice with https://github.com/francoischalifour/medium-zoom.

**Comment by davidklebanoff** [comment]
@alexyakir - any special changes? Or mostly just drop in?

**Comment by PaoloFalomo** [comment]
I know this might be old but here is an easy way to do it, nope? https://codepen.io/PaoloFalomo/pen/mqxXGX

**Comment by alexyakir** [comment]
@davidklebanoff just drop in.

**Comment by yoerivdm** [comment]
@alexyakir You have a sample on codepen?

**Comment by desandro** [comment]
🎉  **[Flickity v2.1.0](https://github.com/metafizzy/flickity/releases/tag/v2.1.0) has been released with support for all new [`fullscreen` option. See docs!](https://flickity.metafizzy.co/options.html#fullscreen)** 🎉

> Enables fullscreen view of carousel. Adds button to view fullscreen. In fullscreen view, pressing ESC will exit fullscreen.

``` js
fullscreen: true
```

---

I am delighted to finally ship this feature. 3 years of waiting now over!  I'm now closing this issue for the feature request. Please open a new issue if you into trouble with using `fullscreen`. Thanks for all the +1's and 👍 over the years. 🌈🐻
