### ISSUE TITLE
IE8: Prev/next causes type mismatch error and does not move slides

### ISSUE THREAD

**Issue by iamkeir** [metafizzy/flickity#281]
The demo carousel on the Flickity homepage does not seem to function correctly in IE8 - it causes a type mismatch error and does not move the carousel forward/back when clicking the next/prev arrows.

This error can be experienced on the homepage - but I also created an isolated test case, although I am not confident that codepen in debug mode isn't causing some other issue for IE8 as well.

http://codepen.io/iamkeir/pen/YyjGEN
http://s.codepen.io/iamkeir/debug/YyjGEN

Any ideas? Thanks

**Comment by aaronstezycki** [comment]
I have also come across this, posted earlier #280.

**Comment by iamkeir** [comment]
@aaronstezycki ah yes sorry for the double-post, thanks for referencing

**Comment by desandro** [comment]
Thank you for reporting this bug. Looks like this was a typo. See [Unidragger commit 320eb8d5](https://github.com/metafizzy/unidragger/commit/320eb8d5120d42adc0ee30deeef2addc9fd1ffa3). Fix will land in the next release.

**Comment by iamkeir** [comment]
Great, thanks @desandro :)

**Comment by mikeebee** [comment]
@desandro I'm using the npm version, where can I add this fix? I tried adding it where I fired Flickity but I got an error `Uncaught ReferenceError: Unipointer is not defined`

**Comment by desandro** [comment]
This fix was added to Flickity in [v1.1.2](https://github.com/metafizzy/flickity/releases/tag/v1.1.2).

@mikeebee You should be able to update your dependencies `npm install`. Make sure Unidragger v1.1.6 is installed.
