### ISSUE TITLE
Disable sliding /default behavior (or disable at all) if viewport is larger than cells

### ISSUE THREAD

**Issue by danielvonmitschke** [metafizzy/flickity#282]
Hi,

is there a way to disable the default flickity behavior (sliding / showing dots, arrows) if the number of cells is so small (smaller than the viewport) that sliding would not even make sense?
Also to re-init/re-enable if cells start to be larger than the viewport (e.g. defined by a css breakpoint).

I extended flickity some time ago to not init itself if only one cell is present (would also be nice to have this on board), but I would need a dynamic solution to disable/re-enable it based on the total width of all cells compared to the viewport width.

thx,

daniel

**Comment by desandro** [comment]
Thanks for reporting this issue. We have a duplicate open at #278
