### ISSUE TITLE
Question about flickity animation

### ISSUE THREAD

**Issue by danielvonmitschke** [metafizzy/flickity#283]
Just out of curiosity (and probably to learn sth.): is there a reason why you are doing the frame animation yourself in the plugin and not using css transitions to accomplish this?
thx

**Comment by desandro** [comment]
Thanks for the question! Frame animation allows better control of the animation. Other carousels use transitions, and I find their animation to feel a bit off. By using frame animation, I have a better platform for using physics-based animation. I did a whole talk on the subject: [Practical UI Physics](https://www.youtube.com/watch?v=90oMnMFozEE)

CSS transitions could be used, but it would require a lot more code. Consider the behavior when you do a strong flick, but it wobbles back to a slide.

**Comment by danielvonmitschke** [comment]
thanks for the link!
