### ISSUE TITLE
Maximum call stack size exceeded when using asNavFor for two sliders

### ISSUE THREAD

**Issue by JSW888** [metafizzy/flickity#284]
I have a main slider and a thumbnail slider below it. I want to use 'asNavFor' on each slider for the other slider, so that they navigate simultaneously. It all works fine, except I'm getting a 'Maximum call stack size exceeded' error in the console. It actually doesn't seem to be causing any issues other than when I use lazyload it's not loading all of the images correctly, and creating some display issues. Is there a workaround for this? 

A bit more info on the error:

Uncaught RangeError: Maximum call stack size exceeded
c.dispatchEvent @ flickity.min.js?ver=4.3.1:12
c.select @ flickity.min.js?ver=4.3.1:12
i.navCompanionSelect @ flickity.min.js?ver=4.3.1:13
onNavCompanionSelect @ flickity.min.js?ver=4.3.1:13
n.emitEvent @ flickity.min.js?ver=4.3.1:12
c.dispatchEvent @ flickity.min.js?ver=4.3.1:12
c.select @ flickity.min.js?ver=4.3.1:12
i.navCompanionSelect @ flickity.min.js?ver=4.3.1:13
onNavCompanionSelect @ flickity.min.js?ver=4.3.1:13
n.emitEvent @ flickity.min.js?ver=4.3.1:12

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by JSW888** [comment]
Thanks for the response. I literally just forked your example and added the reciprocal 'asNavFor' and you can see the same error in the console:

http://codepen.io/desandro/pen/RWLayx

**Comment by desandro** [comment]
Thanks for that. To sync up two carousels, I recommend using [flickity-sync](https://github.com/metafizzy/flickity-sync) instead of asNavFor. It's not mentioned in the docs because I'm not sure how useful it is.

Looks like asNavFor breaks due to an infinite loop if you try to use one nav for another, which I'm okay with.

**Comment by JSW888** [comment]
Thanks, didn't realize that was an option. Sync gives me the same functionality with no infinite loop issues, so problem solved.
