### ISSUE TITLE
Sync small bug

### ISSUE THREAD

**Issue by apsolut** [metafizzy/flickity#286]
Codepen: http://codepen.io/apsolut/full/GpPomV/
*Must resize browser to get scrollbars

If we interact with first carousel (drag,click) and then if we click on bottom one (arrows or drag) then it jumps down to it, it maybe doesnt look as big problem, but when you have this in middle of page, jumping is much more notable

![User Case](https://i.gyazo.com/34864bc0db1ed725178a34ad37750212.gif)

**Comment by desandro** [comment]
Thank you for reporting this bug! I'll have to take a look.

**Comment by desandro** [comment]
Sounds like this the scroll jump on click issue, See #76. This bug was fixed in Flickity v1.1.2.
