### ISSUE TITLE
IE8: Destroy causes type mismatch error

### ISSUE THREAD

**Issue by avalanchedigital** [metafizzy/flickity#287]
Thanks for your hard work.

Destroy seems to cause a type mismatch error in IE8, I am wondering if this is possibly related to:

https://github.com/metafizzy/flickity/issues/281

.. and a similar issue.  Can you advise?

Have tried creating a reduced test case in Code Pen but it's not having it.

**Comment by desandro** [comment]
Thanks for reporting this bug. I'll have to take a look.

**Comment by avalanchedigital** [comment]
Thanks @desandro.  Has this been looked at yet at all?

**Comment by desandro** [comment]
@avalanchedigital Have you tried the temporary solution https://github.com/metafizzy/flickity/issues/281#issuecomment-153230813 ?

**Comment by avalanchedigital** [comment]
@desandro fantastic that has done it, thankyou !
