### ISSUE TITLE
Deck of cards style

### ISSUE THREAD

**Issue by coreyworrell** [metafizzy/flickity#288]
Hi,

Wondering if you might have an idea on how to best accomplish the look of a deck of cards with Flickity. So the slides could be whatever width (say 70% of container), but instead of aligning slides back to back or next to each other, there could be an overlap, and then when you select a slide or swipe, the active slide would slide over (or out of view depending on your layout settings) and the new slide would now show.

Thank you.

**Comment by desandro** [comment]
Thank you for this feature request. **+1 this issue** if you are interested in seeing this feature added to Flickity.

I can visualize how this looks, but Flickity was not built with this feature in mind. It would require a lot more code to get it to work.

**Comment by oskarrough** [comment]
Perhaps https://github.com/gajus/swing is what you're looking for?

**Comment by desandro** [comment]
Looks like this issue hasn't gained enough interest. Closing this one. Thanks again for this request! :strawberry:
