### ISSUE TITLE
Flickity Viewport Height With Lazy Loading in IE

### ISSUE THREAD

**Issue by moe-developerr** [metafizzy/flickity#292]
The **height of my viewport is huge** whenever I use lazy loading in IE, thus **pushing all content underneath it**. Other browsers FF, Chrome, etc.. work fine. I tried adding **imagesLoaded** property but **didn't help**. It only works when I switch **data-flickity-lazyload** back to src for my images, or if I change lazyLoad: true to a number that covers all my carousel slides.

This is a reduced test case: [http://codepen.io/moe-developerr/pen/YybMVN](http://codepen.io/moe-developerr/pen/YybMVN)

**Comment by desandro** [comment]
Thank you for reporting this issue. The issue looks to be a browser quirk. IE renders an unloaded image with a `28 x 30` placeholder. With CSS `img { width: 100%; }`, the placeholder image will grow, maintaining its size ratio. That's where the extra height is coming from.

To resolve this issue, you can add this CSS

``` css
img[data-flickity-lazyload] { width: auto; }`
```

This will disable the unloaded image growing tall. Or you can hide the image completely

``` css
img[data-flickity-lazyload] { display: none; }`
```

See demo http://codepen.io/desandro/pen/meZyzp

**Comment by moe-developerr** [comment]
Works like a charm! Thanks a lot @desandro
