### ISSUE TITLE
Include lock feature

### ISSUE THREAD

**Issue by rzschoch** [metafizzy/flickity#299]
Hi,

for a current project it would be nice to have a slides lock feature integrated. (what is a proper way to implement it with the current version of flickity?)

I just stumbled upon it here:
http://www.idangero.us/swiper/api/ (search for lockSwipes method)

There are also some other interesting features available (despite cube and coverflow effects) – probably good ideas for the flickity roadmap :)

Background:
I use the flickity slider as a navigation for audio content that needs to be ready before the slider is getting enabled.

Thanks a lot for your great work
René

**Comment by desandro** [comment]
Thanks for submitting this issue. You can enable and disable dragging with two undocumented methods: `bindDrag` and `unbindDrag`.  See demo http://codepen.io/desandro/pen/adYJEQ/
