### ISSUE TITLE
Enable vertical page scrolling for touch devices

### ISSUE THREAD

**Issue by macgyver** [metafizzy/flickity#3]
for example on the demo page, http://flickity.metafizzy.co/

When I touchstart the flickity gallery and then swipe up or down, I would expect for the page to scroll up/down, but nothing happens. I know this is kind of a hard problem, how can you know where the user plans to scroll to? what threshold of horizontal movement constitutes the desire to swipe vs. just a wandering vertical scroll...

One advantage of keeping it the way it is now (besides not overcomplicating things) is that I can touchstart on the gallery, then drag my finger down below the gallery before flicking, so I can view the entire slide while swiping.

**Comment by desandro** [comment]
Hi! Thanks for reporting this. Adding functionality for vertical scroll would be a solid feature. Also requested by [DavidDarnes on Twitter](https://twitter.com/DavidDarnes/status/557612876035534848).

If you like [stickers](http://metafizzy.co/blog/flickity-beta-testing/), email me your mailing address yo@metafizzy.co.

**Comment by desandro** [comment]
Vertical page scroll on mobile devices is now enabled in Flickity v0.2.0.
