### ISSUE TITLE
jquery-bridget : missing _init() method

### ISSUE THREAD

**Issue by glafarge** [metafizzy/flickity#30]
`Flickity.prototype._init()` method required to work properly with [jquery-bridget](https://github.com/desandro/jquery-bridget).

**Comment by glafarge** [comment]
Maybe the following could solve the problem ?... Not tested.

```javascript
Flickity.prototype._init = function() {
	this._create();
}
```

**Comment by desandro** [comment]
Good catch! Thanks you for this feedback. [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), email me yo@metafizzy so I can send some your way.

**Comment by glafarge** [comment]
Thank you ! :email:

**Comment by glafarge** [comment]
:+1:
