### ISSUE TITLE
Adaptive height Images distort when window resize

### ISSUE THREAD

**Issue by santiagom86** [metafizzy/flickity#300]
First, sorry for my english :)

I make a fluid gallery with Flickity, but when resize the window, the image galleries are distorted. Why?
<a href="http://santimartinez.com.ar/gallery/gallery.html" target="_blank">Example of my Gallery</a>

<b>My js</b>
<hr>

$(document).ready(function(){
$('.gallery').flickity({
  resize: false,
  setGallerySize: false,
  pageDots: false,
  wrapAround: false,
  cellAlign: 'center',
  contain: true
});
});

<b>My css</b>
<hr>

.gallery {
  background: #FAFAFA;
  padding-bottom: 33.3%; /* gallery height has percentage of width */
  min-height:200px;
}

/* inherit size from gallery */
.gallery .flickity-viewport {
  position: absolute;
  width: 100%;
}

.gallery-cell {
width:auto;
  height: 100%; /* inherit height from gallery */
  counter-increment: gallery-cell;
}

.gallery-cell img{
  height: 100%; /* inherit height from gallery */
  width:auto;
  margin-right: 5px;
}

.flickity-page-dots {
	bottom:20px;
}

<hr>

Thanks!

**Comment by desandro** [comment]
Thanks for submitting this issue. Have you looked at using [`imagesLoaded: true`](http://flickity.metafizzy.co/options.html#imagesloaded) ?
