### ISSUE TITLE
Custom previous/next buttons with delay

### ISSUE THREAD

**Issue by enzo77** [metafizzy/flickity#301]
Ciao!!
Thanks foy your effort.
I have a problem. Can I make a little delay with the transition when you click on the arrows?
I explain you better...  When I click on the arrow I would like that the transition started in 1 or 2 seconds. 
Can I make that?
Thank you very much!
Un saludo,Enzo

**Comment by desandro** [comment]
Yes, you could do this with your [own custom UI](http://flickity.metafizzy.co/extras.html#custom-navigation-ui). Take a look at that code and examples on CodePen. Feel free to modify it for you own purposes.

**Comment by enzo77** [comment]
thanks
