### ISSUE TITLE
Continue Auto Play After Clicking Arrows

### ISSUE THREAD

**Issue by TaylorFoster90** [metafizzy/flickity#304]
Hello! Love this plugin, and use it all the time. This is the only time I have had an issue with the usability and I'm hoping it can be solved easily. 

Is there a way for the auto continue to keep going after a directional arrow is clicked? Using the slider nav arrows kills the auto play function. 

Thank You!

**Comment by desandro** [comment]
Hello, thank! See https://github.com/metafizzy/flickity-docs/issues/5#issuecomment-78370765 for Player API
