### ISSUE TITLE
watchCSS and lazyload... not loading images when slider not initialising

### ISSUE THREAD

**Issue by richgcook** [metafizzy/flickity#305]
I'm getting a weird issue when using `watchCSS` and `lazyload`. On a desktop this all works fine and if I resize the browser down to mobile then `watchCSS` takes over and destroys the slider so the images become stacked. This is all fine. However. If I refresh when the browser is at a mobile size (or test on my phone) the lazyload isn't kicking in because of course `watchCSS` is setting the slider not to initialise at this level but ultimately this means that the lazyloading isn't kicking in.

Any thoughts of ideas around this? It makes sense why it is happening... but maybe I have to write a bit of code so on smaller screens it fires the lazyload?

![screen shot 2016-01-07 at 12 37 11](https://cloud.githubusercontent.com/assets/901289/12170727/8ce235b0-b53b-11e5-820b-e4d1b86f645a.png)

**Comment by desandro** [comment]
Thanks for reporting this issue. As you mention, `lazyLoad` will not load in images If Flickity is disabled via `watchCSS`. When Flickity is disabled, you'll have to implement your own lazy load solution.

Here's one solution. See demo http://codepen.io/desandro/pen/VepoqN

``` js
var $gallery = $('.gallery').flickity({
  lazyLoad: true,
  watchCSS: true
});
// get Flickity instance
var flkty = $gallery.data('flickity');

// load all lazy load images 
if ( !flkty.isActive ) {
  $gallery.find('[data-flickity-lazyload]').each( function( i, elem  ) {
    var $elem = $(elem);
    $elem.attr( 'src', $elem.attr('data-flickity-lazyload') );
    $elem.addClass('flickity-lazyloaded');
    elem.removeAttribute('data-flickity-lazyload');
  });
}
```

**Comment by richgcook** [comment]
Thanks for this; my thoughts too... makes sense I guess. Not sure how this could be implemented into the plugin? Perhaps if the `watchCSS` shows the `content:''` then it loads all the lazy load images but might be a lot of overhead.

I'd also thought I'd point out that this is the same for anything that is setup using the API, so for example, the below code, would error out when `watchCSS` comes into play as the slider is destroyed by that point.

````
function updateCounter() {
    var cellNumber = flkty.selectedIndex + 1;
    $counter.text(cellNumber + '/' + flkty.cells.length);
}
updateCounter();
$slider.on('cellSelect', updateCounter);\
````

**Comment by desandro** [comment]
The best way to address this issue is to account for Flickity being active or not in your own code. 

``` js
var flkty = $gallery.data('flickity');

if ( !flkty.isActive ) {
  // do things when not active
}
```

In your example:

``` js
function updateCounter() {
    if ( !flkty.isActive ) {
       return;
    }
    var cellNumber = flkty.selectedIndex + 1;
    $counter.text(cellNumber + '/' + flkty.cells.length);
}

**Comment by richgcook** [comment]
This works for me, David. Thanks for all your help here.
