### ISSUE TITLE
flickity stop scroll after click

### ISSUE THREAD

**Issue by dormammun** [metafizzy/flickity#306]
Options : 
{"autoPlay": 5000, "pauseAutoPlayOnHover": false, "wrapAround": true, "selectedAttraction": 0.01, "friction": 0.15}

All works good, but after click slider sliders don't autoscroll, how to fix this ?

**Comment by desimon** [comment]
I think if we can disable the pause on hover, we could disable the stop on click too.
+1

**Comment by desandro** [comment]
Try setting `pauseAutoPlayOnHover: false` See http://flickity.metafizzy.co/options.html#autoplay

autoPlay stops on hover by default so users have control over the slider. This is good user experience. f you wish to re-start autoPlay, see Player API: https://github.com/metafizzy/flickity-docs/issues/5#issuecomment-78370765

**Comment by dormammun** [comment]
Not hover, on click flickity stop scroll

**Comment by desandro** [comment]
[v1.2.0](https://github.com/metafizzy/flickity/releases/tag/v1.2.0) has added [proper auto-play API](http://localhost/flickity-docs/build/api.html#player): `playPlayer`, `stopPlayer`, `pausePlayer`, `unpausePlayer`.

As for stopping auto-play on click: this is a feature of Flickity, so that the carousel does not auto-advance while users are interacting with its content. I feel this is a good pattern to uphold so there is no way to disable this behavior.

Closing this issue as resolved :whale:

**Comment by hottmanmichael** [comment]
For anyone trying to disable this behavior I ended up setting up a mouseleave event, this way when the user interacts with the slider it pauses, if they click it is still paused, but when their mouse leaves the area the slider resumes. Hope this helps anyone else that encounters this!

`carousel.addEventListener('mouseleave', function(e) {
    flick.playPlayer()
});`

**Comment by brayansti** [comment]
This worked for me

`$('#your-flickity-select').on( 'select.flickity', function() {
	$('#your-flickity-select').flickity('playPlayer')
})`

**Comment by sushil-cd** [comment]
Just write below code inside your Click event method then it should work.
var $carousel = $('.carousel').flickity({
     autoPlay: 1000
 });
   $carousel.flickity('playPlayer');

**Comment by sushil-cd** [comment]
<div style="width: 168px;height: 95px;" class="carousel-cell">
            <img  onclick="gallaryImageClick()" src="images/a.png"/>
</div>
//js code

function gallaryImageClick(){
var $carousel = $('.carousel').flickity({
autoPlay: 1000
});
$carousel.flickity('playPlayer');
}

**Comment by gsarig** [comment]
I understand the reasoning behind stopping autoplay on click, but I believe that it should resume when the user clicks on any element outside the carousel container, as well as when the slide changes (e.g. when they click and drag the slideshow to change a slide).

**Comment by davemoz** [comment]
It'd be nice to at least have the option to resume the slider if we feel differently than the author that it would be a good pattern to do so.

**Comment by richgcook** [comment]
Try this:
```
flkty.on('staticClick', function(event, pointer, cellElement, cellIndex) {
    flkty.playPlayer();
});
```

**Comment by kalonya** [comment]
When visitors on mobile devices try to scroll the page down, they have to touch the slider and the slider stops. I agree that there must be an option for this.

**Comment by MiguelRoot** [comment]
I just wanted it to stop when you hold or drag the mouse then continue with the animation
this helps me
`flkty.on('dragEnd', function(event, pointer, cellElement, cellIndex) {
    flkty.playPlayer();
});`

**Comment by marcellosa** [comment]
> I just wanted it to stop when you hold or drag the mouse then continue with the animation
> this helps me
> `flkty.on('dragEnd', function(event, pointer, cellElement, cellIndex) { flkty.playPlayer(); });`

Thank you, where do I paste that code?  Thanks a lot

**Comment by niallmc1995** [comment]
Here is a simple way to select the individual sliders that you want your slider to scroll after click.

I had a banner slider on the top of the page,
I didn't want it to stop rotating when a user clicked or dragged the slides, 
I wanted it to autoplay even if it was clicked or dragged, 
I fixed it with the following jquery:

```

// this part is selecting the id (#banner-carousel) which I placed on the banner slider itself and it is setting the autoplay speed to a one second, can be changed to however long.
var $carousel = $('#banner-carousel').flickity({
    autoPlay: 1000
});

//this part is basically saying "if the cell/slide is clicked, then autoplay the player anyway and do not stop"
$(document).ready(function() {
    $('.carousel-cell-image').on('click', function() {
        $carousel.flickity('playPlayer');
    });
//this part here is basically saying "if the cell/slide is dragged, then autoplay the player anyway and do not stop"
    $carousel.on('dragStart.flickity', function() {
        $carousel.flickity('playPlayer');
    });
});
```

**Comment by mrspence** [comment]
+1 

This is the third project I'm on where I've needed to create a work around - there are edge cases where you want the user to advance a slide but then continue autoplaying _because_ no content inside is interactable.

**Comment by Aditya-Raj-Tiwari** [comment]
Try this:
* First declare your carousel:
` var $carousel_1 = $('#wrap .carousel').flickity({})`
* Then declare a function to be called on state change
`function stateResume() {
      $carousel_1.flickity('playPlayer')
        }`
* Lastly call the function on settle 
`  $carousel_1.on('settle.flickity', stateResume);`

**Comment by smity81435** [comment]
What worked for me was:
```
  flkty.on('staticClick', function() {
    flkty.unPausePlayer();
  });
  ```

**Comment by OscarGodson** [comment]
I do wish `pauseOnClick: false` was an option but another option, if your Flickity element is purely for visuals and not something a user must copy paste from or interact with you can use CSS:

```css
.main-carousel {
  pointer-events: none;
}
```

This works in my case because its being used for eye candy but, unfortunately, if you need to interact with it you'll need a JS solution as mentioned above.

Recommendation is the one linked to above but I'd restore the original method for future use cases

```js
// Store backup of the original method to restore later
const stopPlayerOriginal = Flickity.prototype.stopPlayer;

// Overwrite stopPlayer method since we don't want clicking to stop it
Flickity.prototype.stopPlayer = function() {
  this.player.stop();
  setTimeout( () => {
    this.player.play();
  }, autoPlayTime)
};

new Flickity('.main-carousel', {
  // ...
});

// Restore the original method for others
Flickity.prototype.stopPlayer = stopPlayerOriginal;
```
