### ISSUE TITLE
Flickity with lazy load

### ISSUE THREAD

**Issue by niros44** [metafizzy/flickity#308]
Well i read all post here but did not find my answer...
When setting my image - can't i set it with a relative path (as it is set in my app)?
Please any help will be more than helpful.

Ps
I tried to set  my image
<img class="gallery-cell-image" src="/images/ddd.jpg"......
Or
Data-src.....
Or 
Data-flickity-lazyload....
Onother ps...
Usage mobile apps 
None of them work with relative path

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by niros44** [comment]
So Hope i am in the right way :)

Html 

 <div class="ui-content" data-role="content">
            <p>Our Channels</p>

            
            <div class="gallery js-flickity" data-flickity-options='{ "lazyLoad": 2, "initialIndex": 2 ,"wrapAround": true, "freeScroll": true ,"contain": true,"prevNextButtons": false,"pageDots": false}'>
                <div class="gallery-cell">
                    <img class="gallery-cell-image"
                        srcset="\images\10.png" alt="tulip" />
                </div>
                <div class="gallery-cell">
                    <img class="gallery-cell-image"
                         data-src="images/g.jpg" alt="grapes" />
                </div>
                <div class="gallery-cell">
                    <img class="gallery-cell-image" src="/images/g.jpg"  />
                </div>
            </div>
        </div>

----------------------------------------------------------
javascript is referanced on top css too.

**Comment by niros44** [comment]
Html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IsraeliTV</title>
    
    <link href="css/JqueryMobile1.4.5.min.css" rel="stylesheet" />
    <script src="scripts/Jquery1.11.3.min.js"></script>
    <script src="scripts/jquery.mobile-1.4.5.js"></script>
    
    
    <script src="scripts/flickity.js"></script>
    <link href="css/flickity.css" rel="stylesheet" />
    
    <script src="/cordova.js"></script>
    <script src="/scripts/platformOverrides.js"></script>


    
    <style class="cp-pen-styles">
        * {
            box-sizing: border-box;
        }

        body {
            font-family: sans-serif;
        }

        .gallery {
            background: #FAFAFA;
        }

        .gallery-cell {
            width: 66%;
            height: 400px;
            margin-right: 10px;
            background: #333;
        }

        .gallery-cell-image {
            display: block;
            max-height: 100%;
            margin: 0 auto;
            max-width: 100%;
            opacity: 0;
            -webkit-transition: opacity 0.4s;
            transition: opacity 0.4s;
        }

            /* fade in lazy loaded image */
            .gallery-cell-image.flickity-lazyloaded,
            .gallery-cell-image.flickity-lazyerror {
                opacity: 1;
            }
    </style>
    
</head>
<body>
    <div id="ButtonLinks"></div>

    <div data-role="page">
        <div data-role="header">
            <h1>bla bla - Home Page</h1>
            <div data-role="navbar">
                <ul>
                    <li><a href="DoRefresh()" data-icon="refresh">Refresh</a></li>
                    <li><a href="#anylink" data-icon="home">Home</a></li>
                    <li><a href="#anylink" data-icon="search">Search</a></li>
                    <li><a href="UserSettings.html" data-icon="gear">Settings</a></li>
                </ul>
            </div>
        </div>
        <div class="ui-content" data-role="content">
            <p>bla bla</p>

            
            <div class="gallery js-flickity" data-flickity-options='{ "lazyLoad": true ,"wrapAround": true, "freeScroll": true ,"contain": true,"prevNextButtons": false,"pageDots": false}'>
                <div class="gallery">
                    <div class="gallery-cell">
                        <img class="gallery-cell-image"
                             data-flickity-lazyload="images/g.jpg" />
                    </div>
                    <div class="gallery-cell">
                        <img class="gallery-cell-image"
                             data-flickity-lazyload="images/g.jpg" />
                    </div>
...........
                </div>
            </div>
        </div>

        <div data-role="footer">
            
        </div>
    </div>
</body>
</html>

**Comment by niros44** [comment]
[htmlFile.html.txt](https://github.com/metafizzy/flickity/files/93583/htmlFile.html)

**Comment by desandro** [comment]
Thanks for that. I wasn't able to reproduce this bug. lazyLoad with relative paths works. You may want to check the permissions of your images, or check that path of the image 'src' works.
