### ISSUE TITLE
AutoPlay rushes through cells when coming back to inactive browser tab

### ISSUE THREAD

**Issue by flogehring** [metafizzy/flickity#31]
I have AutoPlay and wrapAround activated.
Whenever I switch to another tab for a minute and return to my site with flickity, it seems to be rushing through the animations in order to catch up.

**Comment by nvartolomei** [comment]
Do you use latest version, looks like @desandro tried to fix it #6

**Comment by flogehring** [comment]
Yes, you're right. I hadn't seen the update. Sorry!

**Comment by loweoj** [comment]
This is still happening in version 2.
