### ISSUE TITLE
Images smaller than viewport stay at the top

### ISSUE THREAD

**Issue by stefa168** [metafizzy/flickity#312]
First of all, I must thank you for this excellent gallery.

Next, here is my problem:
When I have images that are higher than the height of the viewport they are resized (like they should). However, if I have images that are shorter, they just stay at the top of the viewport. Instead should'nt they be centered so they appear more ordinated?

Here is a pen with the issue: http://codepen.io/Stefa168/pen/qbxXPz . Just scroll to the third picture to see it

I tried solving the problem with some CSS, but I couldn't fix it.
I know that this might be a corner case, but since the images that I have to show are uploaded by my users, there might be some smaller images, or some very long images that have to be resized horizontally, reducing the height.

**Comment by desandro** [comment]
Thanks for the kind words!

You can center images with flex box CSS. See [demo on CodePen](http://codepen.io/desandro/pen/40b3b959b7e695bd2e69a86e3eae7d45/)

``` css
.gallery-cell {
  height: 100%;
  display: flex;
  align-items: center;
}
```

**Comment by stefa168** [comment]
:flushed: Thanks, I still have to learn so many things
