### ISSUE TITLE
Add container around Prev/Next/Page Dot elements

### ISSUE THREAD

**Issue by thomas-harding** [metafizzy/flickity#314]
For those implementing Flickity on fluid layouts, I think it would be most useful to have the flickity navigation elements contained in a wrapper of some sort. 

I find it cumbersome to ensure the next/prev buttons stay in line with the active banner, especially when said banner is in line with the content width. To have a wrapper to manipulate across all viewports would be most excellent :) 

Obviously if there's a way to do this already, please let me know, haha.

**Comment by desandro** [comment]
Thanks for submitting this feature request. The page dots container, previous button and next button all are contained within the gallery element you initialize Flickity with. The HTML looks like this:

``` html
<div class="gallery flickity-enabled">
  <div class="flickity-viewport">
    <div class="flickity-slider">
      <div class="gallery-cell"></div>
      ...
    </div>
  </div>
  <ol class="flickity-page-dots">
    <li class="dot"></li>
    ...
  </ol>
  <button class="flickity-prev-next-button previous"></button>
  <button class="flickity-prev-next-button next"></button>
</div>
```

If you can put together a **reduced test case** I might have a better idea of what you're trying to do.  See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
