### ISSUE TITLE
Echo Links to all slides in slideshow with numbers

### ISSUE THREAD

**Issue by buck-danny** [metafizzy/flickity#315]
Hey, i have a question:
how can i get links to skip to each slides of the slideshow?
Something like:
```     <a href#slide1>Slide 1</a>
     <a href#slide2>Slide 2</a>
     <a href#slide3>Slide 3</a>```
and so on
thanks for any help!

**Comment by desandro** [comment]
Thanks for submitting this feature request. We already have an issue open for this one. See #239
