### ISSUE TITLE
Webpack guidelines have typo

### ISSUE THREAD

**Issue by patrickbjohnson** [metafizzy/flickity#316]
In the [webpack guidelines for Flickty](http://flickity.metafizzy.co/extras.html#webpack)

```
loaders: [
      {
        test: /flickity/,
        loader: 'imports?define=>false&this=>window'
      }
    ]
```

Which throws an error due to the lack of single-quotes around `/flickity/`

Should be:
```
loaders: [
      {
        test: '/flickity/',
        loader: 'imports?define=>false&this=>window'
      }
    ]
```

**Comment by desandro** [comment]
Hi Patrick! Thanks for reporting this issue.

I wasn't able to reproduce the bug. I'm using Webpack v1.7.3 and imports-loader v0.6.5.

**Comment by patrickbjohnson** [comment]
Interesting.

I'll try to recreate tonight and shoot over the response from the CLI.

On Tue, Jan 26, 2016 at 8:37 AM, David DeSandro <notifications@github.com>
wrote:

> Hi Patrick! Thanks for reporting this issue.
>
> I wasn't able to reproduce the bug. I'm using Webpack v1.7.3 and
> imports-loader v0.6.5.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metafizzy/flickity/issues/316#issuecomment-175016449>.
>



-- 

Patrick Johnson
Front-End Developer
407.460.4813
@patrickbjohnson <https://twitter.com/patrickbjohnson>
www.pbj.me
