### ISSUE TITLE
wrapAround causing glitchy image rerender

### ISSUE THREAD

**Issue by ariroseonline** [metafizzy/flickity#317]
``` $('.items').flickity({
      cellAlign: component.get('isProviders') ? 'left' : 'center',
      prevNextButtons: true,
      pageDots: false,
      //percentPosition: false
      wrapAround: true
    }).focus();
```
![flickitybug](https://cloud.githubusercontent.com/assets/529109/12622682/80d6c77c-c4f4-11e5-8d52-35118b1c0723.gif)

This seems to occur just on the first image on either a touch scroll OR arrow key scroll

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
