### ISSUE TITLE
Flickity in modal has no height until resize

### ISSUE THREAD

**Issue by dustinhorton** [metafizzy/flickity#318]
When opening the modal, `.flickity-viewport` has a `height` of `0`:

![screen shot 2016-02-03 at 7 25 24 pm](https://cloud.githubusercontent.com/assets/378165/12801626/fa49ffc2-caab-11e5-852d-a59a8fca4921.png)

Resizing the window seems to fix the height.

[Reduced test case](http://codepen.io/dustinhorton/pen/QyVvXM)

**Comment by desandro** [comment]
Thanks for reporting this issue. The problem is that Flickity needs to know the size of its content to lay it out. Since the content is hidden in the modal, it does not have any size. One way to resolve this is to trigger [`resize`](http://flickity.metafizzy.co/api.html#resize) once the content is visible. You can do this with Bootstrap Modal `shown.bs.modal` event. See demo on CodePen: http://codepen.io/desandro/pen/LGJLLE

``` js
// show carousel after modal shown
$('#myModal').on( 'shown.bs.modal', function( event ) {
  $('.gallery').flickity('resize');
});
```

**Comment by dustinhorton** [comment]
@desandro That makes complete sense. Thought I'd tried something similar & had issues (not initializing Flickity until the modal is shown), but that seems to mostly work fine. One issue I did notice is on first `mousedown`, the window jumps: [Reduced test case](http://codepen.io/dustinhorton/pen/XXPgVw)

**Comment by desandro** [comment]
See https://github.com/metafizzy/flickity/issues/76#issuecomment-77430660 about the window jump

> Thanks for reporting this! This behavior is actually a feature of keyboard accessibility. By clicking/tapping on a gallery, it adds `focus` to its element. This will jump the scroll so that element is completely in the viewport.
> 
> If this behavior is really bugging you, you can disable it with [`accessibility: false`](http://flickity.metafizzy.co/options.html#accessibility) -- which I don't recommend because accessibility is a wonderful thing.

**Comment by dustinhorton** [comment]
:+1:

**Comment by buayvets** [comment]
Thank you for your answers.

**Comment by KoMiToRaY** [comment]
thx you for answers ! :+1:

**Comment by hanaya26** [comment]
When opening the bootrap modal eveni am having the same issue of height ,
i have checked it on codepen.io  and tried that but the issue still remains the same

**Comment by KoMiToRaY** [comment]
@hanaya26 try with this
.flickity('reloadCells');

and add the option : 
imagesLoaded: true

it works for me.

**Comment by huykon** [comment]
How I can call resize in data-flickity ?

**Comment by desandro** [comment]
@huykon Use [`Flickity.data()`](https://flickity.metafizzy.co/api.html#flickity-data)

> Flickity.data() is useful for getting the Flickity instance in JavaScript, after it has been initalized in HTML.

``` html
<!-- init Flickity in HTML -->
<div class="main-carousel" data-flickity>...</div>
```

``` js
// jQuery
// pass in the element, $element[0], not the jQuery object
var flkty = Flickity.data( $('.main-carousel')[0] )
// vanilla JS
var carousel = document.querySelector('.main-carousel')
var flkty = Flickity.data( carousel )
// using a selector string
var flkty = Flickity.data('.main-carousel')
```

**Comment by huykon** [comment]
Thank @desandro for your answer. I tried your JS script but it stills not working. This is my code:
`<ul class="nav nav-tabs vi-nav-tabs list-tab-4">
	<li role="presentation">
		<a href="#vegetable_0" aria-controls="vegetable_0" role="tab" data-toggle="tab" aria-expanded="false">Vegetable</a></li>
	<li role="presentation">
		<a href="#fruit_1" aria-controls="fruit_1" role="tab" data-toggle="tab" aria-expanded="true">Fruit</a>
	</li>
</ul>
<div class="tab-content">
	<div class="tab-pane" id="vegetable_0" role="tabpanel" data-flickity='{"imagesLoaded": true, "groupCells": "100%", "dragThreshold" : 3, "adaptiveHeight": true, "cellAlign": "left","wrapAround": true,"prevNextButtons": true,"percentPosition": true,"pageDots": false, "rightToLeft": false, "autoPlay" : false}'>
		content 1
	</div>
	<div class="tab-pane" id="fruit_1" role="tabpanel" data-flickity='{"imagesLoaded": true, "groupCells": "100%", "dragThreshold" : 3, "adaptiveHeight": true, "cellAlign": "left","wrapAround": true,"prevNextButtons": true,"percentPosition": true,"pageDots": false, "rightToLeft": false, "autoPlay" : false}'>
		content 2
	</div>
</div>`

**Comment by desandro** [comment]
@huykon If you can provide a **reduced test case**, please open a new issue so I can take a look. 
 See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by huykon** [comment]
@desandro [Reduced test case](https://codepen.io/huykon225/pen/ZJLOMR)
Please check it out to help me. Thank you!

**Comment by desandro** [comment]
@huykon See demo https://codepen.io/desandro/pen/rzjEZK

The same principle was used, triggering `resize` on `shown.bs.tabs`

``` js
$('.nav-tabs').on( 'shown.bs.tab', 'a', function( event ) {
  // get tab pane
  var selector = event.target.getAttribute('href');
  // trigger resize on tab pane
  $( selector ).flickity('resize');
});
```

**Comment by huykon** [comment]
@desandro you are awesome. Thank you very much

**Comment by martezconner** [comment]
Any news on the status of this fix. My project is currently having this same issue for mobile where the height becomes 0

**Comment by huykon** [comment]
@martezconner you can check the code of @desandro in previous answer.
Best regard.
