### ISSUE TITLE
Resume autoPlay after hover off

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#32]
I got a request to resume `autoPlay` after the user have hovered off the element, regardless if the user selected a cell while hovered on.

I'll need to provide code and an example.

**Comment by iversontb** [comment]
I had done it. I changed stop function in your code and make it work like a pause function.

**Comment by pavethiran** [comment]
It would be great if you could deactivate the pause on hover.

**Comment by zslabs** [comment]
+1

**Comment by desandro** [comment]
I feel this is an accessibility issue. After the user has made an explicit interaction with carousel, the carousel shouldn't act without their interaction.
