### ISSUE TITLE
Flickity + Magnific popup issue 

### ISSUE THREAD

**Issue by DeoThemes** [metafizzy/flickity#321]
Hello.

I'm trying to make magnific popup working with flickity slider. But when I drag the slide magnific popup shoots up. I found the solution how to prevent this behavior with images, but can't find how to make it work with videos.

Here is CodePen link - http://codepen.io/DeoThemes/pen/PZWjNy

Looking forward to hear from you.
Thanks for great plugin.

**Comment by desandro** [comment]
Here's how I would do it. Use `<a>` to store source content for popups. Map `<a>` to the Magnific popup `items`. Then use `$.magnificPopup.open` on `staticClick`. At no point use `$('...').magnificPopup()`. Rely on Flickity's `staticClick` event instead.  See [demo on CodePen](http://codepen.io/desandro/pen/dc2f958521e64e3d39fd36a5c33d3375/)

``` js
// Define flickity carousel
var $gallery = $('.gallery').flickity({
  // options..
});

var popupItems = $.map( $gallery.find('.gallery-cell a'), function( link ) {
  return {
    src: link.href,
    type: $(link).attr('data-popup-type') || 'image'
  }
});

$gallery.on('staticClick', function(event, pointer, cellElement, cellIndex) {
  if (!cellElement) {
    return;
  }
  $.magnificPopup.open({
    items: popupItems,
    gallery: {
      enabled: true
    },
    callbacks: {
      open: function () {
        $.magnificPopup.instance.goTo( cellIndex );
      }
    }
  });
});

// prevent links from opening
$gallery.on( 'click', 'a', function(event) {
  event.preventDefault();
});

```

**Comment by DeoThemes** [comment]
It's a great solution, works like a charm. Thanks for a fast reply.

**Comment by xstortionist** [comment]
I copied this code directly from the codepen but when I click on the items within the carousel, it never initializes manificPopup.

`.gallery
						
						.gallery-cell

							a(href="assets/img/carousel/1.jpg")
								img(src="assets/img/carousel/1.jpg")

						.gallery-cell
							
							a(href="assets/img/carousel/2.jpg")
								img(src="assets/img/carousel/2.jpg")

						.gallery-cell
							
							a(href="assets/img/carousel/1.jpg")
								img(src="assets/img/carousel/1.jpg")

						.gallery-cell
							
							a(href="assets/img/carousel/2.jpg")
								img(src="assets/img/carousel/2.jpg")`

`$(document).ready(function() {

  // Define flickity carousel
  var $gallery = $('.gallery').flickity({
    wrapAround: true,
    contain: true,
    percentPosition: true,
    lazyLoad: 1,
    selectedAttraction : 0.1,
    friction: 0.6,
  });

  var popupItems = $.map( $gallery.find('.gallery-cell a'), function( link ) {
    return {
      src: link.href,
      type: $(link).attr('data-popup-type') || 'image'
    }
  });
  
  $gallery.on('staticClick', function(event, pointer, cellElement, cellIndex) {
    if (!cellElement) {
      return;
    }
    $.magnificPopup.open({
      items: popupItems,
      gallery: {
        enabled: true
      },
      callbacks: {
        open: function () {
          $.magnificPopup.instance.goTo( cellIndex );
        }
      }
    });
  });

  // prevent links from opening
  $gallery.on( 'click', 'a', function(event) {
    event.preventDefault();
  });
  
});

}(jQuery));`

**Comment by xstortionist** [comment]
This doesn't work on mobile devices. I ran some debugging and can't pinpoint where the issue may be happening. When you tap on an image, it opens the wrong image. Sometimes when you tap nothing loads at all. Almost like it's firing twice.
