### ISSUE TITLE
Need multiple clicks to go back on AsNavFor

### ISSUE THREAD

**Issue by musdy** [metafizzy/flickity#322]
I have an AsNavFor carousel and when you drag to the last element, (let's assume you have 5 items per view in your carousel), you need to click 5 times to the previous button to go to the previous state. You can even see this behaviour on the example on the website:

http://flickity.metafizzy.co/options.html#asnavfor

Drag the asNavFor nav to the last item, then try to click on the previous button. You at least need 2 clicks to go one step back.

Any recommendations on how to fix this @desandro ? 
Thanks again.

- M

**Comment by desandro** [comment]
Thanks for reporting this issue. See https://github.com/metafizzy/flickity/issues/289#issuecomment-157488885 for discussion.
