### ISSUE TITLE
figure and figcaption how to use as a sole gallery-cell

### ISSUE THREAD

**Issue by feperrella** [metafizzy/flickity#327]
Hi, i wanted to place tags like this:

`<figure class="gallery-cell">
    <img src alt />
    <figcaption>image caption text</figcaption>
</figure>`

But some erros occurs with the first and last images, if they have caption, in most cases, like the cell not responding to the correct width of the image, and going 100% wide...

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
