### ISSUE TITLE
jQuery events not firing with Browserify/Webpack

### ISSUE THREAD

**Issue by jasonwbullok** [metafizzy/flickity#329]
I used your instructions to install Flickity as a jQuery plugin with Browersify, but the Flickity specific events seem to not fire once I have. I wasn't aware of a way to build an online test case with browersify so I created a barebones example at the following link:

https://db.tt/QQ1LlQx4

**Comment by desandro** [comment]
Thanks for reporting this issue and test case. This is indeed a bug.

Because of how jQuery is encapsulated when used with Browserify, I'm sorry to say there's no quick fix. I'm going to have to develop a solution with jQuery Bridget and Flickity.

**Comment by ZaDarkSide** [comment]
:+1:

**Comment by desandro** [comment]
> Looks like window.jQuery is not available with jQuery v3, when bundled with Webpack. I am adding a utility function so you can make jQuery available for Flickity with Webpack.

**Comment by desandro** [comment]
Added documentation for [`Flickity.setJQuery()`](https://flickity.metafizzy.co/api.html#flickity-setjquery) to add jQuery events with Webpack/Browsersify.
