### ISSUE TITLE
Allow continuous scroll/movement on freeScroll/wrapAround carousel

### ISSUE THREAD

**Issue by sprintstar** [metafizzy/flickity#330]
I have a requirement for a freeScroll / wrapAound carousel to move continuously.  Is this attainable? I'm thinking making friction 0 and triggering a drag?

**Comment by sprintstar** [comment]
Damn, just would this duplicate request. https://github.com/metafizzy/flickity/issues/77

Seems like it would be easy to compliment though, I just need an 'initial speed' option.

**Comment by desandro** [comment]
As you've discovered, this feature request has already been discussed in #77.

> I'm going to stick with my position and decline this feature request. The autoPlay feature is a suitable solution. Adding another type of auto-motion behavior is not worth the cost of additional complexity.
