### ISSUE TITLE
Images not displayed correctly on init

### ISSUE THREAD

**Issue by warreb1** [metafizzy/flickity#331]
![screen shot 2016-03-03 at 14 55 57](https://cloud.githubusercontent.com/assets/2844328/13496383/297fdefa-e150-11e5-9b29-d62bfda9eea7.png)

Is this something that can be fixed? The carousel is initiated trough the html data-flickity-options and "js-flickity" class so I presume that should work out of the box?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by warreb1** [comment]
My apologies for not following up on this. I changed the carousel from html initiation to js initiation and the  issue didn't appear anymore.
