### ISSUE TITLE
Focus() not working on html initiated carousel

### ISSUE THREAD

**Issue by warreb1** [metafizzy/flickity#332]
`Uncaught TypeError: galmodalcarousel.focus is not a function`

Is always returned when trying to put focus onto the carousel. Note that the carousel is initiated trough html.

`var galmodalcarousel = Flickity.data('.modal--gallery__carousel'); 
 galmodalcarousel.focus();`

**Comment by warreb1** [comment]
http://codepen.io/anon/pen/zqvNMP
And a mini-pen!

**Comment by desandro** [comment]
Thanks for reporting this issue. If you want to set initial focus on the carousel, then you'll have to initialize Flickity with JavaScript, not in HTML. We need Flickity to be initialized first then we can focus it. See demo http://codepen.io/desandro/pen/bc24ef292ce6e341c1c2aa06b45c9faf

``` js
var galmodalcarousel = document.querySelector('.modal--gallery__carousel'); 
// init Flickity
var flkty = new Flickity( galmodalcarousel )
// set initial focus
galmodalcarousel.focus();
```
