### ISSUE TITLE
Low friction - Attraction - How to be attracted always forward ?

### ISSUE THREAD

**Issue by adrienlamotte** [metafizzy/flickity#333]
Hi !

I'd like to know if it could be possible to always be attracted forward during the slide animation (**with a low friction**) ? For exemple if I drag the slider to the left, I'd like the animation always slide left, and remove the "back" in the end of the animation witch go to the right (and vice versa).

Here is a codepen : http://codepen.io/anon/pen/xVwooY?editors=1100

I tried to play with selectedAttraction, friction, freeScroll... But I had no luck.

Don't know if my question is clear ?

Anyway, thanks for your work :)

**Comment by desandro** [comment]
Thanks for this feature request. Sorry, no Flickity does not support this feature. There may be some valid use cases - like maintaining state in a step-by-step wizard. But I don't feel there's enough use cases to add this feature. Thanks so much for your input!

**Comment by adrienlamotte** [comment]
Too bad, but thanks for you answer. 

Well it's not really about use cases, but more about animation control ;-)
