### ISSUE TITLE
Big size, optimize

### ISSUE THREAD

**Issue by saintroma** [metafizzy/flickity#334]
The large size of the script . And the need to optimize ( accelerate ) the rendering

**Comment by desandro** [comment]
Thanks for reporting this issue. Flickity's source is modular, so you can build a custom version with only the parts you require.  See [Making features independent with internal events blog post for details](http://metafizzy.co/blog/making-features-independent-with-internal-events/). Take a look at [index.js](https://github.com/metafizzy/flickity/blob/v1.1.2/js/index.js) for the files that get packaged together.

**Comment by jurijc** [comment]
Hello desandro, is there are easy way to use included npm scripts to build custom version?

I have noticed that npm run-script bundleJs somehow doesn't create flickity.pkgd.js is it intended?
