### ISSUE TITLE
How to use wrapAround + asNavFor

### ISSUE THREAD

**Issue by renestalder** [metafizzy/flickity#335]
I have two Flickity sliders. The second is used to animate the background, theming the environment. So the second slider is initialized with asNavFor.

The problem is, the first slider uses wrapAround. Also the second slider is set to wrapAround. But unfortunately, it seems that the second slider, which sets the option asNavFor is going to be reset to the first slide instead of wrap around together with the first slider.

You can checkout a demo here. Slide right to the 5th slide and then continue sliding. The background will come up from the wrong side because the background slider starts with index 0.
http://codepen.io/renestalder/live/dMXpoJ

The code:
http://codepen.io/renestalder/pen/dMXpoJ

Is this a bug or indented to work like this?
Is there a workaround or other solution to let the background slider also wrap around?

**Comment by desandro** [comment]
Thanks for reporting this issue. I believe this issue could be resolved by #113. I'm closing this issue here, so we can track along there.
