### ISSUE TITLE
Pause video if it is not in currently shown cell

### ISSUE THREAD

**Issue by IljaDaderko** [metafizzy/flickity#339]
I am having issues with autoplaying looping videos harming performance of the page if there are several present. Essentially a fix would be to pause video when it is not in currently selected cell (as users won't see it) and unpouse it if related cell becomes selected.

i am having issues figuring out how to achieve this within flickity. i.e. on settle get all cells that are not currently selected, check if they have video tag in them, if yes pause that video tag.

**Comment by desandro** [comment]
I could look something like this

``` js
// get Flickity instance
var flkty = $carousel.data('flickity');
// get cells
var $cells = $carousel.find('.carousel-cell');

$carousel.on( 'settle', function() {
  $cells.forEach( function( i, cell ) {
    // do not unpause selected cell
    if ( cell == flkty.selectedElement ) {
      return;
    }
    // you'll have to edit this code for your project
    // not sure how you're handling video
    var $video = $(cell).find('video');
    if ( $video.length ) {
      // pause video here
    }
  });
});
```

**Comment by IljaDaderko** [comment]
@desandro tried figuring out how to implement this via vanilla javascript, how can I select carousel-cells via it, as looking at page markup in inspector I can't find these classes, it follows structure like `flickity-viewport > flickity-slider`

**Comment by desandro** [comment]
Here's vanilla JS code to start with. 

``` js
flkty.on( 'settle', function() {
  // cells is an array of objects
  flkty.cells.forEach( function( cell ) {
    // each cell has .element
    // do not unpause selected cell
    if ( cell.element == flkty.selectedElement ) {
      return;
    }
    // you'll have to edit this code for your project
    // not sure how you're handling video
    var video = cell.element.querySelector('video');
    if ( video ) {
      // pause video here
    }
  });
});
```

This is not the exact code you need, but a starter template code that you should adjust for your own implementation. How you implement this code is up to you.
