### ISSUE TITLE
Prefixed events

### ISSUE THREAD

**Issue by pavethiran** [metafizzy/flickity#34]
I think it might be a good practice to implement the events with a preset like "Flickity.select".

**Comment by desandro** [comment]
[jQuery events are namespaced with `.flickity`](http://flickity.metafizzy.co/api.html#jquery-event-binding). Use this namespace to specify Flickity events.

``` js
$gallery.on( 'select.flickity', function() {
  // Flickity gallery cell select event
});

$gallery.on( 'select', function() {
  // may be text select event
  // or Flickity gallery cell select event
});
```
