### ISSUE TITLE
Marginless Cells

### ISSUE THREAD

**Issue by smed** [metafizzy/flickity#340]
In the following example: http://codepen.io/anon/pen/LNxMXb the margin for .gallery-cell is set to zero, however the margin exists until a window resize occurs then it disappears. How can I initialize the slider so that the cells are marginless from the start?

**Comment by desandro** [comment]
The issue is most likely the browser scroll bar changing the size of page. You can force a scrollbar with 

``` css
html { overflow-y: scroll; }
```

See demo http://codepen.io/desandro/pen/701154ac602716e26b3d580ee656ea46/
