### ISSUE TITLE
Image disappearing while scrolling

### ISSUE THREAD

**Issue by zarecki75** [metafizzy/flickity#341]
Hi there!  I have Flickity installed on multiple places in my site and I can't figure out why when I'm scrolling though, the image on the left disappears.  I'd appreciate any assistance.

Here's the URL and I've attached files:  http://intwinemarketing.com/clients/glasstech/Product-Gallery.html
[scripts.zip](https://github.com/metafizzy/flickity/files/181602/scripts.zip)

Thank you,
Shawn

**Comment by desandro** [comment]
Thanks for reporting this issue. I don't believe I'm able to see the issue on the page. But it sounds like you're running into the wrapAround issue where content width is smaller than the carousel width. Is that correct? If so, see #95 for a discussion on a feature request.

**Comment by zarecki75** [comment]
David, thank you for your prompt attention to my submission.  I have
figured out what the issue was and it was on my end.  I only had 6 images
in the carousel - and it needed 7 for the wrap around to work.  No issue at
all with Flickity - all my fault.  I have to tell you, I love this
carousel.  Thanks for creating it!  And thanks again for your attention.
Much appreciated!  ~Shawn
