### ISSUE TITLE
Sliding unexpected direction when selecting first or last slide with click

### ISSUE THREAD

**Issue by JSW888** [metafizzy/flickity#345]
I'm not sure that this is a bug necessarily, but it's unwanted behavior. This occurs when using wrapAround with a function to select a slide when clicked. If transitioning from the last slide to first, or vice versa, it cycles through every slide, rather than just going directly from last->first as it will with keyboard navigation or dragging.

So for example, if you have 5 slides, with the 5th selected and click the 1st, it will go 5, 4, 3, 2, 1, rather than 5, 1.

Here's a reduced test case of the issue - http://codepen.io/Josh88/pen/NNjQmX

Of course setting animation to false on select will solve the issue, but that's not ideal. Any thoughts on how to resolve this?

**Comment by desandro** [comment]
Thanks for reporting this issue. We already have another issue opened for this. See #113
