### ISSUE TITLE
Free Scroll and cellSelect Event (image caption demo)

### ISSUE THREAD

**Issue by jeffpannone** [metafizzy/flickity#346]
If freeScroll is true, cellSelect Event does not fire on page load. 

**Test case:** http://codepen.io/jeffpannone/pen/rewvGK

**Comment by desandro** [comment]
True, this is a quirk with `freeScroll`. You can resolve this issue by triggering `select` after adding the `cellSelect` listener. See demo http://codepen.io/desandro/pen/f8abb46892b55c8452f05f71d9264f84/

``` js
$gallery.on( 'cellSelect', function() {
  // set image caption using img's alt
  $caption.text( flkty.selectedElement.alt )
});

$gallery.flickity( 'select', 0 );
```

**Comment by jeffpannone** [comment]
That did the trick. Thank you much!
