### ISSUE TITLE
 asNavFor exception

### ISSUE THREAD

**Issue by hschaefer123** [metafizzy/flickity#347]
Version:   Flickity PACKAGED v1.2.0

I am using the option
asNavFor
to combine/sync to flickity instances the way seen in the demo.

The problem is, that i am using OpenUI5 to dynamically render the carousel content. Internally
the object will be instantiated while the content divs are not rendered at this moment (async behavior).

In such a case, both instanced will be created, but the content is still empty. The seconde Instande (asNavFor) will now try to select the first content and this leads to an error

flickity.pkgd.min.js:12Uncaught TypeError: Cannot read property 'matches' of nulle @ flickity.pkgd.min.js:12n.getParent @ flickity.pkgd.min.js:12h.getParentCell @ flickity.pkgd.min.js:12s.complete @ flickity.pkgd.min.js:13s.onload @ flickity.pkgd.min.js:13n.handleEvent @ flickity.pkgd.min.js:12

In this case, the correct behavior would be to defer the setSelectedValue after rendering of the needed DOM elements (especially because OpenSAP triggers rerending on DOM nodes if data changes.
If this would be to complicated, it would be nice to catch the hard error and replace by a warning.

If there is a special issue report for paying customers please let me know, because we have bought a developer licence for flickity.

Regards Holger

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by hschaefer123** [comment]
Hi Desandro,
you can reproduce the bug in our
https://shop.bonvendo.de
demo!

You can freely selfregistrate and login, please click a product for details and the details screen contains the detailimage and the gallery used asNavFor.

Sorry for inconcenience, but otherwise the issue would be hard to demonstrate because of the whole framework dependency around. We also use isotope you the app maybe is also interesting to see ;-)

Regards Holger

**Comment by desandro** [comment]
I appreciate you providing a live link, but in order for me to investigate this bug, I'll need a **reduced test case** that demonstrates the issue.

Can you initialize the galleries after their DOM has been set?
