### ISSUE TITLE
wrapAround with less than X images

### ISSUE THREAD

**Issue by warreb1** [metafizzy/flickity#348]
Hi!

I came across the following issue. In one of our projects we have a flickity carousel that can be ether 4 images or 30 (community driven uploads). When there are only 4 (or less) images the "wrapAround"  doesn't function very well. A test case is added.

Reduced test: http://codepen.io/studiotwist/pen/mPMpzy

Actual image: https://www.dropbox.com/s/kten2agfhwz5m3b/Screenshot%202016-03-30%2014.01.49.png?dl=0

**Comment by desandro** [comment]
Thanks for reporting this issue. See #95
