### ISSUE TITLE
Custom class names

### ISSUE THREAD

**Issue by demrks** [metafizzy/flickity#352]
I think, there should be an option that allows users to set custom class names, mostly for integrating with an existing design system.

I know that there is a `cellSelector` option right now, but probably there should be more options like `viewportSelector` (defaults to `.flickity-viewport`), `enabledSelector`, `dotsSelector`, `prevButtonSelector`, `nextButtonSelector` and so on.

If you want and it helps, I can also create a pull request.

**Comment by desandro** [comment]
Thank you for this feature request! I could see how this could be useful, but I don't feel there will be other users who are that interested in this feature.   Sorry, but I'll pass on this feature request.

**Comment by demrks** [comment]
I see... since you see how this could be useful, can i offer you to create a pull request for this feature so you don't have to spend any time on this yourself? 

I agree that probably not many users need this feature, but since it doesn't really have any downsides (no additional code, just variables instead of strings), the users that need or want this too, can use it. Just asking... one last try :)

**Comment by aaronstezycki** [comment]
Personally, I'm fairly interested in this feature. It could make progressive enhancement easy to implement with custom classes.
