### ISSUE TITLE
Click events on the prev/next buttons

### ISSUE THREAD

**Issue by fabiansalamo** [metafizzy/flickity#358]
Hello, I have a simple question, is there any way to capture click events on the prev/next buttons?

I have to animate elements inside each slide as they appear, and I can't seem to figure this out.

Thanks!

**Comment by desandro** [comment]
I recommend using the [`cellSelect` event](http://flickity.metafizzy.co/api.html#cellselect) for this kind of functionality.

**Comment by fabiansalamo** [comment]
Thank you very much for your time, I've tried and the event triggers when
needed, but I guess I'm still doing something wrond.

I have my carousel initialized by HTML :

<div id="carousel" class="main-carousel js-flickity" style="height: 515px;"
data-flickity-options='{ "wrapAround": true}'>
<div class="carousel-cell">

but when I try to get the data I get Undefined,

var $carousel = $('.main-carousel');
// get instance
var flkty = Flickity.data('.main-carousel')
console.log(flkty);

Can you please guide me on how to get the cell inner html?

Thanks in advance!

**Comment by desandro** [comment]
Since you are using javascript, I recommend initializing Flickity only in JavaScript, and not in HTML. Remove `js-flickity` and `data-flickity-options`.

``` js
var $carousel = $('.main-carousel').flickity({
  wrapAround: true
});
// get instance
var flkty = Flickity.data('.main-carousel')
console.log(flkty);
```

**Comment by fabiansalamo** [comment]
David, thank you very much for your answer, I did as you told me and it
works just fine. Thank you very much!

**Comment by iamricky** [comment]
@desandro  It seems like `Flickity.data` doesn't work if Flickity is initialized in the HTML. I've run into the same issue, where `Flickity.data` returns undefined when `data-flickity` is used; This happens whether I use the DOM element or the selector string. In my case, I can't move this to javascript.

**Comment by iamricky** [comment]
I've discovered that `Flickity.data` works, if a `setTimeout` is used. Not ideal but I can work with it.
