### ISSUE TITLE
Including Flickity with RequireJS in Magento 2

### ISSUE THREAD

**Issue by jaystewart** [metafizzy/flickity#359]
Hello,

I have added the requirejs config in Magento 2:

```
var config = {
    map: {
        '*': {
            'flickity': 'Yeon_Theme/js/vendor/flickity/flickity.pkgd.min'
        }
    }
};
```

I am then including flickity on the page with:

```
    requirejs( [
        'flickity'
    ], function( Flickity ) {
        var flickity = new Flickity( '.hangers', {});
    });
```

However the browser is then requesting path .../flickity.pkgd.min/js/index.js which is not a file.

Does anyone have any idea why flickity is requesting ...../js/index.js?

Thanks

**Comment by desandro** [comment]
`js/index.js` is the main file in Flickity's [`package.json`](https://github.com/metafizzy/flickity/blob/v1.2.1/package.json). It appears that your config only adds that path, rather than overwriting the `main` file its looking for.

**Comment by zengoma** [comment]
Hi, I see that this issue has been closed, I am experiencing the exact same issue. Jay, were you able to finally solve this?

**Comment by gcrane7** [comment]
I am also having this issue. I would be interested if anyone came up with a solution.

**Comment by zengoma** [comment]
I've come up with a temporary hack, it's not all that eloquent but I am physically including these [source files](https://github.com/metafizzy/flickity/tree/master/js) in my module at this path: view/frontend/web/js/flickity.pkgd/js.
