### ISSUE TITLE
Vertical slider? 

### ISSUE THREAD

**Issue by nodkrot** [metafizzy/flickity#36]
Will this feature come in the future?

**Comment by desandro** [comment]
My take is that vertical scrolling is an anti-pattern. A vertical slider provides little value to the user.  If you need a vertical scroller, then you might as well have content laid out vertically in a page. If you need a separated vertical-scrolling content area, then use `overflow-y: scroll`.

But I may be persuaded otherwise. **+1** or **subscribe** to this issue if you would like see vertical slider feature added to Flickity.

**Comment by madebydominick** [comment]
Only use case I can see for a vertical slider is to build something like @peachananr's [One Page Scroll](https://github.com/peachananr/onepage-scroll). Other than that, definitely agreed with @desandro in regards to it being an anti-pattern.

**Comment by desandro** [comment]
Reopening for others to chime in.

**Comment by kamaal-** [comment]
+1

**Comment by lunarose23** [comment]
+1

**Comment by michaelwoodruff** [comment]
I tend to agree that vertical slider is an anti-pattern, although I have had several clients request this functionality.

**Comment by zslabs** [comment]
Agree this is a bit odd when something like a vertical scroll could handle it.

**Comment by silvenon** [comment]
:+1: I frequently need this for [this](http://www.thepetedesign.com/demos/onepage_scroll_demo.html) kind of layouts.

**Comment by egr103** [comment]
+1

**Comment by pasqualevitiello** [comment]
+1

**Comment by pawlikdoc** [comment]
I want to have standard flickity gallery with vertical navigation gallery for it.
+1

**Comment by desandro** [comment]
I'm going to stick to my guns. Do not use carousels for vertical content. Use a normal scrollable area with `overflow-y: scroll`. Closing this issue.

**Comment by daltonrooney** [comment]
This is a bummer, as I'm already using Flickity on a site for a horizontal carousel and now I have to load up a separate script for the vertical carousel. I agree with you that a scrollable area with overflow is preferable in some cases, but in the case where you're using one carousel to control another carousel (like a playlist for a video slider [as in this example](http://dimsemenov.com/plugins/royal-slider/video-gallery/)) a stepped navigation is totally appropriate. If the controller carousel happens to be vertical to work with a particular layout, I don't consider that an anti-pattern.

**Comment by bbnnt** [comment]
From a technical point of view this is an antipattern for sure.
But if you look at it from a "scene" point of view, then that does not matters anymore. i mean "scene"when the whole things happen "in-viewport", talking about webgl stuff, threejs, etc those kind of thing; powerpoint-like presentations
most of photographers / designers will also prefer fitted slides, and often want it to move vertically
You'll just reach loads more use cases. Your plugin just kicks-asses (seriously, unanimously the best one),  so well the devs having to use the existing bloated vertical sliders would be more than just happy

**Comment by cybentizen** [comment]
+1
This is the only slider I found supporting the RTL completely. I'm working on Arabic website and comparatively it works best but one thing that I need in this plugin is Vertical scrolling.

**Comment by Suven** [comment]
One more argument for vertical scrolling:

It is not an antipattern in scenarios where you either

- have a document with an height of 100vh (you don't conflict with the normal scrolling then)
- or want to create a component which is quite small

scrolling vertical would allow to create something like the spinning selector users already know from iOS:

![spinner](https://d13yacurqjgara.cloudfront.net/users/35381/screenshots/1179985/ios7_datepicker.png)

**Comment by nboliver** [comment]
Vertical option could also be useful in combination with the `asNavFor` option. Main carousel is horizontal, navigation is on the side and vertical.

**Comment by prdolmos** [comment]
I have to do the same thing nboliver just mentioned. Since `asNavFor` is the only option we have for thumbnails, and vertical thumbnails are very common, vertical sliders make sense in Flickity's case.

**Comment by pawlikdoc** [comment]
http://domvesta.ru/catalog/svadebnye-platya/leonella/
Please, look at the website I did year ago, and kind of implementation of what I sought in this thread.

**Comment by kimek** [comment]
I just don't get this anti-pattern. Why we cannot implement vertical align ??

@desandro You've said 'My take is that vertical scrolling is an anti-pattern', but does the horizontal-slider isn't also anti-pattern ? Slider should move slides without direction 'on top of it'. Keeping this direction of thinking we should scrap horizontal too. Am I right ? o.O? Ps. Love you slider !

**Comment by desandro** [comment]
You can make a custom vertical navigation with jQuery. See demo http://codepen.io/desandro/pen/dMjbjR

Thanks for all your feedback. Straight up: Flickity will never support vertical scrolling. It's too much code for too little benefit. Features like vertical thumbnail navigation do not have to be built into Flickity directly. You can leverage [Flickity's well documented API](http://flickity.metafizzy.co/api.html) and [many demos]() to create these kind of add-on features.
