### ISSUE TITLE
Tapping previous/next button on iOS jumps 2 cells

### ISSUE THREAD

**Issue by kimek** [metafizzy/flickity#363]
On tap next/prev button slider goes to second slide from selected one.
All galleries.

**Comment by ChristinMilloy** [comment]
duplicate issue has more info: #368

**Comment by desandro** [comment]
Thank you for reporting this issue. I'll have to take a look.

**Comment by garyc40** [comment]
Confirming that this is happening on iOS 8.4 and sometimes on iOS 9, across both iPhone and iPad.

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm tracking this issue now at #122. Closing here as a duplicate!
