### ISSUE TITLE
resize() with images and width: auto

### ISSUE THREAD

**Issue by a-v-l** [metafizzy/flickity#365]
**Test case:** http://codepen.io/anon/pen/MyXQgx

Using the slider with images with a fixed height and `width: auto;` works mostly well, although there are some strange side effects of which I want to address the resize method.

Taking you example [Flickity - resize method with vanilla JS](http://codepen.io/desandro/pen/NPyGjQ) and adding images within the `gallery-cell`s (and some modifications to the css) will render the slider correctly in all browsers. But clicking the _resize-button_ will lead to overlapping images rather than resizing (and positioning) the slider cells correctly. Only in Firefox the slider works as expected. Invoking `flkty.resize()` manually using the console also has no effect.

Am I missing something or is this a bug? Thanks for your reply!

**Comment by a-v-l** [comment]
Strange enough in a bit more complicated use-case it seems to work on Safari as well (through the option `resize: true`): http://codepen.io/anon/pen/grzyXm (resize the viewport/window)
Though upsizing the window will cause issues with the `padding` of the cells, while downsizing works perfectly well…

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like the problem was the images were `inline-block` by default, so the cells didn't have a proper width to hold. Setting `display: block` resolves this issue. See demo http://codepen.io/desandro/pen/f7db8d1ae99a8556f95cf6ceb57f0c98/

**Comment by a-v-l** [comment]
Thank you very much for the hint, but as soon as the image is wrapped in some other container–at least in Chrome–the problem persists:

**Test case:** http://codepen.io/anon/pen/ONEKqg

I hope this is not too specific yet!

**Comment by a-v-l** [comment]
Playing around with this for a while I found out, that this issues actually is different for Google Chrome on the one hand and for Safari on the other hand.

While Chrome is happy with setting the height on the `.gallery-cell` (with image `display: block` as you suggested), for Safari this still isn't working (check your [own pen](http://codepen.io/desandro/pen/f7db8d1ae99a8556f95cf6ceb57f0c98/) with Safari).

Now, Safari does accept setting the height on the `.gallery` itself (adding `setGallerySize: false`):
**Test case:** http://codepen.io/anon/pen/bpmOgb
But this again dosen't work in Chrome… Browser sniffing would be a possibility of getting this done, but I'd rather not dig out that technique anymore!

**Comment by fietstouring** [comment]
I put together this example of a gallery width dynamic height
http://codepen.io/webdesignwien/pen/rORoaV 

using Viewport units which seems to be working in all modern browsers. I only have problems in production now with Safari, which sometimes produces the overlapping images and sometimes not (although I am using a different HTML markup there, not the simplified one from the example).

**Comment by desandro** [comment]
Looks like this issue has been quiet for a while. I'm closing for now. Please follow up if this continues to be an issue.

**Comment by liam-defty** [comment]
Just incase anyone is still having trouble with this:

I was having a similar issue where calling `flickityInstance.resize()` wasn't working as expected is Safari/Webkit. In my case my slides were divs where the images dictated their widths. It turns out webkit struggles to properly redraw/repaint these divs when the image is resized.

You can force a redraw/repaint on these elements:

```
element.style.display = 'none';
element.offsetHeight;
element.style.display = 'block';
```

This did the trick for me. Definitely not the perfect solution but it works for now! Not sure if this issue might need re-opening and investigating further? @desandro
