### ISSUE TITLE
.flickity-viewport height: 0px

### ISSUE THREAD

**Issue by rbellini** [metafizzy/flickity#366]
HI,

After loading the images the .flickity-viewport get height: 0px. Why is that?

http://codepen.io/0rf30/pen/WwKEPX

**Comment by desandro** [comment]
Use [`setGallerySize: false`](http://flickity.metafizzy.co/options.html#setgallerysize)

> Use setGallerySize: false if you prefer to size the carousel with CSS, rather than using the size of cells.

See demo http://codepen.io/desandro/pen/8742dd3cd74b51a08a23b26e2f775f6a

**Comment by rbellini** [comment]
Hey Desandro!
First I'd like to thank you for your help.
The problem is this issue remains when I tried to edit my original site: http://prometalvisual.com.br/tmp/ (Top menu Produtos > Banners > Etc, etc..). The images still not showing in this case.

**Comment by desandro** [comment]
Looks like your cells have no inherent size. You could set:

``` css
.gallery-cell {
  height: 100%;
  width: 100%;
}
```

**Comment by rbellini** [comment]
Amazing! Thank you a lot Desandro! \o/

**Comment by rbellini** [comment]
Hi Desandro!
There are two current errors I am not being able to fix.
First is the fact that the images from one carousel are mixing with the next (from line 119 on from script.js file). This part of the code is somehow failing to empty the current set.
And second and last is a way to start the carousel from index 0. I did try to add initialIndex: 0 on Flickity object and it doesn't seems to be working (line 95 from same source code as before).
Current url :  http://prometalvisual.com.br/
Thank you a lot!

**Comment by desandro** [comment]
Sorry, but I won't be able to debug these issues. I'll leave that up to you!

**Comment by huykon** [comment]
Dear @desandro ,
I have tried to use `setGallerySize: false` but our tab only show list items in the first tab, don't show for the rest. Can you help me resolve this problem?

**Comment by eveevans** [comment]
You can also use: `ImagesLoaded: true`. That is exactly for the problem you are trying to solve. 

The documentation says: 

> Unloaded images have no size, which can throw off cell positions. To fix this, the imagesLoaded option re-positions cells once their images have loaded.

**Comment by coder618** [comment]
flikity not work when parent display property set to ``flex``

i tackle this issues by seting display to block

**Comment by berlindave** [comment]
@coder618 Thank you, that solved my problem!

**Comment by misterjtc** [comment]
> flikity not work when parent display property set to `flex`
> 
> i tackle this issues by setting parent `display : block`

Thank you @coder618!  This also solved my problem!

**Comment by janzenz** [comment]
Thanks @coder618. That fixed it for me as well. This sounds like an issue to me.

**Comment by famapohl** [comment]
@Tagaca19e That fixed it for me. Thank you!
