### ISSUE TITLE
Type script definition for flickity

### ISSUE THREAD

**Issue by abdelkader27** [metafizzy/flickity#367]
Hi,

it will be nice to have a tsd file to use with Typescript. it's working fine with typescript now, but it's showing a compilation error.

**Comment by abdelkader27** [comment]
Here the type script definition:

// Type definitions for flickity 1.2.1
// Project: https://github.com/metafizzy/flickity
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference path="../jquery/jquery.d.ts"/>

interface FlickityOptions {
    cellSelector?: string;
    initialIndex?: number;
    accessibility?: boolean;
    setGallerySize?: boolean;
    resize?: boolean;
    cellAlign?: string;
    contain?: boolean;
    imagesLoaded?: boolean;
    percentPosition?: boolean;
    rightToLeft?: string;
    draggable?: boolean;
    freeScroll?: boolean;
    wrapAround?: boolean;
    lazyLoad?: boolean;
    autoPlay?: boolean;
    watchCss?: boolean;
    asNavFor?: string;
    selectedAttraction?: number;
    friction?: number;
    freeScrollFriction?: number;
    prevNextButtons?: boolean;
    pageDots?: boolean;
    arrowShape?: Object;
}

interface JQuery {
    flickity(options?: FlickityOptions): JQuery;
}

**Comment by desandro** [comment]
Thank you for this feature request. While I can see this feature being used by some, TypeScript is an unfamiliar subject for me. I'd rather not add more code to the project, especially some that I do not understand. Sorry, but Flickity will not be adding a TypeScript definition.
