### ISSUE TITLE
Add caption

### ISSUE THREAD

**Issue by MarcLeyendecker** [metafizzy/flickity#37]
Is there already an official way to add and position caption texts on top of the slides?

**Comment by 72quadrat** [comment]
I'm currently just adding a p-Tag that's is position: absolute, and bottom xy

Works fine and is great for customizations.

**Comment by MarcLeyendecker** [comment]
Yeah I also just added an absolute positioned <div> but I'm sure there are some more options, or let's say some more official solutions to this, maybe also with some options...
Can't wait for next week :-)

**Comment by desandro** [comment]
See demos!

jQuery: http://codepen.io/desandro/pen/dPdVNM
vanilla JS: http://codepen.io/desandro/pen/OPQxpO

These will be in the docs as [Extra demos](http://flickity.metafizzy.co/extras.html#extra-demos)
