### ISSUE TITLE
Draggable false + asNavFor disables click

### ISSUE THREAD

**Issue by beefchimi** [metafizzy/flickity#370]
I want to be able to use the `asNavFor` option and disable dragging, as I know the amount of images I'll be using and am styling them to all fit within the available width. Disabling dragging causes the nav items to no longer be clickable :(

http://codepen.io/beefchimi/pen/ZWqXyM?editors=1000

**Comment by desandro** [comment]
Thank you for reporting this issue. This sounds like a symptom of #51. Closing here as a duplicate.
