### ISSUE TITLE
No loading wheel and fade up?

### ISSUE THREAD

**Issue by arkid** [metafizzy/flickity#372]
This may be a feature request, but is it right that flickity has no ajax style loading wheel and way of checking all the images are in place before it appears?  If you don't want to use the lazyload option for some reason it seems that the appearance of the slider can be rather ungraceful with images darting around before they all load.

**Comment by desandro** [comment]
Thanks for this feature request. While there is no loader animation built-in to Flickity, you could create your own using the [lazyLoad event](http://flickity.metafizzy.co/api.html#lazyload). If you have a **reduced test case** of what you're trying to achieve I may be able to show how you can do it. 
 See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by arkid** [comment]
The fade up feature as well I mentioned is important to help ensure that
the initialization of the interface is as slick as possible.  Right now I
have fairly large images loading and when I clear my cache they jump around
whilst loading after the flickity interface has appeared.
