### ISSUE TITLE
Advance by X amount

### ISSUE THREAD

**Issue by nickff** [metafizzy/flickity#373]
Hey Dave,

I'm looking for the ability to advance the carousel by x amount (pixel or percent) with each click, rather than aligning a cell left/center/right. Possible?

**Comment by desandro** [comment]
Flickity could be hacked for this kind of functionality, but at first glance, I don't see how it's more useful than swiping or selecting previous/next cell. Could you explain what you're trying to achieve with this requested feature?

**Comment by nickff** [comment]
The primary reason is that our carousel has different width images inside,
so each click jumps a different amount and it can tend to feel a little
odd. We'd like a more consistent experience that moves the same amount with
each click.

Let me know if that makes sense!

On Wednesday, May 4, 2016, David DeSandro <notifications@github.com> wrote:

> Flickity could be hacked for this kind of functionality, but at first
> glance, I don't see how it's more useful than swiping or selecting
> previous/next cell. Could you explain what you're trying to achieve with
> this requested feature?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/metafizzy/flickity/issues/373#issuecomment-216943350>
>


-- 

nick hoag

creative partner
the future forward
http://thefutureforward.com

**Comment by desandro** [comment]
Sorry, but Flickity does not have this kind of functionality built-in. If you want this fine-grain control of horizontal position, you may want to try a non-Flickity solution, using overflow-y and browser scrolling.
