### ISSUE TITLE
Wrap Around for 3 Categories

### ISSUE THREAD

**Issue by angelaEpsilon** [metafizzy/flickity#374]
Hey there!

We are using Flickity for a beverage site with 3 categories (Waters, Lemonades, and Teas) with a variable number of slides in each category. Currently, we have it set up so that Wrap-Around is enabled for each category only (example: when the user gets to the last water slide, it starts back at the first water slide.) We would like it to cycle through all 3 categories and then start from the beginning. Any thoughts on if this is possible or not?

**Comment by desandro** [comment]
Hello! Thank you for posting this question. I'm having trouble understanding what you are trying to achieve. Any chance you could put together a **reduced test case**?  See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by angelaEpsilon** [comment]
Thank you so much for your response!

I’m sorry if I didn’t clearly describe the problem — it’s a little convoluted. I can definitely put together a reduced test case for you. It might take me a couple/few hours to gather all of the necessary components, as another developer worked on this bit, and I’m not quite sure what he had going on. In the meantime, if you would like to check out the page to better wrap your head around the issue, here is the link:

http://flavorupyoursummer.com/page/drink-it-up

Thanks so much, and I will put together a reduced test case soon!
Sincerely,
Angela

**Comment by desandro** [comment]
Thanks for that. It looks like when you select a different category, the Flickity carousel content is changed. Given this setup, it's probably going to be complicated to achieve what you're asking for.

What you could do is add behavior on [cellSelect](http://flickity.metafizzy.co/api.html#cellselect), that when the user advanced from the last cell to the first, the carousel is swapped. But Flickity isn't designed for this kind of dynamic changes to entire content while in motion. I can't guarantee it will work well or at all.

**Comment by angelaEpsilon** [comment]
Of course, and thank you so much for your feedback. It seemed like it was going to be a bit complicated to get the carousel to behave the way we’d like it to, and I appreciate your honesty. I’ll forward this on to my manager and see how he’d like to proceed.

Thanks again,
Angela
