### ISSUE TITLE
Sometimes the picture is not loaded

### ISSUE THREAD

**Issue by saintroma** [metafizzy/flickity#375]
Good day. There is a problem. In half of the image is not loaded . Instead, only the picture header and the scroll bar. One has only to open the debugger and photo displays at once. In half of the cases it happens in Opera , Chrome in very occasionally. Is it possible because of the long name of the image ? Let 's "perchatki-kombinirovannye-s-dvojnym-naladonnikom-iz-spilka.png". Thanks

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by mdmoreau** [comment]
You probably need to enable the imagesLoaded option to fix that issue - http://flickity.metafizzy.co/options.html#imagesloaded

**Comment by saintroma** [comment]
Thank you very much. Really helped . Though uvelichelos display the time, but not much . Now no empty frames . Thanks again.
