### ISSUE TITLE
Half Icons At the edges

### ISSUE THREAD

**Issue by jAddict7** [metafizzy/flickity#376]
Thanks for the awesome plugin. When I try to create a multiple image carousel, half icons are show at the edges as like this . How to avoid and make the alignment proper,

**HTML**
`<div class="gallery">
	<div class="gallery-cell">
		<div class="gallery-cnt">
			<a href="#">
				<img class="carousel-cell-image" alt="" title="" data-flickity-lazyload="/resources/images/1.png"/>
				<h3>XXX</h3>
				<h4>YYY</h4>
			</a>
		</div>
	</div>
</div>`

**CSS**
`$('.gallery').flickity({
			imagesLoaded: true,
			pageDots: false,
			lazyLoad: 5,
			autoPlay: 5000,
			wrapAround: true
		});`

In example too, the icons at the edges were shown half [http://flickity.metafizzy.co/options.html#wraparound](here).

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
