### ISSUE TITLE
Infinite linear moving (no physics) Carousel ?

### ISSUE THREAD

**Issue by daslicht** [metafizzy/flickity#377]
Hi,
I haven't found any other way to contact you so please be indulgent with me that I write here.

Is there a way to make the Carousel slides just infinite linear like a marquee, please ?

**Comment by daslicht** [comment]
Hi, 
I quickly hacked your code and came up with this: 
https://plnkr.co/edit/tkiRH8jpRNH7qFv8FM37?p=preview
Is there an option to enable scrolling like this ?
If not , it would be a nice addition no ?

~ Marc

**Comment by desandro** [comment]
Thank you for this feature request. Others have requested it, but I have decided it's worth implementing in Flickity. From https://github.com/metafizzy/flickity/issues/77#issuecomment-181070505

> I'm going to stick with my position and decline this feature request. The autoPlay feature is a suitable solution. Adding another type of auto-motion behavior is not worth the cost of additional complexity.

**Comment by daslicht** [comment]
Do you know any alternative please?
