### ISSUE TITLE
Invalid requests to npmcdn.com

### ISSUE THREAD

**Issue by mjackson** [metafizzy/flickity#378]
Hey @desandro! :D 

I've noticed a lot of invalid requests for `flickity` (and `masonry-layout`, `isotope-layout`, and `imagesloaded`) coming through npmcdn.com in the form:

    /flickity@1.1/dist/flickity.pkgd.min.js?ver=1.1.1

The reason these requests are invalid is because npmcdn doesn't know about the `ver` query parameter, so it returns a 403.

I looked through your docs but I couldn't find where you're telling people to use these URLs, so I'm not sure where they're coming from (I can't see referrers from CDN traffic), but I thought you might have a demo site somewhere that is using URLs like this and I just wanted to give you a heads up.

**Comment by desandro** [comment]
Thanks for the heads up. From my knowledge, I have never used the `ver` query parameter. I use npmcdn URLs in the docs, README, and in CodePen demos. None have `ver`.

[Flickity v1.1.1 is an older version](https://github.com/metafizzy/flickity/releases/tag/v1.1.1). v1.1.2 came out in December 2015. My hunch is it's a WordPress theme version, that's tacking on `ver`. [WordPress does have a `$ver` parameter](https://developer.wordpress.org/themes/basics/including-css-javascript/) used for versioning files.

**Comment by mjackson** [comment]
Great, thanks for the lead. I'll see if I can track it down.

**Comment by izzy69** [comment]
May I ask the about
