### ISSUE TITLE
two-row carousels

### ISSUE THREAD

**Issue by Snowbell92** [metafizzy/flickity#379]
Is it possible to have two-row carousels - at least in desktops?

**Comment by desandro** [comment]
Not directly. But you can use CSS to fit 2 elements into the same div. With one breakpoint, they back be positioned horizontally, and on another they can be positioned vertically.

**Comment by Snowbell92** [comment]
Thanks for the suggestion, I'll have to make a codepen and test it.

**Comment by kabubi** [comment]
Any suggest to do this? Thanks

**Comment by kristiansp** [comment]
I would also really love to have a solution for this. I would think fitting 2 elements within the same div would be a bit tricky, as I guess they then would be treated as one slide? So if I on mobile have only one slide visible, that would in effect only be "half" a slide.

Anyone have other ideas how to hack it, if it's unlikely it would get native support?

**Comment by dpw1** [comment]
I made a quick example [on Codepen](https://codepen.io/diego-fortes/pen/MWqMPeb). I haven't thoroughly tested it yet nor have I used it in production, but this should be a good start. Let me know what can be improved!
