### ISSUE TITLE
selectedIndex not updating

### ISSUE THREAD

**Issue by NicolasVanhecke** [metafizzy/flickity#384]
I have this [codepen](http://codepen.io/desandro/pen/bNyrqy) (not mine btw), where I see this selectedIndex being updated when the carousel has selected a new carousel-cell. When I copy this code into my file it does not work. I get no error whatsoever.

I keep getting 0 for selectedIndex...

How is this happening?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by NicolasVanhecke** [comment]
As it seems there was a problem in my custom jQuery using a name that was reserved.. Although I didn't get errors or an indication I was doing something wrong.
So this is fixed, no issue with Flickity on this.
