### ISSUE TITLE
draggable breaking asNavFor

### ISSUE THREAD

**Issue by chrisrowe** [metafizzy/flickity#386]
Hey!

It looks like using `draggable: true` breaks support for `asNavFor`, the parent still controls the child so they're in sync but the child becomes unclickable. 

Here's a reduced test case https://codepen.io/chrisrowe/pen/wWwzQG

**Comment by chrisrowe** [comment]
Urgh, this is a dupe or at least heavily referenced in #51.
I feel like the docs should mention this if it's intended behaviour as per https://github.com/metafizzy/flickity/issues/51#issuecomment-74321450 ?

**Comment by desandro** [comment]
Thanks for reporting this bug. Yes, it's a proper bug. But I'm not a fan of disabling draggable in the first place, even for the navigation carousel. I'm leaning towards not fixing this one.

**Comment by chrisrowe** [comment]
@desandro Thanks for your comments, I guess it's down to preference. I'm super happy with your stance but it'd be great if this were acknowledged in the docs or something like a `console.log` warning to help others learn about this and not waste the time I did.

**Comment by desandro** [comment]
Good point. I've added a mention in the docs for Flickity v2.

**Comment by chrisrowe** [comment]
You're the best!

/me resumes playing http://codepen.io/desandro/full/ezNawy/
