### ISSUE TITLE
Make next() / prev() consistent with select()

### ISSUE THREAD

**Issue by sjelfull** [metafizzy/flickity#387]
select() can be passed isWrapped and isInstant, but next() / prev() only supports isWrapped().

To move to the next/previous without animating, I have to duplicate the logic of next() / prev().

**Comment by desandro** [comment]
Thanks for this feature request. Yes, you can hack it by adding this code:

``` js
Flickity.prototype.previous = function( isWrap, isInstant ) {
  this.select( this.selectedIndex - 1, isWrap, isInstant );
};

Flickity.prototype.next = function( isWrap, isInstant ) {
  this.select( this.selectedIndex + 1, isWrap, isInstant );
};
```

I'm curious, what's your use case for going next/previous without animation?

**Comment by desandro** [comment]
Flickity v2.0.3 has been released with support for the `isInstant` argument. Thank you for this feature request!

**Comment by sjelfull** [comment]
Thanks!

Forgot to answer your question: _I'm curious, what's your use case for going next/previous without animation?_

My use case was simply that I used it in a context where the client wanted instant switching of slides. In the UI, you could either select a specific slide (```select()```) or next / previous (```next()``` /``` prev()```), but they didn't behave consistently, even though I expected them to.
