### ISSUE TITLE
flickity-is-lazyloading class event

### ISSUE THREAD

**Issue by castrolem** [metafizzy/flickity#389]
Hello. Would be nice to add a class when a lazy-loaded image starts changing from the attribute in `data-flickity-lazyload` to the actual `img[src="url"]`.

My use case for such a class will be adding a loading icon for example, since right now, where we are using this plugin has to rely in an external image service that's extremely slow and they do not allow us to cache their images in our servers.

**Comment by desandro** [comment]
Thanks for this submitting this issue. Let's keep discussion over at #393
