### ISSUE TITLE
Static Click

### ISSUE THREAD

**Issue by pavethiran** [metafizzy/flickity#39]
Inside the `proto.staticClick` method the cell which is saved inside `clickedCell` is no `Cell` object.
This causes the `utils.indexOf( this.cells, clickedCell );` to fail and always to save `clickedCellIndex = -1` and `clickedCellElem = undefined`.

http://jsfiddle.net/8ctjfrcb/

**EDIT**
My FIx:
```javascript
Flickity.prototype.getCell = function( elem ) {
  // loop through cells to get the one that matches
  for ( var i=0, len = this.cells.length; i < len; i++ ) {
    var cell = this.cells[i];
    if ( cell.element == elem ) {
      return cell;
    }
  }
  return false;
};

Flickity.prototype.getParentCell = function( elem ) {
  // first check if elem is cell
  var cell = this.getCell( elem );
  cell = cell || this.getCell(utils.getParent( elem, '.flickity-slider > *' ));
  return cell;
};
```

**Comment by desandro** [comment]
Thanks so much for catching this!  [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), email me yo@metafizzy so I can send some your way.
