### ISSUE TITLE
wrapAround problem when flickity has two slides, it display not correct

### ISSUE THREAD

**Issue by alex1012** [metafizzy/flickity#390]
wrapAround problem, again =(

If I am right, when I selected second slide, the first slide must be shown on left and right side.
In this case when i add third slide, it starts working correct.

http://codepen.io/alex1012/pen/yJyzdK - bug
http://codepen.io/alex1012/pen/QEwOwa - correct

**Comment by desandro** [comment]
Thanks for reporting this issue. See https://github.com/metafizzy/flickity/issues/95#issuecomment-86124653
