### ISSUE TITLE
Remove extra dependencies when installing with Bower

### ISSUE THREAD

**Issue by JasonTheAdams** [metafizzy/flickity#391]
Hey! Sorry if this isn't really the right place for this sort of question.

When I load flickity via bower, `bower install flickity --save`, it loads all the dependencies, which is quite a few. The irony here is that all I need is the packaged file in dist. Everything else is completely unnecessary. I can delete the loaded deps, but the next time I update they're back.

Do you know of a way to _just_ install flickity without all the dependencies?

**Comment by desandro** [comment]
Thanks for reporting this issue. 

>  The irony here is that all I need is the packaged file in dist.

True! I've heard others raise this concern as well.

Buuuuut consider if your site also uses Masonry and imagesLoaded. Just as well, you can use the dist files for those packages, but in doing so, you be included their shared dependencies multiple times (ev-emitter, fizzy-ui-utils, get-size, jquery-bridget). Duplicated dependencies means higher bandwidth for your users and potential compatibility issues. Bower is designed to resolve these dependency issues, so multiple packages can use the same dependency.

I'm trying to provide the widest support for Flickity and Metafizzy's other libraries: Browserify, RequireJS, Webpack, npm, Bower. Including all the dependencies also helps provide this wide support.

So, I hear ya. It's annoying to see those other things clutter up your `bower_components`. But they are there for several valid reasons. I hope this clears up why 🌈🐻
