### ISSUE TITLE
Option to narrow/reduce the width of the touch/grab area of Flickity carousels

### ISSUE THREAD

**Issue by iamandrebulatov** [metafizzy/flickity#394]
**Feature Request:**
-- Option to narrow the drag/touch area of a carousel.

**Uses:**
-- I am using a customized version of [Slideout.js](https://github.com/mango/slideout) to give users the ability to touch-slide/swipe open a hidden menu on mobile.   The area to grab/touch-to-drag is on the left, about 50px.   If viewport is touched beyond 0-50px from the left, the slide-out menu will not show. 
-- The problem is combining this slideout feature with Flickity is when a Flickity slider is on screen and the user tries to open the nav, a "buggy" behavior takes places, where the nav opens but the carousel is also dragged/moved at the same time.
-- I am looking to narrow down the touch/drag area of Flickity carousels, so that an area of 50 pixels on the left side of the viewport will not initialize the Flickity slider movement.

**Test case -- Flickity.js + Slideout.js + Narrowing Flickity Drag Area:** http://codepen.io/iamandrebulatov/pen/KMpBEx

PS:  Thank you for Flickity, and Masonry, and Isotope and more!
PPS:  I am not even sure where to start in narrowing down the touch area, but if you give me  hint, I can try and put together a quality PR for you.

**Comment by desandro** [comment]
Thanks for reporting this issue. This is a particular use case, but we can provide a solution. You can duck punch Flickity's drag behavior to check the initial position of the first touch event.

``` js
var _pointerDown = Flickity.prototype.pointerDown;
Flickity.prototype.pointerDown = function( event, pointer ) {
  // dismiss drags on left edge
  if ( pointer.pageX < 70 ) {
    this.isPointerDown = false;
    delete this.pointerIdentifier;
    return;
  }
  // resume normal behavior
  _pointerDown.apply( this, arguments );
};
```

See demo http://codepen.io/desandro/pen/db77170261a15fbaf49b83765e656771/?editors=1010

**Comment by iamandrebulatov** [comment]
Sweet! Tested: works.  Thank you very much!  Should I close?
