### ISSUE TITLE
Flickity Bower dependency versions out of sync with Masonry and Outlayer

### ISSUE THREAD

**Issue by badfeather** [metafizzy/flickity#395]
When installing via Bower, I received the following notices:
```
Unable to find a suitable version for get-size, please choose one by typing one of the numbers below:
    1) get-size#~1.2.2 which resolved to 1.2.2 and is required by flickity#1.2.1
    2) get-size#^2.0.2 which resolved to 2.0.2 and is required by masonry#4.1.0, outlayer#2.1.0

Prefix the choice with ! to persist it to bower.json
```

and:
```
Unable to find a suitable version for fizzy-ui-utils, please choose one by typing one of the numbers below:
    1) fizzy-ui-utils#~1.0.1 which resolved to 1.0.1 and is required by flickity#1.2.1
    2) fizzy-ui-utils#^2.0.0 which resolved to 2.0.2 and is required by outlayer#2.1.0

Prefix the choice with ! to persist it to bower.json
```

I chose option 2 for both, but haven't tested yet. Thought you should know.

**Comment by desandro** [comment]
Yup. Thanks for heads up. Masonry, Packery, Isotope and their shared dependencies all got major browser upgrades. Flickity is the last big project to get upgraded — which is happening right now.

**Comment by desandro** [comment]
[Flickity v2 is out now](http://flickity.metafizzy.co) which resolves these dependency mismatch issues with Masonry v4, Isotope v3, Packery v2, Draggabilly v2, and imagesLoaded v4.

**Comment by badfeather** [comment]
Cool!

On Mon, Jul 11, 2016 at 1:19 PM, David DeSandro <notifications@github.com>
wrote:

> Flickity v2 is out now <http://flickity.metafizzy.co> which resolves
> these dependency mismatch issues with Masonry v4, Isotope v3, Packery v2,
> Draggabilly v2, and imagesLoaded v4.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/metafizzy/flickity/issues/395#issuecomment-231802152>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAmu0AT9GNyhqUiWDlDjSMxD44DnC2g2ks5qUnsogaJpZM4IxRkX>
> .
>



-- 
badfeather.com
