### ISSUE TITLE
Re-initialize flickity onclick

### ISSUE THREAD

**Issue by W0tti** [metafizzy/flickity#397]
Hi there,

Recently got recommended Flickity and it has quickly become my favourite carousel to use.

For a new job I have coming up, the client wants a 360 degree panoramic feature where you can drag the image left and right. I have managed to to this with Flickity no problem. The issue lies with the fact that the I need to create 3 different pans which can be toggled (basically in tabs unless there is a better way).

From previous experience with using tabs and javascript, the initial tab shows the content fine, but when you click on the other tabs, no content is shown as the height renders at 0. 

I have managed to re-initialize the Masterslider plugin onclick so it works in tabbed content on a different job, so I guess my question is this:

Is it possible to re-initialize my Flickity carousels onclick? 

Thanks,

Jack

**Comment by desandro** [comment]
Thanks for the kind words

+ See the [`destroy` demos](http://flickity.metafizzy.co/api.html#destroy) for toggling Flickity on and off
+ But I think you're better off using [`resize`](http://flickity.metafizzy.co/api.html#resize)

> If Flickity is initialized when hidden, like within a tab, trigger resize after it is shown so cells are properly measured and positioned.

**Comment by W0tti** [comment]
Thank you for the quick response. 

I don't know how I missed that in the docs. 

I have kind of got it working. Currently I have to click the tab twice in order to get the content to show but I am sure I will figure it out.

Thank you.
