### ISSUE TITLE
Carousel not displaying correctly

### ISSUE THREAD

**Issue by lewismalpas** [metafizzy/flickity#398]
Hi,

Thanks for making such amazing plugins, great work! I've been having a few problems which I cannot seem to solve, please view the website at:
[(http://clementjolin.com/staging/)]

I've been having trouble to get the carousel to display correctly and to resize correctly when the browser is resized so that the images are always contained within the viewport. The images are set as background images on the cells with the background-size property set to contain.

I also could not get wrapAround to work even when set to True, the carousel just stopped at the last cell and did not continue.

Any ideas?

Thanks,
Lewis.

**Comment by desandro** [comment]
Looks like you've initialized Flickity twice, once in your JS, once in HTML. Remove `js-flickity` so Flickity is initialized only once.

**Comment by lewismalpas** [comment]
Hi Desandro,

Ahhh thanks so much, that explains the two sets of navigation arrows. One more question which I am struggling with, how do I init the carousel on document ready and resize?

Here is what I have so far but sadly this isn't working:

`(function($) { //No conflict wrapper (allows use of $)
   
	var $carousel = $('.carousel').flickity({
		cellAlign: 'center',
		wrapAround: true,
		cellSelector: '.carousel-cell',
		pageDots: false,
		imagesLoaded: true,
		watchCSS: true,
		resize: true
	});
	
    $(document).ready(function() {
    	$carousel.flickity();
    });

    $(window).resize(function() {
		$carousel.flickity('resize');
	});

})(jQuery); //No Conflict Wrapper` 

Thanks,
Lewis.

**Comment by lewismalpas** [comment]
Hi,

Sorry my explanation wasn't that clear, I am trying to reinit the carousel when the viewport is resized as my images are set as background-images on the carousel-cell so that they are always contained within the viewport.

At the moment the carousel is scaling nicely when the width of the viewport is changed, however I cannot get the carousel to scale when the height of the viewport changes without doing a refresh of the page.

At the moment when the viewport height changes the images overflow outside the viewport until you refresh the page which then resizes everything correctly.

Thanks,
Lewis.
