### ISSUE TITLE
Previous/next buttons feel laggy

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#4]
[growradio via Twitter](https://twitter.com/growradio/status/557653345721401347)

> on my iphone 5s i feel like the arrow buttons have too much lag. Meaning i am inclined to tap another time bc movement is too late

Yup, I felt this too. Currently, Flickity is using on `click` event. I'll have to investigate to see if this can be improved.

**Comment by notflip** [comment]
Same problem here! The plugin is amazing by the way! Thank you so much! My best star on github :)

**Comment by lunelson** [comment]
It looks like you're implementing this; otherwise I was going to ask what 'fast click' library or polyfill you think would play best here. The touch interaction is otherwise superb, I'm really impressed—just the `'click'` event trips it up ;)

**Comment by desandro** [comment]
Buttons now use [tap-listener](https://github.com/metafizzy/tap-listener) for faster tapping. Released in Flickity v0.2.0.

See article: [Taps are faster than clicks](http://metafizzy.co/blog/taps-are-faster-than-clicks/)
