### ISSUE TITLE
Custom buttons don't slide the cells if the gallery is still in motion

### ISSUE THREAD

**Issue by Laosing** [metafizzy/flickity#400]
Hey custom click events don't move the cells if the gallery is still in motion from a drag flick. You have to wait until the slider has completely stopped for the custom buttons to work, is there an easy fix/work around this? Wraparound and freeScroll are both set to true.

**Test case:** http://codepen.io/Laosing/pen/XKKPmE

**Comment by desandro** [comment]
Thanks for reporting this issue. Yes, behavior is handled by standard ui like prev/next buttons and page dots, but not if you create your own UI buttons. To resolve it, you can add `.flickity( 'emitEvent', 'uiChange' )`. This signals that a UI change has been made and that freeScrolling should stop. See demo http://codepen.io/desandro/pen/0e13e7081b20f4345a70d2c4337a99f6/

**Comment by Laosing** [comment]
Sweet that's perfect thanks!
