### ISSUE TITLE
isotope grid of flickity carousels - first carousel empty

### ISSUE THREAD

**Issue by allonestring** [metafizzy/flickity#401]
Hi
I've been putting flickity carousels into an isotope grid (what fun ☺); see these two codepens

http://codepen.io/allonestring/pen/NrrVLO
http://codepen.io/allonestring/pen/BzzXjo

In the first, I've left the flickity options in the HTML and it all works beautifully. 

In the second, I've put the options into js and it doesn't:
1. not all of the options are taking effect (wrapAround: true, pageDots: false)
2. and the first carousel is empty. It doesn't matter which order the element-item divs are in, the first listed is always empty

I expect that the first problem is because I've got the syntax/format wrong, but I can't see what I'm getting wrong with the second (but will gladly be told what!).
Thanks

**Comment by desandro** [comment]
Thanks for reporting this issue. With the 2nd example, since we're initializing with JS, we should remove `js-flickity` so they are not initialized with HTML. Then we need to select multiple `.carousel` elements with `querySelectorAll`.  See demo http://codepen.io/desandro/pen/e38d505e3b852160ff9d381056f00f3d/

``` js
// init Flickity carousels
var carousels = document.querySelectorAll('.carousel');

for ( var i=0; i < carousels.length; i++ ) {
  var carousel = carousels[i];
  new Flickity( carousel, {
    cellAlign: 'center',
    wrapAround: 'true',
    pageDots: 'false'
  });
}
```

**Comment by allonestring** [comment]
Thank you David!
I guessed that I was wrong about the syntax, but didn't think of putting the carousels into an array.

**Comment by desandro** [comment]
Updated options with proper booleans. Try again!

**Comment by allonestring** [comment]
Gosh, was it just the quotes?
:star: Thank you again!
