### ISSUE TITLE
Batch scrolling

### ISSUE THREAD

**Issue by celeryclub** [metafizzy/flickity#402]
Hey there! Thanks for making this great software. I have a feature question: Is it currently possible to scroll in batches of slides, say three at a time, when the "next" button is clicked? I couldn't find any documentation about this. Or if not, is this on the roadmap?

It may be possible to do this with the `select` method and the `selectedIndex` property, but I thought I'd check if there's a built-in way first before trying to build it myself.

Thank you very much for your assistance!

**Comment by desandro** [comment]
This feature will be added in Flickity v2, coming in the next month. See #22

**Comment by celeryclub** [comment]
Thanks so much for the quick reply. Looking forward to it!
