### ISSUE TITLE
Draggable breaks <select> inputs

### ISSUE THREAD

**Issue by StephenBoyd** [metafizzy/flickity#403]
On mobile browsers (at least with Chrome 50 on Android 4.4.4), if a Flickity gallery is set to be draggable, `<select>` inputs within that gallery's cells will not be able to record the user's selection. Sometimes the list of options flickers once as if it were rapidly closing and re-opening.

This problem doesn't happen when `draggable` is set to be `false`.

**Test case:** http://codepen.io/sboyd/pen/pbNqwE

**Comment by desandro** [comment]
Thanks for reporting this issue. I wasn't able to reproduce it with Chrome on iOS. I'll have to look on an actual device.

**Comment by andredalmolin** [comment]
This is happening to me on Windows 10 and Firefox 47.0.1 on the posted test case. On Chrome is ok.

**Comment by blazingarrow** [comment]
With firefox 48.0 I on OS-X 10.11.6 I can't event select an <option>. The selected <option> doesn't focus.

**Comment by desandro** [comment]
Flickity v2.0.3 has been released with a fix for this issue in Firefox. Thank you for reporting this bug!
