### ISSUE TITLE
Cannot position cursor in textarea in a cell

### ISSUE THREAD

**Issue by KingMob** [metafizzy/flickity#404]
There's a bunch of focusing and blurring going on. E.g., inside `Unidragger.prototype._staticClick`, the code checks to see if the event.target is an input or textarea, and if so, calls `focus()` on it. But this knows nothing about where inside the textarea/input the mouse clicked, and as a result, the browser always places the cursor at the start.

**Test case:** http://codepen.io/anon/pen/ZOLYLB

**Comment by desandro** [comment]
Thank you for reporting this issue! I've found a fix for this issue and it will be resolved in Flickity v2.

**Comment by KingMob** [comment]
Awesome, thanks! Think v2 is stable enough for production use? I've already tried several sliders, and Flickity was the first one that handled our flexbox contents properly; I'd hate to have to switch again.

**Comment by desandro** [comment]
v2 will be out in a couple weeks. Until then you can use this fix in v1 by adding this code.

``` js
// nodes that have text fields
var cursorNodes = {
  TEXTAREA: true,
  INPUT: true,
};

// input types that do not have text fields
var clickTypes = {
  radio: true,
  checkbox: true,
  button: true,
  submit: true,
  image: true,
  file: true,
};

Flickity.prototype.pointerDown = function( event, pointer ) {
  // dismiss inputs with text fields. #404
  var isCursorInput = cursorNodes[ event.target.nodeName ] &&
    !clickTypes[ event.target.type ];
  if ( isCursorInput ) {
    // reset pointerDown logic
    this.isPointerDown = false;
    delete this.pointerIdentifier;
    return;
  }

  this._dragPointerDown( event, pointer );

  // kludge to blur focused inputs in dragger
  var focused = document.activeElement;
  if ( focused && focused.blur && focused != this.element &&
    // do not blur body for IE9 & 10, #117
    focused != document.body ) {
    focused.blur();
  }
  this.pointerDownFocus( event );
  // stop if it was moving
  this.dragX = this.x;
  this.viewport.classList.add('is-pointer-down');
  // bind move and end events
  this._bindPostStartEvents( event );
  // track scrolling
  this.pointerDownScroll = getScrollPosition();
  window.addEventListener( 'scroll', this );

  this.dispatchEvent( 'pointerDown', event, [ pointer ] );
};
```

See demo http://codepen.io/desandro/pen/3918f0db294bfbf923825f70162c7e16/

**Comment by blackChef** [comment]
@desandro 
I think we should also check if target is `readOnly` or `disabled`. Only ignore those which are not `readOnly` or `disabled`.

    if ( isCursorInput ) {
      if (!event.target.readOnly && !event.target.disabled) {
        // reset pointerDown logic
        this.isPointerDown = false;
        delete this.pointerIdentifier;
        return;
      }
    }
