### ISSUE TITLE
Indicate direction of advancement, specifically drag.

### ISSUE THREAD

**Issue by mckennedy** [metafizzy/flickity#407]
Definitely a feature request.

Would it be possible while the .is-pointer-down class is applied to .flickity-viewport to also have a class applied indicating the direction a person is swiping or dragging (ex: .dragging-left, or .dragging-right)?

Perhaps a class applied to the .is-selected slide after dragging is finished indicating direction. Ex:

- If I advance from slide-1 to slide-2, slide-2 would have a class of .dragged-left

- If I advance from slide-2 to slide-1, slide-1 would have a class of .dragged-right

**Comment by desandro** [comment]
This feature sounds like a good use case for [Flickity's events](http://flickity.metafizzy.co/api.html#events): pointerDown, dragStart, dragMove, dragEnd, select. Rather than using default CSS, you can add your own classes as you like.
