### ISSUE TITLE
Add support for animate.css (CSS3 animations when slides come into view)

### ISSUE THREAD

**Issue by coliff** [metafizzy/flickity#408]
Please add support for animate.css - so we can have images/text CSS3 animations starting when the slides come in to view. (Of course animate.css works great on the first slide, but I'd like animations on the 2nd slide to only begin when the 2nd slide comes into view)

**Comment by desandro** [comment]
You can detect when slides have been selected with the [cellSelect  event](http://flickity.metafizzy.co/api.html#cellselect). Use this event to trigger animation for each cell.

**Comment by coliff** [comment]
Thanks for the reply and link - would love to see a working example if you ever get time. Could look great and be a useful resource for others.

**Comment by terryupton** [comment]
Did any examples get produced for this?

**Comment by coliff** [comment]
Not that I know of... and I'd still be keen to see some.

**Comment by itcomindo** [comment]
I using animation

.my_element .is_selected {
animation: .......;
}
