### ISSUE TITLE
How to select cell via URL

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#411]
Following up on https://github.com/metafizzy/flickity/issues/148#issuecomment-174656859 ...  [With the `selectCell` method](http://flickity.metafizzy.co/api.html#selectcell) in Flickity v2, you can now select a cell via a selector string

``` js
// jQuery
$carousel.flickity( 'selectCell', '#cell3' )
// vanilla JS
flkty.selectCell('#cell3')
```

You should be able to use in page links like `href="#cell3"` to select cell. I'll have to create a demo to show how.
- Opening a page with `#slide2` in the URL hash should init the gallery with the matching cell
- Clicking on a link with `href="#slide2"` should select the matching cell

**Add a 👍  reaction** if you'd like to see this feature documented or added to Flickity.

**Comment by johanneslamers** [comment]
+1

**Comment by amdad** [comment]
HASH IT!

**Comment by richgcook** [comment]
@desandro Any update on a demo for this?

**Comment by amdad** [comment]
@desandro how you like @richgcook example?

**Comment by liamail** [comment]
Hey @desandro. I have an issue when selecting the cell I want to link to from an external html document. Everything works perfectly when using a link such as `href="page.html#slide2"`- I land on the carousel and the matching cell, however I now cannot flick backwards through the carousel. Only forwards (flicking cells to the left).

Hoping you can help me out. Thanks in advance!

**Comment by liamail** [comment]
@desandro hello?

**Comment by desandro** [comment]
@liamail If you can provide a **reduced test case**, please open a new issue. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by desandro** [comment]
🎉  **[Flickity v2.1.0](https://github.com/metafizzy/flickity/releases/tag/v2.1.0) has been released with support for all new [`hash` option. See docs!](https://flickity.metafizzy.co/options.html#hash)** 🎉

> Enables hash navigation to select slides with links and URLs. Changes page URL to selected cell id.

``` js
hash: true
```

---

I'm now closing this issue for the feature request. Please open a new issue if you into trouble with using `hash`. Thanks for all the +1's and 👍 over the years. 🌈🐻

**Comment by PietM** [comment]
The hash option is excellent. I'm wondering if there is a way to number carousel-cell via php and link from a separate template. Would it look something like:

**Comment by desandro** [comment]
@PietM You would set `href` to match the element's IDs. So if you have

``` html
<div class="carousel">
  <div class="carousel-cell" id="carousel-cell1"></div>
  <div class="carousel-cell" id="carousel-cell2"></div>
  <div class="carousel-cell" id="carousel-cell3"></div>
</div>
```
Then your links external page links would look like:

``` html
<a href="page-name#carousel-cell1">View cell 1</a>
```
