### ISSUE TITLE
even un-displayed carousels lazyLoad

### ISSUE THREAD

**Issue by karnevil9** [metafizzy/flickity#413]
I have a number of carousels, only one of which is displayed at a time (undisplayed carousels have display = none). 

The carousels are configured for lazyLoad. 

**Expected:** Only visible carousels load images.

**Result:** All carousels load images, whether displayed or not. 

Codepen: http://codepen.io/anon/pen/PzEozx

**Comment by desandro** [comment]
If the carousel has `display: none`, then Flickity cannot measure how big its contents is. That's what breaking the lazyLoad.

What are you trying to achieve with `display: none` ? If we can find another solution here, we may be able to resolve the lazyLoad issue.

**Comment by karnevil9** [comment]
I want carousels that have display:none to **not** load any images until they're made visible. As is now, even carousels with display:none load their first images.

**Comment by karnevil9** [comment]
The reason for carousels with display:none is that I'm building a portfolio page with multiple galleries. Only one gallery at a time will be visible. Gallery visibility is changed by adding or removing a class that contains display:none.

**Comment by desandro** [comment]
In that case, I recommend you initialize Flickity when you wish to make the carousels visible, rather than on document ready.
