### ISSUE TITLE
cellSelect doesn't work in V2

### ISSUE THREAD

**Issue by bubbleheadinc** [metafizzy/flickity#415]
Just installed V2 and some of my functionality broke b/c `cellSelect` no longer seems to work. Thought it was still in play until V3, no? Works fine with `select.flickity`

Forked test case: http://codepen.io/Bubblehead/pen/QEaKrp?editors=1111

**Comment by desandro** [comment]
Yes, using `.on( 'cellSelect' ` with jQuery will no longer work. You'll need to update to `select.flickity` (or `cellSelect.flickity`. `cellSelect` has been deprecated, but still works in Flickity v2. I've documented this backwards-compatibility breaking change under [Upgrading from v1](http://flickity.metafizzy.co/extras.html#upgrading-from-v1)

**Comment by bubbleheadinc** [comment]
Ah there it is...hiding under Extras. Got it, thanks. Time to buy a license now :)
