### ISSUE TITLE
Is there a preferred method to link many sliders?

### ISSUE THREAD

**Issue by sheriffderek** [metafizzy/flickity#416]
I've had a few requests where the design calls for many flickity sliders on one page. _Actually_, many groups of sliders on one page. I've just been instantiating 3 sliders, and hiding their prevNextButtons - and then creating a few buttons that call next() etc. 

Sometimes they are different sizes and different index. I'd be curious if there are any cool ways of doing this and keep things as light as possible. Any precedents or examples of this?

**Test case:** http://codepen.io/sheriffderek/pen/ONKLBZ

**Comment by desandro** [comment]
See demo: http://codepen.io/desandro/pen/7f6d823caad0310f3ce1c3b9d4ce758f/

One way to do this is to wrap each carousel & button in a container element

``` html
<div class="carousel-container" data-init-index="2">
  <div class="button-group">
    <button class="button button--previous">Previous</button>
    <button class="button button--next">Next</button>
  </div>
  <div class="carousel">
    <div class="carousel-cell"></div>
    <div class="carousel-cell"></div>
    <div class="carousel-cell"></div>
  </div>
</div>
```

For custom options, like `initialIndex`, they can be set in a data attribute in HTML.

Then use `.each()` to cycle though each container, setting custom options, and binding events for custom UI.

``` js
$('.carousel-container').each( function( i, container ) {
  var $container = $( container );
  var $carousel = $container.find('.carousel');
  var initIndex = $container.attr('data-init-index') || 0;

  $carousel.flickity({
    prevNextButtons: false,
    pageDots: false,
    initialIndex: initIndex,
  });

  $container.find('.button--previous').on( 'click', function() {
    $carousel.flickity('previous');
  });

  $container.find('.button--next').on( 'click', function() {
    $carousel.flickity('next');
  });

});
```

**Comment by sheriffderek** [comment]
Excellent. I hadn't thought to set the attr from the JS. Any suggestions on getting the pageDots in sync?  Here's an example with the scoped nav - http://codepen.io/sheriffderek/pen/xOYAdE

PS Your demo above doesn't seem to have the carousels connected.

**Comment by desandro** [comment]
If you want to sync carousels up, use [flickity-sync](https://github.com/metafizzy/flickity-sync)
