### ISSUE TITLE
inserting caption JavaScript blanks out images

### ISSUE THREAD

**Issue by dvodvo** [metafizzy/flickity#417]
When following [the example codepen jQuery version](http://codepen.io/desandro/pen/dPdVNM) as follows at end of body, the caption renders, but the images do not.

Plain vanilla has the same effect, while doubling up the navigation arrows of the carousel.

Having a pre-loaded script via rails asset pipeline does not render the caption, while the images are fine...

```
<script>
var $carousel = $('.carousel').flickity({
  cellSelector: 'img',
  imagesLoaded: true,
  percentPosition: false
});
var $caption = $('.caption');
// Flickity instance
var flkty = $carousel.data('flickity');

$carousel.on( 'select.flickity', function() {
  // set image caption using img's alt
  $caption.text( flkty.selectedElement.alt )
});
</script>
<script>
$(document).foundation();
</script>
</body>
</html>

```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by dvodvo** [comment]
As a reduced test case, I fear that might be misleading given all the components involved.  portobudva.sirmontenegro.com  you can actually register there and (affter checking (spam?) mail and confirming registration) see a case in action. (P.S.  after having done some rounds, flickity is one of the better tools out there!)

**Comment by dvodvo** [comment]
woeful attempt in codepen: http://codepen.io/jerdvo/pen/AXVRxN

**Comment by dvodvo** [comment]
In codepen: http://codepen.io/jerdvo/pen/AXVRxN  this reflects the set-up whereby caption is shown and images not (with nav arrows being doubled up in carousel). Note: _the flickity scripts are the last ones of the [external JS file](https://s3-us-west-2.amazonaws.com/sirme/assets/application-244f5defb036e3ea59b58c851620f6287549c51cab1ed775a1a1789694616b29.js) lines 2089 on..._  I have also isolated the js caption by creating a  [base js file](https://s3-us-west-2.amazonaws.com/sirme/assets/application-copy.js) and a [separate file just for the caption script](https://s3-us-west-2.amazonaws.com/sirme/assets/staticpages-copy.js)

**Comment by desandro** [comment]
Thanks for that. See fixed demo: http://codepen.io/desandro/pen/6e6073930129f5c4cfabc82b47b22f89/

There were several issues:

1. You should only initialize Flickity with HTML or JS, not with both. I've removed `data-flickity` from `.carousel-main`, and used only `.carousel-main` in JS
2. Because cells have images in them, `flkty.selectedElement` will be the `div`, not the `img`. We'll have to select the child `img` to use its `alt`.

**Comment by dvodvo** [comment]
Removing `data-flickity` from `<div class="carousel carousel-main"` is resulting in a scroll of all images, as [this pen](http://codepen.io/jerdvo/pen/yJvxjb) alludes to.  Verified by isolation of behaviour adn by removal of said tag on [line 117 of original codepen](http://codepen.io/jerdvo/pen/AXVPyb). 

Now I used the flickity.pkgd.min used as an external in your pen.  So that is not the source.

What am I missing?

**Comment by dvodvo** [comment]
Other issue... If the number of thumbnails is greater than viewport, then they flop over onto new line and throw the main images out of viewport's frame. `<div class="carousel carousel-main"` is needed to maintain the structure.

**Comment by jgod** [comment]
This is helpful. I had the same issue (double nav arrows with nothing showing). I went through the site docs, adding data-flickity to get it up and running, and then looked here for more options, so then init'ng in js. Not obvious that they would conflict.

**Comment by dvodvo** [comment]
I finally isolated all components and found the hiccup.  From [David's codepen](http://codepen.io/desandro/pen/6e6073930129f5c4cfabc82b47b22f89/) the tailored javascript must IMPERATIVELY be near the bottom of the body tag.  When inserted in the header, unexpected things happen
