### ISSUE TITLE
Option to hide navigation (or add special class) when there's only one slide

### ISSUE THREAD

**Issue by jofrysutanto** [metafizzy/flickity#42]
More for aesthetic preference for some, when there's one slide some people prefer to just hide the navigation options. Possible to add this as option? Could either be additional class on Flickity main container as well, and use css to hide them.

**Comment by desandro** [comment]
I'd leave this for the developer to implement. You could do something like:

```js
var $gallery = $('.gallery').flickity();
var $galleryCells = $gallery.find('.gallery-cell');

if ( $galleryCells.length < 2 ) {
  $gallery.addClass('is-hiding-nav-ui');
}
```

And then hide previous & next buttons and page dots with CSS with `is-hiding-nav-ui`.

**Comment by danielres** [comment]
I'm using a CSS approach, I found that this works better when the carousel has to be responsive, which can result, for example, on having only 1 dot on large screens and many dots on narrow screens,

Found the tehnique here:
http://stackoverflow.com/questions/8720931/can-css-detect-the-number-of-children-an-element-has

And my implementation (in SCSS):

`
.flickity-page-dots {
  .dot:first-child:nth-last-child(1) {
    opacity: 0;
  }
}
`

**Comment by xcartmods** [comment]
pageDots: $container.find('.carousel-cell').length > 1 ? true : false,
prevNextButtons: $container.find('.carousel-cell').length > 1 ? true : false,

**Comment by ChristophJeworutzki** [comment]
`.flickity-page-dots .dot:only-child {
  visibility: hidden;
};`

**Comment by bahaa-almahamid** [comment]
I would suggest adding a data attribute on the slider element, and check the number of images in the element 
```
  homepage_hero_slider.forEach((slider) => {
        const flickity = new Flickity(slider, {
            draggable: slider.dataset.count > 1,
            prevNextButtons: slider.dataset.count > 1,
            pageDots: slider.dataset.count > 1,
        });
    });
```
