### ISSUE TITLE
Keyboard Navigation works only after first click

### ISSUE THREAD

**Issue by na86** [metafizzy/flickity#420]
Hi David, 

i'm working with a fullscreen slider, is very cool and everything works fine. 
Keyboard navigation works fine too but only after the first click on prev/next link. 
There's a way to activate this function on page load?  

Thanks for your help, and for your amazing work with flickity. 
regards

Na86

**Comment by desandro** [comment]
See demo http://codepen.io/desandro/pen/VYVEbM . Linked in [Extra demos](http://flickity.metafizzy.co/extras.html#extra-demos)

Previously reported in #84
