### ISSUE TITLE
Error when clicking carousel dots in touch-devices

### ISSUE THREAD

**Issue by timukasr** [metafizzy/flickity#422]
Pressing dots under carousel in touch devices causes an error: `Uncaught TypeError: event.preventDefault is not a function`.

**Test case:** http://codepen.io/desandro/pen/azqbop
Use Chrome to emulate touch device and click one of the dots.

**Comment by desandro** [comment]
Thank you for reporting this issue. This is a legit bug. I have a fix and it will be resolved in the next version of Flickity

**Comment by tafkanator** [comment]
Found temporary workaround: hijack touch start event.

after creating slider instance:
``` javascript
Array.from(sliderInstance.querySelectorAll('.dot')).forEach(node => {
	node.addEventListener('touchstart', e => { e.stopPropagation(); });
});
```

clicking on page dot will still work because dot will respond to click events

**Comment by desandro** [comment]
Flickity v2.0.3 has been released with a fix for this issue. Thank you again for reporting!
