### ISSUE TITLE
Using through CDN in MIT-licensed code

### ISSUE THREAD

**Issue by controversial** [metafizzy/flickity#423]
If I have a MIT-licensed software project, can I use this library through a CDN, since I'm not really re-distributing it? Thanks.

**Comment by desandro** [comment]
Yes.

**Comment by controversial** [comment]
Ok. So I don't need to change my license to GPLv3?

**Comment by desandro** [comment]
Nope. Not necessary.

**Comment by controversial** [comment]
Awesome! Thanks
