### ISSUE TITLE
Removing events with function.bind

### ISSUE THREAD

**Issue by jasonpearson** [metafizzy/flickity#424]
**Test case:** http://codepen.io/jasonpearson/pen/LkAQxA

How can I remove an event listener that is bound to a different context using vanilla JS? In the test case you'll see the unbound function works as expected, but the handler.bind(context) function does not get removed when calling flkty.off()

**Comment by desandro** [comment]
When you use `.bind()` you are creating a new function. You can cache this function as a variable:

``` js
var boundHandler = handler.bind( context )
```

See demo http://codepen.io/desandro/pen/755ca44f1c91754b9e8ed5114abcae55/

``` js
// external js: flickity.pkgd.js

var context = {
  name: 'Beverly'
};
var flkty = new Flickity('.carousel');

function handler() {
  console.log( 'handler', this.name )
}

var boundHandler = handler.bind( context );

flkty.on( 'select', handler );
flkty.on( 'select', boundHandler );

document.querySelector('.unbind-button').onclick = function() {
  flkty.off( 'select', handler );
  flkty.off( 'select', boundHandler );
}

```

**Comment by jasonpearson** [comment]
ahhh yes, that makes sense. Thanks!
