### ISSUE TITLE
Setting an container for page dots anchors

### ISSUE THREAD

**Issue by andredalmolin** [metafizzy/flickity#425]
Hi all! First, thanks for this nice library. It is very well made.
This is a feature request for an option that gives more flexibility to developers.

Like the prev and next buttons, that can be hidden via options and another elements can trigger next/prev actions, I suggest doing the same with page dots. Instead of the lib generating the page dots within a container, the lib can only write the pagedots inside a container setted by the user via options.

This is strange but allows, with no hacks, doing the prev/next buttons follow the width of the page dots. Like on the image attached.

Now to archive this, I need to create the element via javascript, attach an click event that triggers the prev/next action on Flickity, and than append to the page dots container.

![pagedots](https://cloud.githubusercontent.com/assets/6907606/17187129/5a97b77a-540e-11e6-9548-deb9dff43b80.png)

Also, it would be awsome if we could generate even the page dots, using a function on the options.

Thanks all!!!

(sorry my not perfect english)

**Comment by desandro** [comment]
Thank you for this suggestion. Rather than adding another option for a page dots container, you can [style/position it with custom CSS](http://flickity.metafizzy.co/style.html#page-dots), or [create your own page dots UI](http://flickity.metafizzy.co/extras.html#custom-navigation-ui).

**Comment by andreiglingeanu** [comment]
Unfortunately, the solution provided in docs is incomplete. It won't handle the dynamic nature of the page dots, as the user resizes the browser window. Here's how to replicate it properly (without duplicating the logic from flickity in user-land code). The solution assumes that you have `pageDots: true` in flickity options:

```javascript
const renderDots = () => {
    el.querySelector(
        '.custom-page-dots'
    ).innerHTML = flkty.pageDots.dots.map(el => '<li></li>').join('')

    el
        .querySelectorAll('.custom-page-dots li')
        [flkty.selectedIndex].classList.add('active')
    ;[...el.querySelectorAll('.custom-page-dots li')].map(li =>
        li.addEventListener('click', e => {
            e.preventDefault()

            flkty.select(
                [...li.parentNode.querySelectorAll('li')].indexOf(li)
            )
        })
    )
}

renderDots()

flkty.on('select', () => renderDots())
flkty.on('resize', () => renderDots())

```
