### ISSUE TITLE
Always initialising Flickity

### ISSUE THREAD

**Issue by dvodvo** [metafizzy/flickity#426]
The following is not fully a flickity problem.  It is one, however, of usage under ruby on rails. 

Turbolinks is designed to  [speed up the process of loading a page](http://guides.rubyonrails.org/working_with_javascript_in_rails.html#turbolinks). With flickity, this creates undesired behaviours as some scripts (this is the case of flickity) are not properly instantiated (for example when navigating from one page to the same, but with a change in parameters).

Accordingly, I am looking for a way to ensure that it is universally loaded, including special functions such as asNavFor, considering placing something like the following at the end of the body

`$(document).on('page:load', function() {
  new Flickity('some-setup-data-here');
});`

What is the best way to proceed?

**Comment by desandro** [comment]
`asNavFor` does use `setTimeout`, as the nav carousel has to wait for the main carousel to first be initialized. It's a hack, but both Flickity instances should be initialized after `setTimeout( ..., 20 )`

``` js
$(document).on('page:load', function() {
  new Flickity('some-setup-data-here');
  setTimeout( function() {
    // both instances now initialized.
  }, 20 )
});

**Comment by dvodvo** [comment]
"some-setup-data-here" being a placeholder, and not having dissected the packaged version, what string(s) should be invoked here?

**Comment by desandro** [comment]
I'm not sure I understand. You should initialize [Flickity the same way with JS](http://flickity.metafizzy.co/#initialize-with-vanilla-javascript), the only difference would be the event — `page:load`, instead of `ready`.

**Comment by dvodvo** [comment]
OK.  will try that.  Thank you for a useful and elastic tool.

**Comment by dvodvo** [comment]
Close... Initialising `carousel-nav` and `carousel-main`solves those elements.  However the arrow navigations dropped fo oth main and nav sections.

**Comment by davideghz** [comment]
I put the following in a `custom.js` in my `assets` folder (Rails5.1 app) but the carousel is not Initialized

```
$(document).on('page:load', function() {

  var elem = document.querySelector('.HowItWorks');

  setTimeout( function() {
    var flkty = new Flickity( elem, {
      // options
      cellAlign: 'left',
      contain: true
    });
  }, 20 )
});
```
