### ISSUE TITLE
Multiple parallax

### ISSUE THREAD

**Issue by code-a-la-mode** [metafizzy/flickity#428]
I'm trying to do three rows of Flickity "Keyhole Parallax," but the js only counts the first carousel and no parallax movement is applied to the remaining two rows.  I tried to use the Button Container Pen made for another issue but I couldn't integrate the two scripts as I am not familiar enough with js and trial and error didn't cut it. 
Would it be possible to make a pen to demonstrate this as an option? I'd like to use it in my project and this will be my last step to complete it. 

**Test case:**http://codepen.io/code-a-la-mode/pen/XKBPgA

**Comment by desandro** [comment]
Since this demo has multiple Flickity instances, we'll need to keep track of separate groups of images for separate scroll events. One way to do this is to loop through each `.carousel` element with `.each()`.  See demo http://codepen.io/desandro/pen/db9591486f5e6010941cc2dacf0d81b5/

``` js
$('.carousel').each( function( i, carousel ) {
  var $carousel = $( carousel );
  $carousel.flickity({
    imagesLoaded: true,
    percentPosition: false,
  });

  var $imgs = $carousel.find('.carousel-cell img');
  // get Flickity instance
  var flkty = $carousel.data('flickity');

   $carousel.on( 'scroll.flickity', function() {
    flkty.slides.forEach( function( slide, i ) {
      var img = $imgs[i];
      var x = ( slide.target + flkty.x ) * -1/3;
      img.style[ transformProp ] = 'translateX(' + x  + 'px)';
    });
  });
});
```

**Comment by code-a-la-mode** [comment]
Thanks, David.

I was re-declaring a new container name with a separate function for each carousel row: $('.carousel_1’)… $('.carousel_2’)   etc…  Besides redundant scripting, is there a downside to this approach?

It’s nice to have the option to give each one its own set of variables, but its not worth a cumbersome script. Any input? (I’m pretty new to js)

I’m getting some great depth-illusion by finding the balance between margin-width, oversizing the image, and cell/cell img ratio of motion. I’ll post one on Codepen when I’m done. I’ve also got it in my head to do a full page 4 rows 6 cells layered parallax of one large image in 24 cells, synchronized with an animation platform like GSAP for a high-tech flip-book effect.

Anyway, thanks for the help and thanks for the plugin.

Todd Haney
