### ISSUE TITLE
Crazy powerful flick on iOS

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#43]
On iPad, I'm able to do a super powerful flick sometimes. Like start at cell 0 and the flick zooms past cell 10 before snapping back into place.

It's a timing issue or touch position issue most likely.

**Comment by danielflodin** [comment]
Just thought I'd add to this that I'm experiencing something very similar to this happening more or less all the time on iOS 7 (iPhone). It will just skip to the first/last one (depending on direction) at random while flicking through the cells. This is happening in all the instances I've tested, including all the ones on flickity.metafizzy.co.

**Comment by desandro** [comment]
@danielflodin: 

> I've had some issues on the iPhone with the carousel going from first to last cell immediately in one flick (similar to #43) as well as sometimes skipping through multiple slides.
> 
> I've made a video of this which is available here. It is recorded on http://flickity.metafizzy.co/, but is basically appearing in all instances I've come across. In the recording I had to exaggerate my flicks with the mouse in order to similate what I'm experiencing. On the real device though I'd say that I use pretty much just regular swipes.
> 
> Is this a threshold issue or something or what could it be? Seeing as Flickity is working beautifully on both my iPad and on desktop I'm also thinking of whether or not it has something to do with the smaller screen size/swipeable area making it more sensitive??

**Comment by desandro** [comment]
No one else has chimed in. Closing. :ghost:

**Comment by iamkevingreen** [comment]
I'm having this issue right now on iOS Chrome and Safari. The issue doesn't occur on my android device only with iOS.

Touch swipe works perfectly but actually clicking the arrows occasionally calls a double click.  

I added a log to .on 

```
      var slideshow = new Flickity(slides, {
        contain: true,
        wrapAround: true,
        arrowShape: {
          x0: 35,
          x1: 75, y1: 45,
          x2: 80, y2: 40,
          x3: 45
        }
      });

    slideshow.on('cellSelect', function() {
      var index = slideshow.selectedIndex;
      console.log('cell on select', index);
    });
```

on iOs the .io('cellSelect') is firing twice on a single click of the prev/next arrows.

**Comment by iamkevingreen** [comment]
Seems the last iOS update solved this. :dancer:
