### ISSUE TITLE
Change groupCells on-the-fly

### ISSUE THREAD

**Issue by andredalmolin** [metafizzy/flickity#431]
There is a way to change groupCells on-the-fly in Flickity?
I made an Pen to be more clear: http://codepen.io/andredalmolin/pen/AXPRjW

Try resizing the window. The CSS will change the width of the cells from 25%, 33.33%, 50% to 100%, so the page starts with 4 cells on the viewport, then 3, 2, and finally only one cell on the viewport.
But because I cant change groupCells, when each cell is 100% width, the carousel jumps 2 of them, because of groupCells option.

So, there is a way to change that on-the-fly or only in inicialization?
On inicialization there is a issue on my layout, because on mobile devices, the user can change the view mode to portrait or landscape, and view 1 ou 2 cells respectlly on the viewport.

**Comment by sumobi** [comment]
👍 This would be great

**Comment by desandro** [comment]
[You can set `groupCells: true` or `groupCells: '100%'`](http://flickity.metafizzy.co/options.html#groupcells). Then use CSS to change the width of cells to fit within that width of the carousel.

``` js
groupCells: true
// if set to true,
// group cells that fit in carousel viewport

groupCells: '100%'
// if set to a percent string,
// group cells that fit in the percent of
// the width of the carousel viewport
```

**Comment by pr1ntr** [comment]
I actually was wondering the same thing except my use case is different. I have a gallery that opens up a larger image and pushes the gallery down to be the navigation for the larger images. There are always about 6 cells (16.6667%) width. I want to turn off groupCells when the larger zoomed in image is active so the user can use the left/right arrows to move individually through the cells. 

I tried changing flickity.options.groupCells = true/false but that didn't really effect any changes.

**Comment by desandro** [comment]
@pr1ntr Sorry, Flickity does not support changing GroupCells values on the fly.

**Comment by pr1ntr** [comment]
After looking over the source I actually got it to work by doing this: 
```
flckty.option({groupCells: true/false});
flckty.reloadCells();
```
I imagine you can change any option on the fly this way.
