### ISSUE TITLE
Setting the 'is-selected' to second cell for example or we can specify the number of cell

### ISSUE THREAD

**Issue by DamirPecnik** [metafizzy/flickity#432]
If i set the cellAlign to 'center' the is-selected is set on the center cell.

Is it possible to adjust the 'is-selected' so it would be set to for example on the cell on the left site from the center cell? or if we could add a number for example add it to the 3 cell ?

**Comment by desandro** [comment]
Sounds like you're asking for something close to adding `is-next` and `is-previous` classes. See demo http://codepen.io/desandro/pen/MagWrN

**Comment by DamirPecnik** [comment]
Thanks ;) I needed this ;)
