### ISSUE TITLE
Multiple Flickity carousels with captions

### ISSUE THREAD

**Issue by studiolathe** [metafizzy/flickity#433]
I am using this [code](http://codepen.io/desandro/pen/OPQxpO) from the Flickity demo's to display img captions. Works perfectly on the first instance of a slider but when implementing multiple carousels on one page, the first sliders caption's are repeated in each slider.

Is there way to select each individual slider? Sorry novice understanding of JS.

Code below —
```
$(document).ready(function() {

  var $carousel = $('.main-carousel').flickity({
    cellSelector: 'img',
    imagesLoaded: true,
    wrapAround: true,
    percentPosition: false,
    prevNextButtons: false,
    pageDots: false
  });

  var $caption = $('.caption');
  // Flickity instance
  var flkty = $carousel.data('flickity');

  $carousel.on( 'select.flickity', function() {
    // set image caption using img's alt
    $caption.text( flkty.selectedElement.alt )
  });
});
```

Thanks for any help!!

**Comment by desandro** [comment]
I recommend wrapping each set of carousel and caption in a container element

``` html
<div class="carousel-container">
  <div class="carousel">
    ...
  </div>
  <p class="caption">...</p>
</div>
```

Then use jQuery `.each()` to iterate through each `.carousel-container` separately, so the correct `flkty` and `$caption` variables can be associated with the $carousel.

``` js
$('.carousel-container').each( function( i, container ) {
  var $container = $( container );

  var $carousel = $container.find('.carousel').flickity({
    cellSelector: 'img',
    imagesLoaded: true,
    percentPosition: false
  });
  var $caption = $container.find('.caption');
  // Flickity instance
  var flkty = $carousel.data('flickity');

  $carousel.on( 'select.flickity', function() {
    // set image caption using img's alt
    $caption.text( flkty.selectedElement.alt )
  });
  
});
```

See demo http://codepen.io/desandro/pen/1a0d3b6e582b489d611605cc715f0494/
