### ISSUE TITLE
Demo : Is-previous and is-next cell classes, dealing with WrapAround option ?

### ISSUE THREAD

**Issue by laurent-d** [metafizzy/flickity#434]
Hi @desandro,

I m coming back with another question about your demo of adding next and previous classes on slider : http://codepen.io/desandro/pen/MagWrN

Do you think it's possible to make it work with wrapAround option ? (http://flickity.metafizzy.co/options.html#wraparound)

It seems not doing the job on the first slide after the loop..

Regards

**Comment by desandro** [comment]
See demo http://codepen.io/desandro/pen/wWQQwN . You need to `modulo` the previous and next index around `slides.length`

``` js
  var previousI = fizzyUIUtils.modulo( this.selectedIndex - 1, this.slides.length );
  var nextI = fizzyUIUtils.modulo( this.selectedIndex + 1, this.slides.length );
  this.previousSlide = this.slides[ previousI ];
  this.nextSlide = this.slides[ nextI ];
```

**Comment by laurent-d** [comment]
You made my day sir !
Thanks 👍
