### ISSUE TITLE
Custom handles (dragging)

### ISSUE THREAD

**Issue by thomasdebruin** [metafizzy/flickity#435]
Is there a way to define a custom handle (dragging) through the API? I have a caroussel where only one specific dom element functions as handle for the draggability. Right now I achieved this by hardcoding:
`this.handles = [ this.viewport ];`
into something like this:
`this.handles = $('#myhandlename');`

**Comment by desandro** [comment]
Thanks for this question. There is no way to set a specific handle via Flickity's options, but you can hack it with the code you proposed

``` js
// jQuery
var $carousel = $('.carousel).flickity();
var flkty = $carousel.data('flickity');
flkty.handles = $('.carousel-custom-handle');

// vanilla JS
var flkty = new Flickity( '.carousel' );
flkty.handles = [ document.querySelector('.carousel-custom-handle') ];
```

**Comment by thomasdebruin** [comment]
Thnx for the quick response! This 'hack' better than mine, I hacked the source file.

Unfortunately the cleaner hack doesn't work for me: proto.bindDrag overrules it again with the viewport, and the whole thing becomes draggable, what am I doing wrong?
Somehow I have to update the binding, any thoughts?

**Comment by desandro** [comment]
Could you provide a **reduced test case** so we can work on this together? See links in [the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by thomasdebruin** [comment]
Jep, good idea:
https://codepen.io/thomasdebruin/pen/WxYWqd
The custom handle is added, but I need to get rid of the default viewport handle.
Just let me know if you need more info.

**Comment by desandro** [comment]
Thanks for that! Right, I the trouble was with event binding. Flickity has a couple of methods to handle this: `bindHandles` and `unbindHandles`. See demo https://codepen.io/desandro/pen/862aa8a6ebfcb8d974c8fb9613e78a6f/

``` js
  var $carousel = $('.carousel').flickity();
  var flkty = $carousel.data('flickity');
  flkty.unbindHandles();
  flkty.handles = $('.custom-handle');
  flkty.bindHandles();
```

**Comment by thomasdebruin** [comment]
Thanks, solved!
