### ISSUE TITLE
asNavFor and freeScroll

### ISSUE THREAD

**Issue by bohdanafanasyev** [metafizzy/flickity#436]
When freeScroll is set to true and carousel was flipped the navigation doesn't respond until the carousel stops. Is there a way to make it work?

**Comment by desandro** [comment]
Thanks for reporting this issue. 
Could you provide a **reduced test case**? Try forking [the asNavFor CodePen](http://codepen.io/desandro/pen/wByaqj). See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
