### ISSUE TITLE
ES2015 module + jQuery -> $(elem).flickity undefined

### ISSUE THREAD

**Issue by raphaelokon** [metafizzy/flickity#438]
Hi there. I am normally using Flickity with vanilla JS in my ES2015 modules with no problems. Today I tried to use the jQuery API but I get an error as the `flickity` property is not found on the object …
Do you have any clues?

``` js
import $ from "jQuery";  // Globally available
const flkty = $("elem").flickity({…}); // TypeError: $("elem").flickity is not a function. …
```

**Comment by desandro** [comment]
You'll likely need to import jQueryBridget. It would be [similar to using Browserify](http://flickity.metafizzy.co/extras.html#browserify).

``` js
import $ from "jQuery";
import jQueryBridget from "jquery-bridget";
import Flickity from "flickity";
// make Flickity a jQuery plugin
jQueryBridget( 'flickity', Flickity, $ );
// now you can use $().flickity()
// okay to use $().flickity()
const $elem = $("elem").flickity({…});
```

**Comment by raphaelokon** [comment]
Cheers. Will give it a try. My obvious workaround was to use vanilla selector and Flickity API … `$` for the rest :>
