### ISSUE TITLE
Flickity data-flickity-bg-lazyload + Lazysizes data-bgset

### ISSUE THREAD

**Issue by raphaelokon** [metafizzy/flickity#439]
Hi.

I would like to combine Flickity's `data-flickity-bg-lazyload` + Lazysizes `data-bgset`.

I really like Flickity's declarative way to lazy load its images (eg. lazy load only next-siblings not exponential algorithmic like `lazysizes`) … but it lacks the responsive features that `lazysizes` offers. What are your opinions @desandro and @afarkas on combining those.

Flickity API for bgLazyLoad: http://flickity.metafizzy.co/options.html#bglazyload
Lazysize bg-set demo: http://jsfiddle.net/trixta/w96o9xm5/

**Comment by desandro** [comment]
Using lazysizes's bgset with Flickity looks like a good use case to build a solution with their APIs. See [lazysizes JS API](https://github.com/aFarkas/lazysizes#js-api) and [Flickity select event](http://flickity.metafizzy.co/events.html#select)

**Comment by raphaelokon** [comment]
Thanks. I was indeed reading `lazysizes` JS API to marry those two. I am closing this thread but will keep you guys posted on my progress.

**Comment by raphaelokon** [comment]
Got it working. Flickity should have a plugin/extension API :D

**Comment by desandro** [comment]
It does! Take a look at any of the .js files to see how they work. For example [lazyload.js](https://github.com/metafizzy/flickity/blob/v2.0.3/js/lazyload.js)

**Comment by raphaelokon** [comment]
@desandro Cheers.

**Comment by rzschoch** [comment]
@raphaelokon Do you remember, how you got it working nearly 2 years ago?
