### ISSUE TITLE
Callback on Prev/Next buttons and dots

### ISSUE THREAD

**Issue by bradfrost** [metafizzy/flickity#442]
Hey there!
Thanks so much for an amazing project. 

Question: I'm trying to update a list of thumbnails to coincide with Flickity's current index.

[Here's a Codepen](http://codepen.io/bradfrost/pen/rLgaQZ) that hints at what I'm talking about. I want the `.is-active` class on my `.button-group`'s `.button`s to update to the appropriate index when Flickity's prev/next buttons and dots are pressed. 

I'm looking at the [events api](http://flickity.metafizzy.co/api.html#events) and I see how it's possible to update Flickity from other elements, but don't see a callback or something for me to latch onto once Flickity updates via its prev/next buttons and dots. 

Does anyone have an idea on how I can accomplish this?

**Comment by rbvea** [comment]
@bradfrost you could use the "settle" event and the slider's selectedIndex option.  Here's a pen: http://codepen.io/anon/pen/bZyNzX

The settle event documentation: http://flickity.metafizzy.co/events.html#settle

**Comment by desandro** [comment]
I recommend using the `select` event. See demo http://codepen.io/desandro/pen/225621f3e3b2f2595268303797f04297/

Take a look at the [Custom navigation UI demo](http://flickity.metafizzy.co/extras.html#custom-navigation-ui), CodePen http://codepen.io/desandro/pen/emVRjv

**Comment by bradfrost** [comment]
@rbvea @desandro AWESOME, thanks a million for the quick replies. Thanks a bunch!
