### ISSUE TITLE
Resize doesn't work when reducing browser width

### ISSUE THREAD

**Issue by shainanigans** [metafizzy/flickity#444]
My carousel determines its viewport height based on the content of each cell. The height of this content changes depending on the browser size. 

When I go from my mobile view to my largest desktop view, `resize: true` seems to work as it should; the viewport's height changes to accommodate the new content size. However, when I reverse the process, going from the largest desktop view to mobile view, the viewport's height is not reset. Instead, the height stays at the desktop viewport's size.

I have initialised the carousel using:
```
var carousel = $('.carousel').flickity({
	wrapAround: true
});
```

I've tried forcing the resize to trigger at each breakpoint (using enquire js) with `carousel.flickity('resize');`, but no luck.

Reduced test case: http://codepen.io/shainanigans/pen/XKLoOX

**Comment by desandro** [comment]
Thanks for reporting this issue and for submitting a reduced test case!  Looks like we can fix this by  removing   `.carousel-cell { min-height: 100%; }`

See demo http://codepen.io/desandro/pen/e8202fd604f8b66b5e71c8941b45145b/

**Comment by shainanigans** [comment]
Thanks @desandro! Now that I'm thinking about it, it makes sense why that was happening.

**Comment by 1101blueli** [comment]
Hi, I am experiencing the same issue from your demo

.flickity-slider{ transform: translateX(-0.3%); }
http://codepen.io/desandro/pen/e8202fd604f8b66b5e71c8941b45145b/

The image is slightly shifted to the left when the initial load. Have to resize the browser to make it back to centre. Any idea how I may fix it?

Thanks
