### ISSUE TITLE
All slides are visible on page load

### ISSUE THREAD

**Issue by xstortionist** [metafizzy/flickity#445]
![fick](https://cloud.githubusercontent.com/assets/4481041/17990578/21f39a66-6b05-11e6-8871-ffb625a3a01a.jpg)

Is there anyway to make only the active slide appear on page load? Right now, after the page load and the carousel initializes everything works as expected.

Thanks!

**Comment by desandro** [comment]
You can fade in Flickity after initialized in JS. See demo http://codepen.io/desandro/pen/KVwVqa/

**Comment by xstortionist** [comment]
@desandro thanks, I actually did something similar but without a fade effect.
