### ISSUE TITLE
Sliding Animation

### ISSUE THREAD

**Issue by madebydominick** [metafizzy/flickity#45]
Is there any way to decrease the force of the physics on slide?

Every time I slide, using drag or arrows (even if it is one slide), it bounces quite heavily.

See comparison gifs below:

![physics-demo](https://cloud.githubusercontent.com/assets/6449278/6149873/aa21a926-b203-11e4-8037-78343ae75507.gif)
My flickity instance, loaded with this code:

```
$('.md-iphone-5 .md-screen').flickity();
```
![physics-demo-flickity-example](https://cloud.githubusercontent.com/assets/6449278/6149914/ee331500-b203-11e4-83c2-6417397b220e.gif)
`single.html` flickity instance in the `sandbox` folder.

How can this be resolved so I can just have the smooth transition, rather than a bounce?

**Comment by pavethiran** [comment]
To adjust the bounce just use the `friction` setting. I found out while testing `0.4` is a good value for a smooth sliding effect :smile:

**Comment by madebydominick** [comment]
@pavethiran Cheers, mate! I never even noticed that setting. :smile:

**Comment by desandro** [comment]
I haven't documented `friction` because I'm likely to change it to improve the bounciness you've pointed out. Right now the physics works differently based on the size of the cells. It should be more consistent.

**Comment by madebydominick** [comment]
@desandro, I thought I hadn’t seen it anywhere.  Cheers for the response.

**Comment by spacecat** [comment]
Experienced this one today as well when trying to get flickity to flick between slides faster. Got super long bounce times. There seems to be a limit in when the slides start to bounce when clicking on arrows. The setting combination in the documentation works quite well however. So +1 for improving bounciness features and docs! :-)
