### ISSUE TITLE
Ie10 Adaptive height bug

### ISSUE THREAD

**Issue by aderaaij** [metafizzy/flickity#450]
It seems like I've got the same ie10 issue described here: https://github.com/metafizzy/flickity/issues/193

I've made a new testcase as the last one is online.

**Test case:** http://codepen.io/aderaaij/full/amorVY/

Regardless, thx for the awesome slider!

**Comment by max-mykhailenko** [comment]
Have same problem

**Comment by desandro** [comment]
Thanks for reporting this issue. This sounds like the same issue as #205. See solutions there
