### ISSUE TITLE
Navigating to next photo from popup

### ISSUE THREAD

**Issue by GemeenAapje** [metafizzy/flickity#451]
Hi guys, I hope someone can help me.

If I use the staticclick function to open a popup box with an enlarged photo in... is there any way in that new popup box to create a button that will navigate to "next" or "previous" photo in the original carousel?
Or, if I know for example that it was item 3 that was clicked, then how I could force a staticclick on item 2 or item 4.

Thanks for the awesome script!!!
Matt

**Comment by GemeenAapje** [comment]
Ok I ALMOST have it!  I have the code to jump to the next element, but I cannot trigger the click.
So far...

 $( "#albid_1" ).flickity( 'next', true );
 $( "#albid_1" ).flickity('staticClick');

It moves, but doesn't trigger click.

I've also tried...  $( "#albid_1" ).flickity().click()

Anyone? Please?

Thanks!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by GemeenAapje** [comment]
Hi Desandro

I don't believe I've found a bug.  I simply cannot find the API documentation I need to work this out.

I can see how I can trigger things from external buttons, but i don't know how to trigger a static click.  Do you know if it's possible to do?

Thanks
Matt

**Comment by desandro** [comment]
staticClicks cannot be triggered. If you have a reduced test case, then I can better understand what you're trying to do and provide a solution.

**Comment by KrielkipNL** [comment]
A flickery carousels with on each slide a image. When u click on the image. it opens a lightbox with the bigger image. And then u want a next / prev button in de lightbox, which also controles the flickery below?

Maybe this helps? http://flickity.metafizzy.co/options.html#asnavfor
In the lightbox u also have a flickity that works with the main one.

**Comment by GemeenAapje** [comment]
Here you go my friends...
Username: desandro
Password: testtest

Example page: https://www.bikermatch.co.uk/sites/bm/profiles/view_profile.asp?user_id=9

When you view your own profile and add photos there's also an options menu for editing each photo.  Your link for this test account would be...
https://www.bikermatch.co.uk/sites/bm/profiles/view_profile.asp?tab=photos&user_id=74866

See what you think.

Thanks!

**Comment by desandro** [comment]
Sorry, but I won't be able to [debug this issue without a **reduced test case**](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues)

+ A reduced test case clearly demonstrates the bug or issue.
+ It contains the bare minimum HTML, CSS, and JavaScript required to demonstrate the bug.
+ A link to your production site is not a reduced test case.
