### ISSUE TITLE
initialIndex with selector

### ISSUE THREAD

**Issue by chrispcb** [metafizzy/flickity#453]
Hello,
`initialIndex` accepts only number. 
`$carousel.flickity( 'selectCell', '.cell2' );` accepst number and selector.

it would be good that `initialIndex`also accepts selector.

**Comment by desandro** [comment]
Not a bad suggestion!

**Comment by evgenyshev** [comment]
Yes, that would be great. I need it very much.

**Comment by desandro** [comment]
Flickity now has [`selectCell` method,](https://flickity.metafizzy.co/api.html#selectcell) which you can pass a selector string:

``` js
// jQuery
$carousel.flickity( 'selectCell', value, isWrapped, isInstant )
// vanilla JS
flkty.selectCell( value, isWrapped, isInstant )
```

**Comment by evgenyshev** [comment]
I think you do not quite understand the task. I (and the commentator above) need to assign, as a initialIndex element, a carousel with a certain class.

**Comment by evgenyshev** [comment]
I apologize, I understood what you meant. If someone needs:
html
`<div class="carousel">
  <div class="carousel-cell"></div>
  <div class="carousel-cell"></div>
  <div class="carousel-cell"></div>
  <div class="carousel-cell"></div>
  <div class="carousel-cell"></div>
  <div class="carousel-cell"></div>
  <div class="carousel-cell"></div>
  <div class="carousel-cell yes"></div>
</div>`

js
`var $carousel = $('.carousel').flickity({
  groupCells: true
});

$carousel.flickity( 'selectCell', '.yes' );`
