### ISSUE TITLE
IE10 mostly broken

### ISSUE THREAD

**Issue by andycook71** [metafizzy/flickity#454]
Hi,

Flickity looks great but I need IE10 support. I thought perhaps you had dropped IE10 support as none of the examples seem to work, but then I noticed that the Parallax example *does* work in IE10. Perhaps there is a recent bug introduced that stops all the other examples working?

I haven't provided a test case, any of your examples except Parallax will do!

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this bug! This was related to #441. The demos that aren't working are using HTML init, where as the demos that are working are using JS init. This will be fixed in the next version. This bug is now fixed in Flickity v2.0.4. Try refreshing!

**Comment by andycook71** [comment]
That's awesome thanks - I'll be getting a licence purchased :)
