### ISSUE TITLE
event.preventDefault error on touch device

### ISSUE THREAD

**Issue by arthurmuchir** [metafizzy/flickity#455]
On touch device (chrome simulation does the same), I get this error when I click on the next or previous button. I use last version of flickity (2.0.3)

`drag.js:85 Uncaught TypeError: event.preventDefault is not a function`

I got the error on your codepen.
[codepen](http://codepen.io/desandro/pen/azqbop)

**Comment by desandro** [comment]
Thanks for reporting this issue. This bug has been fixed with #440 and #442 in Flickity v2.0.4.
