### ISSUE TITLE
Implementing a slide duration animation graphic

### ISSUE THREAD

**Issue by coolwebs** [metafizzy/flickity#456]
This is not an issue per se, but rather a request. Would be nice if there was a function within Flickity which could show the user how much longer the slide currently displaying will be showing until the next slide transition.

I've modified the script here, http://www.slq.qld.gov.au to include a pause/play toggle button. Would work really well if I could get the background (stroke) of the toggle to animate a fill in a clockwise direction to show how long the slide will display for.

Hope this makes sense. This all stems from making the Flickity Slider more accessible (i.e. WCAG standards).

**Comment by desandro** [comment]
Thanks for your feature request. I'd prefer to keep this kind of behavior outside of Flickity and up to developers like yourself.
