### ISSUE TITLE
iOS 10 bug - page scrolls while dragging

### ISSUE THREAD

**Issue by sibianyu** [metafizzy/flickity#457]
i found a bug when i use the browsers in iOS 10. it can not slide smoothly.

**Comment by laurent-d** [comment]
+1

**Comment by luruke** [comment]
👍 
It looks that when swiping, a slightly scroll up/down of the page cause the swipe to being interrupted.

**Comment by simeydotme** [comment]
ios10 is a piece of shit... I might have a go at handling this in a PR, can't believe how bad it feels.

My observation is that as you swipe the carousel left/right, it doesn't lock the browser's vertical scrolling anymore. Causing the user to get all dizzy as the page jumps around vertically and horizontally. No idea yet of the solution, but it's a terrible experience, especially if a full-page carousel on a mobile is like your main selling point.

**Comment by hvbe** [comment]
+1

**Comment by three60five** [comment]
+1 

iOS 10 (no matter if you use Safari or Chrome) behavior is very different now. Flicking left and right is much more difficult as the browser tries to scroll up and down with the slightest movement in those directions. Honestly, it is no longer easy and fun to flick between slides. As stated above, it is very noticeable on full-page carousel on iPhones. 

Any chance you have seen this yet @desandro ?

**Comment by desandro** [comment]
Thanks all or have chimed in. I will be updating my personal phone to iOS 10 today. Then I'll be able to debug this issue.

It sounds like the hack to prevent vertical scrolling is no longer working.

**Comment by beneshort** [comment]
+1

**Comment by bruceontheloose** [comment]
+1

Thanks for creating Flickity, David!

**Comment by adrienlamotte** [comment]
+1 ! :)

**Comment by three60five** [comment]
Any update on this issue? Where is the hack to prevent vertical scrolling in the source code?

**Comment by diegopamio** [comment]
+1

**Comment by benjibee** [comment]
Oh no… I have a whole website ready to go and just ran into this bug right before launch. I tried some hacks to no avail, anyone out there have a fix?

**Comment by saschanos** [comment]
yes; try this (first comment from supercranky):
https://github.com/RubaXa/Sortable/issues/973

**Comment by desandro** [comment]
Flickity v2.0.5 has been released with a couple fixes for iOS10 scroll behavior. Please upgrade to the latest version to check that this issue has been addressed.

1. The drag won't be canceled if vertical scrolling does occur
2. iOS 10 has a bug where `event.preventDefault()` will not cancel window scrolling. You can fix this behavior by adding an innocuous event handler.

``` js
window.addEventListener( 'touchmove', function() {})
```

Thx @saschanos and @supercranky for finding this solution. It's a bit scary that this hack works, but it shouldn't have unforeseen consequences *crosses fingers*.

**Comment by jzimdars** [comment]
Thanks for this @desandro. It's utter nonsense that this should work but it totally does. Fixed a similar issue in Basecamp with the same solution. Reminds me of similar mystery solutions for [this issue](http://alxgbsn.co.uk/2011/10/17/enable-css-active-pseudo-styles-in-mobile-safari/).

**Comment by luruke** [comment]
Thanks @desandro .
Tried out on different projects and it works great

**Comment by desandro** [comment]
I'm closing this issue as resolved. Please open a new issue if you run into a similar problem. Thank you for your feedback!

**Comment by MohammadKani** [comment]
.scrolling-content {
   overflow-y: scroll;
   -webkit-overflow-scrolling: touch;
   height:100%; //A value other than height:auto needs to be set
}
