### ISSUE TITLE
Slides not showing until page refresh

### ISSUE THREAD

**Issue by bjtalbot1** [metafizzy/flickity#458]
Hoping you can give me a clue, even though I'm not sufficiently knowledgeable to create a reduced test case....

My product pages (here's one: http://paramusbuildingsupply.cloudaccess.host/products/plygem/) use a Flickity slider. The slides don't always appear on first page load; sometimes it takes a refresh (or multiple refreshes) to reveal the slides. The prev/next arrows do appear right away, though. Any idea what might fix this?

THANKS!!

**Comment by desandro** [comment]
It may be unloaded images. See [imagesLoaded option](http://flickity.metafizzy.co/options.html#imagesloaded)

**Comment by bjtalbot1** [comment]
Thanks, I added that option, and haven't been able to reproduce the problem so far since—fingers crossed!

**Comment by achilesnikkolo** [comment]
I have the same problem and I also try the imagesLoaded but it's still the same
