### ISSUE TITLE
How to use staticClick and initialize with data-flickity?

### ISSUE THREAD

**Issue by xstortionist** [metafizzy/flickity#459]
I'm wanting to use staticClick but I'm initializing carousel with data-flickity. Does the API support initializing this way or do I need to use javascript per all of the demos listed on the site?

**Comment by desandro** [comment]
If you're using `staticClick` logic in JavaScript, then you might as well initialize in JavaScript.

However, you do not have to. You can use [`Flickity.data()` to get the Flickity instance](http://flickity.metafizzy.co/api.html#flickity-data)

``` js
// get Flickity instance
var flkty = Flickity.data('.carousel');
// do stuff
flkty.on( 'staticClick', function() {...});
```

**Comment by xstortionist** [comment]
@desandro thanks! I'm going to give it a shot.
