### ISSUE TITLE
Adjust slide animation time

### ISSUE THREAD

**Issue by FabianGabor** [metafizzy/flickity#46]
Would be nice to be able to set the slide transition time. Maybe by just setting the end translate coordinate and animate it with CSS.

**Comment by madebydominick** [comment]
+1 to this, guessing this will probably be a future feature?

**Comment by desandro** [comment]
Yes, this would be a nice pro-user feature to have. Right now the physics variables are kind of hard-coded in. I'll have to return to formalize the options to do so. It's not quite ready for public use at the moment.

**Comment by zslabs** [comment]
+1

**Comment by gordonwes** [comment]
+1

**Comment by r-flash** [comment]
+1

2015-03-12 9:26 GMT+01:00 gordonwes <notifications@github.com>:

**Comment by ChristophLabacher** [comment]
+1

**Comment by ChristophLabacher** [comment]
The intern physics are pretty cool, but for me having basic CSS3 animation would be enough, and I believe that to be true for many cases. Setting your own transition time and maybe easing function would make it easy to customize the animation and still look natural. This is of course only true if draggable is set to false, so it might be bound to that option.

**Comment by oppenheimer-** [comment]
+1

**Comment by StefanEndress** [comment]
+1

**Comment by paul-straetmans** [comment]
+1
would like to use no animations at all on a static click

**Comment by bealrx** [comment]
+1

**Comment by impsart** [comment]
+1

**Comment by eelkeh** [comment]
+1

**Comment by drastick** [comment]
+1

**Comment by VincentPeters** [comment]
+1

**Comment by mattisahuman** [comment]
If custom times aren't possible, would be nice to have options like 'normal', 'fast', 'slow', 'none'.

**Comment by sebastiangraz** [comment]
+1

**Comment by anthony0579** [comment]
+1

**Comment by 78doog** [comment]
+1

**Comment by vajkri** [comment]
+1

**Comment by desandro** [comment]
### [The `selectedAttraction` and `friction` options are now documented](http://flickity.metafizzy.co/options.html#selectedattraction-friction)

> `selectedAttraction` and `friction` are the two options that control the speed and motion of the slider.
> 
> `selectedAttraction` attracts the position of the slider to the selected cell. Higher attraction makes the slider move faster. Lower makes it move slower. Default `selectedAttraction: 0.025`.
> 
> `friction` slows the movement of slider. Higher friction makes the slider feel stickier and less bouncy. Lower friction makes the slider feel looser and more wobbly. Default `friction: 0.28`.

``` js
selectedAttraction: 0.2,
friction: 0.8
// higher attraction and higher friction
// faster transitions
```

``` js
selectedAttraction: 0.01,
friction: 0.15
// lower attraction and lower friction
// slower transitions
// easier to flick past cells
```

### [`freeScrollFriction` option documented as well](http://flickity.metafizzy.co/options.html#freescrollfriction)

> Slows movement of slider when freeScroll: true. Higher friction makes the slider feel stickier. Lower friction makes the slider feel looser. Default `freeScrollFriction: 0.075`.

---

Adjusting these options, you should be able to speed up or slow down how the slider moves when transitioning. You still cannot set an arbitrary time, but this should provide enough fine-grain control. Give it a try! :whale:

**Comment by mattisahuman** [comment]
:+1: Thanks, @desandro. Great addition!

**Comment by StefanEndress** [comment]
Thanks man!

**Comment by Hlsgs** [comment]
@desandro `selectedAttraction` and `friction` options are cool, but there is still a case to be made for having a fixed timing on the transition: for example, say one wants to add a progress bar that does something(empties) while the slide is transitioning. I've done this a couple of times with other sliders, but i really wish to migrate my workflow to Flickity because I'm absolutely done with sliders that use clones :)
However, this and #233 are preventing me from doing so.

That being said, if I set `friction: 1`, is there some math that can be done to infer the transition time from the value of `selectedAttraction`?
