### ISSUE TITLE
Visible arrows with all slides contained in viewport

### ISSUE THREAD

**Issue by guttoZ** [metafizzy/flickity#460]
Hello,

I am seeing arrows (and they are clickable) even when all slides are contained within slider viewport. You can see example here: 

http://codepen.io/anon/pen/dpNJpB

I understand this has something to do with cell selection ( https://github.com/metafizzy/flickity/issues/177 ) but is there a way to avoid those arrows when selecting cells is not needed?

**Comment by desandro** [comment]
One option is to use `groupCells: true`. This will group all visible cells into a single slide. Otherwise, you may be able to hack it with this solution https://github.com/metafizzy/flickity/issues/289#issuecomment-157488885
