### ISSUE TITLE
Less.js bug

### ISSUE THREAD

**Issue by mozzillation** [metafizzy/flickity#461]
Hello everyone!

I have errors in using the flickity script with less:  the slides do not flow if i embed the less.js.
How can I fix the problem?

Thx for the support!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
