### ISSUE TITLE
Question: Why select event happened on window resize?

### ISSUE THREAD

**Issue by maximelebreton** [metafizzy/flickity#463]
Hi david, and thank you for the amazing work!

Why when you resize the window, the `select` event is triggered?
**Test case:** http://codepen.io/maximelebreton/pen/ALRWbX?editors=1111

**Comment by desandro** [comment]
The `select` is triggered on resize so that Flickity can properly re-align cells after they have been resized. Consider that a mediq query breakpoints may dramatically change the size or grouping of cells.
