### ISSUE TITLE
almost un-usable on iPhone 6 (iOS10) with video

### ISSUE THREAD

**Issue by shakyShane** [metafizzy/flickity#464]
Hi, thanks for a great library!

However, it seems like there's either a huge regression with regard to touch events in 2.0, or iOS 10 has broken something. 

Either way, all of your demos on my phone are pretty much un-usable with the page jumping up/down as I attempt to 'flick' slides left or right.

please see screen recording - you can't see my actual touches but it's still very clear that as I swipe left/right the screen is moving up/down erratically. 

https://www.youtube.com/watch?v=U9-HiHjGfc0&feature=youtu.be

Let me know if I can provide any more details :)

**Comment by bruceontheloose** [comment]
Hi, @shakyShane. This seems like the same issue reported in #457, if you want to keep an eye on that one, too.

**Comment by desandro** [comment]
Let's keep to #457
