### ISSUE TITLE
Flickity + Magnific Popup Issue On Mobile

### ISSUE THREAD

**Issue by DerekBess** [metafizzy/flickity#465]
http://codepen.io/aaron-stez/pen/ZbxooO

This works as expected on desktop but when you test on a mobile device, the wrong images load on click. Is there any way to correct this issue?

**Comment by desandro** [comment]
After working on this for 30 minutes, I am unable to debug the problem.

+ The problem does happen with Flickity, but does not occur when [Flickity is disabled](http://codepen.io/desandro/pen/b3dc2d87bf09c6720fdf87c2c99f284e)
+ `wrapAround` is not the issue
+ If you size the window to mobile size, the problem does not occur.
+ The code works the same for mobile or desktop.

My only guess is that Magnific Popup has some extra mobile behavior that is messing with the results. You may want to try another solution.

**Comment by xstortionist** [comment]
I been working on it off and on in my spare time. I've debugged with console and find that it definitely something to do with magnific popup because when I add breakpoints I can see where it works. It looks like it double firing but I have not been able to pinpoint exactly where the issue occurs. I appreciate you taking a look and I'll update if I find a solution but I'm probably going to ditch mag popup, doesn't look to be active anymore.

**Comment by xstortionist** [comment]
I had some time this morning to troubleshoot again. Oddly enough, if I do not use static click event there is no issue. Of course, dragging on desktop opens the image but on mobile devices the bug does not occur.

**Comment by xstortionist** [comment]
I ended up getting this to work with Tom's solution of dragstart and dragend events.

`$gallery.on( 'dragStart.flickity', function( event, pointer ) {
        $(this).addClass('is-dragging');
    })

    $gallery.on( 'dragEnd.flickity', function( event, pointer ) {
        $(this).removeClass('is-dragging');
    })`

**Comment by DeoThemes** [comment]
Hey,

Is there a full code version to fix this bug?
I'm having the same problem.

Regards.

**Comment by xstortionist** [comment]
@DeoThemes Yes, you can fix the problem by using dragStart and dragEnd in my example above.

**Comment by DeoThemes** [comment]
@xstortionist I've tried to use this, but no result. What am I missing? Here is my code:

`  var $gallery = $('.mfp-hover');

  // magnific popup bug fix
  var popupItems = $.map( $gallery.find('.gallery-cell a'), function( link ) {
    return {
      src: link.href,
      type: $(link).attr('data-popup-type') || 'image'
    }
  });

  $gallery.on('staticClick.flickity', function(event, pointer, cellElement, cellIndex) {
    if (!cellElement) {
      return;
    }
    $.magnificPopup.open({
      items: popupItems,
      gallery: {
        enabled: true
      },
      closeBtnInside:false,
      callbacks: {
        open: function () {
          $.magnificPopup.instance.goTo( cellIndex );
        }
      }
    });
  });

  // prevent links from opening
  $gallery.on( 'click', 'a', function(event) {
    event.preventDefault();
  });

  $gallery.on( 'dragStart.flickity', function( event, pointer ) {
    $(this).addClass('is-dragging');
  })

  $gallery.on( 'dragEnd.flickity', function( event, pointer ) {
    $(this).removeClass('is-dragging');
  })`

**Comment by xstortionist** [comment]
@DeoThemes can you provide codepen or something similar? Did you add the css to your project to disable pointer events?

**Comment by DeoThemes** [comment]
@xstortionist 
Sure, I added style as well.
Here is my demo - http://deothemes.com/envato/test/index-ny.html

**Comment by xstortionist** [comment]
This is my code that I created:

`// ==================================
// Carousel Gallery
// ==================================

// Define flickity carousel
var $gallery = $('.gallery-carousel').flickity({
    cellAlign: 'left',
    contain: false,
    wrapAround: true,
    imagesLoaded: true,
    groupCells: false,
    adaptiveHeight: true,
    pageDots: false
});

$gallery.on( 'dragStart.flickity', function( event, pointer ) {
    $(this).addClass('is-dragging');
})

$gallery.on( 'dragEnd.flickity', function( event, pointer ) {
    $(this).removeClass('is-dragging');
})

$('.gallery-carousel').magnificPopup({
    delegate: '.gallery-cell > a', // child items selector, by clicking on it popup will open
    type: 'image',
    gallery:{
        enabled:true
    }
});`

**Comment by DeoThemes** [comment]
@xstortionist Thanks a lot, this solution finally solved my problem. You are right about mobile popups, but what about videos? On Apple devices it's the best way to play Youtube/Vimeo videos.

Here is the final code.
In addition I've added some code for video popups as well:

```javascript
$gallery.magnificPopup({
    delegate: '.lightbox-img, .lightbox-video',
    callbacks: {
      elementParse: function(item) {
      if(item.el.context.className == 'lightbox-video') {
          item.type = 'iframe';
        } else {
          item.type = 'image';
        }
      }
    },    
    type: 'image',
    gallery:{
      enabled:true
    }
  });
```

What is your recommendation about parallax? I've tried a lot of plugins, and this is the best I found so far. Or you mean to get rid of it completely? Thanks again for helping. Cheers.

**Comment by xstortionist** [comment]
@DeoThemes I didn't realize you were running youtube and pictures within the portfolio section. In that case, it does make sense to utilize lightbox for videos.

Glad to know that you got it all situated and it's working as expected. The issue has to do with magpopup and not flickity because I've gotten it to work just fine with another carousel plugin.

In regards to parallax, I would simply replace it with background cover. There's no need to sacrifice user experience for some fancy background effect. Parallax tends not to work well on mobile devices and on 4k monitors it uses a lot of hardware resources making the page lag.
