### ISSUE TITLE
Captions not displaying in WP slider

### ISSUE THREAD

**Issue by RogueTiger** [metafizzy/flickity#467]
Hi! I'm following the example for captions here: http://codepen.io/desandro/pen/dPdVNM
and am unable to have the caption actually pulled to display. 

I'm working off WP and WooCommerce, so it just may be that I'm not hooking up everything correctly. I was hoping you'd be able to provide some direction. My reduced test case is here: https://codepen.io/GinnyV/pen/LRjQxr

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Flickity. Thanks for putting this in a CodePen, but it looks like there's some pieces missing

```
woocommerce.js:7 Uncaught ReferenceError: Flatsome is not defined(…)
flatsome.js:63 Uncaught ReferenceError: flatsomeVars is not defined
```

Can you check that the theme is working okay?

**Comment by RogueTiger** [comment]
I checked the theme, it is working fine. I checked the console as well, those errors don't kick back for me on the live site. It may have been something I missed when setting up the pen. 

For instance, I can get the script and caption to work with a static site, but the WP, theme and js is beyond my ability, so I'm reaching out here. Unfortunately, I do mostly front end work. I can figure out most js applications, but I don't understand so much of it. 

Really great script, by the way!

**Comment by desandro** [comment]
Sorry, but I cannot debug this issue with the CodePen you provided. I'll need a reduced test case. Otherwise I won't be able to identify where this issue is occurring.

**Comment by RogueTiger** [comment]
Ok! Lets try this again! I tracked down the issue :)

Here you go: http://codepen.io/GinnyV/pen/LRjQxr

**Comment by desandro** [comment]
Thanks for that. See http://codepen.io/desandro/pen/deb8b14e13463bf93dd9426a28c20792/

1. Looks like your demo is missing jQuery, so I added it. 
2. Flickity is already being initialized in HTML. I've removed the JS init code
3. Our custom code should run after Flickity is initialized, so I wrapped it in `$(document).ready()`

``` js
$( document ).ready( function() {
	
	var $mainCarousel = $('.product-gallery-slider');

	var $caption = $('.caption');
	// Flickity instance
	var flkty = $mainCarousel.data('flickity');

	$mainCarousel.on( 'select.flickity', function() {
		// set image caption using img's alt
		var caption = $(flkty.selectedElement).find('img').attr('alt')
		$caption.text( caption )
	});
});
```

**Comment by RogueTiger** [comment]
David - I wanted to thank you so much for your help! I implemented the changes you made and found there was a conflict with another plugin I was using (the TM Extra Products Option) and ended up having to change only the code wrap, in order to avoid conflicts. The final code became:
`<script>
jQuery(document).ready(function($){
	var $mainCarousel = $('.product-gallery-slider');
	var $caption = $('.caption');
	// Flickity instance
	var flkty = $mainCarousel.data('flickity');
	$mainCarousel.on( 'select.flickity', function() {
		// set image caption using img's alt
		var caption = $(flkty.selectedElement).find('img').attr('alt')
		$caption.text( caption )
	});
});
</script>`

I wanted to share in case others are having the same issue. Thank you so much again for your help!
