### ISSUE TITLE
Random initialIndex

### ISSUE THREAD

**Issue by vilav** [metafizzy/flickity#469]
**Test case:** http://codepen.io/desandro/pen/vEdOKg

Anyway to pass a **random** value into the initialIndex parameter to a random cell is loaded first each time?

**Comment by desandro** [comment]
Yes, you can use `Math.random()` in JS.

``` js
var carousel = document.querySelector('.carousel');
var flkty = new Flickity( carousel, {
  initialIndex: Math.floor( Math.random() * carousel.children.length )
});
```

See demo http://codepen.io/desandro/pen/2d56398416e1fef1b409863e47e79cc3/

**Comment by TheRealJAG** [comment]
Thanks!
