### ISSUE TITLE
asNavFor offsetting menu gallery using transform: translateX

### ISSUE THREAD

**Issue by since1976** [metafizzy/flickity#47]
I have setup a asNavFor gallery that controls another gallery as per [the docs](http://flickity.metafizzy.co/options.html#asnavfor). 

The problem I'm seeing is that there is a ``transform: translateX( )`` being applied to the ``flickity-slider`` div. The value of the transform seems to be different depending on the width of the viewport but essentially if is bumping the whole menu to the left, giving it the appearance of right aligned.
 
![screen shot 2015-02-13 at 8 18 03 am](https://cloud.githubusercontent.com/assets/90833/6175118/e0cd808e-b358-11e4-89b3-abe3ebf62c18.png)

I thought this might be because I had ``dragable: true`` set which would make room for more items but when I set this to ``false`` I see the same behaviour. Further to that, setting that to ``false`` actually disables the ability to control the other gallery using this one.

Adding an additional 
My settings for gallery b are:
```
$('.gallery--as-nav-for-b').flickity({
    asNavFor: '.gallery--as-nav-for-a',
    cellAlign: 'left',
    cellSelector: '.gallery-cell',
    contain: true,
    pageDots: false,
    prevNextButtons: false,
    percentPosition: true,
    draggable: true
  });
```

**Comment by desandro** [comment]
Sounds like this could the same issue as #48. If you set `contain: false`, does this resolve the positioning?

**Comment by since1976** [comment]
Yup same as #48. Setting ``contain: false`` does resolve the positioning problem but kind of need them contained.

**Comment by desandro** [comment]
Right-o! Closing this issue as a duplicate then.
