### ISSUE TITLE
Next/Previous event to stop video

### ISSUE THREAD

**Issue by LeoSeyers** [metafizzy/flickity#470]
Hello,
It's my first issue ever, don't know if it's appropriate to ask this here.
I'm definetely not a JS guru but I did check the documentations API before.

I've integrated a youtube video into my Flickity slider, I'd like a create a function that trigger my player.pauseVideo():Void function to stop the video playing. Is there an elegant way to this ? The only option I have now is to create event listenner for each swap/touch and click (on both arrows and dots) function, it feels very redondant!

Thanks in advance, Flickity is magic :)
:+1:

**Comment by desandro** [comment]
Thank you for this question. I think the best way to implement this behavior is to listen for [Flickity's select event](http://flickity.metafizzy.co/events.html#select) to pause the video

``` js
// jQuery
$carousel.on( 'select.flickity', function() {
  player.pauseVideo();
});
// vanilla JS
flkty.on( 'select', function() {
  player.pauseVideo();
});
```
