### ISSUE TITLE
selectedCellIndexes with groupCells

### ISSUE THREAD

**Issue by mikeebee** [metafizzy/flickity#472]
Hi there,

I have a single slider, broken up into a few sections, in order. I have a navigation element. I would like the navigation element to show which section I am currently in.

So, say the second section starts on cell 8, with `groupCells` set to `false` I get the index of the first cell via it's ID.

`const motionSlideIndex = slides.indexOf(document.getElementById('motion'));`

Then, I am highlighting a navigation item if the index is greater than or equal to the current `selectedIndex`. It's crude but it works (happy to take suggestions on any improvements by the way!)

```
flkty.on('select', function() {
       if (flkty.selectedIndex >= motionSlideIndex) {
        motionNavItem.classList.add('is-active');

        if (flkty.selectedIndex >= aboutSlideIndex) {
            motionNavItem.classList.remove('is-active');
        }

    } else {
        motionNavItem.classList.remove('is-active');
    }
});
```

This works great, however, when I set `groupCells` to `true`. The indexes are now based on the cell grouping rather than number of cells so my logic doesn't work.

Can you advise on how to get the correct index of the first slide in this instance please?

---

http://codepen.io/mikeebee/pen/vXdPEV?editors=0010#0

Many thanks,
Mike

**Comment by desandro** [comment]
I'm having trouble understanding what you're trying to do. I appreciate you producing a reduced test case, but because its got JS errors, I'm not able to use it. Can you try fixing the CodePen so I can better understand what you want to do?

**Comment by mikeebee** [comment]
Apologies! I have fixed the CodePen example. Let me know if you have any more questions.

**Comment by slimndap** [comment]
I ran into this as well:

If `groupCells` is set to `true` then `flkty.selectedIndex` no longer contains the index of the selected 'cell'. Instead, it contains the index of the 'group' that is visible.

Because of this, it is impossible to find out which cell is selected on the `select` event.

**Comment by desandro** [comment]
Let's say that you have 8 cells, groups of 3

```
| [0] [1] [2] || [3] [4] [5] || [6] [7] |
```

The second slide is selected, so cells 3, 4, and 5 are selected. What data would you like? Something like `selectedCellIndexes = [ 3, 4, 5 ]` ?

**Comment by slimndap** [comment]
For me it this:

Let's say that you have 8 cells, groups of 3

`[0] [1] [2]` `[3] [4] [5]` `[6] [7]`

The second _cell_ (not group) is selected, for example by clicking on it. I would then expect `flkty.selectedIndex` to be `1`, just like when `groupCells` is set to `false`.  
Instead, `flkty.selectedIndex` returns `0`.

You already solved this problem in CSS, by adding an `.is-nav-selected` class to the selected _cell_. Unfortunately, this is done after the `select` event, so it it not possible to use this class to determine which _cell_ is selected.

My use case is that I need to update the contents of another element on the page, based on the selected _cell_.

**Comment by desandro** [comment]
> The second cell (not group) is selected

I think there may be a misunderstanding. There is no concept of a single selected cell when groupCells is enabled. When you 'select a cell', you're actually selecting the slide that the cell is in.

The `is-nav-selected` class matches the selected cell(s) of the main carousel. If the main carousel has single cells in slides, then `is-nav-selected` will get added to the corresponding cell in the nav carousel, even if the nav carousel has groupCells.

So how can I help?

**Comment by slimndap** [comment]
> There is no concept of a single selected cell when groupCells is enabled.

I think there is.

I have two sliders:

`[mon][tue][wed][thu][fri][sat][sun]`

`[events of mon][events of tue][events of wed][events of thu][events of fri][events of sat][events of sun]`

The first slider has the following settings:

    asNavFor: 			'.today_block_events'
    groupCells: 		true

If I click on `tue` in the first slider then:

- `[mon]` and `[tue]` get the `is-selected` class.
- `tue` gets the `is-nav-selected` class. 
- the second slider jumps to `[events of tue]`.
- `flkty.selectedIndex` return `0` for the first slider.
- `flkty.selectedIndex` return `1` for the second slider.

I would have expected that `flkty.selectedIndex` for the first slider to be `1` as well.

In this situation there is no way to determine which that `[tue]` was selected (eg. on the `select` event).

![selectedindex](https://cloud.githubusercontent.com/assets/2284714/19828044/336aa0ca-9dbc-11e6-9b76-a1e61c8fa08f.gif)

**Comment by desandro** [comment]
When you ['selectCell' on a carousel with `groupCells`](http://flickity.metafizzy.co/api.html#selectcell), you are not selecting the cell, but rather the slide the cell is in.

Here's a demo with asNavFor and groupCells: http://codepen.io/desandro/pen/KgjWmz

Clicking on a nav cell will select the corresponding cell/slide in the main carousel, but it had a different set of slides because it has `groupCells`. The `is-nav-selected` class matches the selected cell(s) of the main carousel.

---

You can listen for `[select` event](http://flickity.metafizzy.co/events.html#select) on the main carousel to detect what cell has been selected.

**Comment by slimndap** [comment]
OK, I get it, thanks. I guess it is a misunderstanding then.

I do however think that this is unexpected behaviour and very confusing.

**Comment by mikeebee** [comment]
@desandro: your suggestion of `selectedCellIndexes = [ 3, 4, 5 ]` would work great for my use case.

**Comment by desandro** [comment]
@mikeebee Thanks for clarifying. I've labeled this issue as a feature request.

We can add this functionality by adding this code:

``` js
Flickity.prototype.getSelectedCellIndexes = function() {
  return this.selectedCells.map( function( cell ) {
    return this.cells.indexOf( cell );
  }, this );
};
```

You can then use `getSelectedCellIndexes` method.

``` js
flkty.getSelectedCellIndexes()
// => [ 3, 4, 5 ]
```

See demo http://codepen.io/desandro/pen/ORBxky/

**Comment by mikeebee** [comment]
Brilliant, thank you!
