### ISSUE TITLE
Allow single slide dragging if groupCells is active

### ISSUE THREAD

**Issue by ABaier** [metafizzy/flickity#474]
Hi @desandro! First of all, great module again, thanks a lot.

Would it be somehow possible to set the value for dragging/swiping to a single slide even if groupCells is true? I have a slider which shows five slides on desktop which can be controlled by page dots. It would be nice to not apply the grouping for drag/swipe events and instead snap to one of the next slides. I could only solve that by setting freeScroll to true, but then the slider does not snap to a position anymore. Otherwise, snapping for freeScroll maybe?

Thanks for your help!

**Comment by desandro** [comment]
> Would it be somehow possible to set the value for dragging/swiping to a single slide even if groupCells is true?

Sorry, ,o. This feature makes sense in order for `groupCells` to work. You can select slides by dragging, clicking next/previous buttons, or page dots.

**Comment by ABaier** [comment]
Ok, I think I just did not explain my (support) request clearly. groupCells works as expected, no problem here.

If I set groupCells to true, my slider actually shows 5 columns on desktop, 2 on tablet and 1 on handhelds, which get grouped correctly and slide according the number of elements in the viewport. Navigation is set to page dots only.

I just wanted to know if it is possible to set a different grouping value (for example grouCells: 1) that would only apply for drag or swipe event, so that every individual slide would snap to its next position. The page dots should behave like groupCells: true.

Thanks for your help!

**Comment by benface** [comment]
@desandro Any chance you can reconsider this? I feel like it really should work like @ABaier describes, where the page dots represent cell groups, and the previous/next arrows behave exactly like they do now (scroll to the next/previous group of cells), BUT still give users the ability to drag the slider to a single cell (so, in-between two "groups").
