### ISSUE TITLE
Safari 8 and early v9 compatibility (desktop)

### ISSUE THREAD

**Issue by creative-resort** [metafizzy/flickity#476]
Hello :)
Is Flickity 2 compatible with (desktop) Safari 8 and early v9 versions?
The imagesLoaded option doesn't seem to work, even on the official demos,
I can see images loading in a "waterfall" fashion on top of each other 
and the slider starting only after that weird looking moment.

No problems using Safari 10, so far.

**Comment by creative-resort** [comment]
@desandro do you have Safari 8 or 9 available for reproducing / debugging the issue?

**Comment by desandro** [comment]
Unfortunately, I'm upgraded to Safari 10. I do remember have some trouble with Safari 8 or 9, but I forget which project it was on. Sorry, but I cannot reproduce this issue. Please note that Safari 8 & 9 have less than 1% usage http://caniuse.com/usage-table

Sorry, but I won't be debugging this issue.

**Comment by creative-resort** [comment]
Thank you for your answer :)
I did some experimentation and found that 
- declaratavely (via -data-flickity attribute) it works,
- just not programmatically from jQuery document.ready
