### ISSUE TITLE
Flickity + Magnific popup issue

### ISSUE THREAD

**Issue by DeoThemes** [metafizzy/flickity#477]
Hi,

I'm having a new problem with this issue - https://github.com/metafizzy/flickity/issues/321
I want to make 2 links on the slide, one is for lightbox, the other is for standard link.
http://codepen.io/DeoThemes/pen/PZWjNy

When I click on the second link it just opens popup again.
Can you help with solution for this?

Best Regards.

**Comment by desandro** [comment]
You'll need to check that if the clicked element is `a:not(.popup-target)`, then do not trigger the popup. See http://codepen.io/desandro/pen/354f7976bac5de65bab6eab93eb96697/

``` js
  $gallery.on('staticClick.flickity', function(event, pointer, cellElement, cellIndex) {
    if (!cellElement) {
      return;
    }
    var $target = $( event.currentTarget );
    if ( $target.is('a:not(.popup-trigger)') ) {
      return;
    }
    $.magnificPopup.open({
      items: popupItems,
      gallery: {
        enabled: true
      },
      closeBtnInside:false,
      callbacks: {
        open: function () {
          $.magnificPopup.instance.goTo( cellIndex );
        }
      }
    });
  });
```

**Comment by DeoThemes** [comment]
Hi, thanks for helping, but as you can see here it causes another problem on mobile - [https://github.com/metafizzy/flickity/issues/465#issuecomment-255623776](url)

So, the final solution to fix this:

```javascript
$gallery.on( 'dragStart.flickity', function( event, pointer ) {
    $(this).addClass('is-dragging');
  })

  $gallery.on( 'dragEnd.flickity', function( event, pointer ) {
    $(this).removeClass('is-dragging');
  })

  $gallery.magnificPopup({
    delegate: '.lightbox-img, .lightbox-video',
    callbacks: {
      elementParse: function(item) {
      if(item.el.context.className == 'lightbox-video') {
          item.type = 'iframe';
        } else {
          item.type = 'image';
        }
      }
    },    
    type: 'image',
    closeBtnInside:false,
    gallery:{
      enabled:true
    }
  });
```

And then just add this to css:

```
.is-dragging {
    pointer-events: none;
}
```

**Comment by desandro** [comment]
Sorry, I will not be able to personally debug this issue.
