### ISSUE TITLE
select.flickity event is not trigger on webpack

### ISSUE THREAD

**Issue by tolgaergin** [metafizzy/flickity#478]
Hi David,

Without Webpack, I can listen the select.flickity event with flickity.pkgd.js

If I illustrate the issue that I faced.

The below code is working correctly, I can see the console.log, as it in your example http://codepen.io/desandro/pen/emVgqE

```
<script src="flickity.pkgd.min.js"></script>
<script>
var $customGallery = $('.example-gallery').flickity();
var flkty = $customGallery.data('flickity');

$customGallery.on( 'select.flickity', function() {
  console.log( 'Flickity select ' + flkty.selectedIndex );
});
</script>

```

But When I do with webpack, I can not see the console.log message

```
var $ = require('jquery');
var jQueryBridget = require('jquery-bridget');

var Flickity = require('flickity');
jQueryBridget( 'flickity', Flickity, $ );

require('flickity-as-nav-for');
require('flickity-bg-lazyload');
require('flickity-imagesloaded');

var $customGallery = $('.example-gallery').flickity();
var flkty = $customGallery.data('flickity');

$customGallery.on( 'select.flickity', function() {
  console.log( 'Flickity select ' + flkty.selectedIndex );
});
```

Is there any issue about webpack packaging or did i do something wrong?
Thanks

**Comment by desandro** [comment]
Thank you for submitting this bug. Looks like `window.jQuery` is not available with jQuery v3, when  bundled with Webpack. I am adding a utility function so you can make jQuery available for Flickity with Webpack.

**Comment by desandro** [comment]
Closing here. Looks we already have an issue opened in #329
