### ISSUE TITLE
"SCRIPT5007: Unable to get property 'add' of undefined or null reference"

### ISSUE THREAD

**Issue by hirasso** [metafizzy/flickity#481]
Hi there! Sorry to bother you with this, but maybe there is a simple answer to my issues:

I have a project, that sadly has to support IE10. When using flickity, I get these errors in the console:
```
SCRIPT5007: Unable to get property 'add' of undefined or null reference 
flickity.pkgd.js, line 1322 character 3
SEC7115: :visited and :link styles can only differ by color. Some styles were not applied to :visited. 
dev04
SCRIPT5007: Unable to get property 'forEach' of undefined or null reference 
flickity.pkgd.js, line 1451 character 3
SCRIPT5007: Unable to get property 'forEach' of undefined or null reference 
flickity.pkgd.js, line 1451 character 3
```
If I deactivate the flickity call, the errors disappear and the rest of my javascript executes fine. Do you have any recommendations for me how to fix this?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by hirasso** [comment]
Actually, the answer was really simple: I had the document mode set to "ie9 standards" in ie10 dev tools. After I changed that to "Standards", flickity started working just fine. Thanks for your time, somtimes just asking already helps solving the problem :)

**Comment by desandro** [comment]
Thanks for following up!
