### ISSUE TITLE
How to make a click and swipe working together?

### ISSUE THREAD

**Issue by francoisromain** [metafizzy/flickity#486]
Is it possible to have two behaviours at the same time on the same slide?
- swipe (default and better four touch screen)
- click to next slide (better for desktop)

I tried something like:

```
var carouselCells = Array.from(document.querySelectorAll('.carousel-cell'))
  carouselCells.forEach(function(e) {
  e.addEventListener('click', function() {
    flkty.next();
  })
})
```

Here is the fiddle: https://jsfiddle.net/francoisromain/fum7Lrac/

Now, the click works fine but the problem is the swipe moves forwards two slides.

Thank you

**Comment by desandro** [comment]
I recommend using [Flickity's `staticClick` event](http://flickity.metafizzy.co/events.html#staticclick) over standard `click`, as `click` is triggered during drag.

``` js
flkty.on( 'staticClick', function() {
  flkty.next()
})
```

**Comment by francoisromain** [comment]
thank you for your answer and all the great work you do : )
