### ISSUE TITLE
Chrome Warning: Navigator.pointerEnabled is a non-standard API added for experiments only. It will be removed in near future.

### ISSUE THREAD

**Issue by sdempsey** [metafizzy/flickity#489]
macOS Sierra 10.12.1
Chrome Version 54.0.2840.87 (64-bit)

I'd love to provide a reduced test case for this but essentially the warning appears on every page of my site that has a flickity slider on it.   Admittedly I'm using a 1.x version as we need to support IE 9 however, in dropping in the latest dist file from the repo the warning persists.  

If nothing else, you'll know chrome is planning to deprecate and resolve in a future release.  Let me know if you need or want more info. 

EDIT: just loaded up your test case example: http://codepen.io/desandro/pen/azqbop and the warning is there as well. 

Keep up the great work!

Love,
Sean

**Test case:** http://codepen.io/desandro/pen/azqbop

**Comment by desandro** [comment]
Thanks for reporting this issue. Looks like `navigator.pointerEnabled` is no longer part of the [working spec](https://www.w3.org/TR/pointerevents/). I'll evaluate a fix

**Comment by desandro** [comment]
This will be fixed in the next version of Flickity

**Comment by desandro** [comment]
Flickity v2.0.6 has been released with all `navigator.pointerEnabled` removed.
