### ISSUE TITLE
Slider not initialising correctly on elements created dynamically.

### ISSUE THREAD

**Issue by mdixon18** [metafizzy/flickity#491]
Hello, I am creating a page builder in vanilla JS. Now the contents are put into an iframe, and well im trying to initialise flickity on content that was dynamically created. Now, whats happened is, the initialising of the slider is successful but it ignores the new elements. Here's an example of how it looks after initialising.

```
<div class="carousel js-flickity flickity-enabled is-draggable" tabindex="0">
    <div class="carousel-cell">
        <a href="#" data-role="image" style="background-repeat: no-repeat; background-position: center top; background-image: url(&quot;http://placehold.it/350x150&quot;);"></a>
    </div>
    <div class="carousel-cell">
        <a href="#" data-role="image" style="background-repeat: no-repeat; background-position: center top; background-image: url(&quot;http://placehold.it/350x150&quot;);"></a>
    </div>
    <div class="carousel-cell">
        <a href="#" data-role="image" style="background-repeat: no-repeat; background-position: center top; background-image: url(&quot;http://placehold.it/350x150&quot;);"></a>
    </div>
    <div class="flickity-viewport" style="height: 0px;">
        <div class="flickity-slider" style="left: 0px;"></div>
    </div>
    <button class="flickity-prev-next-button previous" type="button" disabled="" aria-label="previous"><svg viewBox="0 0 100 100"><path d="M 10,50 L 60,100 L 70,90 L 30,50  L 70,10 L 60,0 Z" class="arrow"></path></svg></button>
    <button class="flickity-prev-next-button next" type="button" disabled="" aria-label="next"><svg viewBox="0 0 100 100"><path d="M 10,50 L 60,100 L 70,90 L 30,50  L 70,10 L 60,0 Z" class="arrow" transform="translate(100, 100) rotate(180) "></path></svg></button>
    <ol class="flickity-page-dots"></ol>
</div>
```
Flickity seems to be ignoring the carousel-cells. Even if i use the cellSelector option, it stills appears to ignore the elements as im presuming they are meant to be within the flickity-slider class.

Happy to provide more information on this.

**Comment by georgebeastiebach** [comment]
Yall need a modernz

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by prithivi-clustrex** [comment]
Hi

I got images from API. In client side, I'm using anuglar2 ngfor while page loading images are not rendering correctly.

It will display one by one
Like image1 below image2 etc

**Comment by eveevans** [comment]
Any news about this ?

**Comment by SingularReza** [comment]
I am facing the same problem in vue

**Comment by espositodaniele** [comment]
Someone has solved this? Got the same problem within `v-for` with Vue js. I think that the problem is that the carousel instance initializes before you can get results from the API.

**Comment by desandro** [comment]
If you're dynamically adding and removing cells via a framework, I recommend first looking into an implementation designed for that framework [vue-flickity](https://github.com/drewjbartlett/vue-flickity), or you can try using Flickity's API after making DOM changes, like [reloadCells](https://flickity.metafizzy.co/api.html#reloadcells)

**Comment by Luid101** [comment]
For Angular users I found that installing [ngx-flickity](https://www.npmjs.com/package/ngx-flickity), using their API: `<div [flickity]>
       <div [flickityChild] *ngFor="let child of children">{{child.title}}</div>
     </div>` and removing my original flickity JS import helped.

**Comment by DeoThemes** [comment]
I'm having the same issue but with Elementor Editor. Any solution for this? I tried reloadCells, resize but nothing seems to be working.
