### ISSUE TITLE
Prepend with only one element breaks the currentIndex

### ISSUE THREAD

**Issue by berengerzyla** [metafizzy/flickity#492]
Hi!

When the Flickity instance is created with only one element, and then elements are added with **prepend**, the instance loses the current selected index.

Issue seems to come from `this.selectedIndex = Math.max( 0, Math.min( this.slides.length - 1, this.selectedIndex ) );` in `proto._cellAddedRemoved`.

Test case exemple below:
- Create a gallery with one item.
- Prepend X new items.

Expected: the new items are added before the item#1, and focus stays on item#1.
Happens: the new items are added before #1 BUT the #4 gets the focus, instead of #1.

**Test case:** http://codepen.io/berengerzyla/pen/ObpbzY

Thank you!

**Comment by desandro** [comment]
Thank you for reporting this bug. I'll have to take a look.

**Comment by tylermadsen** [comment]
I'm hitting up against this issue, too. I've found that this occurs if the instance has less than 3 cells at any point (doesn't seem specific to initialization). Removing the third cell in @desandro's [prepend pen](http://codepen.io/desandro/pen/XJZpMN) will also cause the bug.

This might be a long shot, but were either of you able to come up with a patch for this @berengerzyla @desandro?

Please forgive the Easter Sunday comment I'm under the gun on a deadline!
Any help would be so thoroughly appreciated, thank you

**Comment by berengerzyla** [comment]
@tylermadsen, what did the trick is to call `this.updateSlides();` at the beginning of `_cellAddedRemoved`. Right there: https://github.com/metafizzy/flickity/blob/master/dist/flickity.pkgd.js#L3835

The thing is, when the process gets to `_cellAddedRemoved` and re-calculates the new index of the slide that's already selected, `updateSlides()` has not been called yet, and so `this.selectedIndex = Math.max( 0, Math.min( this.slides.length - 1, this.selectedIndex ) );` returns a wrong index, because `this.slides.length` is the number of slides BEFORE any changes made to it (appending, prepending or removing. The new array of slides is updated by `this.updateSlides` and is called later). Do a trace of that number or the data in `this.slides` at that line, and you'll see.

@desandro, I didn't dive enough in the whole code to make a pull without knowing for sure it's the right way to fix it, but hopefully it'll get you on the right track. Same for you @tylermadsen. :)

**Comment by tylermadsen** [comment]
@berengerzyla you have made my day

**Comment by swixpop** [comment]
This issue has been open for quite some time now. Seems like a small fix. @desandro can you please provide an update as this bug prevents building up a gallery with ajax starting from a small number of slides?

**Comment by desandro** [comment]
🎉  **[Flickity v2.1.0](https://github.com/metafizzy/flickity/releases/tag/v2.1.0) has been released with  this bug fixed** 🎉

Thanks for sticking with Flickity 🌈🐻
