### ISSUE TITLE
.flickity-page-dots blocking page scroll on mobile

### ISSUE THREAD

**Issue by joaomnb** [metafizzy/flickity#494]
On mobile, it's not possible to scroll the page if you start dragging on top of the slider dots (.flickity-page-dots).

The behaviour can be seen when running this snippet using the inspector's mobile view: http://codepen.io/joaomnb/pen/pNPMpZ

It also happens on every slider on the Flickity website.

**Comment by Ceremony64** [comment]
Can't replicate with latest FF and Chrome on Android or Chrome on Windows with the mobile view.

Probably fixed since then or maybe only an issue on your specific setup (more infos?).

**Comment by joaomnb** [comment]
Maybe I just did explain very well, but the issue is still there.

Take a look at the screenshot:
![flickity](https://user-images.githubusercontent.com/1238088/27700162-a8a22b68-5cf4-11e7-81c3-38f07d260e9f.png)

I can't scroll the page if I start by placing the thumb on top of the dots.

**Comment by Ceremony64** [comment]
I was able to reproduce it after i increased the height of .flickity-page-dots to counteract those small dots and apparently fat fingers. Seems to only affect Firefox on Android, as Chrome seemed fine.

Also, while trying to hit the page dots to start a scroll, I also hit the slides themselves from time to time. FF displayed inconsistent behavior, as sometimes I could only scroll the page, switch slides or do both at the same time. Couldn't replicate this on Chrome either...

**Comment by lewhunt** [comment]
This also seems to affect Safari mobile on iPhone and iPad. To minimise the issue I have reduced the height of the list element containing the dots.

**Comment by desandro** [comment]
This particular issue does not happen any more in iOS 15, but we have a new issue dealing with mobile scrolling #1196
