### ISSUE TITLE
ES6 Import Flickity doesn't work

### ISSUE THREAD

**Issue by allencoded** [metafizzy/flickity#496]
I am using JSPM and I have installed flickity using:
`jspm install npm:flickity` which is successful and adds: `"flickity": "npm:flickity@2.0.5",` to the config.

Then in my JS I have:
`import 'flickity'`
But when doing so`Flickity` is undefined.

**Comment by allencoded** [comment]
I actually found I can import flickity like so:
`import Flickity from 'flickity';`

**Comment by uriel2707** [comment]
Alternative use jQueryBridget 
`
import Flickity from "flickity";
$ = jQuery.noConflict();
jQueryBridget("flickity", Flickity, $);
`
