### ISSUE TITLE
Option to manage cell gap

### ISSUE THREAD

**Issue by xemox** [metafizzy/flickity#500]
Hi,
Is there any option to manage gap between carousel cells?

I use background image to fill cells, like this example has white gap between image. How to eliminate it?
http://codepen.io/desandro/pen/jAGAEb

**Comment by desandro** [comment]
You can change the margin between cells by changing cell `margin` CSS.  Currently, that demo has

``` css
.carousel-cell { margin-right: 10px; }
```

[See demo with 0 margin](http://codepen.io/desandro/pen/0b6c814a0b7f45cc67bb6f9ab5b6d5cf/)

**Comment by wernerwerks** [comment]
@desandro  I'm not sure this is working quite right? Or, am I missing something. The demo you linked to above still has a gap. And, when I try to change the margin-right number nothing changes. Any ideas?

**Comment by desandro** [comment]
gap was caused by a vertical scrollbar. Try it again.

**Comment by georgebeastiebach** [comment]
Don't under-estimate rounding errors and different browsers rounding vars reaching for ceil or floor akin to their own. Find the DOM node where sub-pixels are calculated.

**Comment by wernerwerks** [comment]
Bingo! Vertical scroll bar fix worked. Thank you kind sir!

**Comment by paulburgess** [comment]
Hi - can anyone help me with what is going on here on this margin issue - I have margin-right:0 on .carousel-cell - it doesn't take effect on load, only when there is any kind of window resize - a quick demo video here:

http://dlrg.co/2Z2B3K141W3H

Slider is initialised via JS.

I've tried all sorts to fix this... I must be doing something silly.

Can anyone point me in the right direction?

Many thanks!

**Comment by desandro** [comment]
@paulburgess  I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by protoEvangelion** [comment]
I have this same problem.  As the slides change there is about a 10px gap between the images.

**Comment by mathiasprisfeldt** [comment]
I solved this problem with Flickity's own example of a gapless carousel.

**Answer:**
`/* force scrollbar, not necessary, but may reduce gaps. Setting a max-height on .carousel also works */
html { overflow-y: scroll; }`

[Click for source](https://codepen.io/desandro/pen/MYQWEe)

**Comment by Artem-Schander** [comment]
It seems only to occur with the option `percentPosition: false`
