### ISSUE TITLE
Seamless flow?

### ISSUE THREAD

**Issue by Toccamonium** [metafizzy/flickity#501]
Hi, thanks for this cool plugin. I'm just wondering if there is a option to create an seamless flow from it? Seamless flow means for me, that you put this plugin onto a page and in the flickity viewport you see 4 items. All together there are 6 items inside. The flow is starting via autoplay and it's not jumping from slide to slide it's just continuing scrolling. When the first item is out of view it will be appended to item 6 so get this seamless flow. So after item 6 it begins again with 1, 2, 3...

cheers
Florian

**Comment by willpower232** [comment]
Are you not describing the [wraparound option](http://flickity.metafizzy.co/options.html#wraparound)?

**Comment by desandro** [comment]
Sounds like you're asking for an auto scroll feature. Sorry, but Flickity will not support this feature. See #77
