### ISSUE TITLE
autoPlay stops after any user interaction

### ISSUE THREAD

**Issue by h0r0man** [metafizzy/flickity#502]
Hello, I notice that `autoPlay` stops when the user interact with Flickity carousel, l also have: `pauseAutoPlayOnHover: false`.
It‘s possible to force autoplay after the user interaction something with `unpausePlayer`.

**Comment by desandro** [comment]
While there is no option for this, you can re-start the Player with [`playPlayer`](http://flickity.metafizzy.co/api.html#playplayer) method.

**Comment by h0r0man** [comment]
I solved with, this concept:
```javascript
var $carousel = $('.carousel').flickity();

$carousel.on('mouseenter', function() {
  $carousel.on('mouseleave', onNavMouseleave);
});

function onNavMouseleave() {
  $carousel.flickity('playPlayer');
  $carousel.off('mouseleave', onNavMouseleave);
};
```
