### ISSUE TITLE
Temporarily disable left/right arrow navigation

### ISSUE THREAD

**Issue by piotrkulpinski** [metafizzy/flickity#503]
Hi,
Does anyone know a way to temporarily disable the keyboard events for Flickity carousel?
I need to disable it while the modal window is open.

Thanks!
Piotrek

**Comment by desandro** [comment]
Thanks for reporting this issue. Keyboard events will not trigger if the focused element is not the Flickity container element. I recommend you set focus on an input in the modal window to resolve this issue.
