### ISSUE TITLE
draggable: true => Triggered Links directly 

### ISSUE THREAD

**Issue by davidhellmann** [metafizzy/flickity#505]
Strange behavior. 
I've draggable: true an when I trag the slides (each one is a link) he triggered asap the link. But I don't need this behavior here. Any Idea to disable this? :/

Cheers!

**Comment by davidhellmann** [comment]
Sorry, my Problem :)

**Comment by davidhellmann** [comment]
Hm I've the Problem again :/ Anyone an Idea? I fixed it last time but I don't know how  :/

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by davidhellmann** [comment]
That's the Problem. I can reproduce it :/ Here on Codepen it works fine: http://codepen.io/fredmansky/pen/LWGzJY that's the same code as I use in the Project. 

Bad move not to comment what was the Problem last year, damn! :D

**Comment by davidhellmann** [comment]
Tried a lot Stuff but no chance. Copied stuff from one project to the other but it doesn't work. Excluded all other CSS / JS and same problem. On mouse release he triggered the link when I swipe.

**Comment by davidhellmann** [comment]
Fixed!

I've a Pagetransition Script and here was a EventListener that was until now `click` and I changed that to `onmouseup` and now it works fine!

```
/**
 * Page Transitions
 */

// Dependencies
import goToUrl from '../lib/goToUrl'

// Vars
const body = document.body
const siteURL = `${window.location.protocol}//${window.location.host}`
const triggers = Array.from(document.querySelectorAll(`a[href^="${siteURL}"]:not([href*="#"])`))

triggers.forEach((trigger) => {
  // Click Event
  trigger.addEventListener('onmouseup', function(event) {
    if (!(event.ctrlKey || event.metaKey || event.which === 2)) {
      const newLocation = this.getAttribute('href')
      event.preventDefault()

      // Set Transition Class
      body.classList.add('js_pageTransition')

      // Go to New Page
      setTimeout(() => {
        goToUrl(newLocation)
      }, 250)
    }
  }, false)
})

window.onpageshow = (event) => {
  if (event.persisted) {
    body.classList.remove('js_pageTransition')
  }
}
```

**Comment by davidhellmann** [comment]
ok @desandro maybe you've an Idea. I've created a test case and when you swipe you see he triggered the link directly. In the JS Section is a little pagetransition script and this and flickity are not best friends at the moment. 

http://codepen.io/fredmansky/pen/LWGzJY?editors=1011

**Comment by davidhellmann** [comment]
http://codepen.io/fredmansky/pen/LWGzJY?editors=0011 Looks like this work for now.

**Comment by desandro** [comment]
Has this been resolved? Is there something I can help with?
