### ISSUE TITLE
wrapAround two slides at a time?

### ISSUE THREAD

**Issue by wadehammes** [metafizzy/flickity#507]
Hey Dave! Hope you're well.

I am building a two-row, staggered slider using Flickity:

http://via.wade.today/3l3R331o2u3j

The issue is, in my two column (which is essentially a slide with two elements stacked vertically, and the first being transformed left -50%) the wrapAround slide's top element is flickering into view only after the slide itself is in viewport (this is due to the transform, obviously). If this were wrapping two slides at a time, I think this issue would correct itself as the flicker would happen offscreen (or that is the theory I have). Any suggestions for setting a wrap amount? I've poked around the core code, but to no avail. Thanks in advance!

**Comment by wadehammes** [comment]
Achieved this by setting `.flickity-viewport` to `width: 120%` and then adjusting the math on the `getPositionValue` function...will work for now, but would love to see an option for wrapAround amount in the future!

**Comment by desandro** [comment]
Hmm, this is an edge case. But you may be able to hack a solution. Set something like `width: 150%` on the Flickity element, so that it's bigger than the viewport. The add a secondary container to the Flickity elements so they are cropped for the viewport

``` html
<div class="container">
  <div class="carousel">...</div>
  <div class="carousel">...</div>
</div>
```

If you can put together a demo on CodePen, I could take a shot at the solution in code.

**Comment by wadehammes** [comment]
@desandro yea been tinkering with that too...only issue is, setting the width of `flickity-slider` causes the calculations to widen, throwing the slides off:

http://codepen.io/wadehammes/pen/MJwpZj
