### ISSUE TITLE
Have margin at the extremes of a carousel with contain: true

### ISSUE THREAD

**Issue by sgtpenguin** [metafizzy/flickity#509]
Hello.  I'm wondering how I can achieve the same type of behavior as `contain: true` but have a margin to the left of the first item and to the right of the last item, while still allowing the cells to span full-width when not at an extreme.

Any ideas?

**Test case:** http://codepen.io/sgtpenguin/pen/vgOGEP

**Comment by desandro** [comment]
If you still want the margins on the outside of the cells, you can turn off `contain: true`. `Contain` is designed so that there are no margins.

**Comment by sgtpenguin** [comment]
But I don't want large margins the the left and/or right of the first and last items as I would get with any `cellAlign` option.  I just want to maintain the same spacing at each end that I have between cells in the middle.  That is, I want to be able to flick through the whole carousel and maintain the `contain` bounds left and right, but retain a bit of margin on the edge of the screen.

**Current:**
![screenshot 2017-01-06 16 06 50](https://cloud.githubusercontent.com/assets/16600959/21732969/2eeca012-d42a-11e6-8a71-3481fbf0bb4c.png)

**Desired:**
![screenshot 2017-01-06 16 08 13](https://cloud.githubusercontent.com/assets/16600959/21733016/5cf07e2a-d42a-11e6-847f-8e3e8c5d7334.png)

**Comment by sgtpenguin** [comment]
I was able to solve this by adding a wrapper around each item and setting padding there.  Can't believe I didn't think of it sooner...so simple :)  Still feels a little inelegant though.

[http://codepen.io/sgtpenguin/pen/vgOGEP](http://codepen.io/sgtpenguin/pen/vgOGEP)

In any case, thank you for the response and for the great libraries!

**Comment by georgebeastiebach** [comment]
Why are you confused about bounding box? Look into flexbox and calc. Also modernizer.

**Comment by ryanhilton** [comment]
> I was able to solve this by adding a wrapper around each item and setting padding there. Can't believe I didn't think of it sooner...so simple :) Still feels a little inelegant though.
> 
> http://codepen.io/sgtpenguin/pen/vgOGEP
> 
> In any case, thank you for the response and for the great libraries!

Thank you for the idea @sgtpenguin!! I had a design to build that had a box shadow around it, and this solved the problem for me too!
