### ISSUE TITLE
staticClick event doesn't trigger if draggable: false

### ISSUE THREAD

**Issue by flogehring** [metafizzy/flickity#51]
Not sure if this is supposed to be this way.
I wanted to disable dragging because it can be annoying when scrolling on mobile devices. Turns out™ it disables the static click too 😁

**Comment by desandro** [comment]
This is intended. If draggable is disabled then you don't need `staticClick`. But I recognize there's your edge, when you have draggable disabled, sometimes, and you always use `staticClick`.

If others would like `staticClick` to fire with `draggable: false`, **+1** issue. Even better, let me know what your use case is.

**Comment by flogehring** [comment]
My case:  
- I have added a lightbox (with higher quality images) for the staticClick event. 
- I want the lightbox to be fired on all sizes
- I always want the slider to AutoPlay
- I want draggable disabled on small handsets, because it's annoying when scrolling vertically
- I want to show the arrows only on small handsets where draggable is false

I've separated the draggable vs. arrows situation using a Modernizr media query before the init. However, I have to do it (the separation) again when attaching the click event for the lightbox. 

- Using a regular click handler with draggable enabled fires after dragging (which is probably why you implemented `staticClick`.
- `staticClick`doesn't work when draggable is disabled

I know it's  a bit complicated but I hope you get what I'm trying to explain 😉

**Comment by since1976** [comment]
Another example is when you use asForNav. If you set your ``b`` gallery (menu for ``a`` gallery) to ``draggable: false`` it will prevent you from being able to click on  a ``b`` gallery item to control your ``a`` gallery.

**Comment by desandro** [comment]
It won't prevent you, you can use normal `click` event instead.

**Comment by pawlikdoc** [comment]
I agree with @since1976 . It prevents click...

**Comment by passiomatic** [comment]
Yes, this hit me today as well. I'm implementing a carousel which advances when user interacts with single cells, without using left/right arrows nor page dots.  I'm using staticClick to figure out which call has been clicked and its index. 

However, sometimes it would be desirable al not to be able to flick back, so I've specified `draggable: false` as option and noticed that staticClick is not fired.

**Comment by flowgrow** [comment]
+1

**Comment by passiomatic** [comment]
+1

**Comment by sjelfull** [comment]
+1

**Comment by justrhysism** [comment]
+1

You can't use `asForNav` without `draggable: true` - I can't see why this is limited this way. I should be able to use `asForNav` regardless of the `draggable` setting.

For my current project, it has rendered `asForNav` completely useless.

**Comment by markseu** [comment]
I am also running into this problem. I implemented an option that goes to the next cell when the Flickity div is clicked, but there is no staticClick event if draggable is set to false. Would be nice to configure this independently.

**Comment by cireriddler** [comment]
+1

**Comment by beefchimi** [comment]
+1

**Comment by Dylan-Chapman** [comment]
+1

**Comment by sgtpenguin** [comment]
+1

**Comment by takuhito-h** [comment]
+1

**Comment by ARCITEX** [comment]
+1

**Comment by DustinStupp** [comment]
Is this still being considered? +1

**Comment by ssanch** [comment]
+1

**Comment by desandro** [comment]
If your Flickity carousel has `draggable: false` and you still want to use `staticClick` events for convienent `cellElem` and `cellIndex` arguments, you can add this code to always trigger `staticClick` on `click`:

``` js
// jQuery
var $carousel = $('.carousel').flickity({
  draggable: false,
});

// hack staticClick
var flkty = $carousel.data('flickity');
flkty.element.addEventListener( 'click', function( event ) {
  flkty.staticClick( event, event );
});
```

``` js
// vanilla JS
var flkty = new Flickity( '.carousel',{
  draggable: false,
});

// hack staticClick
flkty.element.addEventListener( 'click', function( event ) {
  flkty.staticClick( event, event );
});
```

See demos: [jQuery](https://codepen.io/desandro/pen/MVYyYL?editors=1111) & [vanilla JS(https://codepen.io/desandro/pen/jzEWoK?editors=1111)

**Comment by desandro** [comment]
🎉  **[Flickity v2.1.0](https://github.com/metafizzy/flickity/releases/tag/v2.1.0) has been released with support for all new `staticClick` enabled with `draggable: false` 🎉

I'm now closing this issue. Please open a new issue if you into trouble with using `staticClick`. Thanks for all the +1's and 👍 over the years. 🌈🐻

**Comment by chpio** [comment]
I have a somewhat related issue:

```js
let nav = document.querySelector('.nav');
let content = document.querySelector('.content');

	new Flickity(nav, {
		draggable: true,
		setGallerySize: false,
		asNavFor: content,
	});

	new Flickity(content, {
		draggable: false,
		pageDots: false,
		prevNextButtons: false,
		setGallerySize: true,
	});
```

clicks on the cells work as expected (change the selected cell in the content flickity) but if i press the arrows or drag to an other cell in the nav the content isn't affected. I also tried swapping the `asNavFor` option to the content:

```js
	new Flickity(nav, {
		draggable: true,
		setGallerySize: false,
	});

	new Flickity(content, {
		draggable: false,
		pageDots: false,
		prevNextButtons: false,
		setGallerySize: true,
		asNavFor: nav,
	});
```

that fixes the issue drag-and-arrow-click issue but now it's ignoring direct clicks on nav cells and dots.

**Comment by desandro** [comment]
@chpio Could you please open a new issue with a **reduced test case**. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

I'm locking this thread.
