### ISSUE TITLE
next slide appearing on its top

### ISSUE THREAD

**Issue by nilskdc** [metafizzy/flickity#510]
Hi
I added a custom button--next to my slider. Is there anyway that by cliking on this next button, I can have the next slide appearing on at the top (intead of a purely horizontal movement) ?
This is an issue for me, as I have long vertical slides with html text content, and I need the next slide to appear on its top starting point

I would have the same question for the bottom slides dots

Thank you for your very nice and documented plugin ;-)

Nils

**Comment by desandro** [comment]
[Use `select` with the third argument to `true`](http://flickity.metafizzy.co/api.html#select)

``` js
// select cell instantly, without animation
$('.button-group').on( 'click', '.button', function() {
  var index = $(this).index();
  $carousel.flickity( 'select', index, false, true );
});
```

[See demo](http://codepen.io/desandro/pen/pggQeL)

**Comment by nilskdc** [comment]
Hi Desandro 
Thank you for such a quick answer !
Unfortunately it does not solve my problem, wich I did not make clear enough. I give it another try :
When I click the custom next button, the next slide appears at the same heigth as the the previous slide. For example, for a long slide (of html text) with heigth=1000px, if the button next is at the middle (heigth = 50% = 500px) , then the next slide will also be appearing at the same heigth of 500px.
On a mobilephone screen this is a problem as the top of the slide may not be visible, except with manual vertical scrolling.
I want the next slide to appear at its top = heigth = 0px instead of 500px.
That is, the horizontal jumping of one slide to another should go along with a vertical scroll in order to reset slides to their top

Hoping this is more clear ;-)

Thanks !

Nils

**Comment by desandro** [comment]
look at [`adaptiveHeight: true`](http://flickity.metafizzy.co/options.html#adaptiveheight)
