### ISSUE TITLE
staticClick triggers a click-event after the click in react.

### ISSUE THREAD

**Issue by kristoffernolgren** [metafizzy/flickity#511]
I use staticClick like this:

    this.flky.on('staticClick', (e) => { this.setState({mobileZoom: true})

When I click it, an image gets expanded to 100% size, ususally bigger than the screen:

     <img onClick={this.state.mobileZoom && () => {this.setState({mobileZoom: false}}}
     style={...this.state.mobileZoom && {position: 'absolute', top: 0, left: 0, width: 'auto', zIndex: 1070}}
     />

(this.state.mobileZoom makes the attributs and styliing conditional in react)

This works on desktop, but on mobil, the onClick-event of the full-screen image also get's triggered, causing the image to just flicker and then disapear again.

It works if I add a delay:

    this.flky.on('staticClick', (e) => { 
        setTimeout(() => { this.setState({mobileZoom: true}) }, 100)
    )

But I have no idea how long the click event lasts on different devices, so this is not a sustainable solution and very bad practice. Is there a better way?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
