### ISSUE TITLE
watchCSS in mobile after page load

### ISSUE THREAD

**Issue by kaochihhui** [metafizzy/flickity#514]
Hi. Thanks for the brilliant work. 

watchCSS is a smart idea for handling responsive layout.

The problem is that, it works fine in window resizing. 

Ex. On desktop, flickity is not triggered which is great, and I resize the window to mobile size, and flickity is triggered as I expected. 

But If I load the page in mobile, flickity is not called. 

I am not sure if I express myself.

Once again thanks for the great job and look forward to your reply.

Screenshot of codes:

Resizing from desktop size to mobile size is working fine
![resize](https://cloud.githubusercontent.com/assets/1179931/22324818/3eb18f32-e3e6-11e6-9e89-d42df318cfb5.PNG)

Webpage loaded in mobile, flickity is not triggered (Under flickity-slider class is empty....)
![after refresh](https://cloud.githubusercontent.com/assets/1179931/22324846/5ca2d992-e3e6-11e6-8619-f58283b35d8c.PNG)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
