### ISSUE TITLE
Slider dosn't render with angular 2 lazy router

### ISSUE THREAD

**Issue by Knewtone** [metafizzy/flickity#515]
**Test case:** https://cliniqueduval-17c9a.firebaseapp.com/
1 - when you click on "Accueil" menu --> the slider renders well
2 - you click on other menu and return to the " accueil" menu --> the slider doesn't work

I created a component slider : 

```
<div class="carousel" data-flickity='{ "cellAlign": "center","accessibility": true,"wrapAround": true,"initialIndex": 1,"freeScroll": false, "prevNextButtons": true, "pageDots": false }'>
    <div class="carousel-cell">
        <img class="carousel-cell-image" src="../../../assets/1.jpg" alt="tulip" />
    </div>
    <div class="carousel-cell">
        <img class="carousel-cell-image" src="../../../assets/2.jpg" alt="tulip" />
    </div>
    <div class="carousel-cell">
        <img class="carousel-cell-image" src="../../../assets/3.jpg" alt="tulip" />
    </div>
</div>
```

in the component class i use a constructor : 

```
  constructor() { 
    var Flickity = require('flickity');
  }
```
i added the js dependecy of course.

PS : when the slider is called from the root component it works fine and without the require.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
