### ISSUE TITLE
Using Cubic-Bezier (Easing) Transition on Slides

### ISSUE THREAD

**Issue by kbenakole** [metafizzy/flickity#517]
Hi, it would be nice to be able to set a cubic-bezier, easing transition on the carousel-cells/slides, so they slide according to one's defined style/easing. I've tried implementing it with CSS but it's kinda janky. Maybe that could be included as an option/property within the flickity object.

Thanks.

**Comment by desandro** [comment]
Thank you for this feature request. Flickity uses physics-based animation, with velocity and attraction. You can fine tune its movement behavior with [selectedAttraction and friction](http://flickity.metafizzy.co/options.html#selectedattraction-friction).

Custom easing could be a nice fine-detail option, but it would be difficult to implement on top of the physics animation. I appreciate your feedback, but I'll have to pass on this idea.
