### ISSUE TITLE
consider implementing passive on eventListeners

### ISSUE THREAD

**Issue by chrisbraddock** [metafizzy/flickity#518]
Flickity added a [new blip to my Lighthouse report](https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners).

```
Using modern JavaScript features
JavaScript: Site uses passive listeners to improve scrolling performance  
Consider marking your touch and wheel event listeners as passive to improve your page's scroll performance.
```

I'm not sure if you've considered [passive event listeners](https://developers.google.com/web/updates/2016/06/passive-event-listeners). The page reads:

> In general, add the passive flag to every wheel, mousewheel, touchstart, and touchmove event listener that does not call preventDefault()

I did grep your code and see you do preventDefault() at least in some cases, so maybe this isn't feasible.

I end up with Lighthouse complaining about the following lines:

```
div.flickity-viewport.addEventListener('touchstart', function (e){var t="on"+e.type;this[t]&&this[t](e)})

button.flickity-prev-next-button.previous.addEventListener('touchstart', function (e){var t="on"+e.type;this[t]&&this[t](e)})

button.flickity-prev-next-button.next.addEventListener('touchstart', function (e){var t="on"+e.type;this[t]&&this[t](e)})
```

**Comment by desandro** [comment]
Thanks for pointing to this issue! I was not aware about passive listeners.

> Passive event listeners solve this problem by enabling you to set a flag in the options parameter of addEventListener indicating that the listener will never cancel the scroll. 

Ah, but Flickity does cancel the scroll. So I don't think passive listeners are going to be for Flickity.

**Comment by desandro** [comment]
I didn't understand the scope of this issue. Chrome 56 'breaks the web' by implementing a different behavior that disables `preventDefault`. Closing here, continuing in #521
