### ISSUE TITLE
Gap and container issue

### ISSUE THREAD

**Issue by elemis** [metafizzy/flickity#519]
When we apply gap between cells using margin-right, the cells don't fit in the container http://codepen.io/anon/pen/WRapMK We'd like all 3 columns to fit in the container. How to fix this issue?

**Comment by thesublimeobject** [comment]
Hey @elemis!

The easiest way to fix this is by accounting for both the width and the margin of your items in the calculation of your width. So, for example, on your isotope instance I changed the width to:

```
.carousel-cell {
    width: calc((100% / 3) - (20px * 2 / 3));
}

.carousel-cell:nth-child(3n) {
    margin-right: 0;
}
```

This works consistently with a formula of:

`width: calc((itemWidth) - (margin * (numRows - 1) / (rows)))`

So, you are essentially accounting for the fact that there will me no margin on the last item, such that each item's width is a portion of the total width minus a portion of the total margin. I hope this makes sense; it will definitely solve your issue.

**Comment by elemis** [comment]
I managed to solve this problem by using Bootstrap columns. However other issues occured. 

Please check: http://codepen.io/anon/pen/bgJyOr There are 6 cells in this example and 6 dots show. But on the last two dots the carousel doesn't move. If I enable wrapAround it works properly: http://codepen.io/anon/pen/EZJzGM But I'd like the wrapAround feature to be disabled. 

Not sure how to fix this.

**Comment by thesublimeobject** [comment]
`groupCells: 3`

**Comment by elemis** [comment]
@thesublimeobject Yes but this makes the carousel move 3 cells at a time. I'd like the cells to move one by one.

**Comment by thesublimeobject** [comment]
I'm not sure there's an option to group cells and have them scrolled one-by-one; although, you should be able to achieve this if you build a navigation with your own methods, built on what is supplied in the exposed API.
