### ISSUE TITLE
EaseOut anitate on entering

### ISSUE THREAD

**Issue by gabrielribeiro** [metafizzy/flickity#520]
Is it possible to load all itens entering with an ease out animation like that?

**Reference:** https://dribbble.com/shots/3076329-BigScoots-Testimonials-Design-2nd-part

**Comment by desandro** [comment]
See [image gallery with fancy selected style](http://codepen.io/desandro/full/jEpxqJ/) for a similar demo. It works by changing style with `.is-selected` and CSS transitions.
