### ISSUE TITLE
Swipe triggers prev/next browser navigation on Chrome & Windows 10

### ISSUE THREAD

**Issue by jrsett** [metafizzy/flickity#521]
**Test case:** http://codepen.io/desandro/pen/azqbop

Swiping on a flickity slider triggers navigation to previous or next page in Chrome.

When I try to swipe from left to right on the codepen example above, the entire page immediately starts to move to the right, revealing the previous page I was on. This is true for both a one-finger swipe and a two-finger swipe.

This happens on Windows 10 with Chrome 56.
It works fine on Windows 10 with Edge browser.

**Comment by simeydotme** [comment]
This could be to do with the new changes in Chrome56 ... it no longer respects `preventDefault()` 😞  ... what a mistake

**Comment by desandro** [comment]
Thank you for reporting this issue and @simeydotme for providing a possible diagnosis. I'll have to take a look.

Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=639227 Developers like me are not happy.

**Comment by DerekBess** [comment]
@desandro Looks like chrome dropping the ball here. For whatever reason, this warning create some kind of memory leak on my project and will eventually freeze the carousel from reacting. Oddly enough, this only occurs in IoS and Chrome. Works fine in firefox.

**Comment by raphaelokon** [comment]
@DerekBess Had the same here.

**Comment by justlevine** [comment]
@DerekBess same here

**Comment by desandro** [comment]
This issue has been quiet for a while so I'm closing it. Please open a new issue if you run into something similar.
