### ISSUE TITLE
How to get Flickity instance at first select.flickity event?

### ISSUE THREAD

**Issue by mauricesnip** [metafizzy/flickity#523]
I'm wondering how to get the Flickity instance for the first occurring select.flickity event. It works just fine for every other select.flickity events. Seems like the Flickity instance is bound after the initial/first select.flickity event triggers.

```javascript
var carousel = $('.carousel');

carousel
    .on('select.flickity', function() {

        // Logs undefined
        console.log($(this).data('flickity'));

        // Worth trying, but obviously also logs undefined
        console.log(carousel.data('flickity'));

        // Seems legit... but not really what I've had in mind
        setTimeout(function() {
            console.log(carousel.data('flickity'));
        });
    })
    .flickity();

// Logs instance Object
console.log(carousel.data('flickity'));
```

Codepen: http://codepen.io/mauricesnip/pen/oZxvjm

**Comment by desandro** [comment]
The `select` event may be triggered before instance is assigned to the jQuery object. I recommend using this pattern instead

``` js
var carousel = $('.carousel').flickity();
var flkty = carousel.data('flickity');

carousel.on('select.flickity', function() {
  console.log( flkty )
})
```

See demo http://codepen.io/desandro/pen/b653761876469a69659b72a4ab61556c/

**Comment by mauricesnip** [comment]
I'm aware of the demo, although, apart from the difference in pattern, it behaves the same as the example provided. With the exception that the `select.flickity` handler is added after initialization, so it never handles the first `select.flickity` event.

Is _may_ (be triggered) the keyword here? After endless amounts of refreshes, the Flickity instance is never logged to the console, in any condition whatsoever. Is there any other way to access the Flickity instance for the first `select.flickity` event? Can it be guaranteed?

Ps. What I'm trying to achieve is; if the first (or `initialIndex`) cell contains certain content > stop autoplay.

**Comment by desandro** [comment]
> Ps. What I'm trying to achieve is; if the first (or initialIndex) cell contains certain content > stop autoplay.

Rather than stopping autoplay, I recommend not enabling autoplay when initializing Flickity.
