### ISSUE TITLE
API function to get the current position of the slider

### ISSUE THREAD

**Issue by hirasso** [metafizzy/flickity#525]
Hi there! 

I would like to let another element's css react to the current position (best would be percent) of a flickity instance. Is there maybe an option hidden somewhere inside Flickity to get the current position of the slider? 

best, Rasso

**Comment by desandro** [comment]
Sounds like you're looking for [scroll event, which passes a progress argument](http://flickity.metafizzy.co/events.html#scroll)

``` js
$carousel.on( 'scroll.flickity', function( event, progress ) {
  progress = Math.max( 0, Math.min( 1, progress ) );
  $progressBar.width( progress * 100 + '%' );
});
```

**Comment by hirasso** [comment]
Dave, you are simply the best. In the entire internet.

**Comment by hirasso** [comment]
Is there also a way to detect if the slider is moving towards right or left?

**Comment by desandro** [comment]
yes, `flkty.velocity` will indicate how the slider is moving.
