### ISSUE TITLE
How to set the number of slides to display when flickity loads?

### ISSUE THREAD

**Issue by malik415** [metafizzy/flickity#526]
New to flickity, I'm trying to determine what's the best way to control the number of slides that get shown.  I couldn't find in the documentation where it states what controls how many slides show when the slider first loads.  I tried using "groupCells", but it doesn't seem to group them when I set the value to say "3". 

`$(mySlider).flickity({
                cellSelector: '.slide',
                cellAlign: 'left',
                wrapAround: true,
                pageDots: paging,
                prevNextButtons: arrows,
                autoPlay: autoplay,
                draggable: draggable,
                imagesLoaded: true,
		groupCells: 3
            });
`

Apologize if this isn't the right place for questions like.

**Comment by desandro** [comment]
Thank you for this question! You can set the number of visible cells by setting their width with your own CSS. See http://flickity.metafizzy.co/style.html#cell-style

**Comment by malik415** [comment]
Thanks, that worked.  I thought that was for just the height, but it works for width as well.

**Comment by vsasvipul0605** [comment]
Is there any way to set the limit of slider page dots count..?
As slider looks awful with so many page dots when there are so many slides
