### ISSUE TITLE
How to display Slides like Magazine Style 

### ISSUE THREAD

**Issue by aakocval31dms** [metafizzy/flickity#527]
Hi!

Is it possible to display slides in this order (Magazine Style): 
[0]       
[1] [2]    
[3] [4]     
[5]

Will display only 1 cell on first and last slide whilst 2 cells within the slider.

Thank you!

**Comment by desandro** [comment]
Yes! Use [groupCells](http://flickity.metafizzy.co/options.html#groupcells) and use CSS to set 100% width for cells 0 and 5, and 50% width for cells 2-4. See demo http://codepen.io/desandro/pen/3f696512ff336938ca3737dd001853a8/

**Comment by aakocval31dms** [comment]
wow brilliant! Thank you so much for your reply. By the way, what a great plugin!

**Comment by desandro** [comment]
You are welcome! Please consider starring this repo to support Flickity.

**Comment by aakocval31dms** [comment]
Hi!

How can I properly implement asNavfor for this? I will create image thumbnail for the main carousel.

Thanks again!
