### ISSUE TITLE
Custom pageDots functionality

### ISSUE THREAD

**Issue by richgcook** [metafizzy/flickity#528]
Apologies if this has been answered before but I'm trying to create my own pageDots UI. Fairly similar to how the default functionality works but I want to have a bit more flexibility with position etc.

I have created a reduced case test here: http://codepen.io/anon/pen/mWBwwm

You have see, in my JS, I have appended `.slider-pager`, using the slide count, to generate the individual 'dots'. This seems to work okay but the issue is when I click on the pager dots.

1. It doesn't want to add an active class on `cellSelect` as instructed.
2. If I click the last dot, it seems to go backwards... rather than forwards. Is there any way to control the direction (much like how the default pageDots work)

Thanks!

**Comment by desandro** [comment]
> It doesn't want to add an active class on cellSelect as instructed.

when you store `selectedIndex` as a variable...

```
var selectedIndex = flkty.selectedIndex;
```

then the variable does not get changed when the property `flkty.selectedIndex` does. You can resolve this by using `flkty.selectedIndex` instead. See demo http://codepen.io/desandro/pen/cf729b817735295d019171cd41a3c438/

> If I click the last dot, it seems to go backwards... rather than forwards. Is there any way to control the direction (much like how the default pageDots work)

This is now default pageDots work with `wrapAround` enabled. This feature was highly requested #113

**Comment by richgcook** [comment]
@desandro Thanks for clearing that up.
