### ISSUE TITLE
select.flickity event fired on window resize

### ISSUE THREAD

**Issue by bennybee** [metafizzy/flickity#529]
I want to fire a google analytics event each time someone interacts with a flickity instance. Either by pressing next arrow, pressing nav dot or dragging the carousel (I don't want it to fire if the carousel moves to next slide on autoPlay)

I've been looking at the select event but in the flickity example it is firing each time the browser window is resized:

http://codepen.io/desandro/pen/emVgqE

Is this intentional? Is there another way I could catch any kind of user interaction?

**Comment by desandro** [comment]
Thank you for this question

> Is this intentional?

Yes. When you resize the window, the carousel cells might have changed their layout via media queries. Flickity needs to re-select the current slide in order to properly lay out the cells.

One solution is to check if the selectedIndex has changed and log those events. See demo http://codepen.io/desandro/pen/ba29eb8f9155b0aa466622cb3056a0a0/

**Comment by bennybee** [comment]
Thanks for your reply. I tried your example code and it fixes the window resize issue but the event is also fired when the slides move automatically as part of the autoPlay. Is there a way to differentiate between a user-initiated slide change and an autoPlay slide change?

**Comment by desandro** [comment]
You could check for a conditional with `flkty.player.state == 'playing'`. It's undocumented, sorry about that!

``` js
$carousel.on( 'select.flickity', function() {
  // disregard same index select
  var isSameIndex = selectedIndex == flkty.selectedIndex;
  // disregard auto play selects
  var isPlaying = flkty.player.state == 'playing';
  if ( isSameIndex || isPlaying ) {
    return;
  }
  selectedIndex = flkty.selectedIndex;
  console.log( 'Flickity select ' + flkty.selectedIndex );
});
```

[See updated demo](http://codepen.io/desandro/pen/ba29eb8f9155b0aa466622cb3056a0a0/?editors=0011)

**Comment by bennybee** [comment]
That worked perfectly, thank you.

**Comment by Enchiridion** [comment]
I'm doing the exact same thing as OP.  It'd be nice if flickity would emit a true `change` event so I don't have to listen to `select` and filter everything out.  That's currently what I'm doing, then emitting my own `change.flickity` event.

**Comment by desandro** [comment]
@Enchiridion Yeah. I've added #701 to track this feature. It's time I added it.
