### ISSUE TITLE
Can I turn scrollbar?

### ISSUE THREAD

**Issue by pe6o** [metafizzy/flickity#53]
Hi, awesome plugin you have there. I'm a long time fan of your Isotope plugin and now this? Awesome!

I've been thinking if it's possible to turn on a scrollbar visibility on your carousel ( with `wrapAround: false` of course) .

I've tried this but doesn't seem to work as it should.
```
.flickity-viewport {
   overflow-x: scroll;
}
```

**Comment by desandro** [comment]
Hi there! Flickity does not support a scrollbar because it doesn't actually use scrolling. In theory, you could build a custom scrollbar for Flickity. But this would be re-building native UI, which is a bad practice. If you would like a scroll bar, then I recommend not using Flickity.
