### ISSUE TITLE
Parrallax Scrolling effect

### ISSUE THREAD

**Issue by sum-github** [metafizzy/flickity#530]
I have tried to put a parallax scrolling effect on the home page with a flickity slider mechanism.

.item {
	background-attachment: fixed;
}

It does not work at all in firefox, where parallax scrolling effect works in chrome to some extent but when the flickity slider goes through a transition, the background disappears and then reappears again.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by clarknelson** [comment]
I am having trouble with this also... I will create a test case.

**Comment by desandro** [comment]
Thanks for that. Looks like this is a browser issue. `background-attachment: fixed` works with natural page scrolling, whereas Flickity uses transforms for positioning elements. If you want to use `background-attachment: fixed`, then you're better off not using Flickity and using a simple `div` with`overflow-x: scroll`.
