### ISSUE TITLE
Flickity + drag and drop event

### ISSUE THREAD

**Issue by phelipemaia** [metafizzy/flickity#531]
Hi guys,

Does anybody know if is possible to combine the scroll of flickity (dragging) and drag and drop events (using draggable, ondragover, ondrop attributes)? I have one list of images that I should scroll over (swipe) but I also want to select one of them and add to another list using drag and drop.

Thanks

**Comment by desandro** [comment]
Sorry, no, this is not currently possible with Flickity. It works by listening for any touch down event to act as a drag. You may be able to hack a solution by listening for drag-item interactions with an inner element. I'll leave that solution to you.

**Comment by phelipemaia** [comment]
Yeah, thanks for reply @desandro But I think that won't work also. If I instantiate Flickity for one container, I can listen the events dispatch on the child elements, because Flickity will intercept every hit on the container. Am I right?

**Comment by desandro** [comment]
That's correct.
