### ISSUE TITLE
Click current cell to advance

### ISSUE THREAD

**Issue by richgcook** [metafizzy/flickity#533]
Hi @desandro thanks again for all your work that goes into flickity.

I have it set up so if you select the left or right cell it'll move to that cell but I'm wondering if you can do the same thing for current cell (so if you select the current cell it'll advance to the next). I'm unsure how much I agree with this but just curious!

Thanks!

```
$slider.on('staticClick.flickity', function(event, pointer, cellElement, cellIndex) {
	if (typeof cellIndex == 'number') {
		$slider.flickity('selectCell', cellIndex);
	}
});
```

**Comment by desandro** [comment]
Sure thing

``` js
$carousel.on( 'staticClick.flickity', function( event, pointer, cellElement, cellIndex ) {
  // dismiss if cell was not clicked
  if ( !cellElement ) {
    return;
  }
  
  if ( cellIndex == flkty.selectedIndex ) {
    // go to next if current cell selected
    $carousel.flickity('next');
  } else {
    $carousel.flickity( 'select', cellIndex );
  }
});

```

**Comment by richgcook** [comment]
Thanks @desandro – I'm sure I tried `if (cellIndex == flkty.selectedIndex ) {` but alas. Most appreciated.
