### ISSUE TITLE
How to get the caption of the first image

### ISSUE THREAD

**Issue by buck-danny** [metafizzy/flickity#535]
Hey,

I store the images caption in a data attribute and get it like this:

$carousel.on( 'select.flickity', function() {    
    var element = flkty.selectedElement;
  var caption = $(flkty.selectedElement).attr('data-caption')  
});

this works fine when I select a slide, but how can i get the data for the first slide? 

thanks alot!

**Comment by desandro** [comment]
I recommend using a function, then triggering that function for the initial caption.

``` js
var $carousel = $('.carousel').flickity({
  // options
});
var $caption = $('.caption');

var flkty = $carouse.data('flickity');

function setCaption() {
  captionText = $( flkty.selectedElement ).attr('data-caption');
  $caption.text( captionText );
}

// set initial caption
setCaption();

// set caption on select
$carousel.on( 'select.flickity', function() {
  setCaption();
});
```

**Comment by buck-danny** [comment]
thanks a lot!
