### ISSUE TITLE
Interfacing Flickity with Shiny & Bootstrap

### ISSUE THREAD

**Issue by harveymj** [metafizzy/flickity#538]
Hello, 

Apologies if this is a simple question, I am new to web-development. I am working with R and it's Shiny interface developing an app for process simulation. I would like to use Flickity within this app as I think that it will make the app more enjoyable for users. 

I have managed to get Flickity running in the Shiny interface (which is powered by bootstrap). My intent was to use the carousel to either display text or use for selecting inputs to a model. I currently have two tabs (pages) in the app (though there may be many). The carousel works brilliantly on the first page. However, on the second page, the content will not show up. I was able to follow your example on how to set up multiple instances, and the navigation appears to be in place on tab 2, only the content is missing.

I will paste my HTML for the page below, though I don't know how reproducible the example is because R does the conversion directly from source code to HTML. I appreciate that this may be slightly outside the intended scope, but any help would be much appreciated. 

Thank you

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by harveymj** [comment]
I had a look at this on codepen and I don't think that I'll be able to provide a test case as the program itself is not written in HTML directly. I've tried several times but I haven't been able to generate one that is close to what I'm trying to do. Writing a test case, I think, would similar to reengineering the entire R/Shiny complier - which I, unfortunately, can not do. 

I could share a simple reproducible example of my R code, if that is something that would be useful? 

However, I think that this may be similar to a previous question/issue upon further searching over the weekend - with the carousel on 'Page 2' / Tab 2 possibly being hidden when the page is initially loaded. Would it be possible to include an initializing script that searched through all the pages/tabs for carousel instances and initialized all of them when the page loads? 

Thank you for your help.

**Comment by harveymj** [comment]
As a quick update, I just reopened the app, I was on Tab 2 and the carousel was not working. I accidently resized the window while on Tab 2 and the carousel seemed to load upon resizing. I then checked Tab 1 and that carousel had disappeared. I do not know if this is useful information, but I thought this may be helpful.

**Comment by desandro** [comment]
A **reduced test case** is the best way to debug this issue.

**Comment by harveymj** [comment]
Hi David, 

I managed to get together a test case: http://codepen.io/harveymj/pen/JWVOMv

I am getting the same behavior in the test case as in the app. 

If you click on page 2 and then resize the codepen window the carousel on that page will run, but without a resize, it stays on panel 2.2. Once resized the carousel on page 1 will stick on slide 1.2.

Any help on this would be great. 

Thank you

**Comment by desandro** [comment]
Thanks for that test case! Looks like the issue is that Flickity needs to resize its measurements after its tab is shown. You can do this via [Bootstrap's `shown.bs.tab` event](http://getbootstrap.com/javascript/#tabs-events).

See demo http://codepen.io/desandro/pen/f26c07459bfbdd278c1cfa1a1fd42492/

[This behavior is mentioned in the docs](http://flickity.metafizzy.co/api.html#resize)

> If Flickity is initialized when hidden, like within a tab, trigger resize after it is shown so cells are properly measured and positioned.

**Comment by harveymj** [comment]
Hi David, 
Your solution works great. I figured that it was something simple. Thank you for your time, being new to web-development this was a _major_ help. 
All the best
