### ISSUE TITLE
Definine speed for autoPlay

### ISSUE THREAD

**Issue by lucassmacedo** [metafizzy/flickity#539]
How define a speed transition to a autoplay slider?

**Comment by desandro** [comment]
[From the autoPlay docs](http://flickity.metafizzy.co/options.html#autoplay)

``` js
autoPlay: 1500 // {Number}
// advance cells ever {Number} milliseconds
// 1500 will advance cells every 1.5 seconds
```

**Comment by dillonburns** [comment]
I'm interested in this as well, not the speed of the interval, but the speed of the transition itself. It seems like it takes about 200ms to transition to the next cell. Is this value editable at all?

My overall goal is to have the autoPlay number (what i'm calling the interval number) match the transition number, so the carousel is constantly slowly scrolling.

**Comment by lucassmacedo** [comment]
@dillonburns this is my question...

**Comment by dillonburns** [comment]
I'm currently poking around flickity.pkgd.js, i'll keep you posted!

**Comment by desandro** [comment]
[Try setting selectedAttraction and friction](http://flickity.metafizzy.co/options.html#selectedattraction-friction)

> selectedAttraction and friction are the two options that control the speed and motion of the slider.
>
> selectedAttraction attracts the position of the slider to the selected cell. Higher attraction makes the slider move faster. Lower makes it move slower. Default selectedAttraction: 0.025.
> 
> friction slows the movement of slider. Higher friction makes the slider feel stickier and less bouncy. Lower friction makes the slider feel looser and more wobbly. Default friction: 0.28.

**Comment by jigneshdrc** [comment]
If i want to specify different transition time for only first slide then how we can do it?
For example:- First slide of the slider will have transition time of 12 sec and all other slides will have transition time of 5 sec

Is this something possible?

Thanks for quick help on this.

**Comment by desandro** [comment]
> If i want to specify different transition time for only first slide then how we can do it?

You'll have to start autoPlay after you manually trigger the first advance

``` js
// init Flickity
var $carousel $('.carousel').flickity({
  // options, do not enable autoPlay
});

setTimeout( function() {
  $carousel.flickity('next');
  $carousel.flickity('playPlayer');
}, 1200 );
```

See Player methods https://flickity.metafizzy.co/api.html#player

**Comment by jigneshdrc** [comment]
Thanks for your quick help on this :)
I will apply your solution and will let you know on this.

**Comment by desandro** [comment]
Here's another way to do it:  https://codepen.io/desandro/pen/gvKKrN/

I'm setting autoPlay option, using selectedIndex and select event

**Comment by jigneshdrc** [comment]
yes, it is working fine.
Thanks a lot :)
