### ISSUE TITLE
Slide disappears while finger is down in Mobile Safari iOS 10.3/iPhone 6s

### ISSUE THREAD

**Issue by animaux** [metafizzy/flickity#541]
No need for a test-case as the first example on `flickity.metafizzy.co` also behaves this way.

When you touch the slide – it disappears. Layout behaves like it has zero height then. When you then drag it to the left and remove your finger it reappears and moves as expected.

**Comment by animaux** [comment]
Can anyone confirm this behavior?

**Comment by desandro** [comment]
Thanks for reporting this bug. I was not able to reproduce on my iPhone 5s with iOS 10.3. I'll keep this issue open in case anyone else runs into it.

**Comment by animaux** [comment]
I already suspected it, but can now confirm. The Umbra content blocker for Safari is the problem. Switching it off makes it work. Not sure what it does to cause this. I’m closing since this is a special case. Thanks David!

**Comment by desandro** [comment]
Thanks for following up!

**Comment by traf** [comment]
Is there any sort of workaround for this? There are many people who use Umbra on mobile.
