### ISSUE TITLE
Slides change margins when orientation is changed

### ISSUE THREAD

**Issue by aminebenkeroum** [metafizzy/flickity#542]
The slides are changing their margins when the orientation changes on Safari, iPhone 7. 

There are some websites using "resize" listener but I can't figure out what the handler is doing.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
