### ISSUE TITLE
flickity is not defined with jquery

### ISSUE THREAD

**Issue by giacomoalonzi** [metafizzy/flickity#543]
Hello, i'm imported flickity like this 

`import $ from 'jquery'
import 'flickity/dist/flickity.pkgd'`

and then 

`$('.class-name').flickity({ // options here })`

but I have an error where flickity is not defined. Anyone can help me?

This happen only with jQuery, with vanilla js work perfectly
jQuery version used 1.12.4 and 3.1.1, same error.

Thank you.

**Comment by desandro** [comment]
You'll likely need to initialize Flickity as a jQuery plugin, [similar to using Browserify](http://flickity.metafizzy.co/extras.html#browserify)

> To use Flickity as a jQuery plugin with Browserify, you need to call jQuery Bridget.

``` js
npm install jquery-bridget
var $ = require('jquery');
var jQueryBridget = require('jquery-bridget');
var Flickity = require('flickity');

// make Flickity a jQuery plugin
jQueryBridget( 'flickity', Flickity, $ );
// now you can use $().flickity()
$('.carousel').flickity({...});
```

**Comment by giacomoalonzi** [comment]
I'm going to try early! Thank you!
