### ISSUE TITLE
Allow maximum groupCells size?

### ISSUE THREAD

**Issue by nickwanninger** [metafizzy/flickity#544]
Is there a way to set a maximum number of items alllowed in a single group with
`"groupCells": true,`? I love the fact that it automatically adjusts based on the number of items can fit, but I would like to cap the number of items at 2. Is there any way of doing this currently?

**Comment by nickwanninger** [comment]
I jerry rigged it for now by calculating in the resize event with `Math.min(2, number_of_items)`

This would be nice to see in the default config though

**Comment by desandro** [comment]
I recommend using a percent string like '80%'. Items that take up <= 80% of the width will be used as a group. See demo http://codepen.io/desandro/pen/mEBPQG
