### ISSUE TITLE
Animate when resizing width

### ISSUE THREAD

**Issue by maimairel** [metafizzy/flickity#545]
Hello, 

When `flickity.resize` is called manually after a container width resize the change is not animated. When the slider is positioned with the last cell visible, this change doesn't look very nice.

It can be seen from the DOM that translateX is directly assigned to the `flickity-slider` instead of animating it using `translate3d`. Is there anyway so the change is animated upon resize? Perhaps by specifying a boolean for the `.resize` method?

Thank you!

**Comment by maimairel** [comment]
After looking at the `resize` method it seems the change is not animated because isInstant is set to true when `selectCell` is called. Any work around?

**Comment by desandro** [comment]
Thanks for this feature request.

You could hack it by setting 
``` css
.carousel-cell { transition: left 0.3s; }
```

See demo http://codepen.io/desandro/pen/mmVMRV
