### ISSUE TITLE
Flickity carousel cursor options

### ISSUE THREAD

**Issue by bsbytnyi** [metafizzy/flickity#546]
Are there any js options for cursor?
It looks like I can do this in css only.

**Comment by desandro** [comment]
There are no JS options for cursor, but you can control the cursor with CSS as you mention. What are you looking to do, that you would require JS?

**Comment by bsbytnyi** [comment]
Ok, no problem. I found it in flickity.css. 
But i think it would be more flexible and easier to control cursor via js option like this: cursor: 'default' / 'pointer' / 'grab' / 'text'. 

p.s. Thanks a lot for the great stuff!
