### ISSUE TITLE
Transition duration

### ISSUE THREAD

**Issue by fireform** [metafizzy/flickity#549]
Hi David!

Is it possible to calculate transition duration value using selectedAttraction and friction values for modifying autoplay dynamically or just use autoplay as interval before transitioning programmatically? Actually, autoplay speed is including animation duration so the time before initial sliding isn't equal to the time between all next transitions which is quite odd. Basically, interval between all transitions except first = autoplay - transition duration. I hope it's clear.

Regards

**Comment by desandro** [comment]
Hello! Thanks for this question. Theoretically, there could be a way to calculate how long the animation takes to advance from one slide to another. I imagine it'll take some calculus. Unfortunately, I do not have this calculation available.

I'm curious: what are you looking to do with this?

**Comment by fireform** [comment]
Hi David,
Thanks a lot for your prompt reply.
I created progress bar that mimics a countdown. So it restarts after every transition and goes from 100% to 0 before next slide animation starts. It works using CSS animation. So, interval becomes not equal to animation duration after initial transition (initial interval is 4000ms for example, other intervals are 4000ms - ~2000ms (slide transition) = ~2000ms which depends on selectedAttraction and friction). Now I'm changing autoplay option dynamically via 'flickity.select' to set equal interval between all transitions, but the problem is that now I "hardcode" slide animation duration, because I don't know  how to calculate it. It could be nice if you can share any thoughts :)

Regards

**Comment by desandro** [comment]
Sorry, I don't have recommendations on how to make the calculation. You'll have to dig into [animate.js](https://github.com/metafizzy/flickity/blob/v2.0.6/js/animate.js).
