### ISSUE TITLE
Disable pausing autoPlay on hover

### ISSUE THREAD

**Issue by madebydominick** [metafizzy/flickity#55]
As far as I can tell, it's not possible to disable this as yet.

Is this in the works? If it not, can it be added?

**Comment by desandro** [comment]
Pausing autoPlay on hover is a good pattern as it puts some level of control back to the user looking at the gallery. IMO, removing it would be an anti-pattern.

But I'm interested to hear what others think. If you would like to see this feature added to Flickity, **+1** or subscribe to this issue.

**Comment by zslabs** [comment]
+1

A typical pattern for this could be if Flickity was used as a "full-page" background-slider for photography websites that you'd want to auto-cycle through. Not my personal preference, but a valid use-case nonetheless.

**Comment by remisture** [comment]
+1

**Comment by SoullessWaffle** [comment]
+1

**Comment by stubear** [comment]
+1

**Comment by mbryne** [comment]
+1

**Comment by mogholito** [comment]
+1

**Comment by limpa123** [comment]
+1

**Comment by halfempty** [comment]
+1

**Comment by jonnyhaynes** [comment]
+ 1

**Comment by PaoloFalomo** [comment]
+1

**Comment by notflip** [comment]
+1!

**Comment by elainen** [comment]
+1

**Comment by permanyer** [comment]
+1

**Comment by gordonwes** [comment]
+1

**Comment by PaoloFalomo** [comment]
+1

**Comment by nicholas-c** [comment]
+1 only if it's an option and not default

**Comment by joshrounsville** [comment]
+1

**Comment by wekii** [comment]
+1

**Comment by chrishale** [comment]
+1

**Comment by nlfonseca** [comment]
+1

**Comment by fizzydigital** [comment]
+1

**Comment by tgadiot** [comment]
+1

**Comment by emidiotorre** [comment]
+1

**Comment by HammenWS** [comment]
+1

**Comment by michaelwoodruff** [comment]
>> IMO, removing it would be an anti-pattern
I agree

Although judging by the number of +1 it seems a lot of people want it.

**Comment by hardley** [comment]
+1

**Comment by alemur** [comment]
+1

**Comment by bootsified** [comment]
+1 Yes, it's an anti-pattern if the slider is part of the UI.  I have a site, though, that uses the slider as a fullscreen background behind the content.  I need to be able to disable the "pause on hover".  It would be really nice to have the option, even though it would rarely get used.

**Comment by nvartolomei** [comment]
I agree that this is an anti pattern usually but when using flickity for full screen sliders this is an issue.

+1 :+1:

**Comment by Jray3D** [comment]
+1 for full screen sliders it would be really helpful.

**Comment by desandro** [comment]
Next version will have `pauseAutoPlayOnHover` option. Set this `pauseAutoPlayOnHover: false` to keep autoPlay playing on hover.

**Comment by richgcook** [comment]
@desandro I had a quick question. I have custom left/right nav set up which is 50% split over the image, so if you hover over the left and click, the slider proceeds previous and if you hover over the right the slider proceeds next. By having this, however, it seems to have voided the hover and pause function as there is a higher z-index container over the slider. Is there any way to call the pause method so I could bind it if the user hovers over the higher z-index container rather than the slider?

**Comment by desandro** [comment]
@richgcook Yes see https://github.com/metafizzy/flickity-docs/issues/5#issuecomment-78370765 for the Player API

**Comment by desandro** [comment]
Flickity v1.1.2 has been released with [`pauseAutoPlayOnHover` option](http://flickity.metafizzy.co/options.html#autoplay). See `pauseAutoPlayOnHover: false` to keep autoPlay playing on hover. See demo http://codepen.io/desandro/pen/yeeQJK

Thanks for all the feedback on this issue. :rainbow: :bear:

**Comment by richgcook** [comment]
@desandro Amazing! Thanks!

**Comment by richgcook** [comment]
@desandro Ah right yes so I'd still need to use the Player API if I have custom left/right nav on a higher z-index over the slider. Be nice if you could add a selector to the `pauseAutoPlayOnHover` for example `pauseAutoPlayOnHover: '.slider-navigation'. Thanks for all your help.

**Comment by dalvujovic** [comment]
Please ,when slide is clicked autoplay stops,i dont want that,how to make autoplay to work after clicking

**Comment by dicktornfeldt** [comment]
@dalvujovic I solved this by adding `pointer-events: none` to a wrapper div.

**Comment by luksak** [comment]
@dicktornfeldt that only works as long as you don't need to have anything clickable in the slideshow. In my case I have links that stop working with this approach.

Here is one that keeps the elements clickable:

```
flkty.on('click', () => {
  flkty('playPlayer');
});
```
