### ISSUE TITLE
Multiple sliders with counter

### ISSUE THREAD

**Issue by thiebou** [metafizzy/flickity#550]
How can i use multiple sliders on one page with a counter?

For one slider this works..

```
var flkty = new Flickity( '.carousel', {
  // options
    
    lazyLoad: 2, 
    initialIndex: 1, 
    percentPosition: false, 
    pageDots: false 
    
});


var carouselStatus = document.querySelector('.carousel-status');

function updateStatus() {
  var slideNumber = flkty.selectedIndex + 1;
  carouselStatus.textContent = slideNumber + '/' + flkty.slides.length;
}
updateStatus();

flkty.on( 'select', updateStatus );

```

**Comment by desandro** [comment]
Thanks for submitting this issue.

> How can i use multiple sliders on one page with a counter?

I'm not sure what you're trying to achieve.  Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by thiebou** [comment]
Hello,

On a single page i want to use multiple sliders (if possible with html init) with a slide counter for each slider.

http://codepen.io/anon/pen/oWyGrQ

**Comment by desandro** [comment]
Thanks for that. Looks like I got a similar question recently answered. See answer at https://github.com/metafizzy/flickity/issues/558#issuecomment-301499190
