### ISSUE TITLE
Integrate Flickity With Bootstrap 4 Carousel

### ISSUE THREAD

**Issue by aice09** [metafizzy/flickity#551]
Hi Sir! 

I've been interested on the TechGirl post at http://stackoverflow.com/questions/43650566/integrate-flickity-with-bootstrap-4-carousel  last April 27, 2017. This is by integrating Flickity into Bootstrap 4 carousels .The following pens are located at https://codepen.io/aice09/pen/xdrMoX.  

Is this possible for the flickity to be integrate into Bootstrap 4 carousel without any changes with Bootstrp 4 carousel existing styles but the Flickity ability to add touch, reponsive, and flickible carousels are present.

**Comment by desandro** [comment]
Sorry you cannot use both Bootstrap carousel and Flickity at the same time. They are two separate solutions for the same feature. I recommend you choose either one or the other.

You can use some of the interior `carousel` Bootstrap CSS like `carousel-caption` within a Flickity carousel.  See demo https://codepen.io/desandro/pen/0b21742d14871f88a56893eeee7011c7/
