### ISSUE TITLE
The height of my slider is cropping some content

### ISSUE THREAD

**Issue by Ollie-w** [metafizzy/flickity#552]
I have setGallerySize set to true and yet the height of the cells is less than that of their content. (I have a mixture of both text and an image, if that makes any difference)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
