### ISSUE TITLE
Flickity Viewport height goes 0 on mobile

### ISSUE THREAD

**Issue by maaxxicarvalho** [metafizzy/flickity#553]
Hello there,

I am having an issue with the mobile version of my website.
The flickity viewport height will be set to ZERO on mobile devices.

I know that you ask for a test case using the CodePen app but it'll be really hard to do it since I have a full application, so I'm giving you the URL of the development environment:
- https://newtheme.180smoke.ca/

and the mobile view:
- https://sizzy.co/?url=https%3A%2F%2Fnewtheme.180smoke.ca%2F

I will understand if without the test case you find that's not possible to help me but I would really appreciate if you could try.

**Comment by desandro** [comment]
I believe the issue is likely due to using flex box CSS for `.carousel-cell`. You can use flex box for interior content, but using on cells themselves might throw off Flickity.

That's only a suspicion. Without a reduced test case, I cannot properly debug and test a possible solution.

**Comment by maaxxicarvalho** [comment]
Hi @desandro 
Thanks for your reply and I'm sorry about the delay. I tried a reduced test case here http://codepen.io/maaxxicarvalho/pen/rmpyrp
I'm using Bulma.io.

Apparently, the `flickity-viewport` is not being properly resized.

**Comment by desandro** [comment]
Looks like you're using percentage sizes for the cells. So it will inherit the size of its parent. If you want to use these styles, you'll have to see a size for the carousel and disable `setGallerySize`. See https://flickity.metafizzy.co/options.html#setgallerysize

``` css
.smoke-carousel-cell {
  width: 100%;
  height: 100%;
}
```

**Comment by maaxxicarvalho** [comment]
I was able to fix the issue by setting a fixed height to the images.
Thanks for your help ;-)
