### ISSUE TITLE
Issue with "adaptiveHeight" and "groupCells" and "contain: true"

### ISSUE THREAD

**Issue by enesemini** [metafizzy/flickity#554]
Hey @desandro 

I love Flickity! With that out of the way, I noticed an odd issue with flickity, when using "adaptiveHeight" with "groupCells".

I got a test case here on codepen: http://codepen.io/enesemini/pen/ZKargg

Basically, when I have a groups enabled (e.g. 4 items per "page") with different height items, and I have 5 items in total, and I go to the next page (item 5 is smaller than any of 1-4), the slider adapts to the height of item 5, whereas items 2-4 are larger, and still visible. Items 2-4 will all be cut off. I have the options contain: true and cellAlign: left. "wrapAround" doesn't help.

Using "contain: false" would be an option, but I would prefer avoiding this.

And help would be appreciated!

**Test case:** http://codepen.io/enesemini/pen/ZKargg

**Comment by desandro** [comment]
Thank you for reporting this issue and providing a reduced test case.  I can clearly see the issue.

You can get a better sense of what's going on, by disabling `contain`. See demo http://codepen.io/desandro/pen/ea9a342711eaccf4678e62110677d3c9/

Cells 1-4 are fit within the carousel, so they are considered a single slide. The height of the carousel is set to the tallest cell. Cell 5 is a separate slide. When cell 5 is selected, the carousel height is set to its height. Although some of the cells 1-4 are still viewable when cell 5 is selected, they are not accounted for in the height of the carousel. This would require additional code that measures and checks what cells are viewable when what slides are selected — it'd be complex.

So everything is working as intended. I'm sorry to say I don't feel this is a bug, just more a conflict of features. As you mentioned, you can resolve this by disabling `contain`.

**Comment by enesemini** [comment]
Thank you for your answer.

I feel like multiple options should be compatible with each other, but I understand your point.

Thanks nonetheless, for the otherwise phenomenal slider ;)

**Comment by patricekaufmann** [comment]
If anybody else finds this issue via google, by the first looks I managed to solve the problem with the following extension. Basically you create an intersection observer to then set a class to check if a cell is in the slide viewport. Then to override the setGallerySize function to check all elements that are in the viewport, and set larger height if neccessary.

You can replace `this.on('scroll', this.setGallerySize);` with the `settle` event if you worry about performance here.

```
    Flickity.createMethods.push('_createIntersectionObserver');

    Flickity.prototype._createIntersectionObserver = function () {
        this.observer = new IntersectionObserver((entries, observer) => {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('in-flickity-viewport');
                } else {
                    entry.target.classList.remove('in-flickity-viewport');
                }
            });
        }, {
            root: this.viewport,
            rootMargin: `0px`,
            threshold: 0
        });
        this.on('scroll', this.setGallerySize);
    }

    const originalUpdateSlides = Flickity.prototype.updateSlides;

    Flickity.prototype.updateSlides = function() {
        if (this.slides) {
            this.slides.forEach((slide) => {
                slide.cells.forEach((cell) => {
                    this.observer.unobserve(cell.element);
                });
            })
        }
        originalUpdateSlides.call(this);
        this.slides.forEach((slide) => {
            slide.cells.forEach((cell) => {
                this.observer.observe(cell.element);
            });
        })
    }

    Flickity.prototype.setGallerySize = function () {
        if (this.options.setGallerySize) {
            var height = this.options.adaptiveHeight && this.selectedSlide ? this.selectedSlide.height : this.maxCellHeight;
            this.slides.forEach((slide) => {
                slide.cells.forEach((cell) => {
                    if (cell.element.classList.contains('in-flickity-viewport') && cell.size.height > height) {
                        height = cell.size.height;
                    }
                });
            })
            if (height + 'px' !== this.viewport.style.height) {
                this.viewport.style.height = height + 'px';
            }
        }
    }
```
