### ISSUE TITLE
URL links to cell with inter-cell links

### ISSUE THREAD

**Issue by vilav** [metafizzy/flickity#555]
Hello,

Noob issue with a use case:
Overall, I have multiple Flickity sliders on the same page.
The intent is to have a URL for bring up each cell in each of the sliders.
Additionally, trying to have the first cell have a link to the third cell of the same slider.
A bit lost:

JSFiddle: https://jsfiddle.net/qw95v1br/

Thanks

**Comment by desandro** [comment]
Thank you for this issue.

Flickity has a [`selectCell` method](https://flickity.metafizzy.co/api.html#selectcell), which allows you to pass in a CSS selector to select a cell.

As for the URLs, I've got an open ticket for this feature. See #411 . I still need to provide a demo (sorry!)

**Comment by vilav** [comment]
@desandro Thanks, will await your updated demo.
