### ISSUE TITLE
Clickable cell only when is-selected

### ISSUE THREAD

**Issue by tatimblin** [metafizzy/flickity#557]
Hi Dave, loving Flickity so far!

 I have a question about using the .is-selected class to make cells clickable but only when it is active. Right now I have it where you can click on a cell to run a function, but it runs when any cell is clicked. How can I run a function for only on click of the currently selected cell?

Thank you.

Here is my forked demo. [http://codepen.io/tatimblin/pen/LydEKr](http://codepen.io/tatimblin/pen/LydEKr)

**Comment by desandro** [comment]
Thank you for this question! You can check if the clicked element is the selected element with this code:

``` js
var $carousel = $('.carousel').flickity();
// Flickity instance
var flkty = $carousel.data('flickity');

$carousel.on( 'staticClick.flickity', function( event, pointer, cellElement, cellIndex ) {
  if ( cellElement == flkty.selectedElement ) {
    console.log('selected element clicked')
  }
});
```

Se demo http://codepen.io/desandro/pen/9b37c2db51b32733f76bdb62984835f2/?editors=0011

**Comment by tatimblin** [comment]
Thanks so much for the fast response!! Put the code in and worked like a charm.

**Comment by desandro** [comment]
Glad I could help! Please consider support Flickity's development by [purchasing a commercial license](https://flickity.metafizzy.co/#commercial-license) (if you haven't already).
