### ISSUE TITLE
slide number / slides - multiple carousels

### ISSUE THREAD

**Issue by kreativstau** [metafizzy/flickity#558]
Hello, 

im refering to this: https://codepen.io/anon/pen/NjzYwp

Im using this code to caption multiple carousels in a loop in Wordpress. To let the code know, with carousel i am referring to, i added a specific id to each carousel. Still only the last carousel-status updates, but the correct number of slide for each carousel is shown. 

Here my code (within the loop, so its generated multiple times - maybe thats the issue?):  

```
			    <script>	
					var flkty = new Flickity('#carousel-<?php the_sub_field('galerie_id'); ?>');
					var carouselStatus = document.querySelector('#carousel-status-<?php the_sub_field('galerie_id'); ?>');
					
					function updateStatus() { 
					  var slideNumber = flkty.selectedIndex + 1;
					  carouselStatus.textContent = 'P ' + slideNumber + ' — ( ' + flkty.slides.length + ' )'; 
					}
					updateStatus();
					
					flkty.on( 'select', updateStatus );	
			    </script> 	
```

Any ideas? 

Thanks

**Comment by desandro** [comment]
Thank you for this question. My recommendation is wrap each carousel + counter combo a container element. Then loop through those containers and initialize each. This way, the carousels and counters are encapsulated from one another, and you can re-use the same initialization code.

See demo https://codepen.io/desandro/pen/60e8036ccbe34f8375d7b1021995dad8/

``` js
var carouselContainers = document.querySelectorAll('.carousel-container');

for ( var i=0; i < carouselContainers.length; i++ ) {
  var container = carouselContainers[i];
  initCarouselContainer( container );
}

function initCarouselContainer( container ) {
  var carousel = container.querySelector('.carousel');
  var flkty = new Flickity( carousel );
  var carouselStatus = container.querySelector('.carousel-status');

  function updateStatus() {
    var slideNumber = flkty.selectedIndex + 1;
    carouselStatus.textContent = slideNumber + '/' + flkty.slides.length;
  }
  updateStatus();

  flkty.on( 'select', updateStatus );
  
}
```

**Comment by kreativstau** [comment]
Works linke a charm. Thank you!

**Comment by thiebou** [comment]
Thanks for your reply!
How can i make it work with html init?

**Comment by desandro** [comment]
If you're already using JavaScript to update the counters, then I recommend initializing Flickity with JS.

**Comment by asmundsollihogda** [comment]
This is a great solution! Thank you!

**Comment by desandro** [comment]
I recommend looking at [Fizzy School - Lessons in JavaScript for anyone writing jQuery](http://fizzy.school). It contains several concepts at work with this code.
