### ISSUE TITLE
Flickity viewport collapses when viewport height:100% and img are height:auto in carousel-cell

### ISSUE THREAD

**Issue by kreativstau** [metafizzy/flickity#559]
Hello, 

after really trying out anything - a last question. Is it correct, that adaptive height will not let me to the following: 

```
<div class="carousel" data-flickity='{ "adaptiveHeight": true, "imagesLoaded": true }'>
<div class="carousel-cell" style="width: 100%;"><img src="" style="width: 100%; height: AUTO;" /></div>
<div><img src="" style="width: 100%; height: AUTO;" /></div>
</div>
```

The images used are always bigger than the carousel for responsive reasons, but they all have the same ratio. I want to achieve that the image scales a 100% of the carousel-cell, which has the width of 100% of the window. And the carousel itself should have the height according to this width. I hope Im explaining this rather understandable.

I also tried "setGallerySize: false" - also not the result i wanted to achieve. The images always end up bigger than the carousel-cell. I also did not get there with background-images, because i need the image to set the size of the parent div, right? 

Thank you

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by kreativstau** [comment]
Thanks, i was able to solve this by setting "setGallerySize: false" and change the .flickity-viewport.

**Comment by kreativstau** [comment]
This is still troubling me. Now I am having issues when loading in different browsers. My code ist

```
.carousel {
	width: 100%;
	margin: 0 auto;
}

.carousel-cell {
	width: 100%;
	height: auto;
}

.carousel-cell-img {
	width: 100%;
	height: auto;
}

.flickity-viewport {
	height: 100%;	
}
```
					
```
<div class="carousel-container">
<div class="carousel" data-flickity='{ "setGallerySize": false, "imagesLoaded": true }'>
<div class="carousel-cell">
<img src="<?php echo $image['url']; ?>" class="carousel-cell-img" alt="">
</div>
</div>
```

Even though i activated imagesloaded around 50% of the times I load the Page, the viewport ends up with a high of around 20px - see attached. Then again, it works perfectly. 

Any ideas someone? 

Thanks in advance.

![bildschirmfoto 2017-05-15 um 23 21 23](https://cloud.githubusercontent.com/assets/8202191/26080098/5e1921e8-39c5-11e7-858b-ae30096c7aa0.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by kreativstau** [comment]
I am refering to this: http://codepen.io/anon/pen/qmymXX

**Comment by desandro** [comment]
See this demo for 100% height carousel: http://codepen.io/desandro/pen/VLrReY

**Comment by kreativstau** [comment]
Thanks, i already saw that one. But i am not trying to achieve a 100% height carousel. The height should be defined by the img (height:auto and width: 100%;) in the carousel-cell. By the way: All images have the same size (but still the 100% width is responsive.) Get it?

**Comment by desandro** [comment]
Then you'll need to enable `setGallerySize`. I also recommend setting `display: block` on the images. See demo http://codepen.io/desandro/pen/268028c27d4c21464ba9e77bc8d8653f/

**Comment by kreativstau** [comment]
Thank you desandro, unfortunately this does not work too :( Two things happen: 

a) The Viewport ist bigger than the picture (about 175px or so)
b) from time to time the viewport still collapses. I used the demos code: 

```
				<div class="carousel-container">
                	<div id="carousel-<?php the_sub_field('galerie_id'); ?>" class="carousel" data-flickity='{ "imagesLoaded": true }'>
                  
                    <?php $images = get_sub_field('portfolio_referenz_galerie_content');
                       if( $images ): ?>				
				
                            <?php foreach( $images as $image ): ?>		
					<div class="carousel-cell">    		
						<img src="<?php echo $image['url']; ?>" alt="" class="carousel-cell-img" />
					</div>
                            <?php endforeach; ?>
					
                    <?php endif; ?>

              	  </div>
```

```
.carousel {
	width: 100%;
	margin: 0 auto;
}

.carousel-cell {
	width: 100%;
	height: auto;
}

.carousel-cell-img {
	width: 100%;
	height: auto;
  	display: block;
}

.flickity-viewport {
	height: auto;	
	border: 1px solid red;
}
```

**Comment by kreativstau** [comment]
Ok, so this is my workaround if anyone is interested.

Refering to this: 

I removed the carousel-cell and added this script: 

```
<script type="text/javascript">
$(function () {
    function setHeight(ab) {
        var target = $('.carousel-cell-img'),
            heightImage;
        if (target[0].complete || target[0].readyState === 4) {
            heightImage = target.height();
            ab.height(heightImage);
        }
        else {
            target.on('load', function () {
                heightImage = $(this).height();
                console.log(heightImage);
                ab.height(heightImage);
            });
        }
    }
    setHeight($('.flickity-viewport'));
    $(window).resize(function () {
        setHeight($('.flickity-viewport'));
    });
});
</script>
```

This only works, if all your images have the same size.

**Comment by desandro** [comment]
Sorry, I will not be able to provide personal support for this issue.

**Comment by justlevine** [comment]
Hey, i know this is old and closed, but since its the first google result, figured Id post the non-js solution here for anyone else who stumbles on this and spends hours trying to figure it out (like I did)

Seems this issue occurs when none of the parents elements have a px height set before a flex element.

My solution is to add `padding-top: x%` to `.flickity-viewport`, and a `margin-top: -x%` to `.flickity-slider.`

[https://codepen.io/anon/pen/dwzrEb](https://codepen.io/anon/pen/dwzrEb)

**Comment by cheeseytoastie** [comment]
> Hey, i know this is old and closed, but since its the first google result, figured Id post the non-js solution here for anyone else who stumbles on this and spends hours trying to figure it out (like I did)
> 
> Seems this issue occurs when none of the parents elements have a px height set before a flex element.
> 
> My solution is to add `padding-top: x%` to `.flickity-viewport`, and a `margin-top: -x%` to `.flickity-slider.`
> 
> https://codepen.io/anon/pen/dwzrEb

Justlevine - THANK YOU! I'm buying a random person a beer in your name.

**Comment by mjelectrolibrary** [comment]
> Hey, i know this is old and closed, but since its the first google result, figured Id post the non-js solution here for anyone else who stumbles on this and spends hours trying to figure it out (like I did)
> 
> Seems this issue occurs when none of the parents elements have a px height set before a flex element.
> 
> My solution is to add `padding-top: x%` to `.flickity-viewport`, and a `margin-top: -x%` to `.flickity-slider.`
> 
> https://codepen.io/anon/pen/dwzrEb

Thanks Justlevine!! I too will buy someone a drink!

**Comment by drewbetts** [comment]
Justlevine - THANK YOU! I too am joining the beer buying for a stranger team. For anyone else using a 3:2 ratio, my padding/margin-top was 66.67%
