### ISSUE TITLE
fullscreen or zoom ?

### ISSUE THREAD

**Issue by pepperstreet** [metafizzy/flickity#56]
Hello, just curious if there are plans to integrate a **fullscreen** option? i.e. a click on an image zooms the slider to whole screen height and width.

Examples:

Apple subpage / see photo-strip below the video hero
http://www.apple.com/start-something-new/

Even cooler, Codrops playground project "Draggable Dual-View Slideshow"
http://tympanus.net/Development/DraggableDualViewSlideshow/

If no direct implementation, what about combining a 3rd-party lightbox script?  
Thanks in advance.

**Comment by desandro** [comment]
Thanks for your feature request. We've got a full screen feature request already open. I'll close this as a duplicate of #28
