### ISSUE TITLE
Auto-play wont stop on custom next/prev click

### ISSUE THREAD

**Issue by iamdesfranco** [metafizzy/flickity#561]
Hi, I cant seem to get my slider to stop Auto play when clicking my custom next/prev buttons. The auto-play stops when I drag on the slides or click the dots but not on my custom buttons. Is there something that I need to do to make this work?

**Comment by desandro** [comment]
Hello! Thanks for this question. Yes, Flickity is working as intended. You can stop the player by using a `stopPlayer` method. You'll have to add this code to your custom prev/next buttons. See demo http://codepen.io/desandro/pen/299b82545fff31fa4b27c6e3eb454d46/
