### ISSUE TITLE
matchMedia or CSS media query to change amount of dots?

### ISSUE THREAD

**Issue by Ollie-w** [metafizzy/flickity#562]
Is it possible for Flickity to recalculate the amounts of dots that are needed? 
I am using CSS media queries to control the width of the cells - 50% width on mobile, 33% on tablet, 25% on desktop - so that two cells show on mobile at a time, three on tablet and 4 on desktop, There will be 12 cells total so ideally i would like 6 dots on mobile, 4 on tablet and 3 on desktop. Is this possible?

**Comment by desandro** [comment]
Thank you for your question. Could you provide a **reduced test case** with what you're trying to achieve? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

Have you looked at using [`groupCells`](https://flickity.metafizzy.co/options.html#groupcells)
