### ISSUE TITLE
imagesLoaded when wrapped in a link

### ISSUE THREAD

**Issue by Borkent** [metafizzy/flickity#563]
Hi there,

Flickity rocks!

I am trying to have variety of landscape and portrait images in a slider.
However when I wrap them in a link, they loose their imagesLoaded auto sizing when out of view.

Any way to get this to work? I would love to be able to open these images in a lightbox on click. All I need is the slides to be sized outside of view when added as `<a href="" rel=""><img here></a>`

Kind regards,
Thomas

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by Borkent** [comment]
I am playing around, I see its something in the css.
As soon as I add the css on codepen it breaks.

http://codepen.io/anon/pen/qmvVmE

**Comment by desandro** [comment]
Looks like a CSS bug. I had to remove

``` css
.carousel img { max-width: 100%;}
```

See demo https://codepen.io/desandro/pen/f5783395e2d8e5070b01029401060e75/

**Comment by Borkent** [comment]
Hi desandro,

Thank you, with your guidence I found the issue, the base theme had max-width:100% set on all img elements.
Therefor when I removed above from my css it was still bugging out. 

`.carousel img { max-width: initial;}`

Fixed the issue. 

Thank you, Resolved!

**Comment by Borkent** [comment]
re opened as I realised you would probably not read the fix if I closed it. close when you wish!

**Comment by desandro** [comment]
Thanks for following up! I see these threads even if you close them.
