### ISSUE TITLE
Unable to focus on slide items

### ISSUE THREAD

**Issue by felipearosemena** [metafizzy/flickity#565]
I've found that I'm unable to focus on child elements of the slider on click. Please refer to the reduced test case: https://codepen.io/anon/pen/YVMmzp

Before initialization, I can focus with no problem. After init, it seems like the elements inside the slider are not focusable.

Is this behaviour intended?

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. Yes, this behavior is intended. Flickity listens for clicks and will set the focus on the Flickity container element. This allows users to use keyboard navigation: tabbing to Flickity, then using left & right keys to advance/go back. You can disable keyboard navigation accessibility with [`accessibility: false`](https://flickity.metafizzy.co/options.html#accessibility).

But to re-enable individual cells to get focus, you'll have to hack Flickity, overwriting a method.

``` js
// external js: flickity.pkgd.js



var flkty = new Flickity('.carousel2', {
  accessibility: false,
});

// overwrite this method
flkty.canPreventDefaultOnPointerDown = function() {
  return false;
};
```

See demo https://codepen.io/desandro/pen/75e676fe0c0e0989b33b7a73561c376d/

**Comment by desandro** [comment]
Hmm, you may have a point. I'll see if preventDefault needs to happen at all across the board.

**Comment by felipearosemena** [comment]
@desandro Awesome, thanks for considering.

**Comment by desandro** [comment]
`preventDefault` is useful for preventing dragging of other stuff, i.e. selected text or an image. I'm actually running into other issues with not having preventDefault, like in #581 and #567
