### ISSUE TITLE
Un-intended dragging images

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/flickity#567]
hi there

recently got a problem with flickity dragging after adding dragThreshold. here you can see the issue https://codepen.io/Mohsen-Khakbiz/pen/xrbOad

the issue will be gone after removing dragThreshold option, or after setting pointer-events to none on images. but that's not the case for me right now and also need the dragThreshold option.

Thanks

**Comment by daziegler** [comment]
+1

**Comment by desandro** [comment]
Thanks for reporting this issue!

As you mention, I think the best solution is to disable `pointer-events` on images.

``` css
.carousel-cell img { pointer-events: none; }
```

**Comment by daziegler** [comment]
Although I had to workaround the links that I still wanted working, that did it. Thanks a lot.

**Comment by desandro** [comment]
Flickity v2.0.10 has been released with this fix. Please update & report back if you still encounter this issue.

**Comment by Mohsen-Khakbiz** [comment]
working perfectly. thanks a lot
