### ISSUE TITLE
The Carousel Items collapse after rotation back from 'Landscape to Portrait' 

### ISSUE THREAD

**Issue by aminebenkeroum** [metafizzy/flickity#568]
![image](https://cloud.githubusercontent.com/assets/6145715/26825351/32e7082e-4aa4-11e7-9422-8cec296a026d.png)
![image](https://cloud.githubusercontent.com/assets/6145715/26825432/85f595d0-4aa4-11e7-812d-f2a8292ef201.png)

Hello the team,

I'm having a problem on Safari, the items collapse (See the pictures) after rotation from portrait to landscape and back. 

Do you have any idea?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
