### ISSUE TITLE
Performance Issues with Firefox in Fullscreen Slideshows with background-image

### ISSUE THREAD

**Issue by SebastianKempf** [metafizzy/flickity#570]
I am running into performance issues with a simple fullscreen slideshow using slides with background-images in Firefox. The slideshow runs fine in every other browser and screen in fullscreen mode. However, in Firefox there are grave performance issues on bigger screens and especially retina displays. The animation becomes very jerky. Now, I know that retina displays are a high end test environment, but I was really wondering why it works great in every other browser while Firefox has such a hard time.
I played around with the css settings and discovered that it might be connected to the fixed position of the slideshow element but could not figure out why or how exactly it is connected.
Since I do not have a codepen account I assembled a reduced test case on our server http://flickity-test.tilgner-kempf.com/ and was hoping somebody could check it and give me a hint how to fix this if possible.

**Test case:** http://codepen.io/desandro/pen/azqbop

**Comment by desandro** [comment]
Thanks for reporting this issue. I see you're using very large images (2500 x 1700px). Firefox may not have as good performance using such large images. I recommend trying half size images (1250 x 850px) and seeing if this issue persists.

**Comment by SebastianKempf** [comment]
Thx for the hint. I drastically reduced the image resolution and optimized the images with jpegmini without any effect. I tested some other slideshows that use transform: translate got similar results. Seems like Firefox is not the best browser for animating stuff … As I said, the strange thing is, that, as long as no parent element is set to display: fixed, the animation is significantly smoother. I have no clue why.

**Comment by desandro** [comment]
Thanks for reporting back!
