### ISSUE TITLE
Vue.js autoPlay + asNavFor with custom ui dots bug

### ISSUE THREAD

**Issue by jmharveys** [metafizzy/flickity#571]
Maybe some of view will found this useful:

https://github.com/drewjbartlett/vue-flickity/issues/15

**Comment by desandro** [comment]
Thanks for reporting this issue. Do you have a **reduced test case** I could look at?   See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by hvalcourtSerdy** [comment]
The problem here : https://github.com/drewjbartlett/vue-flickity/issues/15 is a problem with the Vue Wrapper, not with flickity. You can close this issue.

**Comment by desandro** [comment]
Thanks for following up!
