### ISSUE TITLE
Custom prev/next buttons disabling with only two slides

### ISSUE THREAD

**Issue by runnickrun** [metafizzy/flickity#572]
Hi, 
I'm using custom prev/next buttons with the [code](https://codepen.io/desandro/pres/VLPJqO).
It is working fine, unless you only have two slides, then buttons would remain disabled after being disabled for the first time (the disabled attribute won't be removed). It seems that condition doesn't catch all cases. 

The workaround is (added lines are commented): 

```
// update selected cellButtons
  $gallery.on( 'select.flickity', function() {
    // enable/disable previous/next buttons
    if ( !flkty.cells[ flkty.selectedIndex - 1 ] ) {
      $previousButton.attr( 'disabled', 'disabled' );
      $nextButton.removeAttr('disabled'); // <-- remove disabled from the next
    } else if ( !flkty.cells[ flkty.selectedIndex +1 ] ) {
      $nextButton.attr( 'disabled', 'disabled' );
      $previousButton.removeAttr('disabled'); //<-- remove disabled from the prev
    } else {
      $previousButton.removeAttr('disabled');
      $nextButton.removeAttr('disabled');
    }
  });
```

**Test case:** https://codepen.io/desandro/pres/VLPJqO

**Comment by desandro** [comment]
Thank you for this fix. I've made the change on the pen.
