### ISSUE TITLE
Images do not load when the container div is set to display:block

### ISSUE THREAD

**Issue by davejack1** [metafizzy/flickity#573]
I have a container block, which lists several flickity galleries. I have 3 such containers and two of them are hidden by `display:none`.

In accordance with a specific button click I set the display property as `block` for one specific container.

When I display a hidden container, gallery images do not show up. Gallery itself is there and visible, I can see the dot indicators but the images are not there, therefore the height of the gallery is also small.

If I resize the browser page, images appear promptly.

Any ideas about this problem?

**Edit:**

http://jsfiddle.net/4sfbov2z/33/

This does not demonstrate the above mentioned conditions, but in this simple example I don't see the images when the page is loaded. If I resize the page, images appear. Very similar to my problem.

**Edit2:**

I realised almost all the examples use `<div>` for gallery images. Replaced the `<img>` tag with a div and that solved the display problem for the jsfiddle example. However, my original problem still persists.

**Comment by desandro** [comment]
1. Are you using imagesLoaded option?
2. You may need to initialize Flickity first, then hide the gallery. So when it is revealed it has proper sizing.

**Comment by davejack1** [comment]
`imagesLoaded` didn't make any difference.

Following is the structure of my html file. I am never hiding the main-gallery directly, but hiding the body1 and body2.

```
<div class="body1">
    <div class="main-gallery">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
    </div>

    <div class="main-gallery">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
    </div>
</div>

<div class="body2">
    <div class="main-gallery">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
    </div>

    <div class="main-gallery">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
        <img class="mekanImg gallery-cell" src="IMG/mek1.jpg">
    </div>
</div>
```

Furthermore, I cannot initalize the Flickity with a JS code.
Trying the following script right after `</body>` 

```
<script>
    var elem = document.querySelector('.main-gallery');
    var flkty = new Flickity( elem, {
        // options
        imagesLoaded: true
    });
</script>
```

If I initalize it in HTML, it works fine;

`<div class="main-gallery" data-flickity='{ "imagesLoaded": true }'>` does the trick.

Still having the problem though.

**Comment by desandro** [comment]
Could you put together a **reduced test case** demonstrating this issue? I wasn't able to reproduce it in the previous jsfiddle.

**Comment by davejack1** [comment]
Here is the example. Sorry about the fuzzy css file. I directly extracted this example from my project.

https://dbilgili.github.io/trialWebsite/example/index.html

If you resize the browser window it will switch to Flickity galleries. When you do so galleries appear without any problem. However, if you switch to `tab2`, you will see 3 galleries without images. Now slightly resize the screen and the images will appear abruptly. Now switch back to `tab1` and the previously visible galleries will disappear, I mean not the entire gallery but images inside.

**Comment by desandro** [comment]
I'm seeing this error in the JS console

```
mekan_tabs.js:27 Uncaught TypeError: Cannot read property 'style' of undefined
    at HTMLButtonElement.<anonymous> (mekan_tabs.js:27)
```

**Comment by davejack1** [comment]
This is because I removed one of the tabs' content. Replaced the index.html, now it should be okay. It is not related with Flickity anyways.

**Comment by desandro** [comment]
Thanks for that.

Okay, it looks like you're running into the issue I mentioned above. A Flickity gallery is initialized in a hidden element. You'll need to [trigger `resize` after the gallery's element is shown](https://flickity.metafizzy.co/api.html#resize).

Here is my solution: https://codepen.io/desandro/pen/fecdb3e7fccb133f328c87705d46aa8a

**Comment by davejack1** [comment]
Thank you! Much appreciated.
