### ISSUE TITLE
Adding images to flickity

### ISSUE THREAD

**Issue by o-t-w** [metafizzy/flickity#574]
I am making an ajax request to remove the images in the slider and add new ones but flickity breaks when I do this. What is the best option? I thought of doing .destroy() then initializing all over again, although this doesn't feel like the best way to go about things. My call to .destroy() generated the following error: "Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node."

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by Ollie-w** [comment]
Hi David. Thanks for responding. I will make a reduced test case but is destroying and reinitializing flickity the recommended course of action for AJAXing new images into the carousel?

**Comment by desandro** [comment]
> destroying and reinitializing flickity the recommended course of action for AJAXing new images into the carousel

Nope, I recommend adding cells with [append](https://flickity.metafizzy.co/api.html#append) or [insert](https://flickity.metafizzy.co/api.html#insert)

**Comment by o-t-w** [comment]
Thanks Desandro. I got it working using append and remove. Great product 💯

**Comment by desandro** [comment]
Thanks for following up and for your kind words! Please consider starring this repo and [purchasing a commercial license](https://flickity.metafizzy.co/#commercial-license) to help support development.
