### ISSUE TITLE
Allow carousel elements to use custom classes

### ISSUE THREAD

**Issue by esr360** [metafizzy/flickity#575]
I personally think it would be great to allow custom classes to be used to build the carousel and carousel elements. I would like the markup (and hence, custom CSS) to match the rest of my project.

So, for example, instead of the carousel creating divs with the class `dot` for the dots, I would like to tell the carousel to instead create divs with the class `carousel_bullet`. 

And to achieve this perhaps I would do something like:

```js
var carousel = new app.Flickity(el, {
    dotClass: 'carousel_bullet'
});
```

Thoughts? I think any CSS class name used by Flickity should be customisable.

**Comment by desandro** [comment]
Thank you for this feature request!

> I think any CSS class name used by Flickity should be customisable.

I totally relate. When it comes to my markup, I'm particular. It pains me to use others' markup I see as unfit.

But I don't see this feature as a good for Flickity. Flickity creates a lot of markup:

+ previous/next button
+ previous/next button SVG
+ viewport
+ slider
+ page dots list
+ page dots

Adding a `class` option for each of these elements would add a lot of weighty code for a little benefit. I'm sorry, but I'll have to say no for this one.

I appreciate your feedback all the same. Thanks so much for adding your input on Flickity.

**Comment by esr360** [comment]
Ok, thanks for the swift response. 

Before I call it a day on this feature request, I'll just share my use case. For what it's worth, I'm able to relatively simply get the markup I need with a setup like this:

```json
"components": {
    "wrapper": ".flickity-viewport",
    "pagination": ".flickity-page-dots",
    "bullet": ".dot",
    "navigation": "",
    "navigationItem": ".flickity-prev-next-button",
    "navigationItem-prev": ".flickity-prev-next-button.previous",
    "navigationItem-next": ".flickity-prev-next-button.next"
}
```

```js
for (let [key, value] of Object.entries(options.components)) {
    if (value && value !== "''") {
        value = value.replace(/'/g, '');
        const identifier = `${options.name}_${key}`;
        const component = el.querySelector(value);
        component.classList.add(identifier);
    }
}
```

My goal is to keep my carousel CSS/markup completely agnostic from any third party library I'm using. If I ever decide to move from Flickity to something else (or indeed, move _from_ something else _to_ Flickity, which is the case for me here), it would be great to know I don't have to go and update all my CSS and markup. The presence and existence of Flickity classes are not a problem, I just need my own classes to be present for styles to be applied, lest there be an impact on my carousel CSS naming conventions. I already have my carousel elements marked up and styled, I just need some logic library to make it interactive, without re-defining anything.

You mention there is little benefit, and I fully appreciate I may be alone in this boat, but to me the benefit is huge, and almost a deal maker/breaker for me.

Thanks again for looking at my request, and you're decision to pass on it is fully respected and appreciated.
