### ISSUE TITLE
Disable previous / next buttons if there are no other slides

### ISSUE THREAD

**Issue by Shperung** [metafizzy/flickity#576]
If there are 3 elements in the slider, they are placed in the container. How to not show previous / next buttons, if there are no other slides. If the window size is changed, if the width of the container changes, the buttons should appear.
` const flickityFiltersListSlider = new Flickity('.js--filters-list-slider', {
       contain: true,
       pageDots: false,
       bgLazyLoad: 2,
       initialIndex: 1,
       dragThreshold: 40,
       cellAlign: 'left',
       arrowShape: {
         x0: 10,
         x1: 50, y1: 50,
         x2: 50, y2: 40,
         x3: 20
       }
      });`

![slide](https://user-images.githubusercontent.com/9537441/27328247-24c78e96-55ba-11e7-828d-ca355076c8f0.gif)
example in https://codepen.io/Shperung/pen/bRWbpg.

**Comment by desandro** [comment]
See https://github.com/metafizzy/flickity/issues/289#issuecomment-157488885
