### ISSUE TITLE
Use custom ui dots and make them adjust their numbers depending of the group-cell?

### ISSUE THREAD

**Issue by jmharveys** [metafizzy/flickity#577]
Hi all,

I was wondering if someone have an idea if it’s possible to use custom ui dots and make them adjust their numbers depending of the group-cell show?

I have few breakpoints in my design and the number of dots should changed in function of the group-cell display.

This behaviour work well with the build-in dots, but what should I do with custom ones to archive that?

Thanks for you help!

**Comment by desandro** [comment]
Thanks for submitting this issue.

You can use an undocumented event `resize`:

``` js
// resize event not available with jQuery, you'll have to use vanilla JS
flkty.on( 'resize', function() {
  // do something with slide count...
  console.log( this.slides );
});
```

I'm curious to see how you use this
