### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by nam-co** [metafizzy/flickity#578]
Hi desandro, hope everything is ok, I was wondering if theres a way to loop true so the next arrow goes to the first slide after the end, right now it just disables the next arrow.

Also, is there a easy way to reactivate the autoplay after an arrow click? maybe something like autoplayafterclick: 10 seconds

Thanks for the work, hope you'll consider this ideas

**Comment by desandro** [comment]
Thanks for this issue

>  I was wondering if theres a way to loop true so the next arrow goes to the first slide after the end, right now it just disables the next arrow.

Can you put together a [reduced test case](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues) of what options your are using?

> is there a easy way to reactivate the autoplay after an arrow click?

Sorry, this is no option for this. You'll have to [add code for Player methods](https://flickity.metafizzy.co/api.html#player)

**Comment by nam-co** [comment]
Hi Alejandro, I didn't see the response, this is a basic implementation in codepen.io, the idea for the loop is that when is reached the last cell, it allows next and goes to the first cell
thanks
https://codepen.io/anon/pen/PKpMyj

**Comment by desandro** [comment]
You'll  need to add [your own custom buttons](https://flickity.metafizzy.co/extras.html#custom-navigation-ui) to enable buttons that wrap around. Use the `isWrapped` argument with `previous` and [`next` methods](https://flickity.metafizzy.co/api.html#next)
