### ISSUE TITLE
Static click not working on tablet - tried ipad and android

### ISSUE THREAD

**Issue by o-t-w** [metafizzy/flickity#579]
I used this custom event to make images go fullscreen but its working only on mobile and desktop. 
http://www.duetshop.co.uk/temp/productdetail.asp?productid=STENTOR-STN1400&title=Stentor-Student-I-violin

**Comment by o-t-w** [comment]
I tried pointerDown as well. This is the largest API i have ever seen for such a small component :( *sadface*

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. I appreciate your providing a live URL, but it looks like there's a lot going on on that page. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by o-t-w** [comment]
Before I make a reduced test case, can i confirm that both these events should work on tablet?

**Comment by desandro** [comment]
yes, they should both work on tablets
