### ISSUE TITLE
Tapping page dots of asNavFor gallery doesn't select content gallery

### ISSUE THREAD

**Issue by typogrammer** [metafizzy/flickity#58]
I've forked the main asNavFor pen here:

http://codepen.io/typogrammer/pen/EaEzBx

I would like to have a main gallery and navigation gallery set up to where the main gallery is set with prevNextButtons, and the navigation gallery is set with pageDots underneath. (I would use the navigation as more of a caption area for the main image nav, so the height is variable.)

In example 1, nearly everything works as expected, but the pageDots only change the is-selected class on the navigation gallery and do not move the main gallery. (I've created a second CSS class to show the is-selected class in orange.)

I thought a logical thing would be to tell both the main and nav that they're navigation for each other, and included asNavFor for both in example 2. This works somewhat, as the pageDots now control both galleries, but the prev arrow is always disabled, and the first page dot is always selected.

**Comment by desandro** [comment]
Thanks for taking a look here. The navigation gallery is working as intended. It's a conscious UI behavior that selecting a cell from navigation gallery does not select it from the content gallery. This allows the user to pan around the navigation gallery without it automatically changing the selected gallery. In my testing, this felt more natural than having the galleries completely synced up.

I did make a Flickity extension that does syncing, [flickity-sync](https://github.com/metafizzy/flickity-sync), if that is what you're looking for. Try the demo http://codepen.io/desandro/pen/OPZJmE

Another way to resolve your request is to update the content gallery when the page dots of the navigation gallery are tapped. See http://codepen.io/desandro/pen/QwrWgo . Add this code:

``` js
var utils = window.fizzyUIUtils;

// duck-punch page dots onTap to update navCompanion
var onPageDotsTap = Flickity.PageDots.prototype.onTap;
Flickity.PageDots.prototype.onTap = function( instance, event ) {
  onPageDotsTap.apply( this, arguments );
  // update
  if ( !this.parent.navCompanion ) {
    return;
  }
  var target = event.target;
  // only care about dot clicks
  if ( target.nodeName != 'LI' ) {
    return;
  }
  var index = utils.indexOf( this.dots, target );
  this.parent.navCompanion.select( index );
};
```

**Comment by typogrammer** [comment]
This makes complete sense. I was using the navigation as more of a gallery caption, so of course it wouldn't work exactly as I expected it to. I pulled in flickity-sync and it worked fine.

Thanks for the explanation and help!

**Comment by Und3Rdo9** [comment]
I think I might have similar issue. The main content slider is only updated if I actually click on a cell in the (secondary) navigation slider, but not when I select a cell in the navigation slider using the arrow navigation on that slider. Do I need flickity-sync for this as well? In the asNavFor example in the docs, it seems to sync all the time (on slide click, on arrow click, on page dot click). I'm using flickity.pkgd.js using require as well as the flickity-as-nav-for/as-nav-for using (a second) require.
