### ISSUE TITLE
Odd questions for an experiment...

### ISSUE THREAD

**Issue by richgcook** [metafizzy/flickity#580]
Hi @desandro couple of odd queries that I thought I could ask...

1. Is it possible to fire an event that will cycle through the all slides a few times then land on a random slide? Almost like a slot machine. I know this isn't part of the API but was curious to know if you think it would be possible?
2. Do you reckon it would be possible to control the slider translate position on mousemove?

Both odd questions really but just experimenting... 🤡

**Comment by desandro** [comment]
1. Yes, you can use `setTimeout` to trigger [`select`](https://flickity.metafizzy.co/api.html#select) or [`next`](https://flickity.metafizzy.co/api.html#next).
2. Yes it is possible, but Flickity doesn't provide any easy hooks to do this. You'll have to add your own code, manipulating Flickity's `x` property then triggering `positionSlider`.
