### ISSUE TITLE
Second image gets squished

### ISSUE THREAD

**Issue by stmalk** [metafizzy/flickity#582]
Hello, I'm trying to make a simple carousel that takes 50% of page width. I just put 2 images there that are called through php loop. So First image is displayed full-size as needed, while the second image is super tiny and stick to the left top corner. If I make a container for the carouse 100% width, all images are displayed correctly. 
I just added more images to the gallery and they are not displayed at all. Why all 4 dots are present to switch between them. Only the first one is present and the second super tiny one. 
What can cause it? 

![sample1](https://user-images.githubusercontent.com/14063136/27657417-97fe70d0-5c1a-11e7-83c8-bf7828e4e2e0.jpg)

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
