### ISSUE TITLE
slider does not release mouse on mouseup

### ISSUE THREAD

**Issue by subdigger** [metafizzy/flickity#585]
Here is example taken from official site.

https://codepen.io/desandro/pen/MYQWEe

in chrome:
1) mousedown on any image
2) drag mouse up
3) release mouse button
4) problem here - now slider always cscroll on mouse move

Found that component built on draggable.
actually expected it should not to be bound...

**Comment by cbergen** [comment]
Adding `pointer-events: none` directly to the images helps. It prevents images from getting "grabbed".

https://codepen.io/corny/pen/JJZKPo

**Comment by subdigger** [comment]
thanks. that helps
