### ISSUE TITLE
How call a function on start or end of sliding?

### ISSUE THREAD

**Issue by amerllica** [metafizzy/flickity#586]
I wanna call different functions on start of slide and end of slide. No different between dragging or click on navigation keys, When slide is on start or after movement on start I wanna run function A() and on end of slide I wanna run function B().

I read all docs but didn't find anything.

**Comment by desandro** [comment]
I recommend you use [`dragStart`](https://flickity.metafizzy.co/events.html#dragstart) and [`select`](https://flickity.metafizzy.co/events.html#select) events for the start, and [`settle`](https://flickity.metafizzy.co/events.html#settle) for the end.

Heads up: the `dragStart` and `select` events are not exclusive. They may trigger at the same time, or one after another.

See demo https://codepen.io/desandro/pen/e840106b3d3785f75c492dd8beda7a51

``` js
var $carousel = $('.carousel').flickity();

$carousel.on( 'select.flickity', onSlideStart );
$carousel.on( 'dragStart.flickity', onSlideStart );
$carousel.on( 'settle.flickity', onSlideEnd );

function onSlideStart() {
  console.log('slide start');
}

function onSlideEnd() {
  console.log('slide end');
}

```

**Comment by amerllica** [comment]
thanks, I did it.
