### ISSUE TITLE
removing last index using .remove(el) breaks drag scrolling

### ISSUE THREAD

**Issue by bobmoff** [metafizzy/flickity#588]
This bug is visible on the documentation pages.

https://flickity.metafizzy.co/api.html#remove

Just click on the last item (to remove it) and try to use the mouse to drag scroll to the left. The issue resolves itself if one clicks the left arrow button.

Browser: Chrome Version 59.0.3071.115 
OS: macOS Sierra 10.12.5

**Comment by desandro** [comment]
Thanks for reporting this bug! I'll look into resolving this in a future release.

**Comment by desandro** [comment]
🎉  **[Flickity v2.1.0](https://github.com/metafizzy/flickity/releases/tag/v2.1.0) has been released with  this bug fixed** 🎉

Thanks for sticking with Flickity 🌈🐻
