### ISSUE TITLE
Wrap around snaps back when wrapping slides more than once

### ISSUE THREAD

**Issue by Ceremony64** [metafizzy/flickity#589]
When you have a small slideshow and/or few slides along with wrap around enabled, you may be able to go through all slides in one go multiple times (within a single mouse drag). After you have passed the "starting position" slide for the first time time and moved past that, letting go of the slideshow lets it snap back to correct slide, but unfortunately not the shown slide, but the one in the first wrap.

Based on the testcase below, if you start on A (0) and drag it to the right, till you see B (1) and then A (2) again, moving further right to B (3) and letting go would make it snap back to the first B you have seen (1). Going even further to the very next A (4), would make it snap back to the second A (2). Going even further, it would snap back to either A (2) or B (1), depending on which slide you let go, no matter how often you passed them before. Dragging to the left would change the "snapback" on B to the B (3) after the second wrap, given we start on A again.

**Test case:** https://jsfiddle.net/xj35jf8r/

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm not sure how prevalent this issue is. I may be able to resolve it in a future release.

**Comment by Ceremony64** [comment]
Just so you know, I am currently working on a website, where flickity is used in rather small tiles (think windows metro/windows 8/windows phone) to display various information in few slides, which scroll through automatically. dragging is enabled, which is how I stumbled over this bug. At least its not a page-breaking bug, just some visual oddity :-)

**Comment by desandro** [comment]
🎉  **[Flickity v2.1.0](https://github.com/metafizzy/flickity/releases/tag/v2.1.0) has been released with  this bug fixed** 🎉

Thanks for sticking with Flickity 🌈🐻
