### ISSUE TITLE
Add resize buffer/throttle option

### ISSUE THREAD

**Issue by JoeJHoward** [metafizzy/flickity#590]
When you set the `resize` option to `true` and the window is resized it looks like there is a sort of `event throttling` that limits the carousel repaint to be less frequent than the native window resize `event`. When you have responsive images or even text , this results in a visual "lag" from when the window is resized to when the carousel is repainted.

I assume this is for performance reasons, however I find myself having to set the `resize` option to `false` and then adding my own native `EventListener` on the window which calls `flickity.resize()`. This is additionally disadvantageous as I can't initialize the carousel via `HTML`.

It would be good to add in an additional option - something like `resizeBuffer` that accepts an integer in milliseconds of how frequently to repaint the carousel when the `resize` option to `true`.

See these examples below:

**Resize option on - with lag:** https://codepen.io/anon/pen/GEBrmm
**Manual resize listener - no lag:** https://codepen.io/anon/pen/eRjgGa

**Comment by desandro** [comment]
Thanks for reporting this feature request.

As you have mentioned, this behavior is for performance considerations. In my experience, regular users hardly ever resize their windows, and if so, they aren't concerned with websites being perfectly laid-out during that resizing.

Thanks for putting together the CodePens. This shows that you can get around it with your own code.

I appreciate your effort here, but I'm going to leave this feature request as is. There's a good work around :)
