### ISSUE TITLE
Images are collapsed on MacOS

### ISSUE THREAD

**Issue by szopos** [metafizzy/flickity#594]
Hello there. On MacOS there is a strange behaviour: if the slider contains images, it is collapsed. I fixed this by re-rendering the slider on load:
```
$(window).on('load', function () {
    // debug collapsed height on MacOS
    $slider.flickity('resize');
});
```

**Comment by desandro** [comment]
Have you tried using [imagesLoaded](https://flickity.metafizzy.co/options.html#imagesloaded) ?

[window.load should be used only as a last resort](https://metafizzy.co/blog/window-load-last-resort/).

**Comment by szopos** [comment]
imagesLoaded: true solved the problem. Thank you.
