### ISSUE TITLE
.flickity-viewport height set to 0px in Safari

### ISSUE THREAD

**Issue by michaelpumo** [metafizzy/flickity#597]
When using lazyLoad, the height on the `.flickity-viewport` element is set to 0px in Safari.

I have a test case here:
https://codepen.io/michaelpumo/pen/pwQMGG

You can see in the above (which is a fork from an official example) that the slider is completely collapsed on Safari, but Chrome handles this well.

Due to the dynamic nature of my slider, I'm not able to solve this by setting explicit heights on the slides / cells / viewport. The example above has no explicit height set on the cells.

**Chrome**: 59
**Safari**: 10.1.1

macOS Sierra.

**Comment by desandro** [comment]
Thanks for reporting this issue. As you mention, your example is missing `height` CSS on `.carousel-cell`, which is used for the size of the image. See original demo https://codepen.io/desandro/pen/vOeGzL

So with images unloaded, the cell is `0px`. Then when the image loads, it has `max-height: 100%`, but that's 100% of 0px.

I think you may be able to resolve this by removing `max-height`. See demo https://codepen.io/desandro/pen/8ab4283105b7efc7c440ae9b787b68dc/

**Comment by michaelpumo** [comment]
@desandro Thanks for the very quick response!

You are absolutely correct. Removing the max-height does seem to solve the issue.

Prior to this, I was able to acquire each images aspect ratio and calculate a percentage for the padding-bottom trick. Seems to work well so far, so I'll stick with that.

Perhaps the official example could be updated with this max-height removed for lazyload?

Thanks!

**Comment by desandro** [comment]
Thanks for following up. Different people may use different CSS. I'm okay with leaving `max-height` & letting others decide what works for them 🌈🐻
