### ISSUE TITLE
flickity-prev-next-button doesn't fire event for first element

### ISSUE THREAD

**Issue by nickcom** [metafizzy/flickity#598]
I have an `asNavFor ` consisting of a flickity-main and flilckity-nav. The nav has `prevNextButtons` enabled. I have a click event defined 

> $('.button--previous').on( 'click', function() {
>   $carousel.flickity('previous');
> });

Because flickity automatically sets the `prevNextButtons` to disabled when moving to the first/last nav element this click event is not fired on the first or last nav elements. Thus when moving from the second nav element to the first using `prevNextButtons` the flickity-main is not updated.

How to solve for this?

![qlty5d](https://user-images.githubusercontent.com/500766/28077975-df252f96-6695-11e7-9fed-3675fd467d76.gif)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by nickcom** [comment]
sorry my GIF wasn't clear.

I have navigation carousel below the main carousel. The two carousels are linked using as asNavFor.  

According to the documentation I notice the default behaviour of the arrow buttons on the navigation carousel are to slide the navigation carousel left or right - useful for when the width/number of thumbnails exceeds the container width.

What I want to do is that when a user clicks these navigation arrows it will select the prev/next image. As you can see in the GIF this is working fine, but not for the first or last thumbnails. I beleive this is due to the 'disable' attribute being added to these buttons.

I have made the following codepen. Unfortunately for whatever reason I couldn't get the main-carousel to update based on arrow clicks but I already have that working outside of codepen.

You can see in the codepen that clicking the arrow buttons only fires events when the first or last thumbnails is not involved. How to make the arrow event fire for each click - or in other words how to stop the 'disable' attribute being placed on this button?

https://codepen.io/anon/pen/xrvMWz?editors=0010

**Comment by desandro** [comment]
Thanks for the demo.

Sounds there is a bit of confusion in how the previous/next arrows work for a navigation carousel. The previous/next buttons allow a user to navigate cells in that carousel. So you could swipe to the far left or far right, and it wouldn't change the main carousel. The main carousel would only change when you clicked on a navigation cell.

To enable your desired behavior, you'll have to implement your own [custom buttons](https://flickity.metafizzy.co/extras.html#custom-navigation-ui). See demo https://codepen.io/desandro/pen/291975a383c8bce86d733dbcb2435a07

``` js
// external js: flickity.pkgd.js

var $mainCarousel = $('.carousel-main').flickity({
  prevNextButtons: false,
});

var $navCarousel = $('.carousel-nav').flickity({
  asNavFor: '.carousel-main',
  cellSelector: '.carousel-cell',
  contain: true,
  pageDots: false,
  prevNextButtons: false,
});

$('.prev-button').on( 'click', function() {
  $mainCarousel.flickity('previous');
});

$('.next-button').on( 'click', function() {
  $mainCarousel.flickity('next');
});
```

**Comment by nickcom** [comment]
thanks. This solution works for my needs.
