### ISSUE TITLE
Returning to autoPlay makes crazy scrolling

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#6]
+ Have a flickity with `autoPlay: true`
+ Go to a different browser tab for while
+ Return to the flickity browser tab

Expected result: flickity is in previous position

Actual result: flickity scrolls a crazy distance

**Comment by kukac7** [comment]
unfortunately, the problem still exists. :sob: 
(chrome latest)

**Comment by loweoj** [comment]
This is still happening in the latest version.
