### ISSUE TITLE
Don't work with FLEX elements

### ISSUE THREAD

**Issue by guminov** [metafizzy/flickity#60]
http://codepen.io/Guminov/pen/ravLMB

**Comment by desandro** [comment]
Flickity will not work with flex-box CSS, as you have set in your CodePen. This is to be expected, as Flickity lays out cell elements outside of the gallery element. Flex-box layouts are designed to work with cell elements contained with the container element. The two layout patterns are incompatible.

However, Flickity will work with flex-box layout within cell elements. See example http://codepen.io/desandro/pen/MYGvYy

**Comment by desandro** [comment]
Also see this example which uses flexible box layout to center images in an image gallery http://codepen.io/desandro/pen/xbjzeK
