### ISSUE TITLE
Need help in fixing blank cells

### ISSUE THREAD

**Issue by jaszblack** [metafizzy/flickity#600]
I have to apologise that, I'm not a developer. And hence wont know most of the tech language. I have bought a theme which uses flickity. One of the pages uses a slider which uses 3 divs.And i'm facing 2 problems on this.  

My 1st div image is appearing as the second image on html, 2nd as third, and 3rd as the first.

Also when i slide 2 second image using nav dots, the first section is going blank.

Can someone please help me to sort this? Thanks for any help in advance

![gif](https://user-images.githubusercontent.com/30124838/28130773-85d2a76e-6755-11e7-8f2a-1ae5945f8fec.gif)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
