### ISSUE TITLE
Build in Typescript and no dependency on jQuery - pretty please :D

### ISSUE THREAD

**Issue by Montago** [metafizzy/flickity#601]
Any chance in hell that you will upgrade all code to TypeScript and remove the dependency on jQuery ?

is this a long shot ?

:)

**Comment by desandro** [comment]
> remove the dependency on jQuery

Flickity is already written in vanilla JS. Its jQuery plugin support is optional. Try out any of the vanilla JS CodePens [in the docs](https://flickityjs.com)

> Any chance in hell that you will upgrade all code to TypeScript

Sorry, no chance. TypeScript is not my thing and I feel it's at odds with a core tenet of JavaScript: dynamic typing.

**Comment by Montago** [comment]
hi - thanks..
The link for docs didn't work ?

But great :)
maybe if there's not too much code i could convert it myself.

**Comment by desandro** [comment]
link fixed
