### ISSUE TITLE
Insert a cell after the current "is-selected" cell?

### ISSUE THREAD

**Issue by sujan-s** [metafizzy/flickity#609]
Hi,

I see there's an `insert`, `append` and `prepend` option, but how can I `insert` after the current cell? I'm a JS noob, so please bear with me if this is a silly question.

FAN-TAS-TIC plugins, by the way. All of them.

**Comment by yaodingyd** [comment]
@sujan-s You can get current `selectedIndex` from Flickity instance then use `insert`.

```javascript
// init Flickity with jQuery
var $carousel = $('.carousel').flickity();
// get instance
var flkty = $carousel.data('flickity');
// access selectedIndex
var selected = flkty.selectedIndex;
// insert cell
var $cellElems = $('<div class="carousel-cell">...</div>');
$carousel.flickity( 'insert', $cellElems, selected );
```

**Comment by sujan-s** [comment]
@yaodingyd Yes, this works! Thanks! :)

**Comment by desandro** [comment]
@yaodingyd Thank you for your suggested code!

You could also try adding a custom method

``` js
Flickity.prototype.insertAfterSelected = function( elems ) {
  this.insert( elems, this.selectedIndex );
};

$carousel.flickity( 'insertAfterSelected', $cellElems );
```
