### ISSUE TITLE
Clicking elements in links on mobile broken

### ISSUE THREAD

**Issue by guminov** [metafizzy/flickity#61]
How to do elegantly hrefs to be opened from child elements ( ex. ul li a href="url")

**Comment by desandro** [comment]
Flickity already has logic built in to handle clicking on links. Similar to the  `staticClick` event, it will allow clicks when the gallery hasn't moved. It will disable clicks when the gallery has moved. You do not need to add any additional `logic`. See http://codepen.io/desandro/pen/KwRMXL

**Comment by guminov** [comment]
its work on desktop version, but not on mobile, for ex. on iphone 5, any browser

**Comment by desandro** [comment]
Working just fine for me, iPhone 5s, iOS 8.1.3. Can you produce a **reduced test case** demonstrating the bug? You could fork the CodePen linked to above. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

There is a small buggy behavior where you can tap down, hold, then move a little bit within the linked area. This will trigger a click. I'm okay allowing this behavior. Trying to resolve this behavioral edge case would conflict with the current behavior.

**Comment by guminov** [comment]
http://codepen.io/Guminov/pen/qEYqLE
image link don't work, text link - ok
iPhone 5c, iOS 8.1.3

**Comment by desandro** [comment]
Ah! Thank you for that. This is indeed a bug. Currently Flickity will not allow child elements of links to be clicked on mobile. I'll resolve this in an upcoming fix

**Comment by desandro** [comment]
Fixed with `v1.0.0`. Closing as resolved.
