### ISSUE TITLE
Bug: change style when Flickity carousel move

### ISSUE THREAD

**Issue by mahyar33** [metafizzy/flickity#611]
I've used Flickity plugin for carousel slider in my site
my address: http://niniplus.com/new/
when I zoom by developer tools (in picture number 1)
then i scroll horizontally carousel (number 2)
box shadow of other carousel sliders Are affected (number 3) 
picture:
![sdfsdf](https://user-images.githubusercontent.com/11396253/28865049-be61921e-7783-11e7-8cbd-f7b4ac86f4af.jpg)
what can i do to solve it?

**Comment by desandro** [comment]
Thanks for reporting this issue. The rendering of box shadow on browser zoom is unrelated to Flickity. This issue would still occur if Flickity were disabled. Sorry I won't be able to help here.
