### ISSUE TITLE
autoPlay with wrapAround on false keeps scrolling

### ISSUE THREAD

**Issue by JimmyAppelt** [metafizzy/flickity#612]
When I set 
```json
{ "wrapAround": false , "autoPlay": true}
```
The sliders keep scrolling, I would have expected it to stop at the last slide. Perhaps I'm overlooking something? Or is there a way around this behavior.

**Test case:** https://codepen.io/JimAppelt/pen/oeLKbW

**Comment by yaodingyd** [comment]
@JimmyAppelt  It is discussed in this issue #584.
I also created a codepen https://codepen.io/earthmount/pen/RZGbwv

**Comment by desandro** [comment]
@yaodingyd Thank you for your suggested code!

I recommend checking [`selectedIndex`](https://flickity.metafizzy.co/api.html#selectedindex) matches [`slides.length`](https://flickity.metafizzy.co/api.html#slides).

See demo https://codepen.io/desandro/pen/mMOXKg
