### ISSUE TITLE
Having problems issuing multiple sliders

### ISSUE THREAD

**Issue by enjoikumar** [metafizzy/flickity#615]
I already have one slider in place
html:
<div class="main-carousel">
		<img class="carousel-cell" src="assets/highwaist_black_front_2_1024x1024.jpg">
		<img class="carousel-cell" src="assets/highwaist_black_front_3_1024x1024.jpg">
		<img class="carousel-cell" src="assets/highwaist_black_front_5_1024x1024.jpg">
		<img class="carousel-cell" src="assets/highwaist_black_front_4_1024x1024.jpg">
		<img class="carousel-cell" src="assets/highwaist_black_side_1024x1024.jpg">
	</div>

js: 
$('.main-carousel').flickity({
	  // options
	  cellAlign: 'left',
	  contain: true,
	  prevNextButtons: false 
	});

I'm trying to get another slider, but it's not showing up for some reason. any help with multiple slider issues. Thank you

**Test case:** http://codepen.io/desandro/pen/azqbop

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
