### ISSUE TITLE
Bug: change color when Flickity carousel move

### ISSUE THREAD

**Issue by mahyar33** [metafizzy/flickity#616]
hi
in my website:
http://niniplus.com/post/850-Air-pollution-and-an-increased-risk-of-diabetes
when I scroll horizontally carousel 
color change light to dark
i've figure out that this issue is for .flickity-slider class because when i scroll transform: translateX() change to translate3d()
![sdfgfh](https://user-images.githubusercontent.com/11396253/29354996-993bf086-8284-11e7-9894-30bde3b0f50c.JPG)
![sadasdasd](https://user-images.githubusercontent.com/11396253/29354997-9949f62c-8284-11e7-9278-d125f129b251.JPG)
you can see color change on this image
now i have to change color to blue for solve it

**Comment by desandro** [comment]
Thanks for reporting this issue. While dragging, Flickity uses 3D transforms to activate hardware acceleration. After dragging, Flickity uses 2D transforms for better text rendering. So the text may appear a little blurry while dragging. But after dragging, it should appear clear.

**Comment by mahyar33** [comment]
can you fix it please?

**Comment by desandro** [comment]
My decision is to keep Flickity's rendering logic as is. Adding a change would require additional code and complexity, and I don't feel this issue warrants that. I appreciate you reporting this issue, but I'll have to pass on this one.

**Comment by yellow1912** [comment]
I know this is old and marked as wontfix, but is there a way to get around this issue? It's really buggy to see the colored text on the slide keeps changing.
