### ISSUE TITLE
Flickity in angular2 refresh

### ISSUE THREAD

**Issue by sri1722** [metafizzy/flickity#617]
**Test case:** http://codepen.io/desandro/pen/azqbop

Hi there I am using flickity in angular2 application and I'm binding the flickity cell from http service call and I need to refresh the service when I'm refreshing the service flickity is disabled and it is not working at all.
And I tried destroy the flickity when service refresh but still the issue persists.    

Thank you.

**Comment by yaodingyd** [comment]
@sri1722 you need to fork the original codepen to show your test case.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
