### ISSUE TITLE
Lazy Load and Wrap Around issue

### ISSUE THREAD

**Issue by spectralshadow514** [metafizzy/flickity#618]
With Lazy Load and Wrap Around active, there's an odd visual glitch when scrolling backwards through the gallery the first time around:
https://codepen.io/anon/pen/VzyxWM
It works fine when everything is loaded, but prior to that the animation is.. choppy.

**Comment by desandro** [comment]
Duplicate of #231

**Comment by desandro** [comment]
Thanks for reporting this issue. We already have an issue opened for this bug.
