### ISSUE TITLE
watchCSS issue with length (slide count) once destroyed

### ISSUE THREAD

**Issue by richgcook** [metafizzy/flickity#620]
Hi @desandro I'm using a fairly simple setup with watchCSS (which will disable the slider at a certain breakpoint as detailed here: ) but I've ran into a little issue. I'm getting an error `Cannot read property 'length' of undefined` for the `slideCount = flkty.slides.length`  variable assignment when I load the page after the certain breakpoint as I guess the data `.data('flickity')` doesn't exist as watchCSS is turning it off. 

Any thoughts?

```
if ($('.image__group--container').length > 0) {

	var options = {
	    wrapAround: true,
	    prevNextButtons: false,
	    setGallerySize: false,
	    pageDots: false,
	    watchCSS: true,
	    draggable: false
	};

	$('.image__group--container .image__group--slider').flickity(options);

	$('.image__group--container').each(function (i, container) {

	    var $container = $(container),
	    	$slider = $container.find('.image__group--slider'),
			$slide = $slider.find('.image__group'),
	    	flkty = $slider.data('flickity'),
	    	selectedIndex = flkty.selectedIndex,
	    	slideCount = flkty.slides.length,
			$dots = $container.find('.slider__dots');

		for (i = 0; i < slideCount; i++) {
			$dots.append('<span></span>');
			}
			var $dot = $dots.find('span');

		function onSelect() {
			$dot.filter('.is--active').removeClass('is--active');
			$dot.eq(flkty.selectedIndex).addClass('is--active');
		}
		onSelect();

		$slider.on('select.flickity', onSelect);

		$dots.on('click', 'span', function() {
			var index = $(this).index();
			$slider.flickity('select', index);
		});

	});
}
```

**Comment by yaodingyd** [comment]
Can you check if `flkty` is not `undefined` before any usage?

**Comment by richgcook** [comment]
Well it still exists... even when it's not active  `.data('flickity')` is still returning data as it still exists in the DOM.

**Comment by richgcook** [comment]
I actually managed to use `if (flkty.slides != undefined)` which seems to work but then when you size back up it's obviously not refiring (and not generating the `$dots`

**Comment by yaodingyd** [comment]
Maybe we need a new feature of `watchCSS` event?

**Comment by desandro** [comment]
Thanks for reporting this issue.

To check if `watchCSS` has activate a Flickity instance, you can check for the `isActive` property

``` js
flkty.isActive
// => true if active, false if not active
```

There's also an internal events for `activate` and `deactivate`. Because their internal, you'll have to use vanilla JS event binding

``` js
flkty.on( 'activate', function() {
  // flickity instance has been activated
});

flkty.on( 'deactivate', function() {
  // flickity instance has been activated
});
```

These properties and events have not been documented because I do not want to over-complicate the documentation.

Looking at your code, it appears you're dynamically creating another set of paging dots. Can you explain what you're trying to achieve? We may be able to remove all this code if we can find another solution
