### ISSUE TITLE
disable class has problem

### ISSUE THREAD

**Issue by mahyar33** [metafizzy/flickity#623]
hi
please watch this video
[Video_2017-08-26_113011.zip](https://github.com/metafizzy/flickity/files/1253457/Video_2017-08-26_113011.zip)
in my website:
https://niniplus.com/
when i drag the item, .disable class on flickity-prev-next-button works fine but when i click it doesn't work properly
Please check this out

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by mahyar33** [comment]
here you are:
https://codepen.io/anon/pen/LjqXpq
you can see that pre & next button have problem

**Comment by desandro** [comment]
See https://github.com/metafizzy/flickity/issues/289#issuecomment-157488885
