### ISSUE TITLE
How to Build without ImagesLoaded

### ISSUE THREAD

**Issue by maimairel** [metafizzy/flickity#626]
Hi, 

I'm not really experienced with build tools, is there any guide how you can build flickity without the images loaded module?

Thanks :)

**Comment by desandro** [comment]
Sure thing!

1. Clone or download the Flickity repo
2. Open [gulpfile.js and remove line 72](https://github.com/metafizzy/flickity/blob/v2.0.9/gulpfile.js#L72)
3. Run `bower install`. Run `npm install`. Then run `gulp`

You should get a `packery.pkgd.js` and `packery.pkgd.min.js` file without the flickity-imagesloaded package or imagesLoaded.

**Comment by maimairel** [comment]
Done thanks!
