### ISSUE TITLE
Images does not appear

### ISSUE THREAD

**Issue by salasmx** [metafizzy/flickity#627]
Images does not appear but when resize the browser then appears.

Problem persist on Chrome for Mac, Safari for Mac and some times on Firefox for Mac.

Any idea?

Here is the link http://bit.ly/2eGcdrf

Thank you.

**Comment by desandro** [comment]
Use [imagesLoaded](https://flickity.metafizzy.co/options.html#imagesloaded) or [lazyLoad](https://flickity.metafizzy.co/options.html#lazyload)

**Comment by salasmx** [comment]
That does not solve the problem but thank you.
