### ISSUE TITLE
place dots in an independent div

### ISSUE THREAD

**Issue by s-norman** [metafizzy/flickity#628]
Would be nice if dots could be placed in a div that could then be placed on a page like a header that would not be impacted by scrolling the content. 

My implementation is on a mobile web app where the content needs to be vertically scrolled, so dots on top work best because dots are visible when content is loaded. But when user scrolls vertically, dots scroll up and out of view.

**Comment by desandro** [comment]
Thanks for reporting this issue. You can create your own custom dot UI with the Flickity API. See [Custom navigation UI](https://flickity.metafizzy.co/extras.html#custom-navigation-ui)
