### ISSUE TITLE
How to detect an element which is on the edge and visible in the viewport.

### ISSUE THREAD

**Issue by segmentationfaulter** [metafizzy/flickity#629]
I want to apply some styling to elements which are on the edge of the visible carousel, how can I detect it?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
