### ISSUE TITLE
Height 100%

### ISSUE THREAD

**Issue by notflip** [metafizzy/flickity#63]
Does anyone have experience using flickity as a full width, full height page slider. 
I'm trying the following

    .gallery-cell {
	    width: 100%;
	    height: 100%;
    }

And this is my JS

    	$('#gallery').flickity({
		cellSelector: '.gallery-cell',
		accessibility: false,
		percentPosition: true
	});

But with no result! Thank you

**Comment by notflip** [comment]
Edit: I'm sorry, was confused. This can be achieved by 

    #gallery {
	    height: 100%;
    }
    .gallery-cell {
	    width: 100%;
    }

( why can't u delete things on github )

**Comment by desandro** [comment]
Have you looked at using [`setGallerySize`](http://flickity.metafizzy.co/options.html#setgallerysize)?  Try playing with this example: http://codepen.io/desandro/pen/dPmKyx

**Comment by robrecord** [comment]
Forgive me if I misunderstand, but the example you link to is about something different - height as a percentage of width. I still cannot achieve full height with Flickity.

**Comment by desandro** [comment]
Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by tdturn2** [comment]
Are there any examples of 100% width and height that you are able to refer? I've tried setting the height of .gallery-cell to 100% to no avail. <a href="http://dev.worldturners.org/flickity/">My test page</a> vs <a href="http://mightyslider.com/#intro">what I'm shooting for</a>

**Comment by desandro** [comment]
I put together this demo with 100% width and 100% height carousel: http://codepen.io/desandro/pen/VLrReY

+ set [`setGallerySize: false`](http://flickity.metafizzy.co/options.html#setgallerysize)
+ `.gallery { height: 100%; }`
+ `.gallery-cell { height: 100%; }`
+ `.flickity-page-dots { bottom: 10px; }`
