### ISSUE TITLE
Vertical slider for thumbnails effecting main horizontally slider

### ISSUE THREAD

**Issue by functionandform** [metafizzy/flickity#630]
I would like to be able to have slides displayed vertically. I know an issue was posted previously because it was declared as a bad UX choice or 'anti-pattern'.  
But my issue presents a valid use case for this experience. I have a primary product carousel displayed horizontally. But also a second carousel to the left of this displaying small thumbnails vertically which can be clicked onto display in the primary carousel.
How would I go about achieving this?

cheers

**Comment by desandro** [comment]
Thanks for opening this issue. If you do want a vertical thumbnail list, [I did make this demo with the Flickity API](https://codepen.io/desandro/pen/dMjbjR). But for as a main feature, Flickity will not support vertical dragging, see #36
