### ISSUE TITLE
Fire event when user attempts to continue on last slide

### ISSUE THREAD

**Issue by richgcook** [metafizzy/flickity#631]
I am wanting to achieve something so if the user clicks, and it's the slide slide (`wrapAround` is disabled) it should trigger an event.

```
$slider.on('select.flickity', function() {
    if (flkty.selectedIndex == flkty.cells.length - 1) {
        // DO SOMETHING
    }
});
```
This fires when the user reaches the last slide, but I need to fire an event when the user clicks and it's the last slide. What do you think, is this possible?

**Comment by yaodingyd** [comment]
You can use `settle` instead of `select`. [Example](https://codepen.io/earthmount/pen/RLNaaO)

**Comment by desandro** [comment]
@yaodingyd has it 😁

**Comment by richgcook** [comment]
Yeah this could work...

```
$slider.on('settle.flickity', function() {
	if (flkty.selectedIndex == flkty.cells.length - 1) {
		$container.find('.slider__navigation.next').on('click', function(e) {
			e.preventDefault();
	                console.log('works');
	    });
	}
});
```

Thanks all!
