### ISSUE TITLE
Slider loads image after image while resizing

### ISSUE THREAD

**Issue by skenic2003** [metafizzy/flickity#632]
Hey!

I'm using flickity on a client's website and it's working as expected except for one thing.
I'm not too sure how to describe the behavior but to say:

When the page loads the images stack up next to each other before reaching their correct size.
This makes the slider look broken for the first second or so, which my client really hates.

Is there any way to fix this?
I've already tried using loadedImages: yes and also hiding the gallery until flickity is loaded.

I've attached a screenshot so you know what I mean.

The slider is set to wrap around, if that's important somehow.

Thanks for your help!
![bug_flickity](https://user-images.githubusercontent.com/2659372/30385713-4e1c332e-98a8-11e7-9f34-0607e82c64af.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by skenic2003** [comment]
I've copied my code exactly and can't for the life of me figure out why the CodePen loads just fine...
Here's the CodePen: https://codepen.io/anon/pen/JrdyoY

When you open the website http://visions2you.de/home how does it look to you?

**Comment by desandro** [comment]
Thanks for taking a shot at this. Sorry, I'm not able to reproduce the issue.
