### ISSUE TITLE
Initial `select` event, $element.data( 'flickity' ); returns undefined

### ISSUE THREAD

**Issue by maimairel** [metafizzy/flickity#633]
As the title says, how come at the first `select` event, the flickity instance is not available from `$( event.target ).data( 'flickity' );`?

**Comment by desandro** [comment]
Thanks for reporting this issue. I wasn't able to reproduce this issue. Could you [fork this demo](https://codepen.io/desandro/pen/Qqwvmd/) to show the problem?

**Comment by maimairel** [comment]
Maybe because I'm listening to the event before flickity is initialized? But if I do it after, then the initial `select` event would be done already before the event is listened to.

https://codepen.io/anon/pen/mByojW

**Comment by desandro** [comment]
Ah, thanks for that. Yes, there's no way to get the Flickity instance via jQuery in the initialization `select` event, because the element does not get its instance until after its been initialized.  From jquery-bridget:

``` js
instance = new PluginClass( elem, options ); // initialize
$.data( elem, namespace, instance ); // add instance via data
```

Can you explain what you're trying to achieve with this technique? There may be another solution.

**Comment by maimairel** [comment]
I'm creating a kenburns effect slider with Flickity, it all works but with a hacky code caused by the missing flickity instance on the first select event.

This is part of the code:

```javascript
$flkty.on( 'select.flickity', function( event ) {

	var flkty = $( event.currentTarget ).data( 'flickity' );
	var currentCell, nextCell;
	var currentIndex = 0, nextIndex = 1;

	if( flkty ) {

		if( flkty.player ) {
			flkty.player.visibilityChange = $.noop;
			flkty.player.visibilityPlay = $.noop;
		}

		currentIndex = flkty.selectedIndex;
		currentCell  = $( flkty.selectedElement );

		nextIndex = ( currentIndex + 1 ) % flkty.cells.length;
		nextCell  = $( flkty.cells[ nextIndex ].element );

	} else {

		currentCell = $( '.flkty__cell', event.target ).first();
		nextCell = currentCell.next();
	}

	var x = Math.random() * 20 + 5;
	var y = Math.random() * 50 + 25;

	var xn = Math.random() * 20 + 75;
	var yn = Math.random() * 50 + 25;

	if( Math.random() * 10 > 5 ) {
		x += 70;
		xn -= 70;
	}

	if( currentIndex % 2 == 0 ) {

		currentCell.css({
			transformOrigin: x + '% ' + y + '%', 
			transform: 'scale3d(1.25, 1.25, 1.25)'
		});

		nextCell.css({
			transitionDuration: '0s', 
			transformOrigin: xn + '% ' + yn + '%', 
			transform: 'scale3d(1.25, 1.25, 1.25)'
		});

	} else {

		currentCell.add( nextCell ).css({
			transitionDuration: '', 
			transform: ''
		});
	}
});
```

**Comment by maimairel** [comment]
Perhaps adding to _createMethods then listening to the `select` event is the best method?

**Comment by desandro** [comment]
Thanks for that. If you want to set up this effect on initialization, I would move the behavior into a separate function and call that after initializing Flickity

``` js
// init Flickity
$flkty.flickity({
 // options...
});

kenBurnsCells( $flkty );

$flkty.on( 'select.flickity', function( event ) {
  var $target = $( event.target );
  kenBurnsCells( $target );
}

function kenBurnsCells( $carousel ) {
  var flkty = $carousel.data('flickity');
  var currentCell, nextCell;
  var currentIndex = 0, nextIndex = 1;
  ...
}
```

**Comment by maimairel** [comment]
I managed to get this working by adding to `_createMethods`. Thanks!
