### ISSUE TITLE
Latest release caused error "invalid byte sequence in UTF-8 (ArgumentError)" on Elastic Beanstalk

### ISSUE THREAD

**Issue by camwes** [metafizzy/flickity#635]
I don't really have a test case for this and have very little information more than the title. This morning I attempted to deploy a new version of my app to Elastic Beanstalk and got the above error. I quickly realized since it was in the EB npm.sh file it was a dependency. I found the most recently updated dep, changed the version to a previous version, redeployed and my problem was fixed.

So basically I don't know what the problem is, but you have one with the latest version.

**Comment by desandro** [comment]
Thanks for reporting this issue. I'll keep it open in case anyone else runs into this.

**Comment by AugustBrenner** [comment]
I'm running into this, I haven't been able to deploy code for days.
