### ISSUE TITLE
Anyway to combine Flickity and Infinitescroll

### ISSUE THREAD

**Issue by maimairel** [metafizzy/flickity#636]
I need some guide here :)

**Comment by desandro** [comment]
You'll need to initialize Flickity after new content is appended. You can use Infinite Scroll's [`append` method](https://infinite-scroll.com/events.html#append) to do so.

``` js
// with jQuery
$container.on( 'append.infiniteScroll', function( event, response, path, items ) {
  $( items ).find('.carousel').flickity({
     // Flickity options
  });
});
```

``` js
// with vanilla JS
infScroll.on( 'append', function( response, path, items ) {
  for ( var i=0; i < items.length; i++ ) {
    var item = items[i];
    var carousels = item.querySelectorAll('.carousel');
    for ( var j=0; j < carousels.length; j++ ) {
      var carousel = carousels[j];
      new Flickity( carousel, {
        // Flickity options
      })
    }
  }
});
```

**Comment by maimairel** [comment]
No I mean, loading Flickity cells using Infinitescroll :)
Maybe by using the `scroll` event after it reaches a certain percentage?

**Comment by banago** [comment]
@maimairel it's not hard to implement infinite scroll in a carousel, but unfortunately it has a bug at this moment. Check this issue: #649.

I'm working on a solution and I'll post it there.
