### ISSUE TITLE
flickity-viewport can't edit

### ISSUE THREAD

**Issue by ginxx009** [metafizzy/flickity#637]
**Test case:** https://codepen.io/jamy/pen/gbdWGJ?q=testimonial&limit=all&type=type-pens

I'm using this kind of pen and i'm having trouble of editing the flickity-viewport.

I'm trying to make the height of the viewport to be 

it's on my style.css
.flickity-viewport{
 height:678px;
}

on my flickity.min.css
.flickity-viewport{
   overflow: hidden;
    position: relative;
    height: 635px
}

but when im trying to edit on my style.css it's not working

![image](https://user-images.githubusercontent.com/28310693/30573824-8969075c-9d28-11e7-85b1-709157a9b133.png)

I don't know where that style="height:1228px;" came from. Kindly help me please

**Comment by kukac7** [comment]
why do you want to give the `flickity-viewport` a height?

**Comment by desandro** [comment]
If you're going to set the gallery size with your own code, I recommend setting it on a the `.main-gallery` element, rather than `.flickity-viewport`. See [setGallerySize option](https://flickity.metafizzy.co/options.html#setgallerysize)
