### ISSUE TITLE
Remove first x cells by jQuery

### ISSUE THREAD

**Issue by JonasVorwerk** [metafizzy/flickity#640]
Hey there,

I'm trying to delete the first x posts after an event but struggling with the syntax.
Trying to make a slideshow that loads data every x time and erases the previous slides. 
Some help would be appreciated ;) 

	function loadPosts() {
		$.ajax({
			url: php_data.url + "/wp-admin/admin-ajax.php",
			type: 'POST',
			data: 'action=loadPosts',
			success: function(html) {
				var $newPostItems = $(html);
				$carousel.flickity( 'append', $newPostItems );
				
				//remove the x first items
				$carousel.flickity('remove', flkty.cells[0]);
				
				//show cell array
				console.log(flkty.cells);
				
			},
			error: function(xhr, ajaxOptions, thrownError) {
				console.log('error');
			}
		});
		return false;
	}

**Comment by crapthings** [comment]
have u tried reloadCells ?

https://flickity.metafizzy.co/api.html#reloadcells

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by JonasVorwerk** [comment]
Your code works awesome as always, I just don’t know how to remove the first 3 cells using jQuery. 

Something like: 	//remove the 3 first items
				$carousel.flickity('remove', 3);

What should I add instead of the 3? 

Thanks in advance,

Jonas

**Comment by desandro** [comment]
You can pass in an [array of elements to remove](https://flickity.metafizzy.co/api.html#remove), so you could select the first 3 cells with [jQuery slice()](https://api.jquery.com/slice/)

``` js
var $cells = $carousel.find('.carousel-cell');
// remove first 3 cells
$carousel.flickity( 'remove', $cells.slice( 0, 2 );
```

**Comment by JonasVorwerk** [comment]
Perfect, thanks!
