### ISSUE TITLE
Multiple instances on a page trigger window scroll events when clicking between them

### ISSUE THREAD

**Issue by swixpop** [metafizzy/flickity#641]
See codepen below. Open the console in devtools. Scroll down so both sliders are visible. Click in one slider, then in the other. Each time, a window scroll event is logged.

**Test case:** https://codepen.io/anon/pen/XegKLG

**Comment by desandro** [comment]
This behavior is intended. Similar to https://github.com/metafizzy/flickity/issues/76#issuecomment-77430660

>  This behavior is actually a feature of keyboard accessibility. By clicking/tapping on a gallery, it adds focus to its element. 

Flickity v1.1.1 add behavior to capture that scroll and reset the window position so there would be no change in scroll position. The scroll event would like still trigger.
