### ISSUE TITLE
Lazyload not working with 3 slides or fewer

### ISSUE THREAD

**Issue by nmklong** [metafizzy/flickity#642]
Hi, i have multiple carousels on one page, everything works fine, except for the lazyload only works with one slider, it automatically loads everything else, so it only lazy loads on the first slider, the rest of the sliders the images are already preloaded without lazyloading, i also see class 'flickity-lazyloaded' added to the loaded images.

EDIT: See my below comment for further details

**Comment by nmklong** [comment]
After testing further, i think it's not because of multiple sliders, the problem is that some sliders have only 3 items and it won't lazyload, it will preload everything. Some other sliders have 4 or more items and it will lazyload.

My settings is set to `lazyLoad: 1`

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by nmklong** [comment]
Hi @desandro 
Basically my currently layout is having 2 images in 1 div `carousel-cell` using `lazyLoad: 1`, checkout the codepen:
https://codepen.io/anon/pen/veprWX

I don't want to modify the existing layout so i'm not using `groupCells`

If you uncomment the 4th block, lazyload will work, but if you leave it commented, lazyload wont' work and will just load all of the images on first load.

My network tab when having 4 blocks of `carousel-cell` (loading only the first 4)
![screen shot 2017-10-05 at 12 11 55](https://user-images.githubusercontent.com/1017308/31247874-ccc6b436-a9c6-11e7-9451-c13c86d01e9e.png)

And this is when having 3 blocks of `carousel-cell` (loading all 6 images)
![screen shot 2017-10-05 at 12 11 25](https://user-images.githubusercontent.com/1017308/31247842-b7128caa-a9c6-11e7-8ca1-68fc7d3524b1.png)

**Comment by desandro** [comment]
Thanks for that. I believe the issue is that the cells have no default width. So when Flickity is first initialized with unloaded images, the cells have width of 0. Then, when images are loaded, `select` is triggered, and it may select the 2nd or 3rd cell because of how the math works.

One way to resolve this is to provide a default width

``` css
.carousel-cell {
  min-width: 400px;
}
```

See demo https://codepen.io/desandro/pen/ec8e24f6616e939af10743c32a54490d/

**Comment by nmklong** [comment]
Hi @desandro  i just tried your demo link and it's still loading all 6 images

**Comment by Josh-PCD** [comment]
Hi @desandro,
Not sure if Flickity is still being actively developed, but this bug still exists (even in your revised codepen). Uncommenting the 4th block works. Running into the same issue on my staging site.
