### ISSUE TITLE
.is-selected removed initially

### ISSUE THREAD

**Issue by ottobyte** [metafizzy/flickity#643]
Hi, I'm trying to use flickity where it's initial state hasn't added the class .is-selected. Is there any way that can be done?
Thanks

**Comment by ottobyte** [comment]
Hi, I've resolved this by adding:

>jQuery(document).ready(function() {
                    jQuery('.is-selected').removeClass('is-selected');
                });
I don't know with this is totally right - I'm not brilliant with js!!

**Comment by yaodingyd** [comment]
Your code snippet is totally valid.

**Comment by ottobyte** [comment]
Thanks! @yaodingyd
