### ISSUE TITLE
Specify how many slides to duplicate left/right of the viewport with wrapAround: true

### ISSUE THREAD

**Issue by jamesmoss** [metafizzy/flickity#644]
This a feature request.

We have a design element where we don't want `overflow: hidden` on the `.flickity-viewport` element - we'd like the slides to extend off past the sides of their container (and off the edge of the page). This works fine by default but with `wrapAround: true` the elements are disappearing due to the way the effect works. It looks like not enough slides are being duplicated to stop them from disappearing prematurely.

You can see a demo of this in action here: https://codepen.io/hugo/pen/GMMwXb

Can we add a new option to specify a width to determine how many slides to duplicate?  Or at least a number of additional slides to buffer left/right?

Thanks.

**Comment by yaodingyd** [comment]
Flickity is built from the beginning that it will not clone any DOM nodes for performance reasons. See this issue: #95. Although I'm not the owner, I think your feature request is hardly going to be implemented.

**Comment by jamesmoss** [comment]
Thanks @yaodingyd - I've closed this for the reasons outlined in #95.
