### ISSUE TITLE
Disable Mouse Drag

### ISSUE THREAD

**Issue by kdesigns** [metafizzy/flickity#645]
When the option 'draggable' is set to 'true', the slider is draggable with the mouse + touch.

Is it possible to disable this for mouse only?

I don't see a real world case that someone would drag a slider with the mouse. This should only be for mobile right?

**Comment by yaodingyd** [comment]
I think the best way is to disable mouse drag event on the element, out of Flickity.

**Comment by CHEWX** [comment]
I always drag with mouse, much easier than trying to click on a 50px 50px square arrow.

Aside from that, you can use a lib such as Modernizr to detect touch events and use a tenary operator on the `draggable` option for `true : false`. Something like `draggable : ( Modernizr.touch ) ? true : false`

This isn't a perfect solution, but it's better than nothing I guess. Another option is to do the above but detect screen width. 

There isn't really a perfect catch all solution.
