### ISSUE TITLE
Cannot read property 'option' of undefined

### ISSUE THREAD

**Issue by spanishproperty** [metafizzy/flickity#646]
Hi,

I'm no good at javascript - so sorry in advance if this shouldn't go here, I just don't know where else to go for this flickity error.

In chrome I am getting this javascript error:

Uncaught TypeError: Cannot read property 'option' of undefined
    at new l (flickity.js:1)
    at flickity.js:1
    at Array.forEach (<anonymous>)
    at flickity.js:1

Does anyone know the fix or what I am doing wrong? ( Web URL is https://www.domusvenari.com/ )

Thanks in advance.

Richie

**Comment by spanishproperty** [comment]
@yaodingyd - thank you very much. Stupid me, I was adding all js files into one, and forgot to take that one out! Stupid mistake, but sometimes you need two sets of eyes to find the problem.

Thanks again.

**Comment by yaodingyd** [comment]
@spanishproperty no problem. Happy to help.

**Comment by Pooja-Suresh-Mehta** [comment]
@yaodingyd I am facing the same error : Cannot read property 'options' of undefined
[connection-1] disconnected connect ETIMEDOUT 40.83.177.42:5671
[connection-1] disconnected connect ETIMEDOUT 40.83.177.42:5671
[connection-1] disconnected connect ETIMEDOUT 40.83.177.42:5671
[connection-1] disconnected connect ETIMEDOUT 40.83.177.42:5671


My javascript code is:


'use strict';
var connectionString = 'HostName=goapl-goregoan.azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=1sMhy8SH2UYFRXHZgP5vipCM7IeiaSn6VYH9bfkyVLI=';
var { EventHubClient, EventPosition } = require('azure-event-hubs');

var printError = function (err) {
  console.log(err.message);
};

var printMessage = function (message) {
  console.log('Telemetry received: ');
  console.log(JSON.stringify(message.body));
  console.log('Application properties (set by device): ')
  console.log(JSON.stringify(message.applicationProperties));
  console.log('System properties (set by IoT Hub): ')
  console.log(JSON.stringify(message.annotations));
  console.log('');
};


var ehClient;
EventHubClient.createFromIotHubConnectionString(connectionString).then(function (client) {
  console.log("Successully created the EventHub Client from iothub connection string.");
  ehClient = client;
  return ehClient.getPartitionIds();
}).then(function (ids) {
  console.log("The partition ids are: ", ids);
  return ids.map(function (id) {
    return ehClient.receive(id, printMessage, printError, { eventPosition: EventPosition.fromEnqueuedTime(Date.now()) });
  });
}).catch(printError);

**Comment by harshs07** [comment]
@Pooja-Suresh-Mehta were you able to resolve the issue? I am facing the same issue.

**Comment by Pooja-Suresh-Mehta** [comment]
Hello,

The problem was with my firewall blocking the requests sent by the device.

Regards,
Pooja Mehta
