### ISSUE TITLE
Flickity when as CommonJS module coupled with jQuery

### ISSUE THREAD

**Issue by dsheiko** [metafizzy/flickity#648]
The documentation says one can use Flickity with Vanilla JavaScript and it seems to work with no jQuery instance loaded as global object. However if requested as a module require/import 
https://github.com/metafizzy/flickity/blob/master/dist/flickity.pkgd.js#L32
it requires jQuery. The question is why it is strongly coupled? For example, I would like to use the lib as lazy-loaded chunk and avoid using jQuery. But Webpack  during transpolation crushes because it cannot find jQuery package (which is not installed)

**Comment by desandro** [comment]
flickity.pkgd.js includes [jQuery bridget](https://github.com/desandro/jquery-bridget) which adds jQuery plugin functionality. If you install Flickity via npm, it does not include jQuery Bridget. See https://flickity.metafizzy.co/extras.html#webpack

**Comment by dsheiko** [comment]
Awesome! I've checked, works to me fine.
