### ISSUE TITLE
Unrelated events are fired when appending 

### ISSUE THREAD

**Issue by trideout** [metafizzy/flickity#649]
**Test case:** https://codepen.io/trideout/pen/eGbBVa

This behavior is preventing me from creating an "infinite scrolling" carousel and the events being fired appear completely unrelated to the action of appending data.

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you follow up and describe what kind of behavior you are trying to achieve?

**Comment by trideout** [comment]
I am attempting to create an endless scroller that uses a jquery ajax call to append additional items once the end of the current list is reached. To do this I am listening to the events to detect the end of a scroll event and fire off my loadMore method. However, when appending the new contents, several events are fired that do not appear to be at all related and are causing the loadMore method to be fired again for every item being appended.

**Comment by banago** [comment]
Hi @desandro,

I've got he same issue. If you put the append inside an event call, it will fire infinitely. I'm trying to add cells to the carousel when you hit next slide.

Here is a slight edit of the previous pan that shows the issue: https://codepen.io/anon/pen/NwMRMp

Thanks very much.

**Comment by banago** [comment]
@trideout and @desandro, I was able to make this work. Here is my solution, check the commented lines: 

```js
    var flkty = new Flickity( '.carousel', {'groupCells': true, 'pageDots': false} );
        
    flkty.on('select', function(){
        // How many cells we've navigated already to compare against total cells
        var cellCount = (flkty.selectedIndex + 1) * flkty.selectedCells.length; 

        // This is needed to stop firing of this event infinitely
        if( cellCount < flkty.cells.length) return;

        $.ajax({
            url: settings.ajax.url,
            data: {
                action: 'get_caros',
                nonce: settings.ajax.nonce,
                cat: caro.dataset.cat,
                offset: flkty.cells.length
            },
            success: function(html){
                if (! html) return;
                var tag = document.createElement("div");			    
                tag.innerHTML = html;
                flkty.append( tag.childNodes ); 
            }
        });
    });
```
I hope it helps.

**Comment by desandro** [comment]
🎉  **[Flickity v2.1.0](https://github.com/metafizzy/flickity/releases/tag/v2.1.0) has been released with  all new [`change` event See docs!](https://flickity.metafizzy.co/events.html#change)** 🎉

> Triggered when the selected slide is changed.

``` js
// jQuery
$carousel.on( 'change.flickity', function( event, index ) {
  console.log( 'Slide changed to ' + index )
});

// vanilla JS
flkty.on( 'change', function( index ) {...});
```

`select` will continue to be triggered multiple times, but `change` is only triggered when the selected slide is changed. 

I'm now closing this issue. Please open a new issue if you into trouble with using `change`. Thanks for sticking with Flickity! 🌈🐻
