### ISSUE TITLE
loading problem while switching between tabs

### ISSUE THREAD

**Issue by geroldhinzen** [metafizzy/flickity#65]
the problem can be created by including a flickity stream on two different tabs. while the content of the first tab is loaded, the content of the second isn't correct initialized. by switching the tab the flickity stream doesn't show the pictures correctly

![bildschirmfoto_2015-02-26_um_14_19_28](https://cloud.githubusercontent.com/assets/4331332/6392686/7c7d2cfe-bdc3-11e4-8b90-2bbb5934f445.png)
![bildschirmfoto_2015-02-26_um_14_19_43](https://cloud.githubusercontent.com/assets/4331332/6392685/7c7ce55a-bdc3-11e4-8370-a89d2a9993aa.png)

update: i used bootstrap 3.3.2, chrome Version 40.0.2214.115 (64-bit)
.

**Comment by Plunkett112358** [comment]
Hey, I was wondering if there is a solution to this yet.  Having a similar issue. 

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue.

The solution is to [trigger `resize`](http://flickity.metafizzy.co/api.html#resize) after a hidden Flickity gallery is un-hidden.

``` js
$gallery.show()
  .flickity('resize')
```

See example: http://codepen.io/desandro/pen/eNvdoo

I've added this to the `resize` docs.

**Comment by bcalik** [comment]
@desandro calling resize does not work for me.
