### ISSUE TITLE
height in responsive carousel...??

### ISSUE THREAD

**Issue by arcadia81** [metafizzy/flickity#650]
I never understood how to set the viewport (and cells) height on responsive carousel.

I need a carousel of images in full width and auto height. Not adaptive height, all the images has the same size, but obviously the images need to be responsive. If i set width:100% and height:auto on the images this should be ok, but i have to set a viewport's height too and I don't know this informations because the images are responsive...

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
