### ISSUE TITLE
Speed Differences: HTML Data API  Vs JavaScript Objects

### ISSUE THREAD

**Issue by TheRealJAG** [metafizzy/flickity#652]
While researching your awesome plugin, I'm curious if there's a difference in page speed between the 2. 

https://i.imgur.com/8h3V54J.png

**Comment by yaodingyd** [comment]
JavaScript should be faster than init with data attributes but the difference would be negligible as `hltmInit` has around 30 lines of codes.

**Comment by desandro** [comment]
Initializing in JavaScript should be faster, as initializing in HTML may be delayed waiting for `DOMContentLoaded` event. But the difference should be negligible.
