### ISSUE TITLE
Flickity won't initialising when switching Tab

### ISSUE THREAD

**Issue by Androsyn31** [metafizzy/flickity#653]
hello I installed flickity in asnavfor and 
it is correctly initialized in the first tab. But when i change the tabs 
it does not appear . when I go into developer mode (F12) in my browser, it appears correctly in the active tabs

I have already tried the resize solution but it does not work

here my code for the main 
`<div class="row <?php echo $slide;?> carousell-nav" data-flickity='{"contain": true}'>`
and for the nav
`<div id="<?php echo 'tabs-'.$critere->getId(); ?>" class="row carousel-main" data-flickity='{"contain": true, "asNavFor": ".carousell-nav","pageDots": false, "prevNextButtons": false}'>`
![46de0980-8943-4473-9a24-1481ea7a6d8c]

The fisrt tab is alway ok
![46de0980-8943-4473-9a24-1481ea7a6d8c](https://user-images.githubusercontent.com/15155920/32602619-086950ca-c547-11e7-8893-1712ba0a1926.png)

The second tab won't initialize
![screenshot-2017-11-9 top consoles de jeux 2018](https://user-images.githubusercontent.com/15155920/32602626-15cc3ae8-c547-11e7-817d-5a4e86f25703.png)

When i push F12 to my browser the tab is ok

![8ec272a6-b61e-4d84-818a-1b6d3a1c513e](https://user-images.githubusercontent.com/15155920/32602642-29117640-c547-11e7-8f52-38922ff82e65.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by ishtiaq1218** [comment]
Hi Desandro,

I have the same issue. I have created a reduced test case.

https://codepen.io/ishtiaquk08/pen/qpjxgm

Please help.
Thanks

**Comment by ishtiaq1218** [comment]
Hi Desandro,

I managed to get it work!! The issue is that the height of 'flickity-viewport' is not being calculated for the carousels in tabs 2 and 3.. Upon manually resizing the window the content is displaying perfectly.  (whenever we open the Developer tools, the size of the content area is updated/changed, which resulted the desired output.)

Now upon triggering resizing event ("window.dispatchEvent(new Event('resize'));") onClick of Tab, the issue is fixed (for now).

Regards,
Ishtiaq.

**Comment by desandro** [comment]
I recommend use [`resize` method](https://flickity.metafizzy.co/api.html#resize) when the tab is shown.

> If Flickity is initialized when hidden, like within a tab, trigger resize after it is shown so cells are properly measured and positioned.

``` js
$('.button').on( 'click', function() {
  $carousel.show()
    // resize after un-hiding Flickity
    .flickity('resize');
});
```

See demo https://codepen.io/desandro/pen/eNvdoo

**Comment by srikat** [comment]
@ishtiaq1218 Thank you.

```
window.dispatchEvent(new Event('resize'));
```

did the trick.

```
$('#_tab-154-25').on( 'click', function() {
    window.dispatchEvent(new Event('resize'));
});
```

For some reason,

```
$('#_tab-154-25').on( 'click', function() {
    $carousel.show()
        // resize after un-hiding Flickity
        .flickity('resize');
})
```

doesn't work for me.

**Comment by joneyspark** [comment]
> Hi Desandro,
> 
> I managed to get it work!! The issue is that the height of 'flickity-viewport' is not being calculated for the carousels in tabs 2 and 3.. Upon manually resizing the window the content is displaying perfectly. (whenever we open the Developer tools, the size of the content area is updated/changed, which resulted the desired output.)
> 
> Now upon triggering resizing event ("window.dispatchEvent(new Event('resize'));") onClick of Tab, the issue is fixed (for now).
> 
> Regards,
> Ishtiaq.

Thanks a lot. I Finally found the solution.
