### ISSUE TITLE
Carousel offset incorrectly calculated resulting in gaps between items

### ISSUE THREAD

**Issue by TheHoover** [metafizzy/flickity#654]
Dell Latitude 5587 (viewport: 1376 x 643, res: 1920 x 1080). 
Chrome only - OK in IE.
Only happens on a client's laptop (2 of them exhibited this problem). Cannot reproduce on other laptops that I've tried or desktops.

Gaps between carousel items.

**Test case:** https://codepen.io/anon/pen/gXmLRR

Actual output:

![image](https://user-images.githubusercontent.com/10939145/32664578-a157d6c0-c629-11e7-81b8-098977b274ee.png)

Although width of cells specified at 25% they are being offset at 25.12% increments hence the gap.

I'm not in a position to debug at the moment but a generated log shows that in getPostitionValue the carousel width (t) is greater than 25% of the viewport although on screen it isn't.

I should add that I haven't been able to reproduce this on my desktop using dev tools in responsive mode so was looking for a workaround that doesn't involve not using percentage widths.

**Comment by yaodingyd** [comment]
You have border setting and I think your IE's default `box-sizing` is set to `border-box` so it works in IE. Chrome's default `box-sizing` is `content-box` so all you need to do is add `box-sizing: border-box` to your `.gallery-cell`

**Comment by desandro** [comment]
The gap could also be caused by scroll bar being removed after Flickity is initialized. add `html { overflow-y: scroll; }` to resolve that.
