### ISSUE TITLE
Lazyload and Autoplay on a slow connection. 

### ISSUE THREAD

**Issue by rgfx** [metafizzy/flickity#656]
Hi,

It would be nice with autoplay could wait for the image to load before going to the next slide. When testing on slow 3g noticed some jank.  Maybe am doing something wrong.

**Comment by desandro** [comment]
You can add this kind of custom behavior with Flickity's API. See [lazyLoad event ](https://flickity.metafizzy.co/events.html#lazyload) and [Player methods](https://flickity.metafizzy.co/api.html#player)
