### ISSUE TITLE
Creating an external gutter while preserving edge-to-edge transition

### ISSUE THREAD

**Issue by bakura10** [metafizzy/flickity#657]
Hi,

I'm trying to achieve a design where I want to have external gutter (left and right) that are larger than the spacing between cells, while still preserving the horizontal scrolling in the full width.

I've tried countless of combinations but I've been completely unable to solve it. The most I've been able to achieve is this: https://codepen.io/anon/pen/WXXMRe

But there are two issues here:

1) We can still see the previous and next items.
2) It flickers when you reach the edge of the carousel.

I could indeed move back the overflow: hidden to the flickity-viewport, but when doing that, the animation does not transition "edge to edge", which is not visually the most appealing.

How can we therefore combine edge to edge transition, while having larger gutter on outside?

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue. I appreciate you putting together the demo. But I'm having trouble understanding what kind of behavior you're trying to achieve. Could you make a little image/diagram showing what you're thinking?

**Comment by bakura10** [comment]
Hi @desandro . Thanks for welcoming the issue.

Please find a small drawing:

![blank2](https://user-images.githubusercontent.com/1198915/33030088-a9c0f9ec-ce1a-11e7-84d8-780decd87c04.jpg)


As you can see, the top screen is the initial state. The red element is the container viewport.

Each item (in green) has a horizontal padding that make it separated from next cells. However I'd like to have larger spacing on the edges _without_ displaying the next and previous cells.

This can be achieved by adding a margin on the flickity-viewport for instance.

But when I do so, the animation no longer goes until the edges of the container (bottom picture).

I've tried to add padding and/or margin to the flickity-slider but it seems that it does not do the trick.

I hope it's clearer :).

**Comment by desandro** [comment]
Thanks for that. I think you want to try enabling [groupCells: true](https://flickity.metafizzy.co/options.html#groupcells)
