### ISSUE TITLE
Hide the BigCommerce CDN image path on image mouseover (product detail page)

### ISSUE THREAD

**Issue by atpworldtour** [metafizzy/flickity#658]
https://www.screencast.com/t/I8jwTQH2Tw

How can we remove clickable links that are embed on our listing description? We do not want the CDN image url visible on mouseover.

I.e. https://cdn6.bigcommerce.com/s-l0ery2h/images/stencil/1024x1024/products/168/454/Milk_Break_Up_Bar_2__43189.1511142714.jpg?c=2

**Test case:** http://codepen.io/desandro/pen/azqbop

**Comment by desandro** [comment]
The clickable links are present due to whatever HTML code you are using. Flickity does not add or edit the HTML used in navigation.
