### ISSUE TITLE
[QUESTION] Tactic to stop Right-click initiating start drag?

### ISSUE THREAD

**Issue by AshCoolman** [metafizzy/flickity#659]
If you go [to the example](http://codepen.io/desandro/pen/azqbop) and right-click on a slide, the browser pauses for the context menu, but then when the context menu is dismissed, the slide continues to drag.

Is there currently a correct (or possible) way to tackle this using the API?

Thanks

Edit: Thanks! for others wanting to test the solution below https://codepen.io/AshCoolman/pen/EbLJBG

**Comment by desandro** [comment]
Thanks for reporting this bug! I'll have a fix in the next release.

Until then, you should be able to hack it by adding this code before you initializing Flickity:

``` js
var _pointerDown = Flickity.prototype._pointerDown;
Flickity.prototype._pointerDown = function( event ) {
  if ( event.button ) {
    return;
  }
  _pointerDown.apply( this, arguments );
};
```

**Comment by desandro** [comment]
Flickity v2.0.11 has been released with this fixed. Thanks again for reporting this!
