### ISSUE TITLE
freeScroll and a single item

### ISSUE THREAD

**Issue by Simpleqode** [metafizzy/flickity#663]
I tried to use freeScroll with a single really long item, but it didn't work until I added the second empty one. This gave me a lot of white space to the right of the first item (which was fixed by adding contain: true).

**Comment by desandro** [comment]
Sounds like you're trying to use Flickity as a sort of scroller, which is not its intended behavior. I recommend trying another solution for this use-case. Sorry, I won't be able to help here.
