### ISSUE TITLE
.is-selected for all visible slides when using wrapAround

### ISSUE THREAD

**Issue by anteksiler** [metafizzy/flickity#664]
When using wrapAround, is-selected class is only added to the cells that are not duplicated.

Let's say you have 5 total cells and only 4 are visible, and you  go to the next page, only 1 gets the .is-selected class.

Of course, this is with groupCells as I would like to always display 4 cells.

**Comment by desandro** [comment]
Thanks for reporting this issue. This is how Flickity is intended to work. It does make groups for any combination of cells, but rather only one set of groups. You can choose to use groupCells, which you'll select 4 + 1, or not and select 5 x 1.
