### ISSUE TITLE
lazyload + wrapAround = last image is loaded before first image

### ISSUE THREAD

**Issue by virgo79** [metafizzy/flickity#666]
Hi,
I'm using flickity with lazyload and wrapAround options enabled.
The configuration is:

`lazyload : 1` 
`wrapAround : true`.

Currently I've 5 slides, and every slide contain an image inside it, let's say that:

slide1 contains image1.jpg
slide2 contains image2.jpg
...
slide5 contains image5.jpg

I've noticed that, with the above configuration, image5.jpg is loaded before image1.jpg.
I think that image1.jpg should be loaded for FIRST, because is the first slide showed to the users.

I expect that the correct loading order should be

image1.jpg
image2.jpg
image5.jpg

If `wrapAround` is set to `false` (or not declared) the loading order is correct.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
