### ISSUE TITLE
Very poor scrolling performance

### ISSUE THREAD

**Issue by bakura10** [metafizzy/flickity#667]
Hi,

I'm encountering a very poor performance on the project I'm working on with scrolling on iPhone (tried on iPhone 6 but I can reproduce this on more powerful iPhone as well).

My page indeed have a bit of carousels, but all carousels have very few slides (4 at most), but even keeping 2 carousels or 3 causes the same sluggish performance.

I can't reproduce that on the Flickity demo website where it's silky smooth on my phone, as well as on other websites using Flickity, where it's absolutely perfect.

You can try it yourself here: https://diamant-development.myshopify.com/

Then try to swipe relatively quickly different slides from slideshow, and you will be able to exeprience a kind of "lag" in the swipe.

I tried to isolate my code, removing all other parts that do not contain Flickity... But I can't find anything that could cause this performance issue, so I may be missing something obvious here...

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue. Possible performance issues:

+ Several big image are loaded. Mobile devices may run into memory images trying to render extra large (> 1000px x 1000px) images.
+ Lots of images in general
+ Other transitions or animations happening on the page.

I've had reports that Flickity holds up well in other high-performance issues #655, so I believe the issue may lie outside of Flickity.

**Comment by bakura10** [comment]
Hi,

Thanks a lot. I'll check but on my cases images are not that large (I'm suing responsive image and only serve exact needed dimensions, so they are much less than 1000x1000). There are zero other transitions happening on the page neither.

I'll continue digging up but I can't explain the difference, while it's perfectly smooth on other website I've tried in demos that are using much much more images than I am doing.

**Comment by Samuell1** [comment]
Hey, we having similar issue but Iphone animations between slides are smooth but on Android device Chrome or Samsung Internet its choppy. Any idea what can cause this issue?

**Comment by jlahijani** [comment]
Not sure if this is completely related, but I had performance issues on my Android phone (Pixel 6). The images in the carousel had a drop shadow on them (specifically Tailwind's 'drop-shadow-lg' class). Removing that class resolved the issue.
