### ISSUE TITLE
Slider full width glitch (incorrect position on page load)

### ISSUE THREAD

**Issue by JimmyAppelt** [metafizzy/flickity#668]
**Test case:** https://codepen.io/desandro/pen/dPdyJK

The slider has incorrect positioning on initial page load. When scaling the browser window the slider corrects itself.

![2017-12-21_01-42-09](https://user-images.githubusercontent.com/5420393/34235188-42157ee2-e5f0-11e7-91c8-8288448c3afc.gif)

Tested on Chrome/Edge/FF

**Comment by desandro** [comment]
You can resolve this issue with `html { overflow-y: scroll; }` CSS. Demo updated.

**Comment by JimmyAppelt** [comment]
@desandro thanks for your response.

I see 😃, but ouch, that will force a sidebar even when no sidebar is necessary. But I guess there is no other way at this time.

**Comment by desandro** [comment]
Or you can use `overflow-y: hidden` if you never want a scrollbar. Or your page might automatically have a scrollbar, in which case this wouldn't be an issue. Try out options!

**Comment by JimmyAppelt** [comment]
> Or you can use overflow-y: hidden if you never want a scrollbar. Or your page might automatically have a scrollbar, in which case this wouldn't be an issue. Try out options!

I did. Flickity is deeply integrated within our CMS theme, we can't force scroll or hide it on behalf of the users on all pages that way.

**Comment by JimmyAppelt** [comment]
When the content of the page is not big enough, but a scroll bar is automatically added, the issue is still present.

You can see it here: https://codepen.io/JimAppelt/pen/zpoPxM

**Comment by desandro** [comment]
Looks to be the same scroll bar issue. I think your demo may have needed more content below https://codepen.io/desandro/pen/eb88a65940fbfe872312be88092204c6/

**Comment by JimmyAppelt** [comment]
@desandro Yes indeed 😃 I know it works fine with more page content. I've tested that 👍 
The again ... we don't decide the page length for our users either 😉
