### ISSUE TITLE
npm package size

### ISSUE THREAD

**Issue by flihub** [metafizzy/flickity#669]
why npm package has sandbox folder? 

sandbox folder is 7.93 MB  
yoshi-parallax in sandbox folder necessary?

**Comment by desandro** [comment]
ah! Thanks for the heads up. I had ignored these in `.git/info/exclude`, not `.gitignore`. That has been changed and will be fixed in the next release.

**Comment by desandro** [comment]
v2.0.11 has been released with this fix added. Thank you for reporting this!
