### ISSUE TITLE
Separate gallery scrolling from vertical page scrolling on touch devices

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#67]
[Kiwistian](https://twitter.com/sirkaisermann/status/572439084909654016)

> is there a way to block  the window vertical scroll, on mobile, while the user is swiping the slide?

I'm considering changing the `touchVerticalScroll` behavior so that user can either scroll horizontally in the gallery OR scroll vertically on the page, but not do both.

**+1** or subscribe to this issue If you'd like to see this feature added.

**Comment by chrispif** [comment]
+1

**Comment by o-l-e** [comment]
+1

This would be a really nice detail.

**Comment by piehouserat** [comment]
+1

**Comment by unireverse** [comment]
+1

**Comment by zitrusfrisch** [comment]
+1

**Comment by boynet** [comment]
sound good but must be option to turn this off

**Comment by dowonkang** [comment]
+1

**Comment by auginator** [comment]
+1

**Comment by rbrtsmith** [comment]
+1 even more so if it can be toggled.

**Comment by jonathanolsen** [comment]
+1 - this is a must for a project I am working on!

Anyone have any temporary hack/solution?

**Comment by remisture** [comment]
+1

**Comment by sebastiangraz** [comment]
+ 1

**Comment by SoullessWaffle** [comment]
+1 this is the reason I currently have draggable set to false

**Comment by dagobertrenouf** [comment]
+1

**Comment by ivancuric** [comment]
+1

**Comment by rgfx** [comment]
+1

**Comment by mdmoreau** [comment]
+1

**Comment by mikestempien** [comment]
+1

**Comment by rjmil** [comment]
+1

**Comment by flowgrow** [comment]
:+1:

**Comment by passiomatic** [comment]
+1 

Indeed this can be annoying while on mobile, although in my case this will be flixed by setting draggable: false (see #51).

**Comment by evoactivity** [comment]
+1 Really want to see this as right now on touch devices it feels a little janky when swiping and also causes a vertical movement.

**Comment by oppenheimer-** [comment]
+1

**Comment by aebsr** [comment]
+1
I have a gallery that at times can consume all but 60 or so pixels of the screen. Very problematic.

**Comment by kasparhuebener** [comment]
+1

**Comment by bpowers1215** [comment]
+1

**Comment by reberhardt** [comment]
+1

**Comment by matthewblack** [comment]
+1

**Comment by limpa123** [comment]
+1

**Comment by dagobertrenouf** [comment]
Already plus oned this, just want to add this: Flickity is awesome because of the way it responds to user input. This is what makes it really stand out to me: the physical aspect of it. Not being able to use "draggable" on touch devices is a huge loss. Let me know if I can help in any way.

**Comment by marcamos** [comment]
+1

**Comment by sjelfull** [comment]
+1

I feel the same way, @dagobertrenouf - it's the most elegant slideshow in terms of responding natural to any type of gesture/interaction, so having to disable draggable just sucks.

**Comment by desandro** [comment]
To confirm: I'll be focusing on resolving this in an upcoming release. This issue has received plenty of interest. Thanks for all the feedback :whale:

**Comment by apsolut** [comment]
@desandro thanks for listening to us [lost souls]...

**Comment by dagobertrenouf** [comment]
@desandro awesome!

**Comment by desandro** [comment]
Flickity `v1.0.1` has been released with fixes for touch scrolling. [Try it out](http://flickity.metafizzy.co/) and let me know of any issues.

**Comment by flowgrow** [comment]
Yesyesyes!
You are awesome! It works perfectly.. Very intuitive

**Comment by matthewblack** [comment]
You the man!!!

**Comment by jonathanolsen** [comment]
Finally! You own the internet.

**Comment by remisture** [comment]
@desandro: 404 for both js and css: 

http://cdnjs.cloudflare.com/ajax/libs/flickity/1.0.1/flickity.pkgd.min.js
http://cdnjs.cloudflare.com/ajax/libs/flickity/1.0.1/flickity.css

**Comment by dagobertrenouf** [comment]
@desandro this created a new issue : clicking on the arrows makes the carousel move ahead by two items instead of one, only on touch devices (tested on ios safari, chrome android).

Shown here
https://jsfiddle.net/rfdeoqea/25/

**Comment by flowgrow** [comment]
i can confirm this new issue. Chrome on iOS8

**Comment by desandro** [comment]
@dagobertrenouf @flowgrow I've opened and addressed this separate bug in #122. Flickity `v1.0.2` has a fix

@remisture Thanks for the heads up. CDNJS is being a bit slow with its version updates :( I'm considering alternatives

**Comment by sjelfull** [comment]
Does anyone else experience staticClick being fired when scrolling vertically?

**Comment by marcamos** [comment]
Thank you @desandro.

**Comment by desandro** [comment]
@sjelfull Hadn't tested that. I've opened #127 to track it.

**Comment by sashabeep** [comment]
V.2.0.5 problem still exists

**Comment by Bryan101Nicholson** [comment]
I am using vertical scroll and dynamically loading content. On the Iphone6 performance is terrible. Trying to rectify.

**Comment by skill83** [comment]
@desandro do you plan to release an option to prevent vertical dragging during horizontal?

**Comment by desandro** [comment]
@skill83 See #740
