### ISSUE TITLE
Visible bump with lazyLoad and adaptiveHeight both enabled

### ISSUE THREAD

**Issue by ryanburnette** [metafizzy/flickity#670]
If you enable `lazyLoad` and `adaptiveHeight` at the same time, you get a bump, albeit an expected one where the adaptive height feature fires on the slide without its image loaded. The adaptive height feature fires again when the image loads, but there is a more graceful transition that could occur here.

What do you think, @desandro? Is this something you might consider addressing? One thought I have is just to hold at least the height of the previous element until the image loads on the next slide. Some ideas on how to hook into the plugin to configure a different approach could also be helpful.

My issue has some distant connection to https://github.com/metafizzy/flickity/pull/430. If lazy loading could always be a certain number of slides ahead, this issue would also be solved, at least enough to improve my user experience.

The test case isn't optimal because the images load quickly, you have to look closely for the bump I'm talking about.

**Test case:** https://codepen.io/ryanburnette/pen/rpyqNV

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. The best solution is to set `lazyLoad: 1`, so the next adjacent slide's images are loaded.

**Comment by ryanburnette** [comment]
Doh, I thought lazyload only took a Boolean. Sorry for missing that detail.
