### ISSUE TITLE
is-selected cannot modify height

### ISSUE THREAD

**Issue by Lyla01** [metafizzy/flickity#671]
Hello,

I've just recently used Flickity and I'm liking it. Currently, I have a dilemma about the "is-selected" option for CSS. It seems it cannot alter the height of the carousel's cell.

`.carousel-cell.is-selected {
  height: 500px;
}`

Any workaround for this? Thanks in advance. :)

**Comment by desandro** [comment]
Thanks for reporting this issue. Flickity measures cells once for performance.

One workaround is to set initial cell height to the tall height for all cells, then add another CSS style to resize all cells down to normal height once Flickity is initialized.

``` js
/* initial height */
.carousel-cell { height: 400px; }

/* non-selected size */
.flickity-enabled .carousel-cell { height: 200px; }

/* selected size */
.carousel-cell.is-selected { height: 400px }
```

See demo https://codepen.io/desandro/pen/a4a888abfcf55fd397c737625041d624/

**Comment by Lyla01** [comment]
Hi @desandro ,

Thanks for the response. I've checked yours and it produces the same result as the one I have -- height does not alter. Apparently, the height does not change UNTIL the window gets either zoom in or out. This happens on both mine and your code:

`.carousel-cell.is-selected { height: 500px; }`

```
/* initial height */
.carousel-cell { height: 400px; }

/* non-selected size */
.flickity-enabled .carousel-cell { height: 200px; }

/* selected size */
.carousel-cell.is-selected { height: 400px }
```

Any thoughts on this?

**Comment by desandro** [comment]
Ah, sorry about that. Looks like you'll need to initialize with jQuery or vanilla JS so you can [trigger resize](https://flickity.metafizzy.co/api.html#resize) after initializing.


``` js
var $carousel = $('.carousel').flickity();
$carousel.flickity('resize');
```

**Comment by Lyla01** [comment]
Thank you very much. It now works. I'll take note of this.
