### ISSUE TITLE
Flickity won't initialising in accordion panels

### ISSUE THREAD

**Issue by ishtiaq1218** [metafizzy/flickity#672]
Hi Desandro,

This is extension to "Flickity won't initialising when switching Tab #653". But for MOBILE, The tabs become "accordion" (in my work). In the mobile the resize is also not working on initial load.

**Test case:** https://codepen.io/ishtiaquk08/pen/aEEVRd

Until and unless, the mobile's orientation is changed the resize is not triggering.

**Comment by desandro** [comment]
My recommendation is to initialize Flickity first, then initialize & hide the panel. Do this all in JS (remove HTML initialization) to remove race conditions.

``` js
// init Flickity
var $acarousel = $('.carousel').flickity({
  wrapAround: true,
});

var $collapse1 = $('#collapse1');
$('.anchor-click').on( 'click', function() {
  $collapse1.collapse('toggle')
});

// collapse panel once Flickity is initialized
// hack with setTimeout
setTimeout( function() {
  $collapse1.addClass('collapse');
});
```

See demo https://codepen.io/desandro/pen/82f5a8d70e47a1f1fbf9922b11bb2be2

**Comment by malkum** [comment]
Hi,
If we use details tag, instead of bootstrap accordion, here is a working solution https://github.com/metafizzy/flickity/issues/1214

**Comment by malkum** [comment]
Hi @desandro ,
Do you have a working example of flickity slders inside accordions or details. when we open and close the acoordion or details tag, sometimes, the sliders viewport height goes to 0. 
Is it even a right strategy to use sliders inside collapsable panels? bootstrap or otherwise
