### ISSUE TITLE
Ability to disable one cell

### ISSUE THREAD

**Issue by knynkwl** [metafizzy/flickity#673]
We are enabling the slider on mobile but don't want one slide to appear. Is there a way to disable a single slide, without removing it completely?

**Comment by desandro** [comment]
Hmm, one way would be to add a class to all the active cells `.active-cell` and then using that selector to specify those [cells with `cellSelector`](https://flickity.metafizzy.co/options.html#cellselector)

``` js
cellSelector: '.active-cell',
```
