### ISSUE TITLE
Width change on "Selected" Cell creates issue

### ISSUE THREAD

**Issue by sonimanoj** [metafizzy/flickity#678]
Hello,

I love the flickity slider ever since I started using it, Today  I was working on something where I have created slider that has 4 visible cells on screen where "is-selected" (i.e. selected cell) is bigger than rest of the cells, So in CSS i created different size for selected cell (each cell contains html text and image).

Now what happens is my selected cell becomes bigger on change but it doesn't adapt the width so it overlaps with previous and next cell, once i resize browser window, it would adapt width, but it wouldn't otherwise.

I tried fixing this by settle event by using:

$carousel.on( 'settle.flickity', function() {
  $carousel.resize();
})

but it didn't help. any help for this, i attached two files, one is what i want to achieve and another is what i am getting.

Regards
Manoj Soni
![01](https://user-images.githubusercontent.com/35563798/35096153-1ab36084-fc71-11e7-8e6e-a79f9e0c20e4.jpg)
![02](https://user-images.githubusercontent.com/35563798/35096154-1ae3366a-fc71-11e7-825b-40abffbca93f.jpg)

**Comment by desandro** [comment]
Have you looked at using `reposition`? https://flickity.metafizzy.co/api.html#reposition
