### ISSUE TITLE
asNavFor not working with draggable:false

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/flickity#679]
hey there.

just noticed an issue. that's when we set a carousel as nav for another carousel, with draggable set to false it will cause the nav carousel not working. is that something normal? https://codepen.io/Mohsen-Khakbiz/pen/opJEgQ

Regards,
Mohsen

**Comment by desandro** [comment]
Thanks for reporting this bug. This issue is related to #51 

Sorry there is no fix yet.

**Comment by desandro** [comment]
🎉  **[Flickity v2.1.0](https://github.com/metafizzy/flickity/releases/tag/v2.1.0) has been released with support for all new `staticClick` enabled with `draggable: false` 🎉

`asNavFor` will now work with `draggable: false`.
