### ISSUE TITLE
asNavFor, previous & next buttons don't select main

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [metafizzy/flickity#680]
hey there.

please check this pen https://codepen.io/Mohsen-Khakbiz/pen/MrZVbZ/
added a carousel as nav, also used it's navigation buttons to act like prev/next buttons for the main carousel. but when using buttons we can't reach to the end or the beginning of carousels. I saw there was something like this situation here https://github.com/metafizzy/flickity/issues/598
but isn't there any way to use flickity default buttons?
also on selecting cells, they're getting both .is-selected and .is-nav-selected classnames, but on navigating the last and first items are getting .is-selected classname but not .is-nav-selected. even when groupCells is false for nav carousel.

**Comment by desandro** [comment]
Yes, you can achieve this behavior using [flickity-sync,](https://github.com/metafizzy/flickity-sync) and adding in click-to-select with the nav.

See demo https://codepen.io/desandro/pen/MrMrqP

``` js
var mainFlkty = new Flickity( '.gallery-main', {
  sync: '.gallery-nav',
});

var navFlkty = new Flickity( '.gallery-nav', {
  contain: true,
});

// select on nav click
navFlkty.on( 'staticClick', function( event, pointer, cellElement, cellIndex ) {
  console.log( cellIndex )
  if ( cellIndex !== undefined ) {
    navFlkty.select( cellIndex );
  }
});
```

**Comment by Mohsen-Khakbiz** [comment]
perfect. thanks a lot for this awesome plugin
