### ISSUE TITLE
Resize .flickity-viewport upon viewport change

### ISSUE THREAD

**Issue by kaleidografik** [metafizzy/flickity#681]
Hi @desandro - Quick question, we are not using AdaptiveHeight, however when the browser is resized we would like the .flickity-viewport inline style to update to the height of the largest cell. Currently, the height of .flickity-viewport is set upon load, and only changes when INCREASING the size of the viewport. If decreasing the size, the .flickity-viewport inline height does not update, leaving us with large cell sizes seen on bigger browsers.

Any tips?

**Comment by desandro** [comment]
Thanks for reporting this issue. You may have stumbled on a bug. Can you create a **reduced test case** so I can better understand the issue?  
I'm sorry to see you're having trouble with Flickity. Try [forking the basic demo](https://codepen.io/desandro/pen/azqbop)

 See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by desandro** [comment]
@Sam-Pryor I recommend you use [`setGallerySize: false`](https://flickity.metafizzy.co/options.html#setgallerysize)

**Comment by dsheiko** [comment]
@desandro by disabling gallery size one has to set  height of `.carousel`, but the thing is that it's dynamic (made by the highest slide). I don't think it can be solved with CSS. The only, note when following @Sam-Pryor, do not forget to debounce window resize handler

**Comment by cmalven** [comment]
I had to use the same hack as @Sam-Pryor. I'm not sure why you would want `flickity-viewport` to lock its height on page load if you're using `setGallerySize: true` and want to explicitly control slide height.

**Comment by wolfx1998** [comment]
> @Sam-Pryor I recommend you use [`setGallerySize: false`](https://flickity.metafizzy.co/options.html#setgallerysize)

Late reply, but I have just faced the same issue. Great answer! Just for someone adding this solution, make sure that the parent element wrapping viewport has `height: 100%;`
