### ISSUE TITLE
Keyhole parallax with wrapAround

### ISSUE THREAD

**Issue by Zo4inec** [metafizzy/flickity#682]
Good day.
How to make parallax infinite slider from this codepen https://codepen.io/desandro/pen/qNPbgb ?
When the last slide scrolled to first, last slide disapears on transform.

**Comment by desandro** [comment]
Sorry, I do not have a demo ready for Keyhole parallax with wrapAround. I'll leave that to you or another valiant developer to find a solution for in the meantime.

**Add a 👍  reaction** to this issue if you would like to see this demo added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by desandro** [comment]
Closing here. Add your 👍 to #468
