### ISSUE TITLE
Chrome/Opera Flickity sliders not resizing properly on navigation to and soft-refresh

### ISSUE THREAD

**Issue by AttilaDelmont** [metafizzy/flickity#683]
Hello,

We've got a slight problem with Chrome (and Opera) not resizing Flickity sliders properly, when loading page in some cases and when doing a soft-refresh (Just pressing F5 or refresh icon - No control key) on these pages:

https://tinyurl.com/y97yoxqk
https://tinyurl.com/y7ywsgr8
https://tinyurl.com/ydb75gfk
https://tinyurl.com/ydyfal8j
https://tinyurl.com/y7lb84w4
https://tinyurl.com/y8m9gtzh
https://tinyurl.com/y9csjmn6
https://tinyurl.com/y9u7z4or
https://tinyurl.com/yagrpznx

![image](https://user-images.githubusercontent.com/26059576/35617084-7c8fa7d0-0677-11e8-826e-714c6ee40cdc.png)

We've already implemented a half a second timeout (Loop and resizing all sliders) - But the issue persists at random?!

This is not a problem in either UC, IE or FF!

Any help would be appreciated - Thanks!

Best regards,
Attila Delmont

**Comment by desandro** [comment]
Thanks for reporting this issue. I appreciate you providing a live URL but I will not be able to debug this issue on your produce site. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
