### ISSUE TITLE
Prevent modal opening on click when dragging

### ISSUE THREAD

**Issue by nicolay-zlobin** [metafizzy/flickity#684]
Each cell is a link to modal window. When user drags slides with mouse on desktop modal became open.

**Comment by desandro** [comment]
Sounds like you're modal library is using `click` event. If you can use [`staticClick`](https://flickity.metafizzy.co/events.html#staticclick) instead, you should be able to resolve this issue.

**Comment by nicolay-zlobin** [comment]
Thank you, that's exactly what I need to!
