### ISSUE TITLE
Wrong position calculation on init with uncached fluid images

### ISSUE THREAD

**Issue by maximelebreton** [metafizzy/flickity#691]
Hello @desandro, and thanks for your amazing work!

I have a strange position calculation bug on a **full screen carousel with fluid images**

**Important:**
* this bug appears on `Chrome 64 stable`, `66 canary` and `Firefox 58` (less often)
* it seems to bug when images aren't cached (`ctrl+F5` on Windows or `disable cache` with DevTools)
* bug when i'm working on a localhost server
* this bug disappear if you resize the window
* no bug when images are removed

Here is the pen: https://codepen.io/anon/pen/bLgvOZ
-
On this pen, if I **reload without cache**, the **bug appears**, but if I hit reload with cache, everything is ok.

Correct behaviour (images are correctly positionned, left positions ok)
-
![image](https://user-images.githubusercontent.com/1072425/36001816-05b6882e-0d28-11e8-9e42-427978ab192c.png)

![image](https://user-images.githubusercontent.com/1072425/36002746-8b57d73c-0d2b-11e8-9f78-95fcb0f550e0.png)

Wrong behaviour (.flickity-slider `translateX` at the middle, and every .carousel-cell `left` positions on `0px`)
-
![image](https://user-images.githubusercontent.com/1072425/36001829-14543dfe-0d28-11e8-9f97-9b4d7bad4123.png)

![image](https://user-images.githubusercontent.com/1072425/36001787-e729b1ce-0d27-11e8-88f0-f35a4ada805f.png)

I hope you can reproduce the problem and understand what's going on!

Thank you,

**Comment by desandro** [comment]
Looks like you can resolve this with `"imagesLoaded": true`. See https://flickity.metafizzy.co/options.html#imagesloaded
