### ISSUE TITLE
Multiple carousels on a page with custom Prev/Next controls

### ISSUE THREAD

**Issue by frazerf** [metafizzy/flickity#692]
I've got two carousels on a page and thanks to this codepen - https://codepen.io/desandro/pen/60e8036ccbe34f8375d7b1021995dad8/ - I've been able to make sure both work independently of each other using vanilla JS. However now I'm trying to tie in some custom controls (Next/Prev) using this method - 

`
var previousButton = document.querySelector('.feature-image-carousel-controls__nextprev--prev'     previousButton.addEventListener('click', function () {  
    featureImageCarousel.previous()  
})
`

But it's not really playing ball. Is it possible to have custom controls on multiple carousels?

**Comment by desandro** [comment]
Sure thing. You'll need to trigger previous/next on both Flickity instances

``` js
var previousButton = document.querySelector('.previous-button');
previousButton.addEventListener('click', function () {
  flkty1.previous();
  flkty2.previous();
});

var nextButton = document.querySelector('.next-button');
nextButton.addEventListener('click', function () {
  flkty1.next();
  flkty2.next();
});
```

**Comment by frazerf** [comment]
Hey @desandro , Thanks for getting back to me so quickly!

Yeah I have something similar to that but the next/prev buttons still control all of of carousels on a page. Here's a fiddle of my problem - https://jsfiddle.net/3Lebtnm0/

Am I doing something wrong? Do I need to put the button triggers inside a function?

**Comment by desandro** [comment]
You were close. You need to change `document.querySelector` (which selects the first element it finds) to `container.querySelector` (which will select the correct button in the container). See demo https://jsfiddle.net/5g4ch0g9/

**Comment by frazerf** [comment]
That makes complete sense. Thanks again @desandro !

**Comment by desandro** [comment]
@differenceclouds You can wrap each instance in its own function. See http://fizzy.school/un-repeat-with-functions

**Comment by patrulea** [comment]
> 
> 
> Cool, thanks for the hint. Got it working with something like below. lots of `$(this).find(...)`
> 
> ```
> $('.gallery').each( function() {
>   var $carousel = $( this ).find('.gallery-carousel').flickity({
> 
>   });
>   var flkty = $carousel.data('flickity');
> 
>   var $cellButtonGroup = $(this).find('.button-group');
>   var $cellButtons = $cellButtonGroup.find('.button');
> 
> 
>   $(this).find('.button--previous').on( 'click', function() {
>     $carousel.flickity('previous');
>   });
>   $(this).find('.button--next').on( 'click', function() {
>     $carousel.flickity('next');
>   });
> });
> ```

You saved my life.
