### ISSUE TITLE
Correctly handle multiple "selected" elements

### ISSUE THREAD

**Issue by bfred-it** [metafizzy/flickity#694]
Having multiple items in view, especially with `contain: true`, has two unwanted behaviors:

1. Flickity lets you click from 1 to 2, but nothing happens (caused by `contain`)
2. There's a selected class, but it only applies to one element (always happens)

You can see both here:

![a](https://user-images.githubusercontent.com/1402241/36356563-738a06fe-1526-11e8-82ec-1e361368baf9.gif)

**Test case:** https://codepen.io/anon/pen/dddYvZ

Sadly I had to switch to iDangerous Swiper because it behaves how I want (for `2` it still applies one class, but it never reaches the end, so `.active + .slide + .slide` lets me select the last visible slide). Its demo http://idangero.us/swiper/demos/110-slides-per-view.html

**Comment by desandro** [comment]
Thanks for reporting this issue. See https://github.com/metafizzy/flickity/issues/289#issuecomment-157488885
