### ISSUE TITLE
freeScroll with single cell

### ISSUE THREAD

**Issue by hirasso** [metafizzy/flickity#696]
Hi there, just wanted to ask if this approach is right for a single-line nested nav bar, that should be scrollable, if it's contents exceed the available width:

https://codepen.io/hirasso/pen/ddqrQb

(if `freeScroll` is set to true, but there is only one element that already is wider then the Flickity wrapper, it's not possible to scroll to the very right)

**Comment by desandro** [comment]
Hello! 

I feel the best solution is to add a cell for each button, rather than keeping all the buttons in a single cell.

The first carousel does not scroll because it only has one cell. There is nothing to scroll to. The second one works because it has a second cell to scroll to.

**Comment by hirasso** [comment]
Hi @desandro, thanks for your reply. 

> I feel the best solution is to add a cell for each button, rather than keeping all the buttons in a single cell.

You are right, but in my case, I would prefer nesting in order to produce semantically meaningful code. There will also be some elements outside of the `nav`, that should also be part of the Flickity instance.

> The first carousel does not scroll because it only has one cell. There is nothing to scroll to.

Intuitively, I would presume that `freeScroll` would enable me to freely scroll to the end of the content of a Flickity slider, also if it's only one element that overlaps to the right. Don't you think so?

As always, thanks for your stellar support.

**Comment by nicooprat** [comment]
I'm having the same problem. I'm using flickity as a `overflow-x: auto` replacement with only one cell. I can't subdivide my elements in multiple children. Looks like Flickity won't let me scroll if the cell is larger than the viewport. Here's an example:

https://codepen.io/nicooprat/pen/mXYzeo

I agree with OP, `freeScroll` should let us scroll in this case. I tried a few different configurations (like adding `contain: true`, without success. Any idea?

Thanks.

**Comment by hirasso** [comment]
...would also make a lot of sense, if you would have an image gallery that contained images that would fit to the height of the gallery and have an automatic width (that can sometimes overflow the gallery container to the right).

**Comment by desandro** [comment]
> I'm using flickity as a overflow-x: auto replacement with only one cell.

Flickity is not designed for this use case. I recommend you stick with `overflow-x: auto` CSS.

**Comment by nicolas-cusan** [comment]
For anyone having this issue. I solved it by adding a placeholder div at the end of the slides (I had an issue with my last slide being wider than the slider itself) as a "fake slide" of sorts with the styles:

```css
.placeholder {
  width: 1px;
  height: 100%; /* or whatever souits your needs */
  margin-left: -1px
}
```

This will trick Flickty into thinking there are two slides and work as a replacement for `overflow-x: auto` with no visuall impact.
