### ISSUE TITLE
namespace in flickity

### ISSUE THREAD

**Issue by sably** [metafizzy/flickity#697]
in this section :    
    var $gallery = $('.gallery').flickity({
            prevNextButtons: false,
            wrapAround : true,
            pageDots: false
        }); 
$gallery.on( 'select.flickity', function() {// do somthing }

'select.flickity' where define in flickity plugine?

**Comment by desandro** [comment]
Hello! Flickity's [jQuery events are namespaced here](https://github.com/metafizzy/flickity/blob/v2.0.10/js/flickity.js#L486).

**Comment by sably** [comment]
ok boy
