### ISSUE TITLE
cellSelector with watchCSS/destroy messes DOM ordering

### ISSUE THREAD

**Issue by shadysamir** [metafizzy/flickity#698]
When using cellSelector, flickity collects dom objects matching the selector inside a viewport div and places itself at the end of the container element. This messes up the DOM order of the cells. Once used with watchCSS or destory the DOM order of the cells is messed up when flickity is removed for media queries or when destroy method is used.
**Test case:** https://codepen.io/anon/pen/QQzByX

**Comment by desandro** [comment]
Yes, this is indeed a bug. Flickity will not keep track of element ordering of the cells before being initialized. One way to resolve this is to track the order before Flickity initialized and re-set it after Flickity is deactivated. You could use the undocumented events `activate` and `deactivate`

``` js
// requires vanilla JS instance
flkty.on( 'activate', function() {});
flkty.on( 'deactivate', function() {});
```

**Comment by shadysamir** [comment]
Thanks @desandro. Does `activate` fire before or after activation?

**Comment by desandro** [comment]
`activate` _is_ the activation event. But if you add an event listener, the listener should be triggered after the other behaviors have been activated.

**Comment by desandro** [comment]
See #493 for a `ready` event feature request.

**Comment by shadysamir** [comment]
@desandro I tried the activate event using the code below, it never fires while flickity is activated. I'm using 2.1.0

``` javascript
$(document).ready(function () {
    $carousel = $('.featured-stories').flickity({
      cellSelector: '.flick',
      contain: true,
      watchCSS: true,
      rightToLeft: true,
      prevNextButtons: false
    });
    $carousel.on('activate.flickity', function() {
      console.log('active');
    });
  });
```

**Comment by desandro** [comment]
`activate` will only work with vanilla JS. You can listen for it: 

``` js
$carousel.flickity( 'on', 'activate', function() {
  console.log('active');
});
```

I'll be releasing v2.1.0 in the next couple days with a new `ready` event that resolves this. Keep an eye on #493 for a better solution.

**Comment by shadysamir** [comment]
@desandro great. This worked. Thanks.
