### ISSUE TITLE
Using custom path data for arrows with arrowShape

### ISSUE THREAD

**Issue by joepagan** [metafizzy/flickity#699]
Hey,

Thanks for making flickity btw, been an isotope user for some time, love it.

I am having an issue where I want to use a custom arrow, I am pasting in some path data, but, the `svg` element is square, but, the path element within it is not:

The following icon has been put in a new 100x100 artboard in illustrator and pathdata has been extracted from there:
**Test case:** https://codepen.io/joepagan/pen/wyRbYx

Hovering over the `svg` element:
![image](https://user-images.githubusercontent.com/2337910/36796531-a5435122-1c9d-11e8-8352-c70ea1877bb7.png)

Hovering over the `path` element:
![image](https://user-images.githubusercontent.com/2337910/36796552-b0424362-1c9d-11e8-952a-f835819d4046.png)

When this happens, the path is not vertical aligned in the middle of the svg element & can make the next/prev icons off-center:
![image](https://user-images.githubusercontent.com/2337910/36796570-bc363516-1c9d-11e8-9716-b058c948aebb.png)

[Docs page for reference](https://flickity.metafizzy.co/options.html#arrowshape).

I thought a way to prevent this would be to make the path have a 1:1 ratio to the 100x100 viewbox, I have tried creating a 100x100 artboard in illustrator & stretching the icon to fit these dimensions, though it ends up being cropped:
https://codepen.io/joepagan/pen/jZXjGO

What is the preferred way to add path data for this option? How can I prevent this from happening?

**Comment by desandro** [comment]
Hi! Looks like there might be some leftover `transform` attributes at work in your SVG code.

I've found the best SVG is generated from Illustrator with **File > Export > Export for Screens**.

![screen shot 2018-03-02 at 11 16 31 am](https://user-images.githubusercontent.com/85566/36909482-131a06d6-1e0c-11e8-830a-c7ea19162ee2.png)

Here are the settings I use (button next to iOS, Android)

![screen shot 2018-03-02 at 11 23 24 am](https://user-images.githubusercontent.com/85566/36909525-343a9b14-1e0c-11e8-9857-ab27b05cae63.png)

**Comment by joepagan** [comment]
FFS! I have been copying the code straight from illustrator/sketch and picking out the path data in a code editor.

I tried your svg settings, they work, but, any other settings work also! 

I guess there is just some extra magic that happens with export for screens.

Thanks for the suggestion. 👍

**Comment by iamricky** [comment]
I'm having cross-browser issues with `arrowShape`, specifically on IE11.

**Comment by jaseography** [comment]
Is it possible to apply a new arrowshape to an asNavFor carousel?

**Comment by Asef00** [comment]
For those who can't access Adobe illustrator like me, I suggest using online SVG [editor](https://boxy-svg.com/) to center the path element.
