### ISSUE TITLE
Select always the first slide (in viewport)

### ISSUE THREAD

**Issue by cornerholland** [metafizzy/flickity#700]
I have a normal flickity slider, but i want a cool effect.
It would be great that if you click on the prev/next button or drag the slider the first slide goes to the background with a transform. I have no idea how to do this, can you help me out.

Here is an example.
http://themenectar.com/demo/salient-business-2/

Thanks a lot!

**Comment by desandro** [comment]
Hello! [Flickity transformer](https://github.com/elcontraption/flickity-transformer) is a good way to achieve this kind of effect.

**Comment by cornerholland** [comment]
Thanks a lot for your reaction! Im going to work with it.

**Comment by cornerholland** [comment]
I'm sorry but im am new to jQuery, javascript (i know some basics but thats it).
I understand Flickity transformer but, i have no idea to add that effect only for the first slide.

Do you have any ideas?

Thanks!

**Comment by desandro** [comment]
This kind of behavior requires some familiarity with JavaScript. Sorry there is no option to automatically set up this behavior.

Try taking a look at the [scroll event demos](https://flickity.metafizzy.co/events.html#scroll) to see how these kind of effects are achieved.
