### ISSUE TITLE
Flickity with video tags

### ISSUE THREAD

**Issue by jmharveys** [metafizzy/flickity#705]
Just wondering if it's me, but if I make a Flickity with videos tags, when the user drag to the next slide it's starting the video right away. Is there a work around or a option to avoid this?!

Thanks

**Comment by desandro** [comment]
There is a browser bug with autoplaying videos. See #674

Otherwise, could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
