### ISSUE TITLE
asNavFor + IsInstant

### ISSUE THREAD

**Issue by virgo79** [metafizzy/flickity#706]
Is there a way to implement `asNavFor` together with the `isInstant` method?

I'm using two flickity sliders where the second one is connected to the first one throught the `asNavFor` option.

Would be very nice having the ability to jump directly to the requested slide when a user click on a slide in the second slider, instead of wait for the a long animation with all slides that scroll horizontally. 

the api method `selectCell` has this very useful option through the `isInstant` parameter.

I think this would improve the user experience, expecially when the sliders has many slides.

**Comment by desandro** [comment]
Sure thing. You can achieve this behavior by overwriting `onNavStaticClick` method. See demo https://codepen.io/desandro/pen/jzEOZq?editors=1010

``` js
var mainFlkty = new Flickity('.carousel-main');

var navFlkty = new Flickity( '.carousel-nav', {
  asNavFor: '.carousel-main',
  contain: true,
  pageDots: false,
});

// overwrite method to select instant
navFlkty.onNavStaticClick = function( event, pointer, cellElement, cellIndex ) {
  if ( typeof cellIndex == 'number' ) {
    this.navCompanion.selectCell( cellIndex, false, true );
  }
};
```

**Comment by virgo79** [comment]
Hi Dave,
thank you so much! This works perfectly.
