### ISSUE TITLE
Progress of autoplay

### ISSUE THREAD

**Issue by Moorst** [metafizzy/flickity#710]
Is it possible to detect the current progress of a slide when autoplay is enabled? I'd like to have an indicator to show how long is left on the current slide before it automatically transitions, much like this;

https://codepen.io/fjacobi/pen/mVJpma

I intend to use the pause on hover to it would need to take this into consideration.

I've had a good look through the documentation, existing issues & codepen but can't find any reference.

Thanks,

**Comment by yaodingyd** [comment]
You can easily swap out all slick's API with flickity's since they are almost the same.

[https://codepen.io/earthmount/pen/xWVxQV](https://codepen.io/earthmount/pen/xWVxQV)

**Comment by nevnein** [comment]
I needed something similar and converted that example to use Flickity and vanilla JS, sharing it in case anyone stumbles here.

[https://codepen.io/nevnein/pen/NBWdwb](https://codepen.io/nevnein/pen/NBWdwb)

**Comment by thexpand** [comment]
I am using Flickity in a React project. I came up with a similar solution like @nevnein's, but I'm using https://www.npmjs.com/package/react-countup to handle all the logic for the progress. Thanks for the idea, @nevnein!
