### ISSUE TITLE
Gridder & Flickity: Flickity won't reinitialize once gridder content has loaded.

### ISSUE THREAD

**Issue by tylerjordanp724** [metafizzy/flickity#711]
Hi!

I'm building a site that contains hidden content within a grid. When you click on an image, the expanded content from that grid slides down and contains some text and a slideshow (using flickity). My only issue is that when the content expands, for some reason the flickity slider won't animate proplerly. I do have other instances of flickity throughout the site that are working properly, so  I'm assuming that in this particular case, the slideshow needs to be re-initialized, but I'm not 100% sure. Any help would be greatly appreciated. Thanks!

**Test case:** http://codepen.io/desandro/pen/azqbop

**Comment by desandro** [comment]
>  When you click on an image, the expanded content from that grid slides down and contains some text and a slideshow

Thanks for reporting this issue. You'll have to resize Flickity once it is un-hidden. You can do this with the [`resize` method](https://flickity.metafizzy.co/api.html#resize).

``` js
// jQuery
$carousel.flickity('resize')
// vanilla JS
flkty.resize()
```

> If Flickity is initialized when hidden, like within a tab, trigger resize after it is shown so cells are properly measured and positioned.

See demo https://codepen.io/desandro/pen/eNvdoo

**Comment by tylerjordanp724** [comment]
@desandro Thank you so much for getting back to me on this issue! I did try to trigger 'resize', but the slider still won't animate. Here's a snippet of what I'm working on if that helps:

`var $carousel = $('.gallery'), 
function grid() {
	$('.gridder').gridderExpander({
		scroll: false,
        animationSpeed: 400,
        showNav: true,
        onStart: function(){
            //Gridder Inititialized
            $carousel.flickity('resize');
           
        }
	});
}
`
also, for your reference,  here is a link to the gridder plugin i'm using: https://github.com/oriongunning/gridder

**Comment by desandro** [comment]
Hmm, maybe `onContent` is the correct event option to use here.

**Comment by tylerjordanp724** [comment]
@desandro Haha. I thought the same thing too so I tried it out, but unfortunately that produces the same result. It's weird because I don't get an error saying that flickity can't be initialized, but when I click the arrows, it just doesn't move.

**Comment by desandro** [comment]
Gridder may not have the correct events for Flickity to be used in it. Sorry I can't help more here.

**Comment by tylerjordanp724** [comment]
@desandro Ok, no worries. I'll take another look at it myself or I may just have to use a different slideshow, but thanks for all your help. Much appreciated!
