### ISSUE TITLE
autoPlay Instant option

### ISSUE THREAD

**Issue by homerjam** [metafizzy/flickity#712]
Hi @desandro 

I may be able to work on a PR for this - would it be something you'd consider?

Basically I'd like the auto play behaviour to be instant as it is possible with next/previous using the API.

Thanks!
James

**Comment by desandro** [comment]
You can hack this feature by adding this code:

``` js
Flickity.Player.prototype.tick = function() {
  // do not tick if not playing
  if ( this.state != 'playing' ) {
    return;
  }

  var time = this.parent.options.autoPlay;
  // default to 3 seconds
  time = typeof time == 'number' ? time : 3000;
  var _this = this;
  this.clear();
  this.timeout = setTimeout( function() {
    _this.parent.next( true, true );
    _this.tick();
  }, time );
};
```

See demo https://codepen.io/desandro/pen/6acdefb2b4fec682efc14f8ed90a5adc/

---

**Add a 👍  reaction** to this issue if you would like to see this feature properly added to Flickity. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by desandro** [comment]
Looks like this feature request hasn't received much attention. Closing
