### ISSUE TITLE
images cut-off when multiple flickity carousels are used in one page

### ISSUE THREAD

**Issue by tyte** [metafizzy/flickity#713]
Hello!
I use multiple (more than 20 :)) flickity carousels in one page. First couple of carousels are showing images in whole, but as I scroll down, the images are cut-off. As soon as I resize the window just a little bit, everything is being shown as it should.

Below is an example of how the cut-off image looks
![fireshot capture 047 - maria angquist klyvare - http___new mariaklyvare se_](https://user-images.githubusercontent.com/3532176/37401841-be6b4c44-2789-11e8-8dbf-441679f64555.jpg)

Do you know what kind of problem it is and how I could solve it?

**Comment by yaodingyd** [comment]
Are you using `imagesLoaded: true` for all instances?

**Comment by tyte** [comment]
No, I am not using it. Would it help?

**Comment by yaodingyd** [comment]
@tyte  yes. [check out official guides on this](https://flickity.metafizzy.co/options.html#imagesloaded)

**Comment by tyte** [comment]
It worked. Thank you!
