### ISSUE TITLE
display a timer for flickity autoplay duration

### ISSUE THREAD

**Issue by riiccardo** [metafizzy/flickity#714]
i dont have any codpen but 

my mean show timer (progress) for each slide duration autoPlay option

**Comment by riiccardo** [comment]
sry found it in #710 

 but dont have other way to create this ?

**Comment by yaodingyd** [comment]
[https://codepen.io/earthmount/pen/xWVxQV](https://codepen.io/earthmount/pen/xWVxQV)

**Comment by desandro** [comment]
Let's keep discussion in #710
