### ISSUE TITLE
Releasing drag over disabled button does not release slider

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#716]
See demo https://codepen.io/desandro/pen/4560024fbcab18c9425b2983c999e051/

Try dragging the slider, moving the cursor over a disabled button, then releasing the mouse button. The slider should be released.

**Comment by isnur** [comment]
https://codepen.io/isnur/pen/bvXRYx

/* prevent disabled button from capturing pointer up event. #716 */
pointer-events: none;

this make the link can be click in first or last carousel-cell

**Comment by desandro** [comment]
@isnur I believe the issue may be using `http` for links. See with `https` https://codepen.io/desandro/pen/b0c03d76d9342d190efe7d9a76f09b82/

**Comment by isnur** [comment]
@desandro thanks for your response.
I mean the link is should be can not click in the flickity-button.
![image](https://user-images.githubusercontent.com/18082199/38823376-78a06b84-41d0-11e8-8c1f-93ba3204e8d5.png)


I set pointer-events to unset
![image](https://user-images.githubusercontent.com/18082199/38823402-8bd94eb4-41d0-11e8-84d3-01f8e9467cdb.png)
.
