### ISSUE TITLE
Zoom Thumbnail on Hover?

### ISSUE THREAD

**Issue by pertrai1** [metafizzy/flickity#717]
Hi, I was wondering if there are any built in options for being able to zoom a thumbnail on hover? I have been playing around with extra CSS but have not found any good solutions yet. Very interested to see if anyone else has done such a thing with example(s).

**Comment by yaodingyd** [comment]
IMO you can only use `transform: scale` on your flickity cells as changing cell width would change cell's position too.

**Comment by pertrai1** [comment]
@yaodingyd I have been working with `transform: scale` but it get cropped by the flickity-viewport.

**Comment by yaodingyd** [comment]
You can do it like this: [demo](https://codepen.io/earthmount/pen/rdMvzX)

If you are not satisfied with this solution, check out #665(essentially your issues are the same) and this [comment](https://github.com/metafizzy/flickity/issues/665#issuecomment-373168027)

**Comment by pertrai1** [comment]
@yaodingyd perfect solution you have supplied. 🥇
