### ISSUE TITLE
Vertical scroll within a slide

### ISSUE THREAD

**Issue by dmegatool** [metafizzy/flickity#719]
I want to scroll within a slide (overlfow-y content) while keeping the flickity viewport height fixed. It works on desktop devices but on touch devices I can't drag... Test case is the wrapAround example with some lorem ipsum and overflow-y:scoll applied. I don't know whats breaking it. 

Is this possible ? I can do it with Slick carousel but I would rather use Flickity to be honest... .

**Test case:** https://codepen.io/dmegatool/pen/jzVjem

**Comment by desandro** [comment]
I think the only way to do this is by disabling draggable: `draggable: false`.

**Comment by dmegatool** [comment]
Aww what a shame. I had the impression that it was pretty close as you can move it around. The slides dont change consistantly though... and it's freaking hard to do! (doable if you swipe far&fast). 

I'll stay on Slick for that project than. I miss the volicity though D: 
Thx for the answer.

**Comment by mgsmith57** [comment]
@dmegatool  Adding 

```
.carousel-cell {
 touch-action: pan-y;
}
```
should fix the issue 

https://codepen.io/anon/pen/vjLaqw

**Comment by ThangaBalajiS** [comment]
> @dmegatool Adding
> 
> ```
> .carousel-cell {
>  touch-action: pan-y;
> }
> ```
> 
> should fix the issue
> 
> https://codepen.io/anon/pen/vjLaqw

This Worked! Thanks.
