### ISSUE TITLE
PointerMove stops when using touch

### ISSUE THREAD

**Issue by podenphant** [metafizzy/flickity#723]
Hi,

PointerMove is triggered on every move of the mouse. As expected.
When I move a touchpoint the PointerMove event is fired from 5 to 20 times seemingly depending on how far or how fast the touchpoint is moving.

I'd expect PointerMove to behave the same way when using touch as for mouse events.
Is this by design or a bug?

Check this pen:
https://codepen.io/anon/pen/JLrgdR

Regards
Kristian

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. I wasn't able to reproduce this issue in iOS Safari or Chrome 65 on iOS, looking at the [Events demo](https://flickity.metafizzy.co/events.html#events-demo). `pointerMove` and `dragMove` both were triggering with every movement, without duplication.

Are you saying that `pointerMove` is being triggered for the same movement?

**Comment by podenphant** [comment]
Thank you for you response.
I've updated the pen to clarify the issue (although the issue is still there on the original cells). 
https://codepen.io/anon/pen/JLrgdR

It occurs when touch-dragging vertically within a cell.
If you drag vertically (using touch) for a short while - then no further PointerMove events are fired.

If you start dragging horizontally and then drag vertically it behaves as expected.

If you still can't reproduce the issue I'll see if I can produce a short screen capture.

**Comment by desandro** [comment]
Ah! Thanks for clearing that up. I'll have to take another look.
