### ISSUE TITLE
Is it possible to have active slide with different width?

### ISSUE THREAD

**Issue by nicolay-zlobin** [metafizzy/flickity#726]
Hello! We need slider with centered active slide always bigger than others like that:

![screen shot 2018-03-28 at 18 46 50](https://user-images.githubusercontent.com/25667028/38040582-7e66cd6e-32b8-11e8-9a53-8f4a0a1f66c7.png)

Is it possible to implement this way?

**Comment by desandro** [comment]
After re-sizing cells, you should trigger [`reposition`](https://flickity.metafizzy.co/api.html#reposition). You could do this on `change` event.

``` js
var flkty = new Flickity('.carousel');
flkty.on( 'change', flkty.reposition );
```

See demo https://codepen.io/desandro/pen/64a4bafd54dbe9b28ae949de6140746e/

Unfortunately, triggering `reposition` will snap the slider to the selected cell, stopping animation. You'd have to hack Flickity's internal code to get around this.
