### ISSUE TITLE
watchCSS breaks dragging if browser is resized

### ISSUE THREAD

**Issue by hirasso** [metafizzy/flickity#729]
Hey! I have a problem with watchCSS: My slider is set to only be active if the browser window is smaller then a certain size. When visiting the page directly with the small browser size, the slider works just fine. But when I resize the browser so that the slider gets disabled and after that make it small again, the dragging on the slider is not working anymore. Same if I visit the page directly in a large browser window and then make the window smaller until Flickity is activated. The prevNextButtons and pageDots navigations keep working.

**Test case:** https://codepen.io/hirasso/pen/PReZGN

**Comment by desandro** [comment]
Thanks for reporting this bug! Looks like I missed changing an event with the last release. I'll have a fix in the next release. Until then, you can use Flickity v2.1.1 with `watchCSS` by adding this code:

``` js
Flickity.prototype._createDrag = function() {
  this.on( 'activate', this.onActivateDrag );
  this.on( 'uiChange', this._uiChangeDrag );
  this.on( 'childUIPointerDown', this._childUIPointerDownDrag );
  this.on( 'deactivate', this.onDeactivateDrag );
  this.on( 'cellChange', this.updateDraggable );
};
```

**Comment by hirasso** [comment]
@desandro Thanks for the fast response and the hotfix, works just fine!

**Comment by desandro** [comment]
v2.1.2 has been released with this fix added. Thanks again for reporting this!

**Comment by leran** [comment]
i still have this problem, flickity v2.1.2 
and some carousel doesn't work until resize window (i use flex-box there)
