### ISSUE TITLE
Flickity not defined while running test cases

### ISSUE THREAD

**Issue by atul-bajpai** [metafizzy/flickity#730]
Hey!
I am trying to write test cases, however, its throwing error as Flickity not defined.
I have verified that the flickity js and css are loading properly.
![image](https://user-images.githubusercontent.com/2909552/38177871-0163326a-3625-11e8-967b-88e2aac55c3b.png)
![image](https://user-images.githubusercontent.com/2909552/38177882-1638a292-3625-11e8-8a76-238163463cdb.png)

Please help

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
