### ISSUE TITLE
v2.1.1 - Dragging doesn't work on earlier FF versions.

### ISSUE THREAD

**Issue by xcartmods** [metafizzy/flickity#731]
With v2.1.1, dragging no longer works on earlier Firefox versions (in my case FF v56.02 / Win7).
If I revert back to v2.0.11, dragging works again.
You can test on any demo at https://flickity.metafizzy.co/
https://ftp.mozilla.org/pub/firefox/releases/

**Comment by desandro** [comment]
Thanks for reporting this bug. Also reported in desandro/draggabilly#187. I'll have to take a look.
