### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by alexey-saransk** [metafizzy/flickity#732]
-

**Comment by desandro** [comment]
Hello! Thanks for putting together the CodePen. You were close to a solution

+ move `<div class="progress-bar"></div>` into `<div class="carousel-container">`
+ Then you can select the `.progress-bar` within the loop with `$container.find('.progress-bar')`.

I wrote lessons on Fizzy School about concepts used here: [Un-repeat with functions](http://fizzy.school/un-repeat-with-functions), [Simplify selectors](http://fizzy.school/simplify-selectors)

See demo https://codepen.io/desandro/pen/25bea8ce84fd75a65b0f78e76c0e2139

``` js
$('.carousel-container').each( function( i, container ) {
	var $container = $( container );
	var $carousel = $container.find('.carousel').flickity({
		lazyLoad: 1,
	});
	var flkty = $carousel.data('flickity');
	// update status: 1/3
	var $status = $container.find('.carousel-status');
	$carousel.on( 'change.flickity', updateStatus );
	function updateStatus() {
		var slideNumber = flkty.selectedIndex + 1;
		$status.text( slideNumber + '/' + flkty.slides.length );
	}
	updateStatus();
	// update progress bar
	var $progressBar = $('.progress-bar');
	$carousel.on( 'scroll.flickity', function( event, progress ) {
		progress = Math.max(0, Math.min(1, progress));
		$progressBar.width(progress * 100 + '%');
	});
});
```

**Comment by alexey-saransk** [comment]
No. I don't think you understood me. A certain carousel should work with a certain progress bar. Not all together.  Each progress bar should respond only to its own carousel.
