### ISSUE TITLE
Changing wrapAround breaks; cells length undefined

### ISSUE THREAD

**Issue by jakedowns** [metafizzy/flickity#733]
[VERY LOW PRIORITY] I sometimes get an uncaught exception on resize from this method:
https://github.com/metafizzy/flickity/blob/3f5b5fb66ffb0f392852bb6e45b7b8553d6d06e6/dist/flickity.pkgd.js#L1080

https://cl.ly/3D1K0b1y1S15

Context: i have an on.resize handler which enables/disables certain flickity options based on the current window size as part of our responsive implementation design requirements.

This error is not critical, as it does not break execution of flickity. 

Here's a reduced testcase: https://codepen.io/jakedowns/pen/LdgZJR

1. open console and resize browser < 600 (disable wrapAround)
2. resize > 600 (re-enable wrapAround)
3. see exception

Oddly, repeated resizing / toggling beyond that doesn't seem to trigger the uncaught error again:
https://cl.ly/1O3j0e1n0H2Q

`Uncaught TypeError: Cannot read property 'length' of undefined  at Flickity.proto._shiftCells`

**Comment by desandro** [comment]
Thanks for reporting this bug!

We're in a gray area area here. Technically, Flickity only supports setting `wrapAround` on initialization. I haven't implemented or documented a way to change it after initialization. This may be the first time it's been brought up in 3 years.

However, we can resolve this issue by calling `_getWrapShiftCells()` after enabling `wrapAround`. See demo https://codepen.io/desandro/pen/08c8efd52ebc580eb30f61ce23c2aeb0/

---

**Add a 👍  reaction** to this issue if you would ran into this issue. If enough people chime in, I'll consider adding a better API for changing `wrapAround` like this. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by jakedowns** [comment]
thanks for the quick reply, i appreciate the undocumented workaround!

i went with a debounced destroy / full-reinit of the instance on resize since it’s a largely an edge-case and we have lots of options being toggled between our mobile and desktop layout (pesky designers 😜)

thanks again for a great suite of plugins!

**Comment by jakedowns** [comment]
@desandro 

So, a wholesale destroy / re-init isn't great since mobile safari triggers a resize event when the browser chrome shifts sizes during scroll

i could store the currently viewed slide index and use it during re-init to make sure the user's spot isn't lost

but maybe it's better to just update the options and call the updater method you outlined.

do you think there's a particular order of operations I should follow here?:

```
    // here *this* is the flkty instance
    this.options = _.extend(this.options, nextOpts);

    // Likely to change:
    // wrapAround on|off
    // draggable on|off
    // cellAlign left|center
    // prevNextButtons on|off

    this.updateDraggable();
    this.setCellAlign();
    
    setTimeout(()=>{
        this._getWrapShiftCells();
        setTimeout(()=>{
            this.updateSlides();
        },1);
    },1);
```

**Comment by desandro** [comment]
Taking another look at this... Since we need to re-trigger methods that are already triggered in `Flickity.prototype.resize()`, a better solution is to duck punch `.resize()` to add in the options, rather than using a method. See demo https://codepen.io/desandro/pen/5dff02ac5917360d33664b1e02739957/


``` js
// external js: flickity.pkgd.js
var f = new Flickity('.carousel');

// original resize method
var resize = f.resize;
// duck punch resize method with changing options
f.resize = function() {
  if ( !this.isActive ) {
    return;
  }
  
  if(window.innerWidth < 600){
    console.log('mobile-mode');
    this.options.draggable = false;
    this.options.wrapAround = false;
    this.options.cellAlign = 'center';
  }else{
    console.log('desktop-mode');
    this.options.draggable = true;
    this.options.wrapAround = true;
    this.options.cellAlign = 'left';
  }
  // call original method
  resize.call( this );
};
```

**Comment by jakedowns** [comment]
brilliant. thank you. will give this a try on Monday

**Comment by jakedowns** [comment]
@desandro just a quick follow up update: your suggestion worked perfectly. ashamed i didn't think of it myself, haha. thanks again!

**Comment by joshdavenport** [comment]
Sorry to resurrect an old issue @desandro but we're seeing the exact same trace shown in the original report but from a normal flickity initialisation rather than any change to `wrapAround` after a resize.  There is reports that just removing `wrapAround` does prevent the issue, but we'd like to keep it on ideally. Could you think of any likely culprits here?

Init looks like:

```
{
    cellAlign: 'center',
    autoPlay: 2000,
    contain: true,
    pageDots: true,
    wrapAround: true,
    prevNextButtons: true,
    lazyLoad: 1,
    selectedAttraction: 0.2,
    friction: 1
}
```

And there's also an `asNavFor` in play:

```
{
    asNavFor: '.carousel-main',
    cellAlign: 'left',
    contain: true,
    pageDots: false,
    prevNextButtons: false,
    lazyLoad: 1,
    selectedAttraction: 0.2,
    friction: 1
}
```

**Comment by desandro** [comment]
@joshdavenport  If you're changing `wrapAround` after inititalizing, you'll likely need to [destroy](https://flickity.metafizzy.co/api.html#destroy) and re-initialize

**Comment by joshdavenport** [comment]
Unfortunately not, we were seeing this from a normal flickity initialisation. Let me see if I can recover the issue in our team, we may have found a workaround.

**Comment by obliviga** [comment]
> Unfortunately not, we were seeing this from a normal flickity initialisation. Let me see if I can recover the issue in our team, we may have found a workaround.

Any update? @joshdavenport
