### ISSUE TITLE
autoPlay stops working as soon as you interact with the carousel

### ISSUE THREAD

**Issue by romain-granai** [metafizzy/flickity#734]
I have played with the pauseAutoPlayOnHover: true/false, but I don't think it s the issue.
As soon as you interact with the carousel (clicking next or prev, or grabing to select the next/prev slide), the slider stops to autoplay. Why does the slider stops to work even if I'm not hovering it.

I've seen a similar issue but no proper answer to fixe that. Don't really get the purpose of completely stop the carousel autoplay.

Thanks

**Comment by clody69** [comment]
I have a similar issue. On mobile the autoplay stops even by just scrolling the page in case my finger starts the vertical scrolling gesture from the carousel. I think in this case I'm only trying to scroll the page and not necessarily interact with the carousel. 
On mobile, the autoplay should stop only if I scroll horizontally the carousel. In this way using the dragThreshold parameter I have a way to decide how sensitive it should be.

**Comment by wwdes** [comment]
as clody69 points out, sliders stop playing when users touch-scrolls the page. Slides usually take up most of the screen on a mobile device, which means that autoplay is vertually nonexisten for these devices. This seems like a "desktop-first" design problem.
