### ISSUE TITLE
Slides Don't Advance in iOS 7

### ISSUE THREAD

**Issue by SunnysGlimpse** [metafizzy/flickity#735]
We were just testing transitioning from Slack to Flickity and were going to purchase a Commercial Team license but in our testing, we've found it does not work whatsoever in iOS 7.1.2. I'm guessing the same goes for any device running iOS 7.

We will be using it for a large website and have a very significant audience of people still running iOS 7.

The page dots will actually advance and the left toggle will enable after clicking the right arrow but no actual slides change. The same goes for any and all of the demos on Flickity.metafizz.co--none of them actually advance the slides.

If I look at the groupCells demo, for example, the "selected yellow" actually jumps to the partial bit of slide 4 showing but the slides themselves never advance.

Any ideas? We were extremely excited to move to Flickity due to the freeScroll and simplicity of it but this is a show-stopper for us, unfortunately.

Thank you!
Curtis

**Comment by SunnysGlimpse** [comment]
So when viewing the Events demo page:
https://flickity.metafizzy.co/events.html

The iOS 7 devices are sometimes registering a "pointerUp" and "pointerDown" event when clicking the arrows, or actually swiping. When swiping, there are a lot of "pointerMove" events.

On the newer iOS devices, these "pointer" events are not registered. There are "dragMove and dragEnd on the newer iOS.

The events "select" and "selected cell 2" and "change and "changed to cell 2" and "settle" "settled at cell 2" will all show when clicking the arrow, however it is still on Cell 1. The same goes with any further clicking.

As I mentioned above, other things advance like selected cell color, pagedots, enabling/disabling of arrows, etc.

**Comment by desandro** [comment]
[Flickity v2 does not support iOS 7.](https://flickity.metafizzy.co/extras.html#browser-support) You can try [Flickity v1](https://flickity.metafizzy.co/v1)

**Comment by SunnysGlimpse** [comment]
Thanks for the quick response Desandro. We'll give that version a try.

What's the difference between v1 and v2? And why was the support for iOS 7 dropped?

We had over 15,000 users visit our website last month using a version of iOS 7.

**Comment by SunnysGlimpse** [comment]
Well, what a major disappointing! v1 doesn't work with our newer iOS devices. freeScroll doesn't work and swiping to change slides is a challenge. 

We were so looking forward to using Flickity.  :(

**Comment by desandro** [comment]
Read about changed under [upgrading from v1](https://flickity.metafizzy.co/extras.html#upgrading-from-v1)

v1 works just fine for me on iOS 11
