### ISSUE TITLE
WrapAround and GroupCells displays wierd for certain sizes

### ISSUE THREAD

**Issue by JaieParker** [metafizzy/flickity#736]
Hey as per the code pen below, I see lots of space. It looks like the absolute positioning is not quite right when using these two options together. I sometimes see half "carousel-cell" when there are a limited amount to display and I can't click next to see it fully.

https://codepen.io/JaieParker/pen/ZxwWQb

Is there another setting or css or something I can do to fix this?

Cheers
Jaie

**Comment by JaieParker** [comment]
Setting a max-width seems to improve this but there can still be lots of padding between the cells, is there a way around this?
https://codepen.io/JaieParker/pen/gedKKw

Cheers
Jaie

**Comment by desandro** [comment]
Could this be caused by the scroll-bar? Try adding CSS:

``` css
html { overflow-y: scroll; }
```

**Comment by JaieParker** [comment]
Found setting 'cellAlign': 'left' was required to fix this.

Thanks for the response
