### ISSUE TITLE
Links on slides won't open on IE 11 when Flickity isn't fully in viewport

### ISSUE THREAD

**Issue by martinhellwagner** [metafizzy/flickity#738]
We're running into an issue where links on slides won't open upon click in IE 11 (no other browser has trouble with this). This seems to be reproducible only when Flickity isn't fully in the viewport.

Is it possible that focus isn't correctly set on these slides? Any workaround or solution to this?

**Comment by desandro** [comment]
Thanks for reporting this issue. I'll have to take a look.
