### ISSUE TITLE
Filtering/Blocking 'select' Events

### ISSUE THREAD

**Issue by Enchiridion** [metafizzy/flickity#739]
Hi, Love flickity!  Switched from slick and haven't looked back.  I'm working on a carousel where the first slide contains a form which needs to be correctly filled out before being allowed to proceed to the next slides.  I have the form logic working, I'm just having issues trying to prevent the carousel slide from being changed using any of the four methods (dragging, arrows, keyboard, dots).

Ideally I'd like to filter the 'select' event so I can dynamically determine whether or now to allow the current slide to be changed.

Test case: https://codepen.io/enchiridion/pen/yKwNbB

The test case handles the arrows and draggablility, but it's not ideal since I'd rather apply a 'disabled' class to the arrows instead so I can style them rather than hiding them entirely.  Same for the page dots, which I don't want to disable at all as I want them to visible at all times.  I can't style using `pointer-events` as I need it to work in IE 10.

**Comment by desandro** [comment]
Thanks for submitting this issue. One solution is to [duck-punch](https://metafizzy.co/blog/duck-punching-prototype/) the `select` method. In this case, we can add a `isLocked` property. If `isLocked`, do not do anything with `select`. See demo https://codepen.io/desandro/pen/jzJMPa

``` js
// duck-punch select method to not change when locked
var select = Flickity.prototype.select;
Flickity.prototype.select = function() {
  if ( this.isLocked ) {
    return;
  }
  select.apply( this, arguments );
};

var $carousel = $('.carousel').flickity();
var flkty = $carousel.data('flickity');

var $lockCheckbox = $('.lock-checkbox').on( 'change', function() {
  flkty.isLocked = $lockCheckbox[0].checked;
  flkty.options.draggable = !flkty.isLocked;
  flkty.updateDraggable();
});
```

**Comment by Enchiridion** [comment]
Thanks! Your monkey patch worked perfectly!
