### ISSUE TITLE
Draggable disabled after switching flickity off and on again

### ISSUE THREAD

**Issue by joshas** [metafizzy/flickity#741]
Using watchCSS example.
Resize window to less than 768px wide, notice that slider is draggable. Now increase window to disable flickity. Finally resize window to <768px again. Now slider is not draggable.

**Test case:** https://codepen.io/anon/pen/VXRoBe

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm already addressing this issue in #729. Fix coming in next release!
