### ISSUE TITLE
Autoplay click nav bug 

### ISSUE THREAD

**Issue by smmaxim** [metafizzy/flickity#746]
Good day!

If autoPlay:true and after click prev || next button autoplay stops working

You can see this in your examples https://flickity.metafizzy.co/options.html

**Comment by desandro** [comment]
This is by design. This allows users to have control over carousel.

If you would to re-start autoPlay you can do so with [player API.](https://flickity.metafizzy.co/api.html#player) Maybe also add a 👍 to #429
