### ISSUE TITLE
padding on caroucel-cell needed when dpr > 1

### ISSUE THREAD

**Issue by filly82** [metafizzy/flickity#748]
on my google pixel 2 (device pixel ratio about 2.5) all of my carousel-cell content is cropped from the left side. i need to set a left padding to see the content, which is hard to find a correct value that works for all pixel ratios (1 for desktop, and 2-3 for mobile phones)

the easiest way to test it is with firefox developer tools and the responsive size tools

![auswahl_017](https://user-images.githubusercontent.com/4948973/39088830-949a2b8a-45b9-11e8-9475-14274b33f562.png)

![auswahl_016](https://user-images.githubusercontent.com/4948973/39088824-74bd65f2-45b9-11e8-9621-b05915f7715d.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by filly82** [comment]
sorry, my fault. it was some css from bootstrap that caused it. should've known and tested it before posting here
