### ISSUE TITLE
show/hide content within carousel-cell, howto adapt height to content

### ISSUE THREAD

**Issue by filly82** [metafizzy/flickity#750]
I have some content within my carousel that I want to show/hide on user interaction, but the content stays hidden because the height of carousel-cell won't adapt to the new height of the content

adaptiveHeight: true won't do it, since it seems to be only triggered when showing a new slide

i did not set any height to the carousel-cell

i know i could do it by myself with javascript but i am not always able to interceipt the show/hide-click

here is an example: https://codepen.io/anon/pen/BxzqZR

is there anything that i missed in the documentation that would fix my problem?

**Comment by desandro** [comment]
Thanks for reporting this issue. [`adaptiveHeight`](https://flickity.metafizzy.co/options.html#adaptiveheight) is for when the heights of cells vary and Flickity will change the height of the carousel to match the selected slide.

For this use, we want to use the [`resize` method](https://flickity.metafizzy.co/api.html#resize), which is useful when we want to change the size of the carousel after change to the carousel has been made. See demo https://codepen.io/desandro/pen/82417cedda90ab3179a544e7ed51dbf0/

``` js
// external js: flickity.pkgd.js

var moreContent = document.querySelector('#morecontent');
var moreLink = document.querySelector('.more-link');

var flkty = new Flickity('.carousel');

var isMoreOpen = false;

moreLink.onclick = function( event ) {
  isMoreOpen = !isMoreOpen;
  moreContent.style.display = isMoreOpen ? 'block' : 'none';
  flkty.resize();
  event.preventDefault();
};
```

[I'm using a state variable concept. Read more on Fizzy School](http://fizzy.school/state-variables)

**Comment by filly82** [comment]
thanks. that is something that helps me. must have overseen that event in the documentation
