### ISSUE TITLE
flickity + materialize Tabs

### ISSUE THREAD

**Issue by garethhorner** [metafizzy/flickity#752]
Hi
Attempting to use Flickity inside Materlize tabs — the number of tabs will increase over time and would like to find a solution which doesn't require me updating the JS each time. 

Test case here — https://codepen.io/anon/pen/gzwEje

The issue being Materialize uses display:none to hide tabs and the tabs themselves are just li items, not button elements. I know I need to apply a resize when the tab is selected but cannot get it working myself. 

*Of note — using this on Wordpress with content of varying heights and fields pulled.

Any help will be massively appreciated
Cheers

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue and providing a reduced test case.

Looking at the CodePen, everything looks to be working. If you initializing Flickity before the Materialize tabs, the Flickity carousels will have proper sizing when shown in a tab.

If you do need to trigger [`resize` method](https://flickity.metafizzy.co/api.html#resize), you can use Materialize's `onShow` option. See demo https://codepen.io/desandro/pen/0eb106f9cfd442d4b96f92ab0e7e46c3

``` js
$('.carousel').flickity({
  // options
});

var $tabs = $('.tabs').tabs({
  onShow: function( tab ) {
    var $carousel = $( tab ).find('.carousel')
    $carousel.flickity('resize');
  },
});
```
