### ISSUE TITLE
Issue with cells not being sized correctly until page resize?

### ISSUE THREAD

**Issue by carlinyuen** [metafizzy/flickity#756]
Hey there! I'm working on figuring out the reduced repro case, but figured I'd post this up first in case you've already seen something similar that you could point me to. I spent about half an hour searching and looking through open and closed issues, but you have a LOT of closed items!

What it looks like when the bug happens
<img width="603" alt="screen shot 2018-04-29 at 8 32 23 am" src="https://user-images.githubusercontent.com/422877/39406663-3fc793ca-4b88-11e8-808e-566ae948e063.png">

What it is supposed to look like and what it changes to once I resize the screen
<img width="563" alt="screen shot 2018-04-29 at 8 32 33 am" src="https://user-images.githubusercontent.com/422877/39406664-3fe3243c-4b88-11e8-97f7-c92109fa33e8.png">

**Comment by carlinyuen** [comment]
Nevermind, fixed it by calling "resize" after a little wait. Thanks!

**Comment by desandro** [comment]
Looks like this could be resolved with [imagesLoaded](https://flickity.metafizzy.co/options.html#imagesloaded)
