### ISSUE TITLE
Different height per slide (cell), not defining the height in CSS (Auto)

### ISSUE THREAD

**Issue by Mysensed** [metafizzy/flickity#758]
How can i use flickity's AdaptiveHeight without definining a set value in the CSS?
My slides contain text and other HTML elements, and i dont want to restrict myself to a set height for every slide.

Kind regards
Sander

**Comment by desandro** [comment]
You can set `min-height` and the let the content determine the size of the cell. See demo https://codepen.io/desandro/pen/b1362c9b518c6cfe080c975e1ab2211d/

**Comment by owenhope** [comment]
Im having the same issue ...

In your example, the flickity-viewport is getting a value of 100px by default, and once it finds a slide that's taller (135px) it adjusts. However whenever I look at my code, my flickity-viewport only has a 

```
element.style {
    touch-action: pan-y;
}
```

Any help much appreciated.

**Comment by desandro** [comment]
@owenhope 
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by Mysensed** [comment]
I have not made much progress on my project yet, but i can confirm the codepen solution worked for me.

However, maybe it is related to the method of initializing. Because your test version uses the HTML set-up, but i wasn't able (yet) to get the Jquery version to work.

**Comment by owenhope** [comment]
@desandro thanks - it will be challenging to replicate my set up as i'm using angular to load the carousel - I suspect it has something to do with that.

@Mysensed I am initializing in the same way you are.. (not jquery, rather angular) but same issue - no height given on flickity-viewport
