### ISSUE TITLE
During load all photo's are shown

### ISSUE THREAD

**Issue by UisgeBeatha436** [metafizzy/flickity#759]
Hi,
During the load of the flickity header slideshow, it initially shows all images, and than start the slideshow. Is that something I can for come? I. other words, all photo's are now first being stacked, the users sees all photo's, and than start the slide show with the first photo.
The code for Flickity:
`<div class="main-carousel" data-flickity='{"imagesLoaded": true, "contain" : true, "percentPosition" : true, "initialIndex" : 2, "wrapAround" : true, "autoPlay": 3000, "setGallerySize": true, "adaptiveHeight": true, "cellSelector": ".carousel-cell"}>`
  .
  .
  foreach - loop for loading images from folder
  .
`</div>`

Thank you!

**Comment by desandro** [comment]
Try using [`lazyLoad`](https://flickity.metafizzy.co/options.html#lazyload) instead of imagesLoaded

**Comment by desandro** [comment]
If you are using lazyLoad then you can remove `"imagesLoaded": true`.

**Comment by UisgeBeatha436** [comment]
Thanks, removed, However no luck.

**Comment by desandro** [comment]
Sorry I cannot personally debug your issue for you.  See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
