### ISSUE TITLE
New created instances don't work properly

### ISSUE THREAD

**Issue by LeoSeyers** [metafizzy/flickity#760]
Hello,
I've been trying to built a simple drop-down layout (for different projects) with a slider nested in each.
I'd like not to instantiate them all to preserve ressources. Basically, each time you click it is supposed to kill the previous instance and create the new one.

My issue is that it's not consistently working, the first instance is correctly created but when I try to create a new on it is failed. But the pagination I've made is working in some cases.
I assume something is wrong the way I've built it and I might need some help.

Here is the the educed test case : https://codepen.io/anon/pen/bMrLgK

Best
Leo

**Comment by desandro** [comment]
Thanks for this issue.

In this accordion widget, we'll have to deactive previous panel and activate a new panel. I like to do this with two separate methods. [See demo on CodePen](https://codepen.io/desandro/pen/0e8892e4057b16b616aa7a507f85d830)

I'm putting a couple lessons from [Fizzy School](http://fizzy.school) in use: [Cache jQuery objects](http://fizzy.school/cache-jquery-objects) and [Simplify selectors](http://fizzy.school/simplify-selectors)

``` js
const $window = $(window);

class App {
  constructor() {
    this.events();
    this.$projects = $('.project');
    this.activeIndex = null;
  }

  events() {
    $(".project__title").on("click", this.onTitleClick.bind(this));
  }

  onTitleClick(e) {
    var index = $(e.target).closest('.project').index();
    this.toggleProject(index);
  }
  
  toggleProject(index) {
    const isNewIndex = index != this.activeIndex;
    this.deactivateProject();
    if (isNewIndex) {
      // activate new project
      this.activateProject(index);
    }
  }
  
  deactivateProject() {
    if (this.activeIndex == null) {
      return;
    }
    const $dropdown = this.$activeProject.find('.project__dropdown');
    $dropdown.slideUp();
    const $carousel = this.$activeProject.find('.carousel');
    $carousel.flickity('destroy');
    // reset flag
    this.activeIndex = null;
  }
  
  activateProject(index) {
    // set properites
    this.activeIndex = index;
    const $project = $( this.$projects[index] );
    this.$activeProject = $project;
    
    const $dropdown = $project.find('.project__dropdown');
    $dropdown.slideDown();
  
    const $carousel = $project.find('.carousel');
    // init Flickity
    $carousel.flickity({
      setGallerySize: false,
      pageDots: false,
      prevNextButtons: false,
      wrapAround: true
    });

    $carousel.focus();
    
    // set slider__total number
    const cellTotal = $carousel.find(".carousel-cell").length;
    $project.find(".slider__total").html(cellTotal);
  
    // change slider__index number    
    const $sliderIndex = $project.find(".slider__index");
    $carousel.on("change.flickity", (e, changeIndex) => {
      $sliderIndex.html(changeIndex + 1);
    });

    // previous/next on staticClick
    $carousel.on("staticClick.flickity", e => {
      var viewportWidth = $window.width();
      var side = viewportWidth / 2;
      var cursorPositionX = e.pageX;
      if (cursorPositionX > side) {
        $carousel.flickity("next");
      } else {
        $carousel.flickity("previous");
      }
    });
  
  }
}
var app = new App();

```

**Comment by LeoSeyers** [comment]
Thanks David for the clarification, it really does help!

**Comment by LeoSeyers** [comment]
Ok I think I got something wrong again, it seems to originate from the prev/next static click part.
Shoud I open a new issue?

In your demo - when you try to open a tab that has already been opened, it goes like crazy when you click on either left or right part of the slider.

**Comment by desandro** [comment]
Try removing event listeners. You're doing a lot with this tab interface, it may be overly complex for what you're trying to achieve. I'll leave that up to you

**Comment by LeoSeyers** [comment]
I've finally managed to do it by using legacy prev/next buttons and setting their css to the whole area since the client want a custom cursor on hovering. Thanks again for your helping hand! :)
