### ISSUE TITLE
Full Bleed: Cell height doesn't change on window resize

### ISSUE THREAD

**Issue by babyPrince** [metafizzy/flickity#761]
@desandro  I've added bg lazy load to the full bleed example (https://codepen.io/desandro/pen/VLrReY) but for some reason cell height doesn't get updated on window resize.

Test Case: https://codepen.io/winteriscoming/pen/XqzRRG 
(resize height)

Am I missing something?

**Comment by desandro** [comment]
Thanks, I'll have to take a look.

**Comment by babyPrince** [comment]
@desandro any update on this?

**Comment by desandro** [comment]
If you remove  initializing in JS, you can let the HTML options work. See demo https://codepen.io/desandro/pen/ec7bd1a4af31daa364d509a252d515ec

**Comment by desandro** [comment]
Yes
