### ISSUE TITLE
Events for fullscreen mode enter/exit?

### ISSUE THREAD

**Issue by winzig** [metafizzy/flickity#762]
Are there (or can there be) events that we can hook into to detect when full screen mode has been entered/exited?

**Comment by desandro** [comment]
Not yet! I'll be adding `fullscreenChange` in the next release. Tracking at metafizzy/flickity-fullscreen#7

**Comment by winzig** [comment]
Great! Thank you.

**Comment by winzig** [comment]
Fixed in https://github.com/metafizzy/flickity-fullscreen/releases/tag/v1.1.0

Thanks!
