### ISSUE TITLE
Remove tap-listener

### ISSUE THREAD

**Issue by desandro** [metafizzy/flickity#764]
From [ftlabs/fastclick](https://github.com/ftlabs/fastclick)

> As of late 2015 most mobile browsers - notably Chrome and Safari - no longer have a 300ms touch delay, so fastclick offers no benefit on newer browsers, and risks introducing bugs into your application.

[tap-listener](https://github.com/metafizzy/tap-listener) was designed to resolve the 300ms delay, like fastclick. Since that's [no longer an issue](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away), tap-listener can be removed and `click` event can be used instead.

**Comment by GospelNerd** [comment]
+1

**Comment by desandro** [comment]
`tap-listener` has been removed with [v2.2.0](https://github.com/metafizzy/flickity/releases/tag/v2.2.0).
