### ISSUE TITLE
Using CSS 'zoom' property makes buttons inoperable

### ISSUE THREAD

**Issue by jugglingcats** [metafizzy/flickity#766]
**Test case:** https://codepen.io/jugglingcats/pen/PeVWMB

I'm trying to resize SVG inside Flickity according to media queries using CSS zoom property on the whole carousel. Everything works great except the right button and dots stop working. If you set the zoom to 101% the buttons still kind of work but there must be a miscalculation somewhere because if the zoom is bigger (or smaller -- I am looking for 80%) the buttons stop working altogether.

What's quite odd is that the buttons still give the appearance of working -- the hover style etc is applied, but it seems the click event becomes unreliable.

Reading some more it seems zoom is maybe not a good idea -- not cross browser compatible. Feel free to ignore/close, but thought worth pointing out anyway!

Thanks

**Comment by desandro** [comment]
Thanks for reporting this issue. This may be resolved in a future update that removes custom `tap` event in favor of browser standard `click` event. #764 

Until then, I recommend not using `zoom`.

**Comment by jugglingcats** [comment]
For anyone else coming across this issue the solution is to use viewBox on your svg and then just set the width and height of the svg element using CSS media queries in the normal way, and it will scale everything inside the svg correctly.
