### ISSUE TITLE
Disabled slideshow view on mobile + lazyloadBackground

### ISSUE THREAD

**Issue by babyPrince** [metafizzy/flickity#767]
Hey there @desandro,
I have a question regarding the watchCSS option with the default example code.
The logic is reversed from min-width to max-width.

My goal is to have the slides appear on top of each other on mobile, and as slideshow on desktop.

https://codepen.io/winteriscoming/pen/VxNXqe

lazyLoad background doesn't fire if the page is loaded from <768px width as content: ''; disables the whole functionality. Vice versa works of course.

Is there a way to achieve this layout and keep lazyLoad background images?

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry, if you want to use Flickity's lazyLoad behavior then Flickity has to be activated. When Flickity is inactive, you'll have to provide another solution. I recommend [lazysizes](https://github.com/aFarkas/lazysizes)

**Comment by babyPrince** [comment]
Thanks for the reply desandro.
Secondary lazy load did the job. Also kinda nice that it has a separate data attribute which could be used for mobile sized files in this scenario :)
