### ISSUE TITLE
Skip slides with prev/next buttons

### ISSUE THREAD

**Issue by babyPrince** [metafizzy/flickity#768]
Hi there,
I can't get my head around a button functionality.

What would be the best way to approach skipping certain slides when pressing prev/next arrow button and go to the one before/after?

Cell 1 and 3 currently have class `.skip` and `display: none;` They are getting a visibility on a different breakpoint, where the carousel has been destroyed and all cells are visible.
If it makes any difference, the skipped cells will always be always 1 an 3.

example:
https://codepen.io/winteriscoming/pen/jxoOVw

Thank you

**Comment by desandro** [comment]
Using `cellSelector` as your demo as is a good technique. Were you able to resolve this?

**Comment by babyPrince** [comment]
At the time I was making the demo, I didn't notice I could use `cellSelector`. 
Works perfectly, as it completely ignores the `.skip` (swipe, drag, click, etc)!
