### ISSUE TITLE
Change Event -- form in slide

### ISSUE THREAD

**Issue by kylekylekyle** [metafizzy/flickity#770]
Hi there @desandro,
I'm using the new Change Event and ran into an issue where I added a form to a slide. On any change within the form -- select, radio, checkbox etc -- it will trigger a Flickity change event. Any way to prevent this?
Example: 
https://codepen.io/kylekylekyle/pen/GdbJdw?editors=1111

Thanks

**Comment by desandro** [comment]
That's for reporting this issue. You can double-check for Flickity `change` events, rather than browser `change` events by checking for `event.namespace == 'flickity'` in the listener.

``` js
$carousel.on( 'change.flickity', function( event, index ) {
  if ( event.namespace == 'flickity' ) {
    console.log( 'Flickity change', index );
  }
});
```

See demo https://codepen.io/desandro/pen/qYePPq/

**Comment by kylekylekyle** [comment]
Works like a charm. Thanks!
