### ISSUE TITLE
On init wrong slide size

### ISSUE THREAD

**Issue by CHEWX** [metafizzy/flickity#771]
https://codepen.io/anon/pen/xjoMOO

Above is reduced test case.

On load it's setting second slide position wrong... 50.4%, this should be 50%. If you resize it recalculates correctly.

Thanks.

**Comment by desandro** [comment]
This could likely be a scroll bar issue. Add `html { overflow-y: scroll; }`. See demo https://codepen.io/desandro/pen/31093efa873f96ea96cff1ee606373a2/

**Comment by CHEWX** [comment]
For the purpose of this issue, that wasn't my problem.

I do not include the bundled CSS as there's too much for a custom website, (aside, would be good to split into SCSS and then bundle so developer only needs to include `_core.scss` if they so wish), but I was missing `.flickity-viewport { position: relative }` which fixed the issue.
