### ISSUE TITLE
Content refreshes when changing page

### ISSUE THREAD

**Issue by theomourad** [metafizzy/flickity#773]
First, thank you for this great plugin.

I just have a refreshing problem when I swipe from one page to another.
All the images refresh every time, resulting in flickering. The images are hidden then displayed, which is annoying. 

I'd like the content to load once then staying fixed and not disappearing and reappearing every time I swipe.

Is there somewhere in the code where there is a refreshing function in the swipe function ?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
