### ISSUE TITLE
Improve document for using Flickity with webpack

### ISSUE THREAD

**Issue by yellow1912** [metafizzy/flickity#778]
I'm following the document here:
https://flickity.metafizzy.co/extras.html

On this very specific page, it says:

> Install and require add-on features for imagesLoaded, asNavFor, fullscreen, bgLazyLoad, and hash.

> npm install flickity-imagesloaded
> npm install flickity-fullscreen

Perhaps a bit of re-wording here will help alot, and also an exact list of all the modules should be listed here as well for convenience.

**Comment by desandro** [comment]
Thanks for reporting this issue. What did you have trouble understanding? How would you like this re-worded?
