### ISSUE TITLE
caption inside the image/carousel container

### ISSUE THREAD

**Issue by abbynucup** [metafizzy/flickity#78]
Hi, I just want to suggest if it's possible to allow us to add a caption inside the carousel image container? Like at the top of the image, and set a unique caption for each image.

**Comment by desandro** [comment]
Sure thing. Under [Extra demos](http://flickity.metafizzy.co/extras.html#extra-demos) there is [Setting image caption](http://codepen.io/desandro/pen/dPdVNM) or [vanilla JS demo](http://codepen.io/desandro/pen/OPQxpO). In addition, you could also just add HTML for each the gallery cell

**Comment by callumflack** [comment]
If the gallery cell uses background-images rather than containing an img, the alt tag is not recognised. 

Would it be possible to use data-attributes on the .gallery-cell instead?

**Comment by desandro** [comment]
@callumflack Sure thing. You can use `$( flkty.selectedElement ).attr('data-attribute')`

**Comment by callumflack** [comment]
Too easy, thanks!
