### ISSUE TITLE
requestAnimationFrame support android

### ISSUE THREAD

**Issue by stephan-v** [metafizzy/flickity#782]
For Android 4.2.2 we are currently seeing errors on our Sentry logging server.

> requestAnimationFrame is not defined

This is where the exact bit of code is executed:

./node_modules/flickity/js/animate.js in animate at line 57:1

```
  this.positionSlider();
  this.settle( previousX );
  // animate next frame
  if ( this.isAnimating ) {
    var _this = this;
    requestAnimationFrame( function animateFrame() {
      _this.animate();
    });
  }
};
```

This library claims to have the proper support for Android but as of Android 4.2.2 `requestAnimationFrame` does not work in the default Android browser anymore.

See this article:

> Short story – window.requestAnimationFrame does not work on the Android default browser as of Android 4.2.2.

http://shitnever.works/2015/08/11/android-default-browser-aka-internet-and-requestanimationframe/

Do you guys recommend to polyfill this myself or is this something that will be patched in an upcoming version?

I am starting to see that this error pop up more and more.

**Comment by desandro** [comment]
[Flickity v2.1.1 has dropped support for Android v4](https://github.com/metafizzy/flickity/releases/tag/v2.1.1). In addition to removing the `requestAnimationFrame` polyfill, there are other vendor prefix support that was removed in v2.1.1. Android v4 has >1% global browser usage. If you still need android v4 support you can downgrade to Flickity v2.1.0.
