### ISSUE TITLE
Detect last cell with contain: true and custom nav btns

### ISSUE THREAD

**Issue by lorenzo-gasperoni** [metafizzy/flickity#783]
I am using contain: true.
So, for example:
- i have 5 cells
- i can see 3 cells at time
- if i press two times the next button i reach the last cell

But at this position the current index is 3 and the cells count is 5. If i click the next button still 2 times i reach the "real" end of the slider and can trigger the event "current slide = tot slides".

Considering the responsivness (so i can't assume ender slide = tot slides - 3, cause the 3 number is variable with screen resolution), what can i do?
Thanks!

**Comment by desandro** [comment]
See https://github.com/metafizzy/flickity/issues/289#issuecomment-157488885

Closing as duplicate.
