### ISSUE TITLE
If use hash: true, obtain an unwanted anchor to slider [mobile]

### ISSUE THREAD

**Issue by lorenzo-gasperoni** [metafizzy/flickity#784]
With hash plugin installed and hash: true option, on page reload i have, ONLY ON MOBILE (Chrome, iOS) an anchor to selected slide.

So i have a slider at a certain vertical scroll position of the page, and if i select a slide named "id=cell-3", the url state is pushed with url#cell-3. If now i reload the page the scroll top position instantly goes to top offset of the slider and do not start from the top or does not remain where was before the reflesh.

On desktop (Chrome) i don't have any issue and the scroll position is normal.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
