### ISSUE TITLE
arrowShape is warped when initialized in HTML

### ISSUE THREAD

**Issue by iamricky** [metafizzy/flickity#786]
I've run into an issue where defining `arrowShape` in the markup returns warped arrows. Any idea what could be causing this?

e.g.`data-flickity='{ "arrowShape": { "x0": "10", "x1": "60", "y1": "50", "x2": "65", "y2": "45", "x3": "20" } }'
`
**Test case:**
https://codepen.io/iamricky/pen/XYZbRr

**Comment by desandro** [comment]
Thanks for reporting this issue. The number values should be set without quotes, so they are interpreted as numbers and not strings. I realize it's a bit confusing with all the single quotes and double quotes going on. 

``` html
<div class="carousel" data-flickity='{ "arrowShape": { "x0": 10, "x1": 60, "y1": 50, "x2": 65, "y2": 45, "x3": 20 } }'>
```

See demo https://codepen.io/desandro/pen/c72dac16af936b84eedcfe973561ab93/

**Comment by iamricky** [comment]
@desandro Looks good on my end as well, thanks for your help. I've run into another issue where `data-flickity` also warps my arrows, whenever I initialize two carousels on the same page. Would you mind if I detailed the problem here? or should I open a separate issue?

**Comment by desandro** [comment]
Let's keep it going here!
