### ISSUE TITLE
cells collapse on first load 

### ISSUE THREAD

**Issue by Ricky55** [metafizzy/flickity#789]
Hi 

I think this maybe down to my code rather than a bug persay but I'm using two sliders with the asNavFor option and unless I set a specific height for my cells the sliders collapse on first load. This happens in Firefox on Windows and Safari iOS.

The page https://qwerty-website.co.uk/

If I set a height in my CSS and then set back to auto in my js the problem is solved. What am I doing wrong here? All your examples seem to set an explicit height but this stops them from scaling responsively.

Sorry if this is just down to my inexperience but if you can help me I'd very much appreciate it.

Thanks Richard

**Comment by desandro** [comment]
You may need [imagesLoaded](https://flickity.metafizzy.co/options.html#imagesloaded)

**Comment by Ricky55** [comment]
Desandro, thank you mate! I've been messing around trying to fix this for a few days, I should have checked the docs more thoroughly. I knew a project like this wouldn't have something like omitted.

**Comment by mrafei** [comment]
Hi

@desandro I'm having problem with cells collapsing when my custom fonts is being loaded on my website, which results in changing width of cells.

Do you have any suggestions?
Thanks.

**Comment by clarknelson** [comment]
wrap the Flickity instantiation in a jQuery window load event listener

``` javascript
$(window).on('load', function(){
  // create flickity somewhere in here
  // new Flickity()
  // $().flickity()
});
```

**Comment by desandro** [comment]
You may need to trigger [resize](https://flickity.metafizzy.co/api.html#resize) after fonts have loaded.
