### ISSUE TITLE
.gallery-cell.is-selected with freeScroll: true

### ISSUE THREAD

**Issue by damienroche** [metafizzy/flickity#79]
Hi there,
I got an issue when setting up the freeScroll parameter to true.
For each gallery-cell, I got some text with opacity set to 0.
When each gallery-cell have class equal to .is-selected, the opacity becomes equals to 1.
However, when I try it in my browser (Chrome), it works only on odd gallery cells.
When freeScroll parameter is false, it works on every cells, but I would like to keep this parameter to true.

**Comment by damienroche** [comment]
http://codepen.io/ramien/pen/ByqNLb

**Comment by desandro** [comment]
Thank you for reporting this issue. This looks to be a bug. Another bug behavior: if you do select an even-numbered cell, you cannot scroll to the end.

I'll take a look at fixing this.  http://codepen.io/desandro/pen/gbBaZL
