### ISSUE TITLE
Custom 'is-selected' classname

### ISSUE THREAD

**Issue by Herokid** [metafizzy/flickity#790]
**Test case:** https://codepen.io/desandro/pen/azqbop

Hi
Would it be possible for the classname 'is-selected' to be customizable in the object instance, as one more option?

for example:

```
new Flickity (elem, {
    isSelectedClassname: 'my-is-selected-classname'
});
```

Thanks in advance!

**Comment by desandro** [comment]
There is no option. However, you can set your own custom is-selected class by overwriting Flickity's `changeSelected` method

``` js
Flickity.prototype.changeSelected = function( isSelected ) {
  var classMethod = isSelected ? 'add' : 'remove';
  this.cells.forEach( function( cell ) {
    cell.element.classList[ classMethod ]('my-is-selected-classname');
    cell.element.setAttribute( 'aria-selected', isSelected.toString() );
  });
};
```

**Comment by Herokid** [comment]
Hi @desandro 
I think is better by option, but this is enough.

Thanks (:
