### ISSUE TITLE
On low 3G connections, the css is not configuring slide positioning. How to solve this?

### ISSUE THREAD

**Issue by ivanferrer** [metafizzy/flickity#792]
How it should be:
` <div class="flickity-viewport" style="height: 426px; touch-action: pan-y;"><div class="flickity-slider" style="left: 0px; transform: translateX(38.76%);"><div class="carousel-cell cell-1 is-selected" aria-selected="true" style="position: absolute; left: 0%;">`

As it is displaying:

`<div class="flickity-viewport" style="height: 440px; touch-action: pan-y;"><div class="flickity-slider" style="left: 0px; transform: translateX(0%);"><div class="carousel-cell cell-1 is-selected" aria-selected="true" style="position: absolute; left: 0%;">`

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
