### ISSUE TITLE
Why if I made a hard reload/ cache delete, images doesn't render unless another refresh for the page

### ISSUE THREAD

**Issue by mahmoud-zakria-sociomantic** [metafizzy/flickity#793]
# Problem

I guess the preloading of the images is not working properly because it's somehow is done behind the scenes and when it gets done it doesn't render the image, there is a reload page must be done and all good.

**Comment by desandro** [comment]
Are you using [imagesLoaded](https://flickity.metafizzy.co/options.html#imagesloaded) or [lazyLoad](https://flickity.metafizzy.co/options.html#lazyload)?

**Comment by mahmoud-zakria-sociomantic** [comment]
Yes that was the issue, we disabled it, Thanks a lot @desandro 👍
