### ISSUE TITLE
Margin on cell element

### ISSUE THREAD

**Issue by fpaterno** [metafizzy/flickity#796]
Hey,

I've a problem with Flickity and cells using margin. I've added a margin on my first element and now it's outside slider container : https://codepen.io/anon/pen/gjgQPN

Why translateX(-Xpx) is added on flickity-slider element in this specific case ?

Thx !

**Comment by desandro** [comment]
Looking just fine to me.

![screen shot 2018-08-08 at 3 08 10 pm](https://user-images.githubusercontent.com/85566/43858781-e7f683a6-9b1c-11e8-99d4-5eff3552b1ed.png)


What are you seeing?

**Comment by brandondurham** [comment]
I believe I’m experiencing the same thing that was originally reported here. I need to be able to add left and right padding (different values) to either `.flickity-viewport` or `.flickity-slider`.

The idea in my case is that cells would be grouped by 3, and any cell that wasn’t currently fully in the viewport area would be dimmed. Here’s a screenshot for example’s sake:

![image](https://user-images.githubusercontent.com/250210/119409439-eb1ee780-bcac-11eb-8b50-c8c0e988ba91.png)

I tried it in a few different ways [here](https://codepen.io/brandondurham/pen/PopmyZQ) and nothing worked. Is this possible? If not possible with padding or margin, can you suggest another method?
