### ISSUE TITLE
Disabled buttons allow click events on carousel cells behind it

### ISSUE THREAD

**Issue by row1** [metafizzy/flickity#798]
The fix for #716 has a side-effect where clicking on the disabled button allows the click event on the cell/item behind it to fire.

See: https://codepen.io/anon/pen/qyPbQM

Scenario 1: Click the disabled previous button and you **will** get the click event on the cell behind it. Not working as expected and breaks my current site.
Scenario 2: Click the enabled next button and you **will not** get the click event on the cell behind it. Working as expected

**Comment by desandro** [comment]
Thanks for reporting this issue. Personally, I prefer being able to release dragging over a disabled button compared to capturing click events. I'll have to look into a solution that solves for both.

**Comment by desandro** [comment]
I've decided not to pursue resolving this issue. This one has been quiet.

**Comment by mmoser-markl** [comment]
I'm also having this issue. Can the button not be disabled when you have arrived to the end of the gallery and just change the opacity of the button?
