### ISSUE TITLE
Document changing focus state on previous/next buttons

### ISSUE THREAD

**Issue by albertorestifo** [metafizzy/flickity#8]
![image](https://cloud.githubusercontent.com/assets/1037048/5904779/5a42f8c6-a58b-11e4-85fb-be018988cae8.png)

I think the outline visible in Chrome once you clicked the slider buttons, is not very aesthetically pleasing.

**Comment by desandro** [comment]
Hi! Thanks for the contribution. I agree, it doesn't look too nice, but `:focus` states are a great accessibility feature. I've made a couple changes that removes the `:focus` when users click, but keeps it enabled so you can tab to it via keyboard. I'll also be adding documentation on how to change or remove `:focus`.

I'll leave this ticket open for any discussion.

**Comment by nvartolomei** [comment]
@desandro :+1:

**Comment by albertorestifo** [comment]
A good solution, would be to use `box-shadow` to create a similar glow to the one created by the `outline`, with the advantage that it will follow the rounded objects

**Comment by desandro** [comment]
Ha, I just implemented that last night, SHA: 6eb2fe5e9439ca59abc377d00dfb4cd1d1028a08

**Comment by desandro** [comment]
Thanks you for this feedback. [If you like stickers](http://metafizzy.co/blog/flickity-beta-testing/), please email me yo@metafizzy so I can send some your way.

**Comment by desandro** [comment]
Added to docs http://flickity.metafizzy.co/style.html#previous-next-buttons :white_check_mark:

**Comment by zkauansantos** [comment]
What css class can I change the focus color, or remove the outline? I already added it to all the html elements and the outline is still there ?
