### ISSUE TITLE
Click events not triggering on touch devices

### ISSUE THREAD

**Issue by mariyanang** [metafizzy/flickity#80]
We recently bought a developers license and really like Flickity so far.

The only issue we have is that the library prevents us from listening to click events on the viewport area where Flickity is initialized.

E.g.:

        $('body').click(function(e)
        {
            console.log(this);
        });

This will fire for clicks anywhere on our page except for click on the Flickity slider. It seems like Flickity is preventing any event propagation on the flickity container. Is this true? Any way for us to resolve this issue?

This is crucial for us because on our mobile site we need to detect any clicks outside of the mobile menu as to figure out when to close our mobile menu.

**Comment by desandro** [comment]
Thanks for reporting this issue. I was not able to reproduce this issue in a reduced test case. See:
+ [`$('body').on( 'click' )`](http://codepen.io/desandro/pen/xbygjB)
+ [`$('body').click()`](http://codepen.io/desandro/pen/EadZRG)

**Comment by mariyanang** [comment]
Thanks for the reply. The issue is not about event propagation as we thought. Actually the issue is present when I use the Chrome inspector in responsive view and select iPhone 5 for test device. I opened the pen you send above in the described environment and even in its most simplified case clicks over the slider are not triggering the console output message.

**Comment by desandro** [comment]
For touch devices, yes, `click` events will not trigger. This is because Flickity captures `touchstart` / `pointerdown` event on the initial interaction.

To resolve your issue, you can listen for other events. Flickity does trigger [`staticClick`](http://flickity.metafizzy.co/api.html#staticclick), which will be propagated to body with jQuery

``` js
$('body').on( 'click staticClick', function() {
  console.log('click')
})
```

Or, better yet, listen for pointer down events, which would be even faster.

``` js
$('body').on( 'mousedown touchstart pointerdown MSPointerDown', function() {
  console.log('pointer down')
})
```

**Comment by eads** [comment]
We're struggling with this bug over here at NPR as well. Is there no way to capture clicks or allow standard link interaction in gallery items? We need both -- standard links out as well as event listeners bound to button clicks.

**Comment by eads** [comment]
As an addendum, listening for staticClick doesn't seem to work as documented. We can listen for it on 'body' but the `$gallery.on('staticClick', myCallback)` never seems to trigger `myCallback`.

**Comment by dannydb** [comment]
False alarm on the issue @eads reported. We had a pseudo-element adding a screen to the inactive cells that was inadvertently obscuring the selected cell and blocking the clicks.

**Comment by mariyanang** [comment]
Just an update - the statickClick listener you proposed worker like a charm for me. Thanks!
