### ISSUE TITLE
Not enough transition types

### ISSUE THREAD

**Issue by Ajax30** [metafizzy/flickity#802]
I would like a "blinds" transition (see http://wowslider.com/ajax-jquery-slider-pulse-blinds-demo.html) on the slider. The free version does not have it. Does the commercial one have it?

**Comment by AdamJaggard** [comment]
With Flickity being more conceptually similar to a basic physics simulation than preset transitions I don't think you would be able to achieve these kinds of effects with Flickity without changing how Flickity works completely. Flickity doesn't have any concept of "transition" as far as I understand.

**Comment by desandro** [comment]
You can adjust Flickity's transition animation via its [selectedAttraction & friction](https://flickity.metafizzy.co/options.html#selectedattraction-friction) options. Otherwise, you'll have to use another carousel plugin for that specific 'blinds' effect.
