### ISSUE TITLE
freeScroll: last item cut off when cell width > viewport width

### ISSUE THREAD

**Issue by ohbiko** [metafizzy/flickity#806]
**Test case:** https://codepen.io/desandro/pen/bNLGNZ
**Reduced test case:** https://codepen.io/ohbiko/pen/yqqRbR

This is a quite a bummer.  Please fix.  Reduced test case posted above.

To reproduce:
Simply scroll to the last item by dragging or clicking the last dot.

**Comment by ohbiko** [comment]
I'm trying to patch this and got everything working except for one bug.

When you perform a quick and swift drag on the last cell, it's repositioned to the beginning of the cell (left side) instead of keeping it to the right side.  Can you let me know what is triggering this reposition?

So far I made these changes:
```
proto._containSlides = function() {
  ...
  this.slides.forEach( function( slide, index ) {
    if ( isContentSmaller ) {
      // all cells fit inside gallery
      slide.target = contentWidth * this.cellAlign;
    } else {
      // contain to bounds
      slide.target = Math.max( slide.target, beginBound );
      slide.target = Math.min( slide.target, endBound );
      // ohbiko fix
      if (index === this.slides.length - 1) {
        slide.targetEnd = slide.target + slide.outerWidth - this.size.innerWidth;
      }
    }
  }, this );
};
```

```
proto.dragMove = function( event, pointer, moveVector ) {
  ...
  if ( !this.options.wrapAround && this.slides.length ) {
  ...
	// ohbiko fix
    var targetEnd = this.getLastSlide().targetEnd ? this.getLastSlide().targetEnd : this.getLastSlide().target;
    var endBound = Math.min( -targetEnd, this.dragStartPosition );
    // var endBound = Math.min( -this.getLastSlide().target, this.dragStartPosition );
  ...
  }
  ...
};
```

**Comment by desandro** [comment]
Thanks for reporting this issue. This is an edge case. You can use Flickity as a horizontal scroller, but it's optimized as such. For example, if the slides are wider than the carousel, there will be bugs. You're better off trying another solution. Perhaps even just a div with `overflow-x: scroll`.

**Comment by ohbiko** [comment]
Thanks David. I agree that it might be an edge case but it is still a bug that I need to fix. I’ve built a responsive timeline and i need it to have free scroll as well as the traditional features of a carousel. A scrollable div won’t make the cut.

If you won’t fix this, can you at least point me to where in your code you are resetting the slider position to the start of the last element?  I notice it happens when there is either a hard flick/swipe or when it goes over the end of the last slide.

BTW I did purchase a commercial license to support your awesome project which I’ve been using over the past few years :)

**Comment by desandro** [comment]
The behavior in question occurs in [`drag.js` within `dragEnd`](https://github.com/metafizzy/flickity/blob/v2.1.2/js/drag.js#L258-L264)

``` js
  if ( this.options.freeScroll && !this.options.wrapAround ) {
    // if free-scroll & not wrap around
    // do not free-scroll if going outside of bounding slides
    // so bounding slides can attract slider, and keep it in bounds
    var restingX = this.getRestingPosition();
    this.isFreeScrolling = -restingX > this.slides[0].target &&
-restingX < this.getLastSlide().target;
```

You can remove this conditional, which will allow free-scrolling behavior to continue past the targets of the first & last slides. You'll have to add back a way to prevent scrolling outside.

**Comment by ohbiko** [comment]
I was actually able to fix this case but I forgot to post it.  As posted above, I've defined a `targetEnd` property for the last slide.  It stores the x position of the end of the slide.  In dragEnd, I then use targetEnd instead of target to determine whether isFreeScrolling remains true.  This works when you scroll gently to the end.
```
var targetEnd = this.getLastSlide().targetEnd ? this.getLastSlide().targetEnd : this.getLastSlide().target;
this.isFreeScrolling = -restingX > this.slides[0].target &&
      -restingX < targetEnd;
```

However the issue I'm now facing is when you do a hard flick/swipe or when it goes over the end of the last slide.  I found out that the issue here is in the physics implementation.  I believe it's in the applyDragForce function but I haven't got time to wrap my head around how to fix this.  Any ideas?

**Comment by desandro** [comment]
Sorry, there's no easy fix off the top of my head to implement this behavior. I leave that challenge up to you.

**Comment by stonetwig** [comment]
Hello,

I've had this issue as well but I think I found a problem in the code that perhaps is a bug?
I noticed that the target of each slide got calculated to the furthest x of the first cell in `slide.cells` and got into the `updateTarget` method in the Slide-class.

What I noticed was `this.parent.cellAlign` was always zero in my case which is correct sometimes I assume but it was what led to what I assume is the incorrect target. When I change the last line in that method to this:
`this.target = this.x + this.firstMargin + slideWidth * (this.parent.cellAlign === 0 ? 1 : this.parent.cellAlign);` the issue disappear.

I'm sorry but I don't have the time atm to go through the code in more details than that, but it might help others or maybe to fix this issue for good.

**Comment by rsepierre** [comment]
It could/should be a feature of the "contain" flickity option.
To calculate the exact "stop point" of the slider, leaving the standard behavior untouched

**Comment by xxvii** [comment]
Same issue as https://github.com/metafizzy/flickity/issues/349

It would be very useful to have it fixed.

**Comment by TaraOShea** [comment]
+1

**Comment by TaraOShea** [comment]
I'm also coming across this problem, any chance this might be built in at any point? 

If not has anyone come across a  slider that is freescroll and anchors the last slide to the end of the last frame?
