### ISSUE TITLE
programmatically "scroll" slider with freeScroll:true

### ISSUE THREAD

**Issue by hatsumatsu** [metafizzy/flickity#807]
Is it currently possible to set the slider's position through the API when `freescroll: true`? Potential use cases are syncing the vertical scroll position of the document to the slider's progress or using an external UI like a range input to control a freescroll slider.

**Comment by hatsumatsu** [comment]
I currently use

````
flickityInstance.applyForce( offset );
flickityInstance.startAnimation();
flickityInstance.dragEnd();
````
Depending on your input you have to play with the `offset`  value to get the desired effect.

Simulating a drag event feels a little bit hacky so I wonder if there is another way to do this...?

**Comment by desandro** [comment]
Sorry, there is no API to directly change the slider position with `freeScroll`.  You would have to look at the internal properties `x` and manipulate that. 

Flickity does have `select` method for selecting individual slides.

**Comment by hatsumatsu** [comment]
Thanks for clarifying! 
But somehow manually setting the `x` property doesn't move the slider. Is there some kind of update functionality to be called afterwards? And I guess in this case I have to handle wrapping of the content (like with the `wrapAround` option manually) myself?

**Comment by m4n1ok** [comment]
Hi @hatsumatsu,
I achieved a programmatic behavior by setting first x property and after call positionSlider() method from flickity. :)

**Comment by elmbrent** [comment]
```
  $('.flickity-slider').css({'transform'         : 'translateX(5%)'});
    $('.carousel').flickity( 'positionSlider');

```
this does not work it reset the position?
