### ISSUE TITLE
Carousel tries to center after first click when wrapAround is set to true

### ISSUE THREAD

**Issue by jacobarriola** [metafizzy/flickity#808]
**Test case:** https://codepen.io/jacobarriola/pen/gjdxRV

A carousel tries to center itself when set to `wrapAround: true` and its cells are less than the parent container's width.

Is there something that I am doing wrong?

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue. The root problem is the first example does not have enough content to fill the carousel. Related to #95. One solution is to only enable wrapAround if there's enough content to fill the carousel.

I've added a new issue to add this as a feature #809

**Comment by jacobarriola** [comment]
@desandro thank you for the response! 👏

>One solution is to only enable wrapAround if there's enough content to fill the carousel.
In my use case, the carousel will be used an indefinite number of types in an application, with some having enough content to fill the space, and others not. Therefore, I'm not sure I'd be able to use this solution.

In the meantime, I'll cross my fingers on that feature request :)

I'd be happy to contribute if you already had something in mind with your `wrapAround: 'fill'` proposal.

**Comment by desandro** [comment]
Yeah, I imagine others have the same kind of usage. I'm closing the issue here. Follow #809 for progress
