### ISSUE TITLE
Page Scrolls Vertically While Swiping (iOS Mobile Browsers)

### ISSUE THREAD

**Issue by mattrothenberg** [metafizzy/flickity#813]
Howdy! First and foremost, thanks for creating + maintaining such a great library.

**Test case:** https://codepen.io/mattrothenberg/pen/qyeyLX
**Production**: https://alisonunderwood.com/collage/concealed-objects

I'm running into an issue where, on my iPhone 8+ (running the latest version of both Safari + Chrome), I'm able to pan the page vertically while I'm in the process of swiping through a single slider. This can be frustrating, as I don't want the page to move up and down while I browse through a beautiful gallery of images.

I've read through previous issues and discovered fixes such as adding this noop event handler, but I'm not having any success there. I could very well be doing something wrong 😭.

```js
window.addEventListener( 'touchmove', function() {})
```

Might there be any other tricks I can use to prevent the page from scrolling vertically while someone is swiping through a gallery?

Thank you!

**Comment by desandro** [comment]
Thanks for reporting this issue. See discussion #740. Hopefully this is resolved in iOS 12

**Comment by mattrothenberg** [comment]
Thank you for the prompt reply! ❤️

**Comment by lougreenwood** [comment]
I have this issue in iOS 12 :(

**Comment by DzmitrySiver** [comment]
Reproducing this on iOS12.

**Comment by desandro** [comment]
Lets keep discussion in #740. Locking this issue.
