### ISSUE TITLE
Flickity sync and nav hover event

### ISSUE THREAD

**Issue by Moorst** [metafizzy/flickity#814]
Hi,

I'm looking to change the main carousel on the hover event of a nav item, using [flickity-sync](https://github.com/metafizzy/flickity-sync).

https://github.com/metafizzy/flickity-sync/issues/8#issuecomment-314789316 essentially covers the functionality I'm after, though of course I'd need a hover event instead of staticClick. Is this available, or is it possible to add a custom hover event?

e.g.
```
$navCarousel.on( 'hover.flickity', function( event, pointer, cellElement, cellIndex ) {
  if ( cellElement ) {
    $mainCarousel.flickity( 'select', cellIndex );
  }
});
```

**Comment by desandro** [comment]
Flickity does not have a hover event, but you could build this functionality with [jQuery's mouseover event](https://api.jquery.com/mouseover/).

See demo https://codepen.io/desandro/pen/LJYxmZ

``` js
var $carouselMain = $('.carousel-main').flickity();

var $carouselNav = $('.carousel-nav').flickity({
  asNavFor: '.carousel-main',
  contain: true,
  pageDots: false,
});

// select main on nav hover
$carouselNav.on( 'mouseover', '.carousel-cell', function( event ) {
  var index = $( event.currentTarget ).index();
  $carouselMain.flickity( 'select', index );
});
```
