### ISSUE TITLE
show/hiding content within FLickity slides pushes content outside of the slide

### ISSUE THREAD

**Issue by Fazyyy** [metafizzy/flickity#815]
If you have an element which can change height, at it's expanded heights, it can push stuff out of view of the Flickity slider as the height of each slide is only set on initialisation and doesn't seem to ever be recaulculated again at any point after.

**Test case:** https://jsfiddle.net/y9gmzjdt/10/

**Comment by desandro** [comment]
Thanks for reporting this issue. You'll need to trigger the [`resize` method](https://flickity.metafizzy.co/api.html#resize)
