### ISSUE TITLE
Slider doesn't work on BlackBerry 10 Browser

### ISSUE THREAD

**Issue by vadimhp** [metafizzy/flickity#816]
Tested on the BlackBerry 10 Device Simulator on Windows 10 (build 10.3.1.995)

**Test case:** https://codepen.io/desandro/pen/azqbop

**Comment by desandro** [comment]
Thanks for reporting this issue. 
**Add a 👍  reaction** to this issue if you would like to see Flickity support BlackBerry 10 added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by desandro** [comment]
No one else chimed so I'm closing.

**Comment by vadimhp** [comment]
just checked on an actual blackberry Z10 device, and it works fine.
