### ISSUE TITLE
Is it possible wrapAround to be continuous

### ISSUE THREAD

**Issue by asolopovas** [metafizzy/flickity#817]
Hi, 

Is it possible to make `wrapAround` to be continuous, because currently when you get to the last image in the carousel the first one disappears on the right-hand side, a similar thing happens when you get to the 1 carousel image the 6th one the right-hand sort of disappears and then reappears.

**Test case:** https://codepen.io/asolopovas/pen/OoPqgW

**Comment by desandro** [comment]
Sorry, this behavior is not possible. See discussion in #95.
