### ISSUE TITLE
Thumbnail support

### ISSUE THREAD

**Issue by gijsroge** [metafizzy/flickity#82]
I would love this plugin to have native support for thumbnails.
None of the "better" touch optimized carousels have this. Would be a nice and surprisingly unique feature.

Thanks :)

**Comment by desandro** [comment]
Thanks for this feature request. My take is that creating thumbnails may be too opinionated of a feature for Flickity. You might want square thumbnails, or captions, or in a gallery, or just stacked. You can achieve thumbnail navigation with [`asNavFor`](http://flickity.metafizzy.co/options.html#asnavfor) or building [custom navigation](http://flickity.metafizzy.co/extras.html#custom-navigation-ui), both of which are flexible solutions that can accommodate a variety of use cases.

I'll leave this issue open to see if others' interest in this feature.

**Comment by pesla** [comment]
+1 for thumbnail navigation as a standard feature :)

**Comment by starise** [comment]
Sounds redundant. Using asNavFor and some custom css you can achieve a great result.

**Comment by phelippe** [comment]
+1  :+1:

**Comment by desandro** [comment]
I'm closing this issue as it didn't get enough public interest. :whale:

**Comment by notflip** [comment]
+1!

**Comment by ilicmarko** [comment]
We really need this... +2017

**Comment by peucaio** [comment]
imo the asNavFor with flickity-sync provides everything we need to create a thumbnailed gallery.

**Comment by abrambailey** [comment]
Would love if there was a demo of this posted... seems like a very typical use case. Image thumbnail nav with lazy load would seem ideal.

**Comment by abrambailey** [comment]
Took a whack at it... Not sure if all the CSS is needed. https://codepen.io/abrambailey/pen/bjLxvx
