### ISSUE TITLE
Center Align multiple cells

### ISSUE THREAD

**Issue by kevmon** [metafizzy/flickity#820]
Is it possible to center align multiple cells when the total width of all of them is less than the width of the slider?

I'm building a navigation list that has less items right now than fill up the full width.  But over time there will be more.  I'm trying to have them (only two) center, however when I choose cellAlign: center, it brings the first cell to the center.

Thanks in advance

**Comment by desandro** [comment]
I'm having trouble understanding what you're trying to achieve, but I recommend looking at:

+ [groupCells](https://flickity.metafizzy.co/options.html#groupcells)
+ [contain](https://flickity.metafizzy.co/options.html#contain)
