### ISSUE TITLE
How to install flickity 

### ISSUE THREAD

**Issue by vinhhali** [metafizzy/flickity#821]
can help me install flickity, i use demo on codepen.io successfully, and i proceed to copy on html and css import your website . however flickity inactive , please help me !!

**Comment by kukac7** [comment]
@vinhhali demo link pls?
import `<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>` too.

**Comment by vinhhali** [comment]
i code on menu mobile theme , you cant help me . Link here : https://muradbeauty.com/

**Comment by kukac7** [comment]
@vinhhali I do not know what the problem is and what to look at. 🤷‍♂️

**Comment by desandro** [comment]
You need to add [flickity.css](https://unpkg.com/flickity@2/dist/flickity.css) and [flickity.pkgd.min.js](https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js) to your site. You can do so by [directly pointing to unpkg](https://flickity.metafizzy.co/#cdn):

Link directly to Flickity files on unpkg.
``` html
<!-- CSS -->
<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">

<!-- JavaScript -->
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
```
