### ISSUE TITLE
How can I temporarily hide individual cells without removing and re-inserting them?

### ISSUE THREAD

**Issue by nicknack23** [metafizzy/flickity#829]
I want the hidden cells to be completely invisible, i.e. navigation arrows should bypass them and their navigation dots should be removed/hidden. I thought this would be possible using `cellSelector` but I couldn't get navigation to work properly. Here's a codepen: https://codepen.io/anon/pen/QVgOrg.

**Comment by Tmp2k** [comment]
I have the same issue. If you want a carousel who's cells change based on a dynamic filter you need to show/hide cells.  This works, but the nav arrows and dots still take hidden cells into account. 

The problem with using append/remove is that append moves the element form their existing position in the dom, and remove doesn't put them back. So if you want to do this many times over, you have to clone the elements. I can be done, and I have now done this, but it's not a very clean or simple solution, to what is a simple requirement.

Given that hiding the cells with display:none; works perfectly apart from the navigation logic you could forgive people for expecting this functionality.

If I get time to look at the code, I'll give it a go, but wouldn't it be a case of adding :visible to the selectors used int he arrows and dots logic?

**Comment by flowgrow** [comment]
> I have the same issue. If you want a carousel who's cells change based on a dynamic filter you need to show/hide cells. This works, but the nav arrows and dots still take hidden cells into account.
> 
> The problem with using append/remove is that append moves the element form their existing position in the dom, and remove doesn't put them back. So if you want to do this many times over, you have to clone the elements. I can be done, and I have now done this, but it's not a very clean or simple solution, to what is a simple requirement.
> 
> Given that hiding the cells with display:none; works perfectly apart from the navigation logic you could forgive people for expecting this functionality.
> 
> If I get time to look at the code, I'll give it a go, but wouldn't it be a case of adding :visible to the selectors used int he arrows and dots logic?

I also have to filter some of the slides, but for me the best way is to use display: none; followed by the [reposition method](https://flickity.metafizzy.co/api.html#reposition)

**Comment by binarymonkey84** [comment]
> I also have to filter some of the slides, but for me the best way is to use display: none; followed by the [reposition method](https://flickity.metafizzy.co/api.html#reposition)

@flowgrow I tried this but could not get it to work. Have you got a code sample / CodePen link you can share where it's working?
