### ISSUE TITLE
Option not to add 'transform' css to flickity-slider class

### ISSUE THREAD

**Issue by eskimo212** [metafizzy/flickity#83]
Hi, I'm using 2 instance of the slider, one with 4 thumbnail images which should always be in view and NOT slide and one with 4 slides with html content inside them which slide. The thumbnails and html slides link to each other so there is a relevant thumbnail for each html slide but because I want the thumbnails always in view how do I stop the transform CSS being added to the thumbnail slider?

When the transform CSS is added and the page gets smaller some of the thumbnails are hidden and you have to scroll to view them. I could override some the CSS but would prefer to stop it being added in the first place.

Hope the above makes sense, great slider/carousel.

Cheers, Lee.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
