### ISSUE TITLE
Align cell to center, but start with first cell aligned left?

### ISSUE THREAD

**Issue by peminator** [metafizzy/flickity#834]
this is more a feature request - its cool to have cells centered - but often for design it would be great to allow start first cell aligned left - but after dragging cells would always (except the first) center to middle - is this achievable in a simple way? would be a great help

**Comment by desandro** [comment]
Yes! [Enable `contain`](https://flickity.metafizzy.co/options.html#contain). `contain` will also align the last cell to the right.

**Comment by dpw1** [comment]
Is it possible to achieve this very same effect whilst using wrapAround?
