### ISSUE TITLE
Select with custom speed/duration

### ISSUE THREAD

**Issue by AndreMantas** [metafizzy/flickity#835]
Hi all.

I want to use select method (https://flickity.metafizzy.co/api.html#select) and specify a custom speed/duration for the animation. But I only want this speed/duration for this particular select and not for the normal swipe in the carousel.

Is there a way to achieve this?

Thanks

**Comment by desandro** [comment]
Not quite.

You can control the physics variables for selecting animation with [selectedAttraction & friction](https://flickity.metafizzy.co/options.html#selectedattraction-friction)

**Comment by AndreMantas** [comment]
Hmm I see. Yes I use those ones in my config but then is it possible to give flickity 1 config and then after some time change its config to new values? Would it work if I pass one object and then change the properties of the given object after some time?

**Comment by desandro** [comment]
Yes, you can change the option values for selectedAttraction and friction on-the-fly. That said, I don't think you'll be able to achieve the specific behavior you're looking for. Sorry, Flickity does not provide that kind of behavior.

**Comment by michaeldouma** [comment]
Perfect. selectedAttraction is what I needed.
