### ISSUE TITLE
Handling images of varying sizes with captions and description ...

### ISSUE THREAD

**Issue by bdcoder2** [metafizzy/flickity#836]
I am trying (for the past 7 hours) to get Flickity to cooperate with Bootstrap 3.3.7 and am nearly there but ...

The carousel I am trying to get working must accommodate the following:

1) Varying dimensions of images minimum w:250 x h:150 to a maximum w:1200 x h:900 (pixels) - seems to work.

2) Keep everything responsive when the user resizes the window (makes it bigger or smaller)

The one thing I cannot seem to figure out is how to make the carousel height change depending on the carousel-cell content, i.e.: make the carousel container responsive like all other elements -- it seems that one must keep the carousel "container" a fixed height -- is that correct?

BONUS: For tracking purposes I need to fire a "GET" request to our server whenever an image is brought into view.  I suspect one uses the "change" event for this, but first I just want to get the basics running.

**Test case:** https://codepen.io/bdcoder2/full/NLLBeb/

Appreciate any insights that may be provided as I am still obviously very green with regard to how to configure everything correctly.

Thanks in advance.

**Comment by desandro** [comment]
If you want to change the carousel height to fit the cells, you may have to remove the height set in CSS to both `.carousel` and `.carousel-cell`. See demo https://codepen.io/desandro/pen/rZPXYy

**Comment by bdcoder2** [comment]
Ah - thanks big Dave! -- would you happen to have a demo that can display a caption (centered top) followed my the various image sizes shown in my/your demo and a text (couple of lines) description (centered) below the image? -- my current problem is two-fold:

1) In full-screen mode - The text (caption and description) gets "pushed" outside the the screen by the image

2) I would like the images to be auto-resized like in Bootstrap so they retain their aspect ratio, but fit nicely within the cell regardless of screen size / full-screen mode (hope that makes sense).

**Comment by desandro** [comment]
Sorry, I don't have a demo for that kind of particular behavior. I've tagged this issue as _help wanted_. Maybe some valiant hero could swoop in and save the day.

**Comment by bdcoder2** [comment]
Solved - I updated my original pen at:
[https://codepen.io/bdcoder2/full/NLLBeb/](https://codepen.io/bdcoder2/full/NLLBeb/)

**Comment by xcartmods** [comment]
```.carousel .flickity-viewport {
  -webkit-transition: height 0.4s;
  transition: height 0.4s;
}```
