### ISSUE TITLE
Prevent click on link-wrapped content slides when dragging?

### ISSUE THREAD

**Issue by lougreenwood** [metafizzy/flickity#838]
Hello,

I've searched the issues, but I can't find an example implementation for the following...

I'm attempting to use Flickity as a replacement for Swiper.js - http://idangero.us/swiper/ (Flickity performance seems to be better so far...)

However, it seems that Flickity allows a click event to propagate when clicking and dragging a slide, for example:

- User sees a row of 5 sliders, current slide = slide 1
- User click, hold and drags slide 4 so it is the current slide
- When use releases the click, a click event occurs on the content - if the content happens to be a link, it opens the link.

I thought this might be simple enough to handle by setting the `draggable="true"` attribute on each slide and then prevent propagation using the native `ondragstart` event, but it seems that native `ondragstart` doesn't fire for slides (https://www.w3schools.com/jsref/event_ondragstart.asp)

So my question is whether there's some config setting which allows for content slides which are wrapped in a link to only be triggered when not dragging (i.e the inverse of `staticClick`).

Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue. I wasn't able to reproduce the issue I think you are describing. Starting drag on a link and releasing it will not trigger the click event. See demo https://codepen.io/desandro/pen/317400d353f64e9ca109cfa680a8a795

**Comment by riiccardo** [comment]
@desandro js section is empty how can I know what u do? :|

**Comment by fredericoo** [comment]
late reply but I managed to solve it by adding the following event triggers (no jQuery):

```
flkty.on('dragStart', () => flkty.slider.childNodes.forEach(slide => slide.style.pointerEvents = "none") );
      flkty.on('dragEnd', () => flkty.slider.childNodes.forEach(slide => slide.style.pointerEvents = "all") );
```

**Comment by pikooli** [comment]
Thanks you @fredericoo it work : D 👍

**Comment by ositaka** [comment]
Perfect ;)

**Comment by adamduncan** [comment]
Further to @fredericoo's solution, one might consider preventing `pointer-events` simply for the entire carousel `slider` itself, as opposed to having to apply to all children:

```js
flkty.on('dragStart', () => flkty.slider.style.pointerEvents = 'none');
flkty.on('dragEnd', () => flkty.slider.style.pointerEvents = 'all');
```

Thanks for the original tip 👍

**Comment by Bergrebell** [comment]
thanks for all the replies above! for **Nuxt** there are some additional pitfalls to take care of.

since flickity needs to be wrapped inside `<client-only>`-tags, the mounted hook can't be used to add the event-listeners.

what works is to add a mounted-hook on the flickity component

```
<Flickity ref="quoteSlider" :options="flickityOptions" @hook:mounted="onFlickityMounted">
    <div :style="isDragging ? 'pointer-events: none;' : 'pointer-events: auto;'">
         [...]
    </div>
</Flickity>
```

and then add a method that adds the event listeners

```
data() {
        return {
            isDragging: false,
        };
    },

methods: {
        onFlickityMounted() {
            if (this.$refs.quoteSlider) {
                this.$refs.quoteSlider.on('dragStart', this.dragStart);
                this.$refs.quoteSlider.on('dragEnd', this.dragEnd);
            }
        },
        dragStart() {
            this.isDragging = true;
        },

        dragEnd() {
            this.isDragging = false;
        },
    },
```

**Comment by fredericoo** [comment]
> thanks for all the replies above! for **Nuxt** there are some additional pitfalls to take care of.
> 
> since flickity needs to be wrapped inside `<client-only>`-tags, the mounted hook can't be used to add the event-listeners.
> 
> what works is to add a mounted-hook on the flickity component
> 
> ```
> <Flickity ref="quoteSlider" :options="flickityOptions" @hook:mounted="onFlickityMounted">
>     <div :style="isDragging ? 'pointer-events: none;' : 'pointer-events: auto;'">
>          [...]
>     </div>
> </Flickity>
> ```
> 
> and then add a method that adds the event listeners
> 
> ```
> data() {
>         return {
>             isDragging: false,
>         };
>     },
> 
> methods: {
>         onFlickityMounted() {
>             if (this.$refs.quoteSlider) {
>                 this.$refs.quoteSlider.on('dragStart', this.dragStart);
>                 this.$refs.quoteSlider.on('dragEnd', this.dragEnd);
>             }
>         },
>         dragStart() {
>             this.isDragging = true;
>         },
> 
>         dragEnd() {
>             this.isDragging = false;
>         },
>     },
> ```

Is this for Vue?

**Comment by Bergrebell** [comment]
> > thanks for all the replies above! for **Nuxt** there are some additional pitfalls to take care of.
> > since flickity needs to be wrapped inside `<client-only>`-tags, the mounted hook can't be used to add the event-listeners.
> > what works is to add a mounted-hook on the flickity component
> > ```
> > <Flickity ref="quoteSlider" :options="flickityOptions" @hook:mounted="onFlickityMounted">
> >     <div :style="isDragging ? 'pointer-events: none;' : 'pointer-events: auto;'">
> >          [...]
> >     </div>
> > </Flickity>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then add a method that adds the event listeners
> > ```
> > data() {
> >         return {
> >             isDragging: false,
> >         };
> >     },
> > 
> > methods: {
> >         onFlickityMounted() {
> >             if (this.$refs.quoteSlider) {
> >                 this.$refs.quoteSlider.on('dragStart', this.dragStart);
> >                 this.$refs.quoteSlider.on('dragEnd', this.dragEnd);
> >             }
> >         },
> >         dragStart() {
> >             this.isDragging = true;
> >         },
> > 
> >         dragEnd() {
> >             this.isDragging = false;
> >         },
> >     },
> > ```
> 
> Is this for Vue? Vanilla JS or other framework users may be confused about this. Some clarity is welcomed

as stated in the first sentence this applies for [NuxtJS](https://nuxtjs.org) (which is based on Vue). i hope that i could clarify your confusion.

**Comment by hayatbiralem** [comment]
Hey, I just found out that if you're trying to control JavaScript event listeners for links in the carousel, you can look for `event.isDefaultPrevented()` value. [Here is the pen](https://codepen.io/hayatbiralem/pen/XWYNyMe?editors=0010).

```javascript
// external js: jquery.min.js
// external js: flickity.pkgd.js
(function($){
  
  $(document).on('click', 'a', function(event){
    console.log(
      'Is click default prevented?',
      event.isDefaultPrevented()
    );
  });
  
})(jQuery);
```

![image](https://user-images.githubusercontent.com/2085468/200565593-a22a0546-42d9-42c9-8c13-4ab68dc415bd.png)
