### ISSUE TITLE
Keyboard nav only works after first mouse interaction

### ISSUE THREAD

**Issue by eads** [metafizzy/flickity#84]
Keyboard only works in gallery if you've interacted via another means. You can see this behavior in the carousel at the top of the official page: Using arrows on load does nothing, works once you've clicked a dot or one of the paddle arrows.

**Comment by desandro** [comment]
Thanks for reporting this issue. Yes, this is the default behavior. If you wish for a Flickity gallery to have the initial focus, you can do with with JS

``` js
// jQuery
var $gallery = $('.gallery').flickity({
  // options
})
// set initial focus
$gallery.focus();
```

``` js
// vanilla JS
var gallery = document.querySelector('.gallery');
// init Flickity
new Flickity( gallery, {
  // options
});
// set initial focus
gallery.focus();
```

See [jQuery demo](http://codepen.io/desandro/pen/VYVEbM) or [vanilla JS demo](http://codepen.io/desandro/pen/JoemRR)

**Comment by eads** [comment]
Thanks, this is good to know. While it's not the behavior I expected, I entirely understand why you'd build it to work this way. Thanks for adding this to the docs.

**Comment by eads** [comment]
I'm noticing one odd behavior.

If you call focus in a chain everything is groovy:

```
$('.gallery').flickity().focus();
```

If you call focus in a separate call, it does not appear to work:

```
var $gallery = $('.gallery');
$gallery.flickity();
$gallery.focus();
```

I'll try and make a codepen for this later, gotta run to present a workshop that uses flickity right now (:

**Comment by desandro** [comment]
@eads Hmm. I was not able to reproduce http://codepen.io/desandro/full/RNEMrY

**Comment by frontenddevguy** [comment]
I ran into this issue and the demo is not working for me either on FF Dev 63.0b14 (64-bit) or regular FF. It does work in Chrome and Safari. Haven't tested mobile yet.
I would expect first arrow press to work, before clicking on dots. It seems strange from usability perspective why it wouldn't?
