### ISSUE TITLE
Is it possible to automatically go back to first slide when wraparound is false?

### ISSUE THREAD

**Issue by justanotherco** [metafizzy/flickity#841]
Great slider!

If you have wraparound: false and reach the last slide of a slider, is it possible to make it automatically slide all the way back to the first one instead of staying stuck at the end?

I don't want wraparound, but would love it to "reset" when reaching the end and trying to click one more time.

**Comment by desandro** [comment]
Yes, you can achieve this behavior by adding your own [custom buttons](https://flickity.metafizzy.co/extras.html#custom-navigation-ui) that enable the  [`isWrapped` argument](https://flickity.metafizzy.co/api.html#next). See demo https://codepen.io/desandro/pen/1d69e468b469800465cecf63f7382dc9

**Comment by justanotherco** [comment]
Ah perfect, thank you! And is it also possible to do with on a slider with an asNavFor too?

**Comment by desandro** [comment]
Yes, its possible. You would have to write additional code to add that behavior.

**Comment by 7iomka** [comment]
I need this feauture(
