### ISSUE TITLE
scss version

### ISSUE THREAD

**Issue by nam-co** [metafizzy/flickity#844]
Hi A, since the new sass version, .css can't be imported (just linked), so I was wondering if it's possible to duplicate the "/css/flickity.css" into a .scss file (same content), so it can be imported correctly, appreciate any help

thanks

**Comment by theenoahmason** [comment]
+1, I'd be willing to port this to Sass. Can be done quickly, let me know if you don't have plans to do this already.

**Comment by desandro** [comment]
Hi! Thanks for alerting me of this issue.

I'd prefer to keep just the `.css` file as its simpler both to manage on my side and understand on the user's side. I feel the simplest solution is to include the `.css` elsewhere in your pipeline. Perhaps the Sass community has a better solution than to convert a `.css` file to `.scss` so it later be converted back to `.css` ?

**Comment by nam-co** [comment]
I think the best solution would to work in scss, but if you feel is a complication the only thing we need to do is just duplicate the .css and change the extension, that’s all 

David I found in mobile the full screen icon (arrows) has a strange empty padding on the right, have you seen this? Or maybe is just me

**Comment by theenoahmason** [comment]
@desandro the way you have it currently means we can't bundle your style. Sass loader no longer supports CSS.

Often times, flickity's css is the only external css to load, and that sticks out like a sore thumb.

*I propose:*

1. A new folder called `sass` with a `flickity.scss` file inside

2. A gulp task that builds the Sass and places that built but unminified CSS file, fully autoprefixed to the original flickity.css file. Then use your current minification on that file (meaning no change there).

This will improve the styles by drastically shortening it and making it both easy to read and work with. This will also ensure you don't ever have to vendor prefix any styles.

I am willing to do both. Looking at the css, it could be done today to look at.

**Comment by theenoahmason** [comment]
@desandro This should handle everything.

**Install new deps:** `npm install gulp-sass gulp-autoprefixer gulp-sourcemaps`.
**build sass** `gulp build:sass`.



**Build Sass (Gulp Task) | `gulpfile.js`**

```js
// New Deps
const sourcemaps = require('gulp-sourcemaps');
const sass = require('gulp-sass');
const autoprefixer = require('gulp-autoprefixer');

/**
 * Builds SASS.
 * 
 * Creates a `.css` file in the `/css` directory from any `.scss/.sass` files 
 * in the `/sass` directory that do not have an underscore prefix (ie: `_variables.scss`). 
 * The resulting file will be unminified and autoprefixed. This task also allows for simple 
 * lookup of Sass modules from `/node_modules` directory without relative paths. This 
 * task will also write sourcemaps to all initial data allowing for Sass debugging in the browser.
 * 
 * Process:
 *	 1. Imports all SASS modules.
 *	 2. Compiles the SASS to CSS.
 *	 3. Adds all necessary vendor prefixes to CSS.
 *	 4. Writes sourcemaps to initial content.
 *	 5. Writes created CSS files.
 *
 * Run:
 *	 - Global command: `gulp build:sass`.
 *	 - Local command: `node ./node_modules/gulp/bin/gulp build:sass`.
 */
gulp.task('build:sass', function sassBuilder() {
	return gulp.src(['./sass/**/*.s+(a|c)ss'])
		.pipe(sourcemaps.init({ loadMaps: true }))
		.pipe(sass({ includePaths: ['node_modules'], outputStyle: 'expanded' })
			.on('error', function(err) { console.error(err); this.emit('end'); }))
		.pipe(autoprefixer({ browsers: ['last 5 versions', 'ie >= 9'], cascade: true }))
		.pipe(sourcemaps.write('./'))
		.pipe(gulp.dest('./css')));
});
```

**Flickity Sass | `Flickity.scss`**

```sass
.flickity-enabled {
  position: relative;

  &:focus {
    outline: none;
  }

  &.is-draggable {
    tap-highlight-color: transparent;
    user-select: none;

    .flickity-viewport {
      cursor: move;
      cursor: grab;

      &.is-pointer-down {
        cursor: grabbing;
      }
    }
  }
}

.flickity-viewport {
  overflow: hidden;
  position: relative;
  height: 100%;
}

.flickity-slider {
  position: absolute;
  width: 100%;
  height: 100%;
}

.flickity-button {
  position: absolute;
  background: hsla(0, 0%, 100%, 0.75);
  border: none;
  color: #333;

  &:hover {
    background: white;
    cursor: pointer;
  }

  &:focus {
    outline: none;
    box-shadow: 0 0 0 5px #19F;
  }

  &:active {
    opacity: 0.6;
  }

  &:disabled {
    opacity: 0.3;
    cursor: auto;
    pointer-events: none; // prevent disabled button from capturing pointer up event. #716
  }
}

.flickity-button-icon {
  fill: #333;
}

.flickity-prev-next-button {
  top: 50%;
  width: 44px;
  height: 44px;
  border-radius: 50%;
  transform: translateY(-50%); // vertically center

  &.previous { 
    left: 10px; 
  }

  &.next { 
    right: 10px; 
  }

  .flickity-button-icon {
    position: absolute;
    left: 20%;
    top: 20%;
    width: 60%;
    height: 60%;
  }
}

.flickity-page-dots {
  position: absolute;
  width: 100%;
  bottom: -25px;
  padding: 0;
  margin: 0;
  list-style: none;
  text-align: center;
  line-height: 1;

  .dot {
    display: inline-block;
    width: 10px;
    height: 10px;
    margin: 0 8px;
    background: #333;
    border-radius: 50%;
    opacity: 0.25;
    cursor: pointer;

    &.is-selected {
      opacity: 1;
    }
  }
}

.flickity-rtl {

  .flickity-prev-next-button {

    &.previous { 
      left: auto;
      right: 10px;
    }

    &.next { 
      right: auto;
      left: 10px;
    }
  }

  .flickity-page-dots { 
    direction: rtl; 
  }
}
```

**Comment by denisemenov** [comment]
@theenoahmason great job! It will be amazing, if @desandro add scss to flickity to prevent next error: 
```
DEPRECATION WARNING on line 1, column 9 of C:/Users/denis/Server/www/denis.blog/wp-content/themes/dev/sass/_lib.scss:
Including .css files with @import is non-standard behavior which will be removed in future versions of LibSass.
Use a custom importer to maintain this behavior. Check your implementations documentation on how to create a custom importer
```
Sometimes it's important to have all css in one file and it's easiest way to do it.

**Comment by nam-co** [comment]
Sass has reverted the .css restriction, so if I’m not mistaken is back

Regards
Michael

**Comment by desandro** [comment]
Sounds like this has been resolved with the Sass project.
