### ISSUE TITLE
Arrow button still active even though last item is in view

### ISSUE THREAD

**Issue by vinit-m** [metafizzy/flickity#845]
Hey, I need to disable the arrow button when the last slide is shown in the viewport, instead the arrows just changes the selected slide. The button is still active even though the slider wont slide (as the last item is contained)

Here is the code pen:
https://codepen.io/vinit-m/pen/XxbaBV

**Comment by desandro** [comment]
See https://github.com/metafizzy/flickity/issues/289#issuecomment-157488885
