### ISSUE TITLE
flickity tries to use jQuery Deferred function even if jQuery doesn't support it

### ISSUE THREAD

**Issue by vaidotas-adf** [metafizzy/flickity#846]
Consider a legacy website where jQuery 1.4.4 is loaded before flickity. Using `imagesLoaded: true` option results in error `Uncaught TypeError: $.Deferred is not a constructor` as flickity finds $ and does not check if Deferred function is available. Would be nice if flickity did additional check to see if Deferred function is actually available or even option to force disable jQuery usage.

**Test case:** https://codepen.io/anon/pen/GYJvGb

**Comment by desandro** [comment]
Thanks for reporting this issue. See discussion at desandro/imagesloaded#257
