### ISSUE TITLE
IE9 performance

### ISSUE THREAD

**Issue by ivancuric** [metafizzy/flickity#85]
Hey, I know that it isn't the top-of-the-line browser, or that it has a huge market share, but sadly it's still out there.
On IE9 there is a massive performance hit when moving the slider.

**Comment by desandro** [comment]
Thanks for reporting this issue. I've tried to optimize Flickity for performance. I'm not sure if there's any additional improvements that can be done for IE9. On top of that, IE9 itself has dwindling market share. [IE8 is more popular than IE9](http://caniuse.com/usage_table.php). I've got to make a call and say that developing for IE9 is not worth the effort.
