### ISSUE TITLE
Stop autoplay after the second slide is played

### ISSUE THREAD

**Issue by tomasdrvota** [metafizzy/flickity#850]
Hello, 
I am using Flatsome theme, which uses Flickity slider. I need my slider to stop autoplay after the second image is showed. The slider has just two slides. I need them to autoplay but not to repeat. 

I found some old case, but it doesn´t work for me. You can find my solution in the attachment and in the case study. Case study: https://codepen.io/tomasdrvota/pen/PyprJB

URL of the website is www.flatwebs.cz

Thank you for your answers. 

![fw1](https://user-images.githubusercontent.com/43969206/46734208-d8d61380-cc92-11e8-8ea8-a6fb21a57798.PNG)
![fw2](https://user-images.githubusercontent.com/43969206/46734209-d8d61380-cc92-11e8-921b-c4c74b9969ab.PNG)
![fw3](https://user-images.githubusercontent.com/43969206/46734210-d8d61380-cc92-11e8-9433-3334e9880ebb.PNG)

**Comment by desandro** [comment]
Here's that demo working just fine: https://codepen.io/desandro/pen/ReZVom. Be sure to remove HTML initialization and just use jQuery.

**Comment by tomasdrvota** [comment]
Hello, 
I still get $(...).flickity is not a function. Where could be the problem?
