### ISSUE TITLE
Upon sliding, Flickity selects random cell when "contain=true"

### ISSUE THREAD

**Issue by chessydk** [metafizzy/flickity#854]
https://codepen.io/chessydk/pen/BqGEod

Try sliding in either direction a couple of times. When sliding stops, a random cell is selected. It could be the middle, the one to outermost left or to the outermost right.

When contain=false it works according to cellAlign.

**Comment by desandro** [comment]
Thanks for reporting this issue. Flickity is behaving as expected. Although, it's a bit quirky with `contain` enabled:

+ When dragging to the ends of the container, Flickity will select the first/last cell
+ When dragging inside the container, Flickity will select the closest cell

**Comment by desandro** [comment]
Because the contain behavior requires this kind of selection. It works this way because that's how containment works. Sorry for the tautological argument. But, in other words, it works this way because its the most straightforward method that works with Flickity's underlying API.
