### ISSUE TITLE
Function call option values

### ISSUE THREAD

**Issue by arl1nd** [metafizzy/flickity#855]
Hi there,

I was wondering if you can provide function-call options values so whenever the 'resize' is triggered from Flickity these 'function' values options will have chance for alternatives upon screen size, an example:

<pre>let myCarousel = new Flickity( {
  wrapAround : () => window.innerWidth > 992,
  groupCells : () => {
    let cells = 4;
    if ( window.innerWidth < 992 ) {
      cells = 3;
    } else if ( window.innerWidth < 768 ) {
        cells = 2;
    }
    return cells;
  }
} );</pre>

I think this would increase the flexibility and make Flickity even more responsive friendly.

**Comment by desandro** [comment]
See one possible solution here: https://github.com/metafizzy/flickity/issues/233#issuecomment-218465900 Let's keep discussion on that thread.
