### ISSUE TITLE
Keep getting error when installing with npm

### ISSUE THREAD

**Issue by yellow1912** [metafizzy/flickity#856]
When I run npm, I keep getting

Can't resolve 'flickity-imagesloaded'

If I install flickity-imagesloaded then I get

 Can't resolve 'flickity-as-nav-for'

If I install flickity-as-nav-for then I get back to the first error.

**Comment by desandro** [comment]
Thanks for reporting this issue.

+ What command are you initially running?
+ What version of npm are you using?
