### ISSUE TITLE
Carousel not working with Vue.js

### ISSUE THREAD

**Issue by sharjeel619** [metafizzy/flickity#859]
I have been trying to use this carousel for the past 2 days now. I have followed the docs as it is, but the carousel is not working and the image are loading vertically in a column. Am I missing something? I have also added the "https://unpkg.com/flickity@2/dist/flickity.min.css" css in my index.html file. But still doesn't work.

**Comment by kr05** [comment]
I'm trying to use this carousel with lit-element, and I'm also having some trouble. I initially had the same problem as you...are you by any chance instantiating the carousel with the data-flickity atttibute? If so, try instantiating the carousel using javascript. I wish I could say this solves the problem, but it only presents new ones, at least for me. The carousel seems to instantiate, but it is extremely buggy and unusable. My guess is that it doesn't play well with components or the shadow DOM.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
