### ISSUE TITLE
Is it possible to stop freescroll exactly on one cell ?

### ISSUE THREAD

**Issue by thebat98** [metafizzy/flickity#860]
Hi,

I'm using this plugin on many carousels and one of them has freeScroll and wrapAround options.
I would have to know if its possible to center the carousel on one cell when scrolling stops ?

Regards,
thebat

**Comment by desandro** [comment]
> I would have to know if its possible to center the carousel on one cell when scrolling stops ?

If you want to center the carousel on a cell, then you do not want freeScroll to be enabled.

Another solution is to [`select`](https://flickity.metafizzy.co/api.html#select) a cell on [`settle`](https://flickity.metafizzy.co/events.html#settle)

**Comment by thebat98** [comment]
Hi,

Sorry but why did you close this issue ?

Regards,
thebat

**Comment by desandro** [comment]
I've provided my best answer to your question. But the behavior you're looking for is not explicitly supported in Flickity. So that's about it.
