### ISSUE TITLE
Flickity + Bootstrap Modal + fixed-width cells = Sadness  

### ISSUE THREAD

**Issue by robertmclaws** [metafizzy/flickity#862]
So, I'm trying to build an app that has Flickity inside a Bootstrap Modal. The cells are fixed-width (because I intend to put UI in them), and I've set the required properties accordingly. However, something about the math is wrong, because the first cell is 50% hidden, and I'm not sure why.

![image](https://user-images.githubusercontent.com/1657085/48319494-b3635f00-e5dc-11e8-91b9-ddb896a9af32.png)

**Test case:** https://codepen.io/anon/pen/aQmRwK

The problem is made worse when you try to groupCells. For every cell that you add to the group, 50% of a cell disappears.

![image](https://user-images.githubusercontent.com/1657085/48319497-c5dd9880-e5dc-11e8-98d4-cf79ab704860.png)

**Test case:** https://codepen.io/anon/pen/eQdQOj

Any ideas how to solve this one? Thanks!

**Comment by desandro** [comment]
So close! Looks like you have a typo:

``` js
$('#newStackItemModal').on('shown.bs.modal', function (e) {
  $(".carousel").flickity('resize');
  console.log('shown')
});
```

You can `#ewStackItemModal`. Ew!

[See demo on CodePen](https://codepen.io/desandro/pen/d04788520168bc0f8fcd9be47ae4dba3/)

**Comment by robertmclaws** [comment]
![image](https://user-images.githubusercontent.com/1657085/48512689-26ace100-e828-11e8-9bb7-7c8a24895607.png)

Gah, I was so sure I'd found a real bug! Thanks for the second eyes on this, and for building a great control.  :)
