### ISSUE TITLE
Keyboard on events

### ISSUE THREAD

**Issue by richgcook** [metafizzy/flickity#866]
I can't quite create a reduced edge case unfortunately as my setup is quite complex.

I am using `fullpage.js` and upon reaching the last flickity slide, if the user clicks again, then it should advance to the next `fullpage.js` section. This is absolutely fine to do with clicks.

```
 $slider.on('select.flickity', function() {
	if (flkty.selectedIndex == flkty.cells.length - 1) {
		$slider.one('pointerUp.flickity', function(event) {
			var nextCount = $article.next().data('count');
		    	$.fn.fullpage.moveTo(nextCount, 0);
		});
	}
});
```

However I'm wondering if it's at all possible with the keyboard keys too? There seems to be events for touch, drag, pointer etc but not keyboard. I can't send to the user to the next `fullpage.js` section before the user interacts again otherwise they'll skip the last image.

Any thoughts?

**Comment by desandro** [comment]
I recommend just using `select` or `change` event and _do not_ try mapping interactions to touch or keyboard events. The `select` and `change` events are triggered however a cell is selected, via swipe, page dot click, keyboard, or other API call.

**Comment by richgcook** [comment]
@desandro Thanks for your help on this! Much appreciated.
