### ISSUE TITLE
Slider has initial setting of transform:translateX(-41px) 

### ISSUE THREAD

**Issue by gebigoma** [metafizzy/flickity#867]
**Test case:** https://codepen.io/tunasandwich/pen/YRVwNy?editors=1100

Although I do have a test case I wasn't able to successfully reproduce the issue I'm having. 

My Slider has initial setting of transform:translateX(-41px) which causes the left image to be pushed out of the slider. Also, the transform:translate() is also causing problems with the last image of the slider continuing to slide and not aligning with the edge of the container it's in. 

I've searched through the existing issues and haven't found anything relevant to my issue. 

Any insight much appreciated!!

**Comment by desandro** [comment]
could this be caused by a scrollbar? Try adding this CSS `html { overflow-y: scroll; }`

**Comment by gebigoma** [comment]
Yeah, that css is already in my stylesheet. =T

**Comment by desandro** [comment]
Sorry without a reduced test case demonstrating the issue there's no way for me to bug this problem.

**Comment by divixdev** [comment]
in my case, images were not snapping to the edge just the half it .
to fix it add : 
             cellAlign: 'center',
              groupCells: '80%'
