### ISSUE TITLE
Images show on all devices—except new iPad Pro

### ISSUE THREAD

**Issue by jayhlee** [metafizzy/flickity#868]
Head-scratcher. The images on my slides work properly on all devices except for the new iPad Pro (12.9). On both Chrome and Safari on the new iPad Pro, the images don't show and the prevNextButtons get thrown off—again, only on the new iPad. On all other devices and browsers, there's no issues.

When I use Safari's Responsive Design Mode and set it to the new iPad Pro, it even shows that the images load properly. Not sure what's going on. 

Here's two examples. You can use any other device and it works properly. I also tried to create a reduce case, but this is the best I can do.

**Test case:** https://alphabeta.customliftsolutions.com/blog/first-blog
**Test case:** https://alphabeta.customliftsolutions.com/

**Comment by desandro** [comment]
Thanks for reporting this issue. Without a physical device, I won't be able to properly debug this issue ¯\_(ツ)_/¯. Have you tried using [imagesLoaded](https://flickity.metafizzy.co/options.html#imagesloaded) instead of lazyLoad?

**Comment by jayhlee** [comment]
Yes, that seems to have fixed the issue. Thanks much! Still have no idea what makes it not work on the new iPad Pro, though. ¯_(ツ)_/¯
