### ISSUE TITLE
Multiple Flickity on one page (different types)

### ISSUE THREAD

**Issue by ste6412** [metafizzy/flickity#869]
https://codepen.io/ste6412/pen/qQVwxx

I have multiple flickity sliders on one page.  One uses thumbnails for nav and the others are the basic slider. I have the thumnails as nav slider working.  

I can't seem to get the other basic sliders working independently.  Can you help me to see where I have gone wrong?

**Comment by desandro** [comment]
You can add `data-flickity` to the other `.carousel` elements to initialize Flickity on them. https://codepen.io/desandro/pen/4d05d16db88db3a304e5965e1681c237/

**Comment by ste6412** [comment]
@desandro Thank you very much (love the slider btw).

I do have another issue.  I have a page with divs that are hidden and accessed via tabs (using javascript) within each div are multiple sliders.  When I visit each tab the sliders don't work unless I right click and inspect element (then only the current viewable sliders work) as soon as I switch tab (still technically on the same page) the sliders don't work. I've attached some images to illustrate.

![capture](https://user-images.githubusercontent.com/32206042/48850170-f2916d00-ed9f-11e8-9ae3-a7336b64db00.PNG)
![capture2](https://user-images.githubusercontent.com/32206042/48850175-f6bd8a80-ed9f-11e8-8c54-9661cbe0fe87.PNG)
![capture3](https://user-images.githubusercontent.com/32206042/48850177-f9b87b00-ed9f-11e8-9e23-4201390ad48f.PNG)

**Comment by desandro** [comment]
Trigger [`resize`](https://flickity.metafizzy.co/api.html#resize)

> If Flickity is initialized when hidden, like within a tab, trigger resize after it is shown so cells are properly measured and positioned.

``` js
$('.button').on( 'click', function() {
  $carousel.show()
    // resize after un-hiding Flickity
    .flickity('resize');
});
```

**Comment by ste6412** [comment]
Thanks for you response :)

There is now a console error...

Uncaught ReferenceError: $carousel is not defined

**Comment by desandro** [comment]
change `$carousel` to the selector or [jQuery object](http://fizzy.school/cache-jquery-objects) of your carousel element. I'll leave this up to you.

**Comment by ste6412** [comment]
Thanks for the answer.  I'm obviously nowhere near as good at javascript as you as I don't really know what you mean by your answer?

I have done this... and it didn't work?

`jQuery('.tablink').on( 'click', function() {
  $carousel.show('.carousel-cell')
    // resize after un-hiding Flickity
    .flickity('resize');
});`

I know you're very busy but I would really appreciate your help on this matter.  Thanks

**Comment by ste6412** [comment]
I have also tried this method...

`jQuery('.tablink').on( 'click', function() {
  jQuery('.carousel-cell')
    // resize after un-hiding Flickity
    .flickity('resize');
});`

.. to no avail

**Comment by desandro** [comment]
Can you post all your JS that relates to Flickity?

**Comment by ste6412** [comment]
Hi,  

thank you for your continued help :)

The only JS I have used is...

`jQuery('.tablink').on( 'click', function() { jQuery('.carousel-cell') // resize after un-hiding Flickity .flickity('resize'); });`

...I guess I'm missing something?

**Comment by desandro** [comment]
Sorry I will not be able to provide personal support for your issue.

**Comment by SabihaZulfiqar** [comment]
@desandro 

> Trigger [`resize`](https://flickity.metafizzy.co/api.html#resize)
> 
> > If Flickity is initialized when hidden, like within a tab, trigger resize after it is shown so cells are properly measured and positioned.
> 
> ```js
> $('.button').on( 'click', function() {
>   $carousel.show()
>     // resize after un-hiding Flickity
>     .flickity('resize');
> });
> ```

I can't thank you enough! This saved my life. Thanks a million.
