### ISSUE TITLE
As Nav For Wrap Around

### ISSUE THREAD

**Issue by peterph-am** [metafizzy/flickity#87]
I've been playing around with flickity and I'm really liking it so far!

The *asNavFor* extra feature is awesome but I've noticed that the nav gallery doesn't wrap around even with *wrapAround* set in the options.

When I navigation through the main gallery, the nav gallery also slides fine, until i get to the end. The main gallery wraps around to the first slide but the nav gallery animates back left to the start.

It would be nice if they could both wrap around. I hope that made sense..

**Comment by desandro** [comment]
Thanks for this feature request. Yes, I've noticed this as well. I have created a demo to resolve this, but I'm considering adding this functionality in to Flickity proper.

http://codepen.io/desandro/pen/ZYqNrO

**Comment by peterph-am** [comment]
Yeah I feel it would be a nice function to add to the core (is that what you meant by Flickity proper?)

**Comment by desandro** [comment]
Closing this issue and merging it with #113
