### ISSUE TITLE
Fullscreen not resizing images correctly until I change viewport size

### ISSUE THREAD

**Issue by lukezona** [metafizzy/flickity#870]
Can't find a way to replicate the issue but is pretty simple:
when in a desktop I put the slider in fullscreen it put the images way bigger than needed and they overlay ([screenshot](https://imgur.com/gallery/bdTdlkt)).

When I change the viewport (even just one pixel) they fix on their own.

Any idea on what could be going on and how to fix this?

EDIT: Forgot to put the code, here's a snippet with the main part: [codepen](https://codepen.io/lukezona/pen/Gwyaqa)

**Comment by desandro** [comment]
Thanks for reporting this issue. If the images are not resizing correctly it could either be a imagesLoaded or a CSS bug. Sorry, without a reduced test case I cannot debug this issue completely.

**Comment by noahsscott** [comment]
@lukezona I was having a similar issue with text only carousels where the height would correct itself once I resized. I solved it by setting an initial viewport size for my carousels on desktop which corrected the problem without having to resize the browser.

**Comment by DavidOliver** [comment]
I was also having a similar issue. It seemed that sometimes, on an uncached page load, the flickity viewport could be set to zero by flickity. On the other hand, in production it would sometimes be non-zero but the images would be incorrect sizes/aspect ratios.

I was loading flickity via unpkg with the `defer` script tag attribute. I *think* I've resolved the issue by putting the script tag just before the closing body tag instead. I'll keep an eye on it and update here if I find the issue reoccuring after all.

**Comment by DavidOliver** [comment]
Turns out that didn't fix the issue. It seems Chromium is more susceptible to this than Firefox; I wonder if it's because Chromium runs scripts quicker and so is getting to the dimenion-setting earlier, before the first image has loaded. I'm going to see if I can delay the running of flickity until after at least one image has loaded.

**Comment by DavidOliver** [comment]
Actually, looking through flickity's options I found [imagesLoaded](https://flickity.metafizzy.co/options.html#imagesloaded).

> Unloaded images have no size, which can throw off cell positions. To fix this, the imagesLoaded option re-positions cells once their images have loaded.

With this option set to true, things seem to be working well so far. I wonder if there's ever any reason for this repositioning on image load not to take place?

**Comment by abraxxas** [comment]
We have the same issue with our gallery, but only in opera. I checked in chrome/brave/vivaldi but opera seems to be the only chrome derivate where it happens. When opening the full-screen i saw that the flickity-slider and the carousel-cell have wrong translateX and left offset in the fullscreen mode. If i resize it resets and works for fullscreen, but this breaks the gallery for non-fullscreen (and never works again until reload, even after resize)
