### ISSUE TITLE
Selectively show dots for only some cells

### ISSUE THREAD

**Issue by be-still** [metafizzy/flickity#871]
Is it possible to selectively show dots for only certain cells (e.g., using a specified class)? I am not using group cell because I want every click of the next/prev arrow to advance exactly one cell no matter what. 

Ideally, as you advance, if you're on a cell that does not have a corresponding dot, the closest previous cell's dot would be "selected" (even though the cell that's actually selected/in focus would be different). 

Example: There are 4 cells. Cells 1, 3, and 4 have corresponding dots (so there are only three dots total). Every click of the next arrow advances one cell. You start on cell 1 and the first dot is highlighted. Click next, and you advance to cell 2, but the dots stay the same. Click next, and you advance to cell 3 and now the second dot (cell 3's) is highlighted. 

Thank you!
Ben

**Comment by desandro** [comment]
Thanks for reporting this issue. Sorry, there is no built-in way to achieve this behavior. You would have to build your own [custom navigation UI](https://flickity.metafizzy.co/extras.html#custom-navigation-ui).
