### ISSUE TITLE
Multiple carousels with asNavFor and data-flickity without unique selectors

### ISSUE THREAD

**Issue by dexstor** [metafizzy/flickity#872]
I can have multiple/any number of Flickity carousels with the "asNavFor" option on a single page. 

The markup is generated by a CMS and I'm initializing the Flickity instances and adding the options using the data-flickity HTML attribute as this way I don't have to worry about generating unique IDs and selectors/classnames for each carousel if I was initializing them with JS.

However, how can I sync each main carousel with the navigation carousel without using unique selectors - all main carousels will have the class "carousel-main" and all navigation carousels will have the class "carousel-nav"?

If I was initializing the carousels with JS and not HTML data attribute, I could use something like jQuery .closest() and find the closest ".carousel-main" to each ".carousel-nav" - but how can I do this when initializing carousels with data-flickity='{ "asNavFor": ".carousel-main" }' ?

Example:

https://codepen.io/anon/pen/qQYKER

**Comment by desandro** [comment]
> However, how can I sync each main carousel with the navigation carousel without using unique selectors 

Sorry, you _need_ to use unique selectors to specify individual nav/main carousel pairs. If you have a unique ID for each carousel from the CMS, you could add something in your template like:

``` html
<div class="carousel carousel-main carousel-{{post_id}}" data-flickity">...</div>
<div class="carousel carousel-nav" data-flickity='  { "asNavFor": ".carousel-{{post_id}}" }
 '">...</div>
```

**Comment by dexstor** [comment]
Thank you, I wondered if there was a clean and simple way to dynamically set the selector in the data attribute, but I guess there currently isn't.

I ended up doing the exact same thing that you suggested.

**Comment by zakirsajib** [comment]
is it possible to select multiple selectors something like:

`asNavFor: $('.carousel-main, .carousel-contents'),`
