### ISSUE TITLE
Conditionally load flickity based on array length

### ISSUE THREAD

**Issue by sheriffderek** [metafizzy/flickity#873]
Possible feature: Conditionally load flickity based on array length:

In a recent project, we have a bunch of slider-like rows. When they have 3 or less items, the item act as a static row - and when they have 4 or more items - we pull in the slider. It would be fun if there was a parameter for this purpose.

[one] [two] [three]      (three or less - don't even get flickity out of bed)

<  [one] [two] [three] > [four]      (we need you, buddy! Get initialized!)

![screen shot 2018-11-27 at 2 18 37 pm](https://user-images.githubusercontent.com/2066617/49115423-9e7b0280-f24f-11e8-8b14-5690866d8f02.png)

**Comment by desandro** [comment]
Thanks for this feature request. Rather than building this option into Flickity, I think the most straightforward solution is to write your own JS to handle this kind of behavior.
