### ISSUE TITLE
Add attribute to specify larger image version for fullscreen view

### ISSUE THREAD

**Issue by wc-matteo** [metafizzy/flickity#876]
And the image switch happening when entering/exiting fullscreen

**Comment by desandro** [comment]
To be clear, do you want to show a different image when fullscreen?

**Comment by wc-matteo** [comment]
Thank you.

Yes, I had changed the src using the fullscreenChange event. I was wondering if this could be something offered out of the box.

**Comment by desandro** [comment]
I am considering a separate library that focuses just on photo carousels. But, for Flickity specifically, I think this behavior is better address in your code, to allow the most flexibility.
