### ISSUE TITLE
background-attachment: fixed is not displaying 2nd slide

### ISSUE THREAD

**Issue by clarknelson** [metafizzy/flickity#878]
I have heard this is a css3 bug, but I haven't been able to get it to work at all 😣🤢😵 help please!

**Test case:** https://codepen.io/clarknelson/pen/ebBJee

**Comment by desandro** [comment]
Thanks for that. Looks like this is a browser issue. `background-attachment: fixed` works with natural page scrolling, whereas Flickity uses transforms for positioning elements. If you want to use `background-attachment: fixed`, then you're better off not using Flickity and using a simple `div` with`overflow-x: scroll`.
