### ISSUE TITLE
Not fluid slide animation - bad performance on iPhone

### ISSUE THREAD

**Issue by zzseba78** [metafizzy/flickity#879]
**Test case:** https://codepen.io/desandro/pen/azqbop

I notice a very bad animation performance on iPhone, even on the docs ( whitout images, not much slides on page ), the transition doesn´t look fluid at all.

Someone else noticed this?

**Comment by desandro** [comment]
Looks good to me ¯\_(ツ)_/¯

**Comment by zzseba78** [comment]
Sorry, works perfectly, just have my phone on low battery, and affect performance 😄 

Closing this! Great plugin.
