### ISSUE TITLE
Trying to trigger background color change based on index number

### ISSUE THREAD

**Issue by Sorcutt** [metafizzy/flickity#883]
Can anyone give a little javascript advice? This might be a simple answer (I'm hoping). I'm trying to use the "settle" event to trigger a different added class per slide index. I'm not really sure how to go about structuring that. I tried using if else but that doesn't seem like the right fit, because it seems like once it matches one of the index numbers it finishes instead of changing every time there's a new index number.

**Comment by desandro** [comment]
Here's some code to get you started:

``` js
var indexClass;

$gallery.on( 'change.flickity', function( event, index ) {
  // remove previous class
  $gallery.removeClass( indexClass );
  // set and add new class
  indexClass = 'index-' + index;
  $gallery.addClass( indexClass );
});
```

This changes the class on the gallery element to match the selected cell. It works on `change` event, but you can change the name of that to `settle`.
