### ISSUE TITLE
Align cells after flicking in freeScroll mode

### ISSUE THREAD

**Issue by nroyall** [metafizzy/flickity#885]
Hi David, this is more of a feature request than a bug:

I'm trying to create a slider that's super flickable, has infinite looping, and stops immediately if clicked/tapped. When stopped, the clicked slide needs to align left.

**ie: I need the motion and fluidity of freeScroll, with cell alignment after the slider stops.**

Any ideas whether I can achieve something like this with Flickity?

I tried using staticClick to align the clicked slide. Most of the time, this causes the slider to whizz through a few loops before settling on the clicked slide.

Demo: https://codepen.io/naomir/pen/BvGRBJ

**Comment by nroyall** [comment]
Maybe a better way to ask this is: 

could we have an option to **not** run callbacks when using the Flickity select method? 
ie: flkty.select( index, isWrapped, isInstant, runCallbacks)
If runCallbacks is false, the transition will not produce transition events.

...this way, I could run flkty.select on the settle event, without producing an infinite loop, allowing me to align the slide after it has settled. 
Thanks!!

**Comment by desandro** [comment]
Hello! Thanks for opening this issue.

I kinda understand the behavior you're asking for. But I'm not sure if its a desired behavior enough to built into Flickity as a full-fledged feature. You could build this feature as an add-on with a [duck punch](https://metafizzy.co/blog/duck-punching-prototype/).

``` js
var applySelectedAttraction = Flickity.prototype.applySelectedAttraction;

Flickity.prototype.applySelectedAttraction = function() {
  var freeScrollSlowDown = this.options.freeScrollSlowDown;
  if ( freeScrollSlowDown ) {
    this.applyBrakes( freeScrollSlowDown )
  } else {
    applySelectedAttraction.apply( this, arguments );
  }
};

Flickity.prototype.applyBrakes = function( freeScrollSlowDown ) {
  // do not apply brakes if pointer down or no slides
  var dragDown = this.isDraggable && this.isPointerDown;
  if ( dragDown || !this.slides.length ) {
    return;
  }
  var distance = this.selectedSlide.target * -1 - this.x;
  var isValidNumber = typeof freeScrollSlowDown == 'number' && freeScrollSlowDown > 0;
  var deceleration = isValidNumber ? freeScrollSlowDown : 20;
  this.velocity = ( distance * (1-this.getFrictionFactor()) ) * deceleration;
};
```

See demo https://codepen.io/desandro/pen/pqmabE


I think `applyBrakes` could be refactored a bit. I'm curious if `freeScrollSlowDown` is necessary when `freeScrollFriction` is already in use.

**Comment by nroyall** [comment]
Thanks! This is perfect!

I completely forgot about duck punching. I think you've pointed me to that in the past. It seems like the ideal use case for it. Thanks for taking the time to look at this and improve my code! 💯

**Comment by desandro** [comment]
This is still a valid issue. A super-flickable carousel that aligns to cells should be possible with Flickity without a lot of extra code. You should be able to adjust `friction` or another option to produce this kind of behavior.

**Comment by mgmbh** [comment]
I'd appreciate such a feature – basically a super flicky (unsticky) slider without using freeScroll. I have a similar usecase where there could easily be 300 images in a slider. On mobile you want to quickly flick/scroll through the slides but when the slider stops, cellAlign (in my case 'center') has to be effective.

You can somewhat make it work using friction (and selectedAttraction). But since a low value for friction also makes the slider bouncy, the behaviour gets pretty weird. It would be nice if one could have a low value for friction without making the slider bouncy. I think that would solve many flicking issues on mobile.

See: https://codepen.io/anon/pen/GepNrQ but it's suuuper bouncy :)

**Comment by desandro** [comment]
This issue didn't get much outside interest so I am now closing.
