### ISSUE TITLE
bower.json only includes index.js

### ISSUE THREAD

**Issue by silvenon** [metafizzy/flickity#89]
The `main` field in `bower.json` doesn't include all of Flickty, just its `index.js`.

**Comment by silvenon** [comment]
After more reading, is using this only with Bower (+ [wiredep](https://github.com/taptapship/wiredep)) supported?

**Comment by desandro** [comment]
bower.json `main` is a contentious area. I consider it to be the main entry point for each kind of file, not a list of all the required files, similar to npm's package.json `main`. Sorry, Flickity will not work with wiredep.

**Comment by silvenon** [comment]
Darn. I guess I should learn how to use Browserify anyway, it seems pretty popular.
