### ISSUE TITLE
Can i have center big item ?

### ISSUE THREAD

**Issue by mibercsk** [metafizzy/flickity#893]
Is it possible to have a large item located in the center of the slider viewport?

I tried with css by adding width and height to the selected element in the slider, but the slider has to recalculate the next and previous element positions, that's what I deduced, I tried with the events offered by the plugin and did not succeed.

I think it can be solved if the slider increases the width and height of the current slider item and decreases the width and height of the previous and / or next slider item, starting from the initial values of the slider item to the values of the current slider item.

Normal slider item width 390px(in percentage) and height 267px
Selected slider item width: 560px(in percentage) and height 360px

Gap slider items is 30px

**Test case:** https://codepen.io/mibercsk/pen/LqGPOK

**Comment by desandro** [comment]
I made a similar demo, but it uses CSS transforms to handle the scaling: https://codepen.io/desandro/pen/jEpxqJ

**Comment by mibercsk** [comment]
It's a good idea, but it does not help me, I need to recalculate my width and height from bigger to lower, I managed partially, but the slider has to be recalculated to its movement, the recalculate part I do not know how to do it, I tried with other plugins and I can not get the desired result, I would like to stay in this plugin because I can use percentage to the width of the elements, which helps me very well on the responsive side.

Recalculate ideea, center item is 560px width and 360px height, when change slide item, left item before center item need to go on 360px width and 267px height slowly pixel by pixel(in our case procentage by procentage) and right item after center item need to go bigger to 560px width and 360px height, same pixel by pixel(in our case procentage by procentage).


If you do not understand well what I mean and get, I will make a demo with the desired effect.

Thank you.

**Comment by desandro** [comment]
You can resize & reposition items with [`reposition` method](https://flickity.metafizzy.co/api.html#reposition), but Flickity does not support animating that repositioning (its hard to achieve while accounting for other features like contain and wrapAround). That's why I recommend using the CSS transforms technique as you can animate size.

**Comment by mibercsk** [comment]
Ok, i understand, this ideea or what i need is similar to progressBar but need to start from certain point and stop at certain point when the center item is selected.

Thanks, I'll look for other plugin.

**Comment by Fayyazdero** [comment]
I will appreciate if someone helps me with centerMode
