### ISSUE TITLE
settle event doesnt trigger if cell select is instant

### ISSUE THREAD

**Issue by neuedeutsche** [metafizzy/flickity#895]
Based on context I am animating the transition or in some cases have it as instant.
I would assume that the event would trigger my follow up function in both cases.
Even if the settling is instant. (there was no motion to begin with or it was lightning fast ;) 

thoughts?

**Comment by desandro** [comment]
What are you trying to achieve? We may be able to resolve this by adding a separate event listener on `change`.

**Comment by dergraph** [comment]
hard to explain.
my argument is that settle should be the event that is triggered when the cell is in its target position. no matter how fast it got there.

seems odd that this event would not be triggered if i switch to is instant.

i have tweaked my code but the concern was that i dont wanna start running functions that may impact performance of the animation (loading some additional contents). so i would only save these for the settle callback. and do some others on change.

**Comment by desandro** [comment]
Here's a [duck-punch](https://metafizzy.co/blog/duck-punching-prototype/) to trigger settle when it skips animation:

``` js
var positionSliderAtSelected = Flickity.prototype.positionSliderAtSelected;
Flickity.prototype.positionSliderAtSelected = function() {
  positionSliderAtSelected.apply( this, arguments );
  this.dispatchEvent( 'settle', null, [ this.selectedIndex ] );
};
```

**Add a 👍  reaction** to this issue if you would like to see this feature added. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

**Comment by giacomoalonzi** [comment]
@desandro there's a way to speed up the triggering of settled state?

**Comment by desandro** [comment]
@giacomoalonzi You can adjust the physics variables with affect transitions and settling with [selectedAttraction and friction](https://flickity.metafizzy.co/options.html#selectedattraction-friction)

**Comment by giacomoalonzi** [comment]
thank you @desandro
