### ISSUE TITLE
Can we get better docs on styling with images?

### ISSUE THREAD

**Issue by marbuser** [metafizzy/flickity#896]
I just thought I'd open this since I really love flickity, but the styling documentation could really use some work.

Here are some reasons I think it could be improved;
- No inclusion of concepts such as aspect ratios. This is a carousel, it's pretty much going to be used with images in 95% of cases and it's really upsetting to see no explanation of this anywhere.
- Huge use of so called “Magic numbers”. In a lot of the demos, there is just a very specific number given to both width and height without any context, but as soon as you implement that into your own code and change it by even 1% or 1px, it completely ruins the styling. It would be nice to have some sort of explanation as to WHY these numbers where picked and more importantly HOW they were picked.
- Sort of related to the first point, but in the style section of the docs, there is no usage of images at all. It's all used with the green slides. There really should be some more explanation into other use-cases.

Hopefully you can consider these improvements. :)

**Comment by desandro** [comment]
Hello! Thanks for this input. Hmm, yeah. I've offloading the image styling stuff to image demos like [imagesLoaded](https://flickity.metafizzy.co/options.html#imagesloaded) and [lazyLoad](https://flickity.metafizzy.co/options.html#lazyload). Specifying the CSS stuff in the Style section makes sense.
