### ISSUE TITLE
Carousel is constantly 0 height.

### ISSUE THREAD

**Issue by frequentredundancy** [metafizzy/flickity#897]
Forgive me, I'm better at designing what I want to achieve rather than trying to code it at the moment. (Although I still provided a test case)

Here is what I want to achieve basically.
![image](https://user-images.githubusercontent.com/45308208/52167905-7337f680-275d-11e9-88e1-54353c14bd4c.png)

I want it to show 3 images on a single page, but when you scroll it scrolls by 1 image if that makes sense.

I also want to preserve the aspect ratio of the images. I want the carousel to have 100% the height of the images.

From my code, I have to hard-code a height for it to even display which causes stretching. If I don't, then it doesn't even display the images. I've looked at all the demos, none of their methods work.

Test case: https://codepen.io/anon/pen/XORYNO

**Comment by desandro** [comment]
> I want the carousel to have 100% the height of the images.

You've set `position: absolute` on the images, removing them from the sizing of the cells. Try removing that.
