### ISSUE TITLE
Default next-prev buttons does nothing on click

### ISSUE THREAD

**Issue by LuXDAmore** [metafizzy/flickity#899]
### Version

v2.2.0

### Reproduction link

[Codepen](https://codepen.io/LuXDAmore/pen/YBQjZV)

### Steps to reproduce

Updated Flickity to latest version

### What is expected?

To work as expected

### What is actually happening?

Nothing

### Additional comments?

- Goes on old versions;
- In console (Chrome DevTools), targeting `next-button`: `$0.click();` seems work as expected;
- Maybe it's bug with Chrome v72?

**Comment by desandro** [comment]
Thanks for reporting this issue and for providing a CodePen. I was not able to reproduce this issue in Chrome 73 or Firefox 65. And no one else has chimed in 7 days. Can you double-check that this is still occurring?

**Comment by LuXDAmore** [comment]
Thank you for your reply @desandro , i've tried again but without success..
I hope that this is something happening only on my PC 😆,
i'm unable to use flickity's prev-next buttons 🤷‍♂️

I've seen i have the same problem in the bottom navigation `flickity-page-dots`.
It's only related to click event (no pointer-down).

Do you have any other ideas? How can i help you?

`Chrome v73.0.3683.20 dev (64 bit), On latest Windows 10`

**Comment by cwhittl** [comment]
I am seeing this currently on ios 11 if it helps

**Comment by posttoast** [comment]
Same problem here (also in luXDAmores CodePen), but only in Chromium (latest version) under Windows (tested in Windows 7). Chrome (not Chromium ;) ) works fine. Chromium under MacOS also works fine.

It seems all click events are disabled, I have slides with hyperlinks in them, they also don't work.
