### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by edwardr** [metafizzy/flickity#901]
I have some questions about your interpretation of the GPL v3 riders on what constitutes a derivative work.

Reading through other comments you made, it seems that you've indicated to others that if Flickity is used on a commercial site, the entire site's source must be licensed under GPL.

My interpretation would be that only the gallery portion -- i.e. the aspect of the application that is actually built on Flickity -- would need to be GPL.

Can you clarify?

Thanks

**Comment by edwardr** [comment]
I answered my own question in reviewing the differences between GPL v2 and v3.

**Comment by carlmjohnson** [comment]
FTR, what did you learn?
