### ISSUE TITLE
Fade animation doesn't work in some cases 

### ISSUE THREAD

**Issue by FuruholmAnton** [metafizzy/flickity#903]
Hi, I have an issue with the new fade. It doesn't always fade when changing slide, but instead just switches without any animation.
I created an example on Codepen where you could check it out. 

https://codepen.io/Furuholm/pen/PVBWMV

**Comment by desandro** [comment]
1. You should disable `contain` option, if you have `fade` enabled. `contain` is designed for sliding animation and will likely cause issues with fading
2. `flickity-fade` as another bug with only two slides and `wrapAround`. I'm tracking that at metafizzy/flickity-fade#1

Closing here as a duplicate. Follow there for updates.
