### ISSUE TITLE
Issues with percentage widths on initial load

### ISSUE THREAD

**Issue by BrendanBerkley** [metafizzy/flickity#905]
**Test case:** https://codepen.io/BrendanBerkley/pen/yZQKoj?editors=1100
**Tested in:** Chrome and Firefox latest on Ubuntu

Five slides, 20% wide; carousel set to contain. In theory, all five should show, there should be no gaps, and they should never move. (In real life, I'm using this asNavFor, which is why I want a carousel that doesn't much act like one).

On initial load, you can see the slivers of the blue background, and if you advance the slides, it'll move just a bit. If you resize the window, it recalculates correctly and the problem goes away.

Any thoughts on how to fix this?

**Comment by desandro** [comment]
Thanks for reporting this issue. FWIW I do not see gaps on Chrome & Firefox on MacOS. I do believe this issue occurs.

Can you double check it's not a scroll bar issue?

``` css
/* force scroll bar */
html { overflow-y: scroll; }
```

Also try [percentPosition: true](https://flickity.metafizzy.co/options.html#percentposition)

**Comment by BrendanBerkley** [comment]
Thanks for responding!

Seems like a [scrollbar issue](https://codepen.io/BrendanBerkley/pen/yZrxOX).

Any further reading about this?

**Comment by desandro** [comment]
Thanks for that demo. That's about it!
