### ISSUE TITLE
Issue with height in first time load

### ISSUE THREAD

**Issue by surgatekno** [metafizzy/flickity#906]
hello, i love this slider so much, easy to use and have a pretty nice design too
but my slider height have some issue if you are the first time visitor (mean height issue will gone if u refresh the page)

here take a look [https://surgatekno.com/spek-game/spesifikasi-game-the-division-2/](https://surgatekno.com/spek-game/spesifikasi-game-the-division-2/)

and this image for example [https://i.imgur.com/Vn2nzuP.jpg](https://i.imgur.com/Vn2nzuP.jpg)

i load my .css and .js on <head> i dunno how can encountered this issue (even u load my site in front page, then u visit that page, it still have height issue, unless you refresh the page then everything will be normal)
[https://surgatekno.com/](https://surgatekno.com/) my front page
pleasehelp.

**Comment by desandro** [comment]
Sounds like an [imagesLoaded: true](https://flickity.metafizzy.co/options.html#imagesloaded) fix

**Comment by surgatekno** [comment]
> Sounds like an [imagesLoaded: true](https://flickity.metafizzy.co/options.html#imagesloaded) fix

its work like a charm
but next problem is the image between the slider goes smaller [https://i.imgur.com/mZCJxD9.jpg](https://i.imgur.com/mZCJxD9.jpg)
its getting smaller in each slide of image

**Comment by jsvini** [comment]
Same here, imageLoaded: true didn't work.

![image](https://user-images.githubusercontent.com/4185886/53035510-5df8e280-3454-11e9-86fa-de1fafd2abfd.png)

**Comment by desandro** [comment]
@surgatekno See the demo here: https://codepen.io/desandro/pen/MYQWEe

**Comment by surgatekno** [comment]
> @surgatekno See the demo here: https://codepen.io/desandro/pen/MYQWEe

thank you, its work well

**Comment by coder618** [comment]
> Sounds like an [imagesLoaded: true](https://flickity.metafizzy.co/options.html#imagesloaded) fix

Thanks bro.

**Comment by coder618** [comment]
despite of set : {imagesLoaded: true} some case's this issue still appear, 
I fix fix the issue by giving a css width value in the parent div.
Hope that would be helpful.

**Comment by PrasathRavichandran** [comment]
In some cases this issue still appears, Despite of adding {imagesLoaded: true},

The Fix is,
imagesLoaded requires the **flickity-imagesloaded** package. It already is included with flickity.pkgd.js, but not with Flickity as a stand-alone package. If you are using Webpack or RequireJS without flickity.pkgd.js, you need to install and require flickity-imagesloaded separately.

**npm install flickity**
**npm install flickity-imagesloaded**

```
var Flickity = require('flickity');
require('flickity-imagesloaded');

var flkty = new Flickity( '.carousel', {
  imagesLoaded: true
});
```

**For Angular 4 to 8:**

**npm install flickity**
**npm install flickity-imagesloaded**
**npm install @types/node**

**tsconfig.app.json: ( add "types": ["node"] )**
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": ["node"]  
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "src/test.ts",
    "src/**/*.spec.ts"
  ]
}
```

**<in any file>.ts:**

```
import { Component, OnInit, Inject, AfterViewInit } from '@angular/core';
import { DOCUMENT } from '@angular/common';
import * as Flickity from 'flickity';
require('flickity-imagesloaded');

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})

export class HomeComponent implements OnInit, AfterViewInit {

  constructor(@Inject(DOCUMENT) private document: Document) { }

  ngOnInit() {
 }

  ngAfterViewInit() {
    this.initializeFlickitySlider();
  }

  initializeFlickitySlider() {
    var elem = this.document.querySelector('.main-carousel');
    new Flickity(elem, {
      autoPlay: true,
      imagesLoaded: true,
      wrapAround: true
    })
  }
}
```

For more information, https://flickity.metafizzy.co/extras.html#module-loaders

Hope that would be helpful.

**Comment by clarknelson** [comment]
`$(window).on('load', function(){ //create flickity });` has given me a lot of success in the past, without including another library.

**Comment by desandro** [comment]
Rather that using window load to initialize Flickity, you can use it to trigger [resize](https://flickity.metafizzy.co/api.html#resize), so Flickity gets initialized soon, then resizes after all media has been loaded.

``` js
let $carousel = $('.carousel').flickity({});

$(window).load( function() {
  $carousel.flickity('resize');
});
```

**Comment by clarknelson** [comment]
Ah yes, thank you!

**Comment by mihalidis** [comment]
The code below worked for me for vue.js

mounted() {
  this.$nextTick(() => {
              this.$refs.flickity.rerender();
  }
}

**Comment by dpw1** [comment]
Adding a `min-height: 100%; width:100%;` to my gallery cells solved the problem.
