### ISSUE TITLE
IE11 incorrect slide position

### ISSUE THREAD

**Issue by Yakoot** [metafizzy/flickity#907]
I have a problem with ie11 slide position. 
I have 5 slides, in other browsers positions are left: 0%, 20%, 40%, 60%, 80%
in ie11: 0%, 18.04%, ...
chrome
![screenshot_2019-02-17_15-48-46](https://user-images.githubusercontent.com/4795345/52913100-899c9100-32cb-11e9-9d92-0161e5e8bf20.png)
ie11
![screenshot_2019-02-17_15-49-29](https://user-images.githubusercontent.com/4795345/52913099-899c9100-32cb-11e9-8ef5-340f37697075.png)

looks like it ignores slide paddings.

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you produce a **reduced test case** with the padding so I can better understand the issue?  See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by Yakoot** [comment]
thanks for your answer. Sorry, but it's already working) The issue can be closed

**Comment by Simpleqode** [comment]
Hi @desandro, thanks for the wonderful plugin! I've been struggling with the same issue over the last couple of hours and failed to find a solution so far. I use Flickity + Bootstrap grid: https://codepen.io/Deka87/pen/xxxjMbY. The problem only happens in IE11 when you first load the page. Once refreshed, everything gets back to normal. I checked the console and the cells positioning  is different than in Chrome. Looks like it ignores paddings indeed. Any help would be appreciated!
