### ISSUE TITLE
HTML5 video controls not working when draggable activated (MS Edge)

### ISSUE THREAD

**Issue by Saho92** [metafizzy/flickity#910]
Hi,

I am trying to get HTML5 video controls working for MS Edge when "is-draggable" is activated. Clicks on the video controls (play button, full screen button, ...) are just ignored due to the draggable event. On other browsers (Chrome, FF) it works fine: Both, dragging the video and clicking on controls, are working.  
On Edge it only works if I disable draggable on the slider completely, but i would like to have both combined.

For a demo pls have a look here:
https://codepen.io/anon/pen/zbYxGG

thanks!

**Comment by desandro** [comment]
One solution I've heard of is to put a transparent DIV that sits on top of the video, so clicking on the video in places actually clicks on that DIV. And only expose the Video UI that you want to be able to click. Sorry but I don't have a good solution specific for MS Edge.

**Comment by Briareos17** [comment]
Just rid of Edge)
