### ISSUE TITLE
Weird behavior when switching desktops

### ISSUE THREAD

**Issue by msmith7904** [metafizzy/flickity#911]
Let's say there's an autoPlay + wrapAround carousel open in a browser in desktop 1, and I go to desktop 2 for a minute and then return to desktop 1.  When I return to desktop 1 the carousel quickly cycles through many times before resuming regular speed.  Anyone else seen/reported this?  Anything I can do?

**Comment by desandro** [comment]
Yes, every now & then I see autoPlay progressing when it shouldn't. autoPlay is hooked into the browser [visibilitychange](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) API, so it shouldn't progress. But every now & then there's some edge case that passes through. If you could isolate what that edge case, that would help me address it.

**Comment by msmith7904** [comment]
Hi, just tested this again right now.  Using a Macbook with two desktops open.  I have this page open in a browser in the first desktop.  In second desktop I have this codepen open: https://codepen.io/desandro/pen/myXdej (I added "autoPlay": true to the options).  As I leave and return to the second desktop, the carousel quickly scrolls several cycles before returning to normal speed.  Not sure what else I can report but if you try this, I guarantee you'll see what I'm talking about.
