### ISSUE TITLE
Not initializing?

### ISSUE THREAD

**Issue by Fluxtor** [metafizzy/flickity#913]
I'm not reporting a bug or suggesting anything is wrong other than my lack of understanding. I setup a test project using just flickity and bootrap to test flickity was what I wanted. It's great but when trying to use it in my live project it does not load properly. 

All the cells and hidden and the dots are displayed vertically under the previous and next arrows. I can only assume something has errored and flickity has not initialized properly which will be entirely my fault. My project uses and older version of angularjs and bootstrap among other things so was wondering if there were any know conflicts?

**Comment by desandro** [comment]
If you're using Flickity within a framework like Angular, then you'll likely need to either initialize or trigger [`resize`](https://flickity.metafizzy.co/api.html#resize) after the carousel element is added to the page by the framework

**Comment by Fluxtor** [comment]
Thanks, so I'm initializing the carousel using jquery $(document).ready(myFunction) from within the head of the html. I just have a js library file which is also referenced in the head which holds the function called by document ready so not doing anything fancy!

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by Fluxtor** [comment]
Thank you, I will try to setup a test case although with divulging all of our code it maybe difficult to replicate. Will do my best!

**Comment by determin1st** [comment]
That's true, I confirm it. May be solved with:

```
window.dispatchEvent((new Event('resize'));
```

...in the end of `window.addEventListener 'load'` event handler..

But, there is one more problem related to initialization:

it "blinks" the last slide before switching to the first. any ideas?

**Comment by 0x416c69** [comment]
I can confirm this bug exists.

Reproduction:
Go to https://codepen.io/desandro/pen/myXdej
Paste this as for html:
```html
<h1>Flickity - wrapAround</h1>

<!-- Flickity HTML init -->
<div class="myCar">
  <div class="cCell"><a>test</a></div>
  <div class="cCell"><a>test</a></div>
  <div class="cCell"><a>test</a></div>
  <div class="cCell"><a>test</a></div>
  <div class="cCell"><a>test</a></div>
</div>

```

This for css:
```css
/* external css: flickity.css */

* { box-sizing: border-box; }

body { font-family: sans-serif; }

.myCar {
  background: #EEE;
  height: 30px;
}

.cCell {
  width: 30em;
  height: 30px;
  margin-right: 10px;
  background: #8C8;
  border-radius: 5px;
}

```

This for js:
```js
// external js: flickity.pkgd.js
new Flickity('body > div',{
                freeScroll: true,
                contain: true,
                prevNextButtons: false,
                pageDots: false,
                rightToLeft: true,
                imagesLoaded: true,
                setGallerySize: false,
                cellSelector: ".cCell"
            });

```

Initially it's fucked up but when you resize the iframe, it gets fixed.

**Comment by SamuelBismuth** [comment]
> Thank you, I will try to setup a test case although with divulging all of our code it maybe difficult to replicate. Will do my best!

I'm facing the same problem, did you find a solution?

**Comment by 0x416c69** [comment]
I could only fix it by lowering down and changing width of every cell

**Comment by determin1st** [comment]
you may create anonymous pen: codepen.io/pen
my solution works fine.

**Comment by desandro** [comment]
If someone can provide a **reduced test case** then I can debug this issue.
