### ISSUE TITLE
Reposition ( keep transition )

### ISSUE THREAD

**Issue by ModestasMitkus** [metafizzy/flickity#914]
Hey,

I have a small issue. Is it possible to keep transition when using repostion. ( right now snaps instatly ). Or is there an other way to keep transition but change width on active slide. I would have few slides  is-active would be 50% width and others by 25% width. 

Thank you.

**Comment by desandro** [comment]
Hello! The closest solution you can do is transition cell position, but not cell size. See https://github.com/metafizzy/flickity/issues/545#issuecomment-295304324

---

You could hack it by setting 
``` css
.carousel-cell { transition: left 0.3s; }
```

See demo http://codepen.io/desandro/pen/mmVMRV
