### ISSUE TITLE
Destroy slider using matchMedia

### ISSUE THREAD

**Issue by shadeed** [metafizzy/flickity#915]
Hello,

I have a use case where I want to destroy Flickity when the screen width is < X. I tried using `matchMedia` but I got an error that it's Flickity is not defined.

```js
var carousel = document.querySelector('.carousel');
var flkty;

if (window.matchMedia("(min-width: 600px)").matches) {
  flkty = new Flickity(carousel, {
    cellAlign: "right",
    rightToLeft: true,
    contain: true,
    pageDots: false,
    prevNextButtons: false
  });
} else {
  flkty.destroy();
}
```

** Test Case **
https://codepen.io/shadeed/pen/ywMXdx

Thanks in advance

**Comment by desandro** [comment]
Have you tried using [watchCSS](https://flickity.metafizzy.co/options.html#watchcss) which was specifically design for this use case?

**Comment by shadeed** [comment]
Oh I totally missed that -- Thanks a lot for your reply.
