### ISSUE TITLE
Images Loaded option but for video?

### ISSUE THREAD

**Issue by kaleidografik** [metafizzy/flickity#916]
Hi @desandro - I have a Flickity instance made up of images and videos. For the images to fit correctly, we have to activate the imagesLoaded option, however this doesn't work for videos. Instead, videos sit over to the left of the slider, until the browser is resized at which point they position correctly. This leads me to believe it's related to the video not having a set width until it is loaded, so is there an option we can use to ensure correct positioning of videos upon initial load?

Thanks

**Comment by desandro** [comment]
Yeah, imagesLoaded is only for `<img>` elements for now. Add your 👍 to desandro/imagesloaded#197

The [video element does provide several native events](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Events). [`loadeddata`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadeddata_event) might be useful here

**Comment by kaleidografik** [comment]
Thanks @desandro - this would be a nice feature to implement.
Any pointers regarding getting loadeddata to work some magic as a workaround?

**Comment by desandro** [comment]
See https://github.com/metafizzy/flickity/issues/71#issuecomment-77169907

**Comment by polemonade** [comment]
Hey! I just see #71  and doesn't work... There's a new solution for `<video>`? 

Thanks :)
