### ISSUE TITLE
overflow:auto prevents flicking/dragging on mobile (Android)

### ISSUE THREAD

**Issue by srangara** [metafizzy/flickity#917]
The overflow:auto declaration prevents flicking on Android, with some odd behaviour after using the navigation buttons:
https://codepen.io/srangara/pen/bZrxYg

I unfortunately have a need for fixed height and width cells (to tile a background) so overflow is important to address variable content... without abandoning the whole background scheme, of course.

Use case: https://bwmc.reposterous.com

**Comment by desandro** [comment]
Thanks for reporting this issue. Would changing `overflow: auto` to `overflow: scroll-y` or other value resolve it?

**Comment by pmaas** [comment]
I observe the same behaviour. `overflow: auto` unfortunately doesn't resolve the problem.

**Comment by rsgd** [comment]
We face the same issue. Any plans on fixing this? Otherwise we need to think of a different implementation for our UI. Thanks!

**Comment by srangara** [comment]
`overflow: scroll-y` seems to do the trick! All navigation options working as expected.

While technically still an issue, allowing overflow in at least one direction solves my accessibility problem, thanks!

**Comment by hirasso** [comment]
@srangara Can you reopen this issue? I can't get it to work, and am deep into a project where switching to another slider plugin would be a huge effort... @desandro any news on this?

**Comment by hirasso** [comment]
Ah, just found out that it can be fixed with:
```css
.carousel-cell {
  touch-action: pan-y;
}
```
found it here: https://github.com/metafizzy/flickity/issues/719
