### ISSUE TITLE
Drag/drop goes so fast in Safari iOS 

### ISSUE THREAD

**Issue by anialamo** [metafizzy/flickity#918]
Hi! I am using the last version of flickity. In Google Chrome the drag and drop and prev and next buttons.... work excellent! In IPhone Safari the prev and next buttons also work fine ... but the drag and drop works bad...it goes so fast.....e.g. if I have 4 slides...If I am in the 1st slide and drag/drop moves me to the last slide...In this case moves to the 4th slide. If I have 3 slides...moves from 1st slide to 3rd slide.
Can anyone help me please?
Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue. Can you confirm this behavior is occuring on a base demo, like on https://codepen.io/desandro/pen/ReZVom ?
