### ISSUE TITLE
make staticClick prevent regular click from firing

### ISSUE THREAD

**Issue by flowgrow** [metafizzy/flickity#92]
Hi, I'm having a bit of trouble trying to understand the staticClick event (or maybe jQuery events in general)

What I'm trying to do is display an easyzoom overlay (http://i-like-robots.github.io/EasyZoom/) after a staticClick.
To hide the overlay I, set up a delegate click event on 'is-clicked'. Unfortunately this delegate click event fires immediately after the staticClick event so my idea doesn't work out.
Is it possible to block the click event from firing? I tried preventDefault, stopPropagation, return false. Nothing worked.

If this is somehow not possible, then I would really like #51 to be implemented :) thanks

I forked your staticCick demo (http://codepen.io/flowgrow/pen/ZYwQVM) to demonstrate what I want to do.

**Comment by desandro** [comment]
Thanks for reporting this issue and providing a test case. I appreciate you going into detail here, but I don't think there's a good solution. I feel like you're overloading some gestures. Enabling and disabling the gallery dragging by clicking is a non-obvious behavior. After clicking, users could be 'trapped' in a cell without known how that happened.

Sorry, I won't be able to resolve this.

**Comment by flowgrow** [comment]
Thanks for looking into it!
If youre interested: here's what i've come up with
http://s.codepen.io/flowgrow/debug/LEMPxx


Am Dienstag, 24. März 2015 schrieb David DeSandro :

**Comment by nicooprat** [comment]
@flowgrow Could you please share your code? The Codepen link has expired. Thanks!

**Comment by desandro** [comment]
@nicooprat See https://codepen.io/flowgrow/pen/LEMPxx/

**Comment by nicooprat** [comment]
Thanks, but the code looks broken and surely overkill to just prevent a click? I mean, [about this comment](https://github.com/metafizzy/flickity/issues/81#issuecomment-361616429), isn't it possible to access the original click event and cancel it? for reference, here's what I tried:

```js
$(slider).on('staticClick.flickity', (e, pointer, cellElement, cellIndex) => {
  e.originalEvent.preventDefault()
  e.originalEvent.stopPropagation()
  e.preventDefault()
  e.stopPropagation()
  pointer.preventDefault()
  pointer.stopPropagation()
})
```

**Comment by desandro** [comment]
@nicooprat Can you please open a new issue with a **reduced test case** demonstrating the issue?
