### ISSUE TITLE
How do I access the Flickity instance on element initialized with HTML?

### ISSUE THREAD

**Issue by liquidvisual** [metafizzy/flickity#922]
Say I initialize with HTML as per the example:

```html
<div class="main-carousel" data-flickity='{ "cellAlign": "left", "contain": true }'>
```

With vanilla JavaScript, how do I now access the instance of Flickity on this element?

**Comment by desandro** [comment]
Good question! You can access the Flickity instance via an element with [`Flickity.data`](https://flickity.metafizzy.co/api.html#flickity-data)

``` js
const flkty = Flickity.data('.main-carousel');
```

**Comment by HarryFrancis** [comment]
Hello!

I have just tried following what you have said above, but I'm getting an error ('Cannot read property 'reloadCells' of undefined').

I have it set up like this:
`
            console.log(event.target.querySelector('.slider'));
            let sliderInstance = Flickity.data(event.target.querySelector('.slider'));
            sliderInstance.reloadCells();
`

The console log is returning the element with the data-flickity options set on it. Am I missing something? At a loss!

**Comment by desandro** [comment]
Has flickity been initialized first? There may be a race condition you need to check for.

**Comment by robwatkins1988** [comment]
Looks like a bug this.
