### ISSUE TITLE
Jquery independent

### ISSUE THREAD

**Issue by nam-co** [metafizzy/flickity#925]
Hi @desandro , thanks for the last upgrade, excellent

D I was wondering if you're planing to make flickity jquery independent? for example I haven't been able to make the api work with vue, and all the samples are in  jquery and vanilla JS, but jquery looks like is on the way out, even bootstrap 5 is dropping it

Thanks

**Comment by desandro** [comment]
Flickity is and has always been jQuery independent. You can load all the Flickity files just fine without jQuery.

But the large majority of Flickity usage remains tied to jQuery. So its not likely being dropped or downgraded any time soon.

**Comment by nam-co** [comment]
Hi @desandro , what do you think of this https://github.com/drewjbartlett/vue-flickity
too bad he hasn't updated to 2.2

Desandro how do you think is the best way to do a kenburns to the cell background image that only starts on cell focus and on specific cells?
