### ISSUE TITLE
Multiple Add-on Packages

### ISSUE THREAD

**Issue by clarknelson** [metafizzy/flickity#926]
I am trying to use multiple options that require "add-on packages" such as Fade and Hash.

This is close to what I have when importing.

```
var Flickity = require('flickity');
var Flickity = require('flickity-fade');
var Flickity = require('flickity-hash');
```

I have played around with multiple ways of declaring this:

```
require('flickity');
require('flickity-fade');
var Flickity = require('flickity-hash');
```

and others, but I can only get one extra feature to load. What is the best way to do this?

**Comment by desandro** [comment]
Try this one:

``` js
var Flickity = require('flickity-fade');
require('flickity-hash');
```

`flickity` is a dependency for the add-on features, so you don't need to add it explicitly. Hopefully, your package manager will point to the same version of `flickity` when the second add-on package is `require`'d. I'm considering changing the add-on packages to peer dependencies to possibly resolve this.

**Comment by clarknelson** [comment]
When I use the code as you suggested, the fade setting works but not the hash setting.

I've opted towards this approach for the time being:

```
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<script src="https://unpkg.com/flickity-fade@1/flickity-fade.js"></script>
<script src="https://unpkg.com/flickity-hash@1/hash.js"></script>

<link rel="stylesheet" href="https://unpkg.com/flickity-fade@1/flickity-fade.css">
<link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
```

Which allows both hash / fade to work! :) 

I am no module expert, but I think the "peer dependencies" approach might be better than how it is set up now. At least there is a work around where I can use all the features!
