### ISSUE TITLE
Auto select cell in the centre

### ISSUE THREAD

**Issue by Julix91** [metafizzy/flickity#927]
Hi everyone,

I struggled to make a Flickity slider have a draggable nav that while selects the parent slide dynamically while dragging. 

Eventually I got it: https://codepen.io/Julix/pen/ywxoQq - but it still gets stuck at the edge of the slider (between 12 and 1). I'd like some help with that.

Note I also want  [closest neighbors](https://codepen.io/desandro/pen/MagWrN) of the selected to have classes added, and got that to work.  https://codepen.io/Julix/pen/GLKOVa 

Thank y'all,
Julian

--- 
**Acknowledgement**
A pen that [highlights closest cell](https://codepen.io/desandro/pen/XoEpab) was a great starting point for me - I found it in [880 issue discussion](https://github.com/metafizzy/flickity/issues/880).
I went with asNavFor, though I did look at [sync](https://codepen.io/desandro/pen/MrMrqP) as well.

**Comment by Julix91** [comment]
Dang - turns out I'm getting issues when trying to move past the last slide - not sure why yet.

**Comment by Julix91** [comment]
Lol, just saw that I already had noticed before (and forgotten) that the code my code is based on doesn't handle [wrapAround](https://github.com/metafizzy/flickity/issues/880#issuecomment-473454160)!

**Comment by acemir** [comment]
Hi @Julix91,

To accomplish this feature we need to adjust the way we identify the `closestSlideIndex`.
I updated your pen with the adjusts: [https://codepen.io/acemir/pen/MRgNwJ](https://codepen.io/acemir/pen/MRgNwJ)
Hope it helps!

**Comment by Julix91** [comment]
That code works! I found a strange issue, haven't tried reducing the test case yet, to see if that's just wrapAround in general, but hadn't encountered it before.

https://youtu.be/RQQwsAq5BQU

Somehow with the select it doesn't seem to lose momentum the same way...

**Comment by acemir** [comment]
The `scroll` event fires whenever the slider moves. I did this check in the drag only to avoid firing the `select` event again when the` scroll` came from a click instead of the drag.
For example: When slide 1 is selected and a click occurs on slide 4, if you comment lines 23 to 25, 53 and 58, you will see that the scroll is triggered and a select occurs already on the next slide, slide 2. With this check, slide 4 is selected correctly.
About the video, unfortunately I could not reproduce this strange behavior.

**Comment by Julix91** [comment]
Found steps to reproduce:
1. open the code pen, make the window size smaller than your screen size
2. start drag on the nav and pull really hard and fast, somewhat off the window 
2 b  repeat step 2 a bunch of times until it happens 
3. observe crazy scrolling
4. try pausing it by holding or swiping main (won't work)
5. stop scrolling by scrolling on the nav

Very strange bug. - Figured it was rare enough I could ignore it, but designer ran into it. - I can only unreliably reproduce it myself! :( 

Sadly it's _easier_ to reproduce on mobile... I got the S8+ with the curved edge and one hard swipe and I get it...

**Comment by Julix91** [comment]
Actually it was only right at first that it's easy to reproduce, then I noticed why: it's when dragging between the first and the last item!

**Comment by Julix91** [comment]
Still can't figure out what's causing this but I'm running into it often.

**Comment by desandro** [comment]
Thanks for reporting this issue.

You'll likely have to look into the geometry code about selecting the cell in the center WITH wrapAround. That makes things difficult. Flickity is not exactly wired-up for this kind of interaction WITH wrapAround. As this is an implementation issue, I feel it falls outside of Flickity's principle feature set so I'll have to pass on investigating.

**Comment by Julix91** [comment]
Found a solution: increasing friction does it!

```
"friction": 0.5
```

**Comment by Julix91** [comment]
Nevermind - that didn't do it, but changing to this did the job:

```javascript
this.select(this.scrollSlideIndex, isWrapped, isInstant);
```
with both options set to true.
