### ISSUE TITLE
How to determine in which direction the slide will be scrolled

### ISSUE THREAD

**Issue by wayheming** [metafizzy/flickity#929]
Hello, is there a way to determine the side where the slide will turn? Clicks on the arrows can be traced, but I have not found a way to drag or bullet. I want to make a custom animation and so that it depends on which way I'm flipping through. Thanks.

**Comment by jimmyadaro** [comment]
I didn't fully understand what you need, but my guess is you can use [`select`](https://flickity.metafizzy.co/api.html#select) or [`selectCell`](https://flickity.metafizzy.co/api.html#selectcell).

**Comment by wayheming** [comment]
@jimmyadaro Hello, I need to know in what direction I was leafing through a slider.

**Comment by jimmyadaro** [comment]
Then I guess you could implement some custom solution using the [`change`](https://flickity.metafizzy.co/events.html#change) event.

**Comment by wayheming** [comment]
Yes, I thought about it. Well, you need to track the movement of the cursor and other related things. I thought maybe there is a ready-made solution or there is already such data in the slider just to get it

**Comment by jimmyadaro** [comment]
Why track the cursor movement? Maybe an slider is not what you need?

**Comment by wayheming** [comment]
Probably you did not understand what I want to do. I'll wait for the developer’s response. Thanks.

**Comment by jimmyadaro** [comment]
I hope @desandro understands what you mean 😅 Meanwhile I suggest you to add some kind of graphic/visual example of what you want to achieve (image, gif, video), this may make easier for us to help ya'.

**Comment by wayheming** [comment]
Everything is very clear I need to know which way I'm going to swipe the slider.

**Comment by jimmyadaro** [comment]
Yeah, that's fine, but what you want to achieve? If you _just_ need to know which way, you may want to read about [`dragstart`](https://flickity.metafizzy.co/events.html#dragstart) , [`dragmove`](https://flickity.metafizzy.co/events.html#dragmove) and [`dragend`](https://flickity.metafizzy.co/events.html#dragend). Have you tried that?

**Comment by wayheming** [comment]
Yes, I know about these events, but where can I get the side where I scrolled to the left or right

**Comment by jimmyadaro** [comment]
Try with the `moveVector` in `dragmove`

**Comment by wayheming** [comment]
@jimmyadaro Thank you very much, I think using the data from moveVector, I can recognize which way the slide has scrolled.

**Comment by jimmyadaro** [comment]
Glad to know! I'd love to see some Codepen of yours working in case any other person has the same issue and doesn't know how to do it :)

**Comment by wayheming** [comment]
As soon as I implement what I need, I will immediately write off here, mark you and give the code.
