### ISSUE TITLE
Define start slide

### ISSUE THREAD

**Issue by kabubi** [metafizzy/flickity#931]
How can i set slide to start? I have 3 slides, i need to star on slide 2 when the page load.
Thanks

**Comment by jimmyadaro** [comment]
Use `initialIndex`: https://flickity.metafizzy.co/options.html#initialindex
You can set a **zero-based** index, so your 2nd slide is _index 1_ (`initialIndex: 1`), or just apply this class to your 2nd slide element: `initialIndex: '.is-initial-select'`

**Comment by kabubi** [comment]
Thanks, my bad... i read a hundred times the documentation and dont see it. thanks again.

**Comment by jimmyadaro** [comment]
Great to know. Please close the issue if that worked for you :)
