### ISSUE TITLE
Flickity + Webpack - Doc suggestion

### ISSUE THREAD

**Issue by wcDogg** [metafizzy/flickity#934]
I'm using Webpack 4.30.0 + Flickity 2.0.0.

I was having the issue described here: Loading with webpack #225

If like me, you want to bundle Flickity with things like the full cell height hack, then the instructions need minor adjustments. 

Install

    npm i -D flickity
    npm i -D imports-loader

Add

    /src/vendors/flickity.fullheight.js

Entry Index (index.flickity.js)

    var Flickity = require('flickity');
    import '../vendors/flickity.fullheight.js';

webpack.config

Changed test from `/flickity` to `/flickity.pkgd/` else it interferes with importing other files - 'import' and 'export' may only appear at the top level.

Changed loader  from `imports?` to `imports-loader?` per newer Webpack requirements. 

    entry: {
        'flickity': './src/entry/index.flickity.js',
    },

    module: {
        rules: [         
            {
                test: /\.js$/,
                exclude: /(node_modules)/,
                use: {
                    loader: 'babel-loader',
                }
            },
            {
                test: /flickity.pkgd/,
                loader: 'imports-loader?define=>false&this=>window'
            },                   
        ]
    }

**Comment by desandro** [comment]
The instructions you found in #225 are likely outdated. Flickity v2 has better Webpack support. See [Flickity - Webpack](https://flickity.metafizzy.co/extras.html#webpack)

**Comment by jan-dh** [comment]
I'm a bit confused as to how to use multiple "plugins" at the same time with Webpack.
If I want to use the fade package, I need to change

`import Flickity from 'flickity';`

to 

`import Flickity from 'flickity-fade';`

When I want to use the as-nav-for package, the same scenario:

`import Flickity from 'flickity';`

to 

`import Flickity from 'flickity-as-nav-for';`

But what If I want to use them both?  Wouldn't it be better if I could do something like:

`import {Flickity, asNavFor, fade} from 'flickity';` ?
