### ISSUE TITLE
Basic staticClick event implementation

### ISSUE THREAD

**Issue by Geestig** [metafizzy/flickity#936]
After initialising a simple flickity slideshow and turning watchCSS to true (in order to get a regular list of images). I want to trigger a fullscreen slideshow when I click an image. However I can't seem to be able to trigger the actual event. In some cases it executes my function once on load but not on 'staticClick'.

See my test code below.

```
    const flkty = new Flickity(this.fullscreenCarousel, {
      pageDots: false,
      prevNextButtons: false,
      pauseAutoPlayOnHover: false,
      imagesLoaded: false,
      watchCSS: true,
    });

    flkty.on('staticClick', (event, pointer, cellElement, cellIndex) => {
      if (!cellElement) {
        console.log('CELLINDEX ', cellIndex);
        return;
      }

      const prevClickedCell = this.fullscreenCarousel.querySelector('.is-clicked');
      if (prevClickedCell) {
        prevClickedCell.classList.remove('is-clicked');
      }
      cellElement.classList.add('is-clicked');
    });
```

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by Geestig** [comment]
Sure, i've started this from the basic demo and added my code. (part of it also coming from an example)

https://codepen.io/anon/pen/zXbXrd

**Comment by Geestig** [comment]
Nevermind, was trying to do something for which flickity wasn't created.
