### ISSUE TITLE
Touch/swipe on iOS Chrome and Safari is not working

### ISSUE THREAD

**Issue by artemverbo** [metafizzy/flickity#937]
Hi David!

Just noticed that the issue with iOS Chrome/Safari seems to be back, exactly the same described here (Flickity 2.2.0 from npm, when using with Webpack/Laravel Mix): https://github.com/metafizzy/flickity/issues/540

Downgrading to 2.0.9 fixes that for me.

Thanks for the amazing work/plugin!

**Comment by desandro** [comment]
I'm not able to reproduce this issue in Chrome for iOS.

**Comment by Briareos17** [comment]
Safari on iOS 15 same problem, browser completely ignores swipe event until make click on slide and then swipe.
