### ISSUE TITLE
Height isn't being set when images are loaded

### ISSUE THREAD

**Issue by albell** [metafizzy/flickity#938]
Hi. I am calling flickity (current, v2.2) on some simple markup like this:

		<div class="flickity-slideshow ">
			<div class="flickity-cell">
				<img class="slide" src="my-image1.jpg" >
			</div>
			<div class="flickity-cell">
				<img class="slide" src="my-image2.jpg" >
			</div>
            </div>

JS is also very simple, with some straightforward callbacks and a viewport width to decide if it's "mobile":

		flkty = new Flickity( '.flickity-slideshow', {
			draggable: isMobile,
			fade: !isMobile,
			pageDots: false,
			wrapAround: isMobile,
			on: {
				change: updateCaption,
				ready: updateCaption // Otherwise blank on initial load.
			}
		});

You can see it in action here:

https://bit.ly/2IMVGTx

Try hard-refreshing several times in a row.

The issue is that about half the time, the flickity-viewport has a height of zero, effectively hiding the entire carousel. Sometimes it works as expected. If it's broken, and you nudge the viewport wider or narrower by a pixel, triggering a resize, everything lays out as expected. When I test locally, it works perfectly every time, unless I throttle to 3G in Chrome, in which case it breaks every single time. 😄 

So it seems like imagesLoaded isn't working quite as I expected. In layout, the cells are of course getting their height from the images they contain. I don't want to just reposition cells horizontally once images are loaded, _I want the entire carousel height to reevaluate_.

(I could write a simple listener that triggers a synthetic `resize` on imagesloaded, perhaps with a slight delay, but that seems gross and possibly redundant.)

I would be grateful for any insight on this. Thanks in advance.

**Comment by lollypopzz** [comment]
Hi Albell,

I'm having the same issue as you.

I've tried to use "imagesLoaded: true" and "adaptiveHeight: true", it is somehow fixed this problem.

Let me know if it's working for you or not.

More info here: [https://flickity.metafizzy.co/options.html](https://flickity.metafizzy.co/options.html)

**Comment by desandro** [comment]
You can use [`imagesLoaded`](https://flickity.metafizzy.co/options.html#imagesloaded) or [`lazyLoad`](https://flickity.metafizzy.co/options.html#lazyload)
