### ISSUE TITLE
Gallery Size 0 when auto-width and caption script breaks slider

### ISSUE THREAD

**Issue by inznmx** [metafizzy/flickity#940]
So I'm actually having 2 issues.

1. Some images are not loading when I don't set a cell width (because I'd like it to auto-size) although image load is true and I've encountered a weird bug there too, where some images randomly disappear if I go through the slideshow.

2. When I paste the script for setting an image caption, it breaks the whole slider.

Codepen is here: [https://codepen.io/asldkfjl/pen/YbKobP](https://codepen.io/asldkfjl/pen/YbKobP), however, I'm unsure if I was able to reproduce the issue.

Working example of 1. can be found here: [manuelauer.at/projects](https://manuelauer.at/projects) and of 2. here: [manuelauer.at/projects2](https://manuelauer.at/projects2).

**Comment by desandro** [comment]
You'll need to set either a width or height for images, as Flickity needs to know these measurements to size the viewport container. OR you can set your own size with [setGallerySize: false](https://flickity.metafizzy.co/options.html#setgallerysize)
