### ISSUE TITLE
Needed options or setup for advanced more friendly cells alignment 

### ISSUE THREAD

**Issue by 7iomka** [metafizzy/flickity#942]
By default `cellAlign: 'center'`, and when total count of cells is less than available width of closest container, slider is centered, so there is no way to align it to the left, except through set `cellAlign: 'left'`, but the disadvantage of this approach is that when the width of the closest container is less than the total number of visible slides on the scene, when switching to the next slide(cell), we do not see a slice of the previous one, so that we can be able to switch to it through the click, but without using the navigation buttons (`prevNextButtons: false`).
So I would like 2 behaviors at the same time: `cellAlign: 'left'` when available area width is more than total calculated width of visible slide, and `cellAlign: 'center'` when is less (or my be one another option for centering slides when we navigate, except the first and last one (implies that we use `contain: true`)
I want to use your plugin for one reason - none of the plug-ins known to me easily cope with the task of organizing synched (asNavFor + sync) sliders, and this is exactly the alignment behavior I miss. Maybe I didn’t read the documentation well.
Note: We do not know when the total number of visible slides will be less or more than the width of the parent container and I want this to be controlled without user intervention.

Thanks!

**Comment by desandro** [comment]
Thanks for this feature request. I think the best approach is add your own conditional JavaScript to handle this kind of logic. 

``` js
// pseudo-code
var totalContentWidth = getTotalContentWidth();
if ( totalContentWidth < carousel.width ) {
  cellAlign = 'left';
} else {
  cellAlign = 'center';
}
```

I'll leave that up to you.
