### ISSUE TITLE
Next slide on click

### ISSUE THREAD

**Issue by scrgb** [metafizzy/flickity#945]
Hello there,

I'm wondering if there's any way to deactivate the drag and simply click on the image to go to the next slide.

Thanks in advance.
Keep the good work!

**Comment by desandro** [comment]
> deactivate the drag

Set [draggable](https://flickity.metafizzy.co/options.html#draggable) to false

> simply click on the image to go to the next slide

Use the [next](https://flickity.metafizzy.co/api.html#next) method

``` js
$carousel.on( 'click', function() {
  $carousel.flickity('next');
});
```
