### ISSUE TITLE
Use Flickity to scroll 1 extra-wide cell.

### ISSUE THREAD

**Issue by chessydk** [metafizzy/flickity#946]
Thx. for Flickity. Using it a lot.

I was wondering if I can use Flickity as a viewport to one (1!) very wide image. I have tried setting it up and I can indeed slide it left and right, revealing more of the image, but Flickity always re-centers it again when I release the mouse button.

I know its not the intended behaviour, but its so close! 

Best, Carsten

**Comment by desandro** [comment]
Yeah, a lot of people have tried with `freeScroll` enabled. It may work, but this is definitely outside the scope of Flickity.
