### ISSUE TITLE
Get mouse position while dragging

### ISSUE THREAD

**Issue by SpabRice** [metafizzy/flickity#947]
Hello,

I'm looking for a possibility to get the mouse position while the carousel is dragging.

The usual jquery actions like 'mousemove','ondrag', ... are not working.  It always stops when dragging the carousel.  Is there any way to get them?

**Example** 
http://jsfiddle.net/hrzt698n/7/

**Comment by desandro** [comment]
Use [Flickity's custom `dragMove` event](https://flickity.metafizzy.co/events.html#dragmove) that provides a `moveVector` parameter

``` js
$carousel.on( 'dragMove.flickity', function( event, pointer, moveVector ) {...});
```

[See dragMove demo on CodePen](https://codepen.io/desandro/pen/azqwWW)
