### ISSUE TITLE
Animating each slide with GSAP

### ISSUE THREAD

**Issue by ionz149** [metafizzy/flickity#948]
Hello,
I have enjoyed using flickity. I've recently began fussing with GSAP and have been able to get away with only the first slide being animated by GSAP.

However I am curious if it is easy enough to make it so every slide can animate via GSAP.

This codepen has minimized example, you will notice only the first slide animates on page load but then the others don't: https://codepen.io/ionz149/pen/vwQBGM

Thanks,
Chris

**Comment by desandro** [comment]
This is looking good. Were you able to resolve it?

**Comment by ionz149** [comment]
Yes, I accidentally overwrote the one I linked but it is working now.
