### ISSUE TITLE
Flickity - select method with a select element: Chrome issue

### ISSUE THREAD

**Issue by fashionnugget** [metafizzy/flickity#949]
Hi @desandro and Flickity community,

I encountered a curious behavior on Chrome browser (_Version 74.0.3729.169_). 
I attempted to replace buttons on official _[Flickity - select method](https://codepen.io/desandro/pen/jEZwxb)_ demo with some `option` nested in a `select` element.

**Test case:** https://codepen.io/guyom/pen/vwPEqe?editors=1011

The select element correctly synchronize carousel on Firefox & Edge, but nothing happens on Chrome.

Thanks for your help.

--
Disclosure: Please be kind, I am a hobbyist developper 🙈

**Comment by desandro** [comment]
Thanks for reporting this bug. If you're listening for changes to a `select` element, then you want to use the [`change` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event). Its interesting that this browser bug differs in Firefox vs Chrome. Nice find!

``` js
$('#platform').on( 'change', function() {
  var index = $(this).val();
  console.log(index);
  $carousel.flickity( 'select', index );
});
```

**Comment by fashionnugget** [comment]
Great! Thank you very much for your positive reply. I have just add a link to your answer on the codepen demo.

P.S: congrats for Zdog 🚀
