### ISSUE TITLE
wrapAround when content width smaller than container

### ISSUE THREAD

**Issue by komunyako** [metafizzy/flickity#95]
If you set `wrapAround: true` and have small amount of items that don't fill container -- then it causing trouble. See this [pin](http://codepen.io/anon/pen/ogmdaK), try remove some items and scroll slider.

I'm suggestion add condition to `_getWrapShiftCells` method that will check widths
``` js
  // cancel wrap-around if content smaller than container
  var lastCell = this.getLastCell();
  var contentWidth = this.slideableWidth - lastCell.size[ this.options.rightToLeft ? 'marginLeft' : 'marginRight' ];
  if ( contentWidth <= this.size.innerWidth ) {
    this.options.wrapAround = false;
  } else {
    this.options.wrapAround = true;
  }
```
[Look at it](http://codepen.io/anon/pen/ZYwoPj). Is it right way?

**Comment by desandro** [comment]
Thanks for this feature request. Yes, this could be helpful. But I feel this is an edge case. Either your content works with wrapAround, or it doesn't. Catering to both use cases could be cumbersome.

**+1** this feature if you would like to see this feature implemented.

**Comment by maimairel** [comment]
+1

**Comment by dzucconi** [comment]
+1

**Comment by desandro** [comment]
I'm closing this issue as it did not get enough public interest. :whale:

**Comment by starsirius** [comment]
+1

**Comment by mzikherman** [comment]
+1 :disappointed:

**Comment by broskoski** [comment]
+1

**Comment by howells** [comment]
+1 ;-)

**Comment by piotrkulpinski** [comment]
+1

**Comment by adrienlamotte** [comment]
+1

**Comment by warreb1** [comment]
+1
I don't see how this could be an edge case. Many carousels are community driven and therefor dynamically filled. Checking how many images there are and enabling/disabling the flickity carousel is a workaround that doesn't give full support in any way.

Example:
In our case we're using a full-width carousel with images of dynamic width/fixed height. The carousel exists out of portrait and landscape imagery. When going trough the 5-image carousel on my 15 inch screen it works perfectly. When I however put it on my full-hd screen the entire carousel breaks.

Please reconsider this. It's not an edge-case but a dealbreaker.

**Comment by navarr** [comment]
+1.  Experienced it today and considered it a bug.

Same sort of case with @warreb1.

**Comment by arkid** [comment]
Experienced today as well.   This is a bad call to consider that the slider should either wrap or not depending on your content amount as many uses of this plugin are going to be with cms populated content where you have no idea if someone is entering 3 or 20 items to slide.

My slider is also responsive so determining at runtime if I can enable wrap around or not is a real pain and likely unreliable.

**Comment by mete89** [comment]
+1

**Comment by AlexMinaev** [comment]
+1 it's not duplicate elements properly https://codepen.io/aminaev/pen/ZWPXQQ

**Comment by paulgc34** [comment]
+1

**Comment by a-v-l** [comment]
+1

**Comment by dylanfisher** [comment]
+1

**Comment by JesseHigson** [comment]
+1

**Comment by evanjmg** [comment]
+1

**Comment by craig-mrare** [comment]
+1

**Comment by willpower232** [comment]
+1 definite issue

**Comment by desandro** [comment]
I'm not likely going to add a fix for this one. The only fix is to duplicate content so that it fills the container. Not only will this add complexity, but there's all these issues that arise when you start cloning nodes — events may not work right, duplicated stuff doesn't get copied correctly, CSS stuff may break.

**Comment by tstoik** [comment]
+1

I'm a bit shocked that this issue was called an edge case, this is a very common use case.

**Comment by ABaier** [comment]
+1

**Comment by desandro** [comment]
I have decided to not implement this feature. Thanks for all your feedback.

**Comment by anishd19** [comment]
+1

**Comment by alex1012** [comment]
+1

**Comment by mgoubert** [comment]
+1

**Comment by Osiruss** [comment]
Bug
+1

**Comment by danielazzopardi** [comment]
Bug
+1

**Comment by derdaani** [comment]
+1

**Comment by leptest** [comment]
Any chance this could be reviewed again please?

**Comment by bartekcholewa** [comment]
Not an edge case... simply deal break. Time to use Owl Carousel.

**Comment by hirasso** [comment]
+ 1

**Comment by gdenisov** [comment]
While I can see how gallery shorter than the viewport can be an edge case, I was surprised to see that the carousel does not handle wrap around when cells are exactly the size of the viewport. In fact this an issue unless one *whole slide* is *fully off screen*. That is definitely a bug.

**Comment by Hankli** [comment]
+1

**Comment by tomanatura** [comment]
+1

**Comment by fredericpfisterer** [comment]
+1

**Comment by danielvonmitschke** [comment]
+1

**Comment by asolopovas** [comment]
+1

**Comment by komunyako** [comment]
Guys, it's time to put your thumbs up at https://github.com/metafizzy/flickity/issues/809, rather than here.

**Comment by jakedowns** [comment]
+1

**Comment by mibercsk** [comment]
+1 fix this bug, if you have only 3 or 4 slide items this bug appear, fix IT.. some of us need a slider with only 4 items and wrapAround to true

**Comment by daveybrown** [comment]
My solution is to duplicate slides before running flickity . 

    function duplicateSlides(cellSelector) {
      var $slides = $(cellSelector).clone();
      $slides.addClass('show-if-flickity-enabled');
      $(cellSelector)
        .last()
        .after($slides);
    }

    duplicateSlides('.variation-slide');

This could be elaborated so that slides aren't duplicated if there are plenty of them.

**Comment by spideyinf** [comment]
+1 I have the same issue. Please revise

**Comment by yepecece** [comment]
+1 Same here

**Comment by bluedge** [comment]
+1 Same here - A cloning Method would be useful when the number of items is limited!

**Comment by obliviga** [comment]
+1

**Comment by desandro** [comment]
I am locking this issue in favor of moving discussion to #809, which does offer a solution.
