### ISSUE TITLE
Achieving a Fieldmag style gallery

### ISSUE THREAD

**Issue by richardwiggins** [metafizzy/flickity#954]
I love the Fieldmag website and have seen they also use Flickity, but not sure how they're achieving the multiple images on the page which then link to a Flickity instance. Anyone know if this can be done natively?

An example here: https://www.fieldmag.com/articles/amtrak-coast-starlight-train-trip-photography

**Comment by desandro** [comment]
Looks like they have a separate Flickity instance. When clicking on a image, they likely trigger [select](https://flickity.metafizzy.co/api.html#select) with `isInstant` and reveal the Flickity instance

**Comment by richardwiggins** [comment]
Thanks, I'll see if I can make sense of it 👍
