### ISSUE TITLE
Custom cellAlign with contain

### ISSUE THREAD

**Issue by marctaule** [metafizzy/flickity#955]
I have a div "container" (title) that has max-width of 800px and width (100%)
I also have my slider in another div with width:100% (full width window) and I'd like to align left my first item of the slider with the title container, but I can not.Any help?

 I tried the following:

https://codepen.io/marctaule/pen/KjNPmy

`var $container = $('.container');
  var leftOffset = ($(window).width() -  $container.width()) / 2;
  var $slider = $('.slider');
  $slider.flickity({
    // options
    //contain: true,
    cellAlign: leftOffset / $(window).width(),
    freeScroll: true,
    pageDots: false,
    percentPosition: true,  
  });`

Thanks!

**Comment by desandro** [comment]
Rather than trying to calculate the custom `cellAlign` value, I think a more straightforward solution is to put the carousel in the container and enable `.flickity-viewport { overflow: visible; }`. This way all the resize behavior is in the same place. See demo https://codepen.io/desandro/pen/7f7e922541efd0d2a1114dc075861928

My JS:

``` js
  $slider.flickity({
    // options
    contain: true,
    freeScroll: true,
    pageDots: false,
    percentPosition: true,  
  }); 
```

**Comment by marctaule** [comment]
It works! Thanks!

**Comment by clarknelson** [comment]
amazing, how beautiful your plugin is!

**Comment by gregg-cbs** [comment]
I am having an issue with text where text cells arent behaving accordingly and this did not fix the issue.

Here is a video showing with the options described above. Next was removing those options. Third is resizing the window showing that then this works:
https://github.com/metafizzy/flickity/assets/57114335/f372d601-5799-4bec-b6c6-ca2554856065
