### ISSUE TITLE
External gutter

### ISSUE THREAD

**Issue by florianbepunkt** [metafizzy/flickity#956]
I saw that there exist are a few issues relating to this, but none seem to solve the problem.

I have a carousel like the following dribble shot (not my, dribble, https://dribbble.com/shots/4901594-Horizontal-Vertical-Scroll)

![1_owfJDGpP-n707h-FZuDDKg](https://user-images.githubusercontent.com/8314202/59768413-9d212e00-92a4-11e9-98c8-488a0ad6d8cd.gif)

As you can see there is some spacing between the slides and there is spacing before the first and after the last slide. This external gutter is consistent with the rest of the layout. But if the carousel has more items that can be shown, the carousel overflows to the right/left.

My problem: How can this be approached with flickity?

Basially I would like to have the carousel full width and have the spacing before the first and after the last element. I have the width of my elements set to a responsive width and added margin between the inner elements like this:

```
.carousel-slide {
  margin-right: $spacing;
  width: calc(100% - 5 * $spacing / 5.5);

  &:last-child {
    margin-right: 0;
  }
}
```

All slides have the same aspect ratio. Therefore I cannot add a margin-left / margin-right on the first/last slide, since this would change the width of the fist/last element and in doing so changing the aspect ratio.

Any help would be appreciated.

**Comment by desandro** [comment]
Thanks for reporting this issue. Sounds like you already resolved this issue with the proposed CSS. If you have a  **reduced test case**, I could better identify the difficulty. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
