### ISSUE TITLE
How to use Flickity events and initialize with data-flickity?

### ISSUE THREAD

**Issue by dimative** [metafizzy/flickity#957]
Hello.
I have seen this [issue](https://github.com/metafizzy/flickity/issues/459). But not working. I want to use Flickity events and initialize with data-flickity.

``` js
// get Flickity instance
var flkty = Flickity.data('.carousel');
// do stuff
flkty.on( 'staticClick', function() {...});
```
I tried this code. Flickity working fine, but events not working.

Here is pen link https://codepen.io/dimative/pen/KjWrqQ

Please help me. 
Thanks.

**Comment by geniuskidkanyi** [comment]
if you wan to initialize with data-flickity then initialize with
`data-flickity='{` options}`
here is a pen link [condepen](https://codepen.io/desandro/pen/MYQWEe)

**Comment by desandro** [comment]
If you're using JS to listen for events, then you might as well initializing in JS. This way you can avoid the race condition.
