### ISSUE TITLE
Build without jQuery

### ISSUE THREAD

**Issue by christopherdarling** [metafizzy/flickity#958]
Trailing out using the library in an upcoming project, we won't be making use of jQuery at all and would be great if we could use (or build) a slimmer build without jQuery. Any chance of this being an option?

**Comment by desandro** [comment]
Flickity is written in vanilla JS. jQuery is an optional dependency. Flickity does include [jQuery Bridget](https://github.com/desandro/jquery-bridget) in its source, but that's only an extra 100 lines of code. If you did want to build a version of flickity.pkgd.js, you can [remove jquery-bridget.js from gulpfile.js](https://github.com/metafizzy/flickity/blob/v2.2.0/gulpfile.js#L70)
