### ISSUE TITLE
Synchronize two sliders

### ISSUE THREAD

**Issue by silvenon** [metafizzy/flickity#96]
There is the option `asNavFor`, but that only triggers the other slider when a cell is selected. Is there a way to achieve this without causing an endless loop?

**Comment by desandro** [comment]
Yes! Use [flickity-sync](https://github.com/metafizzy/flickity-sync). It's a separate add-on library that enables the `sync` option. See demo: http://codepen.io/desandro/pen/OPZJmE

**Comment by silvenon** [comment]
Thanks! I already went with a different solution, so I'll try flickity-sync the next time I'm in a similar situation.
