### ISSUE TITLE
Ability to handle multiple selected cells

### ISSUE THREAD

**Issue by NikxDa** [metafizzy/flickity#961]
Hey there,

I would like to suggest a feature that allows the slider to have multiple selected cells. There have been several issues like this discussed, but most of them focused on how to determine a slider boundary, not so much the issue of multiple selected elements.

Here's the issue broken down:
- A slider with `contain: true` will still be able to change slides without actually moving (as referenced in #289)
- A slider with `groupCells` will not have this issue, but will behave differently when sliding (not sliding one at a time, but per group).

I wonder if it is possible to achieve the following scenario (where `X` is a slide that is selected, `x` (lowercase) is a normal slide, and the viewport is determined by `[]`:

`x x [ X X X ] x x` -> *next* -> `x x x [ X X X ] x`

I would envision a property called `selectionSize` that starts out with the first `selectionSize` items being selected, and then shifts them one at a time when moving in either direction. This would be really useful for cases where slides need to move one at a time, with multiple slides being in viewport, _and_ the inactive slides having certain styles (like opacity) set.

**Comment by desandro** [comment]
Thanks for this feature request. Between `contain` and `groupCells` I feel these features cover enough accommodate most use cases. Adding a third behavior may help, but would make only make things more complicated. For example, how would `selectionSize` work with `groupCell`. I appreciate the idea but I'll have to pass on this one.
