### ISSUE TITLE
Drag and hold slider on desktop triggers link when you release mouse on the link/slide

### ISSUE THREAD

**Issue by woutervanerp** [metafizzy/flickity#968]
When you drag the slider on desktop and release the mouse on the slide with the link in it, it triggers. Is there any way how this can be solved?

**Comment by NEMONAUT** [comment]
Best way I've found to deal with this:
`flickity.on('dragStart.flickity', function(){
            flickity.find('a').css({pointerEvents: 'none'});
        });
    
        flickity.on('dragEnd.flickity', function(){
            flickity.find('a').css({pointerEvents: 'all'});
        });`
From this issue:
https://github.com/metafizzy/flickity/issues/409#issuecomment-431908980

**Comment by desandro** [comment]
I'm not seeing this behavior. Flickity has code so that dragging on links does not click them. If you have a test case, I can take a look.
