### ISSUE TITLE
Support for data binding instead of add/remove functions.

### ISSUE THREAD

**Issue by michalmadethis** [metafizzy/flickity#971]
Hello, are there any plans for flickity to support data binding carousel elements? This is a core part of how a lot of JS frameworks function these days and having to wire up a bunch of change events on models in order to manually insert/delete stuff from the carousel feels like a very poor solution.

e.g. Knockout.js:
>      <div class="main-carousel" data-bind="foreach: peopleModels">
>             <div class="carousel-cell">
>                 <span data-bind="text: firstName"></span >
>                 <span data-bind="text: lastName"></span >
>             <div>
>      </div>

e.g. Svelte.js
>      <div class="main-carousel">
>              {#each peopleModels as person}
>             <div class="carousel-cell">
>                 <BaseCard person={person}/>
>             <div>
>             {/each}
>      </div>

e.g. Angular.js
>      <div class="main-carousel"  ng-repeat="person in peopleModels">
>             <div class="carousel-cell">
>                 <BaseCard ng-model="person"/>
>             <div>
>      </div>

etc etc.

For the record I'm trying to get this going in Svelte, trying to bind in this way does not work because the bound elements are being inserted outside of the carousel, due to DOM manipulation of the carousel happening at runtime.

**Comment by desandro** [comment]
Thanks for reporting this issue. I think porting Flickity to a framework is a better goal.
