### ISSUE TITLE
WatchCSS - Initialize a slider on click

### ISSUE THREAD

**Issue by JordanSayner** [metafizzy/flickity#975]
Hi, Im looking to have a carousel within a modal window, i want to initialize the slider when the modal opens, I was looking at using "watchCSS" option, but cant seem to get it working, Does this only work on resize?

If there any other way you can think of that would make this work?

You can see a basic reduced test case below.

**Test case:** https://codepen.io/jsayner/pen/06e0922d0d980a51cb0c45bba9a0dc5d

**Comment by AdamJaggard** [comment]
It's probably easier to just make the slider on page load and tell flickity to resize and reposition the cells when the modal is opened: https://flickity.metafizzy.co/api.html#sizing-and-positioning

If you don't want to initialise the slider until the modal is open just do a regular `$('.thing').flickity()` on modal open and call destroy when it's closed.
