### ISSUE TITLE
Flickity carousel only shows the last item on list

### ISSUE THREAD

**Issue by AliSafaei1990** [metafizzy/flickity#976]
Hello there. i'm using flickity carousel on my project .this is how my flickity carousel looks :
![flickity-problem](https://user-images.githubusercontent.com/12812648/63916498-cbae4880-ca4d-11e9-85dc-7155381dc4bc.png)

when i resize the browser window it'll work fine.

**Comment by idezigns** [comment]
I have a similar problem. Mine only shows first image, and no others until I resize.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).

**Comment by out-of-order** [comment]
I'm having exactly the same issue.
After browser window resizing it starts to display correctly.
