### ISSUE TITLE
How to link from one slide to other slides (not prev/next)

### ISSUE THREAD

**Issue by marflow** [metafizzy/flickity#977]
Hi. I have a working slider but can´t get links within a slide to work. 

What I want to achieve is a "nav slide" from which a viewer of the carousel can jump to various chapters of the carousel. (These buttons should be within the nav slide not in a buttonGroup outside.)

Is that possible? Thanks a lot for a hint how to do that.

**Comment by marflow** [comment]
Never mind, got it working now.

**Comment by Sweetmaniac** [comment]
Hi ! Would you mind to share with me the way you got it working ? :-)
Thank you in advance !

**Comment by marflow** [comment]
Hello Sweetmaniac, sure, I followed this pen: https://codepen.io/desandro/pen/mEBAXR
My directory / nav slide has button elements and the targets in the "data-selector". I made the button group in the example my first slide. Hope this helps!

**Comment by Sweetmaniac** [comment]
Thank you ! Very appreciated  :-)
