### ISSUE TITLE
Reinit of flickity in barba/pjax scenario

### ISSUE THREAD

**Issue by ionz149** [metafizzy/flickity#978]
I apologize if this is painfully stupid or redundant but I promise I have googled and tried a few different approaches to this but i cannot get it working.

I have a wordpress site using barba transitions with flickity carousel on front page. It works on page load but if you go to another page then come back to home page the carousel loses all its js magic.

I realize I don't have a codepen example to analyze but just looking for what would "generally" be the idea to fix this issue. I am gonna look into how to setup a multi page project in codepen in the meantime but any help would be greatly appreciated.

**Comment by saetia** [comment]
here's how I handle this with turbolinks. I just destroy and recreate the slider on every page change event

```javascript
function destroySlider(){
  if (typeof $slider === 'undefined') return;
  $slider.off('scroll.flickity').flickity('destroy');
}
function initSlider(){
  if (!$('.slider').length) return;
  destroySlider();
  $slider = $('.slider').flickity();
}

$(document).on('page:change', function() {
  initSlider();
});
$(document).on('page:unload', function() {
  destroySlider();
});
```

**Comment by ionz149** [comment]
@saetia thank you so much! I was able to edit that and get it doing what I needed.
