### ISSUE TITLE
Flickity swallows mousedown, mousemove and mouseup events if being dragged around

### ISSUE THREAD

**Issue by hirasso** [metafizzy/flickity#979]
Hi there! 

I have a case where I need to detect mouse moving, even when dragging flickity around. Is there any way to achieve this? It would be very nice to not have to use the flickity-specific pointerDown, pointerUp and pointerMove events for this.

Thanks! 
Rasso

**Test case:** https://codepen.io/hirasso/pen/JjPBxgb

**Comment by MarlBurroW** [comment]
Same trouble, I need to build a global way to have an html element following the mouse cursor on every sliders in my app (to indicate the user he can drag the slider). 
I have a `mousemove` event listener on the `window` element  that is not fired when dragging on a flickity slider, therefore my html cursor stop following the cursor when dragging.

**Comment by MichaelChistyakov** [comment]
I have the same case. I'm using custom cursor image and I can not find a way to catch mousemove while slider is dragging.

Please fix it.

**Comment by MichaelChistyakov** [comment]
@MarlBurroW you can try this:
`// https://github.com/metafizzy/flickity/issues/979
// Have to use hotfix:
import CustomCursor from '../modules/CustomCursor';
Flickity.prototype.dragMove = function(event, pointer, moveVector) {
	if (!this.isDraggable) {
		return;
	}

	CustomCursor.setOuterEvent(event);

	event.preventDefault();

	this.previousDragX = this.dragX;
	var direction = this.options.rightToLeft ? -1 : 1;
	if (this.options.wrapAround) {
		moveVector.x = moveVector.x % this.slideableWidth;
	}
	var dragX = this.dragStartPosition + moveVector.x * direction;

	if (!this.options.wrapAround && this.slides.length) {
		var originBound = Math.max(-this.slides[0].target, this.dragStartPosition);
		dragX = dragX > originBound ? (dragX + originBound) * 0.5 : dragX;
		var endBound = Math.min(-this.getLastSlide().target, this.dragStartPosition);
		dragX = dragX < endBound ? (dragX + endBound) * 0.5 : dragX;
	}

	this.dragX = dragX;

	this.dragMoveTime = new Date();
	this.dispatchEvent('dragMove', event, [pointer, moveVector]);
};`

**Comment by desandro** [comment]
Thanks for reporting this issue. I'm not sure there is a better solution around using Flickity pointerDown / Move events. Flickity needs to `preventDefault` on the event to stop normal browser behavior of dragging, like stopping copy/paste drag behavior or mobile page scrolling.

**Comment by McGern** [comment]
I know this ticket is about dragging, but is the carousel supposed to stop events bubbling when not dragging? I am doing mousedown without any dragging and all events inside the carousel are being cancelled
