### ISSUE TITLE
Flickity not work after refresh page

### ISSUE THREAD

**Issue by DonOzOn** [metafizzy/flickity#980]
![image](https://user-images.githubusercontent.com/42008796/65385402-7289ba00-dd58-11e9-9f67-40e924d3a5a2.png)
After refresh page
![image](https://user-images.githubusercontent.com/42008796/65385414-90571f00-dd58-11e9-9ddb-9ce46acf6ac3.png)

Here my code
![image](https://user-images.githubusercontent.com/42008796/65385443-df9d4f80-dd58-11e9-8182-d93dcf779a76.png)

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/.github/contributing.md#submitting-issues).
