### ISSUE TITLE
Issue with cellAlign: 'center' and groupCells: true when there's not enough elements to fill entire group

### ISSUE THREAD

**Issue by piotrkulpinski** [metafizzy/flickity#981]
Hi, 
I've stumbled upon some issue that appears when you set those parameters and there's not enough elements to full the whole group:

```
cellAlign: 'left',
contain: true,
groupCells: true,
```

Here's the use case: https://codepen.io/piotrkulpinski/pen/eYOxjeP

The elements get positioned incorrectly, where I'd expect them to be center and the gallery to be disabled as currently.

Cheers

**Comment by piotrkulpinski** [comment]
Turns out it doesn't even have to have the `groupCells` setting enabled:
https://codepen.io/piotrkulpinski/pen/BaBMPqd

**Comment by wpchannel** [comment]
Same bug here with Bootstrap 4

**Comment by desandro** [comment]
This looks to be the ol problem when 'not enough content for wrapAround'. See feature request in #809
