### ISSUE TITLE
Flickity slider with asNavFor and hash buggy in IE11

### ISSUE THREAD

**Issue by samkent** [metafizzy/flickity#986]
I'm using Flickity asNavFor with hash. This works well in modern browsers but when you're going through the nav, the second slide skips to the third and breaks the final slide.

**Test case:** https://codepen.io/zoostudios/pen/GRRKjMb
**Debug mode:** https://cdpn.io/zoostudios/debug/GRRKjMb/gaMeYzNwXmWM#slide-one

Maybe the two can't be used together?

**Comment by desandro** [comment]
Sorry, I am de-prioritizing IE11 so I won't fix this one.

**Comment by samkent** [comment]
No worries, I've dropped IE11 support too 😎
