### ISSUE TITLE
Prevent Link Click when dragEnd 

### ISSUE THREAD

**Issue by riiccardo** [metafizzy/flickity#988]
@desandro 

**Test case:** https://codepen.io/riccardo051/pen/GRRpvdy

everything is ok in `unpkg` js file

but if install `flickity` from **`npm`** and **`import`** it

Prevent click a tag when dragging is not working 

how can remove `jquery`,  and `jquery-bridge`

coz I'm using vanilla js and es6

> **No. It includes other files like imagesLoaded. pkgd file is designed for <script> elements, not module loaders or ES6 imports.**

>1. import '../node_modules/flickity/dist/flickity.pkgd.min.js'

>2. import Flickity from 'flickity/dist/flickity.pkgd'

>3. import Flickity from 'flickity/js/index'

>4. import Flickity from 'flickity'

> 5. var Flickity = require('flickity')

> 6. import 'flickity'

> 7. import Flickity from 'https://unpkg.com/flickity@2.2.1/dist/flickity.pkgd.js';

I use 7 way like above but still, links open after drag end 

i use way 2 i got this error
``` error
Error: Could not resolve './cell' from node_modules\flickity\dist\flickity.pkgd.js
```

``` error 
'jquery' is imported by node_modules\flickity\dist\flickity.pkgd.js, but could not be resolved – treating it as an external dependency
'jquery' is imported by  jquery?commonjs-external, but could not be resolved – treating it as an external dependency
'imagesloaded' is imported by node_modules\flickity\dist\flickity.pkgd.js, but could not be resolved – treating it as an external dependency
'imagesloaded' is imported by  imagesloaded?commonjs-external, but could not be resolved – treating it as an external dependency
```
# and if I got no errors, the links will still be clicked while dragging
another qustion `flickity` depends on jquery or its vanilla js?

**Comment by riiccardo** [comment]
line: 2579 `flickity.pkgd.js`
``` js
proto._dragStart = function( event, pointer ) {
  this.isDragging = true;
  // prevent clicks
  this.isPreventingClicks = true;
  this.dragStart( event, pointer );
};

proto.dragStart = function( event, pointer ) {
  this.emitEvent( 'dragStart', [ event, pointer ] );
};
```


line: 2606

``` js
proto._dragEnd = function( event, pointer ) {
  // set flags
  this.isDragging = false;
  // re-enable clicking async
  setTimeout( function() {
    delete this.isPreventingClicks;
  }.bind( this ) );

  this.dragEnd( event, pointer );
};

proto.dragEnd = function( event, pointer ) {
  this.emitEvent( 'dragEnd', [ event, pointer ] );
};
```

line: 2624 

``` js
// handle all clicks and prevent clicks when dragging
proto.onclick = function( event ) {
  if ( this.isPreventingClicks ) {
    event.preventDefault();
  }
};
```

onclick does not prevent click on **`A`** TAG

**Comment by riiccardo** [comment]
@desandro pls add this issue to [flickity Events](https://flickity.metafizzy.co/events.html)

to get rid of this `horrible issue`

Regards and PLS

**Comment by fredericoo** [comment]
Late reply but I managed to solve it by setting these events (no jQuery):

```
flkty.on('dragStart', () => flkty.slider.childNodes.forEach(slide => slide.style.pointerEvents = "none") );
flkty.on('dragEnd', () => flkty.slider.childNodes.forEach(slide => slide.style.pointerEvents = "all") );
```

**Comment by jaygolbitz** [comment]
> Late reply but I managed to solve it by setting these events (no jQuery):
> 
> ```
> flkty.on('dragStart', () => flkty.slider.childNodes.forEach(slide => slide.style.pointerEvents = "none") );
> flkty.on('dragEnd', () => flkty.slider.childNodes.forEach(slide => slide.style.pointerEvents = "all") );
> ```

Where did you add this code? Thanks for any help!

**Comment by SakibAlIslam** [comment]
### Hey, I solved it for **Vanila Javascript**. You may check it.

`const elem = document.querySelector(`.${ID}__collectionsSlider`);
const flkty = new Flickity(elem, {
            contain: true,
            freeScroll: true,
            prevNextButtons: false,
            pageDots: false
  });

flkty.on('dragStart', () => flkty.slider.childNodes.forEach((slide) => {
    slide.style.pointerEvents = 'none';
}));
 flkty.on('dragEnd', () => flkty.slider.childNodes.forEach((slide) => {
    slide.style.pointerEvents = 'all';
}));
`

**ENJOY**
