### ISSUE TITLE
cellAlign to pixel value

### ISSUE THREAD

**Issue by adam-h** [metafizzy/flickity#99]
It's currently only possible to align to a percentage of the carousel area, but it would be really useful for some designs to be able to align to a pixel amount.

Example: http://codepen.io/anon/pen/YPgNLL

I would like to be able to align the leftmost edge of the current Flickity cell to the red boxes.

**Comment by desandro** [comment]
**+1** this issue if you would like to see this feature implemented.

My feel is that this is a small use case.

**Comment by mdmoreau** [comment]
http://codepen.io/anon/pen/raRwdL

I think you can get this working with some minor tweaks.  Set the .gallery horizontal padding to the same as the .alignto horizontal margin, then set flickity to use cellAlign: left and contain: true.  You can drop the contain: true if you don't want the last slide to align to the right edge.

If you want to have slides visible beyond the current gallery boundaries, you can use overflow: visible on .flickity-viewport.  Just did something similar on a project, so figured I'd pass it along.

**Comment by adam-h** [comment]
@mdmoreau Thanks, I had found a similar workaround myself after posting this. Still, could be a handy option and more discoverable.

**Comment by desandro** [comment]
Closing this feature request as its been quiet :ghost:
