### ISSUE TITLE
Init in JS but set some options for different carousels

### ISSUE THREAD

**Issue by cheeseytoastie** [metafizzy/flickity#994]
Is is possible to do something like?

 $carousel = $('.carousel').flickity({
        autoPlay: $(this.element).data('carousel-speed'),

where I've put (by setting a value in a CMS) a data attribute on the markup.

There are multiple carousels on the page so though it this works (setting a single div with a value) it's not suitable, how can I get to the carousel element in the initialisation?!

    $carousel = $('.carousel').flickity({
        autoPlay: $('.carousel-speed').data('carousel-speed'),

**Comment by desandro** [comment]
Yes, you can use [`each()`](url) to iterate though the carousel elements https://fizzy.school/un-repeat-with-functions

``` js
$('.carousel').each( function( i, carousel ) {
  let $carousel = $( carousel );
  $carousel.flickity({
    autoPlay: $carousel.data('carousel-speed');
  });
});
```

**Comment by cheeseytoastie** [comment]
They looks perfect. Thanks!
