### ISSUE TITLE
In specific cases, Flickity forces cell realignment when using freeScroll on mobile

### ISSUE THREAD

**Issue by Jac733** [metafizzy/flickity#995]
When using `freeScroll: true` and stopping in between two cells on mobile, any scrolling **that causes the browser's address bar to appear/disappear** will force the carousel to re-align to the nearest cell. **This does not happen with scrolling that does not affect the state of the browser's address bar**.

I'm assuming that because the height of the page is changing in a way, Flickity feels "forced" to re-align to a cell, but this defeats the purpose of `freeScroll`. Is there a way to prevent this behaviour?

This is reproducible on the Flickity Options page on mobile: https://flickity.metafizzy.co/options.html#freescroll

And visible on this video if you don't have a mobile nearby: https://photos.app.goo.gl/FkLwDbviR4UTxqNq5

**Comment by desandro** [comment]
Sorry, I am not able to reproduce this issue.
