### ISSUE TITLE
Slider does not scroll smoothly on mobile

### ISSUE THREAD

**Issue by UzairSalman** [metafizzy/flickity#998]
I've been using this plugin through Flatsome Theme for woocommerce. 
However I am having a huge issue regarding the swiping right/left on mobile to change the slider on main homepage. 

Link: dablew.pk 
(view on mobile, the main slider)

Please tell me a fix for this. Thanks

**Comment by fbnntt** [comment]
I'm having the exact same issue. A fix for this would be great.

**Comment by benabbottnz** [comment]
What kind of phone do you have? It scrolls smoothly for me.

**Comment by UzairSalman** [comment]
I tried it using multiple android phones, its not scrolling smoothly.

**Comment by UzairSalman** [comment]
I just tried it on iPhone 11 Pro Max and it wasn't sliding smoothly.

**Comment by XPOL555** [comment]
Hi @UzairSalman this might be related to this https://github.com/metafizzy/flickity/issues/959 and also this https://github.com/metafizzy/flickity/issues/740

**Comment by desandro** [comment]
Closing as a duplicate of #959
